# 10-Fold Non-Transformer GNN Training for CXR KG

This notebook tests non-transformer GNN models on the same 10-fold chest X-ray knowledge graph dataset used by the GraphSAGE and transformer-GNN experiments.

Ablations:

- `graphsage`: heterogeneous GraphSAGE via PyG `SAGEConv` inside `HeteroConv`.
- `gcn`: flattened heterogeneous graph with type-specific input projections and PyG `GCNConv` message passing.
- `gat`: heterogeneous graph attention via PyG `GATConv` inside `HeteroConv`.
- Query retrieval `top_k`: `50`, `100`, `200`, `500`.

Outputs are saved under `/data/liangz2/openi/multi_kg/kg_non_transformer_gnn_10fold/{model_name}/top_k_{k}/fold{fold}/`.

In [1]:
# Optional dependency installation. Set True only in a fresh cloud environment.
INSTALL_DEPS = False

if INSTALL_DEPS:
    import subprocess
    import sys
    packages = ["torch", "torch_geometric", "faiss-cpu", "scikit-learn", "pandas", "numpy", "tqdm"]
    subprocess.check_call([sys.executable, "-m", "pip", "install", *packages])

In [2]:
import copy
import json
import random
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
from tqdm.auto import tqdm

import torch
import torch.nn as nn
import torch.nn.functional as F

from sklearn.metrics import average_precision_score, f1_score, roc_auc_score

try:
    from torch_geometric.data import HeteroData
    from torch_geometric.nn import HeteroConv, SAGEConv, GCNConv, GATConv
except ImportError as exc:
    raise ImportError(
        "Install torch_geometric before running this notebook. "
        "In your diffuser2 environment, try: pip install torch_geometric faiss-cpu"
    ) from exc

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

DATA_ROOT = Path("/data/liangz2/openi/multi_kg") if Path("/data/liangz2/openi/multi_kg").exists() else Path.cwd()
KG_10FOLD_DIR = DATA_ROOT / "kg_10fold"
OUTPUT_ROOT = DATA_ROOT / "kg_non_transformer_gnn_10fold"
OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)

MODEL_NAMES = ["graphsage", "gcn", "gat"]
QUERY_TOP_K_VALUES = [50, 100, 200, 500]
FOLD_INDICES = list(range(10))

SKIP_COMPLETED = True
FORCE_RERUN = []  # Optional list of (model_name, top_k, fold), e.g. [("gat", 100, 0)]

VAL_FRAC = 0.10
HIDDEN_DIM = 256
NUM_LAYERS = 2
NUM_HEADS = 4
DROPOUT = 0.20
LR = 1e-3
WEIGHT_DECAY = 1e-4
EPOCHS = 100
PATIENCE = 12
GRAD_CLIP_NORM = 5.0
DECODER = "dot"  # "dot" or "mlp"

TEST_QUERY_BATCH_SIZE = 512
QUERY_INFERENCE_CHUNK_SIZE = 512

# Keep False for the primary experiment to prevent direct label-edge leakage.
INCLUDE_HAS_FINDING_IN_MESSAGE_PASSING = False

# GAT is attention-based and can use much more memory over image-image similarity edges.
# These defaults keep GraphSAGE/GCN comparable to prior settings and make GAT safer.
MODEL_CONFIGS = {
    "graphsage": {
        "hidden_dim": HIDDEN_DIM,
        "num_layers": NUM_LAYERS,
        "num_heads": 1,
        "dropout": DROPOUT,
        "max_train_similar_edges_per_node": None,
        "query_inference_chunk_size": 512,
    },
    "gcn": {
        "hidden_dim": HIDDEN_DIM,
        "num_layers": NUM_LAYERS,
        "num_heads": 1,
        "dropout": DROPOUT,
        "max_train_similar_edges_per_node": None,
        "query_inference_chunk_size": 512,
    },
    "gat": {
        "hidden_dim": 128,
        "num_layers": NUM_LAYERS,
        "num_heads": 2,
        "dropout": DROPOUT,
        "max_train_similar_edges_per_node": 100,
        "query_inference_chunk_size": 128,
    },
}


def get_model_config(model_name: str) -> Dict:
    base = {
        "hidden_dim": HIDDEN_DIM,
        "num_layers": NUM_LAYERS,
        "num_heads": 1,
        "dropout": DROPOUT,
        "max_train_similar_edges_per_node": None,
        "query_inference_chunk_size": QUERY_INFERENCE_CHUNK_SIZE,
    }
    base.update(MODEL_CONFIGS.get(model_name.lower(), {}))
    return base

SCORING_LABELS = (
    "normal",
    "enlarged cardiomediastinum", "cardiomegaly", "lung opacity", "lung lesion", "edema",
    "consolidation", "pneumonia", "atelectasis", "pneumothorax",
    "pleural effusion", "pleural other", "fracture", "support devices",
)
TARGET_COLUMNS = ["y_" + label.replace(" ", "_") for label in SCORING_LABELS]
FINDING_LABELS = SCORING_LABELS[1:]

print("DEVICE", DEVICE)
print("DATA_ROOT", DATA_ROOT)
print("KG_10FOLD_DIR", KG_10FOLD_DIR)
print("OUTPUT_ROOT", OUTPUT_ROOT)
print("MODEL_NAMES", MODEL_NAMES)
print("QUERY_TOP_K_VALUES", QUERY_TOP_K_VALUES)
print("INCLUDE_HAS_FINDING_IN_MESSAGE_PASSING", INCLUDE_HAS_FINDING_IN_MESSAGE_PASSING)

DEVICE cuda
DATA_ROOT /data/liangz2/openi/multi_kg
KG_10FOLD_DIR /data/liangz2/openi/multi_kg/kg_10fold
OUTPUT_ROOT /data/liangz2/openi/multi_kg/kg_non_transformer_gnn_10fold
MODEL_NAMES ['graphsage', 'gcn', 'gat']
QUERY_TOP_K_VALUES [50, 100, 200, 500]
INCLUDE_HAS_FINDING_IN_MESSAGE_PASSING False

## Metrics and Utility Functions

In [3]:
def sigmoid_np(logits: np.ndarray) -> np.ndarray:
    return 1.0 / (1.0 + np.exp(-logits))


def evaluate_prob_matrix(probs: np.ndarray, targets: np.ndarray, thresholds: Optional[np.ndarray] = None) -> pd.DataFrame:
    y = targets.astype(int)
    if thresholds is None:
        thresholds = np.full((probs.shape[1],), 0.5, dtype=np.float32)
    rows = []
    for j, label in enumerate(SCORING_LABELS):
        if len(np.unique(y[:, j])) < 2:
            continue
        pred = (probs[:, j] >= thresholds[j]).astype(int)
        rows.append({
            "label": label,
            "auroc": roc_auc_score(y[:, j], probs[:, j]),
            "auprc": average_precision_score(y[:, j], probs[:, j]),
            "f1": f1_score(y[:, j], pred, zero_division=0),
            "threshold": float(thresholds[j]),
            "support": int(y[:, j].sum()),
        })
    return pd.DataFrame(rows)


def macro_metric(metrics: pd.DataFrame, metric: str = "auroc", disease_only: bool = True) -> float:
    if metrics.empty:
        return float("nan")
    frame = metrics[metrics["label"] != "normal"] if disease_only else metrics
    if frame.empty:
        return float("nan")
    return float(frame[metric].mean())


def tune_f1_thresholds(probs: np.ndarray, targets: np.ndarray, grid: Optional[np.ndarray] = None) -> np.ndarray:
    if grid is None:
        grid = np.linspace(0.01, 0.99, 99)
    thresholds = np.full((probs.shape[1],), 0.5, dtype=np.float32)
    y = targets.astype(int)
    for j in range(probs.shape[1]):
        if len(np.unique(y[:, j])) < 2:
            continue
        best_f1, best_thr = -1.0, 0.5
        for thr in grid:
            pred = (probs[:, j] >= thr).astype(int)
            value = f1_score(y[:, j], pred, zero_division=0)
            if value > best_f1:
                best_f1, best_thr = value, float(thr)
        thresholds[j] = best_thr
    return thresholds


def metric_summary(metrics: pd.DataFrame, fold: int, method: str, extra: Optional[Dict] = None) -> Dict:
    disease = metrics[metrics["label"] != "normal"] if not metrics.empty else metrics
    out = {
        "fold": int(fold),
        "method": method,
        "disease_macro_auroc": float(disease["auroc"].mean()) if len(disease) else float("nan"),
        "disease_macro_auprc": float(disease["auprc"].mean()) if len(disease) else float("nan"),
        "disease_macro_f1": float(disease["f1"].mean()) if len(disease) else float("nan"),
        "all_macro_auroc": float(metrics["auroc"].mean()) if len(metrics) else float("nan"),
        "all_macro_auprc": float(metrics["auprc"].mean()) if len(metrics) else float("nan"),
        "all_macro_f1": float(metrics["f1"].mean()) if len(metrics) else float("nan"),
        "num_scored_labels": int(len(metrics)),
    }
    if extra:
        out.update(extra)
    return out


def save_json(obj: Dict, path: Path) -> None:
    path.write_text(json.dumps(obj, indent=2, default=str), encoding="utf-8")

## Load Fold Graphs

The fold graph is expected at `kg_10fold/fold{i}/kg_heterodata_fold{i}.pt`. Training image nodes already exist in the fold graph. Test images are appended as query nodes with `similar_to` retrieval edges only.

In [4]:
def torch_load_any(path: Path, map_location="cpu"):
    try:
        return torch.load(path, map_location=map_location, weights_only=False)
    except TypeError:
        return torch.load(path, map_location=map_location)


def dict_to_heterodata(obj: Dict) -> HeteroData:
    data = HeteroData()
    for node_type, x in obj.get("x_dict", {}).items():
        data[node_type].x = x.float()
        node_ids = obj.get("node_ids", {}).get(node_type)
        if node_ids is not None:
            data[node_type].node_id = list(node_ids)
        if node_type in obj.get("y_dict", {}):
            data[node_type].y = obj["y_dict"][node_type].float()
    for etype, edge_index in obj.get("edge_index_dict", {}).items():
        data[etype].edge_index = edge_index.long()
        edge_weight = obj.get("edge_weight_dict", {}).get(etype)
        if edge_weight is not None:
            data[etype].edge_weight = edge_weight.float()
    return data


def load_fold_data(fold: int) -> Tuple[HeteroData, pd.DataFrame, pd.DataFrame, np.ndarray]:
    fold_dir = KG_10FOLD_DIR / f"fold{fold}"
    kg_path = fold_dir / f"kg_heterodata_fold{fold}.pt"
    train_meta_path = fold_dir / f"train_metadata_fold{fold}.csv"
    test_meta_path = fold_dir / f"test_query_metadata_fold{fold}.csv"
    test_emb_path = fold_dir / f"test_query_embeddings_fold{fold}.npy"
    if not kg_path.exists():
        raise FileNotFoundError(f"Missing fold KG file: {kg_path}")
    obj = torch_load_any(kg_path, map_location="cpu")
    data = obj if isinstance(obj, HeteroData) else dict_to_heterodata(obj)
    train_df = pd.read_csv(train_meta_path)
    test_df = pd.read_csv(test_meta_path)
    test_embeddings = np.load(test_emb_path).astype("float32")
    return data, train_df, test_df, test_embeddings


def label_names_from_data(data: HeteroData) -> List[str]:
    if hasattr(data["label"], "label_name"):
        return [str(x) for x in data["label"].label_name]
    if hasattr(data["label"], "node_id"):
        names = []
        for node_id in data["label"].node_id:
            text = str(node_id)
            names.append(text.split("label::", 1)[-1] if text.startswith("label::") else text)
        return names
    raise RuntimeError("Label node names are missing from HeteroData. Regenerate KG with label_name/node_id metadata.")


def label_indices_for_scoring(data: HeteroData) -> List[int]:
    label_names = label_names_from_data(data)
    lookup = {name: i for i, name in enumerate(label_names)}
    missing = [label for label in SCORING_LABELS if label not in lookup]
    if missing:
        raise RuntimeError(f"Missing label nodes: {missing}. Available labels: {label_names}")
    return [lookup[label] for label in SCORING_LABELS]


def split_train_val_indices(num_images: int, val_frac: float, seed: int) -> Tuple[torch.Tensor, torch.Tensor]:
    rng = np.random.default_rng(seed)
    indices = np.arange(num_images)
    rng.shuffle(indices)
    val_size = max(1, int(round(num_images * val_frac)))
    val_idx = np.sort(indices[:val_size])
    train_idx = np.sort(indices[val_size:])
    return torch.from_numpy(train_idx).long(), torch.from_numpy(val_idx).long()

## Non-Transformer GNN Models

`GraphSAGE` and `GAT` are implemented as heterogeneous message passing using `HeteroConv` over the KG edge types. `GCNConv` does not support bipartite heterogeneous input directly, so `HeteroGCN` first projects each node type into a shared hidden dimension, flattens all node types into one homogeneous graph, applies true `GCNConv` layers, then unflattens the output back into node-type dictionaries for image-label decoding.

In [5]:
def merge_layer_output(prev_z: Dict[str, torch.Tensor], out_z: Dict[str, torch.Tensor], norm_dict: nn.ModuleDict, dropout: float, training: bool) -> Dict[str, torch.Tensor]:
    next_z = {}
    for node_type, x in prev_z.items():
        y = out_z.get(node_type)
        if y is None:
            next_z[node_type] = x
            continue
        y = F.relu(y)
        y = norm_dict[node_type](y)
        y = F.dropout(y, p=dropout, training=training)
        next_z[node_type] = x + y if x.shape == y.shape else y
    return next_z


class BaseImageLabelDecoder(nn.Module):
    def _init_decoder(self, hidden_dim: int, dropout: float, decoder: str):
        self.decoder = decoder
        if decoder == "mlp":
            self.decoder_mlp = nn.Sequential(
                nn.Linear(2 * hidden_dim, hidden_dim), nn.ReLU(), nn.Dropout(dropout), nn.Linear(hidden_dim, 1)
            )
        elif decoder != "dot":
            raise ValueError(f"Unknown decoder: {decoder}")

    def decode_image_label_logits(self, z_dict, label_indices: Sequence[int]) -> torch.Tensor:
        image_z = z_dict["image"]
        label_z = z_dict["label"][torch.as_tensor(label_indices, device=image_z.device)]
        if self.decoder == "dot":
            return image_z @ label_z.t()
        image_expanded = image_z[:, None, :].expand(-1, len(label_indices), -1)
        label_expanded = label_z[None, :, :].expand(image_z.size(0), -1, -1)
        pair = torch.cat([image_expanded, label_expanded], dim=-1)
        return self.decoder_mlp(pair).squeeze(-1)


class HeteroGraphSAGE(BaseImageLabelDecoder):
    def __init__(self, metadata, input_dims: Dict[str, int], hidden_dim=HIDDEN_DIM, num_layers=NUM_LAYERS, heads=1, dropout=DROPOUT, decoder=DECODER):
        super().__init__()
        node_types, edge_types = metadata
        self.dropout = dropout
        self.proj = nn.ModuleDict({node_type: nn.Linear(int(input_dims[node_type]), hidden_dim) for node_type in node_types if node_type in input_dims})
        self.convs = nn.ModuleList()
        self.norms = nn.ModuleList()
        for _ in range(num_layers):
            conv = HeteroConv({edge_type: SAGEConv((hidden_dim, hidden_dim), hidden_dim) for edge_type in edge_types}, aggr="sum")
            self.convs.append(conv)
            self.norms.append(nn.ModuleDict({node_type: nn.LayerNorm(hidden_dim) for node_type in self.proj}))
        self._init_decoder(hidden_dim, dropout, decoder)

    def forward(self, x_dict, edge_index_dict):
        z = {node_type: F.relu(self.proj[node_type](x.float())) for node_type, x in x_dict.items() if node_type in self.proj}
        for conv, norm_dict in zip(self.convs, self.norms):
            out = conv(z, edge_index_dict)
            z = merge_layer_output(z, out, norm_dict, self.dropout, self.training)
        return z


class HeteroGAT(BaseImageLabelDecoder):
    def __init__(self, metadata, input_dims: Dict[str, int], hidden_dim=128, num_layers=NUM_LAYERS, heads=2, dropout=DROPOUT, decoder=DECODER):
        super().__init__()
        node_types, edge_types = metadata
        self.dropout = dropout
        self.proj = nn.ModuleDict({node_type: nn.Linear(int(input_dims[node_type]), hidden_dim) for node_type in node_types if node_type in input_dims})
        self.convs = nn.ModuleList()
        self.norms = nn.ModuleList()
        for _ in range(num_layers):
            conv = HeteroConv({
                edge_type: GATConv((hidden_dim, hidden_dim), hidden_dim, heads=heads, concat=False, dropout=dropout, add_self_loops=False)
                for edge_type in edge_types
            }, aggr="sum")
            self.convs.append(conv)
            self.norms.append(nn.ModuleDict({node_type: nn.LayerNorm(hidden_dim) for node_type in self.proj}))
        self._init_decoder(hidden_dim, dropout, decoder)

    def forward(self, x_dict, edge_index_dict):
        z = {node_type: F.relu(self.proj[node_type](x.float())) for node_type, x in x_dict.items() if node_type in self.proj}
        for conv, norm_dict in zip(self.convs, self.norms):
            out = conv(z, edge_index_dict)
            z = merge_layer_output(z, out, norm_dict, self.dropout, self.training)
        return z


class HeteroGCN(BaseImageLabelDecoder):
    def __init__(self, metadata, input_dims: Dict[str, int], hidden_dim=HIDDEN_DIM, num_layers=NUM_LAYERS, heads=1, dropout=DROPOUT, decoder=DECODER):
        super().__init__()
        node_types, _ = metadata
        self.node_types = [node_type for node_type in node_types if node_type in input_dims]
        self.dropout = dropout
        self.proj = nn.ModuleDict({node_type: nn.Linear(int(input_dims[node_type]), hidden_dim) for node_type in self.node_types})
        self.convs = nn.ModuleList([GCNConv(hidden_dim, hidden_dim, add_self_loops=True, normalize=True) for _ in range(num_layers)])
        self.norm = nn.LayerNorm(hidden_dim)
        self._init_decoder(hidden_dim, dropout, decoder)

    def flatten_graph(self, z: Dict[str, torch.Tensor], edge_index_dict: Dict) -> Tuple[torch.Tensor, torch.Tensor, Dict[str, Tuple[int, int]]]:
        offsets = {}
        chunks = []
        start = 0
        for node_type in self.node_types:
            x = z[node_type]
            end = start + x.size(0)
            offsets[node_type] = (start, end)
            chunks.append(x)
            start = end
        homo_x = torch.cat(chunks, dim=0)
        edge_chunks = []
        for (src_type, _, dst_type), edge_index in edge_index_dict.items():
            if src_type not in offsets or dst_type not in offsets:
                continue
            src_offset = offsets[src_type][0]
            dst_offset = offsets[dst_type][0]
            ei = edge_index.clone()
            ei = ei.to(homo_x.device)
            ei[0] = ei[0] + src_offset
            ei[1] = ei[1] + dst_offset
            edge_chunks.append(ei)
        if edge_chunks:
            homo_edge_index = torch.cat(edge_chunks, dim=1)
        else:
            homo_edge_index = torch.empty((2, 0), dtype=torch.long, device=homo_x.device)
        return homo_x, homo_edge_index, offsets

    def unflatten(self, homo_x: torch.Tensor, offsets: Dict[str, Tuple[int, int]]) -> Dict[str, torch.Tensor]:
        return {node_type: homo_x[start:end] for node_type, (start, end) in offsets.items()}

    def forward(self, x_dict, edge_index_dict):
        z = {node_type: F.relu(self.proj[node_type](x.float())) for node_type, x in x_dict.items() if node_type in self.proj}
        homo_x, homo_edge_index, offsets = self.flatten_graph(z, edge_index_dict)
        h = homo_x
        for conv in self.convs:
            y = conv(h, homo_edge_index)
            y = F.relu(y)
            y = self.norm(y)
            y = F.dropout(y, p=self.dropout, training=self.training)
            h = h + y if h.shape == y.shape else y
        return self.unflatten(h, offsets)


def build_model(model_name: str, metadata, input_dims: Dict[str, int], cfg: Optional[Dict] = None):
    model_name = model_name.lower()
    cfg = cfg or get_model_config(model_name)
    kwargs = {
        "hidden_dim": int(cfg["hidden_dim"]),
        "num_layers": int(cfg["num_layers"]),
        "heads": int(cfg["num_heads"]),
        "dropout": float(cfg["dropout"]),
        "decoder": DECODER,
    }
    if model_name == "graphsage":
        return HeteroGraphSAGE(metadata, input_dims, **kwargs)
    if model_name == "gcn":
        return HeteroGCN(metadata, input_dims, **kwargs)
    if model_name == "gat":
        return HeteroGAT(metadata, input_dims, **kwargs)
    raise ValueError(f"Unknown model_name={model_name}. Expected one of: graphsage, gcn, gat")


def keep_first_edges_per_src(edge_index: torch.Tensor, max_edges_per_src: Optional[int]) -> torch.Tensor:
    if max_edges_per_src is None or max_edges_per_src <= 0 or edge_index.numel() == 0:
        return torch.arange(edge_index.size(1), dtype=torch.long)
    src_nodes = edge_index[0].cpu().tolist()
    counts = {}
    keep = []
    for col, src in enumerate(src_nodes):
        used = counts.get(src, 0)
        if used < max_edges_per_src:
            keep.append(col)
            counts[src] = used + 1
    return torch.tensor(keep, dtype=torch.long)


def cap_similar_edges_in_data(data: HeteroData, max_edges_per_src: Optional[int]) -> HeteroData:
    if max_edges_per_src is None:
        return data
    for edge_type in [("image", "similar_to", "image"), ("image", "rev_similar_to", "image")]:
        if edge_type not in data.edge_types or not hasattr(data[edge_type], "edge_index"):
            continue
        edge_index = data[edge_type].edge_index.cpu()
        keep = keep_first_edges_per_src(edge_index, max_edges_per_src)
        old_edges = edge_index.size(1)
        data[edge_type].edge_index = edge_index[:, keep]
        if hasattr(data[edge_type], "edge_weight"):
            data[edge_type].edge_weight = data[edge_type].edge_weight.cpu()[keep]
        print(f"Capped {edge_type}: {old_edges} -> {data[edge_type].edge_index.size(1)} edges")
    return data


def message_passing_edge_index_dict(data: HeteroData, include_has_finding: bool = INCLUDE_HAS_FINDING_IN_MESSAGE_PASSING):
    edge_dict = {}
    for edge_type in data.edge_types:
        relation = edge_type[1]
        if not include_has_finding and (relation == "has_finding" or relation == "rev_has_finding"):
            continue
        if hasattr(data[edge_type], "edge_index"):
            edge_dict[edge_type] = data[edge_type].edge_index
    return edge_dict


def input_dims_from_data(data: HeteroData) -> Dict[str, int]:
    return {node_type: int(data[node_type].x.size(-1)) for node_type in data.node_types if hasattr(data[node_type], "x")}


def pos_weight_from_targets(y: torch.Tensor) -> torch.Tensor:
    pos = y.sum(dim=0)
    neg = y.size(0) - pos
    return torch.clamp(neg / torch.clamp(pos, min=1.0), min=1.0, max=50.0)

## Query Graph Construction

Each test image is added as a query node connected to its top-k nearest training image nodes through `similar_to` edges. Query `has_finding` edges are never added. Inference is chunked to avoid GPU memory spikes.

In [6]:
def l2_normalize_np(x: np.ndarray, eps: float = 1e-12) -> np.ndarray:
    return (x / np.maximum(np.linalg.norm(x, axis=1, keepdims=True), eps)).astype("float32")


def topk_inner_product(train_embeddings: np.ndarray, query_embeddings: np.ndarray, top_k: int, batch_size: int = TEST_QUERY_BATCH_SIZE):
    train = l2_normalize_np(train_embeddings.astype("float32"))
    query = l2_normalize_np(query_embeddings.astype("float32"))
    all_sims, all_idx = [], []
    try:
        import faiss
        index = faiss.IndexFlatIP(train.shape[1])
        index.add(np.ascontiguousarray(train))
        for start in tqdm(range(0, len(query), batch_size), desc=f"query FAISS top_k={top_k}"):
            sims, idx = index.search(np.ascontiguousarray(query[start:start + batch_size]), min(top_k, len(train)))
            all_sims.append(sims.astype("float32"))
            all_idx.append(idx.astype("int64"))
    except ImportError:
        for start in tqdm(range(0, len(query), batch_size), desc=f"query dense top_k={top_k}"):
            scores = query[start:start + batch_size] @ train.T
            kth = min(top_k, scores.shape[1]) - 1
            idx = np.argpartition(-scores, kth=kth, axis=1)[:, :top_k]
            sorted_order = np.take_along_axis(scores, idx, axis=1).argsort(axis=1)[:, ::-1]
            idx = np.take_along_axis(idx, sorted_order, axis=1)
            sims = np.take_along_axis(scores, idx, axis=1)
            all_sims.append(sims.astype("float32"))
            all_idx.append(idx.astype("int64"))
    return np.concatenate(all_sims, axis=0), np.concatenate(all_idx, axis=0)


def append_edge_index(data: HeteroData, edge_type, edge_index_new: torch.Tensor, edge_weight_new: Optional[torch.Tensor] = None):
    store = data[edge_type]
    if hasattr(store, "edge_index"):
        store.edge_index = torch.cat([store.edge_index.cpu(), edge_index_new.cpu()], dim=1)
    else:
        store.edge_index = edge_index_new.cpu()
    if edge_weight_new is not None:
        if hasattr(store, "edge_weight"):
            store.edge_weight = torch.cat([store.edge_weight.cpu(), edge_weight_new.cpu()], dim=0)
        else:
            store.edge_weight = edge_weight_new.cpu()


def target_matrix_from_metadata(frame: pd.DataFrame) -> np.ndarray:
    missing = [col for col in TARGET_COLUMNS if col not in frame.columns]
    if missing:
        raise RuntimeError(f"Missing target columns in metadata: {missing}")
    return frame[TARGET_COLUMNS].to_numpy(dtype=np.float32)


def append_query_chunk_to_graph(data: HeteroData, query_embeddings: np.ndarray, query_targets: np.ndarray, neighbor_idx: np.ndarray, neighbor_sims: np.ndarray) -> Tuple[HeteroData, int]:
    query_data = copy.deepcopy(data).cpu()
    train_count = int(query_data["image"].x.size(0))
    query_data["image"].x = torch.cat([query_data["image"].x.float(), torch.from_numpy(query_embeddings).float()], dim=0)
    if hasattr(query_data["image"], "y"):
        query_data["image"].y = torch.cat([query_data["image"].y.float(), torch.from_numpy(query_targets).float()], dim=0)
    else:
        query_data["image"].y = torch.from_numpy(query_targets).float()

    src, dst, weights = [], [], []
    for qi in range(neighbor_idx.shape[0]):
        query_node = train_count + qi
        for rank in range(neighbor_idx.shape[1]):
            src.append(query_node)
            dst.append(int(neighbor_idx[qi, rank]))
            weights.append(float(neighbor_sims[qi, rank]))
    edge_index = torch.tensor([src, dst], dtype=torch.long)
    edge_weight = torch.tensor(weights, dtype=torch.float32)
    append_edge_index(query_data, ("image", "similar_to", "image"), edge_index, edge_weight)
    append_edge_index(query_data, ("image", "rev_similar_to", "image"), edge_index.flip(0), edge_weight)
    return query_data, train_count


def predict_test_queries(model: nn.Module, data_cpu: HeteroData, test_df: pd.DataFrame, test_embeddings: np.ndarray, top_k: int, label_indices: Sequence[int], chunk_size: int = QUERY_INFERENCE_CHUNK_SIZE) -> Tuple[np.ndarray, np.ndarray]:
    train_embeddings = data_cpu["image"].x.cpu().numpy().astype("float32")
    test_targets = target_matrix_from_metadata(test_df)
    sims, idx = topk_inner_product(train_embeddings, test_embeddings, top_k=top_k)
    probs_chunks = []
    model.eval()
    for start in tqdm(range(0, len(test_embeddings), chunk_size), desc=f"test query chunks top_k={top_k}"):
        end = min(start + chunk_size, len(test_embeddings))
        query_data, train_count = append_query_chunk_to_graph(
            data_cpu,
            test_embeddings[start:end],
            test_targets[start:end],
            idx[start:end],
            sims[start:end],
        )
        query_edges = message_passing_edge_index_dict(query_data, include_has_finding=INCLUDE_HAS_FINDING_IN_MESSAGE_PASSING)
        query_data = query_data.to(DEVICE)
        query_edges = {etype: edge_index.to(DEVICE) for etype, edge_index in query_edges.items()}
        with torch.no_grad():
            z = model(query_data.x_dict, query_edges)
            query_logits_all = model.decode_image_label_logits(z, label_indices)
            logits = query_logits_all[train_count:train_count + (end - start)].detach().cpu().numpy().astype("float32")
            probs_chunks.append(sigmoid_np(logits))
        del query_data, query_edges, z, query_logits_all
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    return np.concatenate(probs_chunks, axis=0), test_targets

## Train and Evaluate One Fold

In [7]:
def experiment_root(model_name: str, query_top_k: int) -> Path:
    root = OUTPUT_ROOT / model_name / f"top_k_{query_top_k}"
    root.mkdir(parents=True, exist_ok=True)
    return root


def fold_dirs(model_name: str, query_top_k: int, fold: int) -> Dict[str, Path]:
    root = experiment_root(model_name, query_top_k) / f"fold{fold}"
    dirs = {
        "root": root,
        "models": root / "models",
        "metrics": root / "metrics",
        "predictions": root / "predictions",
        "logs": root / "logs",
    }
    for path in dirs.values():
        path.mkdir(parents=True, exist_ok=True)
    return dirs


def fold_complete(model_name: str, query_top_k: int, fold: int, dirs: Dict[str, Path]) -> bool:
    metrics_file = dirs["metrics"] / f"{model_name}_test_metrics.csv"
    tuned_file = dirs["metrics"] / f"{model_name}_test_metrics_val_tuned_thresholds.csv"
    return (dirs["root"] / "FOLD_COMPLETE.json").exists() and metrics_file.exists() and tuned_file.exists()


def save_predictions(path: Path, test_df: pd.DataFrame, probs: np.ndarray, targets: np.ndarray) -> pd.DataFrame:
    rows = []
    for i, row in test_df.reset_index(drop=True).iterrows():
        out = {
            "study_id": str(row.get("study_id", "")),
            "subject_id": str(row.get("subject_id", "")),
            "image_path": str(row.get("image_path", "")),
        }
        for j, label in enumerate(SCORING_LABELS):
            out[f"prob_{label}"] = float(probs[i, j])
            out[f"target_{label}"] = int(targets[i, j] >= 0.5)
        rows.append(out)
    pred_df = pd.DataFrame(rows)
    pred_df.to_csv(path, index=False)
    return pred_df


def train_one_fold(model_name: str, query_top_k: int, fold: int) -> List[Dict]:
    model_name = model_name.lower()
    method_name = f"hetero_{model_name}"
    dirs = fold_dirs(model_name, query_top_k, fold)
    force_key = (model_name, int(query_top_k), int(fold))
    if SKIP_COMPLETED and force_key not in FORCE_RERUN and fold_complete(model_name, query_top_k, fold, dirs):
        print(f"{model_name} top_k={query_top_k} fold={fold}: already complete, skipping.")
        summary_csv = dirs["metrics"] / f"{model_name}_method_summary.csv"
        if summary_csv.exists():
            return pd.read_csv(summary_csv).to_dict(orient="records")
        summary_path = dirs["metrics"] / f"{model_name}_summary.json"
        return list(json.loads(summary_path.read_text()).values()) if summary_path.exists() else [{"fold": fold, "skipped": True}]

    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    cfg = get_model_config(model_name)
    print(f"Config for {model_name}:", cfg)

    data, train_df, test_df, test_embeddings = load_fold_data(fold)
    data = cap_similar_edges_in_data(data, cfg.get("max_train_similar_edges_per_node"))
    label_indices = label_indices_for_scoring(data)
    if not hasattr(data["image"], "y"):
        raise RuntimeError("data['image'].y is missing. Regenerate fold KG with train labels.")

    num_images = int(data["image"].x.size(0))
    train_idx, val_idx = split_train_val_indices(num_images, VAL_FRAC, seed=SEED + fold)
    y = data["image"].y.float()
    train_y = y[train_idx]
    val_y = y[val_idx]
    pos_weight = pos_weight_from_targets(train_y).to(DEVICE)

    mp_edges = message_passing_edge_index_dict(data, include_has_finding=INCLUDE_HAS_FINDING_IN_MESSAGE_PASSING)
    metadata = (data.node_types, list(mp_edges.keys()))
    input_dims = input_dims_from_data(data)

    data = data.to(DEVICE)
    mp_edges = {etype: edge_index.to(DEVICE) for etype, edge_index in mp_edges.items()}

    model = build_model(model_name, metadata=metadata, input_dims=input_dims, cfg=cfg).to(DEVICE)
    optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
    criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)

    best_score = -float("inf")
    best_state = None
    best_epoch = -1
    stale_epochs = 0
    logs = []

    train_idx_dev = train_idx.to(DEVICE)
    val_idx_dev = val_idx.to(DEVICE)

    for epoch in range(EPOCHS):
        model.train()
        optimizer.zero_grad(set_to_none=True)
        z = model(data.x_dict, mp_edges)
        logits = model.decode_image_label_logits(z, label_indices)
        loss = criterion(logits[train_idx_dev], data["image"].y[train_idx_dev].float())
        loss.backward()
        if GRAD_CLIP_NORM is not None:
            torch.nn.utils.clip_grad_norm_(model.parameters(), GRAD_CLIP_NORM)
        optimizer.step()

        model.eval()
        with torch.no_grad():
            z = model(data.x_dict, mp_edges)
            logits = model.decode_image_label_logits(z, label_indices)
            val_logits = logits[val_idx_dev].detach().cpu().numpy().astype("float32")
            val_probs = sigmoid_np(val_logits)
            val_metrics = evaluate_prob_matrix(val_probs, val_y.numpy())
            val_macro_auroc = macro_metric(val_metrics, "auroc", disease_only=True)
            train_logits = logits[train_idx_dev].detach().cpu().numpy().astype("float32")
            train_probs = sigmoid_np(train_logits)
            train_metrics = evaluate_prob_matrix(train_probs, train_y.numpy())
            train_macro_auroc = macro_metric(train_metrics, "auroc", disease_only=True)

        log_row = {
            "fold": int(fold),
            "model_name": model_name,
            "query_top_k": int(query_top_k),
            "epoch": int(epoch),
            "loss": float(loss.detach().cpu()),
            "train_disease_macro_auroc": float(train_macro_auroc),
            "val_disease_macro_auroc": float(val_macro_auroc),
        }
        logs.append(log_row)
        print(f"model={model_name} top_k={query_top_k} fold={fold} epoch={epoch} loss={log_row['loss']:.4f} val_auc={val_macro_auroc:.4f}")

        if np.isfinite(val_macro_auroc) and val_macro_auroc > best_score:
            best_score = float(val_macro_auroc)
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            best_epoch = int(epoch)
            stale_epochs = 0
        else:
            stale_epochs += 1
        if stale_epochs >= PATIENCE:
            print(f"{model_name} top_k={query_top_k} fold={fold}: early stopping at epoch {epoch}")
            break

    if best_state is not None:
        model.load_state_dict(best_state)
    pd.DataFrame(logs).to_csv(dirs["logs"] / f"{model_name}_training_log.csv", index=False)

    model.eval()
    with torch.no_grad():
        z = model(data.x_dict, mp_edges)
        all_logits = model.decode_image_label_logits(z, label_indices)
        val_probs = sigmoid_np(all_logits[val_idx_dev].detach().cpu().numpy().astype("float32"))
    thresholds = tune_f1_thresholds(val_probs, val_y.numpy())
    pd.DataFrame({"label": SCORING_LABELS, "threshold": thresholds}).to_csv(dirs["metrics"] / f"{model_name}_val_f1_thresholds.csv", index=False)

    data_cpu, _, test_df, test_embeddings = load_fold_data(fold)
    data_cpu = cap_similar_edges_in_data(data_cpu, cfg.get("max_train_similar_edges_per_node"))
    test_probs, test_targets = predict_test_queries(
        model,
        data_cpu,
        test_df,
        test_embeddings,
        top_k=query_top_k,
        label_indices=label_indices,
        chunk_size=int(cfg.get("query_inference_chunk_size", QUERY_INFERENCE_CHUNK_SIZE)),
    )

    metrics_fixed = evaluate_prob_matrix(test_probs, test_targets)
    metrics_tuned = evaluate_prob_matrix(test_probs, test_targets, thresholds=thresholds)
    fixed_metrics_path = dirs["metrics"] / f"{model_name}_test_metrics.csv"
    tuned_metrics_path = dirs["metrics"] / f"{model_name}_test_metrics_val_tuned_thresholds.csv"
    metrics_fixed.to_csv(fixed_metrics_path, index=False)
    metrics_tuned.to_csv(tuned_metrics_path, index=False)
    save_predictions(dirs["predictions"] / f"{model_name}_test_predictions.csv", test_df, test_probs, test_targets)

    model_path = dirs["models"] / f"hetero_{model_name}_fold{fold}_topk{query_top_k}.pt"
    torch.save({
        "state_dict": model.state_dict(),
        "fold": int(fold),
        "model_name": model_name,
        "labels": list(SCORING_LABELS),
        "label_indices": list(label_indices),
        "input_dims": input_dims,
        "hidden_dim": int(cfg["hidden_dim"]),
        "num_layers": int(cfg["num_layers"]),
        "num_heads": int(cfg["num_heads"]),
        "max_train_similar_edges_per_node": cfg.get("max_train_similar_edges_per_node"),
        "dropout": float(cfg["dropout"]),
        "decoder": DECODER,
        "include_has_finding_in_message_passing": INCLUDE_HAS_FINDING_IN_MESSAGE_PASSING,
        "query_top_k": int(query_top_k),
        "best_epoch": int(best_epoch),
        "best_val_disease_macro_auroc": float(best_score),
    }, model_path)

    common_extra = {
        "model_name": model_name,
        "query_top_k": int(query_top_k),
        "include_has_finding_in_message_passing": bool(INCLUDE_HAS_FINDING_IN_MESSAGE_PASSING),
        "model_path": str(model_path),
        "best_epoch": int(best_epoch),
        "best_val_disease_macro_auroc": float(best_score),
        "hidden_dim": int(cfg["hidden_dim"]),
        "num_layers": int(cfg["num_layers"]),
        "num_heads": int(cfg["num_heads"]),
        "max_train_similar_edges_per_node": cfg.get("max_train_similar_edges_per_node"),
    }
    summary = metric_summary(metrics_fixed, fold, method_name, extra={
        **common_extra,
        "threshold_mode": "fixed_0.5",
        "metrics_path": str(fixed_metrics_path),
    })
    summary_tuned = metric_summary(metrics_tuned, fold, method_name, extra={
        **common_extra,
        "threshold_mode": "val_tuned_f1",
        "metrics_path": str(tuned_metrics_path),
    })
    pd.DataFrame([summary, summary_tuned]).to_csv(dirs["metrics"] / f"{model_name}_method_summary.csv", index=False)
    save_json({"fixed_0.5": summary, "val_tuned_f1": summary_tuned}, dirs["metrics"] / f"{model_name}_summary.json")
    save_json({
        "fold": int(fold),
        "status": "complete",
        "model_name": model_name,
        "query_top_k": int(query_top_k),
        "model_path": str(model_path),
    }, dirs["root"] / "FOLD_COMPLETE.json")
    return [summary, summary_tuned]

## Run 10-Fold Ablations

This cell runs `3 models × 4 top_k values × 10 folds`. Because `SKIP_COMPLETED=True`, it is safe to interrupt and resume.

In [8]:
all_summaries = []

for model_name in MODEL_NAMES:
    for query_top_k in QUERY_TOP_K_VALUES:
        print(f"\n######## Model={model_name} top_k={query_top_k} ########")
        run_rows = []
        run_root = experiment_root(model_name, query_top_k)
        for fold in FOLD_INDICES:
            print(f"\n===== Model={model_name} top_k={query_top_k} fold={fold} =====")
            rows = train_one_fold(model_name, query_top_k, fold)
            run_rows.extend(rows)
            all_summaries.extend(rows)
            pd.DataFrame(run_rows).to_csv(run_root / f"{model_name}_topk{query_top_k}_10fold_summary_progress.csv", index=False)
            pd.DataFrame(all_summaries).to_csv(OUTPUT_ROOT / "non_transformer_gnn_10fold_all_results_progress.csv", index=False)
        pd.DataFrame(run_rows).to_csv(run_root / f"{model_name}_topk{query_top_k}_10fold_summary.csv", index=False)

all_results_df = pd.DataFrame(all_summaries)
all_results_df.to_csv(OUTPUT_ROOT / "non_transformer_gnn_10fold_all_results.csv", index=False)
display(all_results_df)

######## Model=graphsage top_k=50 ########

===== Model=graphsage top_k=50 fold=0 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=50 fold=0 epoch=0 loss=19.2190 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=50 fold=0 epoch=1 loss=180.0505 val_auc=0.5345

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=50 fold=0 epoch=2 loss=32.0003 val_auc=0.7287
model=graphsage top_k=50 fold=0 epoch=3 loss=39.0267 val_auc=0.6703
model=graphsage top_k=50 fold=0 epoch=4 loss=20.6012 val_auc=0.7563
model=graphsage top_k=50 fold=0 epoch=5 loss=16.5173 val_auc=0.6406
model=graphsage top_k=50 fold=0 epoch=6 loss=19.6762 val_auc=0.7671
model=graphsage top_k=50 fold=0 epoch=7 loss=10.8799 val_auc=0.7794
model=graphsage top_k=50 fold=0 epoch=8 loss=11.6654 val_auc=0.6710
model=graphsage top_k=50 fold=0 epoch=9 loss=19.4984 val_auc=0.7460
model=graphsage top_k=50 fold=0 epoch=10 loss=11.3335 val_auc=0.7814
model=graphsage top_k=50 fold=0 epoch=11 loss=18.2126 val_auc=0.7809
model=graphsage top_k=50 fold=0 epoch=12 loss=14.5517 val_auc=0.7786
model=graphsage top_k=50 fold=0 epoch=13 loss=9.5377 val_auc=0.5484
model=graphsage top_k=50 fold=0 epoch=14 loss=30.4501 val_auc=0.5040
model=graphsage top_k=50 fold=0 epoch=15 loss=37.8798 val_auc=0.6135
model=graphsage top_k=50 fold=0 epoch=16 loss=20.3118 val_auc=0.7882
model=graphsage top_k=50 fold=0 epoch=17 loss=9.2655 val_auc=0.7906
model=graphsage top_k=50 fold=0 epoch=18 loss=22.3699 val_auc=0.7914
model=graphsage top_k=50 fold=0 epoch=19 loss=37.3825 val_auc=0.7916
model=graphsage top_k=50 fold=0 epoch=20 loss=27.3231 val_auc=0.7910
model=graphsage top_k=50 fold=0 epoch=21 loss=16.9371 val_auc=0.7839
model=graphsage top_k=50 fold=0 epoch=22 loss=12.1876 val_auc=0.7436
model=graphsage top_k=50 fold=0 epoch=23 loss=15.7487 val_auc=0.7591
model=graphsage top_k=50 fold=0 epoch=24 loss=17.5915 val_auc=0.7884
model=graphsage top_k=50 fold=0 epoch=25 loss=9.5446 val_auc=0.7920
model=graphsage top_k=50 fold=0 epoch=26 loss=11.6457 val_auc=0.7928
model=graphsage top_k=50 fold=0 epoch=27 loss=15.3459 val_auc=0.7936
model=graphsage top_k=50 fold=0 epoch=28 loss=12.1543 val_auc=0.7939
model=graphsage top_k=50 fold=0 epoch=29 loss=7.6901 val_auc=0.7902
model=graphsage top_k=50 fold=0 epoch=30 loss=10.0957 val_auc=0.7908
model=graphsage top_k=50 fold=0 epoch=31 loss=9.1023 val_auc=0.7990
model=graphsage top_k=50 fold=0 epoch=32 loss=7.2729 val_auc=0.8010
model=graphsage top_k=50 fold=0 epoch=33 loss=8.1575 val_auc=0.8026
model=graphsage top_k=50 fold=0 epoch=34 loss=7.7514 val_auc=0.8037
model=graphsage top_k=50 fold=0 epoch=35 loss=7.2860 val_auc=0.8015
model=graphsage top_k=50 fold=0 epoch=36 loss=9.2851 val_auc=0.7882
model=graphsage top_k=50 fold=0 epoch=37 loss=14.3306 val_auc=0.7999
model=graphsage top_k=50 fold=0 epoch=38 loss=8.0208 val_auc=0.8046
model=graphsage top_k=50 fold=0 epoch=39 loss=7.1982 val_auc=0.8053
model=graphsage top_k=50 fold=0 epoch=40 loss=6.7742 val_auc=0.8065
model=graphsage top_k=50 fold=0 epoch=41 loss=7.1476 val_auc=0.8082
model=graphsage top_k=50 fold=0 epoch=42 loss=7.8577 val_auc=0.8090
model=graphsage top_k=50 fold=0 epoch=43 loss=7.7875 val_auc=0.8098
model=graphsage top_k=50 fold=0 epoch=44 loss=6.3409 val_auc=0.8102
model=graphsage top_k=50 fold=0 epoch=45 loss=7.8294 val_auc=0.8104
model=graphsage top_k=50 fold=0 epoch=46 loss=6.7377 val_auc=0.8099
model=graphsage top_k=50 fold=0 epoch=47 loss=7.0516 val_auc=0.8100
model=graphsage top_k=50 fold=0 epoch=48 loss=8.8175 val_auc=0.8107
model=graphsage top_k=50 fold=0 epoch=49 loss=5.3341 val_auc=0.8114
model=graphsage top_k=50 fold=0 epoch=50 loss=5.5368 val_auc=0.8124
model=graphsage top_k=50 fold=0 epoch=51 loss=5.4901 val_auc=0.8136
model=graphsage top_k=50 fold=0 epoch=52 loss=5.8333 val_auc=0.8146
model=graphsage top_k=50 fold=0 epoch=53 loss=6.3128 val_auc=0.8151
model=graphsage top_k=50 fold=0 epoch=54 loss=7.6317 val_auc=0.8147
model=graphsage top_k=50 fold=0 epoch=55 loss=7.8761 val_auc=0.8143
model=graphsage top_k=50 fold=0 epoch=56 loss=6.5505 val_auc=0.8134
model=graphsage top_k=50 fold=0 epoch=57 loss=7.8312 val_auc=0.8129
model=graphsage top_k=50 fold=0 epoch=58 loss=8.3010 val_auc=0.8145
model=graphsage top_k=50 fold=0 epoch=59 loss=5.2110 val_auc=0.8149
model=graphsage top_k=50 fold=0 epoch=60 loss=5.8290 val_auc=0.8150
model=graphsage top_k=50 fold=0 epoch=61 loss=7.6285 val_auc=0.8151
model=graphsage top_k=50 fold=0 epoch=62 loss=5.9892 val_auc=0.8146
model=graphsage top_k=50 fold=0 epoch=63 loss=6.8077 val_auc=0.8106
model=graphsage top_k=50 fold=0 epoch=64 loss=7.5645 val_auc=0.8141
model=graphsage top_k=50 fold=0 epoch=65 loss=5.9502 val_auc=0.8152
model=graphsage top_k=50 fold=0 epoch=66 loss=6.1138 val_auc=0.8152
model=graphsage top_k=50 fold=0 epoch=67 loss=6.9320 val_auc=0.8154
model=graphsage top_k=50 fold=0 epoch=68 loss=5.0888 val_auc=0.8136
model=graphsage top_k=50 fold=0 epoch=69 loss=5.5725 val_auc=0.8108
model=graphsage top_k=50 fold=0 epoch=70 loss=6.6538 val_auc=0.8161
model=graphsage top_k=50 fold=0 epoch=71 loss=6.1034 val_auc=0.8171
model=graphsage top_k=50 fold=0 epoch=72 loss=6.2037 val_auc=0.8173
model=graphsage top_k=50 fold=0 epoch=73 loss=5.9628 val_auc=0.8176
model=graphsage top_k=50 fold=0 epoch=74 loss=6.1062 val_auc=0.8176
model=graphsage top_k=50 fold=0 epoch=75 loss=5.9171 val_auc=0.8176
model=graphsage top_k=50 fold=0 epoch=76 loss=4.8915 val_auc=0.8184
model=graphsage top_k=50 fold=0 epoch=77 loss=4.8351 val_auc=0.8192
model=graphsage top_k=50 fold=0 epoch=78 loss=5.4694 val_auc=0.8198
model=graphsage top_k=50 fold=0 epoch=79 loss=6.4529 val_auc=0.8203
model=graphsage top_k=50 fold=0 epoch=80 loss=5.7984 val_auc=0.8204
model=graphsage top_k=50 fold=0 epoch=81 loss=5.1960 val_auc=0.8207
model=graphsage top_k=50 fold=0 epoch=82 loss=5.7469 val_auc=0.8210
model=graphsage top_k=50 fold=0 epoch=83 loss=5.7810 val_auc=0.8214
model=graphsage top_k=50 fold=0 epoch=84 loss=5.1126 val_auc=0.8215
model=graphsage top_k=50 fold=0 epoch=85 loss=4.3819 val_auc=0.8216
model=graphsage top_k=50 fold=0 epoch=86 loss=3.7745 val_auc=0.8213
model=graphsage top_k=50 fold=0 epoch=87 loss=5.0529 val_auc=0.8215
model=graphsage top_k=50 fold=0 epoch=88 loss=5.4249 val_auc=0.8212
model=graphsage top_k=50 fold=0 epoch=89 loss=5.2460 val_auc=0.8211
model=graphsage top_k=50 fold=0 epoch=90 loss=5.6784 val_auc=0.8211
model=graphsage top_k=50 fold=0 epoch=91 loss=5.9382 val_auc=0.8213
model=graphsage top_k=50 fold=0 epoch=92 loss=5.5327 val_auc=0.8216
model=graphsage top_k=50 fold=0 epoch=93 loss=4.7068 val_auc=0.8219
model=graphsage top_k=50 fold=0 epoch=94 loss=4.2476 val_auc=0.8223
model=graphsage top_k=50 fold=0 epoch=95 loss=4.4559 val_auc=0.8223
model=graphsage top_k=50 fold=0 epoch=96 loss=3.8955 val_auc=0.8225
model=graphsage top_k=50 fold=0 epoch=97 loss=4.6066 val_auc=0.8228
model=graphsage top_k=50 fold=0 epoch=98 loss=4.2543 val_auc=0.8230
model=graphsage top_k=50 fold=0 epoch=99 loss=4.6170 val_auc=0.8232

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=50 fold=1 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=graphsage top_k=50 fold=1 epoch=0 loss=29.8078 val_auc=0.5000
model=graphsage top_k=50 fold=1 epoch=1 loss=320.1598 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=50 fold=1 epoch=2 loss=112.9597 val_auc=0.5818

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=50 fold=1 epoch=3 loss=65.1833 val_auc=0.7300
model=graphsage top_k=50 fold=1 epoch=4 loss=54.2468 val_auc=0.7385
model=graphsage top_k=50 fold=1 epoch=5 loss=12.4384 val_auc=0.6365
model=graphsage top_k=50 fold=1 epoch=6 loss=19.6374 val_auc=0.7737
model=graphsage top_k=50 fold=1 epoch=7 loss=11.1691 val_auc=0.7776
model=graphsage top_k=50 fold=1 epoch=8 loss=14.8213 val_auc=0.7620
model=graphsage top_k=50 fold=1 epoch=9 loss=12.8367 val_auc=0.7771
model=graphsage top_k=50 fold=1 epoch=10 loss=11.6603 val_auc=0.7804
model=graphsage top_k=50 fold=1 epoch=11 loss=14.4083 val_auc=0.7809
model=graphsage top_k=50 fold=1 epoch=12 loss=15.9851 val_auc=0.7587
model=graphsage top_k=50 fold=1 epoch=13 loss=17.1241 val_auc=0.7558
model=graphsage top_k=50 fold=1 epoch=14 loss=16.9210 val_auc=0.7839
model=graphsage top_k=50 fold=1 epoch=15 loss=11.8034 val_auc=0.7851
model=graphsage top_k=50 fold=1 epoch=16 loss=10.4147 val_auc=0.7870
model=graphsage top_k=50 fold=1 epoch=17 loss=9.5566 val_auc=0.7888
model=graphsage top_k=50 fold=1 epoch=18 loss=9.5993 val_auc=0.7836
model=graphsage top_k=50 fold=1 epoch=19 loss=9.2794 val_auc=0.7935
model=graphsage top_k=50 fold=1 epoch=20 loss=8.6979 val_auc=0.7962
model=graphsage top_k=50 fold=1 epoch=21 loss=11.4760 val_auc=0.7977
model=graphsage top_k=50 fold=1 epoch=22 loss=9.6024 val_auc=0.7976
model=graphsage top_k=50 fold=1 epoch=23 loss=10.2789 val_auc=0.7993
model=graphsage top_k=50 fold=1 epoch=24 loss=12.1692 val_auc=0.8009
model=graphsage top_k=50 fold=1 epoch=25 loss=7.5353 val_auc=0.8020
model=graphsage top_k=50 fold=1 epoch=26 loss=8.3500 val_auc=0.7994
model=graphsage top_k=50 fold=1 epoch=27 loss=10.4325 val_auc=0.7995
model=graphsage top_k=50 fold=1 epoch=28 loss=10.1059 val_auc=0.8043
model=graphsage top_k=50 fold=1 epoch=29 loss=9.8235 val_auc=0.8034
model=graphsage top_k=50 fold=1 epoch=30 loss=11.7650 val_auc=0.8029
model=graphsage top_k=50 fold=1 epoch=31 loss=16.0047 val_auc=0.8024
model=graphsage top_k=50 fold=1 epoch=32 loss=12.0743 val_auc=0.8015
model=graphsage top_k=50 fold=1 epoch=33 loss=7.3573 val_auc=0.7954
model=graphsage top_k=50 fold=1 epoch=34 loss=10.1284 val_auc=0.7979
model=graphsage top_k=50 fold=1 epoch=35 loss=8.4627 val_auc=0.8019
model=graphsage top_k=50 fold=1 epoch=36 loss=7.0368 val_auc=0.8029
model=graphsage top_k=50 fold=1 epoch=37 loss=6.9902 val_auc=0.8033
model=graphsage top_k=50 fold=1 epoch=38 loss=8.2038 val_auc=0.8058
model=graphsage top_k=50 fold=1 epoch=39 loss=7.6703 val_auc=0.8083
model=graphsage top_k=50 fold=1 epoch=40 loss=7.4116 val_auc=0.8100
model=graphsage top_k=50 fold=1 epoch=41 loss=7.6441 val_auc=0.8119
model=graphsage top_k=50 fold=1 epoch=42 loss=6.7393 val_auc=0.8135
model=graphsage top_k=50 fold=1 epoch=43 loss=5.9152 val_auc=0.8157
model=graphsage top_k=50 fold=1 epoch=44 loss=6.5084 val_auc=0.8176
model=graphsage top_k=50 fold=1 epoch=45 loss=5.5017 val_auc=0.8189
model=graphsage top_k=50 fold=1 epoch=46 loss=6.8817 val_auc=0.8200
model=graphsage top_k=50 fold=1 epoch=47 loss=6.2311 val_auc=0.8209
model=graphsage top_k=50 fold=1 epoch=48 loss=5.7542 val_auc=0.8210
model=graphsage top_k=50 fold=1 epoch=49 loss=5.7516 val_auc=0.8213
model=graphsage top_k=50 fold=1 epoch=50 loss=6.3388 val_auc=0.8216
model=graphsage top_k=50 fold=1 epoch=51 loss=6.1341 val_auc=0.8176
model=graphsage top_k=50 fold=1 epoch=52 loss=7.1847 val_auc=0.8071
model=graphsage top_k=50 fold=1 epoch=53 loss=12.3739 val_auc=0.8174
model=graphsage top_k=50 fold=1 epoch=54 loss=9.7641 val_auc=0.8195
model=graphsage top_k=50 fold=1 epoch=55 loss=6.0066 val_auc=0.8177
model=graphsage top_k=50 fold=1 epoch=56 loss=9.5269 val_auc=0.8162
model=graphsage top_k=50 fold=1 epoch=57 loss=10.7028 val_auc=0.8148
model=graphsage top_k=50 fold=1 epoch=58 loss=10.7078 val_auc=0.8140
model=graphsage top_k=50 fold=1 epoch=59 loss=5.7867 val_auc=0.8133
model=graphsage top_k=50 fold=1 epoch=60 loss=5.8003 val_auc=0.8112
model=graphsage top_k=50 fold=1 epoch=61 loss=10.2611 val_auc=0.8112
model=graphsage top_k=50 fold=1 epoch=62 loss=7.6145 val_auc=0.8138
graphsage top_k=50 fold=1: early stopping at epoch 62

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=50 fold=2 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=graphsage top_k=50 fold=2 epoch=0 loss=20.6030 val_auc=0.5000
model=graphsage top_k=50 fold=2 epoch=1 loss=248.6297 val_auc=0.5277

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=50 fold=2 epoch=2 loss=43.8672 val_auc=0.5007

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=50 fold=2 epoch=3 loss=112.7020 val_auc=0.5011
model=graphsage top_k=50 fold=2 epoch=4 loss=98.2328 val_auc=0.7494
model=graphsage top_k=50 fold=2 epoch=5 loss=49.1154 val_auc=0.5351
model=graphsage top_k=50 fold=2 epoch=6 loss=29.5068 val_auc=0.5023
model=graphsage top_k=50 fold=2 epoch=7 loss=40.1442 val_auc=0.5825
model=graphsage top_k=50 fold=2 epoch=8 loss=21.9554 val_auc=0.7573
model=graphsage top_k=50 fold=2 epoch=9 loss=15.2926 val_auc=0.7592
model=graphsage top_k=50 fold=2 epoch=10 loss=19.9962 val_auc=0.7608
model=graphsage top_k=50 fold=2 epoch=11 loss=13.5090 val_auc=0.7371
model=graphsage top_k=50 fold=2 epoch=12 loss=14.4559 val_auc=0.6579
model=graphsage top_k=50 fold=2 epoch=13 loss=18.4368 val_auc=0.7576
model=graphsage top_k=50 fold=2 epoch=14 loss=13.0741 val_auc=0.7653
model=graphsage top_k=50 fold=2 epoch=15 loss=12.9844 val_auc=0.7663
model=graphsage top_k=50 fold=2 epoch=16 loss=13.1900 val_auc=0.7670
model=graphsage top_k=50 fold=2 epoch=17 loss=13.5443 val_auc=0.7637
model=graphsage top_k=50 fold=2 epoch=18 loss=15.5806 val_auc=0.7593
model=graphsage top_k=50 fold=2 epoch=19 loss=15.4206 val_auc=0.7680
model=graphsage top_k=50 fold=2 epoch=20 loss=8.4365 val_auc=0.7714
model=graphsage top_k=50 fold=2 epoch=21 loss=9.0087 val_auc=0.7732
model=graphsage top_k=50 fold=2 epoch=22 loss=11.5347 val_auc=0.7744
model=graphsage top_k=50 fold=2 epoch=23 loss=9.5825 val_auc=0.7744
model=graphsage top_k=50 fold=2 epoch=24 loss=9.8089 val_auc=0.7701
model=graphsage top_k=50 fold=2 epoch=25 loss=13.4442 val_auc=0.7768
model=graphsage top_k=50 fold=2 epoch=26 loss=9.9834 val_auc=0.7783
model=graphsage top_k=50 fold=2 epoch=27 loss=9.2365 val_auc=0.7793
model=graphsage top_k=50 fold=2 epoch=28 loss=11.3195 val_auc=0.7801
model=graphsage top_k=50 fold=2 epoch=29 loss=9.6431 val_auc=0.7804
model=graphsage top_k=50 fold=2 epoch=30 loss=9.2375 val_auc=0.7805
model=graphsage top_k=50 fold=2 epoch=31 loss=9.0096 val_auc=0.7825
model=graphsage top_k=50 fold=2 epoch=32 loss=8.5596 val_auc=0.7840
model=graphsage top_k=50 fold=2 epoch=33 loss=10.6560 val_auc=0.7864
model=graphsage top_k=50 fold=2 epoch=34 loss=7.8528 val_auc=0.7888
model=graphsage top_k=50 fold=2 epoch=35 loss=7.8917 val_auc=0.7905
model=graphsage top_k=50 fold=2 epoch=36 loss=7.2405 val_auc=0.7919
model=graphsage top_k=50 fold=2 epoch=37 loss=11.4922 val_auc=0.7942
model=graphsage top_k=50 fold=2 epoch=38 loss=7.4843 val_auc=0.7959
model=graphsage top_k=50 fold=2 epoch=39 loss=8.9456 val_auc=0.7970
model=graphsage top_k=50 fold=2 epoch=40 loss=11.7054 val_auc=0.7976
model=graphsage top_k=50 fold=2 epoch=41 loss=7.8609 val_auc=0.7974
model=graphsage top_k=50 fold=2 epoch=42 loss=8.2568 val_auc=0.7970
model=graphsage top_k=50 fold=2 epoch=43 loss=9.6806 val_auc=0.7987
model=graphsage top_k=50 fold=2 epoch=44 loss=6.1930 val_auc=0.8000
model=graphsage top_k=50 fold=2 epoch=45 loss=7.4921 val_auc=0.8012
model=graphsage top_k=50 fold=2 epoch=46 loss=7.8769 val_auc=0.8022
model=graphsage top_k=50 fold=2 epoch=47 loss=7.1582 val_auc=0.8025
model=graphsage top_k=50 fold=2 epoch=48 loss=6.7941 val_auc=0.7781
model=graphsage top_k=50 fold=2 epoch=49 loss=10.4764 val_auc=0.7611
model=graphsage top_k=50 fold=2 epoch=50 loss=15.2910 val_auc=0.7842
model=graphsage top_k=50 fold=2 epoch=51 loss=11.7790 val_auc=0.8044
model=graphsage top_k=50 fold=2 epoch=52 loss=6.7927 val_auc=0.8048
model=graphsage top_k=50 fold=2 epoch=53 loss=11.4683 val_auc=0.8048
model=graphsage top_k=50 fold=2 epoch=54 loss=9.6855 val_auc=0.8049
model=graphsage top_k=50 fold=2 epoch=55 loss=9.1939 val_auc=0.8051
model=graphsage top_k=50 fold=2 epoch=56 loss=6.2417 val_auc=0.8050
model=graphsage top_k=50 fold=2 epoch=57 loss=6.4448 val_auc=0.8023
model=graphsage top_k=50 fold=2 epoch=58 loss=7.6970 val_auc=0.8050
model=graphsage top_k=50 fold=2 epoch=59 loss=7.3078 val_auc=0.8055
model=graphsage top_k=50 fold=2 epoch=60 loss=5.9356 val_auc=0.8057
model=graphsage top_k=50 fold=2 epoch=61 loss=6.8737 val_auc=0.8062
model=graphsage top_k=50 fold=2 epoch=62 loss=9.8965 val_auc=0.8070
model=graphsage top_k=50 fold=2 epoch=63 loss=7.7115 val_auc=0.8079
model=graphsage top_k=50 fold=2 epoch=64 loss=5.4184 val_auc=0.8091
model=graphsage top_k=50 fold=2 epoch=65 loss=6.1623 val_auc=0.8104
model=graphsage top_k=50 fold=2 epoch=66 loss=6.5621 val_auc=0.8120
model=graphsage top_k=50 fold=2 epoch=67 loss=5.3343 val_auc=0.8128
model=graphsage top_k=50 fold=2 epoch=68 loss=7.7727 val_auc=0.8134
model=graphsage top_k=50 fold=2 epoch=69 loss=7.2644 val_auc=0.8141
model=graphsage top_k=50 fold=2 epoch=70 loss=7.3959 val_auc=0.8147
model=graphsage top_k=50 fold=2 epoch=71 loss=5.3411 val_auc=0.8150
model=graphsage top_k=50 fold=2 epoch=72 loss=6.0539 val_auc=0.8152
model=graphsage top_k=50 fold=2 epoch=73 loss=5.4815 val_auc=0.8150
model=graphsage top_k=50 fold=2 epoch=74 loss=5.4367 val_auc=0.8148
model=graphsage top_k=50 fold=2 epoch=75 loss=5.8332 val_auc=0.8146
model=graphsage top_k=50 fold=2 epoch=76 loss=5.4879 val_auc=0.8147
model=graphsage top_k=50 fold=2 epoch=77 loss=4.9437 val_auc=0.8147
model=graphsage top_k=50 fold=2 epoch=78 loss=6.2836 val_auc=0.8146
model=graphsage top_k=50 fold=2 epoch=79 loss=5.7295 val_auc=0.8144
model=graphsage top_k=50 fold=2 epoch=80 loss=3.7122 val_auc=0.8148
model=graphsage top_k=50 fold=2 epoch=81 loss=4.4681 val_auc=0.8154
model=graphsage top_k=50 fold=2 epoch=82 loss=4.0687 val_auc=0.8166
model=graphsage top_k=50 fold=2 epoch=83 loss=5.9592 val_auc=0.8176
model=graphsage top_k=50 fold=2 epoch=84 loss=4.5146 val_auc=0.8186
model=graphsage top_k=50 fold=2 epoch=85 loss=4.8908 val_auc=0.8196
model=graphsage top_k=50 fold=2 epoch=86 loss=5.8140 val_auc=0.8202
model=graphsage top_k=50 fold=2 epoch=87 loss=4.0926 val_auc=0.8209
model=graphsage top_k=50 fold=2 epoch=88 loss=4.9981 val_auc=0.8213
model=graphsage top_k=50 fold=2 epoch=89 loss=4.3283 val_auc=0.8214
model=graphsage top_k=50 fold=2 epoch=90 loss=4.7546 val_auc=0.8212
model=graphsage top_k=50 fold=2 epoch=91 loss=4.0136 val_auc=0.8212
model=graphsage top_k=50 fold=2 epoch=92 loss=5.8830 val_auc=0.8212
model=graphsage top_k=50 fold=2 epoch=93 loss=4.8067 val_auc=0.8214
model=graphsage top_k=50 fold=2 epoch=94 loss=3.6667 val_auc=0.8220
model=graphsage top_k=50 fold=2 epoch=95 loss=4.0659 val_auc=0.8226
model=graphsage top_k=50 fold=2 epoch=96 loss=5.5772 val_auc=0.8224
model=graphsage top_k=50 fold=2 epoch=97 loss=4.1273 val_auc=0.8222
model=graphsage top_k=50 fold=2 epoch=98 loss=4.0788 val_auc=0.8222
model=graphsage top_k=50 fold=2 epoch=99 loss=4.3608 val_auc=0.8226

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=50 fold=3 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=graphsage top_k=50 fold=3 epoch=0 loss=22.4072 val_auc=0.5000
model=graphsage top_k=50 fold=3 epoch=1 loss=311.9162 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=50 fold=3 epoch=2 loss=121.7101 val_auc=0.6735
model=graphsage top_k=50 fold=3 epoch=3 loss=63.5419 val_auc=0.7334
model=graphsage top_k=50 fold=3 epoch=4 loss=46.1818 val_auc=0.6398
model=graphsage top_k=50 fold=3 epoch=5 loss=15.0340 val_auc=0.7461
model=graphsage top_k=50 fold=3 epoch=6 loss=13.3474 val_auc=0.7699
model=graphsage top_k=50 fold=3 epoch=7 loss=23.0956 val_auc=0.7728
model=graphsage top_k=50 fold=3 epoch=8 loss=20.6311 val_auc=0.7711
model=graphsage top_k=50 fold=3 epoch=9 loss=12.3172 val_auc=0.6318
model=graphsage top_k=50 fold=3 epoch=10 loss=21.1014 val_auc=0.7265
model=graphsage top_k=50 fold=3 epoch=11 loss=18.1922 val_auc=0.7807
model=graphsage top_k=50 fold=3 epoch=12 loss=14.1554 val_auc=0.7819
model=graphsage top_k=50 fold=3 epoch=13 loss=13.0504 val_auc=0.7793
model=graphsage top_k=50 fold=3 epoch=14 loss=12.0478 val_auc=0.7821
model=graphsage top_k=50 fold=3 epoch=15 loss=8.2471 val_auc=0.7873
model=graphsage top_k=50 fold=3 epoch=16 loss=10.4374 val_auc=0.7906
model=graphsage top_k=50 fold=3 epoch=17 loss=10.3551 val_auc=0.7818
model=graphsage top_k=50 fold=3 epoch=18 loss=10.0305 val_auc=0.7877
model=graphsage top_k=50 fold=3 epoch=19 loss=12.1811 val_auc=0.7964
model=graphsage top_k=50 fold=3 epoch=20 loss=9.6932 val_auc=0.7971
model=graphsage top_k=50 fold=3 epoch=21 loss=10.9671 val_auc=0.7961
model=graphsage top_k=50 fold=3 epoch=22 loss=10.3020 val_auc=0.7966
model=graphsage top_k=50 fold=3 epoch=23 loss=9.3664 val_auc=0.7979
model=graphsage top_k=50 fold=3 epoch=24 loss=8.7761 val_auc=0.7985
model=graphsage top_k=50 fold=3 epoch=25 loss=9.4131 val_auc=0.7984
model=graphsage top_k=50 fold=3 epoch=26 loss=7.2735 val_auc=0.7994
model=graphsage top_k=50 fold=3 epoch=27 loss=8.5150 val_auc=0.8020
model=graphsage top_k=50 fold=3 epoch=28 loss=8.0989 val_auc=0.8040
model=graphsage top_k=50 fold=3 epoch=29 loss=6.7806 val_auc=0.8053
model=graphsage top_k=50 fold=3 epoch=30 loss=8.0697 val_auc=0.8073
model=graphsage top_k=50 fold=3 epoch=31 loss=8.7793 val_auc=0.8088
model=graphsage top_k=50 fold=3 epoch=32 loss=8.4041 val_auc=0.8092
model=graphsage top_k=50 fold=3 epoch=33 loss=9.0573 val_auc=0.8091
model=graphsage top_k=50 fold=3 epoch=34 loss=6.8138 val_auc=0.8093
model=graphsage top_k=50 fold=3 epoch=35 loss=6.6135 val_auc=0.8096
model=graphsage top_k=50 fold=3 epoch=36 loss=6.5221 val_auc=0.8058
model=graphsage top_k=50 fold=3 epoch=37 loss=10.2605 val_auc=0.8084
model=graphsage top_k=50 fold=3 epoch=38 loss=8.6569 val_auc=0.8107
model=graphsage top_k=50 fold=3 epoch=39 loss=8.3234 val_auc=0.8109
model=graphsage top_k=50 fold=3 epoch=40 loss=6.8880 val_auc=0.8113
model=graphsage top_k=50 fold=3 epoch=41 loss=5.9408 val_auc=0.8095
model=graphsage top_k=50 fold=3 epoch=42 loss=7.6856 val_auc=0.8078
model=graphsage top_k=50 fold=3 epoch=43 loss=8.8669 val_auc=0.8126
model=graphsage top_k=50 fold=3 epoch=44 loss=8.3010 val_auc=0.8131
model=graphsage top_k=50 fold=3 epoch=45 loss=7.4343 val_auc=0.8136
model=graphsage top_k=50 fold=3 epoch=46 loss=7.9296 val_auc=0.8139
model=graphsage top_k=50 fold=3 epoch=47 loss=8.1931 val_auc=0.8143
model=graphsage top_k=50 fold=3 epoch=48 loss=5.6980 val_auc=0.8134
model=graphsage top_k=50 fold=3 epoch=49 loss=7.9360 val_auc=0.8155
model=graphsage top_k=50 fold=3 epoch=50 loss=6.8126 val_auc=0.8176
model=graphsage top_k=50 fold=3 epoch=51 loss=6.4774 val_auc=0.8185
model=graphsage top_k=50 fold=3 epoch=52 loss=7.8866 val_auc=0.8192
model=graphsage top_k=50 fold=3 epoch=53 loss=11.9250 val_auc=0.8197
model=graphsage top_k=50 fold=3 epoch=54 loss=9.4958 val_auc=0.8200
model=graphsage top_k=50 fold=3 epoch=55 loss=7.3701 val_auc=0.8112
model=graphsage top_k=50 fold=3 epoch=56 loss=9.7427 val_auc=0.7610
model=graphsage top_k=50 fold=3 epoch=57 loss=14.2165 val_auc=0.7672
model=graphsage top_k=50 fold=3 epoch=58 loss=18.3656 val_auc=0.8152
model=graphsage top_k=50 fold=3 epoch=59 loss=8.4930 val_auc=0.8205
model=graphsage top_k=50 fold=3 epoch=60 loss=5.3366 val_auc=0.8203
model=graphsage top_k=50 fold=3 epoch=61 loss=9.6402 val_auc=0.8199
model=graphsage top_k=50 fold=3 epoch=62 loss=10.9891 val_auc=0.8194
model=graphsage top_k=50 fold=3 epoch=63 loss=7.7474 val_auc=0.8187
model=graphsage top_k=50 fold=3 epoch=64 loss=5.3658 val_auc=0.8161
model=graphsage top_k=50 fold=3 epoch=65 loss=8.2701 val_auc=0.8020
model=graphsage top_k=50 fold=3 epoch=66 loss=10.1731 val_auc=0.8088
model=graphsage top_k=50 fold=3 epoch=67 loss=9.1334 val_auc=0.8177
model=graphsage top_k=50 fold=3 epoch=68 loss=7.1598 val_auc=0.8190
model=graphsage top_k=50 fold=3 epoch=69 loss=6.0075 val_auc=0.8194
model=graphsage top_k=50 fold=3 epoch=70 loss=7.6067 val_auc=0.8198
model=graphsage top_k=50 fold=3 epoch=71 loss=8.3248 val_auc=0.8199
graphsage top_k=50 fold=3: early stopping at epoch 71

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=50 fold=4 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=50 fold=4 epoch=0 loss=20.1765 val_auc=0.5000
model=graphsage top_k=50 fold=4 epoch=1 loss=145.9016 val_auc=0.5275
model=graphsage top_k=50 fold=4 epoch=2 loss=56.8167 val_auc=0.7607
model=graphsage top_k=50 fold=4 epoch=3 loss=13.6205 val_auc=0.6804
model=graphsage top_k=50 fold=4 epoch=4 loss=24.3631 val_auc=0.7771
model=graphsage top_k=50 fold=4 epoch=5 loss=31.2445 val_auc=0.7728
model=graphsage top_k=50 fold=4 epoch=6 loss=21.7587 val_auc=0.5238
model=graphsage top_k=50 fold=4 epoch=7 loss=26.7417 val_auc=0.5437
model=graphsage top_k=50 fold=4 epoch=8 loss=29.1152 val_auc=0.7818
model=graphsage top_k=50 fold=4 epoch=9 loss=14.7166 val_auc=0.7842
model=graphsage top_k=50 fold=4 epoch=10 loss=19.6775 val_auc=0.7852
model=graphsage top_k=50 fold=4 epoch=11 loss=14.8814 val_auc=0.7858
model=graphsage top_k=50 fold=4 epoch=12 loss=10.4325 val_auc=0.7886
model=graphsage top_k=50 fold=4 epoch=13 loss=11.5857 val_auc=0.7904
model=graphsage top_k=50 fold=4 epoch=14 loss=14.1772 val_auc=0.7924
model=graphsage top_k=50 fold=4 epoch=15 loss=14.7499 val_auc=0.7884
model=graphsage top_k=50 fold=4 epoch=16 loss=10.7205 val_auc=0.7938
model=graphsage top_k=50 fold=4 epoch=17 loss=11.2086 val_auc=0.7961
model=graphsage top_k=50 fold=4 epoch=18 loss=11.3663 val_auc=0.7970
model=graphsage top_k=50 fold=4 epoch=19 loss=11.0956 val_auc=0.7927
model=graphsage top_k=50 fold=4 epoch=20 loss=10.6018 val_auc=0.7927
model=graphsage top_k=50 fold=4 epoch=21 loss=9.1790 val_auc=0.7995
model=graphsage top_k=50 fold=4 epoch=22 loss=10.1833 val_auc=0.8000
model=graphsage top_k=50 fold=4 epoch=23 loss=12.2028 val_auc=0.8004
model=graphsage top_k=50 fold=4 epoch=24 loss=10.2753 val_auc=0.8012
model=graphsage top_k=50 fold=4 epoch=25 loss=7.8739 val_auc=0.8019
model=graphsage top_k=50 fold=4 epoch=26 loss=8.1690 val_auc=0.8026
model=graphsage top_k=50 fold=4 epoch=27 loss=7.5302 val_auc=0.8047
model=graphsage top_k=50 fold=4 epoch=28 loss=11.5981 val_auc=0.8061
model=graphsage top_k=50 fold=4 epoch=29 loss=8.5148 val_auc=0.8069
model=graphsage top_k=50 fold=4 epoch=30 loss=8.3503 val_auc=0.7886
model=graphsage top_k=50 fold=4 epoch=31 loss=12.7300 val_auc=0.8052
model=graphsage top_k=50 fold=4 epoch=32 loss=10.1491 val_auc=0.8108
model=graphsage top_k=50 fold=4 epoch=33 loss=7.2335 val_auc=0.8117
model=graphsage top_k=50 fold=4 epoch=34 loss=8.8479 val_auc=0.8124
model=graphsage top_k=50 fold=4 epoch=35 loss=7.0745 val_auc=0.8050
model=graphsage top_k=50 fold=4 epoch=36 loss=8.3717 val_auc=0.7928
model=graphsage top_k=50 fold=4 epoch=37 loss=12.2898 val_auc=0.8119
model=graphsage top_k=50 fold=4 epoch=38 loss=8.2894 val_auc=0.8137
model=graphsage top_k=50 fold=4 epoch=39 loss=7.2887 val_auc=0.8138
model=graphsage top_k=50 fold=4 epoch=40 loss=8.1116 val_auc=0.8140
model=graphsage top_k=50 fold=4 epoch=41 loss=8.3321 val_auc=0.8139
model=graphsage top_k=50 fold=4 epoch=42 loss=7.0215 val_auc=0.8133
model=graphsage top_k=50 fold=4 epoch=43 loss=8.0213 val_auc=0.8145
model=graphsage top_k=50 fold=4 epoch=44 loss=6.3193 val_auc=0.8151
model=graphsage top_k=50 fold=4 epoch=45 loss=5.8285 val_auc=0.8162
model=graphsage top_k=50 fold=4 epoch=46 loss=6.4856 val_auc=0.8170
model=graphsage top_k=50 fold=4 epoch=47 loss=6.6350 val_auc=0.8178
model=graphsage top_k=50 fold=4 epoch=48 loss=6.7082 val_auc=0.8178
model=graphsage top_k=50 fold=4 epoch=49 loss=6.3591 val_auc=0.8173
model=graphsage top_k=50 fold=4 epoch=50 loss=9.3835 val_auc=0.8169
model=graphsage top_k=50 fold=4 epoch=51 loss=5.5730 val_auc=0.8172
model=graphsage top_k=50 fold=4 epoch=52 loss=5.8252 val_auc=0.8180
model=graphsage top_k=50 fold=4 epoch=53 loss=6.7184 val_auc=0.8185
model=graphsage top_k=50 fold=4 epoch=54 loss=5.4441 val_auc=0.8190
model=graphsage top_k=50 fold=4 epoch=55 loss=4.8170 val_auc=0.8197
model=graphsage top_k=50 fold=4 epoch=56 loss=5.8405 val_auc=0.8202
model=graphsage top_k=50 fold=4 epoch=57 loss=4.5785 val_auc=0.8209
model=graphsage top_k=50 fold=4 epoch=58 loss=5.1334 val_auc=0.8218
model=graphsage top_k=50 fold=4 epoch=59 loss=6.3009 val_auc=0.8223
model=graphsage top_k=50 fold=4 epoch=60 loss=5.4325 val_auc=0.8222
model=graphsage top_k=50 fold=4 epoch=61 loss=6.0766 val_auc=0.8224
model=graphsage top_k=50 fold=4 epoch=62 loss=6.2021 val_auc=0.8225
model=graphsage top_k=50 fold=4 epoch=63 loss=6.3945 val_auc=0.8226
model=graphsage top_k=50 fold=4 epoch=64 loss=5.4520 val_auc=0.8224
model=graphsage top_k=50 fold=4 epoch=65 loss=6.5908 val_auc=0.8218
model=graphsage top_k=50 fold=4 epoch=66 loss=4.8503 val_auc=0.8217
model=graphsage top_k=50 fold=4 epoch=67 loss=4.3822 val_auc=0.8232
model=graphsage top_k=50 fold=4 epoch=68 loss=5.2557 val_auc=0.8239
model=graphsage top_k=50 fold=4 epoch=69 loss=5.6018 val_auc=0.8243
model=graphsage top_k=50 fold=4 epoch=70 loss=4.8057 val_auc=0.8242
model=graphsage top_k=50 fold=4 epoch=71 loss=4.2518 val_auc=0.8240
model=graphsage top_k=50 fold=4 epoch=72 loss=4.8600 val_auc=0.8239
model=graphsage top_k=50 fold=4 epoch=73 loss=3.9095 val_auc=0.8248
model=graphsage top_k=50 fold=4 epoch=74 loss=5.9465 val_auc=0.8254
model=graphsage top_k=50 fold=4 epoch=75 loss=5.3880 val_auc=0.8259
model=graphsage top_k=50 fold=4 epoch=76 loss=5.3315 val_auc=0.8259
model=graphsage top_k=50 fold=4 epoch=77 loss=6.0057 val_auc=0.8222
model=graphsage top_k=50 fold=4 epoch=78 loss=6.5773 val_auc=0.8260
model=graphsage top_k=50 fold=4 epoch=79 loss=7.1214 val_auc=0.8261
model=graphsage top_k=50 fold=4 epoch=80 loss=4.9726 val_auc=0.8249
model=graphsage top_k=50 fold=4 epoch=81 loss=6.7523 val_auc=0.8241
model=graphsage top_k=50 fold=4 epoch=82 loss=6.3154 val_auc=0.8239
model=graphsage top_k=50 fold=4 epoch=83 loss=4.3471 val_auc=0.8245
model=graphsage top_k=50 fold=4 epoch=84 loss=3.9434 val_auc=0.8258
model=graphsage top_k=50 fold=4 epoch=85 loss=7.0634 val_auc=0.8258
model=graphsage top_k=50 fold=4 epoch=86 loss=7.9895 val_auc=0.8270
model=graphsage top_k=50 fold=4 epoch=87 loss=5.9846 val_auc=0.8261
model=graphsage top_k=50 fold=4 epoch=88 loss=4.9742 val_auc=0.8256
model=graphsage top_k=50 fold=4 epoch=89 loss=5.5951 val_auc=0.8252
model=graphsage top_k=50 fold=4 epoch=90 loss=6.2835 val_auc=0.8249
model=graphsage top_k=50 fold=4 epoch=91 loss=4.4262 val_auc=0.8248
model=graphsage top_k=50 fold=4 epoch=92 loss=5.3258 val_auc=0.8248
model=graphsage top_k=50 fold=4 epoch=93 loss=4.2330 val_auc=0.8246
model=graphsage top_k=50 fold=4 epoch=94 loss=4.6375 val_auc=0.8245
model=graphsage top_k=50 fold=4 epoch=95 loss=4.4710 val_auc=0.8246
model=graphsage top_k=50 fold=4 epoch=96 loss=4.0399 val_auc=0.8252
model=graphsage top_k=50 fold=4 epoch=97 loss=4.9302 val_auc=0.8258
model=graphsage top_k=50 fold=4 epoch=98 loss=3.7489 val_auc=0.8264
graphsage top_k=50 fold=4: early stopping at epoch 98

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=50 fold=5 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=50 fold=5 epoch=0 loss=20.7812 val_auc=0.5000
model=graphsage top_k=50 fold=5 epoch=1 loss=181.4545 val_auc=0.7538
model=graphsage top_k=50 fold=5 epoch=2 loss=15.1769 val_auc=0.5000
model=graphsage top_k=50 fold=5 epoch=3 loss=188.7908 val_auc=0.5000
model=graphsage top_k=50 fold=5 epoch=4 loss=153.5655 val_auc=0.5061
model=graphsage top_k=50 fold=5 epoch=5 loss=71.8857 val_auc=0.7644

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=50 fold=5 epoch=6 loss=21.2685 val_auc=0.7862
model=graphsage top_k=50 fold=5 epoch=7 loss=37.6279 val_auc=0.7923
model=graphsage top_k=50 fold=5 epoch=8 loss=20.7411 val_auc=0.5398
model=graphsage top_k=50 fold=5 epoch=9 loss=30.3174 val_auc=0.5393
model=graphsage top_k=50 fold=5 epoch=10 loss=33.8747 val_auc=0.6318
model=graphsage top_k=50 fold=5 epoch=11 loss=13.6527 val_auc=0.7866
model=graphsage top_k=50 fold=5 epoch=12 loss=13.9760 val_auc=0.7855
model=graphsage top_k=50 fold=5 epoch=13 loss=17.8687 val_auc=0.7853
model=graphsage top_k=50 fold=5 epoch=14 loss=13.3159 val_auc=0.7817
model=graphsage top_k=50 fold=5 epoch=15 loss=11.5796 val_auc=0.7709
model=graphsage top_k=50 fold=5 epoch=16 loss=13.6833 val_auc=0.7843
model=graphsage top_k=50 fold=5 epoch=17 loss=11.5260 val_auc=0.7855
model=graphsage top_k=50 fold=5 epoch=18 loss=12.2732 val_auc=0.7858
model=graphsage top_k=50 fold=5 epoch=19 loss=13.2518 val_auc=0.7864
graphsage top_k=50 fold=5: early stopping at epoch 19

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=50 fold=6 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=graphsage top_k=50 fold=6 epoch=0 loss=40.1547 val_auc=0.5000
model=graphsage top_k=50 fold=6 epoch=1 loss=347.7760 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=50 fold=6 epoch=2 loss=132.8881 val_auc=0.6515
model=graphsage top_k=50 fold=6 epoch=3 loss=51.0931 val_auc=0.7365
model=graphsage top_k=50 fold=6 epoch=4 loss=41.4825 val_auc=0.5612
model=graphsage top_k=50 fold=6 epoch=5 loss=26.5069 val_auc=0.5883
model=graphsage top_k=50 fold=6 epoch=6 loss=21.2097 val_auc=0.7687
model=graphsage top_k=50 fold=6 epoch=7 loss=19.6430 val_auc=0.7728
model=graphsage top_k=50 fold=6 epoch=8 loss=17.2575 val_auc=0.7755
model=graphsage top_k=50 fold=6 epoch=9 loss=16.8039 val_auc=0.7783
model=graphsage top_k=50 fold=6 epoch=10 loss=13.7442 val_auc=0.7804
model=graphsage top_k=50 fold=6 epoch=11 loss=14.2059 val_auc=0.7814
model=graphsage top_k=50 fold=6 epoch=12 loss=15.0776 val_auc=0.7644
model=graphsage top_k=50 fold=6 epoch=13 loss=15.8631 val_auc=0.7428
model=graphsage top_k=50 fold=6 epoch=14 loss=16.3953 val_auc=0.7828
model=graphsage top_k=50 fold=6 epoch=15 loss=13.4132 val_auc=0.7848
model=graphsage top_k=50 fold=6 epoch=16 loss=11.5508 val_auc=0.7862
model=graphsage top_k=50 fold=6 epoch=17 loss=15.2205 val_auc=0.7877
model=graphsage top_k=50 fold=6 epoch=18 loss=14.8303 val_auc=0.7784
model=graphsage top_k=50 fold=6 epoch=19 loss=13.6030 val_auc=0.7167
model=graphsage top_k=50 fold=6 epoch=20 loss=17.8088 val_auc=0.7821
model=graphsage top_k=50 fold=6 epoch=21 loss=12.4300 val_auc=0.7916
model=graphsage top_k=50 fold=6 epoch=22 loss=9.8626 val_auc=0.7934
model=graphsage top_k=50 fold=6 epoch=23 loss=11.6250 val_auc=0.7947
model=graphsage top_k=50 fold=6 epoch=24 loss=9.2943 val_auc=0.7915
model=graphsage top_k=50 fold=6 epoch=25 loss=11.8247 val_auc=0.7904
model=graphsage top_k=50 fold=6 epoch=26 loss=14.3939 val_auc=0.7993
model=graphsage top_k=50 fold=6 epoch=27 loss=8.9878 val_auc=0.8019
model=graphsage top_k=50 fold=6 epoch=28 loss=11.3132 val_auc=0.8028
model=graphsage top_k=50 fold=6 epoch=29 loss=12.7480 val_auc=0.8031
model=graphsage top_k=50 fold=6 epoch=30 loss=10.2007 val_auc=0.8028
model=graphsage top_k=50 fold=6 epoch=31 loss=7.8372 val_auc=0.7997
model=graphsage top_k=50 fold=6 epoch=32 loss=13.1806 val_auc=0.8026
model=graphsage top_k=50 fold=6 epoch=33 loss=10.1052 val_auc=0.8055
model=graphsage top_k=50 fold=6 epoch=34 loss=7.3356 val_auc=0.8065
model=graphsage top_k=50 fold=6 epoch=35 loss=10.3593 val_auc=0.8072
model=graphsage top_k=50 fold=6 epoch=36 loss=11.1376 val_auc=0.8076
model=graphsage top_k=50 fold=6 epoch=37 loss=8.0947 val_auc=0.8076
model=graphsage top_k=50 fold=6 epoch=38 loss=8.0403 val_auc=0.8092
model=graphsage top_k=50 fold=6 epoch=39 loss=8.0019 val_auc=0.8107
model=graphsage top_k=50 fold=6 epoch=40 loss=6.5432 val_auc=0.8119
model=graphsage top_k=50 fold=6 epoch=41 loss=6.4955 val_auc=0.8129
model=graphsage top_k=50 fold=6 epoch=42 loss=7.0619 val_auc=0.8134
model=graphsage top_k=50 fold=6 epoch=43 loss=8.3723 val_auc=0.8141
model=graphsage top_k=50 fold=6 epoch=44 loss=6.9868 val_auc=0.8150
model=graphsage top_k=50 fold=6 epoch=45 loss=5.8406 val_auc=0.8160
model=graphsage top_k=50 fold=6 epoch=46 loss=6.9561 val_auc=0.8169
model=graphsage top_k=50 fold=6 epoch=47 loss=7.1965 val_auc=0.8174
model=graphsage top_k=50 fold=6 epoch=48 loss=5.8600 val_auc=0.8182
model=graphsage top_k=50 fold=6 epoch=49 loss=5.9000 val_auc=0.8188
model=graphsage top_k=50 fold=6 epoch=50 loss=5.5966 val_auc=0.8191
model=graphsage top_k=50 fold=6 epoch=51 loss=8.4190 val_auc=0.8191
model=graphsage top_k=50 fold=6 epoch=52 loss=13.1421 val_auc=0.8194
model=graphsage top_k=50 fold=6 epoch=53 loss=11.9333 val_auc=0.8198
model=graphsage top_k=50 fold=6 epoch=54 loss=8.1869 val_auc=0.8200
model=graphsage top_k=50 fold=6 epoch=55 loss=5.8727 val_auc=0.8175
model=graphsage top_k=50 fold=6 epoch=56 loss=7.5362 val_auc=0.8181
model=graphsage top_k=50 fold=6 epoch=57 loss=9.4510 val_auc=0.8212
model=graphsage top_k=50 fold=6 epoch=58 loss=6.3321 val_auc=0.8214
model=graphsage top_k=50 fold=6 epoch=59 loss=5.6642 val_auc=0.8218
model=graphsage top_k=50 fold=6 epoch=60 loss=7.0434 val_auc=0.8222
model=graphsage top_k=50 fold=6 epoch=61 loss=5.9498 val_auc=0.8228
model=graphsage top_k=50 fold=6 epoch=62 loss=4.5677 val_auc=0.8238
model=graphsage top_k=50 fold=6 epoch=63 loss=5.6307 val_auc=0.8247
model=graphsage top_k=50 fold=6 epoch=64 loss=5.3238 val_auc=0.8256
model=graphsage top_k=50 fold=6 epoch=65 loss=4.6231 val_auc=0.8266
model=graphsage top_k=50 fold=6 epoch=66 loss=6.3820 val_auc=0.8273
model=graphsage top_k=50 fold=6 epoch=67 loss=7.4680 val_auc=0.8279
model=graphsage top_k=50 fold=6 epoch=68 loss=5.8594 val_auc=0.8284
model=graphsage top_k=50 fold=6 epoch=69 loss=6.5081 val_auc=0.8282
model=graphsage top_k=50 fold=6 epoch=70 loss=5.8227 val_auc=0.8272
model=graphsage top_k=50 fold=6 epoch=71 loss=4.5262 val_auc=0.8263
model=graphsage top_k=50 fold=6 epoch=72 loss=5.1509 val_auc=0.8255
model=graphsage top_k=50 fold=6 epoch=73 loss=5.4828 val_auc=0.8242
model=graphsage top_k=50 fold=6 epoch=74 loss=7.4028 val_auc=0.8229
model=graphsage top_k=50 fold=6 epoch=75 loss=7.8949 val_auc=0.8218
model=graphsage top_k=50 fold=6 epoch=76 loss=4.3012 val_auc=0.8212
model=graphsage top_k=50 fold=6 epoch=77 loss=4.8986 val_auc=0.8209
model=graphsage top_k=50 fold=6 epoch=78 loss=5.8598 val_auc=0.8210
model=graphsage top_k=50 fold=6 epoch=79 loss=4.5529 val_auc=0.8217
model=graphsage top_k=50 fold=6 epoch=80 loss=5.5686 val_auc=0.8229
graphsage top_k=50 fold=6: early stopping at epoch 80

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=50 fold=7 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=50 fold=7 epoch=0 loss=22.5398 val_auc=0.5000
model=graphsage top_k=50 fold=7 epoch=1 loss=142.4783 val_auc=0.5135
model=graphsage top_k=50 fold=7 epoch=2 loss=57.7377 val_auc=0.7676
model=graphsage top_k=50 fold=7 epoch=3 loss=19.9348 val_auc=0.5373
model=graphsage top_k=50 fold=7 epoch=4 loss=34.4279 val_auc=0.7608

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=50 fold=7 epoch=5 loss=18.9235 val_auc=0.7609

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=50 fold=7 epoch=6 loss=51.1932 val_auc=0.7721
model=graphsage top_k=50 fold=7 epoch=7 loss=47.6266 val_auc=0.7793
model=graphsage top_k=50 fold=7 epoch=8 loss=20.8622 val_auc=0.5909
model=graphsage top_k=50 fold=7 epoch=9 loss=25.1911 val_auc=0.5101
model=graphsage top_k=50 fold=7 epoch=10 loss=46.5306 val_auc=0.6009
model=graphsage top_k=50 fold=7 epoch=11 loss=32.6174 val_auc=0.7805
model=graphsage top_k=50 fold=7 epoch=12 loss=12.1384 val_auc=0.7837
model=graphsage top_k=50 fold=7 epoch=13 loss=15.5533 val_auc=0.7858
model=graphsage top_k=50 fold=7 epoch=14 loss=11.4911 val_auc=0.7654
model=graphsage top_k=50 fold=7 epoch=15 loss=15.4560 val_auc=0.7371
model=graphsage top_k=50 fold=7 epoch=16 loss=15.6697 val_auc=0.7906
model=graphsage top_k=50 fold=7 epoch=17 loss=13.8567 val_auc=0.7955
model=graphsage top_k=50 fold=7 epoch=18 loss=16.8280 val_auc=0.7963
model=graphsage top_k=50 fold=7 epoch=19 loss=17.7190 val_auc=0.7964
model=graphsage top_k=50 fold=7 epoch=20 loss=15.0209 val_auc=0.7945
model=graphsage top_k=50 fold=7 epoch=21 loss=8.4741 val_auc=0.7461
model=graphsage top_k=50 fold=7 epoch=22 loss=15.8323 val_auc=0.7613
model=graphsage top_k=50 fold=7 epoch=23 loss=10.8308 val_auc=0.7977
model=graphsage top_k=50 fold=7 epoch=24 loss=9.2899 val_auc=0.7996
model=graphsage top_k=50 fold=7 epoch=25 loss=12.0834 val_auc=0.8002
model=graphsage top_k=50 fold=7 epoch=26 loss=17.3663 val_auc=0.8007
model=graphsage top_k=50 fold=7 epoch=27 loss=11.5056 val_auc=0.8013
model=graphsage top_k=50 fold=7 epoch=28 loss=8.4177 val_auc=0.8005
model=graphsage top_k=50 fold=7 epoch=29 loss=10.2814 val_auc=0.8018
model=graphsage top_k=50 fold=7 epoch=30 loss=11.6864 val_auc=0.8040
model=graphsage top_k=50 fold=7 epoch=31 loss=8.3754 val_auc=0.8049
model=graphsage top_k=50 fold=7 epoch=32 loss=11.7722 val_auc=0.8056
model=graphsage top_k=50 fold=7 epoch=33 loss=10.5775 val_auc=0.8059
model=graphsage top_k=50 fold=7 epoch=34 loss=10.0087 val_auc=0.8060
model=graphsage top_k=50 fold=7 epoch=35 loss=8.7289 val_auc=0.8020
model=graphsage top_k=50 fold=7 epoch=36 loss=7.8783 val_auc=0.8075
model=graphsage top_k=50 fold=7 epoch=37 loss=7.5131 val_auc=0.8092
model=graphsage top_k=50 fold=7 epoch=38 loss=8.4884 val_auc=0.8099
model=graphsage top_k=50 fold=7 epoch=39 loss=8.3732 val_auc=0.8108
model=graphsage top_k=50 fold=7 epoch=40 loss=6.9711 val_auc=0.8076
model=graphsage top_k=50 fold=7 epoch=41 loss=9.5627 val_auc=0.8035
model=graphsage top_k=50 fold=7 epoch=42 loss=9.8224 val_auc=0.8112
model=graphsage top_k=50 fold=7 epoch=43 loss=8.3377 val_auc=0.8127
model=graphsage top_k=50 fold=7 epoch=44 loss=6.9390 val_auc=0.8130
model=graphsage top_k=50 fold=7 epoch=45 loss=7.6232 val_auc=0.8136
model=graphsage top_k=50 fold=7 epoch=46 loss=7.3552 val_auc=0.8099
model=graphsage top_k=50 fold=7 epoch=47 loss=8.3541 val_auc=0.8069
model=graphsage top_k=50 fold=7 epoch=48 loss=10.3614 val_auc=0.8138
model=graphsage top_k=50 fold=7 epoch=49 loss=7.6447 val_auc=0.8146
model=graphsage top_k=50 fold=7 epoch=50 loss=6.5864 val_auc=0.8147
model=graphsage top_k=50 fold=7 epoch=51 loss=7.2155 val_auc=0.8154
model=graphsage top_k=50 fold=7 epoch=52 loss=6.4303 val_auc=0.8155
model=graphsage top_k=50 fold=7 epoch=53 loss=6.9041 val_auc=0.8140
model=graphsage top_k=50 fold=7 epoch=54 loss=7.7205 val_auc=0.8166
model=graphsage top_k=50 fold=7 epoch=55 loss=6.3608 val_auc=0.8168
model=graphsage top_k=50 fold=7 epoch=56 loss=6.5047 val_auc=0.8171
model=graphsage top_k=50 fold=7 epoch=57 loss=7.9480 val_auc=0.8176
model=graphsage top_k=50 fold=7 epoch=58 loss=6.9447 val_auc=0.8182
model=graphsage top_k=50 fold=7 epoch=59 loss=5.7952 val_auc=0.8182
model=graphsage top_k=50 fold=7 epoch=60 loss=7.4486 val_auc=0.8190
model=graphsage top_k=50 fold=7 epoch=61 loss=7.4826 val_auc=0.8190
model=graphsage top_k=50 fold=7 epoch=62 loss=6.0335 val_auc=0.8187
model=graphsage top_k=50 fold=7 epoch=63 loss=8.6323 val_auc=0.8185
model=graphsage top_k=50 fold=7 epoch=64 loss=11.7078 val_auc=0.8181
model=graphsage top_k=50 fold=7 epoch=65 loss=11.0524 val_auc=0.8177
model=graphsage top_k=50 fold=7 epoch=66 loss=7.1160 val_auc=0.8167
model=graphsage top_k=50 fold=7 epoch=67 loss=5.2227 val_auc=0.8085
model=graphsage top_k=50 fold=7 epoch=68 loss=8.4608 val_auc=0.8084
model=graphsage top_k=50 fold=7 epoch=69 loss=9.5932 val_auc=0.8162
model=graphsage top_k=50 fold=7 epoch=70 loss=5.9261 val_auc=0.8170
model=graphsage top_k=50 fold=7 epoch=71 loss=6.0378 val_auc=0.8172
model=graphsage top_k=50 fold=7 epoch=72 loss=6.6538 val_auc=0.8177
graphsage top_k=50 fold=7: early stopping at epoch 72

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=50 fold=8 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=graphsage top_k=50 fold=8 epoch=0 loss=17.5347 val_auc=0.5000
model=graphsage top_k=50 fold=8 epoch=1 loss=356.3087 val_auc=0.5000
model=graphsage top_k=50 fold=8 epoch=2 loss=160.1748 val_auc=0.7182
model=graphsage top_k=50 fold=8 epoch=3 loss=21.7410 val_auc=0.7438
model=graphsage top_k=50 fold=8 epoch=4 loss=17.2085 val_auc=0.5203
model=graphsage top_k=50 fold=8 epoch=5 loss=47.8175 val_auc=0.5382
model=graphsage top_k=50 fold=8 epoch=6 loss=35.7405 val_auc=0.7566
model=graphsage top_k=50 fold=8 epoch=7 loss=15.6228 val_auc=0.7548

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=50 fold=8 epoch=8 loss=42.8793 val_auc=0.7498
model=graphsage top_k=50 fold=8 epoch=9 loss=48.1450 val_auc=0.7593
model=graphsage top_k=50 fold=8 epoch=10 loss=39.4819 val_auc=0.7610
model=graphsage top_k=50 fold=8 epoch=11 loss=15.1996 val_auc=0.6342
model=graphsage top_k=50 fold=8 epoch=12 loss=23.7756 val_auc=0.5065
model=graphsage top_k=50 fold=8 epoch=13 loss=40.5130 val_auc=0.5235
model=graphsage top_k=50 fold=8 epoch=14 loss=32.4733 val_auc=0.7281
model=graphsage top_k=50 fold=8 epoch=15 loss=20.3790 val_auc=0.7647
model=graphsage top_k=50 fold=8 epoch=16 loss=11.8917 val_auc=0.7660
model=graphsage top_k=50 fold=8 epoch=17 loss=19.7329 val_auc=0.7672
model=graphsage top_k=50 fold=8 epoch=18 loss=13.2305 val_auc=0.7678
model=graphsage top_k=50 fold=8 epoch=19 loss=11.2603 val_auc=0.6871
model=graphsage top_k=50 fold=8 epoch=20 loss=17.0078 val_auc=0.5808
model=graphsage top_k=50 fold=8 epoch=21 loss=18.5081 val_auc=0.6225
model=graphsage top_k=50 fold=8 epoch=22 loss=18.2424 val_auc=0.7673
model=graphsage top_k=50 fold=8 epoch=23 loss=11.2226 val_auc=0.7719
model=graphsage top_k=50 fold=8 epoch=24 loss=10.5495 val_auc=0.7732
model=graphsage top_k=50 fold=8 epoch=25 loss=13.4617 val_auc=0.7744
model=graphsage top_k=50 fold=8 epoch=26 loss=13.1084 val_auc=0.7756
model=graphsage top_k=50 fold=8 epoch=27 loss=9.2587 val_auc=0.7713
model=graphsage top_k=50 fold=8 epoch=28 loss=11.7941 val_auc=0.7568
model=graphsage top_k=50 fold=8 epoch=29 loss=14.0093 val_auc=0.7632
model=graphsage top_k=50 fold=8 epoch=30 loss=13.8362 val_auc=0.7799
model=graphsage top_k=50 fold=8 epoch=31 loss=9.6356 val_auc=0.7827
model=graphsage top_k=50 fold=8 epoch=32 loss=9.2644 val_auc=0.7836
model=graphsage top_k=50 fold=8 epoch=33 loss=11.2428 val_auc=0.7840
model=graphsage top_k=50 fold=8 epoch=34 loss=10.2848 val_auc=0.7841
model=graphsage top_k=50 fold=8 epoch=35 loss=8.0154 val_auc=0.7848
model=graphsage top_k=50 fold=8 epoch=36 loss=8.5578 val_auc=0.7857
model=graphsage top_k=50 fold=8 epoch=37 loss=9.1452 val_auc=0.7862
model=graphsage top_k=50 fold=8 epoch=38 loss=9.5149 val_auc=0.7845
model=graphsage top_k=50 fold=8 epoch=39 loss=10.2024 val_auc=0.7885
model=graphsage top_k=50 fold=8 epoch=40 loss=9.9633 val_auc=0.7926
model=graphsage top_k=50 fold=8 epoch=41 loss=9.3829 val_auc=0.7940
model=graphsage top_k=50 fold=8 epoch=42 loss=8.5681 val_auc=0.7955
model=graphsage top_k=50 fold=8 epoch=43 loss=9.6012 val_auc=0.7925
model=graphsage top_k=50 fold=8 epoch=44 loss=11.0867 val_auc=0.7917
model=graphsage top_k=50 fold=8 epoch=45 loss=10.6451 val_auc=0.7979
model=graphsage top_k=50 fold=8 epoch=46 loss=8.1678 val_auc=0.7987
model=graphsage top_k=50 fold=8 epoch=47 loss=8.2926 val_auc=0.7993
model=graphsage top_k=50 fold=8 epoch=48 loss=9.4446 val_auc=0.7998
model=graphsage top_k=50 fold=8 epoch=49 loss=9.0097 val_auc=0.8001
model=graphsage top_k=50 fold=8 epoch=50 loss=8.2905 val_auc=0.7995
model=graphsage top_k=50 fold=8 epoch=51 loss=10.0604 val_auc=0.8008
model=graphsage top_k=50 fold=8 epoch=52 loss=7.8858 val_auc=0.8016
model=graphsage top_k=50 fold=8 epoch=53 loss=7.8835 val_auc=0.8022
model=graphsage top_k=50 fold=8 epoch=54 loss=10.7333 val_auc=0.8027
model=graphsage top_k=50 fold=8 epoch=55 loss=7.4187 val_auc=0.8028
model=graphsage top_k=50 fold=8 epoch=56 loss=7.8624 val_auc=0.8036
model=graphsage top_k=50 fold=8 epoch=57 loss=7.7442 val_auc=0.8053
model=graphsage top_k=50 fold=8 epoch=58 loss=8.2685 val_auc=0.8060
model=graphsage top_k=50 fold=8 epoch=59 loss=7.0325 val_auc=0.8061
model=graphsage top_k=50 fold=8 epoch=60 loss=8.3653 val_auc=0.8070
model=graphsage top_k=50 fold=8 epoch=61 loss=6.4667 val_auc=0.8079
model=graphsage top_k=50 fold=8 epoch=62 loss=6.9688 val_auc=0.8085
model=graphsage top_k=50 fold=8 epoch=63 loss=8.9439 val_auc=0.8088
model=graphsage top_k=50 fold=8 epoch=64 loss=9.7845 val_auc=0.8092
model=graphsage top_k=50 fold=8 epoch=65 loss=10.2353 val_auc=0.8095
model=graphsage top_k=50 fold=8 epoch=66 loss=8.0301 val_auc=0.8090
model=graphsage top_k=50 fold=8 epoch=67 loss=5.5345 val_auc=0.7992
model=graphsage top_k=50 fold=8 epoch=68 loss=10.1340 val_auc=0.8021
model=graphsage top_k=50 fold=8 epoch=69 loss=9.0312 val_auc=0.8103
model=graphsage top_k=50 fold=8 epoch=70 loss=6.9107 val_auc=0.8107
model=graphsage top_k=50 fold=8 epoch=71 loss=6.7822 val_auc=0.8107
model=graphsage top_k=50 fold=8 epoch=72 loss=6.6783 val_auc=0.8111
model=graphsage top_k=50 fold=8 epoch=73 loss=7.5833 val_auc=0.8116
model=graphsage top_k=50 fold=8 epoch=74 loss=6.3454 val_auc=0.8107
model=graphsage top_k=50 fold=8 epoch=75 loss=6.3351 val_auc=0.8076
model=graphsage top_k=50 fold=8 epoch=76 loss=8.7235 val_auc=0.8119
model=graphsage top_k=50 fold=8 epoch=77 loss=6.3790 val_auc=0.8132
model=graphsage top_k=50 fold=8 epoch=78 loss=5.2390 val_auc=0.8146
model=graphsage top_k=50 fold=8 epoch=79 loss=7.2275 val_auc=0.8157
model=graphsage top_k=50 fold=8 epoch=80 loss=6.3145 val_auc=0.8166
model=graphsage top_k=50 fold=8 epoch=81 loss=5.3201 val_auc=0.8173
model=graphsage top_k=50 fold=8 epoch=82 loss=6.3748 val_auc=0.8164
model=graphsage top_k=50 fold=8 epoch=83 loss=6.2114 val_auc=0.8191
model=graphsage top_k=50 fold=8 epoch=84 loss=5.9194 val_auc=0.8189
model=graphsage top_k=50 fold=8 epoch=85 loss=5.3750 val_auc=0.8191
model=graphsage top_k=50 fold=8 epoch=86 loss=7.2100 val_auc=0.8198
model=graphsage top_k=50 fold=8 epoch=87 loss=5.0199 val_auc=0.8207
model=graphsage top_k=50 fold=8 epoch=88 loss=4.4223 val_auc=0.8213
model=graphsage top_k=50 fold=8 epoch=89 loss=4.4006 val_auc=0.8219
model=graphsage top_k=50 fold=8 epoch=90 loss=4.2041 val_auc=0.8222
model=graphsage top_k=50 fold=8 epoch=91 loss=5.1434 val_auc=0.8226
model=graphsage top_k=50 fold=8 epoch=92 loss=3.9745 val_auc=0.8232
model=graphsage top_k=50 fold=8 epoch=93 loss=3.8835 val_auc=0.8238
model=graphsage top_k=50 fold=8 epoch=94 loss=5.4994 val_auc=0.8242
model=graphsage top_k=50 fold=8 epoch=95 loss=5.2880 val_auc=0.8244
model=graphsage top_k=50 fold=8 epoch=96 loss=5.3494 val_auc=0.8245
model=graphsage top_k=50 fold=8 epoch=97 loss=5.7460 val_auc=0.8242
model=graphsage top_k=50 fold=8 epoch=98 loss=5.3605 val_auc=0.8241
model=graphsage top_k=50 fold=8 epoch=99 loss=6.6465 val_auc=0.8237

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=50 fold=9 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=graphsage top_k=50 fold=9 epoch=0 loss=41.6175 val_auc=0.5000
model=graphsage top_k=50 fold=9 epoch=1 loss=346.4665 val_auc=0.5000
model=graphsage top_k=50 fold=9 epoch=2 loss=149.2972 val_auc=0.6608
model=graphsage top_k=50 fold=9 epoch=3 loss=37.8985 val_auc=0.7020
model=graphsage top_k=50 fold=9 epoch=4 loss=19.6093 val_auc=0.5278
model=graphsage top_k=50 fold=9 epoch=5 loss=43.0202 val_auc=0.5303
model=graphsage top_k=50 fold=9 epoch=6 loss=40.4869 val_auc=0.7442
model=graphsage top_k=50 fold=9 epoch=7 loss=13.5683 val_auc=0.7511
model=graphsage top_k=50 fold=9 epoch=8 loss=22.8102 val_auc=0.7544
model=graphsage top_k=50 fold=9 epoch=9 loss=16.7931 val_auc=0.7573
model=graphsage top_k=50 fold=9 epoch=10 loss=11.7314 val_auc=0.7248
model=graphsage top_k=50 fold=9 epoch=11 loss=15.8131 val_auc=0.7585
model=graphsage top_k=50 fold=9 epoch=12 loss=11.4587 val_auc=0.7660
model=graphsage top_k=50 fold=9 epoch=13 loss=12.4927 val_auc=0.7680
model=graphsage top_k=50 fold=9 epoch=14 loss=13.8838 val_auc=0.7693
model=graphsage top_k=50 fold=9 epoch=15 loss=10.0958 val_auc=0.7717
model=graphsage top_k=50 fold=9 epoch=16 loss=10.9694 val_auc=0.7724
model=graphsage top_k=50 fold=9 epoch=17 loss=9.1550 val_auc=0.7759
model=graphsage top_k=50 fold=9 epoch=18 loss=10.5622 val_auc=0.7800
model=graphsage top_k=50 fold=9 epoch=19 loss=12.0711 val_auc=0.7819
model=graphsage top_k=50 fold=9 epoch=20 loss=9.4598 val_auc=0.7830
model=graphsage top_k=50 fold=9 epoch=21 loss=7.8227 val_auc=0.7429
model=graphsage top_k=50 fold=9 epoch=22 loss=16.0358 val_auc=0.6971
model=graphsage top_k=50 fold=9 epoch=23 loss=16.7182 val_auc=0.7625
model=graphsage top_k=50 fold=9 epoch=24 loss=15.0693 val_auc=0.7889
model=graphsage top_k=50 fold=9 epoch=25 loss=10.2108 val_auc=0.7902
model=graphsage top_k=50 fold=9 epoch=26 loss=9.5464 val_auc=0.7912
model=graphsage top_k=50 fold=9 epoch=27 loss=8.3556 val_auc=0.7913
model=graphsage top_k=50 fold=9 epoch=28 loss=7.4344 val_auc=0.7933
model=graphsage top_k=50 fold=9 epoch=29 loss=6.9179 val_auc=0.7962
model=graphsage top_k=50 fold=9 epoch=30 loss=7.1837 val_auc=0.7982
model=graphsage top_k=50 fold=9 epoch=31 loss=12.0894 val_auc=0.7995
model=graphsage top_k=50 fold=9 epoch=32 loss=13.4393 val_auc=0.8005
model=graphsage top_k=50 fold=9 epoch=33 loss=12.0334 val_auc=0.8009
model=graphsage top_k=50 fold=9 epoch=34 loss=7.4186 val_auc=0.7770
model=graphsage top_k=50 fold=9 epoch=35 loss=12.9201 val_auc=0.6773
model=graphsage top_k=50 fold=9 epoch=36 loss=15.9150 val_auc=0.6952
model=graphsage top_k=50 fold=9 epoch=37 loss=17.3424 val_auc=0.7848
model=graphsage top_k=50 fold=9 epoch=38 loss=14.0929 val_auc=0.8035
model=graphsage top_k=50 fold=9 epoch=39 loss=8.7777 val_auc=0.8038
model=graphsage top_k=50 fold=9 epoch=40 loss=11.6957 val_auc=0.8034
model=graphsage top_k=50 fold=9 epoch=41 loss=12.6685 val_auc=0.8031
model=graphsage top_k=50 fold=9 epoch=42 loss=10.7957 val_auc=0.8029
model=graphsage top_k=50 fold=9 epoch=43 loss=6.3725 val_auc=0.8022
model=graphsage top_k=50 fold=9 epoch=44 loss=7.1006 val_auc=0.7985
model=graphsage top_k=50 fold=9 epoch=45 loss=9.2520 val_auc=0.7993
model=graphsage top_k=50 fold=9 epoch=46 loss=7.8002 val_auc=0.8033
model=graphsage top_k=50 fold=9 epoch=47 loss=6.9322 val_auc=0.8039
model=graphsage top_k=50 fold=9 epoch=48 loss=6.5884 val_auc=0.8043
model=graphsage top_k=50 fold=9 epoch=49 loss=8.6968 val_auc=0.8046
model=graphsage top_k=50 fold=9 epoch=50 loss=7.7584 val_auc=0.8048
model=graphsage top_k=50 fold=9 epoch=51 loss=6.6849 val_auc=0.8053
model=graphsage top_k=50 fold=9 epoch=52 loss=6.2718 val_auc=0.8059
model=graphsage top_k=50 fold=9 epoch=53 loss=6.0664 val_auc=0.8070
model=graphsage top_k=50 fold=9 epoch=54 loss=6.1671 val_auc=0.8078
model=graphsage top_k=50 fold=9 epoch=55 loss=5.8502 val_auc=0.8088
model=graphsage top_k=50 fold=9 epoch=56 loss=6.4588 val_auc=0.8098
model=graphsage top_k=50 fold=9 epoch=57 loss=5.4938 val_auc=0.8107
model=graphsage top_k=50 fold=9 epoch=58 loss=5.7161 val_auc=0.8115
model=graphsage top_k=50 fold=9 epoch=59 loss=7.2195 val_auc=0.8121
model=graphsage top_k=50 fold=9 epoch=60 loss=5.6142 val_auc=0.8125
model=graphsage top_k=50 fold=9 epoch=61 loss=5.7958 val_auc=0.8130
model=graphsage top_k=50 fold=9 epoch=62 loss=6.5289 val_auc=0.8136
model=graphsage top_k=50 fold=9 epoch=63 loss=5.0525 val_auc=0.8140
model=graphsage top_k=50 fold=9 epoch=64 loss=4.6211 val_auc=0.8145
model=graphsage top_k=50 fold=9 epoch=65 loss=5.0915 val_auc=0.8148
model=graphsage top_k=50 fold=9 epoch=66 loss=5.7473 val_auc=0.8148
model=graphsage top_k=50 fold=9 epoch=67 loss=5.6491 val_auc=0.8149
model=graphsage top_k=50 fold=9 epoch=68 loss=4.4751 val_auc=0.8153
model=graphsage top_k=50 fold=9 epoch=69 loss=4.3095 val_auc=0.8158
model=graphsage top_k=50 fold=9 epoch=70 loss=5.7780 val_auc=0.8162
model=graphsage top_k=50 fold=9 epoch=71 loss=5.5057 val_auc=0.8166
model=graphsage top_k=50 fold=9 epoch=72 loss=5.2523 val_auc=0.8170
model=graphsage top_k=50 fold=9 epoch=73 loss=4.3076 val_auc=0.8176
model=graphsage top_k=50 fold=9 epoch=74 loss=5.0016 val_auc=0.8185
model=graphsage top_k=50 fold=9 epoch=75 loss=4.6115 val_auc=0.8195
model=graphsage top_k=50 fold=9 epoch=76 loss=4.9750 val_auc=0.8202
model=graphsage top_k=50 fold=9 epoch=77 loss=3.7590 val_auc=0.8208
model=graphsage top_k=50 fold=9 epoch=78 loss=4.8084 val_auc=0.8212
model=graphsage top_k=50 fold=9 epoch=79 loss=3.8526 val_auc=0.8216
model=graphsage top_k=50 fold=9 epoch=80 loss=4.1486 val_auc=0.8218
model=graphsage top_k=50 fold=9 epoch=81 loss=4.0396 val_auc=0.8222
model=graphsage top_k=50 fold=9 epoch=82 loss=5.2009 val_auc=0.8222
model=graphsage top_k=50 fold=9 epoch=83 loss=4.2680 val_auc=0.8221
model=graphsage top_k=50 fold=9 epoch=84 loss=4.5117 val_auc=0.8216
model=graphsage top_k=50 fold=9 epoch=85 loss=4.1088 val_auc=0.8206
model=graphsage top_k=50 fold=9 epoch=86 loss=4.1031 val_auc=0.8201
model=graphsage top_k=50 fold=9 epoch=87 loss=4.7687 val_auc=0.8200
model=graphsage top_k=50 fold=9 epoch=88 loss=4.4244 val_auc=0.8200
model=graphsage top_k=50 fold=9 epoch=89 loss=4.0546 val_auc=0.8198
model=graphsage top_k=50 fold=9 epoch=90 loss=4.3869 val_auc=0.8197
model=graphsage top_k=50 fold=9 epoch=91 loss=3.8757 val_auc=0.8199
model=graphsage top_k=50 fold=9 epoch=92 loss=4.0672 val_auc=0.8201
model=graphsage top_k=50 fold=9 epoch=93 loss=4.3411 val_auc=0.8206
graphsage top_k=50 fold=9: early stopping at epoch 93

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

######## Model=graphsage top_k=100 ########

===== Model=graphsage top_k=100 fold=0 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=100 fold=0 epoch=0 loss=52.0289 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=100 fold=0 epoch=1 loss=229.6111 val_auc=0.4995
model=graphsage top_k=100 fold=0 epoch=2 loss=81.8041 val_auc=0.5077
model=graphsage top_k=100 fold=0 epoch=3 loss=80.1952 val_auc=0.5138
model=graphsage top_k=100 fold=0 epoch=4 loss=70.6790 val_auc=0.6256

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=100 fold=0 epoch=5 loss=18.0173 val_auc=0.7350
model=graphsage top_k=100 fold=0 epoch=6 loss=46.3657 val_auc=0.7491
model=graphsage top_k=100 fold=0 epoch=7 loss=53.8123 val_auc=0.7551
model=graphsage top_k=100 fold=0 epoch=8 loss=28.3519 val_auc=0.7173
model=graphsage top_k=100 fold=0 epoch=9 loss=19.0490 val_auc=0.5411
model=graphsage top_k=100 fold=0 epoch=10 loss=27.3094 val_auc=0.6608
model=graphsage top_k=100 fold=0 epoch=11 loss=19.1887 val_auc=0.7705
model=graphsage top_k=100 fold=0 epoch=12 loss=11.1059 val_auc=0.7737
model=graphsage top_k=100 fold=0 epoch=13 loss=13.1972 val_auc=0.7739
model=graphsage top_k=100 fold=0 epoch=14 loss=9.3712 val_auc=0.7083
model=graphsage top_k=100 fold=0 epoch=15 loss=17.1729 val_auc=0.7315
model=graphsage top_k=100 fold=0 epoch=16 loss=12.4457 val_auc=0.7818
model=graphsage top_k=100 fold=0 epoch=17 loss=11.4320 val_auc=0.7851
model=graphsage top_k=100 fold=0 epoch=18 loss=10.8071 val_auc=0.7865
model=graphsage top_k=100 fold=0 epoch=19 loss=11.3941 val_auc=0.7875
model=graphsage top_k=100 fold=0 epoch=20 loss=9.7811 val_auc=0.7884
model=graphsage top_k=100 fold=0 epoch=21 loss=8.7570 val_auc=0.7879
model=graphsage top_k=100 fold=0 epoch=22 loss=9.0436 val_auc=0.7897
model=graphsage top_k=100 fold=0 epoch=23 loss=8.6252 val_auc=0.7914
model=graphsage top_k=100 fold=0 epoch=24 loss=9.0882 val_auc=0.7926
model=graphsage top_k=100 fold=0 epoch=25 loss=8.8814 val_auc=0.7905
model=graphsage top_k=100 fold=0 epoch=26 loss=10.3956 val_auc=0.7917
model=graphsage top_k=100 fold=0 epoch=27 loss=9.5751 val_auc=0.7954
model=graphsage top_k=100 fold=0 epoch=28 loss=6.7247 val_auc=0.7974
model=graphsage top_k=100 fold=0 epoch=29 loss=11.6387 val_auc=0.7990
model=graphsage top_k=100 fold=0 epoch=30 loss=11.7654 val_auc=0.8003
model=graphsage top_k=100 fold=0 epoch=31 loss=7.2245 val_auc=0.8013
model=graphsage top_k=100 fold=0 epoch=32 loss=7.0355 val_auc=0.8025
model=graphsage top_k=100 fold=0 epoch=33 loss=7.0909 val_auc=0.8039
model=graphsage top_k=100 fold=0 epoch=34 loss=8.7265 val_auc=0.8048
model=graphsage top_k=100 fold=0 epoch=35 loss=9.4922 val_auc=0.8053
model=graphsage top_k=100 fold=0 epoch=36 loss=6.0607 val_auc=0.8055
model=graphsage top_k=100 fold=0 epoch=37 loss=5.7142 val_auc=0.8061
model=graphsage top_k=100 fold=0 epoch=38 loss=7.4308 val_auc=0.8068
model=graphsage top_k=100 fold=0 epoch=39 loss=5.5879 val_auc=0.8075
model=graphsage top_k=100 fold=0 epoch=40 loss=8.7986 val_auc=0.8082
model=graphsage top_k=100 fold=0 epoch=41 loss=7.4012 val_auc=0.8089
model=graphsage top_k=100 fold=0 epoch=42 loss=5.6449 val_auc=0.8097
model=graphsage top_k=100 fold=0 epoch=43 loss=5.3944 val_auc=0.8106
model=graphsage top_k=100 fold=0 epoch=44 loss=6.9352 val_auc=0.8113
model=graphsage top_k=100 fold=0 epoch=45 loss=6.4955 val_auc=0.8117
model=graphsage top_k=100 fold=0 epoch=46 loss=7.1004 val_auc=0.8119
model=graphsage top_k=100 fold=0 epoch=47 loss=5.1865 val_auc=0.8131
model=graphsage top_k=100 fold=0 epoch=48 loss=5.8768 val_auc=0.8138
model=graphsage top_k=100 fold=0 epoch=49 loss=6.3045 val_auc=0.8144
model=graphsage top_k=100 fold=0 epoch=50 loss=5.9842 val_auc=0.8150
model=graphsage top_k=100 fold=0 epoch=51 loss=6.2282 val_auc=0.8151
model=graphsage top_k=100 fold=0 epoch=52 loss=5.6223 val_auc=0.8148
model=graphsage top_k=100 fold=0 epoch=53 loss=5.9595 val_auc=0.8146
model=graphsage top_k=100 fold=0 epoch=54 loss=6.3935 val_auc=0.8143
model=graphsage top_k=100 fold=0 epoch=55 loss=4.3947 val_auc=0.8141
model=graphsage top_k=100 fold=0 epoch=56 loss=4.9908 val_auc=0.8142
model=graphsage top_k=100 fold=0 epoch=57 loss=5.7077 val_auc=0.8144
model=graphsage top_k=100 fold=0 epoch=58 loss=5.6740 val_auc=0.8149
model=graphsage top_k=100 fold=0 epoch=59 loss=5.3967 val_auc=0.8151
model=graphsage top_k=100 fold=0 epoch=60 loss=4.9518 val_auc=0.8154
model=graphsage top_k=100 fold=0 epoch=61 loss=4.7393 val_auc=0.8159
model=graphsage top_k=100 fold=0 epoch=62 loss=4.2265 val_auc=0.8163
model=graphsage top_k=100 fold=0 epoch=63 loss=4.8597 val_auc=0.8167
model=graphsage top_k=100 fold=0 epoch=64 loss=4.8989 val_auc=0.8168
model=graphsage top_k=100 fold=0 epoch=65 loss=5.1280 val_auc=0.8169
model=graphsage top_k=100 fold=0 epoch=66 loss=4.4561 val_auc=0.8168
model=graphsage top_k=100 fold=0 epoch=67 loss=5.0673 val_auc=0.8166
model=graphsage top_k=100 fold=0 epoch=68 loss=4.4530 val_auc=0.8164
model=graphsage top_k=100 fold=0 epoch=69 loss=5.1293 val_auc=0.8163
model=graphsage top_k=100 fold=0 epoch=70 loss=7.3957 val_auc=0.8166
model=graphsage top_k=100 fold=0 epoch=71 loss=3.9578 val_auc=0.8171
model=graphsage top_k=100 fold=0 epoch=72 loss=4.6490 val_auc=0.8173
model=graphsage top_k=100 fold=0 epoch=73 loss=5.2951 val_auc=0.8174
model=graphsage top_k=100 fold=0 epoch=74 loss=4.4060 val_auc=0.8176
model=graphsage top_k=100 fold=0 epoch=75 loss=3.7632 val_auc=0.8177
model=graphsage top_k=100 fold=0 epoch=76 loss=4.0676 val_auc=0.8177
model=graphsage top_k=100 fold=0 epoch=77 loss=5.0837 val_auc=0.8176
model=graphsage top_k=100 fold=0 epoch=78 loss=5.1686 val_auc=0.8173
model=graphsage top_k=100 fold=0 epoch=79 loss=3.8452 val_auc=0.8172
model=graphsage top_k=100 fold=0 epoch=80 loss=4.5644 val_auc=0.8171
model=graphsage top_k=100 fold=0 epoch=81 loss=5.1148 val_auc=0.8172
model=graphsage top_k=100 fold=0 epoch=82 loss=5.4107 val_auc=0.8173
model=graphsage top_k=100 fold=0 epoch=83 loss=3.9529 val_auc=0.8174
model=graphsage top_k=100 fold=0 epoch=84 loss=4.8769 val_auc=0.8173
model=graphsage top_k=100 fold=0 epoch=85 loss=3.7015 val_auc=0.8174
model=graphsage top_k=100 fold=0 epoch=86 loss=3.5912 val_auc=0.8178
model=graphsage top_k=100 fold=0 epoch=87 loss=3.9727 val_auc=0.8185
model=graphsage top_k=100 fold=0 epoch=88 loss=4.2199 val_auc=0.8192
model=graphsage top_k=100 fold=0 epoch=89 loss=4.2419 val_auc=0.8197
model=graphsage top_k=100 fold=0 epoch=90 loss=4.7796 val_auc=0.8202
model=graphsage top_k=100 fold=0 epoch=91 loss=4.1922 val_auc=0.8205
model=graphsage top_k=100 fold=0 epoch=92 loss=3.6462 val_auc=0.8203
model=graphsage top_k=100 fold=0 epoch=93 loss=3.5151 val_auc=0.8201
model=graphsage top_k=100 fold=0 epoch=94 loss=4.3021 val_auc=0.8203
model=graphsage top_k=100 fold=0 epoch=95 loss=3.8592 val_auc=0.8210
model=graphsage top_k=100 fold=0 epoch=96 loss=3.5649 val_auc=0.8210
model=graphsage top_k=100 fold=0 epoch=97 loss=4.0651 val_auc=0.8208
model=graphsage top_k=100 fold=0 epoch=98 loss=3.6676 val_auc=0.8210
model=graphsage top_k=100 fold=0 epoch=99 loss=3.2408 val_auc=0.8218

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=100 fold=1 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=graphsage top_k=100 fold=1 epoch=0 loss=37.5981 val_auc=0.5000
model=graphsage top_k=100 fold=1 epoch=1 loss=301.3812 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=100 fold=1 epoch=2 loss=115.5674 val_auc=0.6047
model=graphsage top_k=100 fold=1 epoch=3 loss=60.9621 val_auc=0.6379
model=graphsage top_k=100 fold=1 epoch=4 loss=42.3219 val_auc=0.7018
model=graphsage top_k=100 fold=1 epoch=5 loss=19.7049 val_auc=0.7668
model=graphsage top_k=100 fold=1 epoch=6 loss=11.4017 val_auc=0.7747
model=graphsage top_k=100 fold=1 epoch=7 loss=16.0363 val_auc=0.7783
model=graphsage top_k=100 fold=1 epoch=8 loss=13.4734 val_auc=0.7494
model=graphsage top_k=100 fold=1 epoch=9 loss=13.9299 val_auc=0.7725
model=graphsage top_k=100 fold=1 epoch=10 loss=15.1820 val_auc=0.7769
model=graphsage top_k=100 fold=1 epoch=11 loss=12.6832 val_auc=0.7771
model=graphsage top_k=100 fold=1 epoch=12 loss=14.9545 val_auc=0.7747
model=graphsage top_k=100 fold=1 epoch=13 loss=12.0477 val_auc=0.7735
model=graphsage top_k=100 fold=1 epoch=14 loss=12.0091 val_auc=0.7793
model=graphsage top_k=100 fold=1 epoch=15 loss=11.6052 val_auc=0.7818
model=graphsage top_k=100 fold=1 epoch=16 loss=9.1355 val_auc=0.7837
model=graphsage top_k=100 fold=1 epoch=17 loss=9.8622 val_auc=0.7861
model=graphsage top_k=100 fold=1 epoch=18 loss=10.9884 val_auc=0.7901
model=graphsage top_k=100 fold=1 epoch=19 loss=9.6357 val_auc=0.7924
model=graphsage top_k=100 fold=1 epoch=20 loss=14.9738 val_auc=0.7938
model=graphsage top_k=100 fold=1 epoch=21 loss=12.4610 val_auc=0.7948
model=graphsage top_k=100 fold=1 epoch=22 loss=8.3444 val_auc=0.7845
model=graphsage top_k=100 fold=1 epoch=23 loss=8.5463 val_auc=0.7882
model=graphsage top_k=100 fold=1 epoch=24 loss=9.5672 val_auc=0.7990
model=graphsage top_k=100 fold=1 epoch=25 loss=8.3024 val_auc=0.8002
model=graphsage top_k=100 fold=1 epoch=26 loss=17.8650 val_auc=0.8007
model=graphsage top_k=100 fold=1 epoch=27 loss=16.5425 val_auc=0.8014
model=graphsage top_k=100 fold=1 epoch=28 loss=18.2081 val_auc=0.8019
model=graphsage top_k=100 fold=1 epoch=29 loss=10.9643 val_auc=0.7845
model=graphsage top_k=100 fold=1 epoch=30 loss=12.6588 val_auc=0.6910
model=graphsage top_k=100 fold=1 epoch=31 loss=23.1371 val_auc=0.7064
model=graphsage top_k=100 fold=1 epoch=32 loss=18.4227 val_auc=0.7908
model=graphsage top_k=100 fold=1 epoch=33 loss=12.9710 val_auc=0.8029
model=graphsage top_k=100 fold=1 epoch=34 loss=6.3678 val_auc=0.8033
model=graphsage top_k=100 fold=1 epoch=35 loss=9.4246 val_auc=0.8040
model=graphsage top_k=100 fold=1 epoch=36 loss=10.7796 val_auc=0.8048
model=graphsage top_k=100 fold=1 epoch=37 loss=8.4959 val_auc=0.8054
model=graphsage top_k=100 fold=1 epoch=38 loss=7.9251 val_auc=0.8043
model=graphsage top_k=100 fold=1 epoch=39 loss=8.7938 val_auc=0.8057
model=graphsage top_k=100 fold=1 epoch=40 loss=7.4934 val_auc=0.8065
model=graphsage top_k=100 fold=1 epoch=41 loss=7.4547 val_auc=0.8073
model=graphsage top_k=100 fold=1 epoch=42 loss=7.9496 val_auc=0.8079
model=graphsage top_k=100 fold=1 epoch=43 loss=6.4908 val_auc=0.8090
model=graphsage top_k=100 fold=1 epoch=44 loss=5.8055 val_auc=0.8013
model=graphsage top_k=100 fold=1 epoch=45 loss=10.0233 val_auc=0.7801
model=graphsage top_k=100 fold=1 epoch=46 loss=13.2065 val_auc=0.7986
model=graphsage top_k=100 fold=1 epoch=47 loss=9.6407 val_auc=0.8133
model=graphsage top_k=100 fold=1 epoch=48 loss=6.7789 val_auc=0.8144
model=graphsage top_k=100 fold=1 epoch=49 loss=5.3580 val_auc=0.8150
model=graphsage top_k=100 fold=1 epoch=50 loss=8.1523 val_auc=0.8158
model=graphsage top_k=100 fold=1 epoch=51 loss=8.2920 val_auc=0.8161
model=graphsage top_k=100 fold=1 epoch=52 loss=6.9020 val_auc=0.8103
model=graphsage top_k=100 fold=1 epoch=53 loss=6.7553 val_auc=0.8151
model=graphsage top_k=100 fold=1 epoch=54 loss=7.3103 val_auc=0.8174
model=graphsage top_k=100 fold=1 epoch=55 loss=7.9397 val_auc=0.8169
model=graphsage top_k=100 fold=1 epoch=56 loss=8.5592 val_auc=0.8167
model=graphsage top_k=100 fold=1 epoch=57 loss=7.7608 val_auc=0.8168
model=graphsage top_k=100 fold=1 epoch=58 loss=6.1863 val_auc=0.8168
model=graphsage top_k=100 fold=1 epoch=59 loss=5.4740 val_auc=0.8173
model=graphsage top_k=100 fold=1 epoch=60 loss=6.6115 val_auc=0.8192
model=graphsage top_k=100 fold=1 epoch=61 loss=6.5273 val_auc=0.8201
model=graphsage top_k=100 fold=1 epoch=62 loss=5.4626 val_auc=0.8209
model=graphsage top_k=100 fold=1 epoch=63 loss=5.8640 val_auc=0.8218
model=graphsage top_k=100 fold=1 epoch=64 loss=5.6374 val_auc=0.8227
model=graphsage top_k=100 fold=1 epoch=65 loss=5.3971 val_auc=0.8081
model=graphsage top_k=100 fold=1 epoch=66 loss=11.1747 val_auc=0.7862
model=graphsage top_k=100 fold=1 epoch=67 loss=12.5742 val_auc=0.8061
model=graphsage top_k=100 fold=1 epoch=68 loss=9.7434 val_auc=0.8231
model=graphsage top_k=100 fold=1 epoch=69 loss=7.2942 val_auc=0.8235
model=graphsage top_k=100 fold=1 epoch=70 loss=6.2038 val_auc=0.8231
model=graphsage top_k=100 fold=1 epoch=71 loss=6.0668 val_auc=0.8232
model=graphsage top_k=100 fold=1 epoch=72 loss=6.2732 val_auc=0.8236
model=graphsage top_k=100 fold=1 epoch=73 loss=5.0803 val_auc=0.8243
model=graphsage top_k=100 fold=1 epoch=74 loss=5.5005 val_auc=0.8246
model=graphsage top_k=100 fold=1 epoch=75 loss=5.0661 val_auc=0.8254
model=graphsage top_k=100 fold=1 epoch=76 loss=4.3967 val_auc=0.8265
model=graphsage top_k=100 fold=1 epoch=77 loss=4.3198 val_auc=0.8274
model=graphsage top_k=100 fold=1 epoch=78 loss=4.0320 val_auc=0.8283
model=graphsage top_k=100 fold=1 epoch=79 loss=4.6499 val_auc=0.8290
model=graphsage top_k=100 fold=1 epoch=80 loss=3.9119 val_auc=0.8300
model=graphsage top_k=100 fold=1 epoch=81 loss=4.6579 val_auc=0.8313
model=graphsage top_k=100 fold=1 epoch=82 loss=4.2737 val_auc=0.8324
model=graphsage top_k=100 fold=1 epoch=83 loss=5.5260 val_auc=0.8329
model=graphsage top_k=100 fold=1 epoch=84 loss=5.0746 val_auc=0.8330
model=graphsage top_k=100 fold=1 epoch=85 loss=4.1364 val_auc=0.8326
model=graphsage top_k=100 fold=1 epoch=86 loss=5.2738 val_auc=0.8321
model=graphsage top_k=100 fold=1 epoch=87 loss=6.6447 val_auc=0.8315
model=graphsage top_k=100 fold=1 epoch=88 loss=4.3311 val_auc=0.8312
model=graphsage top_k=100 fold=1 epoch=89 loss=4.2438 val_auc=0.8311
model=graphsage top_k=100 fold=1 epoch=90 loss=4.5199 val_auc=0.8311
model=graphsage top_k=100 fold=1 epoch=91 loss=3.3142 val_auc=0.8329
model=graphsage top_k=100 fold=1 epoch=92 loss=3.7865 val_auc=0.8351
model=graphsage top_k=100 fold=1 epoch=93 loss=3.5956 val_auc=0.8363
model=graphsage top_k=100 fold=1 epoch=94 loss=3.8220 val_auc=0.8361
model=graphsage top_k=100 fold=1 epoch=95 loss=3.4657 val_auc=0.8356
model=graphsage top_k=100 fold=1 epoch=96 loss=4.8254 val_auc=0.8352
model=graphsage top_k=100 fold=1 epoch=97 loss=2.9775 val_auc=0.8350
model=graphsage top_k=100 fold=1 epoch=98 loss=4.5179 val_auc=0.8346
model=graphsage top_k=100 fold=1 epoch=99 loss=3.9484 val_auc=0.8335

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=100 fold=2 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=graphsage top_k=100 fold=2 epoch=0 loss=35.1997 val_auc=0.5000
model=graphsage top_k=100 fold=2 epoch=1 loss=300.6913 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=100 fold=2 epoch=2 loss=106.2207 val_auc=0.5190

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=100 fold=2 epoch=3 loss=85.9680 val_auc=0.6560
model=graphsage top_k=100 fold=2 epoch=4 loss=70.7594 val_auc=0.7382
model=graphsage top_k=100 fold=2 epoch=5 loss=16.2208 val_auc=0.5001
model=graphsage top_k=100 fold=2 epoch=6 loss=56.2866 val_auc=0.5000
model=graphsage top_k=100 fold=2 epoch=7 loss=73.8773 val_auc=0.5093
model=graphsage top_k=100 fold=2 epoch=8 loss=43.2063 val_auc=0.7529
model=graphsage top_k=100 fold=2 epoch=9 loss=12.3696 val_auc=0.7524
model=graphsage top_k=100 fold=2 epoch=10 loss=30.3620 val_auc=0.7527
model=graphsage top_k=100 fold=2 epoch=11 loss=39.7635 val_auc=0.7523
model=graphsage top_k=100 fold=2 epoch=12 loss=36.2683 val_auc=0.7526
model=graphsage top_k=100 fold=2 epoch=13 loss=23.4798 val_auc=0.7529
model=graphsage top_k=100 fold=2 epoch=14 loss=13.6687 val_auc=0.7389
model=graphsage top_k=100 fold=2 epoch=15 loss=16.9932 val_auc=0.7529
model=graphsage top_k=100 fold=2 epoch=16 loss=16.9421 val_auc=0.7588
model=graphsage top_k=100 fold=2 epoch=17 loss=10.6808 val_auc=0.7619
model=graphsage top_k=100 fold=2 epoch=18 loss=11.3148 val_auc=0.7627
model=graphsage top_k=100 fold=2 epoch=19 loss=10.1238 val_auc=0.7638
model=graphsage top_k=100 fold=2 epoch=20 loss=10.1856 val_auc=0.7611
model=graphsage top_k=100 fold=2 epoch=21 loss=13.8218 val_auc=0.7429
model=graphsage top_k=100 fold=2 epoch=22 loss=16.6375 val_auc=0.7622
model=graphsage top_k=100 fold=2 epoch=23 loss=14.5449 val_auc=0.7709
model=graphsage top_k=100 fold=2 epoch=24 loss=9.5520 val_auc=0.7727
model=graphsage top_k=100 fold=2 epoch=25 loss=9.0236 val_auc=0.7744
model=graphsage top_k=100 fold=2 epoch=26 loss=10.1341 val_auc=0.7756
model=graphsage top_k=100 fold=2 epoch=27 loss=8.3937 val_auc=0.7773
model=graphsage top_k=100 fold=2 epoch=28 loss=10.4107 val_auc=0.7776
model=graphsage top_k=100 fold=2 epoch=29 loss=9.8376 val_auc=0.7787
model=graphsage top_k=100 fold=2 epoch=30 loss=10.2659 val_auc=0.7796
model=graphsage top_k=100 fold=2 epoch=31 loss=8.6459 val_auc=0.7805
model=graphsage top_k=100 fold=2 epoch=32 loss=8.1951 val_auc=0.7825
model=graphsage top_k=100 fold=2 epoch=33 loss=7.8447 val_auc=0.7840
model=graphsage top_k=100 fold=2 epoch=34 loss=11.7939 val_auc=0.7859
model=graphsage top_k=100 fold=2 epoch=35 loss=9.9905 val_auc=0.7880
model=graphsage top_k=100 fold=2 epoch=36 loss=8.8755 val_auc=0.7886
model=graphsage top_k=100 fold=2 epoch=37 loss=8.3779 val_auc=0.7911
model=graphsage top_k=100 fold=2 epoch=38 loss=8.5532 val_auc=0.7925
model=graphsage top_k=100 fold=2 epoch=39 loss=8.4009 val_auc=0.7941
model=graphsage top_k=100 fold=2 epoch=40 loss=8.1832 val_auc=0.7959
model=graphsage top_k=100 fold=2 epoch=41 loss=7.4842 val_auc=0.7920
model=graphsage top_k=100 fold=2 epoch=42 loss=10.2479 val_auc=0.7833
model=graphsage top_k=100 fold=2 epoch=43 loss=11.7898 val_auc=0.7970
model=graphsage top_k=100 fold=2 epoch=44 loss=7.6117 val_auc=0.8013
model=graphsage top_k=100 fold=2 epoch=45 loss=6.0472 val_auc=0.8024
model=graphsage top_k=100 fold=2 epoch=46 loss=8.0210 val_auc=0.8034
model=graphsage top_k=100 fold=2 epoch=47 loss=8.1828 val_auc=0.8042
model=graphsage top_k=100 fold=2 epoch=48 loss=8.0562 val_auc=0.8019
model=graphsage top_k=100 fold=2 epoch=49 loss=9.8216 val_auc=0.7899
model=graphsage top_k=100 fold=2 epoch=50 loss=8.9229 val_auc=0.7988
model=graphsage top_k=100 fold=2 epoch=51 loss=7.6003 val_auc=0.8051
model=graphsage top_k=100 fold=2 epoch=52 loss=6.6029 val_auc=0.8048
model=graphsage top_k=100 fold=2 epoch=53 loss=10.1233 val_auc=0.8047
model=graphsage top_k=100 fold=2 epoch=54 loss=12.1256 val_auc=0.8045
model=graphsage top_k=100 fold=2 epoch=55 loss=9.5688 val_auc=0.8045
model=graphsage top_k=100 fold=2 epoch=56 loss=6.5460 val_auc=0.8040
model=graphsage top_k=100 fold=2 epoch=57 loss=6.5876 val_auc=0.8006
model=graphsage top_k=100 fold=2 epoch=58 loss=7.8194 val_auc=0.8026
model=graphsage top_k=100 fold=2 epoch=59 loss=7.6925 val_auc=0.8052
model=graphsage top_k=100 fold=2 epoch=60 loss=6.5752 val_auc=0.8055
model=graphsage top_k=100 fold=2 epoch=61 loss=7.2068 val_auc=0.8059
model=graphsage top_k=100 fold=2 epoch=62 loss=10.1651 val_auc=0.8063
model=graphsage top_k=100 fold=2 epoch=63 loss=8.7138 val_auc=0.8066
model=graphsage top_k=100 fold=2 epoch=64 loss=5.7561 val_auc=0.8073
model=graphsage top_k=100 fold=2 epoch=65 loss=5.8488 val_auc=0.8069
model=graphsage top_k=100 fold=2 epoch=66 loss=7.2180 val_auc=0.8082
model=graphsage top_k=100 fold=2 epoch=67 loss=6.9658 val_auc=0.8093
model=graphsage top_k=100 fold=2 epoch=68 loss=5.6340 val_auc=0.8097
model=graphsage top_k=100 fold=2 epoch=69 loss=7.0923 val_auc=0.8101
model=graphsage top_k=100 fold=2 epoch=70 loss=5.9193 val_auc=0.8106
model=graphsage top_k=100 fold=2 epoch=71 loss=5.5839 val_auc=0.8113
model=graphsage top_k=100 fold=2 epoch=72 loss=5.4461 val_auc=0.8120
model=graphsage top_k=100 fold=2 epoch=73 loss=5.5288 val_auc=0.8125
model=graphsage top_k=100 fold=2 epoch=74 loss=5.4165 val_auc=0.8131
model=graphsage top_k=100 fold=2 epoch=75 loss=4.4874 val_auc=0.8138
model=graphsage top_k=100 fold=2 epoch=76 loss=4.9754 val_auc=0.8149
model=graphsage top_k=100 fold=2 epoch=77 loss=5.0895 val_auc=0.8160
model=graphsage top_k=100 fold=2 epoch=78 loss=6.0193 val_auc=0.8170
model=graphsage top_k=100 fold=2 epoch=79 loss=4.6232 val_auc=0.8182
model=graphsage top_k=100 fold=2 epoch=80 loss=5.1613 val_auc=0.8191
model=graphsage top_k=100 fold=2 epoch=81 loss=6.1011 val_auc=0.8199
model=graphsage top_k=100 fold=2 epoch=82 loss=5.4522 val_auc=0.8201
model=graphsage top_k=100 fold=2 epoch=83 loss=5.4013 val_auc=0.8201
model=graphsage top_k=100 fold=2 epoch=84 loss=5.7524 val_auc=0.8202
model=graphsage top_k=100 fold=2 epoch=85 loss=4.9913 val_auc=0.8203
model=graphsage top_k=100 fold=2 epoch=86 loss=4.9164 val_auc=0.8181
model=graphsage top_k=100 fold=2 epoch=87 loss=6.8489 val_auc=0.8158
model=graphsage top_k=100 fold=2 epoch=88 loss=8.9992 val_auc=0.8189
model=graphsage top_k=100 fold=2 epoch=89 loss=9.0739 val_auc=0.8189
model=graphsage top_k=100 fold=2 epoch=90 loss=4.0985 val_auc=0.8181
model=graphsage top_k=100 fold=2 epoch=91 loss=6.2080 val_auc=0.8171
model=graphsage top_k=100 fold=2 epoch=92 loss=7.5057 val_auc=0.8169
model=graphsage top_k=100 fold=2 epoch=93 loss=6.6592 val_auc=0.8171
model=graphsage top_k=100 fold=2 epoch=94 loss=4.4589 val_auc=0.8178
model=graphsage top_k=100 fold=2 epoch=95 loss=4.8571 val_auc=0.8183
model=graphsage top_k=100 fold=2 epoch=96 loss=6.8536 val_auc=0.8184
model=graphsage top_k=100 fold=2 epoch=97 loss=5.0314 val_auc=0.8183
graphsage top_k=100 fold=2: early stopping at epoch 97

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=100 fold=3 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=100 fold=3 epoch=0 loss=21.3740 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=100 fold=3 epoch=1 loss=210.7624 val_auc=0.6796
model=graphsage top_k=100 fold=3 epoch=2 loss=50.0711 val_auc=0.5000
model=graphsage top_k=100 fold=3 epoch=3 loss=137.6765 val_auc=0.5000
model=graphsage top_k=100 fold=3 epoch=4 loss=107.9144 val_auc=0.5290

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=100 fold=3 epoch=5 loss=41.3920 val_auc=0.7328
model=graphsage top_k=100 fold=3 epoch=6 loss=33.1021 val_auc=0.7457
model=graphsage top_k=100 fold=3 epoch=7 loss=42.6603 val_auc=0.7555
model=graphsage top_k=100 fold=3 epoch=8 loss=19.0071 val_auc=0.5383
model=graphsage top_k=100 fold=3 epoch=9 loss=21.3564 val_auc=0.5148
model=graphsage top_k=100 fold=3 epoch=10 loss=32.6730 val_auc=0.7564
model=graphsage top_k=100 fold=3 epoch=11 loss=16.9521 val_auc=0.7721
model=graphsage top_k=100 fold=3 epoch=12 loss=12.4514 val_auc=0.7752
model=graphsage top_k=100 fold=3 epoch=13 loss=14.7638 val_auc=0.7769
model=graphsage top_k=100 fold=3 epoch=14 loss=14.2716 val_auc=0.7729
model=graphsage top_k=100 fold=3 epoch=15 loss=15.2004 val_auc=0.7737
model=graphsage top_k=100 fold=3 epoch=16 loss=16.1754 val_auc=0.7774
model=graphsage top_k=100 fold=3 epoch=17 loss=14.7204 val_auc=0.7829
model=graphsage top_k=100 fold=3 epoch=18 loss=11.3157 val_auc=0.7844
model=graphsage top_k=100 fold=3 epoch=19 loss=13.8383 val_auc=0.7854
model=graphsage top_k=100 fold=3 epoch=20 loss=10.4585 val_auc=0.7832
model=graphsage top_k=100 fold=3 epoch=21 loss=12.2069 val_auc=0.7831
model=graphsage top_k=100 fold=3 epoch=22 loss=12.5214 val_auc=0.7886
model=graphsage top_k=100 fold=3 epoch=23 loss=9.4669 val_auc=0.7922
model=graphsage top_k=100 fold=3 epoch=24 loss=9.1510 val_auc=0.7942
model=graphsage top_k=100 fold=3 epoch=25 loss=10.5617 val_auc=0.7953
model=graphsage top_k=100 fold=3 epoch=26 loss=10.8804 val_auc=0.7946
model=graphsage top_k=100 fold=3 epoch=27 loss=10.2039 val_auc=0.7908
model=graphsage top_k=100 fold=3 epoch=28 loss=13.4079 val_auc=0.7958
model=graphsage top_k=100 fold=3 epoch=29 loss=10.4381 val_auc=0.7991
model=graphsage top_k=100 fold=3 epoch=30 loss=10.9781 val_auc=0.7998
model=graphsage top_k=100 fold=3 epoch=31 loss=10.8041 val_auc=0.8004
model=graphsage top_k=100 fold=3 epoch=32 loss=7.9418 val_auc=0.8007
model=graphsage top_k=100 fold=3 epoch=33 loss=8.6249 val_auc=0.8026
model=graphsage top_k=100 fold=3 epoch=34 loss=7.5083 val_auc=0.8048
model=graphsage top_k=100 fold=3 epoch=35 loss=7.2850 val_auc=0.8061
model=graphsage top_k=100 fold=3 epoch=36 loss=7.9243 val_auc=0.8076
model=graphsage top_k=100 fold=3 epoch=37 loss=7.5280 val_auc=0.8092
model=graphsage top_k=100 fold=3 epoch=38 loss=6.7853 val_auc=0.8104
model=graphsage top_k=100 fold=3 epoch=39 loss=7.4297 val_auc=0.8112
model=graphsage top_k=100 fold=3 epoch=40 loss=6.1014 val_auc=0.8122
model=graphsage top_k=100 fold=3 epoch=41 loss=6.8677 val_auc=0.8131
model=graphsage top_k=100 fold=3 epoch=42 loss=6.7122 val_auc=0.8089
model=graphsage top_k=100 fold=3 epoch=43 loss=8.9986 val_auc=0.8094
model=graphsage top_k=100 fold=3 epoch=44 loss=7.3078 val_auc=0.8160
model=graphsage top_k=100 fold=3 epoch=45 loss=8.4366 val_auc=0.8168
model=graphsage top_k=100 fold=3 epoch=46 loss=7.3745 val_auc=0.8171
model=graphsage top_k=100 fold=3 epoch=47 loss=11.2592 val_auc=0.8171
model=graphsage top_k=100 fold=3 epoch=48 loss=8.8680 val_auc=0.8166
model=graphsage top_k=100 fold=3 epoch=49 loss=6.8049 val_auc=0.8030
model=graphsage top_k=100 fold=3 epoch=50 loss=10.0539 val_auc=0.7627
model=graphsage top_k=100 fold=3 epoch=51 loss=15.2660 val_auc=0.7795
model=graphsage top_k=100 fold=3 epoch=52 loss=12.0529 val_auc=0.8116
model=graphsage top_k=100 fold=3 epoch=53 loss=9.2616 val_auc=0.8154
model=graphsage top_k=100 fold=3 epoch=54 loss=6.3349 val_auc=0.8162
model=graphsage top_k=100 fold=3 epoch=55 loss=7.8855 val_auc=0.8167
model=graphsage top_k=100 fold=3 epoch=56 loss=9.9292 val_auc=0.8170
model=graphsage top_k=100 fold=3 epoch=57 loss=6.2844 val_auc=0.8165
model=graphsage top_k=100 fold=3 epoch=58 loss=8.3143 val_auc=0.8131
graphsage top_k=100 fold=3: early stopping at epoch 58

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=100 fold=4 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=100 fold=4 epoch=0 loss=32.3298 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=100 fold=4 epoch=1 loss=237.4412 val_auc=0.6715
model=graphsage top_k=100 fold=4 epoch=2 loss=51.6086 val_auc=0.5000
model=graphsage top_k=100 fold=4 epoch=3 loss=131.2322 val_auc=0.5000
model=graphsage top_k=100 fold=4 epoch=4 loss=107.5925 val_auc=0.5195

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=100 fold=4 epoch=5 loss=41.4209 val_auc=0.6959

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=100 fold=4 epoch=6 loss=49.2648 val_auc=0.7076
model=graphsage top_k=100 fold=4 epoch=7 loss=65.9074 val_auc=0.7246
model=graphsage top_k=100 fold=4 epoch=8 loss=43.9636 val_auc=0.7214
model=graphsage top_k=100 fold=4 epoch=9 loss=13.9290 val_auc=0.5305
model=graphsage top_k=100 fold=4 epoch=10 loss=31.9151 val_auc=0.5106
model=graphsage top_k=100 fold=4 epoch=11 loss=29.4795 val_auc=0.7492
model=graphsage top_k=100 fold=4 epoch=12 loss=18.4800 val_auc=0.7607
model=graphsage top_k=100 fold=4 epoch=13 loss=14.5550 val_auc=0.7627
model=graphsage top_k=100 fold=4 epoch=14 loss=17.3111 val_auc=0.7644
model=graphsage top_k=100 fold=4 epoch=15 loss=13.7673 val_auc=0.7631
model=graphsage top_k=100 fold=4 epoch=16 loss=15.7560 val_auc=0.7434
model=graphsage top_k=100 fold=4 epoch=17 loss=14.9259 val_auc=0.7678
model=graphsage top_k=100 fold=4 epoch=18 loss=11.0410 val_auc=0.7687
model=graphsage top_k=100 fold=4 epoch=19 loss=9.8071 val_auc=0.7694
model=graphsage top_k=100 fold=4 epoch=20 loss=13.8583 val_auc=0.7699
model=graphsage top_k=100 fold=4 epoch=21 loss=11.3962 val_auc=0.7689
model=graphsage top_k=100 fold=4 epoch=22 loss=13.5088 val_auc=0.7618
model=graphsage top_k=100 fold=4 epoch=23 loss=14.0884 val_auc=0.7710
model=graphsage top_k=100 fold=4 epoch=24 loss=12.5675 val_auc=0.7737
model=graphsage top_k=100 fold=4 epoch=25 loss=10.0551 val_auc=0.7750
model=graphsage top_k=100 fold=4 epoch=26 loss=9.1631 val_auc=0.7766
model=graphsage top_k=100 fold=4 epoch=27 loss=10.6195 val_auc=0.7772
model=graphsage top_k=100 fold=4 epoch=28 loss=7.8884 val_auc=0.7780
model=graphsage top_k=100 fold=4 epoch=29 loss=11.1458 val_auc=0.7807
model=graphsage top_k=100 fold=4 epoch=30 loss=8.5643 val_auc=0.7822
model=graphsage top_k=100 fold=4 epoch=31 loss=7.5443 val_auc=0.7833
model=graphsage top_k=100 fold=4 epoch=32 loss=7.4651 val_auc=0.7849
model=graphsage top_k=100 fold=4 epoch=33 loss=8.1141 val_auc=0.7859
model=graphsage top_k=100 fold=4 epoch=34 loss=7.1217 val_auc=0.7869
model=graphsage top_k=100 fold=4 epoch=35 loss=7.8688 val_auc=0.7865
model=graphsage top_k=100 fold=4 epoch=36 loss=10.2811 val_auc=0.7880
model=graphsage top_k=100 fold=4 epoch=37 loss=10.7163 val_auc=0.7901
model=graphsage top_k=100 fold=4 epoch=38 loss=7.2234 val_auc=0.7910
model=graphsage top_k=100 fold=4 epoch=39 loss=14.7892 val_auc=0.7915
model=graphsage top_k=100 fold=4 epoch=40 loss=11.9597 val_auc=0.7921
model=graphsage top_k=100 fold=4 epoch=41 loss=11.5304 val_auc=0.7924
model=graphsage top_k=100 fold=4 epoch=42 loss=8.0484 val_auc=0.7919
model=graphsage top_k=100 fold=4 epoch=43 loss=8.7623 val_auc=0.7759
model=graphsage top_k=100 fold=4 epoch=44 loss=15.3284 val_auc=0.7810
model=graphsage top_k=100 fold=4 epoch=45 loss=11.3086 val_auc=0.7938
model=graphsage top_k=100 fold=4 epoch=46 loss=8.5335 val_auc=0.7944
model=graphsage top_k=100 fold=4 epoch=47 loss=8.9086 val_auc=0.7948
model=graphsage top_k=100 fold=4 epoch=48 loss=8.5143 val_auc=0.7950
model=graphsage top_k=100 fold=4 epoch=49 loss=8.8527 val_auc=0.7953
model=graphsage top_k=100 fold=4 epoch=50 loss=5.9631 val_auc=0.7962
model=graphsage top_k=100 fold=4 epoch=51 loss=7.2901 val_auc=0.7971
model=graphsage top_k=100 fold=4 epoch=52 loss=6.1762 val_auc=0.7980
model=graphsage top_k=100 fold=4 epoch=53 loss=5.8721 val_auc=0.7994
model=graphsage top_k=100 fold=4 epoch=54 loss=6.0374 val_auc=0.8010
model=graphsage top_k=100 fold=4 epoch=55 loss=6.4461 val_auc=0.8026
model=graphsage top_k=100 fold=4 epoch=56 loss=6.3957 val_auc=0.8038
model=graphsage top_k=100 fold=4 epoch=57 loss=7.5185 val_auc=0.8048
model=graphsage top_k=100 fold=4 epoch=58 loss=7.2442 val_auc=0.8057
model=graphsage top_k=100 fold=4 epoch=59 loss=5.6731 val_auc=0.8062
model=graphsage top_k=100 fold=4 epoch=60 loss=7.6262 val_auc=0.8065
model=graphsage top_k=100 fold=4 epoch=61 loss=8.2961 val_auc=0.8070
model=graphsage top_k=100 fold=4 epoch=62 loss=6.9999 val_auc=0.8074
model=graphsage top_k=100 fold=4 epoch=63 loss=5.4804 val_auc=0.8079
model=graphsage top_k=100 fold=4 epoch=64 loss=7.8382 val_auc=0.8084
model=graphsage top_k=100 fold=4 epoch=65 loss=9.1240 val_auc=0.8087
model=graphsage top_k=100 fold=4 epoch=66 loss=7.1947 val_auc=0.8090
model=graphsage top_k=100 fold=4 epoch=67 loss=6.1174 val_auc=0.8096
model=graphsage top_k=100 fold=4 epoch=68 loss=6.4339 val_auc=0.8096
model=graphsage top_k=100 fold=4 epoch=69 loss=5.9167 val_auc=0.8101
model=graphsage top_k=100 fold=4 epoch=70 loss=5.7935 val_auc=0.8104
model=graphsage top_k=100 fold=4 epoch=71 loss=5.8828 val_auc=0.8109
model=graphsage top_k=100 fold=4 epoch=72 loss=6.3473 val_auc=0.8113
model=graphsage top_k=100 fold=4 epoch=73 loss=6.6297 val_auc=0.8115
model=graphsage top_k=100 fold=4 epoch=74 loss=4.9651 val_auc=0.8118
model=graphsage top_k=100 fold=4 epoch=75 loss=8.4122 val_auc=0.8046
model=graphsage top_k=100 fold=4 epoch=76 loss=12.7561 val_auc=0.8076
model=graphsage top_k=100 fold=4 epoch=77 loss=11.3099 val_auc=0.8124
model=graphsage top_k=100 fold=4 epoch=78 loss=6.5034 val_auc=0.8125
model=graphsage top_k=100 fold=4 epoch=79 loss=5.3349 val_auc=0.8129
model=graphsage top_k=100 fold=4 epoch=80 loss=7.5279 val_auc=0.8128
model=graphsage top_k=100 fold=4 epoch=81 loss=5.8155 val_auc=0.8127
model=graphsage top_k=100 fold=4 epoch=82 loss=5.3024 val_auc=0.8127
model=graphsage top_k=100 fold=4 epoch=83 loss=6.0243 val_auc=0.8126
model=graphsage top_k=100 fold=4 epoch=84 loss=5.1059 val_auc=0.8127
model=graphsage top_k=100 fold=4 epoch=85 loss=4.5150 val_auc=0.8129
model=graphsage top_k=100 fold=4 epoch=86 loss=4.7938 val_auc=0.8131
model=graphsage top_k=100 fold=4 epoch=87 loss=4.4461 val_auc=0.8134
model=graphsage top_k=100 fold=4 epoch=88 loss=4.9017 val_auc=0.8138
model=graphsage top_k=100 fold=4 epoch=89 loss=4.4251 val_auc=0.8147
model=graphsage top_k=100 fold=4 epoch=90 loss=5.4614 val_auc=0.8153
model=graphsage top_k=100 fold=4 epoch=91 loss=6.0694 val_auc=0.8157
model=graphsage top_k=100 fold=4 epoch=92 loss=4.9814 val_auc=0.8159
model=graphsage top_k=100 fold=4 epoch=93 loss=4.0390 val_auc=0.8165
model=graphsage top_k=100 fold=4 epoch=94 loss=5.6949 val_auc=0.8171
model=graphsage top_k=100 fold=4 epoch=95 loss=4.5502 val_auc=0.8177
model=graphsage top_k=100 fold=4 epoch=96 loss=3.7953 val_auc=0.8183
model=graphsage top_k=100 fold=4 epoch=97 loss=5.1283 val_auc=0.8183
model=graphsage top_k=100 fold=4 epoch=98 loss=7.4657 val_auc=0.8187
model=graphsage top_k=100 fold=4 epoch=99 loss=6.7615 val_auc=0.8194

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=100 fold=5 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=100 fold=5 epoch=0 loss=23.8635 val_auc=0.5000
model=graphsage top_k=100 fold=5 epoch=1 loss=159.2334 val_auc=0.5293
model=graphsage top_k=100 fold=5 epoch=2 loss=54.5229 val_auc=0.7619
model=graphsage top_k=100 fold=5 epoch=3 loss=18.4914 val_auc=0.7762
model=graphsage top_k=100 fold=5 epoch=4 loss=41.1006 val_auc=0.7403
model=graphsage top_k=100 fold=5 epoch=5 loss=15.6006 val_auc=0.7415
model=graphsage top_k=100 fold=5 epoch=6 loss=12.2100 val_auc=0.7858
model=graphsage top_k=100 fold=5 epoch=7 loss=21.5294 val_auc=0.7884
model=graphsage top_k=100 fold=5 epoch=8 loss=16.3392 val_auc=0.5743
model=graphsage top_k=100 fold=5 epoch=9 loss=24.7683 val_auc=0.5501
model=graphsage top_k=100 fold=5 epoch=10 loss=21.3550 val_auc=0.7841
model=graphsage top_k=100 fold=5 epoch=11 loss=12.6636 val_auc=0.7945
model=graphsage top_k=100 fold=5 epoch=12 loss=15.9767 val_auc=0.7964
model=graphsage top_k=100 fold=5 epoch=13 loss=20.0559 val_auc=0.7973
model=graphsage top_k=100 fold=5 epoch=14 loss=14.7005 val_auc=0.7850
model=graphsage top_k=100 fold=5 epoch=15 loss=15.0897 val_auc=0.7495
model=graphsage top_k=100 fold=5 epoch=16 loss=19.6098 val_auc=0.7895
model=graphsage top_k=100 fold=5 epoch=17 loss=14.4919 val_auc=0.7981
model=graphsage top_k=100 fold=5 epoch=18 loss=11.0951 val_auc=0.7984
model=graphsage top_k=100 fold=5 epoch=19 loss=13.2058 val_auc=0.7983
model=graphsage top_k=100 fold=5 epoch=20 loss=10.1931 val_auc=0.7902
model=graphsage top_k=100 fold=5 epoch=21 loss=15.6222 val_auc=0.7840
model=graphsage top_k=100 fold=5 epoch=22 loss=15.1976 val_auc=0.7988
model=graphsage top_k=100 fold=5 epoch=23 loss=11.0345 val_auc=0.8015
model=graphsage top_k=100 fold=5 epoch=24 loss=9.4711 val_auc=0.8026
model=graphsage top_k=100 fold=5 epoch=25 loss=10.1405 val_auc=0.8038
model=graphsage top_k=100 fold=5 epoch=26 loss=8.5769 val_auc=0.7917
model=graphsage top_k=100 fold=5 epoch=27 loss=11.9645 val_auc=0.7821
model=graphsage top_k=100 fold=5 epoch=28 loss=12.4213 val_auc=0.8065
model=graphsage top_k=100 fold=5 epoch=29 loss=9.3668 val_auc=0.8100
model=graphsage top_k=100 fold=5 epoch=30 loss=9.0500 val_auc=0.8113
model=graphsage top_k=100 fold=5 epoch=31 loss=13.8189 val_auc=0.8121
model=graphsage top_k=100 fold=5 epoch=32 loss=8.5813 val_auc=0.8126
model=graphsage top_k=100 fold=5 epoch=33 loss=9.9274 val_auc=0.8104
model=graphsage top_k=100 fold=5 epoch=34 loss=8.7309 val_auc=0.8128
model=graphsage top_k=100 fold=5 epoch=35 loss=7.4896 val_auc=0.8135
model=graphsage top_k=100 fold=5 epoch=36 loss=7.8666 val_auc=0.8140
model=graphsage top_k=100 fold=5 epoch=37 loss=10.0471 val_auc=0.8143
model=graphsage top_k=100 fold=5 epoch=38 loss=7.0365 val_auc=0.8007
model=graphsage top_k=100 fold=5 epoch=39 loss=12.5963 val_auc=0.7830
model=graphsage top_k=100 fold=5 epoch=40 loss=11.2082 val_auc=0.8080
model=graphsage top_k=100 fold=5 epoch=41 loss=8.9499 val_auc=0.8154
model=graphsage top_k=100 fold=5 epoch=42 loss=6.2702 val_auc=0.8162
model=graphsage top_k=100 fold=5 epoch=43 loss=7.6788 val_auc=0.8170
model=graphsage top_k=100 fold=5 epoch=44 loss=7.0579 val_auc=0.8171
model=graphsage top_k=100 fold=5 epoch=45 loss=7.5233 val_auc=0.8174
model=graphsage top_k=100 fold=5 epoch=46 loss=6.7575 val_auc=0.8187
model=graphsage top_k=100 fold=5 epoch=47 loss=8.0583 val_auc=0.8194
model=graphsage top_k=100 fold=5 epoch=48 loss=8.3292 val_auc=0.8196
model=graphsage top_k=100 fold=5 epoch=49 loss=11.0161 val_auc=0.8196
model=graphsage top_k=100 fold=5 epoch=50 loss=6.6375 val_auc=0.8192
model=graphsage top_k=100 fold=5 epoch=51 loss=7.2031 val_auc=0.8137
model=graphsage top_k=100 fold=5 epoch=52 loss=9.4925 val_auc=0.8174
model=graphsage top_k=100 fold=5 epoch=53 loss=7.0724 val_auc=0.8207
model=graphsage top_k=100 fold=5 epoch=54 loss=6.5721 val_auc=0.8212
model=graphsage top_k=100 fold=5 epoch=55 loss=9.2271 val_auc=0.8218
model=graphsage top_k=100 fold=5 epoch=56 loss=10.5488 val_auc=0.8221
model=graphsage top_k=100 fold=5 epoch=57 loss=8.6574 val_auc=0.8225
model=graphsage top_k=100 fold=5 epoch=58 loss=5.4862 val_auc=0.8173
model=graphsage top_k=100 fold=5 epoch=59 loss=8.6219 val_auc=0.8107
model=graphsage top_k=100 fold=5 epoch=60 loss=8.9131 val_auc=0.8217
model=graphsage top_k=100 fold=5 epoch=61 loss=6.3096 val_auc=0.8237
model=graphsage top_k=100 fold=5 epoch=62 loss=6.3735 val_auc=0.8239
model=graphsage top_k=100 fold=5 epoch=63 loss=5.3411 val_auc=0.8246
model=graphsage top_k=100 fold=5 epoch=64 loss=4.8473 val_auc=0.8261
model=graphsage top_k=100 fold=5 epoch=65 loss=5.6210 val_auc=0.8267
model=graphsage top_k=100 fold=5 epoch=66 loss=5.2570 val_auc=0.8262
model=graphsage top_k=100 fold=5 epoch=67 loss=4.9996 val_auc=0.8233
model=graphsage top_k=100 fold=5 epoch=68 loss=8.5628 val_auc=0.8187
model=graphsage top_k=100 fold=5 epoch=69 loss=9.0866 val_auc=0.8186
model=graphsage top_k=100 fold=5 epoch=70 loss=6.5956 val_auc=0.8168
model=graphsage top_k=100 fold=5 epoch=71 loss=5.7637 val_auc=0.8177
model=graphsage top_k=100 fold=5 epoch=72 loss=6.7990 val_auc=0.8194
model=graphsage top_k=100 fold=5 epoch=73 loss=5.6122 val_auc=0.8211
model=graphsage top_k=100 fold=5 epoch=74 loss=5.0891 val_auc=0.8228
model=graphsage top_k=100 fold=5 epoch=75 loss=5.6448 val_auc=0.8237
model=graphsage top_k=100 fold=5 epoch=76 loss=5.4306 val_auc=0.8262
model=graphsage top_k=100 fold=5 epoch=77 loss=5.4121 val_auc=0.8277
model=graphsage top_k=100 fold=5 epoch=78 loss=4.7865 val_auc=0.8292
model=graphsage top_k=100 fold=5 epoch=79 loss=5.6190 val_auc=0.8302
model=graphsage top_k=100 fold=5 epoch=80 loss=4.4330 val_auc=0.8294
model=graphsage top_k=100 fold=5 epoch=81 loss=5.8281 val_auc=0.8271
model=graphsage top_k=100 fold=5 epoch=82 loss=6.8299 val_auc=0.8314
model=graphsage top_k=100 fold=5 epoch=83 loss=5.1619 val_auc=0.8322
model=graphsage top_k=100 fold=5 epoch=84 loss=4.4429 val_auc=0.8324
model=graphsage top_k=100 fold=5 epoch=85 loss=4.6263 val_auc=0.8326
model=graphsage top_k=100 fold=5 epoch=86 loss=4.8552 val_auc=0.8325
model=graphsage top_k=100 fold=5 epoch=87 loss=4.4261 val_auc=0.8315
model=graphsage top_k=100 fold=5 epoch=88 loss=5.8561 val_auc=0.8334
model=graphsage top_k=100 fold=5 epoch=89 loss=5.3088 val_auc=0.8336
model=graphsage top_k=100 fold=5 epoch=90 loss=4.8450 val_auc=0.8336
model=graphsage top_k=100 fold=5 epoch=91 loss=4.0660 val_auc=0.8337
model=graphsage top_k=100 fold=5 epoch=92 loss=4.2377 val_auc=0.8340
model=graphsage top_k=100 fold=5 epoch=93 loss=3.7252 val_auc=0.8342
model=graphsage top_k=100 fold=5 epoch=94 loss=4.4538 val_auc=0.8343
model=graphsage top_k=100 fold=5 epoch=95 loss=4.0374 val_auc=0.8341
model=graphsage top_k=100 fold=5 epoch=96 loss=4.5859 val_auc=0.8344
model=graphsage top_k=100 fold=5 epoch=97 loss=4.2642 val_auc=0.8349
model=graphsage top_k=100 fold=5 epoch=98 loss=4.1776 val_auc=0.8355
model=graphsage top_k=100 fold=5 epoch=99 loss=5.3877 val_auc=0.8359

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=100 fold=6 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=graphsage top_k=100 fold=6 epoch=0 loss=27.5984 val_auc=0.5000
model=graphsage top_k=100 fold=6 epoch=1 loss=312.5987 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=100 fold=6 epoch=2 loss=117.2138 val_auc=0.5875
model=graphsage top_k=100 fold=6 epoch=3 loss=49.4192 val_auc=0.7099
model=graphsage top_k=100 fold=6 epoch=4 loss=35.7146 val_auc=0.5547
model=graphsage top_k=100 fold=6 epoch=5 loss=21.2297 val_auc=0.5930
model=graphsage top_k=100 fold=6 epoch=6 loss=18.4263 val_auc=0.7741
model=graphsage top_k=100 fold=6 epoch=7 loss=14.9869 val_auc=0.7801
model=graphsage top_k=100 fold=6 epoch=8 loss=15.5327 val_auc=0.7799
model=graphsage top_k=100 fold=6 epoch=9 loss=12.8993 val_auc=0.7822
model=graphsage top_k=100 fold=6 epoch=10 loss=12.1207 val_auc=0.7855
model=graphsage top_k=100 fold=6 epoch=11 loss=11.9391 val_auc=0.7870
model=graphsage top_k=100 fold=6 epoch=12 loss=13.7603 val_auc=0.7866
model=graphsage top_k=100 fold=6 epoch=13 loss=10.2836 val_auc=0.7383
model=graphsage top_k=100 fold=6 epoch=14 loss=24.0712 val_auc=0.7477
model=graphsage top_k=100 fold=6 epoch=15 loss=16.7224 val_auc=0.7749
model=graphsage top_k=100 fold=6 epoch=16 loss=10.6381 val_auc=0.7962
model=graphsage top_k=100 fold=6 epoch=17 loss=10.9002 val_auc=0.7989
model=graphsage top_k=100 fold=6 epoch=18 loss=8.6547 val_auc=0.7978
model=graphsage top_k=100 fold=6 epoch=19 loss=11.0438 val_auc=0.7995
model=graphsage top_k=100 fold=6 epoch=20 loss=9.0213 val_auc=0.8039
model=graphsage top_k=100 fold=6 epoch=21 loss=10.2303 val_auc=0.8046
model=graphsage top_k=100 fold=6 epoch=22 loss=10.0500 val_auc=0.8037
model=graphsage top_k=100 fold=6 epoch=23 loss=7.7926 val_auc=0.8060
model=graphsage top_k=100 fold=6 epoch=24 loss=7.4026 val_auc=0.8099
model=graphsage top_k=100 fold=6 epoch=25 loss=7.5836 val_auc=0.8119
model=graphsage top_k=100 fold=6 epoch=26 loss=9.8473 val_auc=0.8139
model=graphsage top_k=100 fold=6 epoch=27 loss=12.8745 val_auc=0.8152
model=graphsage top_k=100 fold=6 epoch=28 loss=8.3766 val_auc=0.8119
model=graphsage top_k=100 fold=6 epoch=29 loss=9.4705 val_auc=0.7824
model=graphsage top_k=100 fold=6 epoch=30 loss=14.7481 val_auc=0.8101
model=graphsage top_k=100 fold=6 epoch=31 loss=13.7227 val_auc=0.8171
model=graphsage top_k=100 fold=6 epoch=32 loss=7.7644 val_auc=0.8176
model=graphsage top_k=100 fold=6 epoch=33 loss=10.9283 val_auc=0.8178
model=graphsage top_k=100 fold=6 epoch=34 loss=10.7720 val_auc=0.8176
model=graphsage top_k=100 fold=6 epoch=35 loss=7.9312 val_auc=0.8161
model=graphsage top_k=100 fold=6 epoch=36 loss=9.9516 val_auc=0.8083
model=graphsage top_k=100 fold=6 epoch=37 loss=15.0791 val_auc=0.8158
model=graphsage top_k=100 fold=6 epoch=38 loss=8.0738 val_auc=0.8181
model=graphsage top_k=100 fold=6 epoch=39 loss=7.7549 val_auc=0.8181
model=graphsage top_k=100 fold=6 epoch=40 loss=6.8171 val_auc=0.8183
model=graphsage top_k=100 fold=6 epoch=41 loss=6.9665 val_auc=0.8191
model=graphsage top_k=100 fold=6 epoch=42 loss=7.2096 val_auc=0.8096
model=graphsage top_k=100 fold=6 epoch=43 loss=10.4697 val_auc=0.8061
model=graphsage top_k=100 fold=6 epoch=44 loss=12.3194 val_auc=0.8209
model=graphsage top_k=100 fold=6 epoch=45 loss=8.1606 val_auc=0.8232
model=graphsage top_k=100 fold=6 epoch=46 loss=6.9324 val_auc=0.8238
model=graphsage top_k=100 fold=6 epoch=47 loss=9.0863 val_auc=0.8243
model=graphsage top_k=100 fold=6 epoch=48 loss=7.2072 val_auc=0.8245
model=graphsage top_k=100 fold=6 epoch=49 loss=7.0789 val_auc=0.8151
model=graphsage top_k=100 fold=6 epoch=50 loss=8.2269 val_auc=0.8077
model=graphsage top_k=100 fold=6 epoch=51 loss=10.4649 val_auc=0.8254
model=graphsage top_k=100 fold=6 epoch=52 loss=9.0108 val_auc=0.8271
model=graphsage top_k=100 fold=6 epoch=53 loss=5.4624 val_auc=0.8272
model=graphsage top_k=100 fold=6 epoch=54 loss=7.3763 val_auc=0.8274
model=graphsage top_k=100 fold=6 epoch=55 loss=10.3669 val_auc=0.8278
model=graphsage top_k=100 fold=6 epoch=56 loss=9.0782 val_auc=0.8278
model=graphsage top_k=100 fold=6 epoch=57 loss=5.9901 val_auc=0.8219
model=graphsage top_k=100 fold=6 epoch=58 loss=7.9997 val_auc=0.7859
model=graphsage top_k=100 fold=6 epoch=59 loss=14.2731 val_auc=0.7939
model=graphsage top_k=100 fold=6 epoch=60 loss=11.3729 val_auc=0.8230
model=graphsage top_k=100 fold=6 epoch=61 loss=8.8067 val_auc=0.8277
model=graphsage top_k=100 fold=6 epoch=62 loss=5.5071 val_auc=0.8282
model=graphsage top_k=100 fold=6 epoch=63 loss=7.4794 val_auc=0.8287
model=graphsage top_k=100 fold=6 epoch=64 loss=7.5379 val_auc=0.8291
model=graphsage top_k=100 fold=6 epoch=65 loss=8.6388 val_auc=0.8295
model=graphsage top_k=100 fold=6 epoch=66 loss=5.7975 val_auc=0.8288
model=graphsage top_k=100 fold=6 epoch=67 loss=7.7138 val_auc=0.8271
model=graphsage top_k=100 fold=6 epoch=68 loss=7.1189 val_auc=0.8284
model=graphsage top_k=100 fold=6 epoch=69 loss=5.0088 val_auc=0.8300
model=graphsage top_k=100 fold=6 epoch=70 loss=5.0082 val_auc=0.8307
model=graphsage top_k=100 fold=6 epoch=71 loss=5.6056 val_auc=0.8316
model=graphsage top_k=100 fold=6 epoch=72 loss=6.5920 val_auc=0.8325
model=graphsage top_k=100 fold=6 epoch=73 loss=6.1001 val_auc=0.8330
model=graphsage top_k=100 fold=6 epoch=74 loss=5.6770 val_auc=0.8332
model=graphsage top_k=100 fold=6 epoch=75 loss=4.9831 val_auc=0.8329
model=graphsage top_k=100 fold=6 epoch=76 loss=4.9576 val_auc=0.8330
model=graphsage top_k=100 fold=6 epoch=77 loss=6.6082 val_auc=0.8335
model=graphsage top_k=100 fold=6 epoch=78 loss=5.2218 val_auc=0.8343
model=graphsage top_k=100 fold=6 epoch=79 loss=5.1457 val_auc=0.8345
model=graphsage top_k=100 fold=6 epoch=80 loss=4.8073 val_auc=0.8348
model=graphsage top_k=100 fold=6 epoch=81 loss=5.4297 val_auc=0.8350
model=graphsage top_k=100 fold=6 epoch=82 loss=4.2741 val_auc=0.8351
model=graphsage top_k=100 fold=6 epoch=83 loss=5.6583 val_auc=0.8353
model=graphsage top_k=100 fold=6 epoch=84 loss=6.7238 val_auc=0.8355
model=graphsage top_k=100 fold=6 epoch=85 loss=7.0463 val_auc=0.8356
model=graphsage top_k=100 fold=6 epoch=86 loss=5.1766 val_auc=0.8354
model=graphsage top_k=100 fold=6 epoch=87 loss=5.3421 val_auc=0.8344
model=graphsage top_k=100 fold=6 epoch=88 loss=5.4471 val_auc=0.8345
model=graphsage top_k=100 fold=6 epoch=89 loss=5.3217 val_auc=0.8342
model=graphsage top_k=100 fold=6 epoch=90 loss=3.7253 val_auc=0.8342
model=graphsage top_k=100 fold=6 epoch=91 loss=3.9215 val_auc=0.8348
model=graphsage top_k=100 fold=6 epoch=92 loss=4.1558 val_auc=0.8356
model=graphsage top_k=100 fold=6 epoch=93 loss=4.6904 val_auc=0.8363
model=graphsage top_k=100 fold=6 epoch=94 loss=4.0461 val_auc=0.8370
model=graphsage top_k=100 fold=6 epoch=95 loss=4.3179 val_auc=0.8378
model=graphsage top_k=100 fold=6 epoch=96 loss=5.8372 val_auc=0.8383
model=graphsage top_k=100 fold=6 epoch=97 loss=4.1761 val_auc=0.8386
model=graphsage top_k=100 fold=6 epoch=98 loss=4.5448 val_auc=0.8391
model=graphsage top_k=100 fold=6 epoch=99 loss=4.2050 val_auc=0.8396

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=100 fold=7 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=graphsage top_k=100 fold=7 epoch=0 loss=20.6912 val_auc=0.5000
model=graphsage top_k=100 fold=7 epoch=1 loss=335.4434 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=100 fold=7 epoch=2 loss=126.1113 val_auc=0.5161

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=100 fold=7 epoch=3 loss=67.5613 val_auc=0.6837
model=graphsage top_k=100 fold=7 epoch=4 loss=55.3028 val_auc=0.7193
model=graphsage top_k=100 fold=7 epoch=5 loss=12.6018 val_auc=0.7355
model=graphsage top_k=100 fold=7 epoch=6 loss=14.3386 val_auc=0.7447
model=graphsage top_k=100 fold=7 epoch=7 loss=20.9887 val_auc=0.7516
model=graphsage top_k=100 fold=7 epoch=8 loss=15.0861 val_auc=0.6540
model=graphsage top_k=100 fold=7 epoch=9 loss=14.6921 val_auc=0.6781
model=graphsage top_k=100 fold=7 epoch=10 loss=19.6492 val_auc=0.7614
model=graphsage top_k=100 fold=7 epoch=11 loss=10.7355 val_auc=0.7640
model=graphsage top_k=100 fold=7 epoch=12 loss=13.8035 val_auc=0.7654
model=graphsage top_k=100 fold=7 epoch=13 loss=16.3369 val_auc=0.7684
model=graphsage top_k=100 fold=7 epoch=14 loss=11.4759 val_auc=0.7716
model=graphsage top_k=100 fold=7 epoch=15 loss=13.2708 val_auc=0.7743
model=graphsage top_k=100 fold=7 epoch=16 loss=12.8587 val_auc=0.7768
model=graphsage top_k=100 fold=7 epoch=17 loss=10.4010 val_auc=0.7787
model=graphsage top_k=100 fold=7 epoch=18 loss=13.4700 val_auc=0.7827
model=graphsage top_k=100 fold=7 epoch=19 loss=10.5655 val_auc=0.7853
model=graphsage top_k=100 fold=7 epoch=20 loss=10.5227 val_auc=0.7881
model=graphsage top_k=100 fold=7 epoch=21 loss=13.6578 val_auc=0.7903
model=graphsage top_k=100 fold=7 epoch=22 loss=9.2125 val_auc=0.7904
model=graphsage top_k=100 fold=7 epoch=23 loss=11.1717 val_auc=0.7899
model=graphsage top_k=100 fold=7 epoch=24 loss=12.7785 val_auc=0.7934
model=graphsage top_k=100 fold=7 epoch=25 loss=8.7179 val_auc=0.7945
model=graphsage top_k=100 fold=7 epoch=26 loss=14.2259 val_auc=0.7950
model=graphsage top_k=100 fold=7 epoch=27 loss=13.9668 val_auc=0.7955
model=graphsage top_k=100 fold=7 epoch=28 loss=9.0991 val_auc=0.7932
model=graphsage top_k=100 fold=7 epoch=29 loss=12.7571 val_auc=0.7852
model=graphsage top_k=100 fold=7 epoch=30 loss=9.8699 val_auc=0.7950
model=graphsage top_k=100 fold=7 epoch=31 loss=8.5973 val_auc=0.7975
model=graphsage top_k=100 fold=7 epoch=32 loss=8.4047 val_auc=0.7982
model=graphsage top_k=100 fold=7 epoch=33 loss=10.3998 val_auc=0.7990
model=graphsage top_k=100 fold=7 epoch=34 loss=7.6717 val_auc=0.8002
model=graphsage top_k=100 fold=7 epoch=35 loss=8.5818 val_auc=0.8015
model=graphsage top_k=100 fold=7 epoch=36 loss=8.9620 val_auc=0.8026
model=graphsage top_k=100 fold=7 epoch=37 loss=7.7952 val_auc=0.8037
model=graphsage top_k=100 fold=7 epoch=38 loss=6.3321 val_auc=0.8051
model=graphsage top_k=100 fold=7 epoch=39 loss=6.6812 val_auc=0.8054
model=graphsage top_k=100 fold=7 epoch=40 loss=7.0753 val_auc=0.8064
model=graphsage top_k=100 fold=7 epoch=41 loss=8.6924 val_auc=0.8087
model=graphsage top_k=100 fold=7 epoch=42 loss=7.6404 val_auc=0.8081
model=graphsage top_k=100 fold=7 epoch=43 loss=9.8951 val_auc=0.8079
model=graphsage top_k=100 fold=7 epoch=44 loss=9.6346 val_auc=0.8082
model=graphsage top_k=100 fold=7 epoch=45 loss=9.0862 val_auc=0.8090
model=graphsage top_k=100 fold=7 epoch=46 loss=6.8820 val_auc=0.7984
model=graphsage top_k=100 fold=7 epoch=47 loss=9.7510 val_auc=0.7533
model=graphsage top_k=100 fold=7 epoch=48 loss=16.0935 val_auc=0.7795
model=graphsage top_k=100 fold=7 epoch=49 loss=14.2006 val_auc=0.8096
model=graphsage top_k=100 fold=7 epoch=50 loss=6.4182 val_auc=0.8093
model=graphsage top_k=100 fold=7 epoch=51 loss=6.8858 val_auc=0.8087
model=graphsage top_k=100 fold=7 epoch=52 loss=8.9632 val_auc=0.8083
model=graphsage top_k=100 fold=7 epoch=53 loss=9.3462 val_auc=0.8080
model=graphsage top_k=100 fold=7 epoch=54 loss=6.9019 val_auc=0.8076
model=graphsage top_k=100 fold=7 epoch=55 loss=7.0829 val_auc=0.8016
model=graphsage top_k=100 fold=7 epoch=56 loss=11.1243 val_auc=0.8046
model=graphsage top_k=100 fold=7 epoch=57 loss=7.8597 val_auc=0.8095
model=graphsage top_k=100 fold=7 epoch=58 loss=6.4762 val_auc=0.8096
model=graphsage top_k=100 fold=7 epoch=59 loss=7.5267 val_auc=0.8097
model=graphsage top_k=100 fold=7 epoch=60 loss=8.8976 val_auc=0.8101
model=graphsage top_k=100 fold=7 epoch=61 loss=6.5294 val_auc=0.8107
model=graphsage top_k=100 fold=7 epoch=62 loss=5.0003 val_auc=0.8096
model=graphsage top_k=100 fold=7 epoch=63 loss=6.9946 val_auc=0.8052
model=graphsage top_k=100 fold=7 epoch=64 loss=9.1645 val_auc=0.8116
model=graphsage top_k=100 fold=7 epoch=65 loss=7.9305 val_auc=0.8140
model=graphsage top_k=100 fold=7 epoch=66 loss=5.4988 val_auc=0.8148
model=graphsage top_k=100 fold=7 epoch=67 loss=6.7476 val_auc=0.8154
model=graphsage top_k=100 fold=7 epoch=68 loss=5.9507 val_auc=0.8157
model=graphsage top_k=100 fold=7 epoch=69 loss=4.9795 val_auc=0.8162
model=graphsage top_k=100 fold=7 epoch=70 loss=4.7522 val_auc=0.8169
model=graphsage top_k=100 fold=7 epoch=71 loss=5.1160 val_auc=0.8175
model=graphsage top_k=100 fold=7 epoch=72 loss=4.9831 val_auc=0.8180
model=graphsage top_k=100 fold=7 epoch=73 loss=4.6351 val_auc=0.8180
model=graphsage top_k=100 fold=7 epoch=74 loss=5.1883 val_auc=0.8183
model=graphsage top_k=100 fold=7 epoch=75 loss=6.3667 val_auc=0.8190
model=graphsage top_k=100 fold=7 epoch=76 loss=4.6354 val_auc=0.8194
model=graphsage top_k=100 fold=7 epoch=77 loss=4.8585 val_auc=0.8193
model=graphsage top_k=100 fold=7 epoch=78 loss=6.9943 val_auc=0.8177
model=graphsage top_k=100 fold=7 epoch=79 loss=9.1889 val_auc=0.8188
model=graphsage top_k=100 fold=7 epoch=80 loss=8.8412 val_auc=0.8177
model=graphsage top_k=100 fold=7 epoch=81 loss=4.0547 val_auc=0.8175
model=graphsage top_k=100 fold=7 epoch=82 loss=7.5505 val_auc=0.8172
model=graphsage top_k=100 fold=7 epoch=83 loss=8.7884 val_auc=0.8170
model=graphsage top_k=100 fold=7 epoch=84 loss=8.0431 val_auc=0.8168
model=graphsage top_k=100 fold=7 epoch=85 loss=4.3009 val_auc=0.8169
model=graphsage top_k=100 fold=7 epoch=86 loss=5.9173 val_auc=0.8172
model=graphsage top_k=100 fold=7 epoch=87 loss=7.1686 val_auc=0.8175
model=graphsage top_k=100 fold=7 epoch=88 loss=7.0003 val_auc=0.8181
graphsage top_k=100 fold=7: early stopping at epoch 88

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=100 fold=8 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=100 fold=8 epoch=0 loss=27.5505 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=100 fold=8 epoch=1 loss=211.5736 val_auc=0.5910
model=graphsage top_k=100 fold=8 epoch=2 loss=31.8125 val_auc=0.5000
model=graphsage top_k=100 fold=8 epoch=3 loss=152.9961 val_auc=0.5000
model=graphsage top_k=100 fold=8 epoch=4 loss=135.8884 val_auc=0.5267
model=graphsage top_k=100 fold=8 epoch=5 loss=57.6728 val_auc=0.6993

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=100 fold=8 epoch=6 loss=27.1513 val_auc=0.7178
model=graphsage top_k=100 fold=8 epoch=7 loss=34.5023 val_auc=0.7318
model=graphsage top_k=100 fold=8 epoch=8 loss=18.9248 val_auc=0.5355
model=graphsage top_k=100 fold=8 epoch=9 loss=24.5844 val_auc=0.5330
model=graphsage top_k=100 fold=8 epoch=10 loss=29.9458 val_auc=0.6656
model=graphsage top_k=100 fold=8 epoch=11 loss=19.0173 val_auc=0.7570
model=graphsage top_k=100 fold=8 epoch=12 loss=12.8898 val_auc=0.7594
model=graphsage top_k=100 fold=8 epoch=13 loss=15.0665 val_auc=0.7607
model=graphsage top_k=100 fold=8 epoch=14 loss=12.0607 val_auc=0.7395
model=graphsage top_k=100 fold=8 epoch=15 loss=18.4544 val_auc=0.7099
model=graphsage top_k=100 fold=8 epoch=16 loss=18.5677 val_auc=0.7475
model=graphsage top_k=100 fold=8 epoch=17 loss=10.7960 val_auc=0.7679
model=graphsage top_k=100 fold=8 epoch=18 loss=11.0688 val_auc=0.7696
model=graphsage top_k=100 fold=8 epoch=19 loss=13.8669 val_auc=0.7703
model=graphsage top_k=100 fold=8 epoch=20 loss=9.9652 val_auc=0.7703
model=graphsage top_k=100 fold=8 epoch=21 loss=10.2109 val_auc=0.7685
model=graphsage top_k=100 fold=8 epoch=22 loss=9.7493 val_auc=0.7747
model=graphsage top_k=100 fold=8 epoch=23 loss=12.3389 val_auc=0.7777
model=graphsage top_k=100 fold=8 epoch=24 loss=10.2113 val_auc=0.7795
model=graphsage top_k=100 fold=8 epoch=25 loss=11.3190 val_auc=0.7803
model=graphsage top_k=100 fold=8 epoch=26 loss=8.3703 val_auc=0.7752
model=graphsage top_k=100 fold=8 epoch=27 loss=13.3149 val_auc=0.7636
model=graphsage top_k=100 fold=8 epoch=28 loss=13.8143 val_auc=0.7783
model=graphsage top_k=100 fold=8 epoch=29 loss=10.2838 val_auc=0.7832
model=graphsage top_k=100 fold=8 epoch=30 loss=7.7180 val_auc=0.7850
model=graphsage top_k=100 fold=8 epoch=31 loss=14.4962 val_auc=0.7857
model=graphsage top_k=100 fold=8 epoch=32 loss=16.0125 val_auc=0.7858
model=graphsage top_k=100 fold=8 epoch=33 loss=19.3195 val_auc=0.7852
model=graphsage top_k=100 fold=8 epoch=34 loss=11.0063 val_auc=0.7840
model=graphsage top_k=100 fold=8 epoch=35 loss=9.1949 val_auc=0.7816
model=graphsage top_k=100 fold=8 epoch=36 loss=8.9390 val_auc=0.7819
model=graphsage top_k=100 fold=8 epoch=37 loss=8.3259 val_auc=0.7849
model=graphsage top_k=100 fold=8 epoch=38 loss=7.5267 val_auc=0.7870
model=graphsage top_k=100 fold=8 epoch=39 loss=9.0080 val_auc=0.7878
model=graphsage top_k=100 fold=8 epoch=40 loss=9.5704 val_auc=0.7882
model=graphsage top_k=100 fold=8 epoch=41 loss=10.0357 val_auc=0.7884
model=graphsage top_k=100 fold=8 epoch=42 loss=7.7284 val_auc=0.7886
model=graphsage top_k=100 fold=8 epoch=43 loss=8.9729 val_auc=0.7894
model=graphsage top_k=100 fold=8 epoch=44 loss=7.8653 val_auc=0.7907
model=graphsage top_k=100 fold=8 epoch=45 loss=6.7025 val_auc=0.7916
model=graphsage top_k=100 fold=8 epoch=46 loss=5.9252 val_auc=0.7931
model=graphsage top_k=100 fold=8 epoch=47 loss=6.8328 val_auc=0.7946
model=graphsage top_k=100 fold=8 epoch=48 loss=6.4946 val_auc=0.7962
model=graphsage top_k=100 fold=8 epoch=49 loss=6.7970 val_auc=0.7973
model=graphsage top_k=100 fold=8 epoch=50 loss=7.7055 val_auc=0.7987
model=graphsage top_k=100 fold=8 epoch=51 loss=6.2930 val_auc=0.8001
model=graphsage top_k=100 fold=8 epoch=52 loss=6.1146 val_auc=0.8012
model=graphsage top_k=100 fold=8 epoch=53 loss=7.4377 val_auc=0.8027
model=graphsage top_k=100 fold=8 epoch=54 loss=6.1698 val_auc=0.8038
model=graphsage top_k=100 fold=8 epoch=55 loss=6.8022 val_auc=0.8041
model=graphsage top_k=100 fold=8 epoch=56 loss=6.4610 val_auc=0.8040
model=graphsage top_k=100 fold=8 epoch=57 loss=5.8228 val_auc=0.8040
model=graphsage top_k=100 fold=8 epoch=58 loss=6.4502 val_auc=0.8037
model=graphsage top_k=100 fold=8 epoch=59 loss=7.1340 val_auc=0.8040
model=graphsage top_k=100 fold=8 epoch=60 loss=6.0280 val_auc=0.8041
model=graphsage top_k=100 fold=8 epoch=61 loss=5.4684 val_auc=0.8047
model=graphsage top_k=100 fold=8 epoch=62 loss=4.9302 val_auc=0.8056
model=graphsage top_k=100 fold=8 epoch=63 loss=6.2063 val_auc=0.8065
model=graphsage top_k=100 fold=8 epoch=64 loss=6.6342 val_auc=0.8073
model=graphsage top_k=100 fold=8 epoch=65 loss=4.5989 val_auc=0.8085
model=graphsage top_k=100 fold=8 epoch=66 loss=4.4650 val_auc=0.8099
model=graphsage top_k=100 fold=8 epoch=67 loss=5.7428 val_auc=0.8109
model=graphsage top_k=100 fold=8 epoch=68 loss=4.5700 val_auc=0.8118
model=graphsage top_k=100 fold=8 epoch=69 loss=4.8320 val_auc=0.8126
model=graphsage top_k=100 fold=8 epoch=70 loss=4.1862 val_auc=0.8134
model=graphsage top_k=100 fold=8 epoch=71 loss=4.0655 val_auc=0.8140
model=graphsage top_k=100 fold=8 epoch=72 loss=5.2525 val_auc=0.8149
model=graphsage top_k=100 fold=8 epoch=73 loss=5.6777 val_auc=0.8156
model=graphsage top_k=100 fold=8 epoch=74 loss=3.8502 val_auc=0.8163
model=graphsage top_k=100 fold=8 epoch=75 loss=4.8471 val_auc=0.8167
model=graphsage top_k=100 fold=8 epoch=76 loss=5.3441 val_auc=0.8169
model=graphsage top_k=100 fold=8 epoch=77 loss=3.4264 val_auc=0.8174
model=graphsage top_k=100 fold=8 epoch=78 loss=5.4022 val_auc=0.8178
model=graphsage top_k=100 fold=8 epoch=79 loss=4.9129 val_auc=0.8184
model=graphsage top_k=100 fold=8 epoch=80 loss=4.3467 val_auc=0.8184
model=graphsage top_k=100 fold=8 epoch=81 loss=4.7535 val_auc=0.8185
model=graphsage top_k=100 fold=8 epoch=82 loss=6.5655 val_auc=0.8186
model=graphsage top_k=100 fold=8 epoch=83 loss=4.9415 val_auc=0.8186
model=graphsage top_k=100 fold=8 epoch=84 loss=3.8656 val_auc=0.8187
model=graphsage top_k=100 fold=8 epoch=85 loss=4.6578 val_auc=0.8187
model=graphsage top_k=100 fold=8 epoch=86 loss=3.7567 val_auc=0.8188
model=graphsage top_k=100 fold=8 epoch=87 loss=5.3729 val_auc=0.8190
model=graphsage top_k=100 fold=8 epoch=88 loss=4.7080 val_auc=0.8195
model=graphsage top_k=100 fold=8 epoch=89 loss=4.5601 val_auc=0.8201
model=graphsage top_k=100 fold=8 epoch=90 loss=3.7127 val_auc=0.8210
model=graphsage top_k=100 fold=8 epoch=91 loss=4.2261 val_auc=0.8217
model=graphsage top_k=100 fold=8 epoch=92 loss=3.4659 val_auc=0.8224
model=graphsage top_k=100 fold=8 epoch=93 loss=4.5136 val_auc=0.8229
model=graphsage top_k=100 fold=8 epoch=94 loss=4.0119 val_auc=0.8233
model=graphsage top_k=100 fold=8 epoch=95 loss=3.0922 val_auc=0.8238
model=graphsage top_k=100 fold=8 epoch=96 loss=4.5664 val_auc=0.8242
model=graphsage top_k=100 fold=8 epoch=97 loss=5.5680 val_auc=0.8246
model=graphsage top_k=100 fold=8 epoch=98 loss=3.4732 val_auc=0.8248
model=graphsage top_k=100 fold=8 epoch=99 loss=3.8619 val_auc=0.8248

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=100 fold=9 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=graphsage top_k=100 fold=9 epoch=0 loss=21.7650 val_auc=0.5000
model=graphsage top_k=100 fold=9 epoch=1 loss=255.8000 val_auc=0.5058

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=100 fold=9 epoch=2 loss=34.7821 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=100 fold=9 epoch=3 loss=111.2661 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=100 fold=9 epoch=4 loss=97.1968 val_auc=0.7712
model=graphsage top_k=100 fold=9 epoch=5 loss=54.7962 val_auc=0.6915
model=graphsage top_k=100 fold=9 epoch=6 loss=17.2385 val_auc=0.5494
model=graphsage top_k=100 fold=9 epoch=7 loss=31.6339 val_auc=0.7698
model=graphsage top_k=100 fold=9 epoch=8 loss=14.0155 val_auc=0.7748
model=graphsage top_k=100 fold=9 epoch=9 loss=28.3167 val_auc=0.7754
model=graphsage top_k=100 fold=9 epoch=10 loss=28.4108 val_auc=0.7753
model=graphsage top_k=100 fold=9 epoch=11 loss=19.9879 val_auc=0.7737
model=graphsage top_k=100 fold=9 epoch=12 loss=12.3676 val_auc=0.7161
model=graphsage top_k=100 fold=9 epoch=13 loss=20.1432 val_auc=0.7375
model=graphsage top_k=100 fold=9 epoch=14 loss=18.1298 val_auc=0.7757
model=graphsage top_k=100 fold=9 epoch=15 loss=12.9223 val_auc=0.7769
model=graphsage top_k=100 fold=9 epoch=16 loss=16.0482 val_auc=0.7779
model=graphsage top_k=100 fold=9 epoch=17 loss=22.5188 val_auc=0.7786
model=graphsage top_k=100 fold=9 epoch=18 loss=21.8057 val_auc=0.7786
model=graphsage top_k=100 fold=9 epoch=19 loss=13.9694 val_auc=0.7612
model=graphsage top_k=100 fold=9 epoch=20 loss=17.9779 val_auc=0.6623
model=graphsage top_k=100 fold=9 epoch=21 loss=20.4729 val_auc=0.7042
model=graphsage top_k=100 fold=9 epoch=22 loss=19.3216 val_auc=0.7786
model=graphsage top_k=100 fold=9 epoch=23 loss=12.8580 val_auc=0.7813
model=graphsage top_k=100 fold=9 epoch=24 loss=12.0344 val_auc=0.7821
model=graphsage top_k=100 fold=9 epoch=25 loss=12.7188 val_auc=0.7826
model=graphsage top_k=100 fold=9 epoch=26 loss=13.3799 val_auc=0.7829
model=graphsage top_k=100 fold=9 epoch=27 loss=8.0675 val_auc=0.7786
model=graphsage top_k=100 fold=9 epoch=28 loss=13.3464 val_auc=0.7674
model=graphsage top_k=100 fold=9 epoch=29 loss=14.8554 val_auc=0.7763
model=graphsage top_k=100 fold=9 epoch=30 loss=13.8086 val_auc=0.7872
model=graphsage top_k=100 fold=9 epoch=31 loss=11.4672 val_auc=0.7907
model=graphsage top_k=100 fold=9 epoch=32 loss=13.9111 val_auc=0.7917
model=graphsage top_k=100 fold=9 epoch=33 loss=15.5342 val_auc=0.7921
model=graphsage top_k=100 fold=9 epoch=34 loss=14.0258 val_auc=0.7926
model=graphsage top_k=100 fold=9 epoch=35 loss=11.4501 val_auc=0.7911
model=graphsage top_k=100 fold=9 epoch=36 loss=8.7778 val_auc=0.7881
model=graphsage top_k=100 fold=9 epoch=37 loss=11.9612 val_auc=0.7908
model=graphsage top_k=100 fold=9 epoch=38 loss=8.3389 val_auc=0.7945
model=graphsage top_k=100 fold=9 epoch=39 loss=7.0542 val_auc=0.7966
model=graphsage top_k=100 fold=9 epoch=40 loss=7.8166 val_auc=0.7984
model=graphsage top_k=100 fold=9 epoch=41 loss=9.5347 val_auc=0.7999
model=graphsage top_k=100 fold=9 epoch=42 loss=7.6259 val_auc=0.8013
model=graphsage top_k=100 fold=9 epoch=43 loss=7.9491 val_auc=0.8030
model=graphsage top_k=100 fold=9 epoch=44 loss=7.1816 val_auc=0.8047
model=graphsage top_k=100 fold=9 epoch=45 loss=8.4606 val_auc=0.8062
model=graphsage top_k=100 fold=9 epoch=46 loss=7.8138 val_auc=0.8069
model=graphsage top_k=100 fold=9 epoch=47 loss=8.2764 val_auc=0.8035
model=graphsage top_k=100 fold=9 epoch=48 loss=10.3842 val_auc=0.7960
model=graphsage top_k=100 fold=9 epoch=49 loss=9.2540 val_auc=0.8056
model=graphsage top_k=100 fold=9 epoch=50 loss=8.5513 val_auc=0.8083
model=graphsage top_k=100 fold=9 epoch=51 loss=7.0934 val_auc=0.8088
model=graphsage top_k=100 fold=9 epoch=52 loss=6.5470 val_auc=0.8093
model=graphsage top_k=100 fold=9 epoch=53 loss=8.4098 val_auc=0.8098
model=graphsage top_k=100 fold=9 epoch=54 loss=6.7655 val_auc=0.8076
model=graphsage top_k=100 fold=9 epoch=55 loss=6.8418 val_auc=0.7966
model=graphsage top_k=100 fold=9 epoch=56 loss=8.1410 val_auc=0.8080
model=graphsage top_k=100 fold=9 epoch=57 loss=10.8235 val_auc=0.8119
model=graphsage top_k=100 fold=9 epoch=58 loss=7.3346 val_auc=0.8122
model=graphsage top_k=100 fold=9 epoch=59 loss=6.4711 val_auc=0.8123
model=graphsage top_k=100 fold=9 epoch=60 loss=6.8932 val_auc=0.8124
model=graphsage top_k=100 fold=9 epoch=61 loss=4.9458 val_auc=0.8131
model=graphsage top_k=100 fold=9 epoch=62 loss=6.7539 val_auc=0.8139
model=graphsage top_k=100 fold=9 epoch=63 loss=7.2330 val_auc=0.8114
model=graphsage top_k=100 fold=9 epoch=64 loss=5.6630 val_auc=0.8104
model=graphsage top_k=100 fold=9 epoch=65 loss=6.1146 val_auc=0.8146
model=graphsage top_k=100 fold=9 epoch=66 loss=5.1570 val_auc=0.8161
model=graphsage top_k=100 fold=9 epoch=67 loss=5.4786 val_auc=0.8170
model=graphsage top_k=100 fold=9 epoch=68 loss=5.1946 val_auc=0.8176
model=graphsage top_k=100 fold=9 epoch=69 loss=5.5005 val_auc=0.8183
model=graphsage top_k=100 fold=9 epoch=70 loss=5.2091 val_auc=0.8190
model=graphsage top_k=100 fold=9 epoch=71 loss=5.0053 val_auc=0.8196
model=graphsage top_k=100 fold=9 epoch=72 loss=4.5322 val_auc=0.8202
model=graphsage top_k=100 fold=9 epoch=73 loss=6.7539 val_auc=0.8207
model=graphsage top_k=100 fold=9 epoch=74 loss=4.9270 val_auc=0.8211
model=graphsage top_k=100 fold=9 epoch=75 loss=5.0779 val_auc=0.8212
model=graphsage top_k=100 fold=9 epoch=76 loss=4.4516 val_auc=0.8220
model=graphsage top_k=100 fold=9 epoch=77 loss=6.0266 val_auc=0.8228
model=graphsage top_k=100 fold=9 epoch=78 loss=6.0293 val_auc=0.8236
model=graphsage top_k=100 fold=9 epoch=79 loss=4.1490 val_auc=0.8247
model=graphsage top_k=100 fold=9 epoch=80 loss=4.8263 val_auc=0.8256
model=graphsage top_k=100 fold=9 epoch=81 loss=5.2423 val_auc=0.8265
model=graphsage top_k=100 fold=9 epoch=82 loss=3.6630 val_auc=0.8275
model=graphsage top_k=100 fold=9 epoch=83 loss=3.9895 val_auc=0.8281
model=graphsage top_k=100 fold=9 epoch=84 loss=3.7056 val_auc=0.8288
model=graphsage top_k=100 fold=9 epoch=85 loss=3.9896 val_auc=0.8294
model=graphsage top_k=100 fold=9 epoch=86 loss=4.0714 val_auc=0.8299
model=graphsage top_k=100 fold=9 epoch=87 loss=3.8859 val_auc=0.8301
model=graphsage top_k=100 fold=9 epoch=88 loss=3.9255 val_auc=0.8302
model=graphsage top_k=100 fold=9 epoch=89 loss=4.4636 val_auc=0.8299
model=graphsage top_k=100 fold=9 epoch=90 loss=3.6773 val_auc=0.8296
model=graphsage top_k=100 fold=9 epoch=91 loss=3.7906 val_auc=0.8292
model=graphsage top_k=100 fold=9 epoch=92 loss=3.4340 val_auc=0.8291
model=graphsage top_k=100 fold=9 epoch=93 loss=3.9263 val_auc=0.8288
model=graphsage top_k=100 fold=9 epoch=94 loss=3.3850 val_auc=0.8290
model=graphsage top_k=100 fold=9 epoch=95 loss=3.1856 val_auc=0.8298
model=graphsage top_k=100 fold=9 epoch=96 loss=3.3674 val_auc=0.8308
model=graphsage top_k=100 fold=9 epoch=97 loss=3.4859 val_auc=0.8314
model=graphsage top_k=100 fold=9 epoch=98 loss=4.3007 val_auc=0.8308
model=graphsage top_k=100 fold=9 epoch=99 loss=2.8150 val_auc=0.8307

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

######## Model=graphsage top_k=200 ########

===== Model=graphsage top_k=200 fold=0 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=graphsage top_k=200 fold=0 epoch=0 loss=24.5339 val_auc=0.5000
model=graphsage top_k=200 fold=0 epoch=1 loss=325.4604 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=200 fold=0 epoch=2 loss=119.5585 val_auc=0.6142
model=graphsage top_k=200 fold=0 epoch=3 loss=62.4047 val_auc=0.7589
model=graphsage top_k=200 fold=0 epoch=4 loss=49.4411 val_auc=0.7557
model=graphsage top_k=200 fold=0 epoch=5 loss=12.7882 val_auc=0.7613
model=graphsage top_k=200 fold=0 epoch=6 loss=16.0878 val_auc=0.7654
model=graphsage top_k=200 fold=0 epoch=7 loss=20.6809 val_auc=0.7679
model=graphsage top_k=200 fold=0 epoch=8 loss=20.3480 val_auc=0.7651
model=graphsage top_k=200 fold=0 epoch=9 loss=13.3887 val_auc=0.7406
model=graphsage top_k=200 fold=0 epoch=10 loss=19.4349 val_auc=0.7707
model=graphsage top_k=200 fold=0 epoch=11 loss=11.8172 val_auc=0.7742
model=graphsage top_k=200 fold=0 epoch=12 loss=11.6298 val_auc=0.7622
model=graphsage top_k=200 fold=0 epoch=13 loss=18.5588 val_auc=0.7705
model=graphsage top_k=200 fold=0 epoch=14 loss=12.8652 val_auc=0.7814
model=graphsage top_k=200 fold=0 epoch=15 loss=9.8747 val_auc=0.7835
model=graphsage top_k=200 fold=0 epoch=16 loss=16.2732 val_auc=0.7854
model=graphsage top_k=200 fold=0 epoch=17 loss=14.0620 val_auc=0.7847
model=graphsage top_k=200 fold=0 epoch=18 loss=10.7326 val_auc=0.7841
model=graphsage top_k=200 fold=0 epoch=19 loss=10.0910 val_auc=0.7887
model=graphsage top_k=200 fold=0 epoch=20 loss=8.3359 val_auc=0.7898
model=graphsage top_k=200 fold=0 epoch=21 loss=9.9817 val_auc=0.7875
model=graphsage top_k=200 fold=0 epoch=22 loss=9.9434 val_auc=0.7892
model=graphsage top_k=200 fold=0 epoch=23 loss=9.1182 val_auc=0.7910
model=graphsage top_k=200 fold=0 epoch=24 loss=10.8708 val_auc=0.7913
model=graphsage top_k=200 fold=0 epoch=25 loss=9.5252 val_auc=0.7913
model=graphsage top_k=200 fold=0 epoch=26 loss=9.9452 val_auc=0.7919
model=graphsage top_k=200 fold=0 epoch=27 loss=9.3452 val_auc=0.7923
model=graphsage top_k=200 fold=0 epoch=28 loss=10.0229 val_auc=0.7927
model=graphsage top_k=200 fold=0 epoch=29 loss=8.9967 val_auc=0.7935
model=graphsage top_k=200 fold=0 epoch=30 loss=8.0176 val_auc=0.7955
model=graphsage top_k=200 fold=0 epoch=31 loss=7.6403 val_auc=0.7976
model=graphsage top_k=200 fold=0 epoch=32 loss=10.2411 val_auc=0.7991
model=graphsage top_k=200 fold=0 epoch=33 loss=8.1536 val_auc=0.7989
model=graphsage top_k=200 fold=0 epoch=34 loss=9.5495 val_auc=0.8011
model=graphsage top_k=200 fold=0 epoch=35 loss=7.6445 val_auc=0.8027
model=graphsage top_k=200 fold=0 epoch=36 loss=7.9563 val_auc=0.8036
model=graphsage top_k=200 fold=0 epoch=37 loss=8.6866 val_auc=0.8044
model=graphsage top_k=200 fold=0 epoch=38 loss=8.6263 val_auc=0.7882
model=graphsage top_k=200 fold=0 epoch=39 loss=12.1561 val_auc=0.7739
model=graphsage top_k=200 fold=0 epoch=40 loss=12.5867 val_auc=0.7994
model=graphsage top_k=200 fold=0 epoch=41 loss=10.5970 val_auc=0.8067
model=graphsage top_k=200 fold=0 epoch=42 loss=7.1905 val_auc=0.8072
model=graphsage top_k=200 fold=0 epoch=43 loss=8.5344 val_auc=0.8078
model=graphsage top_k=200 fold=0 epoch=44 loss=7.0127 val_auc=0.8076
model=graphsage top_k=200 fold=0 epoch=45 loss=7.0701 val_auc=0.8071
model=graphsage top_k=200 fold=0 epoch=46 loss=6.3279 val_auc=0.8083
model=graphsage top_k=200 fold=0 epoch=47 loss=6.0148 val_auc=0.8084
model=graphsage top_k=200 fold=0 epoch=48 loss=7.3052 val_auc=0.8086
model=graphsage top_k=200 fold=0 epoch=49 loss=9.0943 val_auc=0.8089
model=graphsage top_k=200 fold=0 epoch=50 loss=8.0439 val_auc=0.8091
model=graphsage top_k=200 fold=0 epoch=51 loss=5.6983 val_auc=0.8078
model=graphsage top_k=200 fold=0 epoch=52 loss=8.8581 val_auc=0.8069
model=graphsage top_k=200 fold=0 epoch=53 loss=7.0661 val_auc=0.8104
model=graphsage top_k=200 fold=0 epoch=54 loss=7.4657 val_auc=0.8103
model=graphsage top_k=200 fold=0 epoch=55 loss=6.9524 val_auc=0.8102
model=graphsage top_k=200 fold=0 epoch=56 loss=7.1196 val_auc=0.8104
model=graphsage top_k=200 fold=0 epoch=57 loss=5.7439 val_auc=0.8107
model=graphsage top_k=200 fold=0 epoch=58 loss=5.4153 val_auc=0.8097
model=graphsage top_k=200 fold=0 epoch=59 loss=6.2039 val_auc=0.8091
model=graphsage top_k=200 fold=0 epoch=60 loss=7.7337 val_auc=0.8114
model=graphsage top_k=200 fold=0 epoch=61 loss=6.5560 val_auc=0.8115
model=graphsage top_k=200 fold=0 epoch=62 loss=5.6748 val_auc=0.8115
model=graphsage top_k=200 fold=0 epoch=63 loss=5.6843 val_auc=0.8118
model=graphsage top_k=200 fold=0 epoch=64 loss=5.9350 val_auc=0.8121
model=graphsage top_k=200 fold=0 epoch=65 loss=4.5096 val_auc=0.8103
model=graphsage top_k=200 fold=0 epoch=66 loss=7.5294 val_auc=0.8102
model=graphsage top_k=200 fold=0 epoch=67 loss=6.6134 val_auc=0.8132
model=graphsage top_k=200 fold=0 epoch=68 loss=5.7136 val_auc=0.8134
model=graphsage top_k=200 fold=0 epoch=69 loss=5.9959 val_auc=0.8136
model=graphsage top_k=200 fold=0 epoch=70 loss=7.0736 val_auc=0.8140
model=graphsage top_k=200 fold=0 epoch=71 loss=5.1099 val_auc=0.8142
model=graphsage top_k=200 fold=0 epoch=72 loss=4.2999 val_auc=0.8140
model=graphsage top_k=200 fold=0 epoch=73 loss=4.3166 val_auc=0.8139
model=graphsage top_k=200 fold=0 epoch=74 loss=4.7303 val_auc=0.8141
model=graphsage top_k=200 fold=0 epoch=75 loss=3.7867 val_auc=0.8137
model=graphsage top_k=200 fold=0 epoch=76 loss=4.9434 val_auc=0.8141
model=graphsage top_k=200 fold=0 epoch=77 loss=3.9027 val_auc=0.8151
model=graphsage top_k=200 fold=0 epoch=78 loss=4.1698 val_auc=0.8157
model=graphsage top_k=200 fold=0 epoch=79 loss=5.4252 val_auc=0.8161
model=graphsage top_k=200 fold=0 epoch=80 loss=4.1795 val_auc=0.8165
model=graphsage top_k=200 fold=0 epoch=81 loss=5.7372 val_auc=0.8161
model=graphsage top_k=200 fold=0 epoch=82 loss=4.2650 val_auc=0.8152
model=graphsage top_k=200 fold=0 epoch=83 loss=4.2067 val_auc=0.8148
model=graphsage top_k=200 fold=0 epoch=84 loss=5.1101 val_auc=0.8149
model=graphsage top_k=200 fold=0 epoch=85 loss=4.6867 val_auc=0.8158
model=graphsage top_k=200 fold=0 epoch=86 loss=4.7873 val_auc=0.8163
model=graphsage top_k=200 fold=0 epoch=87 loss=4.8182 val_auc=0.8166
model=graphsage top_k=200 fold=0 epoch=88 loss=4.9416 val_auc=0.8167
model=graphsage top_k=200 fold=0 epoch=89 loss=4.4190 val_auc=0.8169
model=graphsage top_k=200 fold=0 epoch=90 loss=4.2906 val_auc=0.8171
model=graphsage top_k=200 fold=0 epoch=91 loss=4.2150 val_auc=0.8170
model=graphsage top_k=200 fold=0 epoch=92 loss=4.7702 val_auc=0.8166
model=graphsage top_k=200 fold=0 epoch=93 loss=3.7395 val_auc=0.8163
model=graphsage top_k=200 fold=0 epoch=94 loss=3.5951 val_auc=0.8163
model=graphsage top_k=200 fold=0 epoch=95 loss=3.3198 val_auc=0.8167
model=graphsage top_k=200 fold=0 epoch=96 loss=3.6245 val_auc=0.8169
model=graphsage top_k=200 fold=0 epoch=97 loss=3.0900 val_auc=0.8177
model=graphsage top_k=200 fold=0 epoch=98 loss=2.9647 val_auc=0.8192
model=graphsage top_k=200 fold=0 epoch=99 loss=3.6305 val_auc=0.8213

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=200 fold=1 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=200 fold=1 epoch=0 loss=16.5095 val_auc=0.5000
model=graphsage top_k=200 fold=1 epoch=1 loss=152.8596 val_auc=0.5323
model=graphsage top_k=200 fold=1 epoch=2 loss=44.2388 val_auc=0.7485
model=graphsage top_k=200 fold=1 epoch=3 loss=19.8337 val_auc=0.5434
model=graphsage top_k=200 fold=1 epoch=4 loss=24.1649 val_auc=0.7639
model=graphsage top_k=200 fold=1 epoch=5 loss=12.3826 val_auc=0.7344
model=graphsage top_k=200 fold=1 epoch=6 loss=16.1752 val_auc=0.7739
model=graphsage top_k=200 fold=1 epoch=7 loss=13.0938 val_auc=0.7489
model=graphsage top_k=200 fold=1 epoch=8 loss=12.4310 val_auc=0.7812
model=graphsage top_k=200 fold=1 epoch=9 loss=15.0028 val_auc=0.7797
model=graphsage top_k=200 fold=1 epoch=10 loss=14.6363 val_auc=0.7837
model=graphsage top_k=200 fold=1 epoch=11 loss=11.2936 val_auc=0.7859
model=graphsage top_k=200 fold=1 epoch=12 loss=9.9780 val_auc=0.7298
model=graphsage top_k=200 fold=1 epoch=13 loss=17.2664 val_auc=0.7579
model=graphsage top_k=200 fold=1 epoch=14 loss=14.7325 val_auc=0.7902
model=graphsage top_k=200 fold=1 epoch=15 loss=11.0564 val_auc=0.7914
model=graphsage top_k=200 fold=1 epoch=16 loss=11.4970 val_auc=0.7897
model=graphsage top_k=200 fold=1 epoch=17 loss=8.8378 val_auc=0.7918
model=graphsage top_k=200 fold=1 epoch=18 loss=10.8515 val_auc=0.7964
model=graphsage top_k=200 fold=1 epoch=19 loss=10.6106 val_auc=0.7977
model=graphsage top_k=200 fold=1 epoch=20 loss=11.0142 val_auc=0.7973
model=graphsage top_k=200 fold=1 epoch=21 loss=8.3529 val_auc=0.7854
model=graphsage top_k=200 fold=1 epoch=22 loss=8.5481 val_auc=0.7979
model=graphsage top_k=200 fold=1 epoch=23 loss=9.3442 val_auc=0.8025
model=graphsage top_k=200 fold=1 epoch=24 loss=11.6835 val_auc=0.8029
model=graphsage top_k=200 fold=1 epoch=25 loss=9.4767 val_auc=0.8027
model=graphsage top_k=200 fold=1 epoch=26 loss=7.3974 val_auc=0.8027
model=graphsage top_k=200 fold=1 epoch=27 loss=8.5450 val_auc=0.8050
model=graphsage top_k=200 fold=1 epoch=28 loss=6.9873 val_auc=0.8061
model=graphsage top_k=200 fold=1 epoch=29 loss=9.0733 val_auc=0.7921
model=graphsage top_k=200 fold=1 epoch=30 loss=11.0894 val_auc=0.7889
model=graphsage top_k=200 fold=1 epoch=31 loss=9.0549 val_auc=0.8081
model=graphsage top_k=200 fold=1 epoch=32 loss=7.2773 val_auc=0.8096
model=graphsage top_k=200 fold=1 epoch=33 loss=9.8689 val_auc=0.8095
model=graphsage top_k=200 fold=1 epoch=34 loss=14.2086 val_auc=0.8097
model=graphsage top_k=200 fold=1 epoch=35 loss=11.5027 val_auc=0.8095
model=graphsage top_k=200 fold=1 epoch=36 loss=6.8898 val_auc=0.7501
model=graphsage top_k=200 fold=1 epoch=37 loss=15.4979 val_auc=0.6431
model=graphsage top_k=200 fold=1 epoch=38 loss=20.7843 val_auc=0.6858
model=graphsage top_k=200 fold=1 epoch=39 loss=16.0492 val_auc=0.7908
model=graphsage top_k=200 fold=1 epoch=40 loss=11.2690 val_auc=0.8085
model=graphsage top_k=200 fold=1 epoch=41 loss=7.3325 val_auc=0.8090
model=graphsage top_k=200 fold=1 epoch=42 loss=16.1370 val_auc=0.8093
model=graphsage top_k=200 fold=1 epoch=43 loss=23.3569 val_auc=0.8094
model=graphsage top_k=200 fold=1 epoch=44 loss=18.3674 val_auc=0.8094
model=graphsage top_k=200 fold=1 epoch=45 loss=12.2879 val_auc=0.8090
model=graphsage top_k=200 fold=1 epoch=46 loss=6.6938 val_auc=0.8003
graphsage top_k=200 fold=1: early stopping at epoch 46

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=200 fold=2 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=200 fold=2 epoch=0 loss=21.9935 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=200 fold=2 epoch=1 loss=212.6107 val_auc=0.5761
model=graphsage top_k=200 fold=2 epoch=2 loss=39.5725 val_auc=0.5000
model=graphsage top_k=200 fold=2 epoch=3 loss=137.1763 val_auc=0.5000
model=graphsage top_k=200 fold=2 epoch=4 loss=132.3828 val_auc=0.5349
model=graphsage top_k=200 fold=2 epoch=5 loss=53.3892 val_auc=0.7232
model=graphsage top_k=200 fold=2 epoch=6 loss=31.5888 val_auc=0.7374
model=graphsage top_k=200 fold=2 epoch=7 loss=40.7777 val_auc=0.7501
model=graphsage top_k=200 fold=2 epoch=8 loss=24.6046 val_auc=0.7517
model=graphsage top_k=200 fold=2 epoch=9 loss=15.5689 val_auc=0.5361
model=graphsage top_k=200 fold=2 epoch=10 loss=26.8515 val_auc=0.6084
model=graphsage top_k=200 fold=2 epoch=11 loss=24.7407 val_auc=0.7662
model=graphsage top_k=200 fold=2 epoch=12 loss=12.1188 val_auc=0.7681
model=graphsage top_k=200 fold=2 epoch=13 loss=17.7881 val_auc=0.7699
model=graphsage top_k=200 fold=2 epoch=14 loss=20.7642 val_auc=0.7711
model=graphsage top_k=200 fold=2 epoch=15 loss=15.1706 val_auc=0.7695
model=graphsage top_k=200 fold=2 epoch=16 loss=13.4555 val_auc=0.7390
model=graphsage top_k=200 fold=2 epoch=17 loss=16.0036 val_auc=0.7706
model=graphsage top_k=200 fold=2 epoch=18 loss=13.1050 val_auc=0.7736
model=graphsage top_k=200 fold=2 epoch=19 loss=9.0323 val_auc=0.7751
model=graphsage top_k=200 fold=2 epoch=20 loss=14.8072 val_auc=0.7764
model=graphsage top_k=200 fold=2 epoch=21 loss=10.7578 val_auc=0.7754
model=graphsage top_k=200 fold=2 epoch=22 loss=10.0822 val_auc=0.7753
model=graphsage top_k=200 fold=2 epoch=23 loss=11.5237 val_auc=0.7809
model=graphsage top_k=200 fold=2 epoch=24 loss=10.4858 val_auc=0.7830
model=graphsage top_k=200 fold=2 epoch=25 loss=10.1823 val_auc=0.7840
model=graphsage top_k=200 fold=2 epoch=26 loss=10.6434 val_auc=0.7841
model=graphsage top_k=200 fold=2 epoch=27 loss=10.6764 val_auc=0.7832
model=graphsage top_k=200 fold=2 epoch=28 loss=7.9350 val_auc=0.7827
model=graphsage top_k=200 fold=2 epoch=29 loss=10.0823 val_auc=0.7849
model=graphsage top_k=200 fold=2 epoch=30 loss=8.0601 val_auc=0.7874
model=graphsage top_k=200 fold=2 epoch=31 loss=9.6991 val_auc=0.7888
model=graphsage top_k=200 fold=2 epoch=32 loss=8.3491 val_auc=0.7898
model=graphsage top_k=200 fold=2 epoch=33 loss=9.4551 val_auc=0.7910
model=graphsage top_k=200 fold=2 epoch=34 loss=8.5530 val_auc=0.7934
model=graphsage top_k=200 fold=2 epoch=35 loss=7.3567 val_auc=0.7958
model=graphsage top_k=200 fold=2 epoch=36 loss=7.1957 val_auc=0.7976
model=graphsage top_k=200 fold=2 epoch=37 loss=7.6602 val_auc=0.7993
model=graphsage top_k=200 fold=2 epoch=38 loss=7.9386 val_auc=0.7940
model=graphsage top_k=200 fold=2 epoch=39 loss=12.7687 val_auc=0.7894
model=graphsage top_k=200 fold=2 epoch=40 loss=13.5302 val_auc=0.8015
model=graphsage top_k=200 fold=2 epoch=41 loss=8.4260 val_auc=0.8057
model=graphsage top_k=200 fold=2 epoch=42 loss=6.8788 val_auc=0.8067
model=graphsage top_k=200 fold=2 epoch=43 loss=13.2770 val_auc=0.8071
model=graphsage top_k=200 fold=2 epoch=44 loss=16.9359 val_auc=0.8069
model=graphsage top_k=200 fold=2 epoch=45 loss=13.7268 val_auc=0.8063
model=graphsage top_k=200 fold=2 epoch=46 loss=13.1354 val_auc=0.8052
model=graphsage top_k=200 fold=2 epoch=47 loss=8.3435 val_auc=0.7955
model=graphsage top_k=200 fold=2 epoch=48 loss=8.3990 val_auc=0.7480
model=graphsage top_k=200 fold=2 epoch=49 loss=11.6826 val_auc=0.7446
model=graphsage top_k=200 fold=2 epoch=50 loss=16.0632 val_auc=0.7848
model=graphsage top_k=200 fold=2 epoch=51 loss=11.7082 val_auc=0.8030
model=graphsage top_k=200 fold=2 epoch=52 loss=7.1242 val_auc=0.8047
model=graphsage top_k=200 fold=2 epoch=53 loss=7.0716 val_auc=0.8054
model=graphsage top_k=200 fold=2 epoch=54 loss=11.1112 val_auc=0.8057
model=graphsage top_k=200 fold=2 epoch=55 loss=11.4163 val_auc=0.8060
graphsage top_k=200 fold=2: early stopping at epoch 55

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=200 fold=3 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=graphsage top_k=200 fold=3 epoch=0 loss=23.3240 val_auc=0.5000
model=graphsage top_k=200 fold=3 epoch=1 loss=332.5124 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=200 fold=3 epoch=2 loss=122.9699 val_auc=0.6147
model=graphsage top_k=200 fold=3 epoch=3 loss=66.9191 val_auc=0.7356
model=graphsage top_k=200 fold=3 epoch=4 loss=45.5667 val_auc=0.7455
model=graphsage top_k=200 fold=3 epoch=5 loss=13.7594 val_auc=0.7582
model=graphsage top_k=200 fold=3 epoch=6 loss=13.4408 val_auc=0.7664
model=graphsage top_k=200 fold=3 epoch=7 loss=28.2198 val_auc=0.7707
model=graphsage top_k=200 fold=3 epoch=8 loss=14.2641 val_auc=0.7532
model=graphsage top_k=200 fold=3 epoch=9 loss=15.4254 val_auc=0.7472
model=graphsage top_k=200 fold=3 epoch=10 loss=17.1422 val_auc=0.7767
model=graphsage top_k=200 fold=3 epoch=11 loss=9.1425 val_auc=0.7791
model=graphsage top_k=200 fold=3 epoch=12 loss=10.1053 val_auc=0.7607
model=graphsage top_k=200 fold=3 epoch=13 loss=12.8471 val_auc=0.7748
model=graphsage top_k=200 fold=3 epoch=14 loss=11.2148 val_auc=0.7864
model=graphsage top_k=200 fold=3 epoch=15 loss=12.3216 val_auc=0.7881
model=graphsage top_k=200 fold=3 epoch=16 loss=9.6067 val_auc=0.7878
model=graphsage top_k=200 fold=3 epoch=17 loss=10.7426 val_auc=0.7894
model=graphsage top_k=200 fold=3 epoch=18 loss=9.9213 val_auc=0.7908
model=graphsage top_k=200 fold=3 epoch=19 loss=11.1085 val_auc=0.7913
model=graphsage top_k=200 fold=3 epoch=20 loss=10.0037 val_auc=0.7811
model=graphsage top_k=200 fold=3 epoch=21 loss=9.6497 val_auc=0.7791
model=graphsage top_k=200 fold=3 epoch=22 loss=12.1008 val_auc=0.7914
model=graphsage top_k=200 fold=3 epoch=23 loss=7.8295 val_auc=0.7926
model=graphsage top_k=200 fold=3 epoch=24 loss=10.0014 val_auc=0.7943
model=graphsage top_k=200 fold=3 epoch=25 loss=7.0040 val_auc=0.7967
model=graphsage top_k=200 fold=3 epoch=26 loss=7.5625 val_auc=0.7987
model=graphsage top_k=200 fold=3 epoch=27 loss=10.6695 val_auc=0.8002
model=graphsage top_k=200 fold=3 epoch=28 loss=8.0359 val_auc=0.8014
model=graphsage top_k=200 fold=3 epoch=29 loss=8.6785 val_auc=0.8028
model=graphsage top_k=200 fold=3 epoch=30 loss=7.5386 val_auc=0.8038
model=graphsage top_k=200 fold=3 epoch=31 loss=8.8316 val_auc=0.8046
model=graphsage top_k=200 fold=3 epoch=32 loss=8.3104 val_auc=0.8057
model=graphsage top_k=200 fold=3 epoch=33 loss=10.0021 val_auc=0.7470
model=graphsage top_k=200 fold=3 epoch=34 loss=11.3725 val_auc=0.6867
model=graphsage top_k=200 fold=3 epoch=35 loss=17.9332 val_auc=0.7231
model=graphsage top_k=200 fold=3 epoch=36 loss=14.7839 val_auc=0.7914
model=graphsage top_k=200 fold=3 epoch=37 loss=9.2624 val_auc=0.8060
model=graphsage top_k=200 fold=3 epoch=38 loss=8.1878 val_auc=0.8058
model=graphsage top_k=200 fold=3 epoch=39 loss=11.9216 val_auc=0.8059
model=graphsage top_k=200 fold=3 epoch=40 loss=11.3578 val_auc=0.8061
model=graphsage top_k=200 fold=3 epoch=41 loss=7.4976 val_auc=0.8051
model=graphsage top_k=200 fold=3 epoch=42 loss=7.1855 val_auc=0.7966
model=graphsage top_k=200 fold=3 epoch=43 loss=10.5930 val_auc=0.8015
model=graphsage top_k=200 fold=3 epoch=44 loss=7.4455 val_auc=0.8066
model=graphsage top_k=200 fold=3 epoch=45 loss=7.7010 val_auc=0.8066
model=graphsage top_k=200 fold=3 epoch=46 loss=9.1722 val_auc=0.8066
model=graphsage top_k=200 fold=3 epoch=47 loss=12.1780 val_auc=0.8067
model=graphsage top_k=200 fold=3 epoch=48 loss=11.5017 val_auc=0.8069
model=graphsage top_k=200 fold=3 epoch=49 loss=8.9064 val_auc=0.8065
model=graphsage top_k=200 fold=3 epoch=50 loss=7.6404 val_auc=0.8043
model=graphsage top_k=200 fold=3 epoch=51 loss=6.8631 val_auc=0.8065
model=graphsage top_k=200 fold=3 epoch=52 loss=6.6402 val_auc=0.8084
model=graphsage top_k=200 fold=3 epoch=53 loss=5.4853 val_auc=0.8091
model=graphsage top_k=200 fold=3 epoch=54 loss=6.9253 val_auc=0.8099
model=graphsage top_k=200 fold=3 epoch=55 loss=7.8560 val_auc=0.8108
model=graphsage top_k=200 fold=3 epoch=56 loss=7.2707 val_auc=0.8116
model=graphsage top_k=200 fold=3 epoch=57 loss=7.1269 val_auc=0.8119
model=graphsage top_k=200 fold=3 epoch=58 loss=10.0335 val_auc=0.8053
model=graphsage top_k=200 fold=3 epoch=59 loss=12.4317 val_auc=0.8079
model=graphsage top_k=200 fold=3 epoch=60 loss=11.0679 val_auc=0.8134
model=graphsage top_k=200 fold=3 epoch=61 loss=7.4049 val_auc=0.8132
model=graphsage top_k=200 fold=3 epoch=62 loss=6.8578 val_auc=0.8131
model=graphsage top_k=200 fold=3 epoch=63 loss=6.9378 val_auc=0.8132
model=graphsage top_k=200 fold=3 epoch=64 loss=7.2777 val_auc=0.8133
model=graphsage top_k=200 fold=3 epoch=65 loss=6.6898 val_auc=0.8127
model=graphsage top_k=200 fold=3 epoch=66 loss=6.0934 val_auc=0.8101
model=graphsage top_k=200 fold=3 epoch=67 loss=8.1799 val_auc=0.8118
model=graphsage top_k=200 fold=3 epoch=68 loss=6.8383 val_auc=0.8130
model=graphsage top_k=200 fold=3 epoch=69 loss=6.3742 val_auc=0.8129
model=graphsage top_k=200 fold=3 epoch=70 loss=6.0254 val_auc=0.8132
model=graphsage top_k=200 fold=3 epoch=71 loss=7.9601 val_auc=0.8135
model=graphsage top_k=200 fold=3 epoch=72 loss=8.0031 val_auc=0.8137
model=graphsage top_k=200 fold=3 epoch=73 loss=6.0635 val_auc=0.8140
model=graphsage top_k=200 fold=3 epoch=74 loss=4.3774 val_auc=0.8141
model=graphsage top_k=200 fold=3 epoch=75 loss=6.0912 val_auc=0.8148
model=graphsage top_k=200 fold=3 epoch=76 loss=4.8812 val_auc=0.8155
model=graphsage top_k=200 fold=3 epoch=77 loss=4.1700 val_auc=0.8162
model=graphsage top_k=200 fold=3 epoch=78 loss=4.4272 val_auc=0.8169
model=graphsage top_k=200 fold=3 epoch=79 loss=4.2473 val_auc=0.8177
model=graphsage top_k=200 fold=3 epoch=80 loss=5.7435 val_auc=0.8180
model=graphsage top_k=200 fold=3 epoch=81 loss=4.7689 val_auc=0.8181
model=graphsage top_k=200 fold=3 epoch=82 loss=4.6172 val_auc=0.8184
model=graphsage top_k=200 fold=3 epoch=83 loss=6.1124 val_auc=0.8189
model=graphsage top_k=200 fold=3 epoch=84 loss=6.3423 val_auc=0.8192
model=graphsage top_k=200 fold=3 epoch=85 loss=5.5124 val_auc=0.8195
model=graphsage top_k=200 fold=3 epoch=86 loss=4.6569 val_auc=0.8197
model=graphsage top_k=200 fold=3 epoch=87 loss=6.3220 val_auc=0.8195
model=graphsage top_k=200 fold=3 epoch=88 loss=3.8974 val_auc=0.8189
model=graphsage top_k=200 fold=3 epoch=89 loss=4.4541 val_auc=0.8185
model=graphsage top_k=200 fold=3 epoch=90 loss=4.7182 val_auc=0.8185
model=graphsage top_k=200 fold=3 epoch=91 loss=4.0869 val_auc=0.8184
model=graphsage top_k=200 fold=3 epoch=92 loss=4.7877 val_auc=0.8185
model=graphsage top_k=200 fold=3 epoch=93 loss=3.7760 val_auc=0.8188
model=graphsage top_k=200 fold=3 epoch=94 loss=3.5993 val_auc=0.8194
model=graphsage top_k=200 fold=3 epoch=95 loss=4.2969 val_auc=0.8200
model=graphsage top_k=200 fold=3 epoch=96 loss=5.7656 val_auc=0.8206
model=graphsage top_k=200 fold=3 epoch=97 loss=3.9924 val_auc=0.8208
model=graphsage top_k=200 fold=3 epoch=98 loss=4.6713 val_auc=0.8210
model=graphsage top_k=200 fold=3 epoch=99 loss=4.2305 val_auc=0.8212

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=200 fold=4 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=200 fold=4 epoch=0 loss=22.2750 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=200 fold=4 epoch=1 loss=230.8206 val_auc=0.5190
model=graphsage top_k=200 fold=4 epoch=2 loss=89.3742 val_auc=0.5006
model=graphsage top_k=200 fold=4 epoch=3 loss=86.0942 val_auc=0.5007
model=graphsage top_k=200 fold=4 epoch=4 loss=62.7659 val_auc=0.6712

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=200 fold=4 epoch=5 loss=14.3834 val_auc=0.7243

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=200 fold=4 epoch=6 loss=54.8268 val_auc=0.7447
model=graphsage top_k=200 fold=4 epoch=7 loss=48.3228 val_auc=0.7528
model=graphsage top_k=200 fold=4 epoch=8 loss=25.5167 val_auc=0.6810
model=graphsage top_k=200 fold=4 epoch=9 loss=21.6758 val_auc=0.5019
model=graphsage top_k=200 fold=4 epoch=10 loss=35.8978 val_auc=0.6323
model=graphsage top_k=200 fold=4 epoch=11 loss=22.1284 val_auc=0.7679
model=graphsage top_k=200 fold=4 epoch=12 loss=11.8451 val_auc=0.7700
model=graphsage top_k=200 fold=4 epoch=13 loss=15.8974 val_auc=0.7700
model=graphsage top_k=200 fold=4 epoch=14 loss=12.2431 val_auc=0.7725
model=graphsage top_k=200 fold=4 epoch=15 loss=10.7746 val_auc=0.7717
model=graphsage top_k=200 fold=4 epoch=16 loss=10.2065 val_auc=0.7774
model=graphsage top_k=200 fold=4 epoch=17 loss=9.6703 val_auc=0.7816
model=graphsage top_k=200 fold=4 epoch=18 loss=9.0360 val_auc=0.7832
model=graphsage top_k=200 fold=4 epoch=19 loss=11.7849 val_auc=0.7862
model=graphsage top_k=200 fold=4 epoch=20 loss=11.9693 val_auc=0.7887
model=graphsage top_k=200 fold=4 epoch=21 loss=12.0286 val_auc=0.7892
model=graphsage top_k=200 fold=4 epoch=22 loss=10.5802 val_auc=0.7849
model=graphsage top_k=200 fold=4 epoch=23 loss=11.7839 val_auc=0.7845
model=graphsage top_k=200 fold=4 epoch=24 loss=9.7940 val_auc=0.7909
model=graphsage top_k=200 fold=4 epoch=25 loss=9.2211 val_auc=0.7926
model=graphsage top_k=200 fold=4 epoch=26 loss=11.4742 val_auc=0.7936
model=graphsage top_k=200 fold=4 epoch=27 loss=9.0703 val_auc=0.7944
model=graphsage top_k=200 fold=4 epoch=28 loss=8.4790 val_auc=0.7947
model=graphsage top_k=200 fold=4 epoch=29 loss=8.9984 val_auc=0.7962
model=graphsage top_k=200 fold=4 epoch=30 loss=7.9659 val_auc=0.7973
model=graphsage top_k=200 fold=4 epoch=31 loss=7.4583 val_auc=0.7983
model=graphsage top_k=200 fold=4 epoch=32 loss=8.3585 val_auc=0.7998
model=graphsage top_k=200 fold=4 epoch=33 loss=7.3315 val_auc=0.8007
model=graphsage top_k=200 fold=4 epoch=34 loss=7.5393 val_auc=0.8023
model=graphsage top_k=200 fold=4 epoch=35 loss=9.0941 val_auc=0.8034
model=graphsage top_k=200 fold=4 epoch=36 loss=9.0038 val_auc=0.8039
model=graphsage top_k=200 fold=4 epoch=37 loss=6.5299 val_auc=0.8036
model=graphsage top_k=200 fold=4 epoch=38 loss=10.8021 val_auc=0.8059
model=graphsage top_k=200 fold=4 epoch=39 loss=8.3482 val_auc=0.8073
model=graphsage top_k=200 fold=4 epoch=40 loss=6.9374 val_auc=0.8080
model=graphsage top_k=200 fold=4 epoch=41 loss=6.9792 val_auc=0.8082
model=graphsage top_k=200 fold=4 epoch=42 loss=8.6768 val_auc=0.8085
model=graphsage top_k=200 fold=4 epoch=43 loss=6.4125 val_auc=0.8071
model=graphsage top_k=200 fold=4 epoch=44 loss=8.7299 val_auc=0.8048
model=graphsage top_k=200 fold=4 epoch=45 loss=8.2755 val_auc=0.8097
model=graphsage top_k=200 fold=4 epoch=46 loss=6.3862 val_auc=0.8105
model=graphsage top_k=200 fold=4 epoch=47 loss=5.8922 val_auc=0.8115
model=graphsage top_k=200 fold=4 epoch=48 loss=9.3306 val_auc=0.8121
model=graphsage top_k=200 fold=4 epoch=49 loss=6.9213 val_auc=0.8127
model=graphsage top_k=200 fold=4 epoch=50 loss=6.2743 val_auc=0.8128
model=graphsage top_k=200 fold=4 epoch=51 loss=7.5839 val_auc=0.8140
model=graphsage top_k=200 fold=4 epoch=52 loss=7.5794 val_auc=0.8146
model=graphsage top_k=200 fold=4 epoch=53 loss=5.9350 val_auc=0.8147
model=graphsage top_k=200 fold=4 epoch=54 loss=6.6456 val_auc=0.8147
model=graphsage top_k=200 fold=4 epoch=55 loss=8.2753 val_auc=0.8146
model=graphsage top_k=200 fold=4 epoch=56 loss=7.9165 val_auc=0.8144
model=graphsage top_k=200 fold=4 epoch=57 loss=5.7512 val_auc=0.8075
model=graphsage top_k=200 fold=4 epoch=58 loss=7.8979 val_auc=0.7805
model=graphsage top_k=200 fold=4 epoch=59 loss=12.3461 val_auc=0.7878
model=graphsage top_k=200 fold=4 epoch=60 loss=11.9833 val_auc=0.8101
model=graphsage top_k=200 fold=4 epoch=61 loss=6.7183 val_auc=0.8133
model=graphsage top_k=200 fold=4 epoch=62 loss=4.9321 val_auc=0.8133
model=graphsage top_k=200 fold=4 epoch=63 loss=5.6596 val_auc=0.8137
model=graphsage top_k=200 fold=4 epoch=64 loss=5.2749 val_auc=0.8146
model=graphsage top_k=200 fold=4 epoch=65 loss=5.1580 val_auc=0.8147
model=graphsage top_k=200 fold=4 epoch=66 loss=6.7407 val_auc=0.8129
model=graphsage top_k=200 fold=4 epoch=67 loss=8.2017 val_auc=0.8165
model=graphsage top_k=200 fold=4 epoch=68 loss=7.8296 val_auc=0.8175
model=graphsage top_k=200 fold=4 epoch=69 loss=4.4916 val_auc=0.8178
model=graphsage top_k=200 fold=4 epoch=70 loss=7.2101 val_auc=0.8178
model=graphsage top_k=200 fold=4 epoch=71 loss=7.8545 val_auc=0.8178
model=graphsage top_k=200 fold=4 epoch=72 loss=7.4596 val_auc=0.8179
model=graphsage top_k=200 fold=4 epoch=73 loss=5.0344 val_auc=0.8183
model=graphsage top_k=200 fold=4 epoch=74 loss=4.2091 val_auc=0.8182
model=graphsage top_k=200 fold=4 epoch=75 loss=6.2574 val_auc=0.8183
model=graphsage top_k=200 fold=4 epoch=76 loss=7.2643 val_auc=0.8189
model=graphsage top_k=200 fold=4 epoch=77 loss=5.6831 val_auc=0.8188
model=graphsage top_k=200 fold=4 epoch=78 loss=4.2985 val_auc=0.8187
model=graphsage top_k=200 fold=4 epoch=79 loss=4.7417 val_auc=0.8192
model=graphsage top_k=200 fold=4 epoch=80 loss=4.2411 val_auc=0.8200
model=graphsage top_k=200 fold=4 epoch=81 loss=4.4882 val_auc=0.8205
model=graphsage top_k=200 fold=4 epoch=82 loss=4.0574 val_auc=0.8211
model=graphsage top_k=200 fold=4 epoch=83 loss=4.3170 val_auc=0.8218
model=graphsage top_k=200 fold=4 epoch=84 loss=5.3925 val_auc=0.8224
model=graphsage top_k=200 fold=4 epoch=85 loss=4.3117 val_auc=0.8229
model=graphsage top_k=200 fold=4 epoch=86 loss=4.5516 val_auc=0.8231
model=graphsage top_k=200 fold=4 epoch=87 loss=4.4465 val_auc=0.8231
model=graphsage top_k=200 fold=4 epoch=88 loss=5.0877 val_auc=0.8230
model=graphsage top_k=200 fold=4 epoch=89 loss=5.7661 val_auc=0.8228
model=graphsage top_k=200 fold=4 epoch=90 loss=4.9163 val_auc=0.8228
model=graphsage top_k=200 fold=4 epoch=91 loss=4.3737 val_auc=0.8231
model=graphsage top_k=200 fold=4 epoch=92 loss=4.4497 val_auc=0.8234
model=graphsage top_k=200 fold=4 epoch=93 loss=4.2723 val_auc=0.8237
model=graphsage top_k=200 fold=4 epoch=94 loss=3.5149 val_auc=0.8247
model=graphsage top_k=200 fold=4 epoch=95 loss=4.2422 val_auc=0.8258
model=graphsage top_k=200 fold=4 epoch=96 loss=3.8091 val_auc=0.8270
model=graphsage top_k=200 fold=4 epoch=97 loss=3.9651 val_auc=0.8278
model=graphsage top_k=200 fold=4 epoch=98 loss=2.8958 val_auc=0.8285
model=graphsage top_k=200 fold=4 epoch=99 loss=4.4495 val_auc=0.8285

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=200 fold=5 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=200 fold=5 epoch=0 loss=30.4912 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=200 fold=5 epoch=1 loss=231.0180 val_auc=0.6503
model=graphsage top_k=200 fold=5 epoch=2 loss=55.1347 val_auc=0.5000
model=graphsage top_k=200 fold=5 epoch=3 loss=120.5585 val_auc=0.5000
model=graphsage top_k=200 fold=5 epoch=4 loss=104.0007 val_auc=0.5340
model=graphsage top_k=200 fold=5 epoch=5 loss=40.6487 val_auc=0.7360

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=200 fold=5 epoch=6 loss=43.3069 val_auc=0.7545
model=graphsage top_k=200 fold=5 epoch=7 loss=58.1465 val_auc=0.7592
model=graphsage top_k=200 fold=5 epoch=8 loss=41.4997 val_auc=0.7607
model=graphsage top_k=200 fold=5 epoch=9 loss=12.3596 val_auc=0.5000
model=graphsage top_k=200 fold=5 epoch=10 loss=37.1041 val_auc=0.5000
model=graphsage top_k=200 fold=5 epoch=11 loss=45.3346 val_auc=0.5362
model=graphsage top_k=200 fold=5 epoch=12 loss=37.6763 val_auc=0.7695
model=graphsage top_k=200 fold=5 epoch=13 loss=14.6359 val_auc=0.7756
model=graphsage top_k=200 fold=5 epoch=14 loss=15.9691 val_auc=0.7765
model=graphsage top_k=200 fold=5 epoch=15 loss=27.6178 val_auc=0.7775
model=graphsage top_k=200 fold=5 epoch=16 loss=23.2497 val_auc=0.7784
model=graphsage top_k=200 fold=5 epoch=17 loss=16.7309 val_auc=0.7742
model=graphsage top_k=200 fold=5 epoch=18 loss=12.7725 val_auc=0.7754
model=graphsage top_k=200 fold=5 epoch=19 loss=16.6200 val_auc=0.7750
model=graphsage top_k=200 fold=5 epoch=20 loss=14.7690 val_auc=0.7782
model=graphsage top_k=200 fold=5 epoch=21 loss=11.1030 val_auc=0.7799
model=graphsage top_k=200 fold=5 epoch=22 loss=16.1221 val_auc=0.7805
model=graphsage top_k=200 fold=5 epoch=23 loss=16.0763 val_auc=0.7810
model=graphsage top_k=200 fold=5 epoch=24 loss=14.7552 val_auc=0.7815
model=graphsage top_k=200 fold=5 epoch=25 loss=10.6271 val_auc=0.7780
model=graphsage top_k=200 fold=5 epoch=26 loss=11.6214 val_auc=0.7426
model=graphsage top_k=200 fold=5 epoch=27 loss=18.6748 val_auc=0.7697
model=graphsage top_k=200 fold=5 epoch=28 loss=14.0277 val_auc=0.7805
model=graphsage top_k=200 fold=5 epoch=29 loss=10.2143 val_auc=0.7856
model=graphsage top_k=200 fold=5 epoch=30 loss=9.1597 val_auc=0.7874
model=graphsage top_k=200 fold=5 epoch=31 loss=12.8332 val_auc=0.7903
model=graphsage top_k=200 fold=5 epoch=32 loss=13.1049 val_auc=0.7920
model=graphsage top_k=200 fold=5 epoch=33 loss=9.5615 val_auc=0.7929
model=graphsage top_k=200 fold=5 epoch=34 loss=11.2159 val_auc=0.7915
model=graphsage top_k=200 fold=5 epoch=35 loss=12.4050 val_auc=0.7939
model=graphsage top_k=200 fold=5 epoch=36 loss=10.5549 val_auc=0.7978
model=graphsage top_k=200 fold=5 epoch=37 loss=8.3968 val_auc=0.7991
model=graphsage top_k=200 fold=5 epoch=38 loss=11.1323 val_auc=0.7995
model=graphsage top_k=200 fold=5 epoch=39 loss=12.5721 val_auc=0.7998
model=graphsage top_k=200 fold=5 epoch=40 loss=10.3808 val_auc=0.8003
model=graphsage top_k=200 fold=5 epoch=41 loss=8.6515 val_auc=0.7999
model=graphsage top_k=200 fold=5 epoch=42 loss=7.3157 val_auc=0.7940
model=graphsage top_k=200 fold=5 epoch=43 loss=8.2099 val_auc=0.7976
model=graphsage top_k=200 fold=5 epoch=44 loss=9.8066 val_auc=0.8018
model=graphsage top_k=200 fold=5 epoch=45 loss=7.4204 val_auc=0.8022
model=graphsage top_k=200 fold=5 epoch=46 loss=7.7274 val_auc=0.8024
model=graphsage top_k=200 fold=5 epoch=47 loss=11.2546 val_auc=0.8024
model=graphsage top_k=200 fold=5 epoch=48 loss=9.6829 val_auc=0.8019
model=graphsage top_k=200 fold=5 epoch=49 loss=8.2527 val_auc=0.8015
model=graphsage top_k=200 fold=5 epoch=50 loss=8.1454 val_auc=0.8006
model=graphsage top_k=200 fold=5 epoch=51 loss=7.3995 val_auc=0.8015
model=graphsage top_k=200 fold=5 epoch=52 loss=7.4655 val_auc=0.8030
model=graphsage top_k=200 fold=5 epoch=53 loss=6.4712 val_auc=0.8038
model=graphsage top_k=200 fold=5 epoch=54 loss=8.1155 val_auc=0.8045
model=graphsage top_k=200 fold=5 epoch=55 loss=7.8477 val_auc=0.8049
model=graphsage top_k=200 fold=5 epoch=56 loss=7.0712 val_auc=0.8052
model=graphsage top_k=200 fold=5 epoch=57 loss=5.8049 val_auc=0.8051
model=graphsage top_k=200 fold=5 epoch=58 loss=7.3739 val_auc=0.8058
model=graphsage top_k=200 fold=5 epoch=59 loss=9.1404 val_auc=0.8081
model=graphsage top_k=200 fold=5 epoch=60 loss=7.5540 val_auc=0.8094
model=graphsage top_k=200 fold=5 epoch=61 loss=5.3995 val_auc=0.8106
model=graphsage top_k=200 fold=5 epoch=62 loss=6.3085 val_auc=0.8117
model=graphsage top_k=200 fold=5 epoch=63 loss=6.8336 val_auc=0.8131
model=graphsage top_k=200 fold=5 epoch=64 loss=6.0652 val_auc=0.8132
model=graphsage top_k=200 fold=5 epoch=65 loss=4.8422 val_auc=0.8140
model=graphsage top_k=200 fold=5 epoch=66 loss=5.0933 val_auc=0.8145
model=graphsage top_k=200 fold=5 epoch=67 loss=5.8626 val_auc=0.8151
model=graphsage top_k=200 fold=5 epoch=68 loss=5.1236 val_auc=0.8155
model=graphsage top_k=200 fold=5 epoch=69 loss=6.4474 val_auc=0.8159
model=graphsage top_k=200 fold=5 epoch=70 loss=5.5182 val_auc=0.8162
model=graphsage top_k=200 fold=5 epoch=71 loss=5.6681 val_auc=0.8166
model=graphsage top_k=200 fold=5 epoch=72 loss=6.2951 val_auc=0.8166
model=graphsage top_k=200 fold=5 epoch=73 loss=8.6058 val_auc=0.8163
model=graphsage top_k=200 fold=5 epoch=74 loss=6.8343 val_auc=0.8158
model=graphsage top_k=200 fold=5 epoch=75 loss=5.8351 val_auc=0.8150
model=graphsage top_k=200 fold=5 epoch=76 loss=5.1200 val_auc=0.8127
model=graphsage top_k=200 fold=5 epoch=77 loss=6.9209 val_auc=0.8140
model=graphsage top_k=200 fold=5 epoch=78 loss=6.8925 val_auc=0.8162
model=graphsage top_k=200 fold=5 epoch=79 loss=5.2751 val_auc=0.8170
model=graphsage top_k=200 fold=5 epoch=80 loss=5.5112 val_auc=0.8179
model=graphsage top_k=200 fold=5 epoch=81 loss=6.4518 val_auc=0.8185
model=graphsage top_k=200 fold=5 epoch=82 loss=6.7557 val_auc=0.8190
model=graphsage top_k=200 fold=5 epoch=83 loss=5.4882 val_auc=0.8195
model=graphsage top_k=200 fold=5 epoch=84 loss=4.7450 val_auc=0.8198
model=graphsage top_k=200 fold=5 epoch=85 loss=6.4512 val_auc=0.8204
model=graphsage top_k=200 fold=5 epoch=86 loss=6.8947 val_auc=0.8210
model=graphsage top_k=200 fold=5 epoch=87 loss=4.3567 val_auc=0.8218
model=graphsage top_k=200 fold=5 epoch=88 loss=5.6412 val_auc=0.8225
model=graphsage top_k=200 fold=5 epoch=89 loss=5.1473 val_auc=0.8232
model=graphsage top_k=200 fold=5 epoch=90 loss=4.9798 val_auc=0.8238
model=graphsage top_k=200 fold=5 epoch=91 loss=4.0060 val_auc=0.8242
model=graphsage top_k=200 fold=5 epoch=92 loss=6.1846 val_auc=0.8228
model=graphsage top_k=200 fold=5 epoch=93 loss=4.8867 val_auc=0.8243
model=graphsage top_k=200 fold=5 epoch=94 loss=7.1071 val_auc=0.8253
model=graphsage top_k=200 fold=5 epoch=95 loss=5.6729 val_auc=0.8252
model=graphsage top_k=200 fold=5 epoch=96 loss=3.6535 val_auc=0.8248
model=graphsage top_k=200 fold=5 epoch=97 loss=5.5473 val_auc=0.8245
model=graphsage top_k=200 fold=5 epoch=98 loss=5.2930 val_auc=0.8244
model=graphsage top_k=200 fold=5 epoch=99 loss=4.7308 val_auc=0.8242

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=200 fold=6 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=200 fold=6 epoch=0 loss=59.5694 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=200 fold=6 epoch=1 loss=221.6830 val_auc=0.5874
model=graphsage top_k=200 fold=6 epoch=2 loss=77.1559 val_auc=0.5166
model=graphsage top_k=200 fold=6 epoch=3 loss=77.2829 val_auc=0.5179
model=graphsage top_k=200 fold=6 epoch=4 loss=67.6013 val_auc=0.6083
model=graphsage top_k=200 fold=6 epoch=5 loss=17.2870 val_auc=0.6967

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=200 fold=6 epoch=6 loss=57.6791 val_auc=0.7330
model=graphsage top_k=200 fold=6 epoch=7 loss=63.5554 val_auc=0.7477
model=graphsage top_k=200 fold=6 epoch=8 loss=46.9081 val_auc=0.7548
model=graphsage top_k=200 fold=6 epoch=9 loss=16.3987 val_auc=0.5000
model=graphsage top_k=200 fold=6 epoch=10 loss=33.8440 val_auc=0.5000
model=graphsage top_k=200 fold=6 epoch=11 loss=47.9722 val_auc=0.5000
model=graphsage top_k=200 fold=6 epoch=12 loss=49.4699 val_auc=0.5001
model=graphsage top_k=200 fold=6 epoch=13 loss=26.3015 val_auc=0.7757
model=graphsage top_k=200 fold=6 epoch=14 loss=11.2039 val_auc=0.7820
model=graphsage top_k=200 fold=6 epoch=15 loss=14.3045 val_auc=0.7846
model=graphsage top_k=200 fold=6 epoch=16 loss=12.7448 val_auc=0.7858
model=graphsage top_k=200 fold=6 epoch=17 loss=10.1944 val_auc=0.7823
model=graphsage top_k=200 fold=6 epoch=18 loss=13.0327 val_auc=0.7786
model=graphsage top_k=200 fold=6 epoch=19 loss=14.4002 val_auc=0.7857
model=graphsage top_k=200 fold=6 epoch=20 loss=15.2908 val_auc=0.7903
model=graphsage top_k=200 fold=6 epoch=21 loss=9.5148 val_auc=0.7910
model=graphsage top_k=200 fold=6 epoch=22 loss=9.3506 val_auc=0.7912
model=graphsage top_k=200 fold=6 epoch=23 loss=8.5091 val_auc=0.7922
model=graphsage top_k=200 fold=6 epoch=24 loss=9.8874 val_auc=0.7945
model=graphsage top_k=200 fold=6 epoch=25 loss=8.8745 val_auc=0.7987
model=graphsage top_k=200 fold=6 epoch=26 loss=10.1793 val_auc=0.8016
model=graphsage top_k=200 fold=6 epoch=27 loss=10.3839 val_auc=0.8033
model=graphsage top_k=200 fold=6 epoch=28 loss=9.0024 val_auc=0.8033
model=graphsage top_k=200 fold=6 epoch=29 loss=8.1805 val_auc=0.8046
model=graphsage top_k=200 fold=6 epoch=30 loss=10.3483 val_auc=0.8036
model=graphsage top_k=200 fold=6 epoch=31 loss=10.0401 val_auc=0.8049
model=graphsage top_k=200 fold=6 epoch=32 loss=9.4866 val_auc=0.8064
model=graphsage top_k=200 fold=6 epoch=33 loss=7.6251 val_auc=0.8076
model=graphsage top_k=200 fold=6 epoch=34 loss=8.6753 val_auc=0.8086
model=graphsage top_k=200 fold=6 epoch=35 loss=10.6173 val_auc=0.8093
model=graphsage top_k=200 fold=6 epoch=36 loss=7.0110 val_auc=0.8096
model=graphsage top_k=200 fold=6 epoch=37 loss=9.7250 val_auc=0.8111
model=graphsage top_k=200 fold=6 epoch=38 loss=7.6394 val_auc=0.8121
model=graphsage top_k=200 fold=6 epoch=39 loss=6.5053 val_auc=0.8130
model=graphsage top_k=200 fold=6 epoch=40 loss=6.1490 val_auc=0.8140
model=graphsage top_k=200 fold=6 epoch=41 loss=7.4556 val_auc=0.8151
model=graphsage top_k=200 fold=6 epoch=42 loss=7.2897 val_auc=0.8162
model=graphsage top_k=200 fold=6 epoch=43 loss=8.2411 val_auc=0.8172
model=graphsage top_k=200 fold=6 epoch=44 loss=6.5152 val_auc=0.8183
model=graphsage top_k=200 fold=6 epoch=45 loss=6.3372 val_auc=0.8193
model=graphsage top_k=200 fold=6 epoch=46 loss=5.6599 val_auc=0.8207
model=graphsage top_k=200 fold=6 epoch=47 loss=6.0233 val_auc=0.8221
model=graphsage top_k=200 fold=6 epoch=48 loss=6.0615 val_auc=0.8232
model=graphsage top_k=200 fold=6 epoch=49 loss=5.9813 val_auc=0.8245
model=graphsage top_k=200 fold=6 epoch=50 loss=5.9561 val_auc=0.8253
model=graphsage top_k=200 fold=6 epoch=51 loss=6.5902 val_auc=0.8260
model=graphsage top_k=200 fold=6 epoch=52 loss=4.5010 val_auc=0.8266
model=graphsage top_k=200 fold=6 epoch=53 loss=6.3673 val_auc=0.8270
model=graphsage top_k=200 fold=6 epoch=54 loss=6.4625 val_auc=0.8273
model=graphsage top_k=200 fold=6 epoch=55 loss=4.7727 val_auc=0.8273
model=graphsage top_k=200 fold=6 epoch=56 loss=6.0479 val_auc=0.8267
model=graphsage top_k=200 fold=6 epoch=57 loss=5.0700 val_auc=0.8259
model=graphsage top_k=200 fold=6 epoch=58 loss=5.9140 val_auc=0.8256
model=graphsage top_k=200 fold=6 epoch=59 loss=6.1103 val_auc=0.8261
model=graphsage top_k=200 fold=6 epoch=60 loss=5.4845 val_auc=0.8264
model=graphsage top_k=200 fold=6 epoch=61 loss=4.6370 val_auc=0.8272
model=graphsage top_k=200 fold=6 epoch=62 loss=4.9502 val_auc=0.8277
model=graphsage top_k=200 fold=6 epoch=63 loss=5.1735 val_auc=0.8285
model=graphsage top_k=200 fold=6 epoch=64 loss=4.2879 val_auc=0.8295
model=graphsage top_k=200 fold=6 epoch=65 loss=4.6193 val_auc=0.8299
model=graphsage top_k=200 fold=6 epoch=66 loss=5.1161 val_auc=0.8304
model=graphsage top_k=200 fold=6 epoch=67 loss=5.0552 val_auc=0.8309
model=graphsage top_k=200 fold=6 epoch=68 loss=4.4110 val_auc=0.8314
model=graphsage top_k=200 fold=6 epoch=69 loss=5.3858 val_auc=0.8315
model=graphsage top_k=200 fold=6 epoch=70 loss=4.8766 val_auc=0.8313
model=graphsage top_k=200 fold=6 epoch=71 loss=5.8905 val_auc=0.8312
model=graphsage top_k=200 fold=6 epoch=72 loss=5.4194 val_auc=0.8307
model=graphsage top_k=200 fold=6 epoch=73 loss=5.7234 val_auc=0.8310
model=graphsage top_k=200 fold=6 epoch=74 loss=4.8077 val_auc=0.8311
model=graphsage top_k=200 fold=6 epoch=75 loss=4.8892 val_auc=0.8307
model=graphsage top_k=200 fold=6 epoch=76 loss=3.7016 val_auc=0.8308
model=graphsage top_k=200 fold=6 epoch=77 loss=4.7866 val_auc=0.8315
model=graphsage top_k=200 fold=6 epoch=78 loss=3.8923 val_auc=0.8327
model=graphsage top_k=200 fold=6 epoch=79 loss=3.6276 val_auc=0.8337
model=graphsage top_k=200 fold=6 epoch=80 loss=4.8693 val_auc=0.8343
model=graphsage top_k=200 fold=6 epoch=81 loss=4.1398 val_auc=0.8349
model=graphsage top_k=200 fold=6 epoch=82 loss=3.6177 val_auc=0.8352
model=graphsage top_k=200 fold=6 epoch=83 loss=3.6863 val_auc=0.8362
model=graphsage top_k=200 fold=6 epoch=84 loss=3.7410 val_auc=0.8368
model=graphsage top_k=200 fold=6 epoch=85 loss=3.6243 val_auc=0.8372
model=graphsage top_k=200 fold=6 epoch=86 loss=4.8877 val_auc=0.8373
model=graphsage top_k=200 fold=6 epoch=87 loss=4.6090 val_auc=0.8365
model=graphsage top_k=200 fold=6 epoch=88 loss=4.2778 val_auc=0.8349
model=graphsage top_k=200 fold=6 epoch=89 loss=4.1916 val_auc=0.8341
model=graphsage top_k=200 fold=6 epoch=90 loss=5.6417 val_auc=0.8337
model=graphsage top_k=200 fold=6 epoch=91 loss=4.2731 val_auc=0.8338
model=graphsage top_k=200 fold=6 epoch=92 loss=3.4737 val_auc=0.8348
model=graphsage top_k=200 fold=6 epoch=93 loss=6.1086 val_auc=0.8332
model=graphsage top_k=200 fold=6 epoch=94 loss=9.1672 val_auc=0.8341
model=graphsage top_k=200 fold=6 epoch=95 loss=6.4883 val_auc=0.8352
model=graphsage top_k=200 fold=6 epoch=96 loss=5.1880 val_auc=0.8349
model=graphsage top_k=200 fold=6 epoch=97 loss=4.0167 val_auc=0.8347
model=graphsage top_k=200 fold=6 epoch=98 loss=4.9309 val_auc=0.8347
graphsage top_k=200 fold=6: early stopping at epoch 98

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=200 fold=7 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=200 fold=7 epoch=0 loss=31.3346 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=200 fold=7 epoch=1 loss=227.1421 val_auc=0.5350
model=graphsage top_k=200 fold=7 epoch=2 loss=53.7746 val_auc=0.5000
model=graphsage top_k=200 fold=7 epoch=3 loss=124.2076 val_auc=0.5000
model=graphsage top_k=200 fold=7 epoch=4 loss=120.2998 val_auc=0.5152
model=graphsage top_k=200 fold=7 epoch=5 loss=40.6460 val_auc=0.5729
model=graphsage top_k=200 fold=7 epoch=6 loss=31.0672 val_auc=0.5673
model=graphsage top_k=200 fold=7 epoch=7 loss=34.6127 val_auc=0.5884
model=graphsage top_k=200 fold=7 epoch=8 loss=15.5915 val_auc=0.5138
model=graphsage top_k=200 fold=7 epoch=9 loss=16.3179 val_auc=0.5042
model=graphsage top_k=200 fold=7 epoch=10 loss=24.9681 val_auc=0.6116
model=graphsage top_k=200 fold=7 epoch=11 loss=17.8744 val_auc=0.7499
model=graphsage top_k=200 fold=7 epoch=12 loss=12.6830 val_auc=0.7632
model=graphsage top_k=200 fold=7 epoch=13 loss=14.2171 val_auc=0.7693
model=graphsage top_k=200 fold=7 epoch=14 loss=13.7798 val_auc=0.7671
model=graphsage top_k=200 fold=7 epoch=15 loss=12.4980 val_auc=0.7460
model=graphsage top_k=200 fold=7 epoch=16 loss=16.4738 val_auc=0.7720
model=graphsage top_k=200 fold=7 epoch=17 loss=13.0234 val_auc=0.7778
model=graphsage top_k=200 fold=7 epoch=18 loss=14.6333 val_auc=0.7782
model=graphsage top_k=200 fold=7 epoch=19 loss=13.4113 val_auc=0.7781
model=graphsage top_k=200 fold=7 epoch=20 loss=13.3809 val_auc=0.7735
model=graphsage top_k=200 fold=7 epoch=21 loss=10.2826 val_auc=0.7742
model=graphsage top_k=200 fold=7 epoch=22 loss=13.3320 val_auc=0.7780
model=graphsage top_k=200 fold=7 epoch=23 loss=11.8118 val_auc=0.7801
model=graphsage top_k=200 fold=7 epoch=24 loss=11.0702 val_auc=0.7811
model=graphsage top_k=200 fold=7 epoch=25 loss=12.8363 val_auc=0.7820
model=graphsage top_k=200 fold=7 epoch=26 loss=12.5993 val_auc=0.7818
model=graphsage top_k=200 fold=7 epoch=27 loss=9.9132 val_auc=0.7820
model=graphsage top_k=200 fold=7 epoch=28 loss=11.2254 val_auc=0.7845
model=graphsage top_k=200 fold=7 epoch=29 loss=8.0319 val_auc=0.7867
model=graphsage top_k=200 fold=7 epoch=30 loss=11.6767 val_auc=0.7882
model=graphsage top_k=200 fold=7 epoch=31 loss=11.7731 val_auc=0.7892
model=graphsage top_k=200 fold=7 epoch=32 loss=10.2374 val_auc=0.7854
model=graphsage top_k=200 fold=7 epoch=33 loss=10.2364 val_auc=0.7812
model=graphsage top_k=200 fold=7 epoch=34 loss=11.7580 val_auc=0.7899
model=graphsage top_k=200 fold=7 epoch=35 loss=9.9886 val_auc=0.7937
model=graphsage top_k=200 fold=7 epoch=36 loss=11.3450 val_auc=0.7945
model=graphsage top_k=200 fold=7 epoch=37 loss=13.9567 val_auc=0.7949
model=graphsage top_k=200 fold=7 epoch=38 loss=9.0462 val_auc=0.7928
model=graphsage top_k=200 fold=7 epoch=39 loss=7.7705 val_auc=0.7899
model=graphsage top_k=200 fold=7 epoch=40 loss=10.7948 val_auc=0.7958
model=graphsage top_k=200 fold=7 epoch=41 loss=9.3681 val_auc=0.7984
model=graphsage top_k=200 fold=7 epoch=42 loss=7.6686 val_auc=0.7994
model=graphsage top_k=200 fold=7 epoch=43 loss=8.4116 val_auc=0.8005
model=graphsage top_k=200 fold=7 epoch=44 loss=8.6882 val_auc=0.8018
model=graphsage top_k=200 fold=7 epoch=45 loss=8.0054 val_auc=0.8022
model=graphsage top_k=200 fold=7 epoch=46 loss=12.1186 val_auc=0.8025
model=graphsage top_k=200 fold=7 epoch=47 loss=9.1472 val_auc=0.8046
model=graphsage top_k=200 fold=7 epoch=48 loss=6.3777 val_auc=0.8054
model=graphsage top_k=200 fold=7 epoch=49 loss=9.8715 val_auc=0.8058
model=graphsage top_k=200 fold=7 epoch=50 loss=10.2234 val_auc=0.8063
model=graphsage top_k=200 fold=7 epoch=51 loss=9.3259 val_auc=0.8066
model=graphsage top_k=200 fold=7 epoch=52 loss=6.4140 val_auc=0.8039
model=graphsage top_k=200 fold=7 epoch=53 loss=9.1571 val_auc=0.7919
model=graphsage top_k=200 fold=7 epoch=54 loss=9.1904 val_auc=0.8017
model=graphsage top_k=200 fold=7 epoch=55 loss=10.5320 val_auc=0.8075
model=graphsage top_k=200 fold=7 epoch=56 loss=7.5792 val_auc=0.8073
model=graphsage top_k=200 fold=7 epoch=57 loss=8.4709 val_auc=0.8069
model=graphsage top_k=200 fold=7 epoch=58 loss=10.8566 val_auc=0.8068
model=graphsage top_k=200 fold=7 epoch=59 loss=15.1212 val_auc=0.8068
model=graphsage top_k=200 fold=7 epoch=60 loss=7.5214 val_auc=0.8070
model=graphsage top_k=200 fold=7 epoch=61 loss=5.8788 val_auc=0.8047
model=graphsage top_k=200 fold=7 epoch=62 loss=8.8358 val_auc=0.8042
model=graphsage top_k=200 fold=7 epoch=63 loss=8.7238 val_auc=0.8081
model=graphsage top_k=200 fold=7 epoch=64 loss=6.4610 val_auc=0.8090
model=graphsage top_k=200 fold=7 epoch=65 loss=6.7470 val_auc=0.8096
model=graphsage top_k=200 fold=7 epoch=66 loss=6.8166 val_auc=0.8103
model=graphsage top_k=200 fold=7 epoch=67 loss=6.6694 val_auc=0.8114
model=graphsage top_k=200 fold=7 epoch=68 loss=5.9376 val_auc=0.8125
model=graphsage top_k=200 fold=7 epoch=69 loss=5.0435 val_auc=0.8138
model=graphsage top_k=200 fold=7 epoch=70 loss=5.6812 val_auc=0.8149
model=graphsage top_k=200 fold=7 epoch=71 loss=6.4841 val_auc=0.8158
model=graphsage top_k=200 fold=7 epoch=72 loss=5.1801 val_auc=0.8165
model=graphsage top_k=200 fold=7 epoch=73 loss=5.5103 val_auc=0.8171
model=graphsage top_k=200 fold=7 epoch=74 loss=6.5333 val_auc=0.8172
model=graphsage top_k=200 fold=7 epoch=75 loss=7.7066 val_auc=0.8174
model=graphsage top_k=200 fold=7 epoch=76 loss=5.3658 val_auc=0.8175
model=graphsage top_k=200 fold=7 epoch=77 loss=4.9622 val_auc=0.8177
model=graphsage top_k=200 fold=7 epoch=78 loss=4.6274 val_auc=0.8180
model=graphsage top_k=200 fold=7 epoch=79 loss=5.2024 val_auc=0.8183
model=graphsage top_k=200 fold=7 epoch=80 loss=4.5712 val_auc=0.8185
model=graphsage top_k=200 fold=7 epoch=81 loss=4.9687 val_auc=0.8185
model=graphsage top_k=200 fold=7 epoch=82 loss=5.0055 val_auc=0.8182
model=graphsage top_k=200 fold=7 epoch=83 loss=5.1590 val_auc=0.8180
model=graphsage top_k=200 fold=7 epoch=84 loss=4.7129 val_auc=0.8182
model=graphsage top_k=200 fold=7 epoch=85 loss=3.9211 val_auc=0.8186
model=graphsage top_k=200 fold=7 epoch=86 loss=6.3755 val_auc=0.8188
model=graphsage top_k=200 fold=7 epoch=87 loss=5.2811 val_auc=0.8190
model=graphsage top_k=200 fold=7 epoch=88 loss=4.7648 val_auc=0.8190
model=graphsage top_k=200 fold=7 epoch=89 loss=4.5372 val_auc=0.8190
model=graphsage top_k=200 fold=7 epoch=90 loss=4.3089 val_auc=0.8194
model=graphsage top_k=200 fold=7 epoch=91 loss=4.7231 val_auc=0.8198
model=graphsage top_k=200 fold=7 epoch=92 loss=4.6621 val_auc=0.8203
model=graphsage top_k=200 fold=7 epoch=93 loss=4.3139 val_auc=0.8209
model=graphsage top_k=200 fold=7 epoch=94 loss=4.3502 val_auc=0.8214
model=graphsage top_k=200 fold=7 epoch=95 loss=3.6716 val_auc=0.8222
model=graphsage top_k=200 fold=7 epoch=96 loss=4.1915 val_auc=0.8227
model=graphsage top_k=200 fold=7 epoch=97 loss=3.8868 val_auc=0.8231
model=graphsage top_k=200 fold=7 epoch=98 loss=5.3538 val_auc=0.8232
model=graphsage top_k=200 fold=7 epoch=99 loss=5.5442 val_auc=0.8233

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=200 fold=8 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=200 fold=8 epoch=0 loss=22.1786 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=200 fold=8 epoch=1 loss=171.8428 val_auc=0.5237

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=200 fold=8 epoch=2 loss=50.3061 val_auc=0.7427
model=graphsage top_k=200 fold=8 epoch=3 loss=30.6002 val_auc=0.5526
model=graphsage top_k=200 fold=8 epoch=4 loss=29.8775 val_auc=0.7602
model=graphsage top_k=200 fold=8 epoch=5 loss=12.6022 val_auc=0.7137
model=graphsage top_k=200 fold=8 epoch=6 loss=22.2596 val_auc=0.7699
model=graphsage top_k=200 fold=8 epoch=7 loss=22.6951 val_auc=0.7674
model=graphsage top_k=200 fold=8 epoch=8 loss=11.7353 val_auc=0.7755
model=graphsage top_k=200 fold=8 epoch=9 loss=13.4304 val_auc=0.7786
model=graphsage top_k=200 fold=8 epoch=10 loss=10.7603 val_auc=0.7807
model=graphsage top_k=200 fold=8 epoch=11 loss=12.1963 val_auc=0.7823
model=graphsage top_k=200 fold=8 epoch=12 loss=17.1902 val_auc=0.7822
model=graphsage top_k=200 fold=8 epoch=13 loss=14.5144 val_auc=0.6874
model=graphsage top_k=200 fold=8 epoch=14 loss=17.2814 val_auc=0.6556
model=graphsage top_k=200 fold=8 epoch=15 loss=17.1456 val_auc=0.7752
model=graphsage top_k=200 fold=8 epoch=16 loss=10.6354 val_auc=0.7832
model=graphsage top_k=200 fold=8 epoch=17 loss=16.1271 val_auc=0.7837
model=graphsage top_k=200 fold=8 epoch=18 loss=19.3200 val_auc=0.7842
model=graphsage top_k=200 fold=8 epoch=19 loss=13.1151 val_auc=0.7662
model=graphsage top_k=200 fold=8 epoch=20 loss=11.5544 val_auc=0.7314
model=graphsage top_k=200 fold=8 epoch=21 loss=11.8567 val_auc=0.7754
model=graphsage top_k=200 fold=8 epoch=22 loss=8.9420 val_auc=0.7848
model=graphsage top_k=200 fold=8 epoch=23 loss=11.2535 val_auc=0.7855
model=graphsage top_k=200 fold=8 epoch=24 loss=14.5898 val_auc=0.7858
model=graphsage top_k=200 fold=8 epoch=25 loss=10.5904 val_auc=0.7794
model=graphsage top_k=200 fold=8 epoch=26 loss=11.7636 val_auc=0.7710
model=graphsage top_k=200 fold=8 epoch=27 loss=13.4312 val_auc=0.7853
model=graphsage top_k=200 fold=8 epoch=28 loss=8.2887 val_auc=0.7883
model=graphsage top_k=200 fold=8 epoch=29 loss=10.3041 val_auc=0.7891
model=graphsage top_k=200 fold=8 epoch=30 loss=9.3769 val_auc=0.7896
model=graphsage top_k=200 fold=8 epoch=31 loss=7.8125 val_auc=0.7884
model=graphsage top_k=200 fold=8 epoch=32 loss=9.6307 val_auc=0.7885
model=graphsage top_k=200 fold=8 epoch=33 loss=10.3521 val_auc=0.7921
model=graphsage top_k=200 fold=8 epoch=34 loss=8.4869 val_auc=0.7931
model=graphsage top_k=200 fold=8 epoch=35 loss=11.4354 val_auc=0.7936
model=graphsage top_k=200 fold=8 epoch=36 loss=14.2327 val_auc=0.7939
model=graphsage top_k=200 fold=8 epoch=37 loss=8.0848 val_auc=0.7921
model=graphsage top_k=200 fold=8 epoch=38 loss=8.1757 val_auc=0.7856
model=graphsage top_k=200 fold=8 epoch=39 loss=10.1976 val_auc=0.7933
model=graphsage top_k=200 fold=8 epoch=40 loss=6.6957 val_auc=0.7957
model=graphsage top_k=200 fold=8 epoch=41 loss=6.6426 val_auc=0.7965
model=graphsage top_k=200 fold=8 epoch=42 loss=8.0595 val_auc=0.7972
model=graphsage top_k=200 fold=8 epoch=43 loss=8.1802 val_auc=0.7931
model=graphsage top_k=200 fold=8 epoch=44 loss=9.6071 val_auc=0.7835
model=graphsage top_k=200 fold=8 epoch=45 loss=9.0473 val_auc=0.7959
model=graphsage top_k=200 fold=8 epoch=46 loss=6.7258 val_auc=0.7994
model=graphsage top_k=200 fold=8 epoch=47 loss=5.6659 val_auc=0.8010
model=graphsage top_k=200 fold=8 epoch=48 loss=10.5045 val_auc=0.8022
model=graphsage top_k=200 fold=8 epoch=49 loss=6.9176 val_auc=0.8036
model=graphsage top_k=200 fold=8 epoch=50 loss=6.8519 val_auc=0.8047
model=graphsage top_k=200 fold=8 epoch=51 loss=7.8965 val_auc=0.8055
model=graphsage top_k=200 fold=8 epoch=52 loss=7.5775 val_auc=0.8056
model=graphsage top_k=200 fold=8 epoch=53 loss=9.1403 val_auc=0.8051
model=graphsage top_k=200 fold=8 epoch=54 loss=9.8451 val_auc=0.8049
model=graphsage top_k=200 fold=8 epoch=55 loss=5.6113 val_auc=0.8046
model=graphsage top_k=200 fold=8 epoch=56 loss=8.4794 val_auc=0.8027
model=graphsage top_k=200 fold=8 epoch=57 loss=7.6543 val_auc=0.8044
model=graphsage top_k=200 fold=8 epoch=58 loss=5.5576 val_auc=0.8039
model=graphsage top_k=200 fold=8 epoch=59 loss=6.4600 val_auc=0.8039
model=graphsage top_k=200 fold=8 epoch=60 loss=7.2430 val_auc=0.8041
model=graphsage top_k=200 fold=8 epoch=61 loss=5.2603 val_auc=0.8050
model=graphsage top_k=200 fold=8 epoch=62 loss=7.4348 val_auc=0.8058
model=graphsage top_k=200 fold=8 epoch=63 loss=7.2737 val_auc=0.8063
model=graphsage top_k=200 fold=8 epoch=64 loss=5.3984 val_auc=0.8064
model=graphsage top_k=200 fold=8 epoch=65 loss=7.4566 val_auc=0.8066
model=graphsage top_k=200 fold=8 epoch=66 loss=9.4902 val_auc=0.8072
model=graphsage top_k=200 fold=8 epoch=67 loss=6.9155 val_auc=0.8081
model=graphsage top_k=200 fold=8 epoch=68 loss=5.5627 val_auc=0.8061
model=graphsage top_k=200 fold=8 epoch=69 loss=8.2807 val_auc=0.8022
model=graphsage top_k=200 fold=8 epoch=70 loss=9.5464 val_auc=0.8078
model=graphsage top_k=200 fold=8 epoch=71 loss=6.9097 val_auc=0.8081
model=graphsage top_k=200 fold=8 epoch=72 loss=6.2144 val_auc=0.8081
model=graphsage top_k=200 fold=8 epoch=73 loss=8.1156 val_auc=0.8083
model=graphsage top_k=200 fold=8 epoch=74 loss=6.4408 val_auc=0.8089
model=graphsage top_k=200 fold=8 epoch=75 loss=5.4704 val_auc=0.8101
model=graphsage top_k=200 fold=8 epoch=76 loss=5.2985 val_auc=0.8124
model=graphsage top_k=200 fold=8 epoch=77 loss=5.4524 val_auc=0.8144
model=graphsage top_k=200 fold=8 epoch=78 loss=5.0589 val_auc=0.8166
model=graphsage top_k=200 fold=8 epoch=79 loss=6.6583 val_auc=0.8180
model=graphsage top_k=200 fold=8 epoch=80 loss=4.7636 val_auc=0.8189
model=graphsage top_k=200 fold=8 epoch=81 loss=4.9005 val_auc=0.8192
model=graphsage top_k=200 fold=8 epoch=82 loss=4.6788 val_auc=0.8193
model=graphsage top_k=200 fold=8 epoch=83 loss=4.0661 val_auc=0.8192
model=graphsage top_k=200 fold=8 epoch=84 loss=5.4721 val_auc=0.8189
model=graphsage top_k=200 fold=8 epoch=85 loss=5.3803 val_auc=0.8186
model=graphsage top_k=200 fold=8 epoch=86 loss=4.0423 val_auc=0.8187
model=graphsage top_k=200 fold=8 epoch=87 loss=7.4354 val_auc=0.8192
model=graphsage top_k=200 fold=8 epoch=88 loss=6.9501 val_auc=0.8201
model=graphsage top_k=200 fold=8 epoch=89 loss=5.4150 val_auc=0.8184
model=graphsage top_k=200 fold=8 epoch=90 loss=5.5286 val_auc=0.8173
model=graphsage top_k=200 fold=8 epoch=91 loss=6.7274 val_auc=0.8175
model=graphsage top_k=200 fold=8 epoch=92 loss=4.8837 val_auc=0.8189
model=graphsage top_k=200 fold=8 epoch=93 loss=4.5160 val_auc=0.8193
model=graphsage top_k=200 fold=8 epoch=94 loss=5.3359 val_auc=0.8190
model=graphsage top_k=200 fold=8 epoch=95 loss=4.5015 val_auc=0.8180
model=graphsage top_k=200 fold=8 epoch=96 loss=4.8081 val_auc=0.8184
model=graphsage top_k=200 fold=8 epoch=97 loss=6.1305 val_auc=0.8196
model=graphsage top_k=200 fold=8 epoch=98 loss=5.1405 val_auc=0.8215
model=graphsage top_k=200 fold=8 epoch=99 loss=3.4723 val_auc=0.8251

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=200 fold=9 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=200 fold=9 epoch=0 loss=26.5248 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=200 fold=9 epoch=1 loss=228.2806 val_auc=0.6185
model=graphsage top_k=200 fold=9 epoch=2 loss=70.2532 val_auc=0.5144
model=graphsage top_k=200 fold=9 epoch=3 loss=109.7073 val_auc=0.5162
model=graphsage top_k=200 fold=9 epoch=4 loss=86.9728 val_auc=0.5359
model=graphsage top_k=200 fold=9 epoch=5 loss=27.1101 val_auc=0.7555

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=200 fold=9 epoch=6 loss=45.5793 val_auc=0.7600
model=graphsage top_k=200 fold=9 epoch=7 loss=52.2580 val_auc=0.7605
model=graphsage top_k=200 fold=9 epoch=8 loss=40.5114 val_auc=0.7570
model=graphsage top_k=200 fold=9 epoch=9 loss=16.9455 val_auc=0.5000
model=graphsage top_k=200 fold=9 epoch=10 loss=41.4615 val_auc=0.5000
model=graphsage top_k=200 fold=9 epoch=11 loss=53.7441 val_auc=0.5000
model=graphsage top_k=200 fold=9 epoch=12 loss=56.3144 val_auc=0.5000
model=graphsage top_k=200 fold=9 epoch=13 loss=28.3691 val_auc=0.7559
model=graphsage top_k=200 fold=9 epoch=14 loss=11.3713 val_auc=0.7604
model=graphsage top_k=200 fold=9 epoch=15 loss=20.0537 val_auc=0.7613
model=graphsage top_k=200 fold=9 epoch=16 loss=35.7327 val_auc=0.7631
model=graphsage top_k=200 fold=9 epoch=17 loss=30.0919 val_auc=0.7649
model=graphsage top_k=200 fold=9 epoch=18 loss=21.6152 val_auc=0.7663
model=graphsage top_k=200 fold=9 epoch=19 loss=14.2018 val_auc=0.7353
model=graphsage top_k=200 fold=9 epoch=20 loss=18.8905 val_auc=0.5541
model=graphsage top_k=200 fold=9 epoch=21 loss=25.2913 val_auc=0.5553
model=graphsage top_k=200 fold=9 epoch=22 loss=21.6120 val_auc=0.7110
model=graphsage top_k=200 fold=9 epoch=23 loss=21.7060 val_auc=0.7653
model=graphsage top_k=200 fold=9 epoch=24 loss=11.6740 val_auc=0.7692
model=graphsage top_k=200 fold=9 epoch=25 loss=11.7584 val_auc=0.7704
model=graphsage top_k=200 fold=9 epoch=26 loss=14.8236 val_auc=0.7712
model=graphsage top_k=200 fold=9 epoch=27 loss=17.1603 val_auc=0.7716
model=graphsage top_k=200 fold=9 epoch=28 loss=9.3755 val_auc=0.7690
model=graphsage top_k=200 fold=9 epoch=29 loss=9.9748 val_auc=0.7681
model=graphsage top_k=200 fold=9 epoch=30 loss=11.3561 val_auc=0.7691
model=graphsage top_k=200 fold=9 epoch=31 loss=11.2995 val_auc=0.7751
model=graphsage top_k=200 fold=9 epoch=32 loss=9.5723 val_auc=0.7783
model=graphsage top_k=200 fold=9 epoch=33 loss=9.0438 val_auc=0.7801
model=graphsage top_k=200 fold=9 epoch=34 loss=9.1208 val_auc=0.7816
model=graphsage top_k=200 fold=9 epoch=35 loss=11.2129 val_auc=0.7827
model=graphsage top_k=200 fold=9 epoch=36 loss=9.1841 val_auc=0.7797
model=graphsage top_k=200 fold=9 epoch=37 loss=9.4506 val_auc=0.7662
model=graphsage top_k=200 fold=9 epoch=38 loss=12.4023 val_auc=0.7705
model=graphsage top_k=200 fold=9 epoch=39 loss=9.6741 val_auc=0.7842
model=graphsage top_k=200 fold=9 epoch=40 loss=10.1920 val_auc=0.7878
model=graphsage top_k=200 fold=9 epoch=41 loss=7.8907 val_auc=0.7887
model=graphsage top_k=200 fold=9 epoch=42 loss=8.6309 val_auc=0.7894
model=graphsage top_k=200 fold=9 epoch=43 loss=9.2348 val_auc=0.7899
model=graphsage top_k=200 fold=9 epoch=44 loss=7.0075 val_auc=0.7883
model=graphsage top_k=200 fold=9 epoch=45 loss=9.4040 val_auc=0.7858
model=graphsage top_k=200 fold=9 epoch=46 loss=9.7257 val_auc=0.7900
model=graphsage top_k=200 fold=9 epoch=47 loss=10.3247 val_auc=0.7931
model=graphsage top_k=200 fold=9 epoch=48 loss=7.0544 val_auc=0.7943
model=graphsage top_k=200 fold=9 epoch=49 loss=7.2037 val_auc=0.7952
model=graphsage top_k=200 fold=9 epoch=50 loss=10.3788 val_auc=0.7959
model=graphsage top_k=200 fold=9 epoch=51 loss=10.1732 val_auc=0.7964
model=graphsage top_k=200 fold=9 epoch=52 loss=6.0590 val_auc=0.7951
model=graphsage top_k=200 fold=9 epoch=53 loss=7.9193 val_auc=0.7913
model=graphsage top_k=200 fold=9 epoch=54 loss=8.0830 val_auc=0.7935
model=graphsage top_k=200 fold=9 epoch=55 loss=7.5735 val_auc=0.7983
model=graphsage top_k=200 fold=9 epoch=56 loss=6.9188 val_auc=0.7998
model=graphsage top_k=200 fold=9 epoch=57 loss=7.0504 val_auc=0.8004
model=graphsage top_k=200 fold=9 epoch=58 loss=8.8409 val_auc=0.8009
model=graphsage top_k=200 fold=9 epoch=59 loss=7.7967 val_auc=0.8012
model=graphsage top_k=200 fold=9 epoch=60 loss=5.1910 val_auc=0.8017
model=graphsage top_k=200 fold=9 epoch=61 loss=6.1871 val_auc=0.8009
model=graphsage top_k=200 fold=9 epoch=62 loss=8.7325 val_auc=0.8028
model=graphsage top_k=200 fold=9 epoch=63 loss=6.7275 val_auc=0.8039
model=graphsage top_k=200 fold=9 epoch=64 loss=6.0302 val_auc=0.8043
model=graphsage top_k=200 fold=9 epoch=65 loss=6.5785 val_auc=0.8048
model=graphsage top_k=200 fold=9 epoch=66 loss=5.5617 val_auc=0.8055
model=graphsage top_k=200 fold=9 epoch=67 loss=5.6996 val_auc=0.8062
model=graphsage top_k=200 fold=9 epoch=68 loss=5.7554 val_auc=0.8071
model=graphsage top_k=200 fold=9 epoch=69 loss=5.5187 val_auc=0.8079
model=graphsage top_k=200 fold=9 epoch=70 loss=6.2640 val_auc=0.8086
model=graphsage top_k=200 fold=9 epoch=71 loss=5.0955 val_auc=0.8095
model=graphsage top_k=200 fold=9 epoch=72 loss=4.9321 val_auc=0.8103
model=graphsage top_k=200 fold=9 epoch=73 loss=5.2642 val_auc=0.8111
model=graphsage top_k=200 fold=9 epoch=74 loss=5.0062 val_auc=0.8119
model=graphsage top_k=200 fold=9 epoch=75 loss=5.7704 val_auc=0.8126
model=graphsage top_k=200 fold=9 epoch=76 loss=5.0870 val_auc=0.8133
model=graphsage top_k=200 fold=9 epoch=77 loss=4.4290 val_auc=0.8139
model=graphsage top_k=200 fold=9 epoch=78 loss=5.6752 val_auc=0.8144
model=graphsage top_k=200 fold=9 epoch=79 loss=4.6004 val_auc=0.8150
model=graphsage top_k=200 fold=9 epoch=80 loss=5.7630 val_auc=0.8154
model=graphsage top_k=200 fold=9 epoch=81 loss=4.3903 val_auc=0.8156
model=graphsage top_k=200 fold=9 epoch=82 loss=4.3676 val_auc=0.8161
model=graphsage top_k=200 fold=9 epoch=83 loss=4.0004 val_auc=0.8165
model=graphsage top_k=200 fold=9 epoch=84 loss=4.7263 val_auc=0.8170
model=graphsage top_k=200 fold=9 epoch=85 loss=4.9673 val_auc=0.8176
model=graphsage top_k=200 fold=9 epoch=86 loss=4.3865 val_auc=0.8184
model=graphsage top_k=200 fold=9 epoch=87 loss=4.3262 val_auc=0.8190
model=graphsage top_k=200 fold=9 epoch=88 loss=4.3865 val_auc=0.8195
model=graphsage top_k=200 fold=9 epoch=89 loss=4.0941 val_auc=0.8198
model=graphsage top_k=200 fold=9 epoch=90 loss=3.5673 val_auc=0.8202
model=graphsage top_k=200 fold=9 epoch=91 loss=3.6666 val_auc=0.8204
model=graphsage top_k=200 fold=9 epoch=92 loss=4.1805 val_auc=0.8207
model=graphsage top_k=200 fold=9 epoch=93 loss=5.4166 val_auc=0.8208
model=graphsage top_k=200 fold=9 epoch=94 loss=4.2235 val_auc=0.8210
model=graphsage top_k=200 fold=9 epoch=95 loss=4.6273 val_auc=0.8210
model=graphsage top_k=200 fold=9 epoch=96 loss=5.1366 val_auc=0.8209
model=graphsage top_k=200 fold=9 epoch=97 loss=4.5263 val_auc=0.8208
model=graphsage top_k=200 fold=9 epoch=98 loss=4.8096 val_auc=0.8207
model=graphsage top_k=200 fold=9 epoch=99 loss=4.5693 val_auc=0.8207

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

######## Model=graphsage top_k=500 ########

===== Model=graphsage top_k=500 fold=0 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=graphsage top_k=500 fold=0 epoch=0 loss=22.2702 val_auc=0.5000
model=graphsage top_k=500 fold=0 epoch=1 loss=345.1638 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=500 fold=0 epoch=2 loss=106.0481 val_auc=0.5325

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=500 fold=0 epoch=3 loss=81.9003 val_auc=0.6940
model=graphsage top_k=500 fold=0 epoch=4 loss=65.6713 val_auc=0.7535
model=graphsage top_k=500 fold=0 epoch=5 loss=13.0969 val_auc=0.5000
model=graphsage top_k=500 fold=0 epoch=6 loss=73.1008 val_auc=0.5000
model=graphsage top_k=500 fold=0 epoch=7 loss=71.9031 val_auc=0.5384
model=graphsage top_k=500 fold=0 epoch=8 loss=44.7001 val_auc=0.7755

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=500 fold=0 epoch=9 loss=12.1705 val_auc=0.7753

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=500 fold=0 epoch=10 loss=37.4885 val_auc=0.7758
model=graphsage top_k=500 fold=0 epoch=11 loss=47.4487 val_auc=0.7798
model=graphsage top_k=500 fold=0 epoch=12 loss=39.7071 val_auc=0.7802
model=graphsage top_k=500 fold=0 epoch=13 loss=20.7987 val_auc=0.7786
model=graphsage top_k=500 fold=0 epoch=14 loss=15.7075 val_auc=0.5719
model=graphsage top_k=500 fold=0 epoch=15 loss=24.1577 val_auc=0.5976
model=graphsage top_k=500 fold=0 epoch=16 loss=24.5192 val_auc=0.7769
model=graphsage top_k=500 fold=0 epoch=17 loss=17.5492 val_auc=0.7800
model=graphsage top_k=500 fold=0 epoch=18 loss=11.6066 val_auc=0.7801
model=graphsage top_k=500 fold=0 epoch=19 loss=12.1360 val_auc=0.7804
model=graphsage top_k=500 fold=0 epoch=20 loss=12.0898 val_auc=0.7794
model=graphsage top_k=500 fold=0 epoch=21 loss=10.4994 val_auc=0.7592
model=graphsage top_k=500 fold=0 epoch=22 loss=17.7809 val_auc=0.7216
model=graphsage top_k=500 fold=0 epoch=23 loss=17.3263 val_auc=0.7678
model=graphsage top_k=500 fold=0 epoch=24 loss=16.0124 val_auc=0.7825
model=graphsage top_k=500 fold=0 epoch=25 loss=10.3401 val_auc=0.7847
model=graphsage top_k=500 fold=0 epoch=26 loss=9.9559 val_auc=0.7862
model=graphsage top_k=500 fold=0 epoch=27 loss=10.7018 val_auc=0.7872
model=graphsage top_k=500 fold=0 epoch=28 loss=11.6853 val_auc=0.7872
model=graphsage top_k=500 fold=0 epoch=29 loss=9.6557 val_auc=0.7838
model=graphsage top_k=500 fold=0 epoch=30 loss=10.9983 val_auc=0.7870
model=graphsage top_k=500 fold=0 epoch=31 loss=9.7415 val_auc=0.7913
model=graphsage top_k=500 fold=0 epoch=32 loss=9.1644 val_auc=0.7921
model=graphsage top_k=500 fold=0 epoch=33 loss=7.0198 val_auc=0.7933
model=graphsage top_k=500 fold=0 epoch=34 loss=9.2601 val_auc=0.7942
model=graphsage top_k=500 fold=0 epoch=35 loss=7.9121 val_auc=0.7939
model=graphsage top_k=500 fold=0 epoch=36 loss=8.9641 val_auc=0.7941
model=graphsage top_k=500 fold=0 epoch=37 loss=8.4230 val_auc=0.7964
model=graphsage top_k=500 fold=0 epoch=38 loss=6.2313 val_auc=0.7983
model=graphsage top_k=500 fold=0 epoch=39 loss=7.6384 val_auc=0.7997
model=graphsage top_k=500 fold=0 epoch=40 loss=7.3679 val_auc=0.8010
model=graphsage top_k=500 fold=0 epoch=41 loss=8.0268 val_auc=0.8022
model=graphsage top_k=500 fold=0 epoch=42 loss=7.6803 val_auc=0.8031
model=graphsage top_k=500 fold=0 epoch=43 loss=7.6854 val_auc=0.8031
model=graphsage top_k=500 fold=0 epoch=44 loss=8.3635 val_auc=0.8046
model=graphsage top_k=500 fold=0 epoch=45 loss=6.7826 val_auc=0.8050
model=graphsage top_k=500 fold=0 epoch=46 loss=7.2359 val_auc=0.8054
model=graphsage top_k=500 fold=0 epoch=47 loss=9.4662 val_auc=0.8056
model=graphsage top_k=500 fold=0 epoch=48 loss=7.4439 val_auc=0.8052
model=graphsage top_k=500 fold=0 epoch=49 loss=8.0893 val_auc=0.8045
model=graphsage top_k=500 fold=0 epoch=50 loss=8.5421 val_auc=0.8055
model=graphsage top_k=500 fold=0 epoch=51 loss=6.4637 val_auc=0.8057
model=graphsage top_k=500 fold=0 epoch=52 loss=7.2188 val_auc=0.8059
model=graphsage top_k=500 fold=0 epoch=53 loss=7.5284 val_auc=0.8061
model=graphsage top_k=500 fold=0 epoch=54 loss=6.0777 val_auc=0.8064
model=graphsage top_k=500 fold=0 epoch=55 loss=6.8890 val_auc=0.8066
model=graphsage top_k=500 fold=0 epoch=56 loss=7.4585 val_auc=0.8073
model=graphsage top_k=500 fold=0 epoch=57 loss=6.3210 val_auc=0.8078
model=graphsage top_k=500 fold=0 epoch=58 loss=6.7278 val_auc=0.8083
model=graphsage top_k=500 fold=0 epoch=59 loss=5.5368 val_auc=0.8088
model=graphsage top_k=500 fold=0 epoch=60 loss=5.9547 val_auc=0.8091
model=graphsage top_k=500 fold=0 epoch=61 loss=5.9954 val_auc=0.8081
model=graphsage top_k=500 fold=0 epoch=62 loss=8.8704 val_auc=0.8102
model=graphsage top_k=500 fold=0 epoch=63 loss=7.6182 val_auc=0.8103
model=graphsage top_k=500 fold=0 epoch=64 loss=6.1094 val_auc=0.8105
model=graphsage top_k=500 fold=0 epoch=65 loss=7.6359 val_auc=0.8108
model=graphsage top_k=500 fold=0 epoch=66 loss=7.9242 val_auc=0.8113
model=graphsage top_k=500 fold=0 epoch=67 loss=5.6284 val_auc=0.8121
model=graphsage top_k=500 fold=0 epoch=68 loss=6.4321 val_auc=0.8121
model=graphsage top_k=500 fold=0 epoch=69 loss=6.1743 val_auc=0.8125
model=graphsage top_k=500 fold=0 epoch=70 loss=6.2584 val_auc=0.8126
model=graphsage top_k=500 fold=0 epoch=71 loss=5.1190 val_auc=0.8127
model=graphsage top_k=500 fold=0 epoch=72 loss=4.6779 val_auc=0.8131
model=graphsage top_k=500 fold=0 epoch=73 loss=7.1380 val_auc=0.8134
model=graphsage top_k=500 fold=0 epoch=74 loss=4.8976 val_auc=0.8139
model=graphsage top_k=500 fold=0 epoch=75 loss=5.4576 val_auc=0.8143
model=graphsage top_k=500 fold=0 epoch=76 loss=5.4242 val_auc=0.8143
model=graphsage top_k=500 fold=0 epoch=77 loss=4.9655 val_auc=0.8145
model=graphsage top_k=500 fold=0 epoch=78 loss=4.4875 val_auc=0.8147
model=graphsage top_k=500 fold=0 epoch=79 loss=4.4917 val_auc=0.8150
model=graphsage top_k=500 fold=0 epoch=80 loss=5.3075 val_auc=0.8152
model=graphsage top_k=500 fold=0 epoch=81 loss=4.1598 val_auc=0.8154
model=graphsage top_k=500 fold=0 epoch=82 loss=4.1343 val_auc=0.8157
model=graphsage top_k=500 fold=0 epoch=83 loss=5.9799 val_auc=0.8159
model=graphsage top_k=500 fold=0 epoch=84 loss=4.8332 val_auc=0.8163
model=graphsage top_k=500 fold=0 epoch=85 loss=4.0476 val_auc=0.8168
model=graphsage top_k=500 fold=0 epoch=86 loss=4.4049 val_auc=0.8174
model=graphsage top_k=500 fold=0 epoch=87 loss=3.9478 val_auc=0.8180
model=graphsage top_k=500 fold=0 epoch=88 loss=5.4243 val_auc=0.8184
model=graphsage top_k=500 fold=0 epoch=89 loss=4.4881 val_auc=0.8188
model=graphsage top_k=500 fold=0 epoch=90 loss=4.8643 val_auc=0.8191
model=graphsage top_k=500 fold=0 epoch=91 loss=4.3522 val_auc=0.8191
model=graphsage top_k=500 fold=0 epoch=92 loss=5.1019 val_auc=0.8193
model=graphsage top_k=500 fold=0 epoch=93 loss=4.5643 val_auc=0.8193
model=graphsage top_k=500 fold=0 epoch=94 loss=4.0638 val_auc=0.8193
model=graphsage top_k=500 fold=0 epoch=95 loss=3.7337 val_auc=0.8194
model=graphsage top_k=500 fold=0 epoch=96 loss=3.8986 val_auc=0.8197
model=graphsage top_k=500 fold=0 epoch=97 loss=3.8537 val_auc=0.8199
model=graphsage top_k=500 fold=0 epoch=98 loss=3.4263 val_auc=0.8202
model=graphsage top_k=500 fold=0 epoch=99 loss=4.3396 val_auc=0.8205

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=500 fold=1 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=graphsage top_k=500 fold=1 epoch=0 loss=22.9654 val_auc=0.5000
model=graphsage top_k=500 fold=1 epoch=1 loss=346.6836 val_auc=0.5000
model=graphsage top_k=500 fold=1 epoch=2 loss=165.4338 val_auc=0.6099
model=graphsage top_k=500 fold=1 epoch=3 loss=29.4037 val_auc=0.6950
model=graphsage top_k=500 fold=1 epoch=4 loss=18.7071 val_auc=0.5195
model=graphsage top_k=500 fold=1 epoch=5 loss=37.2340 val_auc=0.5240
model=graphsage top_k=500 fold=1 epoch=6 loss=32.5815 val_auc=0.7506
model=graphsage top_k=500 fold=1 epoch=7 loss=16.5430 val_auc=0.7574
model=graphsage top_k=500 fold=1 epoch=8 loss=15.3026 val_auc=0.7610
model=graphsage top_k=500 fold=1 epoch=9 loss=15.9473 val_auc=0.7668
model=graphsage top_k=500 fold=1 epoch=10 loss=11.8251 val_auc=0.7721
model=graphsage top_k=500 fold=1 epoch=11 loss=11.1722 val_auc=0.7750
model=graphsage top_k=500 fold=1 epoch=12 loss=10.7049 val_auc=0.7556
model=graphsage top_k=500 fold=1 epoch=13 loss=12.8826 val_auc=0.7433
model=graphsage top_k=500 fold=1 epoch=14 loss=15.8037 val_auc=0.7798
model=graphsage top_k=500 fold=1 epoch=15 loss=12.8999 val_auc=0.7849
model=graphsage top_k=500 fold=1 epoch=16 loss=17.3369 val_auc=0.7864
model=graphsage top_k=500 fold=1 epoch=17 loss=20.0645 val_auc=0.7872
model=graphsage top_k=500 fold=1 epoch=18 loss=12.2050 val_auc=0.7857
model=graphsage top_k=500 fold=1 epoch=19 loss=9.3914 val_auc=0.7826
model=graphsage top_k=500 fold=1 epoch=20 loss=14.0003 val_auc=0.7881
model=graphsage top_k=500 fold=1 epoch=21 loss=11.2696 val_auc=0.7907
model=graphsage top_k=500 fold=1 epoch=22 loss=10.0576 val_auc=0.7915
model=graphsage top_k=500 fold=1 epoch=23 loss=13.0525 val_auc=0.7922
model=graphsage top_k=500 fold=1 epoch=24 loss=9.3050 val_auc=0.7914
model=graphsage top_k=500 fold=1 epoch=25 loss=10.0589 val_auc=0.7885
model=graphsage top_k=500 fold=1 epoch=26 loss=10.7836 val_auc=0.7948
model=graphsage top_k=500 fold=1 epoch=27 loss=8.6280 val_auc=0.7965
model=graphsage top_k=500 fold=1 epoch=28 loss=8.7658 val_auc=0.7977
model=graphsage top_k=500 fold=1 epoch=29 loss=11.2395 val_auc=0.7987
model=graphsage top_k=500 fold=1 epoch=30 loss=7.3377 val_auc=0.8002
model=graphsage top_k=500 fold=1 epoch=31 loss=7.9431 val_auc=0.8018
model=graphsage top_k=500 fold=1 epoch=32 loss=7.9298 val_auc=0.8033
model=graphsage top_k=500 fold=1 epoch=33 loss=6.6683 val_auc=0.8051
model=graphsage top_k=500 fold=1 epoch=34 loss=6.8925 val_auc=0.8068
model=graphsage top_k=500 fold=1 epoch=35 loss=7.0758 val_auc=0.8082
model=graphsage top_k=500 fold=1 epoch=36 loss=6.5221 val_auc=0.8059
model=graphsage top_k=500 fold=1 epoch=37 loss=7.6380 val_auc=0.8051
model=graphsage top_k=500 fold=1 epoch=38 loss=10.0925 val_auc=0.8114
model=graphsage top_k=500 fold=1 epoch=39 loss=6.3920 val_auc=0.8131
model=graphsage top_k=500 fold=1 epoch=40 loss=10.3975 val_auc=0.8140
model=graphsage top_k=500 fold=1 epoch=41 loss=9.3349 val_auc=0.8149
model=graphsage top_k=500 fold=1 epoch=42 loss=9.6056 val_auc=0.8151
model=graphsage top_k=500 fold=1 epoch=43 loss=6.1783 val_auc=0.8109
model=graphsage top_k=500 fold=1 epoch=44 loss=9.4438 val_auc=0.8110
model=graphsage top_k=500 fold=1 epoch=45 loss=8.7213 val_auc=0.8154
model=graphsage top_k=500 fold=1 epoch=46 loss=6.0331 val_auc=0.8158
model=graphsage top_k=500 fold=1 epoch=47 loss=6.8880 val_auc=0.8158
model=graphsage top_k=500 fold=1 epoch=48 loss=7.8090 val_auc=0.8157
model=graphsage top_k=500 fold=1 epoch=49 loss=7.1700 val_auc=0.8160
model=graphsage top_k=500 fold=1 epoch=50 loss=6.6503 val_auc=0.8163
model=graphsage top_k=500 fold=1 epoch=51 loss=5.4202 val_auc=0.8183
model=graphsage top_k=500 fold=1 epoch=52 loss=5.0316 val_auc=0.8210
model=graphsage top_k=500 fold=1 epoch=53 loss=5.5986 val_auc=0.8236
model=graphsage top_k=500 fold=1 epoch=54 loss=5.2297 val_auc=0.8257
model=graphsage top_k=500 fold=1 epoch=55 loss=5.7543 val_auc=0.8274
model=graphsage top_k=500 fold=1 epoch=56 loss=6.2117 val_auc=0.8283
model=graphsage top_k=500 fold=1 epoch=57 loss=5.8418 val_auc=0.8289
model=graphsage top_k=500 fold=1 epoch=58 loss=6.1205 val_auc=0.8292
model=graphsage top_k=500 fold=1 epoch=59 loss=5.7961 val_auc=0.8293
model=graphsage top_k=500 fold=1 epoch=60 loss=6.5028 val_auc=0.8290
model=graphsage top_k=500 fold=1 epoch=61 loss=5.7483 val_auc=0.8283
model=graphsage top_k=500 fold=1 epoch=62 loss=4.6699 val_auc=0.8275
model=graphsage top_k=500 fold=1 epoch=63 loss=4.2821 val_auc=0.8271
model=graphsage top_k=500 fold=1 epoch=64 loss=5.9684 val_auc=0.8264
model=graphsage top_k=500 fold=1 epoch=65 loss=4.6889 val_auc=0.8267
model=graphsage top_k=500 fold=1 epoch=66 loss=4.8111 val_auc=0.8276
model=graphsage top_k=500 fold=1 epoch=67 loss=3.9378 val_auc=0.8302
model=graphsage top_k=500 fold=1 epoch=68 loss=4.1107 val_auc=0.8326
model=graphsage top_k=500 fold=1 epoch=69 loss=6.1500 val_auc=0.8336
model=graphsage top_k=500 fold=1 epoch=70 loss=4.3088 val_auc=0.8330
model=graphsage top_k=500 fold=1 epoch=71 loss=4.2083 val_auc=0.8319
model=graphsage top_k=500 fold=1 epoch=72 loss=6.1384 val_auc=0.8307
model=graphsage top_k=500 fold=1 epoch=73 loss=6.4912 val_auc=0.8299
model=graphsage top_k=500 fold=1 epoch=74 loss=4.0890 val_auc=0.8303
model=graphsage top_k=500 fold=1 epoch=75 loss=4.4120 val_auc=0.8312
model=graphsage top_k=500 fold=1 epoch=76 loss=5.9420 val_auc=0.8327
model=graphsage top_k=500 fold=1 epoch=77 loss=4.4054 val_auc=0.8336
model=graphsage top_k=500 fold=1 epoch=78 loss=4.4750 val_auc=0.8331
model=graphsage top_k=500 fold=1 epoch=79 loss=6.8813 val_auc=0.8319
model=graphsage top_k=500 fold=1 epoch=80 loss=7.1020 val_auc=0.8306
model=graphsage top_k=500 fold=1 epoch=81 loss=5.2903 val_auc=0.8303
model=graphsage top_k=500 fold=1 epoch=82 loss=3.8817 val_auc=0.8304
model=graphsage top_k=500 fold=1 epoch=83 loss=4.5281 val_auc=0.8301
model=graphsage top_k=500 fold=1 epoch=84 loss=4.2126 val_auc=0.8304
model=graphsage top_k=500 fold=1 epoch=85 loss=4.8248 val_auc=0.8299
model=graphsage top_k=500 fold=1 epoch=86 loss=3.7979 val_auc=0.8305
model=graphsage top_k=500 fold=1 epoch=87 loss=4.0530 val_auc=0.8315
model=graphsage top_k=500 fold=1 epoch=88 loss=5.1183 val_auc=0.8319
model=graphsage top_k=500 fold=1 epoch=89 loss=3.9517 val_auc=0.8320
graphsage top_k=500 fold=1: early stopping at epoch 89

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=500 fold=2 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=graphsage top_k=500 fold=2 epoch=0 loss=21.3628 val_auc=0.5000
model=graphsage top_k=500 fold=2 epoch=1 loss=294.5280 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=500 fold=2 epoch=2 loss=79.2003 val_auc=0.5017

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=500 fold=2 epoch=3 loss=96.2040 val_auc=0.5201
model=graphsage top_k=500 fold=2 epoch=4 loss=81.5714 val_auc=0.7496
model=graphsage top_k=500 fold=2 epoch=5 loss=26.3984 val_auc=0.5048
model=graphsage top_k=500 fold=2 epoch=6 loss=62.1908 val_auc=0.5000
model=graphsage top_k=500 fold=2 epoch=7 loss=73.2144 val_auc=0.5182
model=graphsage top_k=500 fold=2 epoch=8 loss=52.5867 val_auc=0.7633
model=graphsage top_k=500 fold=2 epoch=9 loss=14.2252 val_auc=0.7641
model=graphsage top_k=500 fold=2 epoch=10 loss=28.6349 val_auc=0.7644
model=graphsage top_k=500 fold=2 epoch=11 loss=47.0777 val_auc=0.7648
model=graphsage top_k=500 fold=2 epoch=12 loss=43.8611 val_auc=0.7647
model=graphsage top_k=500 fold=2 epoch=13 loss=23.6176 val_auc=0.7641
model=graphsage top_k=500 fold=2 epoch=14 loss=12.1538 val_auc=0.7431
model=graphsage top_k=500 fold=2 epoch=15 loss=15.9371 val_auc=0.7366
model=graphsage top_k=500 fold=2 epoch=16 loss=14.8642 val_auc=0.7677
model=graphsage top_k=500 fold=2 epoch=17 loss=10.7142 val_auc=0.7684
model=graphsage top_k=500 fold=2 epoch=18 loss=10.5144 val_auc=0.7694
model=graphsage top_k=500 fold=2 epoch=19 loss=15.9749 val_auc=0.7704
model=graphsage top_k=500 fold=2 epoch=20 loss=14.3224 val_auc=0.7711
model=graphsage top_k=500 fold=2 epoch=21 loss=9.0568 val_auc=0.7612
model=graphsage top_k=500 fold=2 epoch=22 loss=12.5797 val_auc=0.7317
model=graphsage top_k=500 fold=2 epoch=23 loss=13.4835 val_auc=0.7665
model=graphsage top_k=500 fold=2 epoch=24 loss=12.0480 val_auc=0.7770
model=graphsage top_k=500 fold=2 epoch=25 loss=9.4294 val_auc=0.7786
model=graphsage top_k=500 fold=2 epoch=26 loss=12.6245 val_auc=0.7797
model=graphsage top_k=500 fold=2 epoch=27 loss=15.7387 val_auc=0.7804
model=graphsage top_k=500 fold=2 epoch=28 loss=12.3547 val_auc=0.7809
model=graphsage top_k=500 fold=2 epoch=29 loss=11.9451 val_auc=0.7784
model=graphsage top_k=500 fold=2 epoch=30 loss=10.2823 val_auc=0.7668
model=graphsage top_k=500 fold=2 epoch=31 loss=11.4529 val_auc=0.7708
model=graphsage top_k=500 fold=2 epoch=32 loss=11.5211 val_auc=0.7815
model=graphsage top_k=500 fold=2 epoch=33 loss=9.1585 val_auc=0.7833
model=graphsage top_k=500 fold=2 epoch=34 loss=12.0902 val_auc=0.7839
model=graphsage top_k=500 fold=2 epoch=35 loss=10.5281 val_auc=0.7844
model=graphsage top_k=500 fold=2 epoch=36 loss=9.5591 val_auc=0.7848
model=graphsage top_k=500 fold=2 epoch=37 loss=7.5571 val_auc=0.7850
model=graphsage top_k=500 fold=2 epoch=38 loss=7.9378 val_auc=0.7829
model=graphsage top_k=500 fold=2 epoch=39 loss=12.0851 val_auc=0.7866
model=graphsage top_k=500 fold=2 epoch=40 loss=10.2199 val_auc=0.7897
model=graphsage top_k=500 fold=2 epoch=41 loss=10.9392 val_auc=0.7909
model=graphsage top_k=500 fold=2 epoch=42 loss=8.8402 val_auc=0.7919
model=graphsage top_k=500 fold=2 epoch=43 loss=9.8201 val_auc=0.7927
model=graphsage top_k=500 fold=2 epoch=44 loss=8.9241 val_auc=0.7934
model=graphsage top_k=500 fold=2 epoch=45 loss=7.2028 val_auc=0.7931
model=graphsage top_k=500 fold=2 epoch=46 loss=9.6018 val_auc=0.7889
model=graphsage top_k=500 fold=2 epoch=47 loss=11.4316 val_auc=0.7915
model=graphsage top_k=500 fold=2 epoch=48 loss=8.5419 val_auc=0.7956
model=graphsage top_k=500 fold=2 epoch=49 loss=7.3209 val_auc=0.7970
model=graphsage top_k=500 fold=2 epoch=50 loss=6.7636 val_auc=0.7977
model=graphsage top_k=500 fold=2 epoch=51 loss=10.5759 val_auc=0.7981
model=graphsage top_k=500 fold=2 epoch=52 loss=6.8306 val_auc=0.7986
model=graphsage top_k=500 fold=2 epoch=53 loss=6.9114 val_auc=0.7991
model=graphsage top_k=500 fold=2 epoch=54 loss=5.9710 val_auc=0.8000
model=graphsage top_k=500 fold=2 epoch=55 loss=6.7467 val_auc=0.8010
model=graphsage top_k=500 fold=2 epoch=56 loss=6.8984 val_auc=0.8021
model=graphsage top_k=500 fold=2 epoch=57 loss=6.6583 val_auc=0.8031
model=graphsage top_k=500 fold=2 epoch=58 loss=5.1624 val_auc=0.8043
model=graphsage top_k=500 fold=2 epoch=59 loss=6.4957 val_auc=0.8054
model=graphsage top_k=500 fold=2 epoch=60 loss=5.9729 val_auc=0.8066
model=graphsage top_k=500 fold=2 epoch=61 loss=5.0874 val_auc=0.8081
model=graphsage top_k=500 fold=2 epoch=62 loss=5.3829 val_auc=0.8095
model=graphsage top_k=500 fold=2 epoch=63 loss=5.4797 val_auc=0.8105
model=graphsage top_k=500 fold=2 epoch=64 loss=5.5023 val_auc=0.8117
model=graphsage top_k=500 fold=2 epoch=65 loss=6.6763 val_auc=0.8127
model=graphsage top_k=500 fold=2 epoch=66 loss=5.5142 val_auc=0.8133
model=graphsage top_k=500 fold=2 epoch=67 loss=8.3389 val_auc=0.8132
model=graphsage top_k=500 fold=2 epoch=68 loss=7.2812 val_auc=0.8144
model=graphsage top_k=500 fold=2 epoch=69 loss=5.5538 val_auc=0.8144
model=graphsage top_k=500 fold=2 epoch=70 loss=4.6279 val_auc=0.8146
model=graphsage top_k=500 fold=2 epoch=71 loss=5.0190 val_auc=0.8149
model=graphsage top_k=500 fold=2 epoch=72 loss=4.7523 val_auc=0.8152
model=graphsage top_k=500 fold=2 epoch=73 loss=4.7004 val_auc=0.8156
model=graphsage top_k=500 fold=2 epoch=74 loss=5.6721 val_auc=0.8160
model=graphsage top_k=500 fold=2 epoch=75 loss=5.1721 val_auc=0.8163
model=graphsage top_k=500 fold=2 epoch=76 loss=4.7194 val_auc=0.8166
model=graphsage top_k=500 fold=2 epoch=77 loss=4.3395 val_auc=0.8167
model=graphsage top_k=500 fold=2 epoch=78 loss=5.4219 val_auc=0.8167
model=graphsage top_k=500 fold=2 epoch=79 loss=4.4245 val_auc=0.8169
model=graphsage top_k=500 fold=2 epoch=80 loss=4.8763 val_auc=0.8174
model=graphsage top_k=500 fold=2 epoch=81 loss=4.2466 val_auc=0.8180
model=graphsage top_k=500 fold=2 epoch=82 loss=4.5365 val_auc=0.8181
model=graphsage top_k=500 fold=2 epoch=83 loss=4.2482 val_auc=0.8179
model=graphsage top_k=500 fold=2 epoch=84 loss=3.9425 val_auc=0.8185
model=graphsage top_k=500 fold=2 epoch=85 loss=5.2746 val_auc=0.8195
model=graphsage top_k=500 fold=2 epoch=86 loss=3.6900 val_auc=0.8205
model=graphsage top_k=500 fold=2 epoch=87 loss=5.5521 val_auc=0.8206
model=graphsage top_k=500 fold=2 epoch=88 loss=5.3731 val_auc=0.8204
model=graphsage top_k=500 fold=2 epoch=89 loss=3.4923 val_auc=0.8199
model=graphsage top_k=500 fold=2 epoch=90 loss=5.7111 val_auc=0.8198
model=graphsage top_k=500 fold=2 epoch=91 loss=6.6382 val_auc=0.8202
model=graphsage top_k=500 fold=2 epoch=92 loss=5.3628 val_auc=0.8208
model=graphsage top_k=500 fold=2 epoch=93 loss=3.0792 val_auc=0.8224
model=graphsage top_k=500 fold=2 epoch=94 loss=4.5716 val_auc=0.8236
model=graphsage top_k=500 fold=2 epoch=95 loss=5.9475 val_auc=0.8242
model=graphsage top_k=500 fold=2 epoch=96 loss=4.8421 val_auc=0.8244
model=graphsage top_k=500 fold=2 epoch=97 loss=3.2246 val_auc=0.8244
model=graphsage top_k=500 fold=2 epoch=98 loss=3.4265 val_auc=0.8246
model=graphsage top_k=500 fold=2 epoch=99 loss=4.4540 val_auc=0.8248

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=500 fold=3 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=graphsage top_k=500 fold=3 epoch=0 loss=23.1520 val_auc=0.5000
model=graphsage top_k=500 fold=3 epoch=1 loss=277.9141 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=500 fold=3 epoch=2 loss=64.5742 val_auc=0.5389

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=500 fold=3 epoch=3 loss=100.6457 val_auc=0.5399
model=graphsage top_k=500 fold=3 epoch=4 loss=83.6805 val_auc=0.7706
model=graphsage top_k=500 fold=3 epoch=5 loss=37.5242 val_auc=0.5014
model=graphsage top_k=500 fold=3 epoch=6 loss=27.2479 val_auc=0.5000
model=graphsage top_k=500 fold=3 epoch=7 loss=38.3791 val_auc=0.6582
model=graphsage top_k=500 fold=3 epoch=8 loss=18.8592 val_auc=0.7744
model=graphsage top_k=500 fold=3 epoch=9 loss=15.8923 val_auc=0.7759
model=graphsage top_k=500 fold=3 epoch=10 loss=19.3382 val_auc=0.7771
model=graphsage top_k=500 fold=3 epoch=11 loss=12.8931 val_auc=0.7711
model=graphsage top_k=500 fold=3 epoch=12 loss=15.7745 val_auc=0.7567
model=graphsage top_k=500 fold=3 epoch=13 loss=16.7788 val_auc=0.7768
model=graphsage top_k=500 fold=3 epoch=14 loss=10.2985 val_auc=0.7803
model=graphsage top_k=500 fold=3 epoch=15 loss=16.3088 val_auc=0.7809
model=graphsage top_k=500 fold=3 epoch=16 loss=13.3315 val_auc=0.7812
model=graphsage top_k=500 fold=3 epoch=17 loss=11.1331 val_auc=0.7785
model=graphsage top_k=500 fold=3 epoch=18 loss=13.6256 val_auc=0.7773
model=graphsage top_k=500 fold=3 epoch=19 loss=12.9137 val_auc=0.7806
model=graphsage top_k=500 fold=3 epoch=20 loss=10.5681 val_auc=0.7843
model=graphsage top_k=500 fold=3 epoch=21 loss=9.1388 val_auc=0.7859
model=graphsage top_k=500 fold=3 epoch=22 loss=10.2498 val_auc=0.7872
model=graphsage top_k=500 fold=3 epoch=23 loss=8.7700 val_auc=0.7875
model=graphsage top_k=500 fold=3 epoch=24 loss=9.2911 val_auc=0.7840
model=graphsage top_k=500 fold=3 epoch=25 loss=12.7094 val_auc=0.7892
model=graphsage top_k=500 fold=3 epoch=26 loss=9.9871 val_auc=0.7946
model=graphsage top_k=500 fold=3 epoch=27 loss=8.6356 val_auc=0.7964
model=graphsage top_k=500 fold=3 epoch=28 loss=10.3557 val_auc=0.7974
model=graphsage top_k=500 fold=3 epoch=29 loss=8.2380 val_auc=0.7977
model=graphsage top_k=500 fold=3 epoch=30 loss=7.5018 val_auc=0.7980
model=graphsage top_k=500 fold=3 epoch=31 loss=7.2171 val_auc=0.8005
model=graphsage top_k=500 fold=3 epoch=32 loss=7.5085 val_auc=0.8016
model=graphsage top_k=500 fold=3 epoch=33 loss=7.8620 val_auc=0.8025
model=graphsage top_k=500 fold=3 epoch=34 loss=9.8496 val_auc=0.8034
model=graphsage top_k=500 fold=3 epoch=35 loss=8.2571 val_auc=0.8043
model=graphsage top_k=500 fold=3 epoch=36 loss=7.0512 val_auc=0.8051
model=graphsage top_k=500 fold=3 epoch=37 loss=7.8587 val_auc=0.8060
model=graphsage top_k=500 fold=3 epoch=38 loss=6.8414 val_auc=0.8078
model=graphsage top_k=500 fold=3 epoch=39 loss=6.2857 val_auc=0.8090
model=graphsage top_k=500 fold=3 epoch=40 loss=7.1441 val_auc=0.8102
model=graphsage top_k=500 fold=3 epoch=41 loss=6.9039 val_auc=0.8108
model=graphsage top_k=500 fold=3 epoch=42 loss=6.5606 val_auc=0.8115
model=graphsage top_k=500 fold=3 epoch=43 loss=6.5867 val_auc=0.8122
model=graphsage top_k=500 fold=3 epoch=44 loss=8.0219 val_auc=0.8125
model=graphsage top_k=500 fold=3 epoch=45 loss=6.7725 val_auc=0.8130
model=graphsage top_k=500 fold=3 epoch=46 loss=8.1648 val_auc=0.8137
model=graphsage top_k=500 fold=3 epoch=47 loss=6.4855 val_auc=0.8139
model=graphsage top_k=500 fold=3 epoch=48 loss=7.4110 val_auc=0.8140
model=graphsage top_k=500 fold=3 epoch=49 loss=11.4704 val_auc=0.8141
model=graphsage top_k=500 fold=3 epoch=50 loss=10.1535 val_auc=0.8141
model=graphsage top_k=500 fold=3 epoch=51 loss=7.9462 val_auc=0.8140
model=graphsage top_k=500 fold=3 epoch=52 loss=5.9108 val_auc=0.8144
model=graphsage top_k=500 fold=3 epoch=53 loss=5.7934 val_auc=0.8154
model=graphsage top_k=500 fold=3 epoch=54 loss=5.9943 val_auc=0.8164
model=graphsage top_k=500 fold=3 epoch=55 loss=6.8635 val_auc=0.8171
model=graphsage top_k=500 fold=3 epoch=56 loss=6.1959 val_auc=0.8175
model=graphsage top_k=500 fold=3 epoch=57 loss=6.0827 val_auc=0.8179
model=graphsage top_k=500 fold=3 epoch=58 loss=5.3482 val_auc=0.8184
model=graphsage top_k=500 fold=3 epoch=59 loss=6.2162 val_auc=0.8186
model=graphsage top_k=500 fold=3 epoch=60 loss=7.2877 val_auc=0.8189
model=graphsage top_k=500 fold=3 epoch=61 loss=6.9505 val_auc=0.8192
model=graphsage top_k=500 fold=3 epoch=62 loss=5.9555 val_auc=0.8194
model=graphsage top_k=500 fold=3 epoch=63 loss=6.2518 val_auc=0.8181
model=graphsage top_k=500 fold=3 epoch=64 loss=6.6305 val_auc=0.8196
model=graphsage top_k=500 fold=3 epoch=65 loss=6.5021 val_auc=0.8200
model=graphsage top_k=500 fold=3 epoch=66 loss=5.9920 val_auc=0.8199
model=graphsage top_k=500 fold=3 epoch=67 loss=7.6754 val_auc=0.8198
model=graphsage top_k=500 fold=3 epoch=68 loss=6.6871 val_auc=0.8195
model=graphsage top_k=500 fold=3 epoch=69 loss=5.3438 val_auc=0.8191
model=graphsage top_k=500 fold=3 epoch=70 loss=4.8939 val_auc=0.8185
model=graphsage top_k=500 fold=3 epoch=71 loss=6.2310 val_auc=0.8191
model=graphsage top_k=500 fold=3 epoch=72 loss=5.6317 val_auc=0.8193
model=graphsage top_k=500 fold=3 epoch=73 loss=4.3099 val_auc=0.8197
model=graphsage top_k=500 fold=3 epoch=74 loss=5.2571 val_auc=0.8201
model=graphsage top_k=500 fold=3 epoch=75 loss=4.3668 val_auc=0.8208
model=graphsage top_k=500 fold=3 epoch=76 loss=5.1078 val_auc=0.8214
model=graphsage top_k=500 fold=3 epoch=77 loss=4.4360 val_auc=0.8221
model=graphsage top_k=500 fold=3 epoch=78 loss=5.8073 val_auc=0.8228
model=graphsage top_k=500 fold=3 epoch=79 loss=3.6700 val_auc=0.8233
model=graphsage top_k=500 fold=3 epoch=80 loss=4.3097 val_auc=0.8238
model=graphsage top_k=500 fold=3 epoch=81 loss=4.7185 val_auc=0.8240
model=graphsage top_k=500 fold=3 epoch=82 loss=4.4426 val_auc=0.8238
model=graphsage top_k=500 fold=3 epoch=83 loss=3.6837 val_auc=0.8238
model=graphsage top_k=500 fold=3 epoch=84 loss=5.1984 val_auc=0.8242
model=graphsage top_k=500 fold=3 epoch=85 loss=4.4786 val_auc=0.8245
model=graphsage top_k=500 fold=3 epoch=86 loss=5.1498 val_auc=0.8247
model=graphsage top_k=500 fold=3 epoch=87 loss=4.6646 val_auc=0.8243
model=graphsage top_k=500 fold=3 epoch=88 loss=4.2240 val_auc=0.8240
model=graphsage top_k=500 fold=3 epoch=89 loss=7.0597 val_auc=0.8239
model=graphsage top_k=500 fold=3 epoch=90 loss=5.6576 val_auc=0.8240
model=graphsage top_k=500 fold=3 epoch=91 loss=5.6626 val_auc=0.8243
model=graphsage top_k=500 fold=3 epoch=92 loss=3.7335 val_auc=0.8244
model=graphsage top_k=500 fold=3 epoch=93 loss=4.2165 val_auc=0.8242
model=graphsage top_k=500 fold=3 epoch=94 loss=4.4049 val_auc=0.8238
model=graphsage top_k=500 fold=3 epoch=95 loss=4.2885 val_auc=0.8235
model=graphsage top_k=500 fold=3 epoch=96 loss=4.3927 val_auc=0.8233
model=graphsage top_k=500 fold=3 epoch=97 loss=3.8486 val_auc=0.8235
model=graphsage top_k=500 fold=3 epoch=98 loss=3.9614 val_auc=0.8237
graphsage top_k=500 fold=3: early stopping at epoch 98

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=500 fold=4 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=500 fold=4 epoch=0 loss=19.4029 val_auc=0.7038
model=graphsage top_k=500 fold=4 epoch=1 loss=48.6457 val_auc=0.5000
model=graphsage top_k=500 fold=4 epoch=2 loss=184.5407 val_auc=0.5000
model=graphsage top_k=500 fold=4 epoch=3 loss=116.2334 val_auc=0.7655
model=graphsage top_k=500 fold=4 epoch=4 loss=13.5113 val_auc=0.7701
model=graphsage top_k=500 fold=4 epoch=5 loss=19.9982 val_auc=0.6998
model=graphsage top_k=500 fold=4 epoch=6 loss=17.3823 val_auc=0.7729
model=graphsage top_k=500 fold=4 epoch=7 loss=11.6366 val_auc=0.7781
model=graphsage top_k=500 fold=4 epoch=8 loss=23.0477 val_auc=0.7800
model=graphsage top_k=500 fold=4 epoch=9 loss=26.6103 val_auc=0.7797
model=graphsage top_k=500 fold=4 epoch=10 loss=12.5333 val_auc=0.7774
model=graphsage top_k=500 fold=4 epoch=11 loss=14.0224 val_auc=0.7825
model=graphsage top_k=500 fold=4 epoch=12 loss=13.8944 val_auc=0.7829
model=graphsage top_k=500 fold=4 epoch=13 loss=11.8400 val_auc=0.7840
model=graphsage top_k=500 fold=4 epoch=14 loss=10.7832 val_auc=0.7835
model=graphsage top_k=500 fold=4 epoch=15 loss=9.3552 val_auc=0.7304
model=graphsage top_k=500 fold=4 epoch=16 loss=14.4668 val_auc=0.7373
model=graphsage top_k=500 fold=4 epoch=17 loss=12.8616 val_auc=0.7891
model=graphsage top_k=500 fold=4 epoch=18 loss=9.6939 val_auc=0.7929
model=graphsage top_k=500 fold=4 epoch=19 loss=19.5806 val_auc=0.7943
model=graphsage top_k=500 fold=4 epoch=20 loss=23.3650 val_auc=0.7952
model=graphsage top_k=500 fold=4 epoch=21 loss=15.2714 val_auc=0.7954
model=graphsage top_k=500 fold=4 epoch=22 loss=8.0179 val_auc=0.6675
model=graphsage top_k=500 fold=4 epoch=23 loss=14.4041 val_auc=0.5388
model=graphsage top_k=500 fold=4 epoch=24 loss=26.5071 val_auc=0.5833
model=graphsage top_k=500 fold=4 epoch=25 loss=22.6461 val_auc=0.7720
model=graphsage top_k=500 fold=4 epoch=26 loss=12.3303 val_auc=0.7992
model=graphsage top_k=500 fold=4 epoch=27 loss=10.6206 val_auc=0.7995
model=graphsage top_k=500 fold=4 epoch=28 loss=12.8812 val_auc=0.7998
model=graphsage top_k=500 fold=4 epoch=29 loss=12.8252 val_auc=0.7998
model=graphsage top_k=500 fold=4 epoch=30 loss=10.5581 val_auc=0.7904
model=graphsage top_k=500 fold=4 epoch=31 loss=11.6614 val_auc=0.7673
model=graphsage top_k=500 fold=4 epoch=32 loss=14.6397 val_auc=0.7829
model=graphsage top_k=500 fold=4 epoch=33 loss=12.9354 val_auc=0.7991
model=graphsage top_k=500 fold=4 epoch=34 loss=8.3147 val_auc=0.8002
model=graphsage top_k=500 fold=4 epoch=35 loss=8.5443 val_auc=0.8010
model=graphsage top_k=500 fold=4 epoch=36 loss=8.6582 val_auc=0.8018
model=graphsage top_k=500 fold=4 epoch=37 loss=6.7232 val_auc=0.8006
model=graphsage top_k=500 fold=4 epoch=38 loss=8.3513 val_auc=0.7956
model=graphsage top_k=500 fold=4 epoch=39 loss=10.4837 val_auc=0.8035
model=graphsage top_k=500 fold=4 epoch=40 loss=8.1154 val_auc=0.8055
model=graphsage top_k=500 fold=4 epoch=41 loss=7.4706 val_auc=0.8058
model=graphsage top_k=500 fold=4 epoch=42 loss=8.6832 val_auc=0.8062
model=graphsage top_k=500 fold=4 epoch=43 loss=6.5209 val_auc=0.8052
model=graphsage top_k=500 fold=4 epoch=44 loss=6.6939 val_auc=0.8024
model=graphsage top_k=500 fold=4 epoch=45 loss=10.6070 val_auc=0.8073
model=graphsage top_k=500 fold=4 epoch=46 loss=7.4224 val_auc=0.8077
model=graphsage top_k=500 fold=4 epoch=47 loss=8.2529 val_auc=0.8081
model=graphsage top_k=500 fold=4 epoch=48 loss=7.2747 val_auc=0.8088
model=graphsage top_k=500 fold=4 epoch=49 loss=6.1053 val_auc=0.8091
model=graphsage top_k=500 fold=4 epoch=50 loss=8.1271 val_auc=0.8071
model=graphsage top_k=500 fold=4 epoch=51 loss=8.8490 val_auc=0.8109
model=graphsage top_k=500 fold=4 epoch=52 loss=7.1036 val_auc=0.8112
model=graphsage top_k=500 fold=4 epoch=53 loss=6.2320 val_auc=0.8118
model=graphsage top_k=500 fold=4 epoch=54 loss=7.1441 val_auc=0.8123
model=graphsage top_k=500 fold=4 epoch=55 loss=7.0346 val_auc=0.8130
model=graphsage top_k=500 fold=4 epoch=56 loss=4.9340 val_auc=0.8119
model=graphsage top_k=500 fold=4 epoch=57 loss=7.9145 val_auc=0.8033
model=graphsage top_k=500 fold=4 epoch=58 loss=9.5841 val_auc=0.8151
model=graphsage top_k=500 fold=4 epoch=59 loss=10.1267 val_auc=0.8165
model=graphsage top_k=500 fold=4 epoch=60 loss=5.6463 val_auc=0.8171
model=graphsage top_k=500 fold=4 epoch=61 loss=7.7059 val_auc=0.8173
model=graphsage top_k=500 fold=4 epoch=62 loss=12.0095 val_auc=0.8175
model=graphsage top_k=500 fold=4 epoch=63 loss=7.2914 val_auc=0.8176
model=graphsage top_k=500 fold=4 epoch=64 loss=5.7779 val_auc=0.8167
model=graphsage top_k=500 fold=4 epoch=65 loss=8.8820 val_auc=0.7915
model=graphsage top_k=500 fold=4 epoch=66 loss=10.6618 val_auc=0.7931
model=graphsage top_k=500 fold=4 epoch=67 loss=13.5297 val_auc=0.8140
model=graphsage top_k=500 fold=4 epoch=68 loss=6.7090 val_auc=0.8152
model=graphsage top_k=500 fold=4 epoch=69 loss=5.9477 val_auc=0.8146
model=graphsage top_k=500 fold=4 epoch=70 loss=7.0411 val_auc=0.8144
model=graphsage top_k=500 fold=4 epoch=71 loss=10.5545 val_auc=0.8142
model=graphsage top_k=500 fold=4 epoch=72 loss=9.7230 val_auc=0.8143
model=graphsage top_k=500 fold=4 epoch=73 loss=7.4451 val_auc=0.8145
model=graphsage top_k=500 fold=4 epoch=74 loss=4.5895 val_auc=0.8149
model=graphsage top_k=500 fold=4 epoch=75 loss=5.7131 val_auc=0.8155
graphsage top_k=500 fold=4: early stopping at epoch 75

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=500 fold=5 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=graphsage top_k=500 fold=5 epoch=0 loss=27.6615 val_auc=0.5000
model=graphsage top_k=500 fold=5 epoch=1 loss=324.2077 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=500 fold=5 epoch=2 loss=114.4739 val_auc=0.7352
model=graphsage top_k=500 fold=5 epoch=3 loss=59.7131 val_auc=0.7525
model=graphsage top_k=500 fold=5 epoch=4 loss=38.3462 val_auc=0.7246
model=graphsage top_k=500 fold=5 epoch=5 loss=16.2852 val_auc=0.7614
model=graphsage top_k=500 fold=5 epoch=6 loss=11.8893 val_auc=0.7670
model=graphsage top_k=500 fold=5 epoch=7 loss=22.6032 val_auc=0.7718
model=graphsage top_k=500 fold=5 epoch=8 loss=25.0504 val_auc=0.7760
model=graphsage top_k=500 fold=5 epoch=9 loss=11.6384 val_auc=0.5367
model=graphsage top_k=500 fold=5 epoch=10 loss=32.8066 val_auc=0.5215
model=graphsage top_k=500 fold=5 epoch=11 loss=32.4070 val_auc=0.7000
model=graphsage top_k=500 fold=5 epoch=12 loss=18.2889 val_auc=0.7826
model=graphsage top_k=500 fold=5 epoch=13 loss=12.7623 val_auc=0.7836
model=graphsage top_k=500 fold=5 epoch=14 loss=18.2754 val_auc=0.7850
model=graphsage top_k=500 fold=5 epoch=15 loss=13.8770 val_auc=0.7817
model=graphsage top_k=500 fold=5 epoch=16 loss=9.9052 val_auc=0.7797
model=graphsage top_k=500 fold=5 epoch=17 loss=12.0224 val_auc=0.7898
model=graphsage top_k=500 fold=5 epoch=18 loss=10.5448 val_auc=0.7929
model=graphsage top_k=500 fold=5 epoch=19 loss=15.7853 val_auc=0.7948
model=graphsage top_k=500 fold=5 epoch=20 loss=18.0798 val_auc=0.7964
model=graphsage top_k=500 fold=5 epoch=21 loss=10.0451 val_auc=0.7973
model=graphsage top_k=500 fold=5 epoch=22 loss=10.5387 val_auc=0.7844
model=graphsage top_k=500 fold=5 epoch=23 loss=14.0802 val_auc=0.7978
model=graphsage top_k=500 fold=5 epoch=24 loss=10.0836 val_auc=0.8013
model=graphsage top_k=500 fold=5 epoch=25 loss=9.5261 val_auc=0.8023
model=graphsage top_k=500 fold=5 epoch=26 loss=8.8644 val_auc=0.8033
model=graphsage top_k=500 fold=5 epoch=27 loss=8.7669 val_auc=0.7949
model=graphsage top_k=500 fold=5 epoch=28 loss=9.8531 val_auc=0.7853
model=graphsage top_k=500 fold=5 epoch=29 loss=11.4773 val_auc=0.8029
model=graphsage top_k=500 fold=5 epoch=30 loss=12.1299 val_auc=0.8062
model=graphsage top_k=500 fold=5 epoch=31 loss=9.3266 val_auc=0.8066
model=graphsage top_k=500 fold=5 epoch=32 loss=12.4572 val_auc=0.8071
model=graphsage top_k=500 fold=5 epoch=33 loss=10.2419 val_auc=0.8062
model=graphsage top_k=500 fold=5 epoch=34 loss=9.3989 val_auc=0.8062
model=graphsage top_k=500 fold=5 epoch=35 loss=9.5864 val_auc=0.8080
model=graphsage top_k=500 fold=5 epoch=36 loss=7.7838 val_auc=0.8091
model=graphsage top_k=500 fold=5 epoch=37 loss=9.9391 val_auc=0.8096
model=graphsage top_k=500 fold=5 epoch=38 loss=9.5717 val_auc=0.8102
model=graphsage top_k=500 fold=5 epoch=39 loss=7.8593 val_auc=0.8065
model=graphsage top_k=500 fold=5 epoch=40 loss=9.3830 val_auc=0.7936
model=graphsage top_k=500 fold=5 epoch=41 loss=12.6165 val_auc=0.8075
model=graphsage top_k=500 fold=5 epoch=42 loss=9.8645 val_auc=0.8126
model=graphsage top_k=500 fold=5 epoch=43 loss=6.3388 val_auc=0.8139
model=graphsage top_k=500 fold=5 epoch=44 loss=7.1742 val_auc=0.8153
model=graphsage top_k=500 fold=5 epoch=45 loss=6.4078 val_auc=0.8168
model=graphsage top_k=500 fold=5 epoch=46 loss=8.0637 val_auc=0.8186
model=graphsage top_k=500 fold=5 epoch=47 loss=7.9902 val_auc=0.8196
model=graphsage top_k=500 fold=5 epoch=48 loss=7.2643 val_auc=0.8206
model=graphsage top_k=500 fold=5 epoch=49 loss=6.9429 val_auc=0.8199
model=graphsage top_k=500 fold=5 epoch=50 loss=7.3499 val_auc=0.8205
model=graphsage top_k=500 fold=5 epoch=51 loss=6.1196 val_auc=0.8217
model=graphsage top_k=500 fold=5 epoch=52 loss=7.3676 val_auc=0.8214
model=graphsage top_k=500 fold=5 epoch=53 loss=6.9247 val_auc=0.8216
model=graphsage top_k=500 fold=5 epoch=54 loss=6.6909 val_auc=0.8219
model=graphsage top_k=500 fold=5 epoch=55 loss=6.3333 val_auc=0.8218
model=graphsage top_k=500 fold=5 epoch=56 loss=7.7067 val_auc=0.8218
model=graphsage top_k=500 fold=5 epoch=57 loss=8.6202 val_auc=0.8217
model=graphsage top_k=500 fold=5 epoch=58 loss=8.7519 val_auc=0.8214
model=graphsage top_k=500 fold=5 epoch=59 loss=7.3775 val_auc=0.8212
model=graphsage top_k=500 fold=5 epoch=60 loss=7.3102 val_auc=0.8200
model=graphsage top_k=500 fold=5 epoch=61 loss=6.6020 val_auc=0.8153
model=graphsage top_k=500 fold=5 epoch=62 loss=8.2439 val_auc=0.8197
model=graphsage top_k=500 fold=5 epoch=63 loss=6.2293 val_auc=0.8219
model=graphsage top_k=500 fold=5 epoch=64 loss=6.6855 val_auc=0.8222
model=graphsage top_k=500 fold=5 epoch=65 loss=8.5305 val_auc=0.8226
model=graphsage top_k=500 fold=5 epoch=66 loss=7.6862 val_auc=0.8231
model=graphsage top_k=500 fold=5 epoch=67 loss=7.5759 val_auc=0.8235
model=graphsage top_k=500 fold=5 epoch=68 loss=5.1279 val_auc=0.8107
model=graphsage top_k=500 fold=5 epoch=69 loss=10.1821 val_auc=0.7651
model=graphsage top_k=500 fold=5 epoch=70 loss=13.3325 val_auc=0.7674
model=graphsage top_k=500 fold=5 epoch=71 loss=15.6311 val_auc=0.8071
model=graphsage top_k=500 fold=5 epoch=72 loss=8.8982 val_auc=0.8232
model=graphsage top_k=500 fold=5 epoch=73 loss=6.2346 val_auc=0.8238
model=graphsage top_k=500 fold=5 epoch=74 loss=6.9503 val_auc=0.8237
model=graphsage top_k=500 fold=5 epoch=75 loss=7.5867 val_auc=0.8237
model=graphsage top_k=500 fold=5 epoch=76 loss=8.9231 val_auc=0.8238
model=graphsage top_k=500 fold=5 epoch=77 loss=4.5269 val_auc=0.8242
model=graphsage top_k=500 fold=5 epoch=78 loss=6.3188 val_auc=0.8227
model=graphsage top_k=500 fold=5 epoch=79 loss=8.0768 val_auc=0.8252
model=graphsage top_k=500 fold=5 epoch=80 loss=5.6940 val_auc=0.8258
model=graphsage top_k=500 fold=5 epoch=81 loss=4.9563 val_auc=0.8263
model=graphsage top_k=500 fold=5 epoch=82 loss=4.5733 val_auc=0.8268
model=graphsage top_k=500 fold=5 epoch=83 loss=7.4798 val_auc=0.8269
model=graphsage top_k=500 fold=5 epoch=84 loss=6.4778 val_auc=0.8270
model=graphsage top_k=500 fold=5 epoch=85 loss=4.6841 val_auc=0.8265
model=graphsage top_k=500 fold=5 epoch=86 loss=6.4592 val_auc=0.8189
model=graphsage top_k=500 fold=5 epoch=87 loss=10.0458 val_auc=0.8206
model=graphsage top_k=500 fold=5 epoch=88 loss=7.6988 val_auc=0.8257
model=graphsage top_k=500 fold=5 epoch=89 loss=6.0092 val_auc=0.8255
model=graphsage top_k=500 fold=5 epoch=90 loss=4.9971 val_auc=0.8250
model=graphsage top_k=500 fold=5 epoch=91 loss=6.5725 val_auc=0.8246
model=graphsage top_k=500 fold=5 epoch=92 loss=11.0709 val_auc=0.8244
model=graphsage top_k=500 fold=5 epoch=93 loss=11.8816 val_auc=0.8241
model=graphsage top_k=500 fold=5 epoch=94 loss=10.4361 val_auc=0.8237
model=graphsage top_k=500 fold=5 epoch=95 loss=7.0572 val_auc=0.8233
model=graphsage top_k=500 fold=5 epoch=96 loss=4.5984 val_auc=0.8233
graphsage top_k=500 fold=5: early stopping at epoch 96

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=500 fold=6 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=500 fold=6 epoch=0 loss=39.1638 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=500 fold=6 epoch=1 loss=224.1944 val_auc=0.4479
model=graphsage top_k=500 fold=6 epoch=2 loss=59.8214 val_auc=0.5000
model=graphsage top_k=500 fold=6 epoch=3 loss=117.1311 val_auc=0.5000
model=graphsage top_k=500 fold=6 epoch=4 loss=104.1787 val_auc=0.5038
model=graphsage top_k=500 fold=6 epoch=5 loss=40.0739 val_auc=0.6863
model=graphsage top_k=500 fold=6 epoch=6 loss=47.2766 val_auc=0.7112
model=graphsage top_k=500 fold=6 epoch=7 loss=47.2679 val_auc=0.7249
model=graphsage top_k=500 fold=6 epoch=8 loss=29.1658 val_auc=0.5156
model=graphsage top_k=500 fold=6 epoch=9 loss=22.6417 val_auc=0.5000
model=graphsage top_k=500 fold=6 epoch=10 loss=27.7812 val_auc=0.6336
model=graphsage top_k=500 fold=6 epoch=11 loss=18.0870 val_auc=0.7692
model=graphsage top_k=500 fold=6 epoch=12 loss=13.3243 val_auc=0.7740
model=graphsage top_k=500 fold=6 epoch=13 loss=16.3599 val_auc=0.7776
model=graphsage top_k=500 fold=6 epoch=14 loss=11.1588 val_auc=0.7597
model=graphsage top_k=500 fold=6 epoch=15 loss=16.0792 val_auc=0.7120
model=graphsage top_k=500 fold=6 epoch=16 loss=18.1665 val_auc=0.7780
model=graphsage top_k=500 fold=6 epoch=17 loss=14.9528 val_auc=0.7843
model=graphsage top_k=500 fold=6 epoch=18 loss=12.9455 val_auc=0.7853
model=graphsage top_k=500 fold=6 epoch=19 loss=15.7493 val_auc=0.7857
model=graphsage top_k=500 fold=6 epoch=20 loss=13.2452 val_auc=0.7855
model=graphsage top_k=500 fold=6 epoch=21 loss=9.7753 val_auc=0.7074
model=graphsage top_k=500 fold=6 epoch=22 loss=16.6775 val_auc=0.6295
model=graphsage top_k=500 fold=6 epoch=23 loss=17.2743 val_auc=0.7155
model=graphsage top_k=500 fold=6 epoch=24 loss=15.6809 val_auc=0.7911
model=graphsage top_k=500 fold=6 epoch=25 loss=10.2008 val_auc=0.7939
model=graphsage top_k=500 fold=6 epoch=26 loss=14.0305 val_auc=0.7947
model=graphsage top_k=500 fold=6 epoch=27 loss=16.3582 val_auc=0.7952
model=graphsage top_k=500 fold=6 epoch=28 loss=15.5863 val_auc=0.7952
model=graphsage top_k=500 fold=6 epoch=29 loss=12.3902 val_auc=0.7923
model=graphsage top_k=500 fold=6 epoch=30 loss=8.8963 val_auc=0.7911
model=graphsage top_k=500 fold=6 epoch=31 loss=11.8662 val_auc=0.7966
model=graphsage top_k=500 fold=6 epoch=32 loss=8.7463 val_auc=0.7981
model=graphsage top_k=500 fold=6 epoch=33 loss=8.8395 val_auc=0.7999
model=graphsage top_k=500 fold=6 epoch=34 loss=7.8217 val_auc=0.8011
model=graphsage top_k=500 fold=6 epoch=35 loss=8.0795 val_auc=0.8021
model=graphsage top_k=500 fold=6 epoch=36 loss=7.7980 val_auc=0.8036
model=graphsage top_k=500 fold=6 epoch=37 loss=9.1880 val_auc=0.8050
model=graphsage top_k=500 fold=6 epoch=38 loss=8.5959 val_auc=0.8065
model=graphsage top_k=500 fold=6 epoch=39 loss=7.4895 val_auc=0.8080
model=graphsage top_k=500 fold=6 epoch=40 loss=7.6463 val_auc=0.8079
model=graphsage top_k=500 fold=6 epoch=41 loss=8.2417 val_auc=0.8091
model=graphsage top_k=500 fold=6 epoch=42 loss=7.1145 val_auc=0.8114
model=graphsage top_k=500 fold=6 epoch=43 loss=8.0864 val_auc=0.8125
model=graphsage top_k=500 fold=6 epoch=44 loss=7.9158 val_auc=0.8131
model=graphsage top_k=500 fold=6 epoch=45 loss=9.0412 val_auc=0.8137
model=graphsage top_k=500 fold=6 epoch=46 loss=6.7686 val_auc=0.8134
model=graphsage top_k=500 fold=6 epoch=47 loss=8.7751 val_auc=0.8082
model=graphsage top_k=500 fold=6 epoch=48 loss=10.9571 val_auc=0.8137
model=graphsage top_k=500 fold=6 epoch=49 loss=7.8621 val_auc=0.8153
model=graphsage top_k=500 fold=6 epoch=50 loss=6.6027 val_auc=0.8156
model=graphsage top_k=500 fold=6 epoch=51 loss=5.9459 val_auc=0.8163
model=graphsage top_k=500 fold=6 epoch=52 loss=6.3661 val_auc=0.8145
model=graphsage top_k=500 fold=6 epoch=53 loss=7.6572 val_auc=0.8099
model=graphsage top_k=500 fold=6 epoch=54 loss=9.4937 val_auc=0.8165
model=graphsage top_k=500 fold=6 epoch=55 loss=7.3788 val_auc=0.8179
model=graphsage top_k=500 fold=6 epoch=56 loss=6.2410 val_auc=0.8183
model=graphsage top_k=500 fold=6 epoch=57 loss=6.7830 val_auc=0.8187
model=graphsage top_k=500 fold=6 epoch=58 loss=6.4834 val_auc=0.8191
model=graphsage top_k=500 fold=6 epoch=59 loss=6.1964 val_auc=0.8164
model=graphsage top_k=500 fold=6 epoch=60 loss=10.7676 val_auc=0.8118
model=graphsage top_k=500 fold=6 epoch=61 loss=9.2121 val_auc=0.8169
model=graphsage top_k=500 fold=6 epoch=62 loss=9.2600 val_auc=0.8212
model=graphsage top_k=500 fold=6 epoch=63 loss=7.0471 val_auc=0.8216
model=graphsage top_k=500 fold=6 epoch=64 loss=5.8834 val_auc=0.8219
model=graphsage top_k=500 fold=6 epoch=65 loss=6.4949 val_auc=0.8223
model=graphsage top_k=500 fold=6 epoch=66 loss=6.2279 val_auc=0.8227
model=graphsage top_k=500 fold=6 epoch=67 loss=5.3608 val_auc=0.8234
model=graphsage top_k=500 fold=6 epoch=68 loss=5.4046 val_auc=0.8239
model=graphsage top_k=500 fold=6 epoch=69 loss=6.1742 val_auc=0.8245
model=graphsage top_k=500 fold=6 epoch=70 loss=5.2308 val_auc=0.8253
model=graphsage top_k=500 fold=6 epoch=71 loss=5.3569 val_auc=0.8263
model=graphsage top_k=500 fold=6 epoch=72 loss=5.4062 val_auc=0.8273
model=graphsage top_k=500 fold=6 epoch=73 loss=4.5382 val_auc=0.8283
model=graphsage top_k=500 fold=6 epoch=74 loss=5.7788 val_auc=0.8289
model=graphsage top_k=500 fold=6 epoch=75 loss=4.7763 val_auc=0.8295
model=graphsage top_k=500 fold=6 epoch=76 loss=4.8116 val_auc=0.8301
model=graphsage top_k=500 fold=6 epoch=77 loss=5.1986 val_auc=0.8306
model=graphsage top_k=500 fold=6 epoch=78 loss=5.9107 val_auc=0.8307
model=graphsage top_k=500 fold=6 epoch=79 loss=5.9323 val_auc=0.8309
model=graphsage top_k=500 fold=6 epoch=80 loss=5.4893 val_auc=0.8308
model=graphsage top_k=500 fold=6 epoch=81 loss=6.5001 val_auc=0.8301
model=graphsage top_k=500 fold=6 epoch=82 loss=5.6575 val_auc=0.8296
model=graphsage top_k=500 fold=6 epoch=83 loss=5.6665 val_auc=0.8290
model=graphsage top_k=500 fold=6 epoch=84 loss=4.9743 val_auc=0.8289
model=graphsage top_k=500 fold=6 epoch=85 loss=4.6056 val_auc=0.8289
model=graphsage top_k=500 fold=6 epoch=86 loss=4.0774 val_auc=0.8297
model=graphsage top_k=500 fold=6 epoch=87 loss=3.7069 val_auc=0.8306
model=graphsage top_k=500 fold=6 epoch=88 loss=5.1269 val_auc=0.8314
model=graphsage top_k=500 fold=6 epoch=89 loss=3.7158 val_auc=0.8328
model=graphsage top_k=500 fold=6 epoch=90 loss=3.7930 val_auc=0.8340
model=graphsage top_k=500 fold=6 epoch=91 loss=5.6826 val_auc=0.8348
model=graphsage top_k=500 fold=6 epoch=92 loss=4.4622 val_auc=0.8352
model=graphsage top_k=500 fold=6 epoch=93 loss=4.0470 val_auc=0.8353
model=graphsage top_k=500 fold=6 epoch=94 loss=4.3555 val_auc=0.8354
model=graphsage top_k=500 fold=6 epoch=95 loss=4.9757 val_auc=0.8355
model=graphsage top_k=500 fold=6 epoch=96 loss=4.0868 val_auc=0.8357
model=graphsage top_k=500 fold=6 epoch=97 loss=3.3844 val_auc=0.8357
model=graphsage top_k=500 fold=6 epoch=98 loss=3.3619 val_auc=0.8356
model=graphsage top_k=500 fold=6 epoch=99 loss=4.3219 val_auc=0.8352

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=500 fold=7 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=500 fold=7 epoch=0 loss=21.2114 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=500 fold=7 epoch=1 loss=197.5679 val_auc=0.5709
model=graphsage top_k=500 fold=7 epoch=2 loss=21.3811 val_auc=0.5000
model=graphsage top_k=500 fold=7 epoch=3 loss=166.1704 val_auc=0.5000
model=graphsage top_k=500 fold=7 epoch=4 loss=143.9986 val_auc=0.5000
model=graphsage top_k=500 fold=7 epoch=5 loss=58.1574 val_auc=0.7224
model=graphsage top_k=500 fold=7 epoch=6 loss=24.4858 val_auc=0.7375
model=graphsage top_k=500 fold=7 epoch=7 loss=35.5747 val_auc=0.7484
model=graphsage top_k=500 fold=7 epoch=8 loss=15.3644 val_auc=0.5345
model=graphsage top_k=500 fold=7 epoch=9 loss=17.6690 val_auc=0.5355
model=graphsage top_k=500 fold=7 epoch=10 loss=28.5047 val_auc=0.6461
model=graphsage top_k=500 fold=7 epoch=11 loss=14.9431 val_auc=0.7610
model=graphsage top_k=500 fold=7 epoch=12 loss=13.8266 val_auc=0.7639
model=graphsage top_k=500 fold=7 epoch=13 loss=18.3840 val_auc=0.7651
model=graphsage top_k=500 fold=7 epoch=14 loss=14.1758 val_auc=0.7655
model=graphsage top_k=500 fold=7 epoch=15 loss=10.3050 val_auc=0.7625
model=graphsage top_k=500 fold=7 epoch=16 loss=13.0539 val_auc=0.7648
model=graphsage top_k=500 fold=7 epoch=17 loss=13.5475 val_auc=0.7671
model=graphsage top_k=500 fold=7 epoch=18 loss=12.9778 val_auc=0.7677
model=graphsage top_k=500 fold=7 epoch=19 loss=13.1761 val_auc=0.7692
model=graphsage top_k=500 fold=7 epoch=20 loss=9.7541 val_auc=0.7683
model=graphsage top_k=500 fold=7 epoch=21 loss=12.1944 val_auc=0.7659
model=graphsage top_k=500 fold=7 epoch=22 loss=12.6810 val_auc=0.7733
model=graphsage top_k=500 fold=7 epoch=23 loss=11.8974 val_auc=0.7753
model=graphsage top_k=500 fold=7 epoch=24 loss=10.5114 val_auc=0.7770
model=graphsage top_k=500 fold=7 epoch=25 loss=10.2079 val_auc=0.7786
model=graphsage top_k=500 fold=7 epoch=26 loss=8.7882 val_auc=0.7772
model=graphsage top_k=500 fold=7 epoch=27 loss=10.1230 val_auc=0.7749
model=graphsage top_k=500 fold=7 epoch=28 loss=10.8578 val_auc=0.7821
model=graphsage top_k=500 fold=7 epoch=29 loss=8.4703 val_auc=0.7846
model=graphsage top_k=500 fold=7 epoch=30 loss=8.3221 val_auc=0.7858
model=graphsage top_k=500 fold=7 epoch=31 loss=8.3671 val_auc=0.7870
model=graphsage top_k=500 fold=7 epoch=32 loss=8.0310 val_auc=0.7874
model=graphsage top_k=500 fold=7 epoch=33 loss=7.2454 val_auc=0.7875
model=graphsage top_k=500 fold=7 epoch=34 loss=9.1470 val_auc=0.7889
model=graphsage top_k=500 fold=7 epoch=35 loss=9.3619 val_auc=0.7896
model=graphsage top_k=500 fold=7 epoch=36 loss=6.5774 val_auc=0.7904
model=graphsage top_k=500 fold=7 epoch=37 loss=9.4692 val_auc=0.7915
model=graphsage top_k=500 fold=7 epoch=38 loss=9.5570 val_auc=0.7925
model=graphsage top_k=500 fold=7 epoch=39 loss=7.7433 val_auc=0.7917
model=graphsage top_k=500 fold=7 epoch=40 loss=8.0919 val_auc=0.7873
model=graphsage top_k=500 fold=7 epoch=41 loss=9.1869 val_auc=0.7941
model=graphsage top_k=500 fold=7 epoch=42 loss=7.4253 val_auc=0.7950
model=graphsage top_k=500 fold=7 epoch=43 loss=7.2001 val_auc=0.7952
model=graphsage top_k=500 fold=7 epoch=44 loss=9.5032 val_auc=0.7957
model=graphsage top_k=500 fold=7 epoch=45 loss=9.6990 val_auc=0.7963
model=graphsage top_k=500 fold=7 epoch=46 loss=7.1189 val_auc=0.7961
model=graphsage top_k=500 fold=7 epoch=47 loss=9.0105 val_auc=0.7966
model=graphsage top_k=500 fold=7 epoch=48 loss=6.8413 val_auc=0.7969
model=graphsage top_k=500 fold=7 epoch=49 loss=7.8105 val_auc=0.7975
model=graphsage top_k=500 fold=7 epoch=50 loss=7.2875 val_auc=0.7983
model=graphsage top_k=500 fold=7 epoch=51 loss=6.2968 val_auc=0.7990
model=graphsage top_k=500 fold=7 epoch=52 loss=5.2105 val_auc=0.7983
model=graphsage top_k=500 fold=7 epoch=53 loss=10.5698 val_auc=0.8020
model=graphsage top_k=500 fold=7 epoch=54 loss=8.9288 val_auc=0.8035
model=graphsage top_k=500 fold=7 epoch=55 loss=5.1200 val_auc=0.8046
model=graphsage top_k=500 fold=7 epoch=56 loss=6.1532 val_auc=0.8056
model=graphsage top_k=500 fold=7 epoch=57 loss=5.8371 val_auc=0.8064
model=graphsage top_k=500 fold=7 epoch=58 loss=5.7822 val_auc=0.8068
model=graphsage top_k=500 fold=7 epoch=59 loss=5.4945 val_auc=0.8076
model=graphsage top_k=500 fold=7 epoch=60 loss=5.3785 val_auc=0.8085
model=graphsage top_k=500 fold=7 epoch=61 loss=5.4958 val_auc=0.8092
model=graphsage top_k=500 fold=7 epoch=62 loss=6.4109 val_auc=0.8100
model=graphsage top_k=500 fold=7 epoch=63 loss=4.9026 val_auc=0.8112
model=graphsage top_k=500 fold=7 epoch=64 loss=7.1266 val_auc=0.8119
model=graphsage top_k=500 fold=7 epoch=65 loss=6.6393 val_auc=0.8118
model=graphsage top_k=500 fold=7 epoch=66 loss=5.2233 val_auc=0.8117
model=graphsage top_k=500 fold=7 epoch=67 loss=5.1796 val_auc=0.8119
model=graphsage top_k=500 fold=7 epoch=68 loss=5.5095 val_auc=0.8121
model=graphsage top_k=500 fold=7 epoch=69 loss=4.7990 val_auc=0.8123
model=graphsage top_k=500 fold=7 epoch=70 loss=4.0375 val_auc=0.8134
model=graphsage top_k=500 fold=7 epoch=71 loss=4.0962 val_auc=0.8149
model=graphsage top_k=500 fold=7 epoch=72 loss=5.0481 val_auc=0.8160
model=graphsage top_k=500 fold=7 epoch=73 loss=5.8274 val_auc=0.8167
model=graphsage top_k=500 fold=7 epoch=74 loss=5.3388 val_auc=0.8171
model=graphsage top_k=500 fold=7 epoch=75 loss=4.7763 val_auc=0.8173
model=graphsage top_k=500 fold=7 epoch=76 loss=4.5877 val_auc=0.8178
model=graphsage top_k=500 fold=7 epoch=77 loss=3.9929 val_auc=0.8181
model=graphsage top_k=500 fold=7 epoch=78 loss=4.4097 val_auc=0.8184
model=graphsage top_k=500 fold=7 epoch=79 loss=5.4595 val_auc=0.8186
model=graphsage top_k=500 fold=7 epoch=80 loss=4.9369 val_auc=0.8187
model=graphsage top_k=500 fold=7 epoch=81 loss=3.9725 val_auc=0.8187
model=graphsage top_k=500 fold=7 epoch=82 loss=4.8170 val_auc=0.8185
model=graphsage top_k=500 fold=7 epoch=83 loss=4.6503 val_auc=0.8181
model=graphsage top_k=500 fold=7 epoch=84 loss=4.3796 val_auc=0.8179
model=graphsage top_k=500 fold=7 epoch=85 loss=4.0586 val_auc=0.8178
model=graphsage top_k=500 fold=7 epoch=86 loss=3.6892 val_auc=0.8183
model=graphsage top_k=500 fold=7 epoch=87 loss=5.1041 val_auc=0.8185
model=graphsage top_k=500 fold=7 epoch=88 loss=4.4839 val_auc=0.8188
model=graphsage top_k=500 fold=7 epoch=89 loss=4.4071 val_auc=0.8185
model=graphsage top_k=500 fold=7 epoch=90 loss=4.2832 val_auc=0.8180
model=graphsage top_k=500 fold=7 epoch=91 loss=4.5480 val_auc=0.8176
model=graphsage top_k=500 fold=7 epoch=92 loss=6.4856 val_auc=0.8175
model=graphsage top_k=500 fold=7 epoch=93 loss=3.7464 val_auc=0.8179
model=graphsage top_k=500 fold=7 epoch=94 loss=5.2991 val_auc=0.8180
model=graphsage top_k=500 fold=7 epoch=95 loss=3.8211 val_auc=0.8180
model=graphsage top_k=500 fold=7 epoch=96 loss=4.4074 val_auc=0.8178
model=graphsage top_k=500 fold=7 epoch=97 loss=3.8147 val_auc=0.8178
model=graphsage top_k=500 fold=7 epoch=98 loss=3.4075 val_auc=0.8186
model=graphsage top_k=500 fold=7 epoch=99 loss=6.2279 val_auc=0.8195

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=500 fold=8 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=graphsage top_k=500 fold=8 epoch=0 loss=51.8007 val_auc=0.5000
model=graphsage top_k=500 fold=8 epoch=1 loss=288.2585 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=500 fold=8 epoch=2 loss=59.9201 val_auc=0.5271

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=500 fold=8 epoch=3 loss=104.0568 val_auc=0.5382
model=graphsage top_k=500 fold=8 epoch=4 loss=93.0402 val_auc=0.7423
model=graphsage top_k=500 fold=8 epoch=5 loss=35.6320 val_auc=0.5000
model=graphsage top_k=500 fold=8 epoch=6 loss=41.2502 val_auc=0.5000
model=graphsage top_k=500 fold=8 epoch=7 loss=53.2067 val_auc=0.5035
model=graphsage top_k=500 fold=8 epoch=8 loss=26.9001 val_auc=0.7523
model=graphsage top_k=500 fold=8 epoch=9 loss=13.2920 val_auc=0.7597
model=graphsage top_k=500 fold=8 epoch=10 loss=17.7278 val_auc=0.7645
model=graphsage top_k=500 fold=8 epoch=11 loss=10.0858 val_auc=0.6292
model=graphsage top_k=500 fold=8 epoch=12 loss=20.6957 val_auc=0.5554
model=graphsage top_k=500 fold=8 epoch=13 loss=24.1162 val_auc=0.7666
model=graphsage top_k=500 fold=8 epoch=14 loss=14.8124 val_auc=0.7705
model=graphsage top_k=500 fold=8 epoch=15 loss=12.7504 val_auc=0.7716
model=graphsage top_k=500 fold=8 epoch=16 loss=12.8605 val_auc=0.7724
model=graphsage top_k=500 fold=8 epoch=17 loss=9.7735 val_auc=0.7725
model=graphsage top_k=500 fold=8 epoch=18 loss=11.2942 val_auc=0.7726
model=graphsage top_k=500 fold=8 epoch=19 loss=10.7328 val_auc=0.7741
model=graphsage top_k=500 fold=8 epoch=20 loss=8.9211 val_auc=0.7748
model=graphsage top_k=500 fold=8 epoch=21 loss=8.8755 val_auc=0.7756
model=graphsage top_k=500 fold=8 epoch=22 loss=8.3395 val_auc=0.7778
model=graphsage top_k=500 fold=8 epoch=23 loss=9.3616 val_auc=0.7815
model=graphsage top_k=500 fold=8 epoch=24 loss=7.8414 val_auc=0.7835
model=graphsage top_k=500 fold=8 epoch=25 loss=9.0323 val_auc=0.7844
model=graphsage top_k=500 fold=8 epoch=26 loss=9.2722 val_auc=0.7805
model=graphsage top_k=500 fold=8 epoch=27 loss=9.2000 val_auc=0.7814
model=graphsage top_k=500 fold=8 epoch=28 loss=9.9874 val_auc=0.7846
model=graphsage top_k=500 fold=8 epoch=29 loss=8.4514 val_auc=0.7851
model=graphsage top_k=500 fold=8 epoch=30 loss=8.4751 val_auc=0.7859
model=graphsage top_k=500 fold=8 epoch=31 loss=10.5540 val_auc=0.7867
model=graphsage top_k=500 fold=8 epoch=32 loss=7.9752 val_auc=0.7864
model=graphsage top_k=500 fold=8 epoch=33 loss=12.1013 val_auc=0.7871
model=graphsage top_k=500 fold=8 epoch=34 loss=11.3171 val_auc=0.7892
model=graphsage top_k=500 fold=8 epoch=35 loss=7.8510 val_auc=0.7901
model=graphsage top_k=500 fold=8 epoch=36 loss=9.3109 val_auc=0.7909
model=graphsage top_k=500 fold=8 epoch=37 loss=10.2417 val_auc=0.7917
model=graphsage top_k=500 fold=8 epoch=38 loss=8.1441 val_auc=0.7921
model=graphsage top_k=500 fold=8 epoch=39 loss=7.3735 val_auc=0.7674
model=graphsage top_k=500 fold=8 epoch=40 loss=11.3312 val_auc=0.6669
model=graphsage top_k=500 fold=8 epoch=41 loss=20.8685 val_auc=0.6748
model=graphsage top_k=500 fold=8 epoch=42 loss=17.2558 val_auc=0.7671
model=graphsage top_k=500 fold=8 epoch=43 loss=11.0758 val_auc=0.7938
model=graphsage top_k=500 fold=8 epoch=44 loss=5.9924 val_auc=0.7949
model=graphsage top_k=500 fold=8 epoch=45 loss=9.9600 val_auc=0.7952
model=graphsage top_k=500 fold=8 epoch=46 loss=13.4296 val_auc=0.7953
model=graphsage top_k=500 fold=8 epoch=47 loss=16.8894 val_auc=0.7954
model=graphsage top_k=500 fold=8 epoch=48 loss=13.1615 val_auc=0.7954
model=graphsage top_k=500 fold=8 epoch=49 loss=9.6966 val_auc=0.7950
model=graphsage top_k=500 fold=8 epoch=50 loss=7.7664 val_auc=0.7910
model=graphsage top_k=500 fold=8 epoch=51 loss=8.2544 val_auc=0.7914
model=graphsage top_k=500 fold=8 epoch=52 loss=9.4196 val_auc=0.7953
model=graphsage top_k=500 fold=8 epoch=53 loss=7.3148 val_auc=0.7964
model=graphsage top_k=500 fold=8 epoch=54 loss=6.0985 val_auc=0.7969
model=graphsage top_k=500 fold=8 epoch=55 loss=6.6971 val_auc=0.7975
model=graphsage top_k=500 fold=8 epoch=56 loss=5.8698 val_auc=0.7981
model=graphsage top_k=500 fold=8 epoch=57 loss=6.5070 val_auc=0.7986
model=graphsage top_k=500 fold=8 epoch=58 loss=5.7644 val_auc=0.7996
model=graphsage top_k=500 fold=8 epoch=59 loss=5.9291 val_auc=0.8005
model=graphsage top_k=500 fold=8 epoch=60 loss=6.3512 val_auc=0.8012
model=graphsage top_k=500 fold=8 epoch=61 loss=7.6176 val_auc=0.8018
model=graphsage top_k=500 fold=8 epoch=62 loss=5.6956 val_auc=0.8025
model=graphsage top_k=500 fold=8 epoch=63 loss=7.0919 val_auc=0.8023
model=graphsage top_k=500 fold=8 epoch=64 loss=6.7583 val_auc=0.8037
model=graphsage top_k=500 fold=8 epoch=65 loss=6.2314 val_auc=0.8039
model=graphsage top_k=500 fold=8 epoch=66 loss=5.5049 val_auc=0.8042
model=graphsage top_k=500 fold=8 epoch=67 loss=5.3362 val_auc=0.8048
model=graphsage top_k=500 fold=8 epoch=68 loss=5.0746 val_auc=0.8055
model=graphsage top_k=500 fold=8 epoch=69 loss=5.8719 val_auc=0.8064
model=graphsage top_k=500 fold=8 epoch=70 loss=4.7784 val_auc=0.8073
model=graphsage top_k=500 fold=8 epoch=71 loss=4.7937 val_auc=0.8082
model=graphsage top_k=500 fold=8 epoch=72 loss=5.3251 val_auc=0.8090
model=graphsage top_k=500 fold=8 epoch=73 loss=4.5295 val_auc=0.8099
model=graphsage top_k=500 fold=8 epoch=74 loss=4.7385 val_auc=0.8105
model=graphsage top_k=500 fold=8 epoch=75 loss=6.1166 val_auc=0.8110
model=graphsage top_k=500 fold=8 epoch=76 loss=4.6239 val_auc=0.8116
model=graphsage top_k=500 fold=8 epoch=77 loss=4.4236 val_auc=0.8121
model=graphsage top_k=500 fold=8 epoch=78 loss=4.7933 val_auc=0.8125
model=graphsage top_k=500 fold=8 epoch=79 loss=4.6602 val_auc=0.8128
model=graphsage top_k=500 fold=8 epoch=80 loss=5.0923 val_auc=0.8131
model=graphsage top_k=500 fold=8 epoch=81 loss=4.1472 val_auc=0.8133
model=graphsage top_k=500 fold=8 epoch=82 loss=4.9911 val_auc=0.8137
model=graphsage top_k=500 fold=8 epoch=83 loss=3.8142 val_auc=0.8145
model=graphsage top_k=500 fold=8 epoch=84 loss=3.9148 val_auc=0.8152
model=graphsage top_k=500 fold=8 epoch=85 loss=4.0836 val_auc=0.8159
model=graphsage top_k=500 fold=8 epoch=86 loss=4.6793 val_auc=0.8165
model=graphsage top_k=500 fold=8 epoch=87 loss=4.9081 val_auc=0.8172
model=graphsage top_k=500 fold=8 epoch=88 loss=4.5547 val_auc=0.8175
model=graphsage top_k=500 fold=8 epoch=89 loss=4.0568 val_auc=0.8178
model=graphsage top_k=500 fold=8 epoch=90 loss=3.3355 val_auc=0.8188
model=graphsage top_k=500 fold=8 epoch=91 loss=4.3459 val_auc=0.8194
model=graphsage top_k=500 fold=8 epoch=92 loss=4.4889 val_auc=0.8198
model=graphsage top_k=500 fold=8 epoch=93 loss=4.2247 val_auc=0.8203
model=graphsage top_k=500 fold=8 epoch=94 loss=4.3969 val_auc=0.8206
model=graphsage top_k=500 fold=8 epoch=95 loss=5.5770 val_auc=0.8206
model=graphsage top_k=500 fold=8 epoch=96 loss=4.2940 val_auc=0.8203
model=graphsage top_k=500 fold=8 epoch=97 loss=3.6133 val_auc=0.8203
model=graphsage top_k=500 fold=8 epoch=98 loss=3.5112 val_auc=0.8207
model=graphsage top_k=500 fold=8 epoch=99 loss=4.5783 val_auc=0.8211

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=graphsage top_k=500 fold=9 =====
Config for graphsage: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=500 fold=9 epoch=0 loss=35.1883 val_auc=0.5000

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=500 fold=9 epoch=1 loss=237.0332 val_auc=0.5411
model=graphsage top_k=500 fold=9 epoch=2 loss=78.8327 val_auc=0.5000
model=graphsage top_k=500 fold=9 epoch=3 loss=95.8874 val_auc=0.5000
model=graphsage top_k=500 fold=9 epoch=4 loss=76.7259 val_auc=0.7344

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=500 fold=9 epoch=5 loss=14.0214 val_auc=0.7389

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=graphsage top_k=500 fold=9 epoch=6 loss=60.6490 val_auc=0.6474
model=graphsage top_k=500 fold=9 epoch=7 loss=69.5464 val_auc=0.7671
model=graphsage top_k=500 fold=9 epoch=8 loss=51.6736 val_auc=0.7644
model=graphsage top_k=500 fold=9 epoch=9 loss=13.7545 val_auc=0.5188
model=graphsage top_k=500 fold=9 epoch=10 loss=38.4736 val_auc=0.5000
model=graphsage top_k=500 fold=9 epoch=11 loss=53.2834 val_auc=0.5000
model=graphsage top_k=500 fold=9 epoch=12 loss=49.9131 val_auc=0.5396
model=graphsage top_k=500 fold=9 epoch=13 loss=27.1554 val_auc=0.7657
model=graphsage top_k=500 fold=9 epoch=14 loss=10.8235 val_auc=0.7698
model=graphsage top_k=500 fold=9 epoch=15 loss=24.1313 val_auc=0.7703
model=graphsage top_k=500 fold=9 epoch=16 loss=38.0283 val_auc=0.7711
model=graphsage top_k=500 fold=9 epoch=17 loss=34.3251 val_auc=0.7725
model=graphsage top_k=500 fold=9 epoch=18 loss=26.7341 val_auc=0.7734
model=graphsage top_k=500 fold=9 epoch=19 loss=13.3497 val_auc=0.7690
model=graphsage top_k=500 fold=9 epoch=20 loss=11.7513 val_auc=0.7115
model=graphsage top_k=500 fold=9 epoch=21 loss=17.9967 val_auc=0.5972
model=graphsage top_k=500 fold=9 epoch=22 loss=19.9383 val_auc=0.7658
model=graphsage top_k=500 fold=9 epoch=23 loss=14.6760 val_auc=0.7718
model=graphsage top_k=500 fold=9 epoch=24 loss=13.4825 val_auc=0.7752
model=graphsage top_k=500 fold=9 epoch=25 loss=13.0196 val_auc=0.7752
model=graphsage top_k=500 fold=9 epoch=26 loss=13.0751 val_auc=0.7757
model=graphsage top_k=500 fold=9 epoch=27 loss=14.5437 val_auc=0.7764
model=graphsage top_k=500 fold=9 epoch=28 loss=12.6290 val_auc=0.7767
model=graphsage top_k=500 fold=9 epoch=29 loss=10.3042 val_auc=0.7745
model=graphsage top_k=500 fold=9 epoch=30 loss=13.7365 val_auc=0.7607
model=graphsage top_k=500 fold=9 epoch=31 loss=16.6879 val_auc=0.7621
model=graphsage top_k=500 fold=9 epoch=32 loss=15.6980 val_auc=0.7762
model=graphsage top_k=500 fold=9 epoch=33 loss=10.8381 val_auc=0.7784
model=graphsage top_k=500 fold=9 epoch=34 loss=8.0620 val_auc=0.7796
model=graphsage top_k=500 fold=9 epoch=35 loss=8.3818 val_auc=0.7806
model=graphsage top_k=500 fold=9 epoch=36 loss=11.5209 val_auc=0.7815
model=graphsage top_k=500 fold=9 epoch=37 loss=12.6260 val_auc=0.7822
model=graphsage top_k=500 fold=9 epoch=38 loss=10.1871 val_auc=0.7828
model=graphsage top_k=500 fold=9 epoch=39 loss=7.2332 val_auc=0.7821
model=graphsage top_k=500 fold=9 epoch=40 loss=8.3344 val_auc=0.7767
model=graphsage top_k=500 fold=9 epoch=41 loss=14.5478 val_auc=0.7755
model=graphsage top_k=500 fold=9 epoch=42 loss=9.3136 val_auc=0.7831
model=graphsage top_k=500 fold=9 epoch=43 loss=9.7359 val_auc=0.7875
model=graphsage top_k=500 fold=9 epoch=44 loss=7.3179 val_auc=0.7890
model=graphsage top_k=500 fold=9 epoch=45 loss=9.8878 val_auc=0.7900
model=graphsage top_k=500 fold=9 epoch=46 loss=9.2707 val_auc=0.7908
model=graphsage top_k=500 fold=9 epoch=47 loss=10.0372 val_auc=0.7911
model=graphsage top_k=500 fold=9 epoch=48 loss=7.6715 val_auc=0.7911
model=graphsage top_k=500 fold=9 epoch=49 loss=6.7160 val_auc=0.7912
model=graphsage top_k=500 fold=9 epoch=50 loss=8.1641 val_auc=0.7915
model=graphsage top_k=500 fold=9 epoch=51 loss=8.2255 val_auc=0.7923
model=graphsage top_k=500 fold=9 epoch=52 loss=6.6854 val_auc=0.7932
model=graphsage top_k=500 fold=9 epoch=53 loss=6.1785 val_auc=0.7944
model=graphsage top_k=500 fold=9 epoch=54 loss=7.8946 val_auc=0.7952
model=graphsage top_k=500 fold=9 epoch=55 loss=7.2048 val_auc=0.7959
model=graphsage top_k=500 fold=9 epoch=56 loss=6.5055 val_auc=0.7962
model=graphsage top_k=500 fold=9 epoch=57 loss=7.8430 val_auc=0.7960
model=graphsage top_k=500 fold=9 epoch=58 loss=7.3799 val_auc=0.7972
model=graphsage top_k=500 fold=9 epoch=59 loss=8.0651 val_auc=0.7988
model=graphsage top_k=500 fold=9 epoch=60 loss=6.2569 val_auc=0.7995
model=graphsage top_k=500 fold=9 epoch=61 loss=6.4139 val_auc=0.8002
model=graphsage top_k=500 fold=9 epoch=62 loss=7.7703 val_auc=0.8008
model=graphsage top_k=500 fold=9 epoch=63 loss=6.5951 val_auc=0.8014
model=graphsage top_k=500 fold=9 epoch=64 loss=6.7567 val_auc=0.8021
model=graphsage top_k=500 fold=9 epoch=65 loss=5.9140 val_auc=0.8027
model=graphsage top_k=500 fold=9 epoch=66 loss=6.5558 val_auc=0.8036
model=graphsage top_k=500 fold=9 epoch=67 loss=5.7100 val_auc=0.8043
model=graphsage top_k=500 fold=9 epoch=68 loss=5.0922 val_auc=0.8051
model=graphsage top_k=500 fold=9 epoch=69 loss=4.5013 val_auc=0.8068
model=graphsage top_k=500 fold=9 epoch=70 loss=5.5296 val_auc=0.8082
model=graphsage top_k=500 fold=9 epoch=71 loss=5.2479 val_auc=0.8095
model=graphsage top_k=500 fold=9 epoch=72 loss=5.1658 val_auc=0.8105
model=graphsage top_k=500 fold=9 epoch=73 loss=4.8900 val_auc=0.8112
model=graphsage top_k=500 fold=9 epoch=74 loss=5.5407 val_auc=0.8116
model=graphsage top_k=500 fold=9 epoch=75 loss=5.3322 val_auc=0.8113
model=graphsage top_k=500 fold=9 epoch=76 loss=5.2839 val_auc=0.8111
model=graphsage top_k=500 fold=9 epoch=77 loss=4.8679 val_auc=0.8111
model=graphsage top_k=500 fold=9 epoch=78 loss=6.0329 val_auc=0.8111
model=graphsage top_k=500 fold=9 epoch=79 loss=5.1823 val_auc=0.8113
model=graphsage top_k=500 fold=9 epoch=80 loss=4.9903 val_auc=0.8116
model=graphsage top_k=500 fold=9 epoch=81 loss=5.0480 val_auc=0.8116
model=graphsage top_k=500 fold=9 epoch=82 loss=6.4172 val_auc=0.8119
model=graphsage top_k=500 fold=9 epoch=83 loss=4.9416 val_auc=0.8119
model=graphsage top_k=500 fold=9 epoch=84 loss=5.1956 val_auc=0.8123
model=graphsage top_k=500 fold=9 epoch=85 loss=4.7293 val_auc=0.8129
model=graphsage top_k=500 fold=9 epoch=86 loss=4.4863 val_auc=0.8137
model=graphsage top_k=500 fold=9 epoch=87 loss=3.4787 val_auc=0.8155
model=graphsage top_k=500 fold=9 epoch=88 loss=4.9854 val_auc=0.8167
model=graphsage top_k=500 fold=9 epoch=89 loss=4.2980 val_auc=0.8175
model=graphsage top_k=500 fold=9 epoch=90 loss=4.5889 val_auc=0.8182
model=graphsage top_k=500 fold=9 epoch=91 loss=3.4704 val_auc=0.8189
model=graphsage top_k=500 fold=9 epoch=92 loss=4.8429 val_auc=0.8191
model=graphsage top_k=500 fold=9 epoch=93 loss=3.7654 val_auc=0.8194
model=graphsage top_k=500 fold=9 epoch=94 loss=3.5574 val_auc=0.8198
model=graphsage top_k=500 fold=9 epoch=95 loss=4.0770 val_auc=0.8203
model=graphsage top_k=500 fold=9 epoch=96 loss=3.6288 val_auc=0.8212
model=graphsage top_k=500 fold=9 epoch=97 loss=3.5718 val_auc=0.8217
model=graphsage top_k=500 fold=9 epoch=98 loss=3.7365 val_auc=0.8220
model=graphsage top_k=500 fold=9 epoch=99 loss=3.5278 val_auc=0.8221

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

######## Model=gcn top_k=50 ########

===== Model=gcn top_k=50 fold=0 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=50 fold=0 epoch=0 loss=203.9427 val_auc=0.5198

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=50 fold=0 epoch=1 loss=75.9199 val_auc=0.5996
model=gcn top_k=50 fold=0 epoch=2 loss=22.7025 val_auc=0.7572
model=gcn top_k=50 fold=0 epoch=3 loss=13.1073 val_auc=0.5000
model=gcn top_k=50 fold=0 epoch=4 loss=47.9238 val_auc=0.5377
model=gcn top_k=50 fold=0 epoch=5 loss=45.4490 val_auc=0.6229

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=50 fold=0 epoch=6 loss=19.0322 val_auc=0.7600
model=gcn top_k=50 fold=0 epoch=7 loss=21.0150 val_auc=0.7560
model=gcn top_k=50 fold=0 epoch=8 loss=14.6400 val_auc=0.6874
model=gcn top_k=50 fold=0 epoch=9 loss=16.6767 val_auc=0.6077
model=gcn top_k=50 fold=0 epoch=10 loss=21.9287 val_auc=0.7204
model=gcn top_k=50 fold=0 epoch=11 loss=14.5617 val_auc=0.7643
model=gcn top_k=50 fold=0 epoch=12 loss=14.7059 val_auc=0.7657
model=gcn top_k=50 fold=0 epoch=13 loss=15.1371 val_auc=0.7597
model=gcn top_k=50 fold=0 epoch=14 loss=12.5566 val_auc=0.7557
model=gcn top_k=50 fold=0 epoch=15 loss=13.2126 val_auc=0.7662
model=gcn top_k=50 fold=0 epoch=16 loss=12.3506 val_auc=0.7699
model=gcn top_k=50 fold=0 epoch=17 loss=13.9392 val_auc=0.7716
model=gcn top_k=50 fold=0 epoch=18 loss=12.6686 val_auc=0.7690
model=gcn top_k=50 fold=0 epoch=19 loss=14.6132 val_auc=0.6659
model=gcn top_k=50 fold=0 epoch=20 loss=17.4444 val_auc=0.6096
model=gcn top_k=50 fold=0 epoch=21 loss=20.3208 val_auc=0.6856
model=gcn top_k=50 fold=0 epoch=22 loss=18.1219 val_auc=0.7667
model=gcn top_k=50 fold=0 epoch=23 loss=11.9192 val_auc=0.7748
model=gcn top_k=50 fold=0 epoch=24 loss=12.9178 val_auc=0.7752
model=gcn top_k=50 fold=0 epoch=25 loss=16.2801 val_auc=0.7755
model=gcn top_k=50 fold=0 epoch=26 loss=11.6951 val_auc=0.7755
model=gcn top_k=50 fold=0 epoch=27 loss=12.3974 val_auc=0.7735
model=gcn top_k=50 fold=0 epoch=28 loss=11.3134 val_auc=0.7747
model=gcn top_k=50 fold=0 epoch=29 loss=12.6701 val_auc=0.7768
model=gcn top_k=50 fold=0 epoch=30 loss=12.6239 val_auc=0.7782
model=gcn top_k=50 fold=0 epoch=31 loss=11.9305 val_auc=0.7790
model=gcn top_k=50 fold=0 epoch=32 loss=10.3190 val_auc=0.7790
model=gcn top_k=50 fold=0 epoch=33 loss=13.4768 val_auc=0.7782
model=gcn top_k=50 fold=0 epoch=34 loss=10.6026 val_auc=0.7751
model=gcn top_k=50 fold=0 epoch=35 loss=11.5306 val_auc=0.7713
model=gcn top_k=50 fold=0 epoch=36 loss=11.2123 val_auc=0.7757
model=gcn top_k=50 fold=0 epoch=37 loss=13.1116 val_auc=0.7809
model=gcn top_k=50 fold=0 epoch=38 loss=10.7528 val_auc=0.7831
model=gcn top_k=50 fold=0 epoch=39 loss=12.7177 val_auc=0.7837
model=gcn top_k=50 fold=0 epoch=40 loss=12.9470 val_auc=0.7842
model=gcn top_k=50 fold=0 epoch=41 loss=12.2322 val_auc=0.7835
model=gcn top_k=50 fold=0 epoch=42 loss=11.3011 val_auc=0.7766
model=gcn top_k=50 fold=0 epoch=43 loss=13.0608 val_auc=0.7691
model=gcn top_k=50 fold=0 epoch=44 loss=14.2527 val_auc=0.7723
model=gcn top_k=50 fold=0 epoch=45 loss=12.5431 val_auc=0.7796
model=gcn top_k=50 fold=0 epoch=46 loss=10.9325 val_auc=0.7815
model=gcn top_k=50 fold=0 epoch=47 loss=11.5280 val_auc=0.7818
model=gcn top_k=50 fold=0 epoch=48 loss=11.8315 val_auc=0.7812
model=gcn top_k=50 fold=0 epoch=49 loss=10.4682 val_auc=0.7817
model=gcn top_k=50 fold=0 epoch=50 loss=9.0519 val_auc=0.7828
model=gcn top_k=50 fold=0 epoch=51 loss=10.6659 val_auc=0.7836
model=gcn top_k=50 fold=0 epoch=52 loss=10.5523 val_auc=0.7844
model=gcn top_k=50 fold=0 epoch=53 loss=10.6170 val_auc=0.7855
model=gcn top_k=50 fold=0 epoch=54 loss=9.5073 val_auc=0.7857
model=gcn top_k=50 fold=0 epoch=55 loss=10.7466 val_auc=0.7843
model=gcn top_k=50 fold=0 epoch=56 loss=9.8029 val_auc=0.7842
model=gcn top_k=50 fold=0 epoch=57 loss=10.5083 val_auc=0.7859
model=gcn top_k=50 fold=0 epoch=58 loss=9.7008 val_auc=0.7855
model=gcn top_k=50 fold=0 epoch=59 loss=9.1126 val_auc=0.7850
model=gcn top_k=50 fold=0 epoch=60 loss=8.7077 val_auc=0.7829
model=gcn top_k=50 fold=0 epoch=61 loss=9.9099 val_auc=0.7828
model=gcn top_k=50 fold=0 epoch=62 loss=10.0921 val_auc=0.7849
model=gcn top_k=50 fold=0 epoch=63 loss=8.6755 val_auc=0.7857
model=gcn top_k=50 fold=0 epoch=64 loss=8.8163 val_auc=0.7850
model=gcn top_k=50 fold=0 epoch=65 loss=11.9494 val_auc=0.7845
model=gcn top_k=50 fold=0 epoch=66 loss=10.0251 val_auc=0.7871
model=gcn top_k=50 fold=0 epoch=67 loss=11.0216 val_auc=0.7882
model=gcn top_k=50 fold=0 epoch=68 loss=8.6145 val_auc=0.7882
model=gcn top_k=50 fold=0 epoch=69 loss=9.5386 val_auc=0.7879
model=gcn top_k=50 fold=0 epoch=70 loss=9.8551 val_auc=0.7860
model=gcn top_k=50 fold=0 epoch=71 loss=8.9704 val_auc=0.7844
model=gcn top_k=50 fold=0 epoch=72 loss=9.7412 val_auc=0.7838
model=gcn top_k=50 fold=0 epoch=73 loss=8.0169 val_auc=0.7878
model=gcn top_k=50 fold=0 epoch=74 loss=9.5404 val_auc=0.7886
model=gcn top_k=50 fold=0 epoch=75 loss=10.8957 val_auc=0.7892
model=gcn top_k=50 fold=0 epoch=76 loss=9.6461 val_auc=0.7894
model=gcn top_k=50 fold=0 epoch=77 loss=10.0261 val_auc=0.7887
model=gcn top_k=50 fold=0 epoch=78 loss=9.8429 val_auc=0.7847
model=gcn top_k=50 fold=0 epoch=79 loss=9.4317 val_auc=0.7874
model=gcn top_k=50 fold=0 epoch=80 loss=10.3216 val_auc=0.7900
model=gcn top_k=50 fold=0 epoch=81 loss=8.1156 val_auc=0.7903
model=gcn top_k=50 fold=0 epoch=82 loss=10.0731 val_auc=0.7905
model=gcn top_k=50 fold=0 epoch=83 loss=8.9611 val_auc=0.7905
model=gcn top_k=50 fold=0 epoch=84 loss=8.9271 val_auc=0.7902
model=gcn top_k=50 fold=0 epoch=85 loss=7.5750 val_auc=0.7856
model=gcn top_k=50 fold=0 epoch=86 loss=9.9269 val_auc=0.7764
model=gcn top_k=50 fold=0 epoch=87 loss=10.9174 val_auc=0.7772
model=gcn top_k=50 fold=0 epoch=88 loss=11.5476 val_auc=0.7873
model=gcn top_k=50 fold=0 epoch=89 loss=9.3521 val_auc=0.7927
model=gcn top_k=50 fold=0 epoch=90 loss=8.2727 val_auc=0.7934
model=gcn top_k=50 fold=0 epoch=91 loss=10.3828 val_auc=0.7938
model=gcn top_k=50 fold=0 epoch=92 loss=11.3972 val_auc=0.7940
model=gcn top_k=50 fold=0 epoch=93 loss=8.1670 val_auc=0.7943
model=gcn top_k=50 fold=0 epoch=94 loss=9.5603 val_auc=0.7932
model=gcn top_k=50 fold=0 epoch=95 loss=9.2429 val_auc=0.7933
model=gcn top_k=50 fold=0 epoch=96 loss=8.7525 val_auc=0.7938
model=gcn top_k=50 fold=0 epoch=97 loss=9.1067 val_auc=0.7937
model=gcn top_k=50 fold=0 epoch=98 loss=8.3413 val_auc=0.7934
model=gcn top_k=50 fold=0 epoch=99 loss=8.5898 val_auc=0.7927

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=50 fold=1 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=50 fold=1 epoch=0 loss=195.6096 val_auc=0.5317
model=gcn top_k=50 fold=1 epoch=1 loss=69.4684 val_auc=0.5817
model=gcn top_k=50 fold=1 epoch=2 loss=22.7364 val_auc=0.7478
model=gcn top_k=50 fold=1 epoch=3 loss=17.3758 val_auc=0.5274
model=gcn top_k=50 fold=1 epoch=4 loss=31.0356 val_auc=0.6355

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=50 fold=1 epoch=5 loss=20.0942 val_auc=0.7695
model=gcn top_k=50 fold=1 epoch=6 loss=17.9079 val_auc=0.7682
model=gcn top_k=50 fold=1 epoch=7 loss=16.2113 val_auc=0.6639
model=gcn top_k=50 fold=1 epoch=8 loss=17.1566 val_auc=0.6816
model=gcn top_k=50 fold=1 epoch=9 loss=16.8800 val_auc=0.7580
model=gcn top_k=50 fold=1 epoch=10 loss=15.7701 val_auc=0.7808
model=gcn top_k=50 fold=1 epoch=11 loss=13.5285 val_auc=0.7827
model=gcn top_k=50 fold=1 epoch=12 loss=15.3948 val_auc=0.7818
model=gcn top_k=50 fold=1 epoch=13 loss=12.8411 val_auc=0.7799
model=gcn top_k=50 fold=1 epoch=14 loss=11.7570 val_auc=0.7751
model=gcn top_k=50 fold=1 epoch=15 loss=12.9471 val_auc=0.7797
model=gcn top_k=50 fold=1 epoch=16 loss=13.9335 val_auc=0.7837
model=gcn top_k=50 fold=1 epoch=17 loss=11.5645 val_auc=0.7827
model=gcn top_k=50 fold=1 epoch=18 loss=13.1132 val_auc=0.7812
model=gcn top_k=50 fold=1 epoch=19 loss=11.6294 val_auc=0.7538
model=gcn top_k=50 fold=1 epoch=20 loss=16.0613 val_auc=0.7540
model=gcn top_k=50 fold=1 epoch=21 loss=12.7041 val_auc=0.7804
model=gcn top_k=50 fold=1 epoch=22 loss=11.1563 val_auc=0.7880
model=gcn top_k=50 fold=1 epoch=23 loss=13.2803 val_auc=0.7906
model=gcn top_k=50 fold=1 epoch=24 loss=13.0192 val_auc=0.7925
model=gcn top_k=50 fold=1 epoch=25 loss=14.6808 val_auc=0.7905
model=gcn top_k=50 fold=1 epoch=26 loss=11.3760 val_auc=0.7794
model=gcn top_k=50 fold=1 epoch=27 loss=14.7083 val_auc=0.7800
model=gcn top_k=50 fold=1 epoch=28 loss=11.8757 val_auc=0.7923
model=gcn top_k=50 fold=1 epoch=29 loss=9.8911 val_auc=0.7951
model=gcn top_k=50 fold=1 epoch=30 loss=12.2755 val_auc=0.7968
model=gcn top_k=50 fold=1 epoch=31 loss=11.7218 val_auc=0.7962
model=gcn top_k=50 fold=1 epoch=32 loss=14.5928 val_auc=0.7959
model=gcn top_k=50 fold=1 epoch=33 loss=10.5517 val_auc=0.7938
model=gcn top_k=50 fold=1 epoch=34 loss=12.6488 val_auc=0.7934
model=gcn top_k=50 fold=1 epoch=35 loss=11.7057 val_auc=0.7969
model=gcn top_k=50 fold=1 epoch=36 loss=11.2382 val_auc=0.7981
model=gcn top_k=50 fold=1 epoch=37 loss=12.8411 val_auc=0.7763
model=gcn top_k=50 fold=1 epoch=38 loss=11.8022 val_auc=0.7704
model=gcn top_k=50 fold=1 epoch=39 loss=15.4601 val_auc=0.7877
model=gcn top_k=50 fold=1 epoch=40 loss=13.0704 val_auc=0.7946
model=gcn top_k=50 fold=1 epoch=41 loss=10.8145 val_auc=0.7980
model=gcn top_k=50 fold=1 epoch=42 loss=12.3160 val_auc=0.7979
model=gcn top_k=50 fold=1 epoch=43 loss=11.6006 val_auc=0.7977
model=gcn top_k=50 fold=1 epoch=44 loss=10.9334 val_auc=0.7948
model=gcn top_k=50 fold=1 epoch=45 loss=9.9249 val_auc=0.7731
model=gcn top_k=50 fold=1 epoch=46 loss=15.5340 val_auc=0.7608
model=gcn top_k=50 fold=1 epoch=47 loss=14.3436 val_auc=0.7733
model=gcn top_k=50 fold=1 epoch=48 loss=12.2996 val_auc=0.7927
gcn top_k=50 fold=1: early stopping at epoch 48

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=50 fold=2 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=gcn top_k=50 fold=2 epoch=0 loss=244.2855 val_auc=0.4896
model=gcn top_k=50 fold=2 epoch=1 loss=109.3817 val_auc=0.5019

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=50 fold=2 epoch=2 loss=45.6565 val_auc=0.6679
model=gcn top_k=50 fold=2 epoch=3 loss=19.2607 val_auc=0.7484
model=gcn top_k=50 fold=2 epoch=4 loss=16.5178 val_auc=0.5821
model=gcn top_k=50 fold=2 epoch=5 loss=18.7068 val_auc=0.5914
model=gcn top_k=50 fold=2 epoch=6 loss=23.5529 val_auc=0.7580
model=gcn top_k=50 fold=2 epoch=7 loss=13.1463 val_auc=0.7744
model=gcn top_k=50 fold=2 epoch=8 loss=17.7250 val_auc=0.7792
model=gcn top_k=50 fold=2 epoch=9 loss=15.1724 val_auc=0.5801
model=gcn top_k=50 fold=2 epoch=10 loss=19.0408 val_auc=0.5450
model=gcn top_k=50 fold=2 epoch=11 loss=24.2219 val_auc=0.5872
model=gcn top_k=50 fold=2 epoch=12 loss=20.8784 val_auc=0.7671
model=gcn top_k=50 fold=2 epoch=13 loss=16.3165 val_auc=0.7727
model=gcn top_k=50 fold=2 epoch=14 loss=18.8163 val_auc=0.7714
model=gcn top_k=50 fold=2 epoch=15 loss=17.1386 val_auc=0.7513
model=gcn top_k=50 fold=2 epoch=16 loss=14.7377 val_auc=0.7228
model=gcn top_k=50 fold=2 epoch=17 loss=17.0909 val_auc=0.6610
model=gcn top_k=50 fold=2 epoch=18 loss=21.4101 val_auc=0.7148
model=gcn top_k=50 fold=2 epoch=19 loss=17.9462 val_auc=0.7673
model=gcn top_k=50 fold=2 epoch=20 loss=16.5790 val_auc=0.7750
gcn top_k=50 fold=2: early stopping at epoch 20

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=50 fold=3 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=50 fold=3 epoch=0 loss=234.3047 val_auc=0.5394
model=gcn top_k=50 fold=3 epoch=1 loss=83.9445 val_auc=0.5624
model=gcn top_k=50 fold=3 epoch=2 loss=22.7997 val_auc=0.7423
model=gcn top_k=50 fold=3 epoch=3 loss=19.8345 val_auc=0.5595
model=gcn top_k=50 fold=3 epoch=4 loss=32.8223 val_auc=0.5857
model=gcn top_k=50 fold=3 epoch=5 loss=20.5666 val_auc=0.7603

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=50 fold=3 epoch=6 loss=18.4345 val_auc=0.7690
model=gcn top_k=50 fold=3 epoch=7 loss=16.7204 val_auc=0.6130
model=gcn top_k=50 fold=3 epoch=8 loss=21.4796 val_auc=0.6829
model=gcn top_k=50 fold=3 epoch=9 loss=16.8304 val_auc=0.7751
model=gcn top_k=50 fold=3 epoch=10 loss=15.8848 val_auc=0.7826
model=gcn top_k=50 fold=3 epoch=11 loss=13.3850 val_auc=0.7792
model=gcn top_k=50 fold=3 epoch=12 loss=13.1564 val_auc=0.7027
model=gcn top_k=50 fold=3 epoch=13 loss=17.4926 val_auc=0.7517
model=gcn top_k=50 fold=3 epoch=14 loss=14.1146 val_auc=0.7806
model=gcn top_k=50 fold=3 epoch=15 loss=11.7582 val_auc=0.7828
model=gcn top_k=50 fold=3 epoch=16 loss=15.2483 val_auc=0.7826
model=gcn top_k=50 fold=3 epoch=17 loss=13.0618 val_auc=0.7818
model=gcn top_k=50 fold=3 epoch=18 loss=11.4163 val_auc=0.7772
model=gcn top_k=50 fold=3 epoch=19 loss=14.3873 val_auc=0.7771
model=gcn top_k=50 fold=3 epoch=20 loss=11.6940 val_auc=0.7826
model=gcn top_k=50 fold=3 epoch=21 loss=13.1752 val_auc=0.7824
model=gcn top_k=50 fold=3 epoch=22 loss=12.4933 val_auc=0.7819
model=gcn top_k=50 fold=3 epoch=23 loss=12.9974 val_auc=0.7804
model=gcn top_k=50 fold=3 epoch=24 loss=11.8874 val_auc=0.7781
model=gcn top_k=50 fold=3 epoch=25 loss=13.9955 val_auc=0.7827
model=gcn top_k=50 fold=3 epoch=26 loss=12.4760 val_auc=0.7854
model=gcn top_k=50 fold=3 epoch=27 loss=13.0794 val_auc=0.7857
model=gcn top_k=50 fold=3 epoch=28 loss=13.8513 val_auc=0.7850
model=gcn top_k=50 fold=3 epoch=29 loss=10.4022 val_auc=0.7848
model=gcn top_k=50 fold=3 epoch=30 loss=10.9472 val_auc=0.7859
model=gcn top_k=50 fold=3 epoch=31 loss=11.4239 val_auc=0.7896
model=gcn top_k=50 fold=3 epoch=32 loss=12.2251 val_auc=0.7915
model=gcn top_k=50 fold=3 epoch=33 loss=10.7623 val_auc=0.7925
model=gcn top_k=50 fold=3 epoch=34 loss=12.6450 val_auc=0.7922
model=gcn top_k=50 fold=3 epoch=35 loss=10.2400 val_auc=0.7935
model=gcn top_k=50 fold=3 epoch=36 loss=10.0443 val_auc=0.7950
model=gcn top_k=50 fold=3 epoch=37 loss=10.3357 val_auc=0.7947
model=gcn top_k=50 fold=3 epoch=38 loss=11.1318 val_auc=0.7946
model=gcn top_k=50 fold=3 epoch=39 loss=12.3608 val_auc=0.7950
model=gcn top_k=50 fold=3 epoch=40 loss=9.8023 val_auc=0.7959
model=gcn top_k=50 fold=3 epoch=41 loss=9.5241 val_auc=0.7963
model=gcn top_k=50 fold=3 epoch=42 loss=10.9105 val_auc=0.7955
model=gcn top_k=50 fold=3 epoch=43 loss=11.9505 val_auc=0.7894
model=gcn top_k=50 fold=3 epoch=44 loss=12.0040 val_auc=0.7819
model=gcn top_k=50 fold=3 epoch=45 loss=12.4045 val_auc=0.7877
model=gcn top_k=50 fold=3 epoch=46 loss=10.9597 val_auc=0.7965
model=gcn top_k=50 fold=3 epoch=47 loss=10.8756 val_auc=0.7974
model=gcn top_k=50 fold=3 epoch=48 loss=10.1789 val_auc=0.7977
model=gcn top_k=50 fold=3 epoch=49 loss=10.4537 val_auc=0.7981
model=gcn top_k=50 fold=3 epoch=50 loss=10.3269 val_auc=0.7985
model=gcn top_k=50 fold=3 epoch=51 loss=10.8226 val_auc=0.7983
model=gcn top_k=50 fold=3 epoch=52 loss=9.0739 val_auc=0.7982
model=gcn top_k=50 fold=3 epoch=53 loss=9.7142 val_auc=0.7991
model=gcn top_k=50 fold=3 epoch=54 loss=9.6213 val_auc=0.7996
model=gcn top_k=50 fold=3 epoch=55 loss=9.9382 val_auc=0.8000
model=gcn top_k=50 fold=3 epoch=56 loss=9.7749 val_auc=0.7982
model=gcn top_k=50 fold=3 epoch=57 loss=13.0290 val_auc=0.7987
model=gcn top_k=50 fold=3 epoch=58 loss=10.7634 val_auc=0.8013
model=gcn top_k=50 fold=3 epoch=59 loss=8.9319 val_auc=0.8017
model=gcn top_k=50 fold=3 epoch=60 loss=13.1050 val_auc=0.8019
model=gcn top_k=50 fold=3 epoch=61 loss=10.9444 val_auc=0.8022
model=gcn top_k=50 fold=3 epoch=62 loss=10.7111 val_auc=0.8012
model=gcn top_k=50 fold=3 epoch=63 loss=9.8889 val_auc=0.8021
model=gcn top_k=50 fold=3 epoch=64 loss=9.7868 val_auc=0.8023
model=gcn top_k=50 fold=3 epoch=65 loss=9.8700 val_auc=0.8026
model=gcn top_k=50 fold=3 epoch=66 loss=8.7649 val_auc=0.8030
model=gcn top_k=50 fold=3 epoch=67 loss=9.5646 val_auc=0.8032
model=gcn top_k=50 fold=3 epoch=68 loss=9.6002 val_auc=0.8027
model=gcn top_k=50 fold=3 epoch=69 loss=8.6928 val_auc=0.8032
model=gcn top_k=50 fold=3 epoch=70 loss=8.6350 val_auc=0.8036
model=gcn top_k=50 fold=3 epoch=71 loss=9.4021 val_auc=0.8037
model=gcn top_k=50 fold=3 epoch=72 loss=9.9253 val_auc=0.8035
model=gcn top_k=50 fold=3 epoch=73 loss=8.6288 val_auc=0.8032
model=gcn top_k=50 fold=3 epoch=74 loss=8.6010 val_auc=0.7982
model=gcn top_k=50 fold=3 epoch=75 loss=11.6314 val_auc=0.7999
model=gcn top_k=50 fold=3 epoch=76 loss=8.9085 val_auc=0.8074
model=gcn top_k=50 fold=3 epoch=77 loss=9.8348 val_auc=0.8093
model=gcn top_k=50 fold=3 epoch=78 loss=10.4321 val_auc=0.8097
model=gcn top_k=50 fold=3 epoch=79 loss=9.2425 val_auc=0.8105
model=gcn top_k=50 fold=3 epoch=80 loss=10.0260 val_auc=0.8102
model=gcn top_k=50 fold=3 epoch=81 loss=8.4584 val_auc=0.8100
model=gcn top_k=50 fold=3 epoch=82 loss=9.7270 val_auc=0.8074
model=gcn top_k=50 fold=3 epoch=83 loss=8.7099 val_auc=0.8071
model=gcn top_k=50 fold=3 epoch=84 loss=8.3037 val_auc=0.8092
model=gcn top_k=50 fold=3 epoch=85 loss=9.3951 val_auc=0.8090
model=gcn top_k=50 fold=3 epoch=86 loss=10.1146 val_auc=0.8084
model=gcn top_k=50 fold=3 epoch=87 loss=7.3318 val_auc=0.8079
model=gcn top_k=50 fold=3 epoch=88 loss=9.5621 val_auc=0.8080
model=gcn top_k=50 fold=3 epoch=89 loss=9.2508 val_auc=0.8087
model=gcn top_k=50 fold=3 epoch=90 loss=7.8230 val_auc=0.8093
model=gcn top_k=50 fold=3 epoch=91 loss=8.5139 val_auc=0.8095
gcn top_k=50 fold=3: early stopping at epoch 91

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=50 fold=4 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=50 fold=4 epoch=0 loss=205.0855 val_auc=0.5161
model=gcn top_k=50 fold=4 epoch=1 loss=74.1198 val_auc=0.5817

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=50 fold=4 epoch=2 loss=22.6916 val_auc=0.7148
model=gcn top_k=50 fold=4 epoch=3 loss=21.4139 val_auc=0.5197
model=gcn top_k=50 fold=4 epoch=4 loss=41.6221 val_auc=0.5549
model=gcn top_k=50 fold=4 epoch=5 loss=26.5749 val_auc=0.7568
model=gcn top_k=50 fold=4 epoch=6 loss=14.0838 val_auc=0.7697
model=gcn top_k=50 fold=4 epoch=7 loss=15.6253 val_auc=0.7616
model=gcn top_k=50 fold=4 epoch=8 loss=16.0087 val_auc=0.5631
model=gcn top_k=50 fold=4 epoch=9 loss=24.4227 val_auc=0.5638
model=gcn top_k=50 fold=4 epoch=10 loss=23.1477 val_auc=0.7305
model=gcn top_k=50 fold=4 epoch=11 loss=17.5387 val_auc=0.7770
model=gcn top_k=50 fold=4 epoch=12 loss=12.7192 val_auc=0.7796
model=gcn top_k=50 fold=4 epoch=13 loss=15.3486 val_auc=0.7799
model=gcn top_k=50 fold=4 epoch=14 loss=14.4554 val_auc=0.7802
model=gcn top_k=50 fold=4 epoch=15 loss=13.1239 val_auc=0.7807
model=gcn top_k=50 fold=4 epoch=16 loss=14.1042 val_auc=0.7815
model=gcn top_k=50 fold=4 epoch=17 loss=14.3309 val_auc=0.7815
model=gcn top_k=50 fold=4 epoch=18 loss=12.0890 val_auc=0.7793
model=gcn top_k=50 fold=4 epoch=19 loss=13.0234 val_auc=0.7241
model=gcn top_k=50 fold=4 epoch=20 loss=16.9146 val_auc=0.6805
model=gcn top_k=50 fold=4 epoch=21 loss=19.1797 val_auc=0.7300
model=gcn top_k=50 fold=4 epoch=22 loss=18.6597 val_auc=0.7748
model=gcn top_k=50 fold=4 epoch=23 loss=14.1203 val_auc=0.7809
model=gcn top_k=50 fold=4 epoch=24 loss=13.4843 val_auc=0.7810
model=gcn top_k=50 fold=4 epoch=25 loss=15.3308 val_auc=0.7817
model=gcn top_k=50 fold=4 epoch=26 loss=13.1878 val_auc=0.7817
model=gcn top_k=50 fold=4 epoch=27 loss=10.6404 val_auc=0.7674
model=gcn top_k=50 fold=4 epoch=28 loss=12.8365 val_auc=0.7366
model=gcn top_k=50 fold=4 epoch=29 loss=11.8006 val_auc=0.7454
model=gcn top_k=50 fold=4 epoch=30 loss=14.1458 val_auc=0.7756
model=gcn top_k=50 fold=4 epoch=31 loss=12.2624 val_auc=0.7855
model=gcn top_k=50 fold=4 epoch=32 loss=12.1518 val_auc=0.7862
model=gcn top_k=50 fold=4 epoch=33 loss=11.1826 val_auc=0.7876
model=gcn top_k=50 fold=4 epoch=34 loss=13.1262 val_auc=0.7882
model=gcn top_k=50 fold=4 epoch=35 loss=12.4470 val_auc=0.7883
model=gcn top_k=50 fold=4 epoch=36 loss=10.3164 val_auc=0.7840
model=gcn top_k=50 fold=4 epoch=37 loss=12.4362 val_auc=0.7777
model=gcn top_k=50 fold=4 epoch=38 loss=13.2543 val_auc=0.7832
model=gcn top_k=50 fold=4 epoch=39 loss=12.0462 val_auc=0.7873
model=gcn top_k=50 fold=4 epoch=40 loss=11.7237 val_auc=0.7875
model=gcn top_k=50 fold=4 epoch=41 loss=11.3655 val_auc=0.7855
model=gcn top_k=50 fold=4 epoch=42 loss=11.4587 val_auc=0.7844
model=gcn top_k=50 fold=4 epoch=43 loss=10.5701 val_auc=0.7870
model=gcn top_k=50 fold=4 epoch=44 loss=9.8046 val_auc=0.7883
model=gcn top_k=50 fold=4 epoch=45 loss=12.2734 val_auc=0.7880
model=gcn top_k=50 fold=4 epoch=46 loss=10.5352 val_auc=0.7830
model=gcn top_k=50 fold=4 epoch=47 loss=13.1697 val_auc=0.7826
gcn top_k=50 fold=4: early stopping at epoch 47

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=50 fold=5 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=gcn top_k=50 fold=5 epoch=0 loss=181.9342 val_auc=0.5143
model=gcn top_k=50 fold=5 epoch=1 loss=77.8568 val_auc=0.5609
model=gcn top_k=50 fold=5 epoch=2 loss=17.6794 val_auc=0.6976
model=gcn top_k=50 fold=5 epoch=3 loss=22.7802 val_auc=0.5035
model=gcn top_k=50 fold=5 epoch=4 loss=29.5350 val_auc=0.5518

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=50 fold=5 epoch=5 loss=23.5287 val_auc=0.7763
model=gcn top_k=50 fold=5 epoch=6 loss=17.6686 val_auc=0.7752
model=gcn top_k=50 fold=5 epoch=7 loss=25.7247 val_auc=0.7688
model=gcn top_k=50 fold=5 epoch=8 loss=15.8494 val_auc=0.6932
model=gcn top_k=50 fold=5 epoch=9 loss=17.1199 val_auc=0.6257
model=gcn top_k=50 fold=5 epoch=10 loss=16.8191 val_auc=0.7326
model=gcn top_k=50 fold=5 epoch=11 loss=15.5752 val_auc=0.7734
model=gcn top_k=50 fold=5 epoch=12 loss=15.2629 val_auc=0.7777
model=gcn top_k=50 fold=5 epoch=13 loss=17.2959 val_auc=0.7794
model=gcn top_k=50 fold=5 epoch=14 loss=12.8950 val_auc=0.7798
model=gcn top_k=50 fold=5 epoch=15 loss=14.0941 val_auc=0.7514
model=gcn top_k=50 fold=5 epoch=16 loss=13.8313 val_auc=0.7552
model=gcn top_k=50 fold=5 epoch=17 loss=12.4056 val_auc=0.7790
model=gcn top_k=50 fold=5 epoch=18 loss=12.7966 val_auc=0.7807
model=gcn top_k=50 fold=5 epoch=19 loss=14.2669 val_auc=0.7676
model=gcn top_k=50 fold=5 epoch=20 loss=15.0368 val_auc=0.7686
model=gcn top_k=50 fold=5 epoch=21 loss=15.4789 val_auc=0.7795
model=gcn top_k=50 fold=5 epoch=22 loss=13.2420 val_auc=0.7836
model=gcn top_k=50 fold=5 epoch=23 loss=13.9544 val_auc=0.7833
model=gcn top_k=50 fold=5 epoch=24 loss=12.4918 val_auc=0.7830
model=gcn top_k=50 fold=5 epoch=25 loss=11.3864 val_auc=0.7792
model=gcn top_k=50 fold=5 epoch=26 loss=12.4312 val_auc=0.7784
model=gcn top_k=50 fold=5 epoch=27 loss=13.5325 val_auc=0.7796
model=gcn top_k=50 fold=5 epoch=28 loss=11.6969 val_auc=0.7842
model=gcn top_k=50 fold=5 epoch=29 loss=9.2652 val_auc=0.7870
model=gcn top_k=50 fold=5 epoch=30 loss=10.6072 val_auc=0.7891
model=gcn top_k=50 fold=5 epoch=31 loss=15.4182 val_auc=0.7881
model=gcn top_k=50 fold=5 epoch=32 loss=12.1687 val_auc=0.7895
model=gcn top_k=50 fold=5 epoch=33 loss=10.5146 val_auc=0.7904
model=gcn top_k=50 fold=5 epoch=34 loss=12.1926 val_auc=0.7908
model=gcn top_k=50 fold=5 epoch=35 loss=12.3928 val_auc=0.7914
model=gcn top_k=50 fold=5 epoch=36 loss=10.7577 val_auc=0.7813
model=gcn top_k=50 fold=5 epoch=37 loss=14.4053 val_auc=0.7690
model=gcn top_k=50 fold=5 epoch=38 loss=12.1551 val_auc=0.7853
model=gcn top_k=50 fold=5 epoch=39 loss=11.8540 val_auc=0.7945
model=gcn top_k=50 fold=5 epoch=40 loss=11.4948 val_auc=0.7943
model=gcn top_k=50 fold=5 epoch=41 loss=11.2773 val_auc=0.7943
model=gcn top_k=50 fold=5 epoch=42 loss=13.1795 val_auc=0.7944
model=gcn top_k=50 fold=5 epoch=43 loss=13.0307 val_auc=0.7948
model=gcn top_k=50 fold=5 epoch=44 loss=13.4988 val_auc=0.7897
model=gcn top_k=50 fold=5 epoch=45 loss=12.7951 val_auc=0.7863
model=gcn top_k=50 fold=5 epoch=46 loss=12.7337 val_auc=0.7902
model=gcn top_k=50 fold=5 epoch=47 loss=10.1661 val_auc=0.7936
model=gcn top_k=50 fold=5 epoch=48 loss=9.7384 val_auc=0.7930
model=gcn top_k=50 fold=5 epoch=49 loss=11.5954 val_auc=0.7932
model=gcn top_k=50 fold=5 epoch=50 loss=11.5632 val_auc=0.7931
model=gcn top_k=50 fold=5 epoch=51 loss=10.6965 val_auc=0.7920
model=gcn top_k=50 fold=5 epoch=52 loss=11.6111 val_auc=0.7838
model=gcn top_k=50 fold=5 epoch=53 loss=16.6011 val_auc=0.7820
model=gcn top_k=50 fold=5 epoch=54 loss=11.2909 val_auc=0.7908
model=gcn top_k=50 fold=5 epoch=55 loss=9.0619 val_auc=0.7947
gcn top_k=50 fold=5: early stopping at epoch 55

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=50 fold=6 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=50 fold=6 epoch=0 loss=263.5677 val_auc=0.5072
model=gcn top_k=50 fold=6 epoch=1 loss=88.4220 val_auc=0.5540
model=gcn top_k=50 fold=6 epoch=2 loss=24.1914 val_auc=0.7440
model=gcn top_k=50 fold=6 epoch=3 loss=24.4616 val_auc=0.5888
model=gcn top_k=50 fold=6 epoch=4 loss=15.7705 val_auc=0.7437
model=gcn top_k=50 fold=6 epoch=5 loss=16.2738 val_auc=0.7064
model=gcn top_k=50 fold=6 epoch=6 loss=21.1579 val_auc=0.7623
model=gcn top_k=50 fold=6 epoch=7 loss=22.3028 val_auc=0.7762
model=gcn top_k=50 fold=6 epoch=8 loss=12.7181 val_auc=0.7497
model=gcn top_k=50 fold=6 epoch=9 loss=17.0721 val_auc=0.7823
model=gcn top_k=50 fold=6 epoch=10 loss=14.5811 val_auc=0.7844
model=gcn top_k=50 fold=6 epoch=11 loss=14.2999 val_auc=0.7163
model=gcn top_k=50 fold=6 epoch=12 loss=15.5522 val_auc=0.7006
model=gcn top_k=50 fold=6 epoch=13 loss=20.7199 val_auc=0.7531
model=gcn top_k=50 fold=6 epoch=14 loss=16.0956 val_auc=0.7906
model=gcn top_k=50 fold=6 epoch=15 loss=12.0071 val_auc=0.7882
model=gcn top_k=50 fold=6 epoch=16 loss=12.1515 val_auc=0.7518
model=gcn top_k=50 fold=6 epoch=17 loss=13.1463 val_auc=0.7440
model=gcn top_k=50 fold=6 epoch=18 loss=18.1639 val_auc=0.7818
model=gcn top_k=50 fold=6 epoch=19 loss=13.3288 val_auc=0.7890
model=gcn top_k=50 fold=6 epoch=20 loss=14.1202 val_auc=0.7671
model=gcn top_k=50 fold=6 epoch=21 loss=12.9684 val_auc=0.7293
model=gcn top_k=50 fold=6 epoch=22 loss=15.8420 val_auc=0.7639
model=gcn top_k=50 fold=6 epoch=23 loss=16.7283 val_auc=0.7950
model=gcn top_k=50 fold=6 epoch=24 loss=11.0736 val_auc=0.7982
model=gcn top_k=50 fold=6 epoch=25 loss=11.1493 val_auc=0.7983
model=gcn top_k=50 fold=6 epoch=26 loss=12.1011 val_auc=0.7988
model=gcn top_k=50 fold=6 epoch=27 loss=11.4879 val_auc=0.7961
model=gcn top_k=50 fold=6 epoch=28 loss=13.0653 val_auc=0.7825
model=gcn top_k=50 fold=6 epoch=29 loss=13.6808 val_auc=0.7919
model=gcn top_k=50 fold=6 epoch=30 loss=12.4653 val_auc=0.8005
model=gcn top_k=50 fold=6 epoch=31 loss=10.6574 val_auc=0.8018
model=gcn top_k=50 fold=6 epoch=32 loss=13.0531 val_auc=0.8023
model=gcn top_k=50 fold=6 epoch=33 loss=12.4456 val_auc=0.8024
model=gcn top_k=50 fold=6 epoch=34 loss=13.9497 val_auc=0.8022
model=gcn top_k=50 fold=6 epoch=35 loss=11.3379 val_auc=0.8009
model=gcn top_k=50 fold=6 epoch=36 loss=10.5838 val_auc=0.7997
model=gcn top_k=50 fold=6 epoch=37 loss=11.6623 val_auc=0.8005
model=gcn top_k=50 fold=6 epoch=38 loss=10.2221 val_auc=0.8010
model=gcn top_k=50 fold=6 epoch=39 loss=9.5922 val_auc=0.8012
model=gcn top_k=50 fold=6 epoch=40 loss=10.6208 val_auc=0.8011
model=gcn top_k=50 fold=6 epoch=41 loss=11.0843 val_auc=0.8007
model=gcn top_k=50 fold=6 epoch=42 loss=10.6153 val_auc=0.8018
model=gcn top_k=50 fold=6 epoch=43 loss=10.8130 val_auc=0.8034
model=gcn top_k=50 fold=6 epoch=44 loss=11.5875 val_auc=0.8040
model=gcn top_k=50 fold=6 epoch=45 loss=10.4204 val_auc=0.8034
model=gcn top_k=50 fold=6 epoch=46 loss=9.5600 val_auc=0.7987
model=gcn top_k=50 fold=6 epoch=47 loss=11.3636 val_auc=0.7947
model=gcn top_k=50 fold=6 epoch=48 loss=11.4971 val_auc=0.8002
model=gcn top_k=50 fold=6 epoch=49 loss=10.3260 val_auc=0.8055
model=gcn top_k=50 fold=6 epoch=50 loss=9.4119 val_auc=0.8059
model=gcn top_k=50 fold=6 epoch=51 loss=13.3562 val_auc=0.8057
model=gcn top_k=50 fold=6 epoch=52 loss=15.5789 val_auc=0.8055
model=gcn top_k=50 fold=6 epoch=53 loss=11.8808 val_auc=0.8052
model=gcn top_k=50 fold=6 epoch=54 loss=9.4167 val_auc=0.8028
model=gcn top_k=50 fold=6 epoch=55 loss=9.2937 val_auc=0.8000
model=gcn top_k=50 fold=6 epoch=56 loss=12.4973 val_auc=0.8053
model=gcn top_k=50 fold=6 epoch=57 loss=8.8024 val_auc=0.8067
model=gcn top_k=50 fold=6 epoch=58 loss=9.3771 val_auc=0.8073
model=gcn top_k=50 fold=6 epoch=59 loss=9.4154 val_auc=0.8075
model=gcn top_k=50 fold=6 epoch=60 loss=9.3980 val_auc=0.8067
model=gcn top_k=50 fold=6 epoch=61 loss=10.6327 val_auc=0.8051
model=gcn top_k=50 fold=6 epoch=62 loss=11.0104 val_auc=0.8101
model=gcn top_k=50 fold=6 epoch=63 loss=10.1905 val_auc=0.8117
model=gcn top_k=50 fold=6 epoch=64 loss=12.8475 val_auc=0.8117
model=gcn top_k=50 fold=6 epoch=65 loss=10.1021 val_auc=0.8121
model=gcn top_k=50 fold=6 epoch=66 loss=9.6657 val_auc=0.8115
model=gcn top_k=50 fold=6 epoch=67 loss=9.6834 val_auc=0.8104
model=gcn top_k=50 fold=6 epoch=68 loss=11.5334 val_auc=0.8100
model=gcn top_k=50 fold=6 epoch=69 loss=9.2238 val_auc=0.8091
model=gcn top_k=50 fold=6 epoch=70 loss=10.4197 val_auc=0.8093
model=gcn top_k=50 fold=6 epoch=71 loss=8.5886 val_auc=0.8094
model=gcn top_k=50 fold=6 epoch=72 loss=8.5239 val_auc=0.8105
model=gcn top_k=50 fold=6 epoch=73 loss=9.0704 val_auc=0.8115
model=gcn top_k=50 fold=6 epoch=74 loss=11.0720 val_auc=0.8123
model=gcn top_k=50 fold=6 epoch=75 loss=10.5051 val_auc=0.8124
model=gcn top_k=50 fold=6 epoch=76 loss=8.6489 val_auc=0.8079
model=gcn top_k=50 fold=6 epoch=77 loss=8.3892 val_auc=0.8027
model=gcn top_k=50 fold=6 epoch=78 loss=12.2145 val_auc=0.8076
model=gcn top_k=50 fold=6 epoch=79 loss=10.1925 val_auc=0.8150
model=gcn top_k=50 fold=6 epoch=80 loss=9.3364 val_auc=0.8161
model=gcn top_k=50 fold=6 epoch=81 loss=11.9917 val_auc=0.8159
model=gcn top_k=50 fold=6 epoch=82 loss=10.1741 val_auc=0.8133
model=gcn top_k=50 fold=6 epoch=83 loss=12.6298 val_auc=0.8115
model=gcn top_k=50 fold=6 epoch=84 loss=12.6268 val_auc=0.8133
model=gcn top_k=50 fold=6 epoch=85 loss=8.8804 val_auc=0.8133
model=gcn top_k=50 fold=6 epoch=86 loss=10.0058 val_auc=0.8126
model=gcn top_k=50 fold=6 epoch=87 loss=9.0439 val_auc=0.8121
model=gcn top_k=50 fold=6 epoch=88 loss=9.7726 val_auc=0.8106
model=gcn top_k=50 fold=6 epoch=89 loss=9.0942 val_auc=0.8046
model=gcn top_k=50 fold=6 epoch=90 loss=10.2210 val_auc=0.8005
model=gcn top_k=50 fold=6 epoch=91 loss=10.3812 val_auc=0.8074
model=gcn top_k=50 fold=6 epoch=92 loss=9.9521 val_auc=0.8126
gcn top_k=50 fold=6: early stopping at epoch 92

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=50 fold=7 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=50 fold=7 epoch=0 loss=208.8022 val_auc=0.5256

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=50 fold=7 epoch=1 loss=66.8688 val_auc=0.5378
model=gcn top_k=50 fold=7 epoch=2 loss=31.0370 val_auc=0.7315
model=gcn top_k=50 fold=7 epoch=3 loss=15.9665 val_auc=0.5000
model=gcn top_k=50 fold=7 epoch=4 loss=43.0984 val_auc=0.5000
model=gcn top_k=50 fold=7 epoch=5 loss=34.8901 val_auc=0.6694
model=gcn top_k=50 fold=7 epoch=6 loss=14.5649 val_auc=0.7630
model=gcn top_k=50 fold=7 epoch=7 loss=14.4428 val_auc=0.7615
model=gcn top_k=50 fold=7 epoch=8 loss=13.7124 val_auc=0.6871
model=gcn top_k=50 fold=7 epoch=9 loss=14.6038 val_auc=0.7502
model=gcn top_k=50 fold=7 epoch=10 loss=15.5692 val_auc=0.7800
model=gcn top_k=50 fold=7 epoch=11 loss=15.5980 val_auc=0.7821
model=gcn top_k=50 fold=7 epoch=12 loss=12.4115 val_auc=0.7802
model=gcn top_k=50 fold=7 epoch=13 loss=13.1933 val_auc=0.7582
model=gcn top_k=50 fold=7 epoch=14 loss=15.6578 val_auc=0.7587
model=gcn top_k=50 fold=7 epoch=15 loss=13.0423 val_auc=0.7840
model=gcn top_k=50 fold=7 epoch=16 loss=12.4730 val_auc=0.7843
model=gcn top_k=50 fold=7 epoch=17 loss=12.9039 val_auc=0.7844
model=gcn top_k=50 fold=7 epoch=18 loss=12.0960 val_auc=0.7859
model=gcn top_k=50 fold=7 epoch=19 loss=11.4212 val_auc=0.7867
model=gcn top_k=50 fold=7 epoch=20 loss=16.6598 val_auc=0.7878
model=gcn top_k=50 fold=7 epoch=21 loss=12.6458 val_auc=0.7870
model=gcn top_k=50 fold=7 epoch=22 loss=13.5337 val_auc=0.7857
model=gcn top_k=50 fold=7 epoch=23 loss=12.2198 val_auc=0.7866
model=gcn top_k=50 fold=7 epoch=24 loss=11.7424 val_auc=0.7874
model=gcn top_k=50 fold=7 epoch=25 loss=11.8122 val_auc=0.7872
model=gcn top_k=50 fold=7 epoch=26 loss=13.3997 val_auc=0.7684
model=gcn top_k=50 fold=7 epoch=27 loss=12.9153 val_auc=0.7677
model=gcn top_k=50 fold=7 epoch=28 loss=12.7449 val_auc=0.7870
model=gcn top_k=50 fold=7 epoch=29 loss=13.2987 val_auc=0.7877
model=gcn top_k=50 fold=7 epoch=30 loss=11.9919 val_auc=0.7860
model=gcn top_k=50 fold=7 epoch=31 loss=10.8405 val_auc=0.7890
model=gcn top_k=50 fold=7 epoch=32 loss=12.8180 val_auc=0.7918
model=gcn top_k=50 fold=7 epoch=33 loss=12.6891 val_auc=0.7942
model=gcn top_k=50 fold=7 epoch=34 loss=11.0580 val_auc=0.7883
model=gcn top_k=50 fold=7 epoch=35 loss=13.0748 val_auc=0.7769
model=gcn top_k=50 fold=7 epoch=36 loss=13.3979 val_auc=0.7872
model=gcn top_k=50 fold=7 epoch=37 loss=15.3530 val_auc=0.7930
model=gcn top_k=50 fold=7 epoch=38 loss=11.0020 val_auc=0.7935
model=gcn top_k=50 fold=7 epoch=39 loss=10.2301 val_auc=0.7936
model=gcn top_k=50 fold=7 epoch=40 loss=10.4992 val_auc=0.7942
model=gcn top_k=50 fold=7 epoch=41 loss=11.5880 val_auc=0.7947
model=gcn top_k=50 fold=7 epoch=42 loss=9.8294 val_auc=0.7951
model=gcn top_k=50 fold=7 epoch=43 loss=10.1515 val_auc=0.7926
model=gcn top_k=50 fold=7 epoch=44 loss=10.9492 val_auc=0.7917
model=gcn top_k=50 fold=7 epoch=45 loss=13.4336 val_auc=0.7959
model=gcn top_k=50 fold=7 epoch=46 loss=10.0949 val_auc=0.7999
model=gcn top_k=50 fold=7 epoch=47 loss=10.6208 val_auc=0.8015
model=gcn top_k=50 fold=7 epoch=48 loss=11.9184 val_auc=0.8022
model=gcn top_k=50 fold=7 epoch=49 loss=10.4787 val_auc=0.8026
model=gcn top_k=50 fold=7 epoch=50 loss=9.2412 val_auc=0.8019
model=gcn top_k=50 fold=7 epoch=51 loss=10.5238 val_auc=0.8005
model=gcn top_k=50 fold=7 epoch=52 loss=12.5336 val_auc=0.8016
model=gcn top_k=50 fold=7 epoch=53 loss=10.6908 val_auc=0.8020
model=gcn top_k=50 fold=7 epoch=54 loss=10.1186 val_auc=0.8019
model=gcn top_k=50 fold=7 epoch=55 loss=8.9216 val_auc=0.8015
model=gcn top_k=50 fold=7 epoch=56 loss=14.1768 val_auc=0.8006
model=gcn top_k=50 fold=7 epoch=57 loss=9.5808 val_auc=0.8001
model=gcn top_k=50 fold=7 epoch=58 loss=9.8589 val_auc=0.8008
model=gcn top_k=50 fold=7 epoch=59 loss=11.1173 val_auc=0.8014
model=gcn top_k=50 fold=7 epoch=60 loss=9.4362 val_auc=0.8023
model=gcn top_k=50 fold=7 epoch=61 loss=8.4128 val_auc=0.8043
model=gcn top_k=50 fold=7 epoch=62 loss=9.2633 val_auc=0.8047
model=gcn top_k=50 fold=7 epoch=63 loss=9.5928 val_auc=0.8053
model=gcn top_k=50 fold=7 epoch=64 loss=10.7075 val_auc=0.8055
model=gcn top_k=50 fold=7 epoch=65 loss=9.6249 val_auc=0.8058
model=gcn top_k=50 fold=7 epoch=66 loss=8.9326 val_auc=0.8066
model=gcn top_k=50 fold=7 epoch=67 loss=9.5629 val_auc=0.8076
model=gcn top_k=50 fold=7 epoch=68 loss=9.5682 val_auc=0.8078
model=gcn top_k=50 fold=7 epoch=69 loss=11.5581 val_auc=0.8077
model=gcn top_k=50 fold=7 epoch=70 loss=9.0781 val_auc=0.8081
model=gcn top_k=50 fold=7 epoch=71 loss=9.3755 val_auc=0.8076
model=gcn top_k=50 fold=7 epoch=72 loss=9.1369 val_auc=0.8064
model=gcn top_k=50 fold=7 epoch=73 loss=10.0421 val_auc=0.8056
model=gcn top_k=50 fold=7 epoch=74 loss=10.1437 val_auc=0.8046
model=gcn top_k=50 fold=7 epoch=75 loss=8.9471 val_auc=0.8036
model=gcn top_k=50 fold=7 epoch=76 loss=9.4148 val_auc=0.8042
model=gcn top_k=50 fold=7 epoch=77 loss=9.3665 val_auc=0.8043
model=gcn top_k=50 fold=7 epoch=78 loss=7.7615 val_auc=0.8011
model=gcn top_k=50 fold=7 epoch=79 loss=11.8249 val_auc=0.7992
model=gcn top_k=50 fold=7 epoch=80 loss=10.6727 val_auc=0.8068
model=gcn top_k=50 fold=7 epoch=81 loss=10.0452 val_auc=0.8091
model=gcn top_k=50 fold=7 epoch=82 loss=11.8990 val_auc=0.8118
model=gcn top_k=50 fold=7 epoch=83 loss=9.9517 val_auc=0.8122
model=gcn top_k=50 fold=7 epoch=84 loss=10.1672 val_auc=0.8091
model=gcn top_k=50 fold=7 epoch=85 loss=8.8022 val_auc=0.8076
model=gcn top_k=50 fold=7 epoch=86 loss=9.8102 val_auc=0.8102
model=gcn top_k=50 fold=7 epoch=87 loss=10.1447 val_auc=0.8123
model=gcn top_k=50 fold=7 epoch=88 loss=9.9118 val_auc=0.8119
model=gcn top_k=50 fold=7 epoch=89 loss=8.1329 val_auc=0.8111
model=gcn top_k=50 fold=7 epoch=90 loss=8.6424 val_auc=0.8088
model=gcn top_k=50 fold=7 epoch=91 loss=12.0414 val_auc=0.8080
model=gcn top_k=50 fold=7 epoch=92 loss=10.4122 val_auc=0.8061
model=gcn top_k=50 fold=7 epoch=93 loss=8.9633 val_auc=0.8013
model=gcn top_k=50 fold=7 epoch=94 loss=8.7309 val_auc=0.7946
model=gcn top_k=50 fold=7 epoch=95 loss=10.2414 val_auc=0.7950
model=gcn top_k=50 fold=7 epoch=96 loss=10.4087 val_auc=0.8021
model=gcn top_k=50 fold=7 epoch=97 loss=9.4699 val_auc=0.8067
model=gcn top_k=50 fold=7 epoch=98 loss=8.9749 val_auc=0.8078
model=gcn top_k=50 fold=7 epoch=99 loss=8.7050 val_auc=0.8086
gcn top_k=50 fold=7: early stopping at epoch 99

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=50 fold=8 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=50 fold=8 epoch=0 loss=271.8868 val_auc=0.5102
model=gcn top_k=50 fold=8 epoch=1 loss=102.2249 val_auc=0.5162
model=gcn top_k=50 fold=8 epoch=2 loss=35.1411 val_auc=0.6636
model=gcn top_k=50 fold=8 epoch=3 loss=18.1715 val_auc=0.5361
model=gcn top_k=50 fold=8 epoch=4 loss=31.1376 val_auc=0.6013
model=gcn top_k=50 fold=8 epoch=5 loss=21.6184 val_auc=0.7537
model=gcn top_k=50 fold=8 epoch=6 loss=20.6709 val_auc=0.7603
model=gcn top_k=50 fold=8 epoch=7 loss=17.1990 val_auc=0.7339
model=gcn top_k=50 fold=8 epoch=8 loss=19.2717 val_auc=0.7354
model=gcn top_k=50 fold=8 epoch=9 loss=16.9582 val_auc=0.7603
model=gcn top_k=50 fold=8 epoch=10 loss=13.4692 val_auc=0.7631
model=gcn top_k=50 fold=8 epoch=11 loss=17.6745 val_auc=0.7636
model=gcn top_k=50 fold=8 epoch=12 loss=14.2070 val_auc=0.7623
model=gcn top_k=50 fold=8 epoch=13 loss=11.9675 val_auc=0.7419
model=gcn top_k=50 fold=8 epoch=14 loss=14.2343 val_auc=0.7428
model=gcn top_k=50 fold=8 epoch=15 loss=14.8781 val_auc=0.7637
model=gcn top_k=50 fold=8 epoch=16 loss=14.7996 val_auc=0.7643
model=gcn top_k=50 fold=8 epoch=17 loss=13.7389 val_auc=0.7480
model=gcn top_k=50 fold=8 epoch=18 loss=14.6336 val_auc=0.7409
model=gcn top_k=50 fold=8 epoch=19 loss=15.4183 val_auc=0.7530
model=gcn top_k=50 fold=8 epoch=20 loss=11.3738 val_auc=0.7679
model=gcn top_k=50 fold=8 epoch=21 loss=12.2996 val_auc=0.7691
model=gcn top_k=50 fold=8 epoch=22 loss=14.2616 val_auc=0.7686
model=gcn top_k=50 fold=8 epoch=23 loss=13.5211 val_auc=0.7654
model=gcn top_k=50 fold=8 epoch=24 loss=11.3344 val_auc=0.7685
model=gcn top_k=50 fold=8 epoch=25 loss=14.2817 val_auc=0.7733
model=gcn top_k=50 fold=8 epoch=26 loss=12.6448 val_auc=0.7744
model=gcn top_k=50 fold=8 epoch=27 loss=11.9807 val_auc=0.7753
model=gcn top_k=50 fold=8 epoch=28 loss=10.6927 val_auc=0.7755
model=gcn top_k=50 fold=8 epoch=29 loss=10.6336 val_auc=0.7718
model=gcn top_k=50 fold=8 epoch=30 loss=13.0374 val_auc=0.7645
model=gcn top_k=50 fold=8 epoch=31 loss=14.6415 val_auc=0.7724
model=gcn top_k=50 fold=8 epoch=32 loss=14.4315 val_auc=0.7758
model=gcn top_k=50 fold=8 epoch=33 loss=11.3165 val_auc=0.7759
model=gcn top_k=50 fold=8 epoch=34 loss=12.3516 val_auc=0.7750
model=gcn top_k=50 fold=8 epoch=35 loss=11.1367 val_auc=0.7727
model=gcn top_k=50 fold=8 epoch=36 loss=12.1540 val_auc=0.7679
model=gcn top_k=50 fold=8 epoch=37 loss=12.4631 val_auc=0.7685
model=gcn top_k=50 fold=8 epoch=38 loss=12.1804 val_auc=0.7736
model=gcn top_k=50 fold=8 epoch=39 loss=11.5026 val_auc=0.7750
model=gcn top_k=50 fold=8 epoch=40 loss=10.6793 val_auc=0.7751
model=gcn top_k=50 fold=8 epoch=41 loss=11.5662 val_auc=0.7751
model=gcn top_k=50 fold=8 epoch=42 loss=9.9002 val_auc=0.7768
model=gcn top_k=50 fold=8 epoch=43 loss=11.0782 val_auc=0.7763
model=gcn top_k=50 fold=8 epoch=44 loss=10.6040 val_auc=0.7752
model=gcn top_k=50 fold=8 epoch=45 loss=11.2812 val_auc=0.7752
model=gcn top_k=50 fold=8 epoch=46 loss=10.9276 val_auc=0.7779
model=gcn top_k=50 fold=8 epoch=47 loss=9.9303 val_auc=0.7799
model=gcn top_k=50 fold=8 epoch=48 loss=10.6498 val_auc=0.7806
model=gcn top_k=50 fold=8 epoch=49 loss=11.8784 val_auc=0.7812
model=gcn top_k=50 fold=8 epoch=50 loss=12.4513 val_auc=0.7808
model=gcn top_k=50 fold=8 epoch=51 loss=11.1491 val_auc=0.7819
model=gcn top_k=50 fold=8 epoch=52 loss=11.5576 val_auc=0.7816
model=gcn top_k=50 fold=8 epoch=53 loss=9.7206 val_auc=0.7822
model=gcn top_k=50 fold=8 epoch=54 loss=10.9342 val_auc=0.7830
model=gcn top_k=50 fold=8 epoch=55 loss=10.4276 val_auc=0.7830
model=gcn top_k=50 fold=8 epoch=56 loss=10.6857 val_auc=0.7827
model=gcn top_k=50 fold=8 epoch=57 loss=9.8639 val_auc=0.7825
model=gcn top_k=50 fold=8 epoch=58 loss=10.6708 val_auc=0.7821
model=gcn top_k=50 fold=8 epoch=59 loss=9.6792 val_auc=0.7815
model=gcn top_k=50 fold=8 epoch=60 loss=10.4109 val_auc=0.7831
model=gcn top_k=50 fold=8 epoch=61 loss=10.1323 val_auc=0.7842
model=gcn top_k=50 fold=8 epoch=62 loss=8.7676 val_auc=0.7848
model=gcn top_k=50 fold=8 epoch=63 loss=11.1548 val_auc=0.7840
model=gcn top_k=50 fold=8 epoch=64 loss=10.3863 val_auc=0.7841
model=gcn top_k=50 fold=8 epoch=65 loss=12.3357 val_auc=0.7857
model=gcn top_k=50 fold=8 epoch=66 loss=8.8056 val_auc=0.7862
model=gcn top_k=50 fold=8 epoch=67 loss=9.7438 val_auc=0.7868
model=gcn top_k=50 fold=8 epoch=68 loss=9.1758 val_auc=0.7887
model=gcn top_k=50 fold=8 epoch=69 loss=10.9449 val_auc=0.7904
model=gcn top_k=50 fold=8 epoch=70 loss=8.7041 val_auc=0.7915
model=gcn top_k=50 fold=8 epoch=71 loss=10.7538 val_auc=0.7924
model=gcn top_k=50 fold=8 epoch=72 loss=8.3707 val_auc=0.7911
model=gcn top_k=50 fold=8 epoch=73 loss=10.6154 val_auc=0.7899
model=gcn top_k=50 fold=8 epoch=74 loss=9.4802 val_auc=0.7906
model=gcn top_k=50 fold=8 epoch=75 loss=10.5743 val_auc=0.7911
model=gcn top_k=50 fold=8 epoch=76 loss=9.5653 val_auc=0.7901
model=gcn top_k=50 fold=8 epoch=77 loss=11.4255 val_auc=0.7896
model=gcn top_k=50 fold=8 epoch=78 loss=11.8013 val_auc=0.7893
model=gcn top_k=50 fold=8 epoch=79 loss=9.6500 val_auc=0.7863
model=gcn top_k=50 fold=8 epoch=80 loss=9.0701 val_auc=0.7837
model=gcn top_k=50 fold=8 epoch=81 loss=12.5674 val_auc=0.7841
model=gcn top_k=50 fold=8 epoch=82 loss=8.0592 val_auc=0.7864
model=gcn top_k=50 fold=8 epoch=83 loss=8.4676 val_auc=0.7906
gcn top_k=50 fold=8: early stopping at epoch 83

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=50 fold=9 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=gcn top_k=50 fold=9 epoch=0 loss=254.5045 val_auc=0.5147
model=gcn top_k=50 fold=9 epoch=1 loss=96.0139 val_auc=0.5949
model=gcn top_k=50 fold=9 epoch=2 loss=21.5716 val_auc=0.7519
model=gcn top_k=50 fold=9 epoch=3 loss=22.8249 val_auc=0.5445
model=gcn top_k=50 fold=9 epoch=4 loss=36.8776 val_auc=0.5779
model=gcn top_k=50 fold=9 epoch=5 loss=28.3500 val_auc=0.7599
model=gcn top_k=50 fold=9 epoch=6 loss=16.4523 val_auc=0.7589
model=gcn top_k=50 fold=9 epoch=7 loss=15.5773 val_auc=0.7664
model=gcn top_k=50 fold=9 epoch=8 loss=14.9937 val_auc=0.7072
model=gcn top_k=50 fold=9 epoch=9 loss=14.8305 val_auc=0.7357
model=gcn top_k=50 fold=9 epoch=10 loss=13.2211 val_auc=0.7737
model=gcn top_k=50 fold=9 epoch=11 loss=14.9545 val_auc=0.7800
model=gcn top_k=50 fold=9 epoch=12 loss=13.2496 val_auc=0.7817
model=gcn top_k=50 fold=9 epoch=13 loss=12.4201 val_auc=0.7254
model=gcn top_k=50 fold=9 epoch=14 loss=16.0676 val_auc=0.6988
model=gcn top_k=50 fold=9 epoch=15 loss=15.2625 val_auc=0.7334
model=gcn top_k=50 fold=9 epoch=16 loss=15.2925 val_auc=0.7822
model=gcn top_k=50 fold=9 epoch=17 loss=12.6844 val_auc=0.7862
model=gcn top_k=50 fold=9 epoch=18 loss=14.2988 val_auc=0.7662
model=gcn top_k=50 fold=9 epoch=19 loss=12.1160 val_auc=0.7633
model=gcn top_k=50 fold=9 epoch=20 loss=17.1886 val_auc=0.7695
model=gcn top_k=50 fold=9 epoch=21 loss=13.4558 val_auc=0.7702
model=gcn top_k=50 fold=9 epoch=22 loss=16.4996 val_auc=0.7807
model=gcn top_k=50 fold=9 epoch=23 loss=11.7755 val_auc=0.7837
model=gcn top_k=50 fold=9 epoch=24 loss=13.0833 val_auc=0.7834
model=gcn top_k=50 fold=9 epoch=25 loss=14.3558 val_auc=0.7813
model=gcn top_k=50 fold=9 epoch=26 loss=12.7876 val_auc=0.7726
model=gcn top_k=50 fold=9 epoch=27 loss=12.7647 val_auc=0.7526
model=gcn top_k=50 fold=9 epoch=28 loss=15.1217 val_auc=0.7503
model=gcn top_k=50 fold=9 epoch=29 loss=14.1848 val_auc=0.7673
gcn top_k=50 fold=9: early stopping at epoch 29

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

######## Model=gcn top_k=100 ########

===== Model=gcn top_k=100 fold=0 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=100 fold=0 epoch=0 loss=243.7655 val_auc=0.5258
model=gcn top_k=100 fold=0 epoch=1 loss=98.6801 val_auc=0.5349
model=gcn top_k=100 fold=0 epoch=2 loss=28.7688 val_auc=0.7094
model=gcn top_k=100 fold=0 epoch=3 loss=19.3574 val_auc=0.5147
model=gcn top_k=100 fold=0 epoch=4 loss=28.6014 val_auc=0.6442
model=gcn top_k=100 fold=0 epoch=5 loss=22.4673 val_auc=0.7569

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=100 fold=0 epoch=6 loss=19.2786 val_auc=0.7558
model=gcn top_k=100 fold=0 epoch=7 loss=16.4487 val_auc=0.6942
model=gcn top_k=100 fold=0 epoch=8 loss=17.1976 val_auc=0.7436
model=gcn top_k=100 fold=0 epoch=9 loss=16.7700 val_auc=0.7665
model=gcn top_k=100 fold=0 epoch=10 loss=14.0729 val_auc=0.7713
model=gcn top_k=100 fold=0 epoch=11 loss=14.5570 val_auc=0.7658
model=gcn top_k=100 fold=0 epoch=12 loss=10.9947 val_auc=0.7636
model=gcn top_k=100 fold=0 epoch=13 loss=16.9070 val_auc=0.7711
model=gcn top_k=100 fold=0 epoch=14 loss=18.2987 val_auc=0.7681
model=gcn top_k=100 fold=0 epoch=15 loss=12.7000 val_auc=0.7722
model=gcn top_k=100 fold=0 epoch=16 loss=12.9881 val_auc=0.7465
model=gcn top_k=100 fold=0 epoch=17 loss=13.6589 val_auc=0.7428
model=gcn top_k=100 fold=0 epoch=18 loss=14.4224 val_auc=0.7679
model=gcn top_k=100 fold=0 epoch=19 loss=12.1618 val_auc=0.7777
model=gcn top_k=100 fold=0 epoch=20 loss=10.4392 val_auc=0.7717
model=gcn top_k=100 fold=0 epoch=21 loss=12.3165 val_auc=0.7729
model=gcn top_k=100 fold=0 epoch=22 loss=13.5229 val_auc=0.7793
model=gcn top_k=100 fold=0 epoch=23 loss=12.9569 val_auc=0.7810
model=gcn top_k=100 fold=0 epoch=24 loss=12.9095 val_auc=0.7814
model=gcn top_k=100 fold=0 epoch=25 loss=11.4832 val_auc=0.7800
model=gcn top_k=100 fold=0 epoch=26 loss=10.5269 val_auc=0.7695
model=gcn top_k=100 fold=0 epoch=27 loss=13.1890 val_auc=0.7553
model=gcn top_k=100 fold=0 epoch=28 loss=16.8882 val_auc=0.7667
model=gcn top_k=100 fold=0 epoch=29 loss=16.8885 val_auc=0.7770
model=gcn top_k=100 fold=0 epoch=30 loss=14.1450 val_auc=0.7807
model=gcn top_k=100 fold=0 epoch=31 loss=10.4698 val_auc=0.7805
model=gcn top_k=100 fold=0 epoch=32 loss=11.4289 val_auc=0.7803
model=gcn top_k=100 fold=0 epoch=33 loss=13.2494 val_auc=0.7803
model=gcn top_k=100 fold=0 epoch=34 loss=12.3399 val_auc=0.7750
model=gcn top_k=100 fold=0 epoch=35 loss=10.8820 val_auc=0.7700
model=gcn top_k=100 fold=0 epoch=36 loss=10.7041 val_auc=0.7732
gcn top_k=100 fold=0: early stopping at epoch 36

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=100 fold=1 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=100 fold=1 epoch=0 loss=233.5970 val_auc=0.5252
model=gcn top_k=100 fold=1 epoch=1 loss=92.0133 val_auc=0.5275
model=gcn top_k=100 fold=1 epoch=2 loss=30.9186 val_auc=0.7410
model=gcn top_k=100 fold=1 epoch=3 loss=20.8778 val_auc=0.6285
model=gcn top_k=100 fold=1 epoch=4 loss=19.6644 val_auc=0.6959
model=gcn top_k=100 fold=1 epoch=5 loss=16.0208 val_auc=0.7799
model=gcn top_k=100 fold=1 epoch=6 loss=19.0983 val_auc=0.7817
model=gcn top_k=100 fold=1 epoch=7 loss=15.6263 val_auc=0.6766
model=gcn top_k=100 fold=1 epoch=8 loss=16.6290 val_auc=0.7488
model=gcn top_k=100 fold=1 epoch=9 loss=15.4354 val_auc=0.7821
model=gcn top_k=100 fold=1 epoch=10 loss=13.6450 val_auc=0.7831
model=gcn top_k=100 fold=1 epoch=11 loss=13.6856 val_auc=0.7737
model=gcn top_k=100 fold=1 epoch=12 loss=12.6421 val_auc=0.7659
model=gcn top_k=100 fold=1 epoch=13 loss=14.4790 val_auc=0.7815
model=gcn top_k=100 fold=1 epoch=14 loss=14.7314 val_auc=0.7819
model=gcn top_k=100 fold=1 epoch=15 loss=11.0667 val_auc=0.7832
model=gcn top_k=100 fold=1 epoch=16 loss=12.3259 val_auc=0.7532
model=gcn top_k=100 fold=1 epoch=17 loss=16.7897 val_auc=0.7552
model=gcn top_k=100 fold=1 epoch=18 loss=14.2425 val_auc=0.7845
model=gcn top_k=100 fold=1 epoch=19 loss=11.1869 val_auc=0.7855
model=gcn top_k=100 fold=1 epoch=20 loss=13.2940 val_auc=0.7872
model=gcn top_k=100 fold=1 epoch=21 loss=13.1087 val_auc=0.7873
model=gcn top_k=100 fold=1 epoch=22 loss=12.2040 val_auc=0.7544
model=gcn top_k=100 fold=1 epoch=23 loss=13.9256 val_auc=0.7334
model=gcn top_k=100 fold=1 epoch=24 loss=12.6754 val_auc=0.7671
model=gcn top_k=100 fold=1 epoch=25 loss=17.0288 val_auc=0.7913
model=gcn top_k=100 fold=1 epoch=26 loss=11.7172 val_auc=0.7914
model=gcn top_k=100 fold=1 epoch=27 loss=11.2217 val_auc=0.7907
model=gcn top_k=100 fold=1 epoch=28 loss=10.8232 val_auc=0.7899
model=gcn top_k=100 fold=1 epoch=29 loss=12.2028 val_auc=0.7888
model=gcn top_k=100 fold=1 epoch=30 loss=10.3186 val_auc=0.7823
model=gcn top_k=100 fold=1 epoch=31 loss=13.0552 val_auc=0.7863
model=gcn top_k=100 fold=1 epoch=32 loss=10.9131 val_auc=0.7914
model=gcn top_k=100 fold=1 epoch=33 loss=11.5208 val_auc=0.7924
model=gcn top_k=100 fold=1 epoch=34 loss=12.0002 val_auc=0.7935
model=gcn top_k=100 fold=1 epoch=35 loss=11.5185 val_auc=0.7932
model=gcn top_k=100 fold=1 epoch=36 loss=11.8036 val_auc=0.7879
model=gcn top_k=100 fold=1 epoch=37 loss=12.1794 val_auc=0.7815
model=gcn top_k=100 fold=1 epoch=38 loss=12.1714 val_auc=0.7862
model=gcn top_k=100 fold=1 epoch=39 loss=9.1465 val_auc=0.7923
model=gcn top_k=100 fold=1 epoch=40 loss=11.3992 val_auc=0.7929
model=gcn top_k=100 fold=1 epoch=41 loss=9.4589 val_auc=0.7936
model=gcn top_k=100 fold=1 epoch=42 loss=11.5600 val_auc=0.7941
model=gcn top_k=100 fold=1 epoch=43 loss=10.9233 val_auc=0.7924
model=gcn top_k=100 fold=1 epoch=44 loss=11.7776 val_auc=0.7908
model=gcn top_k=100 fold=1 epoch=45 loss=10.5697 val_auc=0.7907
model=gcn top_k=100 fold=1 epoch=46 loss=11.7112 val_auc=0.7733
model=gcn top_k=100 fold=1 epoch=47 loss=16.2682 val_auc=0.7764
model=gcn top_k=100 fold=1 epoch=48 loss=18.5192 val_auc=0.7935
model=gcn top_k=100 fold=1 epoch=49 loss=12.0603 val_auc=0.7988
model=gcn top_k=100 fold=1 epoch=50 loss=12.3800 val_auc=0.7987
model=gcn top_k=100 fold=1 epoch=51 loss=13.0496 val_auc=0.7985
model=gcn top_k=100 fold=1 epoch=52 loss=12.5061 val_auc=0.7977
model=gcn top_k=100 fold=1 epoch=53 loss=10.9815 val_auc=0.7950
model=gcn top_k=100 fold=1 epoch=54 loss=10.0600 val_auc=0.7904
model=gcn top_k=100 fold=1 epoch=55 loss=10.6670 val_auc=0.7915
model=gcn top_k=100 fold=1 epoch=56 loss=11.6513 val_auc=0.7956
model=gcn top_k=100 fold=1 epoch=57 loss=10.5642 val_auc=0.7983
model=gcn top_k=100 fold=1 epoch=58 loss=9.8308 val_auc=0.7995
model=gcn top_k=100 fold=1 epoch=59 loss=10.3034 val_auc=0.8013
model=gcn top_k=100 fold=1 epoch=60 loss=10.5431 val_auc=0.8029
model=gcn top_k=100 fold=1 epoch=61 loss=10.1561 val_auc=0.8033
model=gcn top_k=100 fold=1 epoch=62 loss=11.1968 val_auc=0.8029
model=gcn top_k=100 fold=1 epoch=63 loss=9.7499 val_auc=0.8020
model=gcn top_k=100 fold=1 epoch=64 loss=9.9238 val_auc=0.8010
model=gcn top_k=100 fold=1 epoch=65 loss=9.0752 val_auc=0.8006
model=gcn top_k=100 fold=1 epoch=66 loss=9.4590 val_auc=0.8008
model=gcn top_k=100 fold=1 epoch=67 loss=10.5232 val_auc=0.8007
model=gcn top_k=100 fold=1 epoch=68 loss=10.0866 val_auc=0.8007
model=gcn top_k=100 fold=1 epoch=69 loss=9.2726 val_auc=0.8008
model=gcn top_k=100 fold=1 epoch=70 loss=10.0271 val_auc=0.8018
model=gcn top_k=100 fold=1 epoch=71 loss=9.4315 val_auc=0.8045
model=gcn top_k=100 fold=1 epoch=72 loss=8.7307 val_auc=0.8065
model=gcn top_k=100 fold=1 epoch=73 loss=9.1744 val_auc=0.8078
model=gcn top_k=100 fold=1 epoch=74 loss=8.0572 val_auc=0.8085
model=gcn top_k=100 fold=1 epoch=75 loss=9.2089 val_auc=0.8081
model=gcn top_k=100 fold=1 epoch=76 loss=8.6468 val_auc=0.8063
model=gcn top_k=100 fold=1 epoch=77 loss=9.9867 val_auc=0.8032
model=gcn top_k=100 fold=1 epoch=78 loss=8.9623 val_auc=0.8009
model=gcn top_k=100 fold=1 epoch=79 loss=12.8230 val_auc=0.8013
model=gcn top_k=100 fold=1 epoch=80 loss=8.8980 val_auc=0.8023
model=gcn top_k=100 fold=1 epoch=81 loss=9.2459 val_auc=0.8024
model=gcn top_k=100 fold=1 epoch=82 loss=8.4709 val_auc=0.8015
model=gcn top_k=100 fold=1 epoch=83 loss=9.6033 val_auc=0.8017
model=gcn top_k=100 fold=1 epoch=84 loss=9.5358 val_auc=0.8038
model=gcn top_k=100 fold=1 epoch=85 loss=8.3948 val_auc=0.8060
model=gcn top_k=100 fold=1 epoch=86 loss=8.5262 val_auc=0.8077
gcn top_k=100 fold=1: early stopping at epoch 86

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=100 fold=2 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=100 fold=2 epoch=0 loss=225.1326 val_auc=0.5257
model=gcn top_k=100 fold=2 epoch=1 loss=76.6263 val_auc=0.5554
model=gcn top_k=100 fold=2 epoch=2 loss=30.8546 val_auc=0.7563
model=gcn top_k=100 fold=2 epoch=3 loss=19.7900 val_auc=0.5717
model=gcn top_k=100 fold=2 epoch=4 loss=18.1818 val_auc=0.6371
model=gcn top_k=100 fold=2 epoch=5 loss=19.1287 val_auc=0.7701
model=gcn top_k=100 fold=2 epoch=6 loss=14.2371 val_auc=0.7679
model=gcn top_k=100 fold=2 epoch=7 loss=13.1114 val_auc=0.7644
model=gcn top_k=100 fold=2 epoch=8 loss=13.6706 val_auc=0.7726
model=gcn top_k=100 fold=2 epoch=9 loss=13.2942 val_auc=0.7754
model=gcn top_k=100 fold=2 epoch=10 loss=13.4701 val_auc=0.7790
model=gcn top_k=100 fold=2 epoch=11 loss=12.0697 val_auc=0.7586
model=gcn top_k=100 fold=2 epoch=12 loss=14.6942 val_auc=0.7608
model=gcn top_k=100 fold=2 epoch=13 loss=17.3951 val_auc=0.7816
model=gcn top_k=100 fold=2 epoch=14 loss=11.6202 val_auc=0.7869
model=gcn top_k=100 fold=2 epoch=15 loss=12.7816 val_auc=0.7877
model=gcn top_k=100 fold=2 epoch=16 loss=12.3387 val_auc=0.7862
model=gcn top_k=100 fold=2 epoch=17 loss=12.6590 val_auc=0.7832
model=gcn top_k=100 fold=2 epoch=18 loss=12.6456 val_auc=0.7790
model=gcn top_k=100 fold=2 epoch=19 loss=12.6919 val_auc=0.7616
model=gcn top_k=100 fold=2 epoch=20 loss=16.1362 val_auc=0.7655
model=gcn top_k=100 fold=2 epoch=21 loss=14.4282 val_auc=0.7762
model=gcn top_k=100 fold=2 epoch=22 loss=12.8289 val_auc=0.7752
model=gcn top_k=100 fold=2 epoch=23 loss=12.1183 val_auc=0.7744
model=gcn top_k=100 fold=2 epoch=24 loss=12.2519 val_auc=0.7740
model=gcn top_k=100 fold=2 epoch=25 loss=10.0898 val_auc=0.7773
model=gcn top_k=100 fold=2 epoch=26 loss=10.5868 val_auc=0.7808
model=gcn top_k=100 fold=2 epoch=27 loss=14.3907 val_auc=0.7829
gcn top_k=100 fold=2: early stopping at epoch 27

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=100 fold=3 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=100 fold=3 epoch=0 loss=190.9174 val_auc=0.5209
model=gcn top_k=100 fold=3 epoch=1 loss=68.1879 val_auc=0.5785

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=100 fold=3 epoch=2 loss=19.8887 val_auc=0.7505

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=100 fold=3 epoch=3 loss=21.1344 val_auc=0.5451
model=gcn top_k=100 fold=3 epoch=4 loss=31.3085 val_auc=0.5647
model=gcn top_k=100 fold=3 epoch=5 loss=19.0026 val_auc=0.7684
model=gcn top_k=100 fold=3 epoch=6 loss=15.2974 val_auc=0.7695
model=gcn top_k=100 fold=3 epoch=7 loss=14.3373 val_auc=0.7775
model=gcn top_k=100 fold=3 epoch=8 loss=12.7525 val_auc=0.7726
model=gcn top_k=100 fold=3 epoch=9 loss=11.8156 val_auc=0.7774
model=gcn top_k=100 fold=3 epoch=10 loss=15.3600 val_auc=0.7807
model=gcn top_k=100 fold=3 epoch=11 loss=12.8249 val_auc=0.7669
model=gcn top_k=100 fold=3 epoch=12 loss=15.4629 val_auc=0.7787
model=gcn top_k=100 fold=3 epoch=13 loss=13.6786 val_auc=0.7832
model=gcn top_k=100 fold=3 epoch=14 loss=17.5929 val_auc=0.7835
model=gcn top_k=100 fold=3 epoch=15 loss=15.6102 val_auc=0.7819
model=gcn top_k=100 fold=3 epoch=16 loss=13.3901 val_auc=0.7214
model=gcn top_k=100 fold=3 epoch=17 loss=17.6966 val_auc=0.6960
model=gcn top_k=100 fold=3 epoch=18 loss=19.3904 val_auc=0.7717
model=gcn top_k=100 fold=3 epoch=19 loss=14.4387 val_auc=0.7869
model=gcn top_k=100 fold=3 epoch=20 loss=11.7894 val_auc=0.7872
model=gcn top_k=100 fold=3 epoch=21 loss=17.2414 val_auc=0.7878
model=gcn top_k=100 fold=3 epoch=22 loss=15.4963 val_auc=0.7884
model=gcn top_k=100 fold=3 epoch=23 loss=12.1998 val_auc=0.7867
model=gcn top_k=100 fold=3 epoch=24 loss=13.0692 val_auc=0.7705
model=gcn top_k=100 fold=3 epoch=25 loss=12.4495 val_auc=0.7767
model=gcn top_k=100 fold=3 epoch=26 loss=12.5281 val_auc=0.7881
model=gcn top_k=100 fold=3 epoch=27 loss=11.7391 val_auc=0.7890
model=gcn top_k=100 fold=3 epoch=28 loss=12.6564 val_auc=0.7879
model=gcn top_k=100 fold=3 epoch=29 loss=13.7735 val_auc=0.7869
model=gcn top_k=100 fold=3 epoch=30 loss=13.1285 val_auc=0.7852
model=gcn top_k=100 fold=3 epoch=31 loss=12.1267 val_auc=0.7690
model=gcn top_k=100 fold=3 epoch=32 loss=16.1505 val_auc=0.7496
model=gcn top_k=100 fold=3 epoch=33 loss=12.4903 val_auc=0.7631
model=gcn top_k=100 fold=3 epoch=34 loss=12.5557 val_auc=0.7812
model=gcn top_k=100 fold=3 epoch=35 loss=10.2984 val_auc=0.7842
model=gcn top_k=100 fold=3 epoch=36 loss=10.3601 val_auc=0.7849
model=gcn top_k=100 fold=3 epoch=37 loss=11.2699 val_auc=0.7855
model=gcn top_k=100 fold=3 epoch=38 loss=10.0129 val_auc=0.7865
model=gcn top_k=100 fold=3 epoch=39 loss=9.7685 val_auc=0.7870
gcn top_k=100 fold=3: early stopping at epoch 39

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=100 fold=4 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=gcn top_k=100 fold=4 epoch=0 loss=252.0430 val_auc=0.4977
model=gcn top_k=100 fold=4 epoch=1 loss=101.6349 val_auc=0.5089
model=gcn top_k=100 fold=4 epoch=2 loss=44.0626 val_auc=0.6829
model=gcn top_k=100 fold=4 epoch=3 loss=15.2157 val_auc=0.6502
model=gcn top_k=100 fold=4 epoch=4 loss=14.6028 val_auc=0.7652
model=gcn top_k=100 fold=4 epoch=5 loss=13.8160 val_auc=0.6474
model=gcn top_k=100 fold=4 epoch=6 loss=18.6201 val_auc=0.7123
model=gcn top_k=100 fold=4 epoch=7 loss=14.3749 val_auc=0.7319
model=gcn top_k=100 fold=4 epoch=8 loss=12.3379 val_auc=0.7565
model=gcn top_k=100 fold=4 epoch=9 loss=14.0106 val_auc=0.7733
model=gcn top_k=100 fold=4 epoch=10 loss=16.7620 val_auc=0.7726
model=gcn top_k=100 fold=4 epoch=11 loss=11.9704 val_auc=0.7755
model=gcn top_k=100 fold=4 epoch=12 loss=15.6955 val_auc=0.7789
model=gcn top_k=100 fold=4 epoch=13 loss=14.3257 val_auc=0.7793
model=gcn top_k=100 fold=4 epoch=14 loss=13.0916 val_auc=0.7659
model=gcn top_k=100 fold=4 epoch=15 loss=14.9153 val_auc=0.7539
model=gcn top_k=100 fold=4 epoch=16 loss=16.2874 val_auc=0.7758
model=gcn top_k=100 fold=4 epoch=17 loss=13.0140 val_auc=0.7801
model=gcn top_k=100 fold=4 epoch=18 loss=13.2745 val_auc=0.7800
model=gcn top_k=100 fold=4 epoch=19 loss=13.2067 val_auc=0.7791
model=gcn top_k=100 fold=4 epoch=20 loss=12.1042 val_auc=0.7623
model=gcn top_k=100 fold=4 epoch=21 loss=13.5197 val_auc=0.7478
model=gcn top_k=100 fold=4 epoch=22 loss=17.2351 val_auc=0.7665
model=gcn top_k=100 fold=4 epoch=23 loss=14.8293 val_auc=0.7786
model=gcn top_k=100 fold=4 epoch=24 loss=11.4772 val_auc=0.7808
model=gcn top_k=100 fold=4 epoch=25 loss=11.5460 val_auc=0.7814
model=gcn top_k=100 fold=4 epoch=26 loss=10.9231 val_auc=0.7817
model=gcn top_k=100 fold=4 epoch=27 loss=9.8688 val_auc=0.7797
model=gcn top_k=100 fold=4 epoch=28 loss=11.2928 val_auc=0.7813
model=gcn top_k=100 fold=4 epoch=29 loss=10.4936 val_auc=0.7830
model=gcn top_k=100 fold=4 epoch=30 loss=11.1321 val_auc=0.7838
model=gcn top_k=100 fold=4 epoch=31 loss=11.4384 val_auc=0.7801
model=gcn top_k=100 fold=4 epoch=32 loss=13.3498 val_auc=0.7817
model=gcn top_k=100 fold=4 epoch=33 loss=14.6355 val_auc=0.7847
model=gcn top_k=100 fold=4 epoch=34 loss=11.9563 val_auc=0.7845
model=gcn top_k=100 fold=4 epoch=35 loss=11.8812 val_auc=0.7843
model=gcn top_k=100 fold=4 epoch=36 loss=12.2328 val_auc=0.7824
model=gcn top_k=100 fold=4 epoch=37 loss=12.7804 val_auc=0.7772
model=gcn top_k=100 fold=4 epoch=38 loss=12.7796 val_auc=0.7549
model=gcn top_k=100 fold=4 epoch=39 loss=12.5940 val_auc=0.7384
model=gcn top_k=100 fold=4 epoch=40 loss=13.2132 val_auc=0.7541
model=gcn top_k=100 fold=4 epoch=41 loss=15.7543 val_auc=0.7764
model=gcn top_k=100 fold=4 epoch=42 loss=11.6014 val_auc=0.7828
model=gcn top_k=100 fold=4 epoch=43 loss=11.6948 val_auc=0.7833
model=gcn top_k=100 fold=4 epoch=44 loss=12.4700 val_auc=0.7838
model=gcn top_k=100 fold=4 epoch=45 loss=12.0866 val_auc=0.7844
gcn top_k=100 fold=4: early stopping at epoch 45

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=100 fold=5 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=gcn top_k=100 fold=5 epoch=0 loss=266.2328 val_auc=0.5251
model=gcn top_k=100 fold=5 epoch=1 loss=89.4962 val_auc=0.5389

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=100 fold=5 epoch=2 loss=31.3939 val_auc=0.7485
model=gcn top_k=100 fold=5 epoch=3 loss=25.3070 val_auc=0.5903
model=gcn top_k=100 fold=5 epoch=4 loss=25.2260 val_auc=0.7601
model=gcn top_k=100 fold=5 epoch=5 loss=17.3460 val_auc=0.7740

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=100 fold=5 epoch=6 loss=18.2841 val_auc=0.7742
model=gcn top_k=100 fold=5 epoch=7 loss=17.2282 val_auc=0.7242
model=gcn top_k=100 fold=5 epoch=8 loss=16.3864 val_auc=0.7680
model=gcn top_k=100 fold=5 epoch=9 loss=12.5339 val_auc=0.7609
model=gcn top_k=100 fold=5 epoch=10 loss=15.5590 val_auc=0.7817
model=gcn top_k=100 fold=5 epoch=11 loss=11.4962 val_auc=0.7664
model=gcn top_k=100 fold=5 epoch=12 loss=14.6538 val_auc=0.7702
model=gcn top_k=100 fold=5 epoch=13 loss=14.4215 val_auc=0.7842
model=gcn top_k=100 fold=5 epoch=14 loss=14.8958 val_auc=0.7853
model=gcn top_k=100 fold=5 epoch=15 loss=11.1352 val_auc=0.7737
model=gcn top_k=100 fold=5 epoch=16 loss=15.3216 val_auc=0.7630
model=gcn top_k=100 fold=5 epoch=17 loss=15.1984 val_auc=0.7811
model=gcn top_k=100 fold=5 epoch=18 loss=13.6058 val_auc=0.7864
model=gcn top_k=100 fold=5 epoch=19 loss=11.6650 val_auc=0.7864
model=gcn top_k=100 fold=5 epoch=20 loss=10.3275 val_auc=0.7857
model=gcn top_k=100 fold=5 epoch=21 loss=12.6510 val_auc=0.7850
model=gcn top_k=100 fold=5 epoch=22 loss=12.0302 val_auc=0.7849
model=gcn top_k=100 fold=5 epoch=23 loss=13.8037 val_auc=0.7856
model=gcn top_k=100 fold=5 epoch=24 loss=10.7612 val_auc=0.7857
model=gcn top_k=100 fold=5 epoch=25 loss=12.1624 val_auc=0.7815
model=gcn top_k=100 fold=5 epoch=26 loss=10.5575 val_auc=0.7794
model=gcn top_k=100 fold=5 epoch=27 loss=11.0488 val_auc=0.7844
model=gcn top_k=100 fold=5 epoch=28 loss=13.5690 val_auc=0.7892
model=gcn top_k=100 fold=5 epoch=29 loss=12.0113 val_auc=0.7905
model=gcn top_k=100 fold=5 epoch=30 loss=12.3029 val_auc=0.7903
model=gcn top_k=100 fold=5 epoch=31 loss=11.6870 val_auc=0.7902
model=gcn top_k=100 fold=5 epoch=32 loss=11.7442 val_auc=0.7884
model=gcn top_k=100 fold=5 epoch=33 loss=12.2645 val_auc=0.7916
model=gcn top_k=100 fold=5 epoch=34 loss=11.5250 val_auc=0.7915
model=gcn top_k=100 fold=5 epoch=35 loss=10.4801 val_auc=0.7936
model=gcn top_k=100 fold=5 epoch=36 loss=11.4107 val_auc=0.7966
model=gcn top_k=100 fold=5 epoch=37 loss=11.8775 val_auc=0.7972
model=gcn top_k=100 fold=5 epoch=38 loss=9.8513 val_auc=0.7977
model=gcn top_k=100 fold=5 epoch=39 loss=11.0004 val_auc=0.7979
model=gcn top_k=100 fold=5 epoch=40 loss=12.8643 val_auc=0.7972
model=gcn top_k=100 fold=5 epoch=41 loss=10.5451 val_auc=0.7971
model=gcn top_k=100 fold=5 epoch=42 loss=9.4390 val_auc=0.7936
model=gcn top_k=100 fold=5 epoch=43 loss=11.2053 val_auc=0.7884
model=gcn top_k=100 fold=5 epoch=44 loss=12.1584 val_auc=0.7921
model=gcn top_k=100 fold=5 epoch=45 loss=14.6584 val_auc=0.7956
model=gcn top_k=100 fold=5 epoch=46 loss=11.8073 val_auc=0.7953
model=gcn top_k=100 fold=5 epoch=47 loss=10.1960 val_auc=0.7960
model=gcn top_k=100 fold=5 epoch=48 loss=14.6960 val_auc=0.7966
model=gcn top_k=100 fold=5 epoch=49 loss=12.7560 val_auc=0.7966
model=gcn top_k=100 fold=5 epoch=50 loss=11.8460 val_auc=0.7970
model=gcn top_k=100 fold=5 epoch=51 loss=11.2882 val_auc=0.7970
gcn top_k=100 fold=5: early stopping at epoch 51

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=100 fold=6 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=100 fold=6 epoch=0 loss=223.9662 val_auc=0.5150
model=gcn top_k=100 fold=6 epoch=1 loss=93.0072 val_auc=0.5269
model=gcn top_k=100 fold=6 epoch=2 loss=27.7575 val_auc=0.7387
model=gcn top_k=100 fold=6 epoch=3 loss=19.3505 val_auc=0.5272
model=gcn top_k=100 fold=6 epoch=4 loss=32.7156 val_auc=0.5551

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=100 fold=6 epoch=5 loss=19.4512 val_auc=0.7876
model=gcn top_k=100 fold=6 epoch=6 loss=17.8424 val_auc=0.7868
model=gcn top_k=100 fold=6 epoch=7 loss=16.3622 val_auc=0.6263
model=gcn top_k=100 fold=6 epoch=8 loss=21.2185 val_auc=0.6814
model=gcn top_k=100 fold=6 epoch=9 loss=26.2525 val_auc=0.7684
model=gcn top_k=100 fold=6 epoch=10 loss=15.8756 val_auc=0.7924

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=100 fold=6 epoch=11 loss=15.2178 val_auc=0.7921
model=gcn top_k=100 fold=6 epoch=12 loss=14.6968 val_auc=0.7719
model=gcn top_k=100 fold=6 epoch=13 loss=15.7108 val_auc=0.7892
model=gcn top_k=100 fold=6 epoch=14 loss=13.2003 val_auc=0.7861
model=gcn top_k=100 fold=6 epoch=15 loss=13.9623 val_auc=0.7965
model=gcn top_k=100 fold=6 epoch=16 loss=15.2696 val_auc=0.7954
model=gcn top_k=100 fold=6 epoch=17 loss=12.7867 val_auc=0.7934
model=gcn top_k=100 fold=6 epoch=18 loss=11.9840 val_auc=0.7730
model=gcn top_k=100 fold=6 epoch=19 loss=13.7369 val_auc=0.7693
model=gcn top_k=100 fold=6 epoch=20 loss=12.6809 val_auc=0.7928
model=gcn top_k=100 fold=6 epoch=21 loss=11.3970 val_auc=0.7958
model=gcn top_k=100 fold=6 epoch=22 loss=11.9366 val_auc=0.7813
model=gcn top_k=100 fold=6 epoch=23 loss=12.4030 val_auc=0.7916
model=gcn top_k=100 fold=6 epoch=24 loss=12.9242 val_auc=0.7717
model=gcn top_k=100 fold=6 epoch=25 loss=14.2874 val_auc=0.7815
model=gcn top_k=100 fold=6 epoch=26 loss=15.7740 val_auc=0.7991
model=gcn top_k=100 fold=6 epoch=27 loss=11.5783 val_auc=0.7996
model=gcn top_k=100 fold=6 epoch=28 loss=16.5996 val_auc=0.7991
model=gcn top_k=100 fold=6 epoch=29 loss=14.8247 val_auc=0.7996
model=gcn top_k=100 fold=6 epoch=30 loss=16.8792 val_auc=0.7893
model=gcn top_k=100 fold=6 epoch=31 loss=11.8844 val_auc=0.7812
model=gcn top_k=100 fold=6 epoch=32 loss=12.8567 val_auc=0.7933
model=gcn top_k=100 fold=6 epoch=33 loss=12.3205 val_auc=0.8020
model=gcn top_k=100 fold=6 epoch=34 loss=12.0492 val_auc=0.8023
model=gcn top_k=100 fold=6 epoch=35 loss=11.5314 val_auc=0.8026
model=gcn top_k=100 fold=6 epoch=36 loss=12.9498 val_auc=0.8006
model=gcn top_k=100 fold=6 epoch=37 loss=11.6498 val_auc=0.7932
model=gcn top_k=100 fold=6 epoch=38 loss=11.4902 val_auc=0.7968
model=gcn top_k=100 fold=6 epoch=39 loss=11.6425 val_auc=0.8021
model=gcn top_k=100 fold=6 epoch=40 loss=11.6529 val_auc=0.8047
model=gcn top_k=100 fold=6 epoch=41 loss=11.5041 val_auc=0.8056
model=gcn top_k=100 fold=6 epoch=42 loss=11.4290 val_auc=0.8064
model=gcn top_k=100 fold=6 epoch=43 loss=11.7314 val_auc=0.8043
model=gcn top_k=100 fold=6 epoch=44 loss=10.3863 val_auc=0.8012
model=gcn top_k=100 fold=6 epoch=45 loss=9.9393 val_auc=0.8031
model=gcn top_k=100 fold=6 epoch=46 loss=10.4948 val_auc=0.8041
model=gcn top_k=100 fold=6 epoch=47 loss=9.3629 val_auc=0.8066
model=gcn top_k=100 fold=6 epoch=48 loss=9.5853 val_auc=0.8072
model=gcn top_k=100 fold=6 epoch=49 loss=10.8460 val_auc=0.8075
model=gcn top_k=100 fold=6 epoch=50 loss=12.3332 val_auc=0.8089
model=gcn top_k=100 fold=6 epoch=51 loss=9.4780 val_auc=0.8107
model=gcn top_k=100 fold=6 epoch=52 loss=11.8213 val_auc=0.8113
model=gcn top_k=100 fold=6 epoch=53 loss=13.2769 val_auc=0.8115
model=gcn top_k=100 fold=6 epoch=54 loss=11.1793 val_auc=0.8086
model=gcn top_k=100 fold=6 epoch=55 loss=10.5763 val_auc=0.8027
model=gcn top_k=100 fold=6 epoch=56 loss=10.8347 val_auc=0.7946
model=gcn top_k=100 fold=6 epoch=57 loss=13.0835 val_auc=0.7999
model=gcn top_k=100 fold=6 epoch=58 loss=14.9065 val_auc=0.8059
model=gcn top_k=100 fold=6 epoch=59 loss=11.1354 val_auc=0.8087
model=gcn top_k=100 fold=6 epoch=60 loss=9.2703 val_auc=0.8080
model=gcn top_k=100 fold=6 epoch=61 loss=12.1115 val_auc=0.8078
model=gcn top_k=100 fold=6 epoch=62 loss=10.4874 val_auc=0.8061
model=gcn top_k=100 fold=6 epoch=63 loss=9.1371 val_auc=0.8026
model=gcn top_k=100 fold=6 epoch=64 loss=9.6744 val_auc=0.8025
model=gcn top_k=100 fold=6 epoch=65 loss=9.9141 val_auc=0.8072
gcn top_k=100 fold=6: early stopping at epoch 65

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=100 fold=7 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=100 fold=7 epoch=0 loss=215.6770 val_auc=0.5039

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=100 fold=7 epoch=1 loss=72.0424 val_auc=0.5513
model=gcn top_k=100 fold=7 epoch=2 loss=20.5017 val_auc=0.7015
model=gcn top_k=100 fold=7 epoch=3 loss=16.9998 val_auc=0.7242
model=gcn top_k=100 fold=7 epoch=4 loss=14.9764 val_auc=0.5956
model=gcn top_k=100 fold=7 epoch=5 loss=21.0760 val_auc=0.7657
model=gcn top_k=100 fold=7 epoch=6 loss=14.8833 val_auc=0.7769
model=gcn top_k=100 fold=7 epoch=7 loss=25.6892 val_auc=0.7782
model=gcn top_k=100 fold=7 epoch=8 loss=17.8600 val_auc=0.7172
model=gcn top_k=100 fold=7 epoch=9 loss=18.0561 val_auc=0.6140
model=gcn top_k=100 fold=7 epoch=10 loss=18.0461 val_auc=0.7305
model=gcn top_k=100 fold=7 epoch=11 loss=13.4373 val_auc=0.7819
model=gcn top_k=100 fold=7 epoch=12 loss=14.5492 val_auc=0.7825
model=gcn top_k=100 fold=7 epoch=13 loss=13.1320 val_auc=0.7809
model=gcn top_k=100 fold=7 epoch=14 loss=15.7337 val_auc=0.7810
model=gcn top_k=100 fold=7 epoch=15 loss=13.8758 val_auc=0.7836
model=gcn top_k=100 fold=7 epoch=16 loss=15.8018 val_auc=0.7838
model=gcn top_k=100 fold=7 epoch=17 loss=14.7866 val_auc=0.7835
model=gcn top_k=100 fold=7 epoch=18 loss=12.7272 val_auc=0.7771
model=gcn top_k=100 fold=7 epoch=19 loss=11.3939 val_auc=0.7443
model=gcn top_k=100 fold=7 epoch=20 loss=11.9359 val_auc=0.7449
model=gcn top_k=100 fold=7 epoch=21 loss=13.4604 val_auc=0.7813
model=gcn top_k=100 fold=7 epoch=22 loss=13.7007 val_auc=0.7846
model=gcn top_k=100 fold=7 epoch=23 loss=13.0505 val_auc=0.7859
model=gcn top_k=100 fold=7 epoch=24 loss=12.9411 val_auc=0.7868
model=gcn top_k=100 fold=7 epoch=25 loss=12.9146 val_auc=0.7759
model=gcn top_k=100 fold=7 epoch=26 loss=15.6118 val_auc=0.7720
model=gcn top_k=100 fold=7 epoch=27 loss=13.9112 val_auc=0.7847
model=gcn top_k=100 fold=7 epoch=28 loss=10.8611 val_auc=0.7886
model=gcn top_k=100 fold=7 epoch=29 loss=13.1529 val_auc=0.7824
model=gcn top_k=100 fold=7 epoch=30 loss=10.4368 val_auc=0.7928
model=gcn top_k=100 fold=7 epoch=31 loss=12.1260 val_auc=0.7931
model=gcn top_k=100 fold=7 epoch=32 loss=11.8887 val_auc=0.7916
model=gcn top_k=100 fold=7 epoch=33 loss=11.5921 val_auc=0.7911
model=gcn top_k=100 fold=7 epoch=34 loss=12.2188 val_auc=0.7926
model=gcn top_k=100 fold=7 epoch=35 loss=13.8069 val_auc=0.7921
model=gcn top_k=100 fold=7 epoch=36 loss=10.1950 val_auc=0.7925
model=gcn top_k=100 fold=7 epoch=37 loss=10.1468 val_auc=0.7916
model=gcn top_k=100 fold=7 epoch=38 loss=9.7757 val_auc=0.7906
model=gcn top_k=100 fold=7 epoch=39 loss=10.3979 val_auc=0.7907
model=gcn top_k=100 fold=7 epoch=40 loss=11.6731 val_auc=0.7898
model=gcn top_k=100 fold=7 epoch=41 loss=11.9947 val_auc=0.7908
model=gcn top_k=100 fold=7 epoch=42 loss=9.8080 val_auc=0.7938
model=gcn top_k=100 fold=7 epoch=43 loss=11.6775 val_auc=0.7949
model=gcn top_k=100 fold=7 epoch=44 loss=9.9340 val_auc=0.7953
model=gcn top_k=100 fold=7 epoch=45 loss=9.5990 val_auc=0.7921
model=gcn top_k=100 fold=7 epoch=46 loss=12.6775 val_auc=0.7943
model=gcn top_k=100 fold=7 epoch=47 loss=11.7952 val_auc=0.7967
model=gcn top_k=100 fold=7 epoch=48 loss=9.7824 val_auc=0.7978
model=gcn top_k=100 fold=7 epoch=49 loss=12.3621 val_auc=0.7981
model=gcn top_k=100 fold=7 epoch=50 loss=11.3738 val_auc=0.7979
model=gcn top_k=100 fold=7 epoch=51 loss=9.9972 val_auc=0.7969
model=gcn top_k=100 fold=7 epoch=52 loss=10.7472 val_auc=0.7957
model=gcn top_k=100 fold=7 epoch=53 loss=10.9072 val_auc=0.7976
model=gcn top_k=100 fold=7 epoch=54 loss=12.1292 val_auc=0.7992
model=gcn top_k=100 fold=7 epoch=55 loss=11.0011 val_auc=0.7965
model=gcn top_k=100 fold=7 epoch=56 loss=10.3011 val_auc=0.7942
model=gcn top_k=100 fold=7 epoch=57 loss=10.6247 val_auc=0.7976
model=gcn top_k=100 fold=7 epoch=58 loss=11.5182 val_auc=0.7985
model=gcn top_k=100 fold=7 epoch=59 loss=13.3486 val_auc=0.7993
model=gcn top_k=100 fold=7 epoch=60 loss=10.0206 val_auc=0.7989
model=gcn top_k=100 fold=7 epoch=61 loss=9.9527 val_auc=0.7970
model=gcn top_k=100 fold=7 epoch=62 loss=12.3680 val_auc=0.7982
model=gcn top_k=100 fold=7 epoch=63 loss=10.8354 val_auc=0.8001
model=gcn top_k=100 fold=7 epoch=64 loss=9.9878 val_auc=0.8021
model=gcn top_k=100 fold=7 epoch=65 loss=9.5515 val_auc=0.8027
model=gcn top_k=100 fold=7 epoch=66 loss=10.6242 val_auc=0.8008
model=gcn top_k=100 fold=7 epoch=67 loss=11.0721 val_auc=0.7979
model=gcn top_k=100 fold=7 epoch=68 loss=10.0122 val_auc=0.7994
model=gcn top_k=100 fold=7 epoch=69 loss=9.6567 val_auc=0.8023
model=gcn top_k=100 fold=7 epoch=70 loss=9.3454 val_auc=0.8022
model=gcn top_k=100 fold=7 epoch=71 loss=10.5174 val_auc=0.8028
model=gcn top_k=100 fold=7 epoch=72 loss=9.2375 val_auc=0.8018
model=gcn top_k=100 fold=7 epoch=73 loss=9.3667 val_auc=0.8017
model=gcn top_k=100 fold=7 epoch=74 loss=8.2235 val_auc=0.8015
model=gcn top_k=100 fold=7 epoch=75 loss=8.6708 val_auc=0.7942
model=gcn top_k=100 fold=7 epoch=76 loss=9.9074 val_auc=0.7883
model=gcn top_k=100 fold=7 epoch=77 loss=11.9019 val_auc=0.7949
model=gcn top_k=100 fold=7 epoch=78 loss=9.8388 val_auc=0.8032
model=gcn top_k=100 fold=7 epoch=79 loss=9.3629 val_auc=0.8043
model=gcn top_k=100 fold=7 epoch=80 loss=10.3805 val_auc=0.8048
model=gcn top_k=100 fold=7 epoch=81 loss=8.8962 val_auc=0.8044
model=gcn top_k=100 fold=7 epoch=82 loss=10.1070 val_auc=0.8043
model=gcn top_k=100 fold=7 epoch=83 loss=13.1240 val_auc=0.8044
model=gcn top_k=100 fold=7 epoch=84 loss=9.5042 val_auc=0.8043
model=gcn top_k=100 fold=7 epoch=85 loss=9.0772 val_auc=0.8044
model=gcn top_k=100 fold=7 epoch=86 loss=9.3630 val_auc=0.8036
model=gcn top_k=100 fold=7 epoch=87 loss=8.3480 val_auc=0.8016
model=gcn top_k=100 fold=7 epoch=88 loss=9.2308 val_auc=0.8011
model=gcn top_k=100 fold=7 epoch=89 loss=10.5828 val_auc=0.8031
model=gcn top_k=100 fold=7 epoch=90 loss=8.7321 val_auc=0.8034
model=gcn top_k=100 fold=7 epoch=91 loss=10.2034 val_auc=0.8028
model=gcn top_k=100 fold=7 epoch=92 loss=9.3166 val_auc=0.8027
gcn top_k=100 fold=7: early stopping at epoch 92

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=100 fold=8 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=100 fold=8 epoch=0 loss=246.8535 val_auc=0.5268
model=gcn top_k=100 fold=8 epoch=1 loss=105.0845 val_auc=0.5326
model=gcn top_k=100 fold=8 epoch=2 loss=31.1164 val_auc=0.6915
model=gcn top_k=100 fold=8 epoch=3 loss=17.1860 val_auc=0.6652
model=gcn top_k=100 fold=8 epoch=4 loss=18.4317 val_auc=0.7567
model=gcn top_k=100 fold=8 epoch=5 loss=14.0177 val_auc=0.6811
model=gcn top_k=100 fold=8 epoch=6 loss=14.9991 val_auc=0.7442
model=gcn top_k=100 fold=8 epoch=7 loss=15.3690 val_auc=0.7664
model=gcn top_k=100 fold=8 epoch=8 loss=17.8437 val_auc=0.7530
model=gcn top_k=100 fold=8 epoch=9 loss=17.0020 val_auc=0.7586
model=gcn top_k=100 fold=8 epoch=10 loss=13.1654 val_auc=0.7620
model=gcn top_k=100 fold=8 epoch=11 loss=14.2528 val_auc=0.7706
model=gcn top_k=100 fold=8 epoch=12 loss=12.5089 val_auc=0.7718
model=gcn top_k=100 fold=8 epoch=13 loss=11.7343 val_auc=0.7477
model=gcn top_k=100 fold=8 epoch=14 loss=13.7554 val_auc=0.7451
model=gcn top_k=100 fold=8 epoch=15 loss=13.6182 val_auc=0.7730
model=gcn top_k=100 fold=8 epoch=16 loss=14.5353 val_auc=0.7723
model=gcn top_k=100 fold=8 epoch=17 loss=15.8357 val_auc=0.7715
model=gcn top_k=100 fold=8 epoch=18 loss=12.2179 val_auc=0.7640
model=gcn top_k=100 fold=8 epoch=19 loss=12.2804 val_auc=0.7667
model=gcn top_k=100 fold=8 epoch=20 loss=12.0657 val_auc=0.7701
model=gcn top_k=100 fold=8 epoch=21 loss=11.8618 val_auc=0.7703
model=gcn top_k=100 fold=8 epoch=22 loss=16.8195 val_auc=0.7694
model=gcn top_k=100 fold=8 epoch=23 loss=15.6685 val_auc=0.7681
model=gcn top_k=100 fold=8 epoch=24 loss=12.5453 val_auc=0.7428
model=gcn top_k=100 fold=8 epoch=25 loss=13.7654 val_auc=0.7131
model=gcn top_k=100 fold=8 epoch=26 loss=14.2096 val_auc=0.7425
model=gcn top_k=100 fold=8 epoch=27 loss=12.3449 val_auc=0.7714
gcn top_k=100 fold=8: early stopping at epoch 27

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=100 fold=9 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=gcn top_k=100 fold=9 epoch=0 loss=232.5855 val_auc=0.5289
model=gcn top_k=100 fold=9 epoch=1 loss=82.0897 val_auc=0.5746
model=gcn top_k=100 fold=9 epoch=2 loss=27.9726 val_auc=0.7472
model=gcn top_k=100 fold=9 epoch=3 loss=18.1198 val_auc=0.5422
model=gcn top_k=100 fold=9 epoch=4 loss=41.9735 val_auc=0.5602

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=100 fold=9 epoch=5 loss=30.9077 val_auc=0.7597
model=gcn top_k=100 fold=9 epoch=6 loss=17.8456 val_auc=0.7643
model=gcn top_k=100 fold=9 epoch=7 loss=16.1290 val_auc=0.7731
model=gcn top_k=100 fold=9 epoch=8 loss=14.7370 val_auc=0.7807
model=gcn top_k=100 fold=9 epoch=9 loss=13.6296 val_auc=0.7621
model=gcn top_k=100 fold=9 epoch=10 loss=15.8339 val_auc=0.7692
model=gcn top_k=100 fold=9 epoch=11 loss=13.3529 val_auc=0.7538
model=gcn top_k=100 fold=9 epoch=12 loss=11.3385 val_auc=0.7752
model=gcn top_k=100 fold=9 epoch=13 loss=14.1424 val_auc=0.7854
model=gcn top_k=100 fold=9 epoch=14 loss=13.8321 val_auc=0.7851
model=gcn top_k=100 fold=9 epoch=15 loss=15.1606 val_auc=0.7530
model=gcn top_k=100 fold=9 epoch=16 loss=14.4331 val_auc=0.7415
model=gcn top_k=100 fold=9 epoch=17 loss=13.1959 val_auc=0.7823
model=gcn top_k=100 fold=9 epoch=18 loss=13.9431 val_auc=0.7887
model=gcn top_k=100 fold=9 epoch=19 loss=12.2871 val_auc=0.7896
model=gcn top_k=100 fold=9 epoch=20 loss=13.0820 val_auc=0.7897
model=gcn top_k=100 fold=9 epoch=21 loss=11.7478 val_auc=0.7902
model=gcn top_k=100 fold=9 epoch=22 loss=10.5730 val_auc=0.7905
model=gcn top_k=100 fold=9 epoch=23 loss=11.7130 val_auc=0.7901
model=gcn top_k=100 fold=9 epoch=24 loss=12.9172 val_auc=0.7899
model=gcn top_k=100 fold=9 epoch=25 loss=12.2811 val_auc=0.7890
model=gcn top_k=100 fold=9 epoch=26 loss=13.0588 val_auc=0.7851
model=gcn top_k=100 fold=9 epoch=27 loss=12.7812 val_auc=0.7806
model=gcn top_k=100 fold=9 epoch=28 loss=12.5614 val_auc=0.7889
model=gcn top_k=100 fold=9 epoch=29 loss=11.9903 val_auc=0.7879
model=gcn top_k=100 fold=9 epoch=30 loss=11.2164 val_auc=0.7877
model=gcn top_k=100 fold=9 epoch=31 loss=9.8792 val_auc=0.7812
model=gcn top_k=100 fold=9 epoch=32 loss=12.7379 val_auc=0.7743
model=gcn top_k=100 fold=9 epoch=33 loss=14.5236 val_auc=0.7820
model=gcn top_k=100 fold=9 epoch=34 loss=11.9694 val_auc=0.7882
gcn top_k=100 fold=9: early stopping at epoch 34

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

######## Model=gcn top_k=200 ########

===== Model=gcn top_k=200 fold=0 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=gcn top_k=200 fold=0 epoch=0 loss=318.5415 val_auc=0.5319
model=gcn top_k=200 fold=0 epoch=1 loss=96.6589 val_auc=0.5590
model=gcn top_k=200 fold=0 epoch=2 loss=22.7200 val_auc=0.7319
model=gcn top_k=200 fold=0 epoch=3 loss=16.6294 val_auc=0.5223
model=gcn top_k=200 fold=0 epoch=4 loss=33.3818 val_auc=0.6579
model=gcn top_k=200 fold=0 epoch=5 loss=16.5462 val_auc=0.7595
model=gcn top_k=200 fold=0 epoch=6 loss=13.4919 val_auc=0.7581
model=gcn top_k=200 fold=0 epoch=7 loss=14.9860 val_auc=0.5726
model=gcn top_k=200 fold=0 epoch=8 loss=20.5125 val_auc=0.5538
model=gcn top_k=200 fold=0 epoch=9 loss=22.2494 val_auc=0.6914
model=gcn top_k=200 fold=0 epoch=10 loss=15.9349 val_auc=0.7661
model=gcn top_k=200 fold=0 epoch=11 loss=12.9177 val_auc=0.7525
model=gcn top_k=200 fold=0 epoch=12 loss=16.0133 val_auc=0.7753
model=gcn top_k=200 fold=0 epoch=13 loss=11.6102 val_auc=0.7701
model=gcn top_k=200 fold=0 epoch=14 loss=12.7971 val_auc=0.7783
model=gcn top_k=200 fold=0 epoch=15 loss=14.2645 val_auc=0.7809
model=gcn top_k=200 fold=0 epoch=16 loss=17.2775 val_auc=0.7802
model=gcn top_k=200 fold=0 epoch=17 loss=13.0361 val_auc=0.7693
model=gcn top_k=200 fold=0 epoch=18 loss=15.1776 val_auc=0.7619
model=gcn top_k=200 fold=0 epoch=19 loss=16.7671 val_auc=0.7741
model=gcn top_k=200 fold=0 epoch=20 loss=11.2833 val_auc=0.7789
model=gcn top_k=200 fold=0 epoch=21 loss=14.0691 val_auc=0.7798
model=gcn top_k=200 fold=0 epoch=22 loss=11.7410 val_auc=0.7792
model=gcn top_k=200 fold=0 epoch=23 loss=12.2507 val_auc=0.7742
model=gcn top_k=200 fold=0 epoch=24 loss=12.7132 val_auc=0.7204
model=gcn top_k=200 fold=0 epoch=25 loss=16.0703 val_auc=0.7035
model=gcn top_k=200 fold=0 epoch=26 loss=18.7515 val_auc=0.7564
model=gcn top_k=200 fold=0 epoch=27 loss=13.5162 val_auc=0.7774
gcn top_k=200 fold=0: early stopping at epoch 27

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=200 fold=1 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=200 fold=1 epoch=0 loss=213.0258 val_auc=0.5265
model=gcn top_k=200 fold=1 epoch=1 loss=107.3089 val_auc=0.5326

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=200 fold=1 epoch=2 loss=45.9031 val_auc=0.7084
model=gcn top_k=200 fold=1 epoch=3 loss=16.3048 val_auc=0.7173
model=gcn top_k=200 fold=1 epoch=4 loss=19.0335 val_auc=0.7618
model=gcn top_k=200 fold=1 epoch=5 loss=17.3196 val_auc=0.6310
model=gcn top_k=200 fold=1 epoch=6 loss=12.4626 val_auc=0.6732
model=gcn top_k=200 fold=1 epoch=7 loss=19.3225 val_auc=0.7794
model=gcn top_k=200 fold=1 epoch=8 loss=15.0793 val_auc=0.7840
model=gcn top_k=200 fold=1 epoch=9 loss=16.6385 val_auc=0.7849
model=gcn top_k=200 fold=1 epoch=10 loss=14.3113 val_auc=0.7240
model=gcn top_k=200 fold=1 epoch=11 loss=18.1901 val_auc=0.7485
model=gcn top_k=200 fold=1 epoch=12 loss=14.5632 val_auc=0.7864
model=gcn top_k=200 fold=1 epoch=13 loss=11.9165 val_auc=0.7869
model=gcn top_k=200 fold=1 epoch=14 loss=14.6732 val_auc=0.7862
model=gcn top_k=200 fold=1 epoch=15 loss=12.2681 val_auc=0.7843
model=gcn top_k=200 fold=1 epoch=16 loss=12.0456 val_auc=0.7805
model=gcn top_k=200 fold=1 epoch=17 loss=12.0887 val_auc=0.7840
model=gcn top_k=200 fold=1 epoch=18 loss=13.2191 val_auc=0.7852
model=gcn top_k=200 fold=1 epoch=19 loss=12.9595 val_auc=0.7865
model=gcn top_k=200 fold=1 epoch=20 loss=12.7774 val_auc=0.7863
model=gcn top_k=200 fold=1 epoch=21 loss=14.0198 val_auc=0.7747
model=gcn top_k=200 fold=1 epoch=22 loss=15.3532 val_auc=0.7751
model=gcn top_k=200 fold=1 epoch=23 loss=14.0173 val_auc=0.7866
model=gcn top_k=200 fold=1 epoch=24 loss=13.6952 val_auc=0.7890
model=gcn top_k=200 fold=1 epoch=25 loss=10.1351 val_auc=0.7895
model=gcn top_k=200 fold=1 epoch=26 loss=10.9230 val_auc=0.7900
model=gcn top_k=200 fold=1 epoch=27 loss=11.3792 val_auc=0.7895
model=gcn top_k=200 fold=1 epoch=28 loss=10.2463 val_auc=0.7706
model=gcn top_k=200 fold=1 epoch=29 loss=12.9683 val_auc=0.7518
model=gcn top_k=200 fold=1 epoch=30 loss=14.5975 val_auc=0.7729
model=gcn top_k=200 fold=1 epoch=31 loss=13.2383 val_auc=0.7892
model=gcn top_k=200 fold=1 epoch=32 loss=12.7010 val_auc=0.7920
model=gcn top_k=200 fold=1 epoch=33 loss=11.5675 val_auc=0.7938
model=gcn top_k=200 fold=1 epoch=34 loss=10.7566 val_auc=0.7929
model=gcn top_k=200 fold=1 epoch=35 loss=10.0141 val_auc=0.7812
model=gcn top_k=200 fold=1 epoch=36 loss=10.4607 val_auc=0.7926
model=gcn top_k=200 fold=1 epoch=37 loss=10.8792 val_auc=0.7970
model=gcn top_k=200 fold=1 epoch=38 loss=11.4277 val_auc=0.7970
model=gcn top_k=200 fold=1 epoch=39 loss=11.6524 val_auc=0.7970
model=gcn top_k=200 fold=1 epoch=40 loss=12.7657 val_auc=0.7973
model=gcn top_k=200 fold=1 epoch=41 loss=11.1152 val_auc=0.7969
model=gcn top_k=200 fold=1 epoch=42 loss=11.9656 val_auc=0.7944
model=gcn top_k=200 fold=1 epoch=43 loss=12.3020 val_auc=0.7933
model=gcn top_k=200 fold=1 epoch=44 loss=11.5220 val_auc=0.7935
model=gcn top_k=200 fold=1 epoch=45 loss=10.1928 val_auc=0.7917
model=gcn top_k=200 fold=1 epoch=46 loss=10.9426 val_auc=0.7917
model=gcn top_k=200 fold=1 epoch=47 loss=10.2378 val_auc=0.7917
model=gcn top_k=200 fold=1 epoch=48 loss=9.9123 val_auc=0.7902
model=gcn top_k=200 fold=1 epoch=49 loss=9.7521 val_auc=0.7931
model=gcn top_k=200 fold=1 epoch=50 loss=9.8931 val_auc=0.7958
model=gcn top_k=200 fold=1 epoch=51 loss=9.7113 val_auc=0.7983
model=gcn top_k=200 fold=1 epoch=52 loss=10.1366 val_auc=0.8007
model=gcn top_k=200 fold=1 epoch=53 loss=9.5876 val_auc=0.8023
model=gcn top_k=200 fold=1 epoch=54 loss=9.7902 val_auc=0.8035
model=gcn top_k=200 fold=1 epoch=55 loss=9.3545 val_auc=0.8040
model=gcn top_k=200 fold=1 epoch=56 loss=8.6298 val_auc=0.8045
model=gcn top_k=200 fold=1 epoch=57 loss=12.1333 val_auc=0.8044
model=gcn top_k=200 fold=1 epoch=58 loss=9.3827 val_auc=0.8029
model=gcn top_k=200 fold=1 epoch=59 loss=10.1210 val_auc=0.8015
model=gcn top_k=200 fold=1 epoch=60 loss=10.1701 val_auc=0.8001
model=gcn top_k=200 fold=1 epoch=61 loss=9.4288 val_auc=0.7989
model=gcn top_k=200 fold=1 epoch=62 loss=9.0038 val_auc=0.7976
model=gcn top_k=200 fold=1 epoch=63 loss=10.0858 val_auc=0.7965
model=gcn top_k=200 fold=1 epoch=64 loss=10.7658 val_auc=0.7959
model=gcn top_k=200 fold=1 epoch=65 loss=11.0736 val_auc=0.7956
model=gcn top_k=200 fold=1 epoch=66 loss=9.1178 val_auc=0.7959
model=gcn top_k=200 fold=1 epoch=67 loss=10.3898 val_auc=0.7959
model=gcn top_k=200 fold=1 epoch=68 loss=10.2659 val_auc=0.7959
gcn top_k=200 fold=1: early stopping at epoch 68

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=200 fold=2 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=gcn top_k=200 fold=2 epoch=0 loss=291.9154 val_auc=0.5255
model=gcn top_k=200 fold=2 epoch=1 loss=111.5563 val_auc=0.5328
model=gcn top_k=200 fold=2 epoch=2 loss=35.6537 val_auc=0.7202
model=gcn top_k=200 fold=2 epoch=3 loss=20.0167 val_auc=0.5032
model=gcn top_k=200 fold=2 epoch=4 loss=36.7772 val_auc=0.5624
model=gcn top_k=200 fold=2 epoch=5 loss=26.8571 val_auc=0.7489
model=gcn top_k=200 fold=2 epoch=6 loss=15.7389 val_auc=0.7549
model=gcn top_k=200 fold=2 epoch=7 loss=18.1251 val_auc=0.7194
model=gcn top_k=200 fold=2 epoch=8 loss=13.3823 val_auc=0.6455
model=gcn top_k=200 fold=2 epoch=9 loss=20.5954 val_auc=0.7264
model=gcn top_k=200 fold=2 epoch=10 loss=17.7227 val_auc=0.7648
model=gcn top_k=200 fold=2 epoch=11 loss=12.6521 val_auc=0.7673
model=gcn top_k=200 fold=2 epoch=12 loss=13.4276 val_auc=0.7664
model=gcn top_k=200 fold=2 epoch=13 loss=13.1351 val_auc=0.7347
model=gcn top_k=200 fold=2 epoch=14 loss=15.1416 val_auc=0.7417
model=gcn top_k=200 fold=2 epoch=15 loss=18.1370 val_auc=0.7697
model=gcn top_k=200 fold=2 epoch=16 loss=10.8088 val_auc=0.7704
model=gcn top_k=200 fold=2 epoch=17 loss=15.7218 val_auc=0.7707
model=gcn top_k=200 fold=2 epoch=18 loss=16.0819 val_auc=0.7684
model=gcn top_k=200 fold=2 epoch=19 loss=14.0561 val_auc=0.7082
model=gcn top_k=200 fold=2 epoch=20 loss=15.5203 val_auc=0.6935
model=gcn top_k=200 fold=2 epoch=21 loss=16.4990 val_auc=0.7507
model=gcn top_k=200 fold=2 epoch=22 loss=14.3739 val_auc=0.7729
model=gcn top_k=200 fold=2 epoch=23 loss=13.6538 val_auc=0.7737
model=gcn top_k=200 fold=2 epoch=24 loss=12.3301 val_auc=0.7738
model=gcn top_k=200 fold=2 epoch=25 loss=13.6804 val_auc=0.7743
model=gcn top_k=200 fold=2 epoch=26 loss=13.0851 val_auc=0.7752
model=gcn top_k=200 fold=2 epoch=27 loss=11.9134 val_auc=0.7648
model=gcn top_k=200 fold=2 epoch=28 loss=13.6202 val_auc=0.7622
model=gcn top_k=200 fold=2 epoch=29 loss=15.3759 val_auc=0.7680
model=gcn top_k=200 fold=2 epoch=30 loss=14.3716 val_auc=0.7749
model=gcn top_k=200 fold=2 epoch=31 loss=10.9693 val_auc=0.7750
model=gcn top_k=200 fold=2 epoch=32 loss=10.9744 val_auc=0.7742
model=gcn top_k=200 fold=2 epoch=33 loss=11.4484 val_auc=0.7713
model=gcn top_k=200 fold=2 epoch=34 loss=10.4101 val_auc=0.7644
model=gcn top_k=200 fold=2 epoch=35 loss=13.6249 val_auc=0.7648
model=gcn top_k=200 fold=2 epoch=36 loss=12.2727 val_auc=0.7707
model=gcn top_k=200 fold=2 epoch=37 loss=10.5596 val_auc=0.7737
model=gcn top_k=200 fold=2 epoch=38 loss=10.1562 val_auc=0.7759
model=gcn top_k=200 fold=2 epoch=39 loss=11.3644 val_auc=0.7781
model=gcn top_k=200 fold=2 epoch=40 loss=11.1505 val_auc=0.7791
model=gcn top_k=200 fold=2 epoch=41 loss=11.2723 val_auc=0.7800
model=gcn top_k=200 fold=2 epoch=42 loss=10.7569 val_auc=0.7816
model=gcn top_k=200 fold=2 epoch=43 loss=12.2902 val_auc=0.7830
model=gcn top_k=200 fold=2 epoch=44 loss=9.6779 val_auc=0.7848
model=gcn top_k=200 fold=2 epoch=45 loss=11.9558 val_auc=0.7852
model=gcn top_k=200 fold=2 epoch=46 loss=10.4366 val_auc=0.7819
model=gcn top_k=200 fold=2 epoch=47 loss=10.6119 val_auc=0.7811
model=gcn top_k=200 fold=2 epoch=48 loss=12.6274 val_auc=0.7818
model=gcn top_k=200 fold=2 epoch=49 loss=11.1548 val_auc=0.7825
model=gcn top_k=200 fold=2 epoch=50 loss=11.4299 val_auc=0.7824
model=gcn top_k=200 fold=2 epoch=51 loss=10.0443 val_auc=0.7819
model=gcn top_k=200 fold=2 epoch=52 loss=11.5776 val_auc=0.7816
model=gcn top_k=200 fold=2 epoch=53 loss=14.6108 val_auc=0.7797
model=gcn top_k=200 fold=2 epoch=54 loss=12.5002 val_auc=0.7769
model=gcn top_k=200 fold=2 epoch=55 loss=12.6140 val_auc=0.7745
model=gcn top_k=200 fold=2 epoch=56 loss=10.3133 val_auc=0.7796
model=gcn top_k=200 fold=2 epoch=57 loss=10.5576 val_auc=0.7825
gcn top_k=200 fold=2: early stopping at epoch 57

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=200 fold=3 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=gcn top_k=200 fold=3 epoch=0 loss=243.0765 val_auc=0.5234
model=gcn top_k=200 fold=3 epoch=1 loss=72.2316 val_auc=0.5717
model=gcn top_k=200 fold=3 epoch=2 loss=27.2720 val_auc=0.7176
model=gcn top_k=200 fold=3 epoch=3 loss=19.5741 val_auc=0.6034
model=gcn top_k=200 fold=3 epoch=4 loss=22.1125 val_auc=0.7321
model=gcn top_k=200 fold=3 epoch=5 loss=17.4434 val_auc=0.7674
model=gcn top_k=200 fold=3 epoch=6 loss=16.4535 val_auc=0.7739
model=gcn top_k=200 fold=3 epoch=7 loss=16.9836 val_auc=0.7607
model=gcn top_k=200 fold=3 epoch=8 loss=18.7260 val_auc=0.7003
model=gcn top_k=200 fold=3 epoch=9 loss=22.9431 val_auc=0.7521
model=gcn top_k=200 fold=3 epoch=10 loss=15.1075 val_auc=0.7805
model=gcn top_k=200 fold=3 epoch=11 loss=13.6614 val_auc=0.7809
model=gcn top_k=200 fold=3 epoch=12 loss=14.1040 val_auc=0.7800
model=gcn top_k=200 fold=3 epoch=13 loss=13.2079 val_auc=0.7815
model=gcn top_k=200 fold=3 epoch=14 loss=12.1621 val_auc=0.7613
model=gcn top_k=200 fold=3 epoch=15 loss=13.9028 val_auc=0.7596
model=gcn top_k=200 fold=3 epoch=16 loss=15.5351 val_auc=0.7815
model=gcn top_k=200 fold=3 epoch=17 loss=12.2620 val_auc=0.7840
model=gcn top_k=200 fold=3 epoch=18 loss=14.9986 val_auc=0.7839
model=gcn top_k=200 fold=3 epoch=19 loss=12.1800 val_auc=0.7827
model=gcn top_k=200 fold=3 epoch=20 loss=11.0830 val_auc=0.7600
model=gcn top_k=200 fold=3 epoch=21 loss=10.7649 val_auc=0.7585
model=gcn top_k=200 fold=3 epoch=22 loss=15.7837 val_auc=0.7803
model=gcn top_k=200 fold=3 epoch=23 loss=10.9967 val_auc=0.7853
model=gcn top_k=200 fold=3 epoch=24 loss=14.6888 val_auc=0.7856
model=gcn top_k=200 fold=3 epoch=25 loss=14.9913 val_auc=0.7857
model=gcn top_k=200 fold=3 epoch=26 loss=12.4770 val_auc=0.7862
model=gcn top_k=200 fold=3 epoch=27 loss=13.8382 val_auc=0.7735
model=gcn top_k=200 fold=3 epoch=28 loss=10.8341 val_auc=0.7385
model=gcn top_k=200 fold=3 epoch=29 loss=16.3946 val_auc=0.7614
model=gcn top_k=200 fold=3 epoch=30 loss=15.0990 val_auc=0.7833
model=gcn top_k=200 fold=3 epoch=31 loss=9.4620 val_auc=0.7850
model=gcn top_k=200 fold=3 epoch=32 loss=11.2835 val_auc=0.7844
model=gcn top_k=200 fold=3 epoch=33 loss=13.1961 val_auc=0.7840
model=gcn top_k=200 fold=3 epoch=34 loss=11.2795 val_auc=0.7835
model=gcn top_k=200 fold=3 epoch=35 loss=11.3593 val_auc=0.7818
model=gcn top_k=200 fold=3 epoch=36 loss=10.1044 val_auc=0.7828
model=gcn top_k=200 fold=3 epoch=37 loss=9.7874 val_auc=0.7858
model=gcn top_k=200 fold=3 epoch=38 loss=10.3145 val_auc=0.7872
model=gcn top_k=200 fold=3 epoch=39 loss=9.7267 val_auc=0.7887
model=gcn top_k=200 fold=3 epoch=40 loss=9.4523 val_auc=0.7905
model=gcn top_k=200 fold=3 epoch=41 loss=9.7569 val_auc=0.7916
model=gcn top_k=200 fold=3 epoch=42 loss=11.6262 val_auc=0.7912
model=gcn top_k=200 fold=3 epoch=43 loss=11.0091 val_auc=0.7924
model=gcn top_k=200 fold=3 epoch=44 loss=13.1064 val_auc=0.7927
model=gcn top_k=200 fold=3 epoch=45 loss=10.5641 val_auc=0.7931
model=gcn top_k=200 fold=3 epoch=46 loss=9.8104 val_auc=0.7914
model=gcn top_k=200 fold=3 epoch=47 loss=11.0758 val_auc=0.7872
model=gcn top_k=200 fold=3 epoch=48 loss=10.6858 val_auc=0.7911
model=gcn top_k=200 fold=3 epoch=49 loss=12.5780 val_auc=0.7938
model=gcn top_k=200 fold=3 epoch=50 loss=9.7112 val_auc=0.7942
model=gcn top_k=200 fold=3 epoch=51 loss=10.1636 val_auc=0.7945
model=gcn top_k=200 fold=3 epoch=52 loss=9.3785 val_auc=0.7927
model=gcn top_k=200 fold=3 epoch=53 loss=12.8314 val_auc=0.7929
model=gcn top_k=200 fold=3 epoch=54 loss=11.1552 val_auc=0.7951
model=gcn top_k=200 fold=3 epoch=55 loss=9.1594 val_auc=0.7953
model=gcn top_k=200 fold=3 epoch=56 loss=9.1488 val_auc=0.7961
model=gcn top_k=200 fold=3 epoch=57 loss=9.0297 val_auc=0.7963
model=gcn top_k=200 fold=3 epoch=58 loss=11.8157 val_auc=0.7968
model=gcn top_k=200 fold=3 epoch=59 loss=9.6625 val_auc=0.7954
model=gcn top_k=200 fold=3 epoch=60 loss=10.1115 val_auc=0.7889
model=gcn top_k=200 fold=3 epoch=61 loss=13.2603 val_auc=0.7893
model=gcn top_k=200 fold=3 epoch=62 loss=11.3621 val_auc=0.7961
model=gcn top_k=200 fold=3 epoch=63 loss=10.2972 val_auc=0.7982
model=gcn top_k=200 fold=3 epoch=64 loss=10.2212 val_auc=0.7986
model=gcn top_k=200 fold=3 epoch=65 loss=9.2624 val_auc=0.7986
model=gcn top_k=200 fold=3 epoch=66 loss=8.5575 val_auc=0.7980
model=gcn top_k=200 fold=3 epoch=67 loss=9.7588 val_auc=0.7966
model=gcn top_k=200 fold=3 epoch=68 loss=11.0935 val_auc=0.7965
model=gcn top_k=200 fold=3 epoch=69 loss=9.2215 val_auc=0.7977
model=gcn top_k=200 fold=3 epoch=70 loss=8.2516 val_auc=0.7988
model=gcn top_k=200 fold=3 epoch=71 loss=8.4022 val_auc=0.7992
model=gcn top_k=200 fold=3 epoch=72 loss=9.4772 val_auc=0.8007
model=gcn top_k=200 fold=3 epoch=73 loss=8.4953 val_auc=0.8016
model=gcn top_k=200 fold=3 epoch=74 loss=9.6031 val_auc=0.8025
model=gcn top_k=200 fold=3 epoch=75 loss=9.6298 val_auc=0.8035
model=gcn top_k=200 fold=3 epoch=76 loss=8.8415 val_auc=0.8034
model=gcn top_k=200 fold=3 epoch=77 loss=8.3759 val_auc=0.7998
model=gcn top_k=200 fold=3 epoch=78 loss=8.2764 val_auc=0.7940
model=gcn top_k=200 fold=3 epoch=79 loss=11.3417 val_auc=0.8027
model=gcn top_k=200 fold=3 epoch=80 loss=10.3240 val_auc=0.8058
model=gcn top_k=200 fold=3 epoch=81 loss=8.7113 val_auc=0.8050
model=gcn top_k=200 fold=3 epoch=82 loss=9.7640 val_auc=0.8042
model=gcn top_k=200 fold=3 epoch=83 loss=8.9236 val_auc=0.8031
model=gcn top_k=200 fold=3 epoch=84 loss=9.3112 val_auc=0.8010
model=gcn top_k=200 fold=3 epoch=85 loss=8.3103 val_auc=0.7984
model=gcn top_k=200 fold=3 epoch=86 loss=9.5604 val_auc=0.7992
model=gcn top_k=200 fold=3 epoch=87 loss=8.6063 val_auc=0.8018
model=gcn top_k=200 fold=3 epoch=88 loss=8.8073 val_auc=0.8016
model=gcn top_k=200 fold=3 epoch=89 loss=9.4457 val_auc=0.8011
model=gcn top_k=200 fold=3 epoch=90 loss=8.3511 val_auc=0.7996
model=gcn top_k=200 fold=3 epoch=91 loss=9.8010 val_auc=0.8008
model=gcn top_k=200 fold=3 epoch=92 loss=9.8278 val_auc=0.8031
gcn top_k=200 fold=3: early stopping at epoch 92

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=200 fold=4 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=gcn top_k=200 fold=4 epoch=0 loss=254.1967 val_auc=0.5123
model=gcn top_k=200 fold=4 epoch=1 loss=93.0468 val_auc=0.5286
model=gcn top_k=200 fold=4 epoch=2 loss=29.7423 val_auc=0.7154
model=gcn top_k=200 fold=4 epoch=3 loss=19.2254 val_auc=0.5463
model=gcn top_k=200 fold=4 epoch=4 loss=25.4341 val_auc=0.6434

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=200 fold=4 epoch=5 loss=21.3088 val_auc=0.7559
model=gcn top_k=200 fold=4 epoch=6 loss=21.2293 val_auc=0.7595
model=gcn top_k=200 fold=4 epoch=7 loss=13.8360 val_auc=0.6854

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=200 fold=4 epoch=8 loss=17.4350 val_auc=0.7628

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=200 fold=4 epoch=9 loss=13.8575 val_auc=0.7715
model=gcn top_k=200 fold=4 epoch=10 loss=12.7302 val_auc=0.7712
model=gcn top_k=200 fold=4 epoch=11 loss=14.7117 val_auc=0.7624
model=gcn top_k=200 fold=4 epoch=12 loss=12.7579 val_auc=0.7709
model=gcn top_k=200 fold=4 epoch=13 loss=12.0072 val_auc=0.7745
model=gcn top_k=200 fold=4 epoch=14 loss=15.3666 val_auc=0.7747
model=gcn top_k=200 fold=4 epoch=15 loss=13.3240 val_auc=0.7731
model=gcn top_k=200 fold=4 epoch=16 loss=11.8639 val_auc=0.7626
model=gcn top_k=200 fold=4 epoch=17 loss=11.9813 val_auc=0.7748
model=gcn top_k=200 fold=4 epoch=18 loss=11.5009 val_auc=0.7786
model=gcn top_k=200 fold=4 epoch=19 loss=12.2998 val_auc=0.7797
model=gcn top_k=200 fold=4 epoch=20 loss=15.0498 val_auc=0.7808
model=gcn top_k=200 fold=4 epoch=21 loss=13.4499 val_auc=0.7818
model=gcn top_k=200 fold=4 epoch=22 loss=15.2446 val_auc=0.7787
model=gcn top_k=200 fold=4 epoch=23 loss=11.7117 val_auc=0.7634
model=gcn top_k=200 fold=4 epoch=24 loss=12.7664 val_auc=0.7583
model=gcn top_k=200 fold=4 epoch=25 loss=12.4582 val_auc=0.7761
model=gcn top_k=200 fold=4 epoch=26 loss=10.5874 val_auc=0.7839
model=gcn top_k=200 fold=4 epoch=27 loss=10.7586 val_auc=0.7850
model=gcn top_k=200 fold=4 epoch=28 loss=12.6003 val_auc=0.7854
model=gcn top_k=200 fold=4 epoch=29 loss=11.6252 val_auc=0.7857
model=gcn top_k=200 fold=4 epoch=30 loss=9.7859 val_auc=0.7863
model=gcn top_k=200 fold=4 epoch=31 loss=9.1804 val_auc=0.7835
model=gcn top_k=200 fold=4 epoch=32 loss=10.2139 val_auc=0.7819
model=gcn top_k=200 fold=4 epoch=33 loss=13.6998 val_auc=0.7846
model=gcn top_k=200 fold=4 epoch=34 loss=13.5298 val_auc=0.7869
model=gcn top_k=200 fold=4 epoch=35 loss=11.1213 val_auc=0.7868
model=gcn top_k=200 fold=4 epoch=36 loss=12.1147 val_auc=0.7862
model=gcn top_k=200 fold=4 epoch=37 loss=9.3166 val_auc=0.7847
model=gcn top_k=200 fold=4 epoch=38 loss=12.7936 val_auc=0.7842
model=gcn top_k=200 fold=4 epoch=39 loss=10.7980 val_auc=0.7865
model=gcn top_k=200 fold=4 epoch=40 loss=10.3507 val_auc=0.7877
model=gcn top_k=200 fold=4 epoch=41 loss=10.0684 val_auc=0.7869
model=gcn top_k=200 fold=4 epoch=42 loss=10.5325 val_auc=0.7880
model=gcn top_k=200 fold=4 epoch=43 loss=11.9212 val_auc=0.7892
model=gcn top_k=200 fold=4 epoch=44 loss=10.4122 val_auc=0.7891
model=gcn top_k=200 fold=4 epoch=45 loss=10.6253 val_auc=0.7887
model=gcn top_k=200 fold=4 epoch=46 loss=10.8575 val_auc=0.7873
model=gcn top_k=200 fold=4 epoch=47 loss=9.7235 val_auc=0.7882
model=gcn top_k=200 fold=4 epoch=48 loss=9.5528 val_auc=0.7880
model=gcn top_k=200 fold=4 epoch=49 loss=10.4893 val_auc=0.7868
model=gcn top_k=200 fold=4 epoch=50 loss=10.2761 val_auc=0.7859
model=gcn top_k=200 fold=4 epoch=51 loss=12.9700 val_auc=0.7879
model=gcn top_k=200 fold=4 epoch=52 loss=12.0996 val_auc=0.7895
model=gcn top_k=200 fold=4 epoch=53 loss=9.3804 val_auc=0.7894
model=gcn top_k=200 fold=4 epoch=54 loss=11.0303 val_auc=0.7912
model=gcn top_k=200 fold=4 epoch=55 loss=10.3765 val_auc=0.7888
model=gcn top_k=200 fold=4 epoch=56 loss=11.5115 val_auc=0.7897
model=gcn top_k=200 fold=4 epoch=57 loss=10.6367 val_auc=0.7928
model=gcn top_k=200 fold=4 epoch=58 loss=11.5653 val_auc=0.7938
model=gcn top_k=200 fold=4 epoch=59 loss=9.2302 val_auc=0.7931
model=gcn top_k=200 fold=4 epoch=60 loss=9.6746 val_auc=0.7927
model=gcn top_k=200 fold=4 epoch=61 loss=10.2072 val_auc=0.7924
model=gcn top_k=200 fold=4 epoch=62 loss=10.7466 val_auc=0.7901
model=gcn top_k=200 fold=4 epoch=63 loss=8.1904 val_auc=0.7897
model=gcn top_k=200 fold=4 epoch=64 loss=10.2475 val_auc=0.7906
model=gcn top_k=200 fold=4 epoch=65 loss=9.8032 val_auc=0.7930
model=gcn top_k=200 fold=4 epoch=66 loss=12.5686 val_auc=0.7924
model=gcn top_k=200 fold=4 epoch=67 loss=10.4116 val_auc=0.7913
model=gcn top_k=200 fold=4 epoch=68 loss=8.2760 val_auc=0.7916
model=gcn top_k=200 fold=4 epoch=69 loss=10.1510 val_auc=0.7864
model=gcn top_k=200 fold=4 epoch=70 loss=10.9146 val_auc=0.7828
gcn top_k=200 fold=4: early stopping at epoch 70

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=200 fold=5 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=gcn top_k=200 fold=5 epoch=0 loss=322.4745 val_auc=0.4929
model=gcn top_k=200 fold=5 epoch=1 loss=127.7211 val_auc=0.5373
model=gcn top_k=200 fold=5 epoch=2 loss=44.7765 val_auc=0.6546
model=gcn top_k=200 fold=5 epoch=3 loss=15.7782 val_auc=0.6848
model=gcn top_k=200 fold=5 epoch=4 loss=26.1414 val_auc=0.7470
model=gcn top_k=200 fold=5 epoch=5 loss=19.5634 val_auc=0.7260
model=gcn top_k=200 fold=5 epoch=6 loss=14.8226 val_auc=0.7478

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=200 fold=5 epoch=7 loss=14.6605 val_auc=0.7761
model=gcn top_k=200 fold=5 epoch=8 loss=16.7832 val_auc=0.7769
model=gcn top_k=200 fold=5 epoch=9 loss=13.9183 val_auc=0.6466
model=gcn top_k=200 fold=5 epoch=10 loss=25.6461 val_auc=0.6412
model=gcn top_k=200 fold=5 epoch=11 loss=24.8938 val_auc=0.7667
model=gcn top_k=200 fold=5 epoch=12 loss=14.9779 val_auc=0.7805
model=gcn top_k=200 fold=5 epoch=13 loss=12.2975 val_auc=0.7812
model=gcn top_k=200 fold=5 epoch=14 loss=13.8217 val_auc=0.7804
model=gcn top_k=200 fold=5 epoch=15 loss=11.9707 val_auc=0.7830
model=gcn top_k=200 fold=5 epoch=16 loss=13.4474 val_auc=0.7824
model=gcn top_k=200 fold=5 epoch=17 loss=12.8743 val_auc=0.7802
model=gcn top_k=200 fold=5 epoch=18 loss=11.7973 val_auc=0.7838
model=gcn top_k=200 fold=5 epoch=19 loss=11.4984 val_auc=0.7857
model=gcn top_k=200 fold=5 epoch=20 loss=12.4587 val_auc=0.7860
model=gcn top_k=200 fold=5 epoch=21 loss=10.7461 val_auc=0.7824
model=gcn top_k=200 fold=5 epoch=22 loss=10.2076 val_auc=0.7803
model=gcn top_k=200 fold=5 epoch=23 loss=12.9726 val_auc=0.7851
model=gcn top_k=200 fold=5 epoch=24 loss=10.7368 val_auc=0.7909
model=gcn top_k=200 fold=5 epoch=25 loss=12.3120 val_auc=0.7929
model=gcn top_k=200 fold=5 epoch=26 loss=11.6981 val_auc=0.7938
model=gcn top_k=200 fold=5 epoch=27 loss=12.3132 val_auc=0.7890
model=gcn top_k=200 fold=5 epoch=28 loss=12.0651 val_auc=0.7862
model=gcn top_k=200 fold=5 epoch=29 loss=11.4170 val_auc=0.7938
model=gcn top_k=200 fold=5 epoch=30 loss=11.4620 val_auc=0.7963
model=gcn top_k=200 fold=5 epoch=31 loss=10.8734 val_auc=0.7965
model=gcn top_k=200 fold=5 epoch=32 loss=13.3486 val_auc=0.7965
model=gcn top_k=200 fold=5 epoch=33 loss=12.7638 val_auc=0.7949
model=gcn top_k=200 fold=5 epoch=34 loss=10.4473 val_auc=0.7938
model=gcn top_k=200 fold=5 epoch=35 loss=9.8553 val_auc=0.7955
model=gcn top_k=200 fold=5 epoch=36 loss=11.0186 val_auc=0.7963
model=gcn top_k=200 fold=5 epoch=37 loss=11.4030 val_auc=0.7961
model=gcn top_k=200 fold=5 epoch=38 loss=10.4545 val_auc=0.7957
model=gcn top_k=200 fold=5 epoch=39 loss=10.4441 val_auc=0.7968
model=gcn top_k=200 fold=5 epoch=40 loss=11.6125 val_auc=0.7972
model=gcn top_k=200 fold=5 epoch=41 loss=10.6777 val_auc=0.7950
model=gcn top_k=200 fold=5 epoch=42 loss=11.4024 val_auc=0.7964
model=gcn top_k=200 fold=5 epoch=43 loss=10.7270 val_auc=0.7980
model=gcn top_k=200 fold=5 epoch=44 loss=10.2493 val_auc=0.7992
model=gcn top_k=200 fold=5 epoch=45 loss=12.1180 val_auc=0.7997
model=gcn top_k=200 fold=5 epoch=46 loss=10.1908 val_auc=0.7981
model=gcn top_k=200 fold=5 epoch=47 loss=10.8350 val_auc=0.7986
model=gcn top_k=200 fold=5 epoch=48 loss=12.3297 val_auc=0.8002
model=gcn top_k=200 fold=5 epoch=49 loss=10.1087 val_auc=0.7999
model=gcn top_k=200 fold=5 epoch=50 loss=10.0830 val_auc=0.8026
model=gcn top_k=200 fold=5 epoch=51 loss=11.6093 val_auc=0.8037
model=gcn top_k=200 fold=5 epoch=52 loss=9.2230 val_auc=0.7883
model=gcn top_k=200 fold=5 epoch=53 loss=12.2489 val_auc=0.7762
model=gcn top_k=200 fold=5 epoch=54 loss=13.7329 val_auc=0.7896
model=gcn top_k=200 fold=5 epoch=55 loss=13.1589 val_auc=0.8015
model=gcn top_k=200 fold=5 epoch=56 loss=9.8238 val_auc=0.8015
model=gcn top_k=200 fold=5 epoch=57 loss=8.8443 val_auc=0.8008
model=gcn top_k=200 fold=5 epoch=58 loss=10.4265 val_auc=0.8008
model=gcn top_k=200 fold=5 epoch=59 loss=12.6546 val_auc=0.8004
model=gcn top_k=200 fold=5 epoch=60 loss=9.1885 val_auc=0.7961
model=gcn top_k=200 fold=5 epoch=61 loss=10.7809 val_auc=0.7927
model=gcn top_k=200 fold=5 epoch=62 loss=12.9398 val_auc=0.7973
model=gcn top_k=200 fold=5 epoch=63 loss=10.2184 val_auc=0.8039
model=gcn top_k=200 fold=5 epoch=64 loss=10.1417 val_auc=0.8059
model=gcn top_k=200 fold=5 epoch=65 loss=9.3867 val_auc=0.8073
model=gcn top_k=200 fold=5 epoch=66 loss=9.3556 val_auc=0.8085
model=gcn top_k=200 fold=5 epoch=67 loss=11.3508 val_auc=0.8098
model=gcn top_k=200 fold=5 epoch=68 loss=10.3158 val_auc=0.8100
model=gcn top_k=200 fold=5 epoch=69 loss=10.4652 val_auc=0.8080
model=gcn top_k=200 fold=5 epoch=70 loss=10.3402 val_auc=0.8080
model=gcn top_k=200 fold=5 epoch=71 loss=11.1085 val_auc=0.8098
model=gcn top_k=200 fold=5 epoch=72 loss=8.5710 val_auc=0.8095
model=gcn top_k=200 fold=5 epoch=73 loss=9.4903 val_auc=0.8094
model=gcn top_k=200 fold=5 epoch=74 loss=9.4596 val_auc=0.8085
model=gcn top_k=200 fold=5 epoch=75 loss=12.0199 val_auc=0.8073
model=gcn top_k=200 fold=5 epoch=76 loss=9.8784 val_auc=0.8048
model=gcn top_k=200 fold=5 epoch=77 loss=9.5328 val_auc=0.8036
model=gcn top_k=200 fold=5 epoch=78 loss=9.2839 val_auc=0.8045
model=gcn top_k=200 fold=5 epoch=79 loss=9.3653 val_auc=0.8034
model=gcn top_k=200 fold=5 epoch=80 loss=9.4513 val_auc=0.8014
gcn top_k=200 fold=5: early stopping at epoch 80

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=200 fold=6 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=200 fold=6 epoch=0 loss=278.8412 val_auc=0.5122
model=gcn top_k=200 fold=6 epoch=1 loss=103.3556 val_auc=0.5126

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=200 fold=6 epoch=2 loss=31.5514 val_auc=0.6784
model=gcn top_k=200 fold=6 epoch=3 loss=19.9722 val_auc=0.7301
model=gcn top_k=200 fold=6 epoch=4 loss=18.9912 val_auc=0.6399
model=gcn top_k=200 fold=6 epoch=5 loss=17.9227 val_auc=0.7851
model=gcn top_k=200 fold=6 epoch=6 loss=17.3914 val_auc=0.7082
model=gcn top_k=200 fold=6 epoch=7 loss=15.7177 val_auc=0.7708
model=gcn top_k=200 fold=6 epoch=8 loss=14.9923 val_auc=0.7923
model=gcn top_k=200 fold=6 epoch=9 loss=14.5639 val_auc=0.7910
model=gcn top_k=200 fold=6 epoch=10 loss=15.0990 val_auc=0.7590
model=gcn top_k=200 fold=6 epoch=11 loss=16.0471 val_auc=0.7824
model=gcn top_k=200 fold=6 epoch=12 loss=14.0997 val_auc=0.7989
model=gcn top_k=200 fold=6 epoch=13 loss=15.0759 val_auc=0.7995
model=gcn top_k=200 fold=6 epoch=14 loss=16.3160 val_auc=0.7982
model=gcn top_k=200 fold=6 epoch=15 loss=13.0768 val_auc=0.7807
model=gcn top_k=200 fold=6 epoch=16 loss=15.7978 val_auc=0.7892
model=gcn top_k=200 fold=6 epoch=17 loss=13.1996 val_auc=0.7993
model=gcn top_k=200 fold=6 epoch=18 loss=12.0990 val_auc=0.8010
model=gcn top_k=200 fold=6 epoch=19 loss=12.1087 val_auc=0.8006
model=gcn top_k=200 fold=6 epoch=20 loss=11.6370 val_auc=0.7950
model=gcn top_k=200 fold=6 epoch=21 loss=11.5435 val_auc=0.7973
model=gcn top_k=200 fold=6 epoch=22 loss=13.8015 val_auc=0.8004
model=gcn top_k=200 fold=6 epoch=23 loss=11.7941 val_auc=0.8015
model=gcn top_k=200 fold=6 epoch=24 loss=11.0102 val_auc=0.8013
model=gcn top_k=200 fold=6 epoch=25 loss=9.9344 val_auc=0.7888
model=gcn top_k=200 fold=6 epoch=26 loss=12.7805 val_auc=0.7792
model=gcn top_k=200 fold=6 epoch=27 loss=15.9322 val_auc=0.7974
model=gcn top_k=200 fold=6 epoch=28 loss=13.8302 val_auc=0.8051
model=gcn top_k=200 fold=6 epoch=29 loss=11.7825 val_auc=0.8056
model=gcn top_k=200 fold=6 epoch=30 loss=12.2269 val_auc=0.8053
model=gcn top_k=200 fold=6 epoch=31 loss=12.6796 val_auc=0.8016
model=gcn top_k=200 fold=6 epoch=32 loss=10.5300 val_auc=0.7957
model=gcn top_k=200 fold=6 epoch=33 loss=13.1740 val_auc=0.7977
model=gcn top_k=200 fold=6 epoch=34 loss=12.1896 val_auc=0.8017
model=gcn top_k=200 fold=6 epoch=35 loss=11.9813 val_auc=0.8042
model=gcn top_k=200 fold=6 epoch=36 loss=11.2886 val_auc=0.8063
model=gcn top_k=200 fold=6 epoch=37 loss=11.9720 val_auc=0.8062
model=gcn top_k=200 fold=6 epoch=38 loss=9.9414 val_auc=0.8025
model=gcn top_k=200 fold=6 epoch=39 loss=10.7870 val_auc=0.8009
model=gcn top_k=200 fold=6 epoch=40 loss=11.2130 val_auc=0.8031
model=gcn top_k=200 fold=6 epoch=41 loss=10.5459 val_auc=0.8075
model=gcn top_k=200 fold=6 epoch=42 loss=10.1032 val_auc=0.8087
model=gcn top_k=200 fold=6 epoch=43 loss=10.8520 val_auc=0.8095
model=gcn top_k=200 fold=6 epoch=44 loss=11.1740 val_auc=0.8103
model=gcn top_k=200 fold=6 epoch=45 loss=9.9740 val_auc=0.8109
model=gcn top_k=200 fold=6 epoch=46 loss=9.8339 val_auc=0.8023
model=gcn top_k=200 fold=6 epoch=47 loss=10.2482 val_auc=0.7898
model=gcn top_k=200 fold=6 epoch=48 loss=12.2462 val_auc=0.7987
model=gcn top_k=200 fold=6 epoch=49 loss=11.2421 val_auc=0.8110
model=gcn top_k=200 fold=6 epoch=50 loss=11.1601 val_auc=0.8132
model=gcn top_k=200 fold=6 epoch=51 loss=11.3225 val_auc=0.8143
model=gcn top_k=200 fold=6 epoch=52 loss=12.3165 val_auc=0.8151
model=gcn top_k=200 fold=6 epoch=53 loss=12.9551 val_auc=0.8146
model=gcn top_k=200 fold=6 epoch=54 loss=11.0462 val_auc=0.8093
model=gcn top_k=200 fold=6 epoch=55 loss=12.7745 val_auc=0.8057
model=gcn top_k=200 fold=6 epoch=56 loss=10.1971 val_auc=0.8111
model=gcn top_k=200 fold=6 epoch=57 loss=9.3367 val_auc=0.8130
model=gcn top_k=200 fold=6 epoch=58 loss=9.2379 val_auc=0.8128
model=gcn top_k=200 fold=6 epoch=59 loss=11.3550 val_auc=0.8126
model=gcn top_k=200 fold=6 epoch=60 loss=11.7517 val_auc=0.8131
model=gcn top_k=200 fold=6 epoch=61 loss=8.8426 val_auc=0.8135
model=gcn top_k=200 fold=6 epoch=62 loss=10.8185 val_auc=0.8105
model=gcn top_k=200 fold=6 epoch=63 loss=12.8598 val_auc=0.8069
model=gcn top_k=200 fold=6 epoch=64 loss=12.4843 val_auc=0.8097
gcn top_k=200 fold=6: early stopping at epoch 64

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=200 fold=7 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=gcn top_k=200 fold=7 epoch=0 loss=280.7559 val_auc=0.5244
model=gcn top_k=200 fold=7 epoch=1 loss=78.9042 val_auc=0.5406

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=200 fold=7 epoch=2 loss=30.9526 val_auc=0.6705

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=200 fold=7 epoch=3 loss=25.5763 val_auc=0.5969
model=gcn top_k=200 fold=7 epoch=4 loss=19.8492 val_auc=0.6783
model=gcn top_k=200 fold=7 epoch=5 loss=16.3866 val_auc=0.7649
model=gcn top_k=200 fold=7 epoch=6 loss=17.8168 val_auc=0.7516
model=gcn top_k=200 fold=7 epoch=7 loss=11.9060 val_auc=0.7339
model=gcn top_k=200 fold=7 epoch=8 loss=13.8608 val_auc=0.7756
model=gcn top_k=200 fold=7 epoch=9 loss=15.1487 val_auc=0.7698
model=gcn top_k=200 fold=7 epoch=10 loss=13.3646 val_auc=0.6702
model=gcn top_k=200 fold=7 epoch=11 loss=19.0646 val_auc=0.7003

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=200 fold=7 epoch=12 loss=17.1522 val_auc=0.7763
model=gcn top_k=200 fold=7 epoch=13 loss=14.0917 val_auc=0.7805
model=gcn top_k=200 fold=7 epoch=14 loss=13.7547 val_auc=0.7796
model=gcn top_k=200 fold=7 epoch=15 loss=12.6530 val_auc=0.7796
model=gcn top_k=200 fold=7 epoch=16 loss=14.6553 val_auc=0.7809
model=gcn top_k=200 fold=7 epoch=17 loss=15.8055 val_auc=0.7812
model=gcn top_k=200 fold=7 epoch=18 loss=14.5377 val_auc=0.7818
model=gcn top_k=200 fold=7 epoch=19 loss=12.5611 val_auc=0.7713
model=gcn top_k=200 fold=7 epoch=20 loss=12.8562 val_auc=0.7615
model=gcn top_k=200 fold=7 epoch=21 loss=15.0719 val_auc=0.7807
model=gcn top_k=200 fold=7 epoch=22 loss=10.6862 val_auc=0.7876
model=gcn top_k=200 fold=7 epoch=23 loss=11.0616 val_auc=0.7888
model=gcn top_k=200 fold=7 epoch=24 loss=12.1324 val_auc=0.7876
model=gcn top_k=200 fold=7 epoch=25 loss=13.3962 val_auc=0.7834
model=gcn top_k=200 fold=7 epoch=26 loss=10.8262 val_auc=0.7882
model=gcn top_k=200 fold=7 epoch=27 loss=12.1719 val_auc=0.7919
model=gcn top_k=200 fold=7 epoch=28 loss=10.7919 val_auc=0.7926
model=gcn top_k=200 fold=7 epoch=29 loss=11.4876 val_auc=0.7924
model=gcn top_k=200 fold=7 epoch=30 loss=10.8340 val_auc=0.7914
model=gcn top_k=200 fold=7 epoch=31 loss=13.6643 val_auc=0.7576
model=gcn top_k=200 fold=7 epoch=32 loss=16.0627 val_auc=0.7383
model=gcn top_k=200 fold=7 epoch=33 loss=16.0461 val_auc=0.7738
model=gcn top_k=200 fold=7 epoch=34 loss=13.8026 val_auc=0.7914
model=gcn top_k=200 fold=7 epoch=35 loss=10.1528 val_auc=0.7929
model=gcn top_k=200 fold=7 epoch=36 loss=14.3937 val_auc=0.7929
model=gcn top_k=200 fold=7 epoch=37 loss=14.4724 val_auc=0.7928
model=gcn top_k=200 fold=7 epoch=38 loss=11.8062 val_auc=0.7927
model=gcn top_k=200 fold=7 epoch=39 loss=12.9646 val_auc=0.7857
model=gcn top_k=200 fold=7 epoch=40 loss=13.2897 val_auc=0.7668
model=gcn top_k=200 fold=7 epoch=41 loss=14.6667 val_auc=0.7714
model=gcn top_k=200 fold=7 epoch=42 loss=9.6148 val_auc=0.7868
model=gcn top_k=200 fold=7 epoch=43 loss=12.6201 val_auc=0.7938
model=gcn top_k=200 fold=7 epoch=44 loss=11.0348 val_auc=0.7949
model=gcn top_k=200 fold=7 epoch=45 loss=12.0612 val_auc=0.7956
model=gcn top_k=200 fold=7 epoch=46 loss=13.5314 val_auc=0.7962
model=gcn top_k=200 fold=7 epoch=47 loss=13.9015 val_auc=0.7955
model=gcn top_k=200 fold=7 epoch=48 loss=13.0783 val_auc=0.7840
model=gcn top_k=200 fold=7 epoch=49 loss=10.3602 val_auc=0.7689
model=gcn top_k=200 fold=7 epoch=50 loss=18.1779 val_auc=0.7791
model=gcn top_k=200 fold=7 epoch=51 loss=12.5649 val_auc=0.7912
model=gcn top_k=200 fold=7 epoch=52 loss=10.4962 val_auc=0.7951
model=gcn top_k=200 fold=7 epoch=53 loss=11.3880 val_auc=0.7955
model=gcn top_k=200 fold=7 epoch=54 loss=11.1461 val_auc=0.7957
model=gcn top_k=200 fold=7 epoch=55 loss=11.7795 val_auc=0.7954
model=gcn top_k=200 fold=7 epoch=56 loss=12.5894 val_auc=0.7933
model=gcn top_k=200 fold=7 epoch=57 loss=12.3311 val_auc=0.7903
model=gcn top_k=200 fold=7 epoch=58 loss=11.1977 val_auc=0.7910
gcn top_k=200 fold=7: early stopping at epoch 58

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=200 fold=8 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=200 fold=8 epoch=0 loss=218.3414 val_auc=0.5167
model=gcn top_k=200 fold=8 epoch=1 loss=88.2951 val_auc=0.5135
model=gcn top_k=200 fold=8 epoch=2 loss=27.3628 val_auc=0.7330

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=200 fold=8 epoch=3 loss=15.0360 val_auc=0.6804

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=200 fold=8 epoch=4 loss=22.3559 val_auc=0.7334
model=gcn top_k=200 fold=8 epoch=5 loss=18.5191 val_auc=0.7086
model=gcn top_k=200 fold=8 epoch=6 loss=19.2074 val_auc=0.7534
model=gcn top_k=200 fold=8 epoch=7 loss=15.5917 val_auc=0.7573
model=gcn top_k=200 fold=8 epoch=8 loss=13.9999 val_auc=0.7522
model=gcn top_k=200 fold=8 epoch=9 loss=12.2700 val_auc=0.7446
model=gcn top_k=200 fold=8 epoch=10 loss=16.8674 val_auc=0.7641
model=gcn top_k=200 fold=8 epoch=11 loss=16.3251 val_auc=0.7677
model=gcn top_k=200 fold=8 epoch=12 loss=15.6648 val_auc=0.7519
model=gcn top_k=200 fold=8 epoch=13 loss=13.3562 val_auc=0.7269
model=gcn top_k=200 fold=8 epoch=14 loss=14.1236 val_auc=0.7426
model=gcn top_k=200 fold=8 epoch=15 loss=17.1623 val_auc=0.7698
model=gcn top_k=200 fold=8 epoch=16 loss=14.4239 val_auc=0.7727
model=gcn top_k=200 fold=8 epoch=17 loss=14.7499 val_auc=0.7729
model=gcn top_k=200 fold=8 epoch=18 loss=15.8228 val_auc=0.7581
model=gcn top_k=200 fold=8 epoch=19 loss=15.0631 val_auc=0.6928
model=gcn top_k=200 fold=8 epoch=20 loss=15.6103 val_auc=0.7191
model=gcn top_k=200 fold=8 epoch=21 loss=13.0390 val_auc=0.7657
model=gcn top_k=200 fold=8 epoch=22 loss=12.3506 val_auc=0.7711
model=gcn top_k=200 fold=8 epoch=23 loss=13.3926 val_auc=0.7716
model=gcn top_k=200 fold=8 epoch=24 loss=15.0912 val_auc=0.7715
model=gcn top_k=200 fold=8 epoch=25 loss=13.1448 val_auc=0.7687
model=gcn top_k=200 fold=8 epoch=26 loss=11.8217 val_auc=0.7632
model=gcn top_k=200 fold=8 epoch=27 loss=14.0770 val_auc=0.7656
model=gcn top_k=200 fold=8 epoch=28 loss=16.1400 val_auc=0.7688
model=gcn top_k=200 fold=8 epoch=29 loss=15.6007 val_auc=0.7706
gcn top_k=200 fold=8: early stopping at epoch 29

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=200 fold=9 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=200 fold=9 epoch=0 loss=275.0811 val_auc=0.5153
model=gcn top_k=200 fold=9 epoch=1 loss=109.9159 val_auc=0.5148
model=gcn top_k=200 fold=9 epoch=2 loss=47.5467 val_auc=0.6835
model=gcn top_k=200 fold=9 epoch=3 loss=17.1601 val_auc=0.7569
model=gcn top_k=200 fold=9 epoch=4 loss=16.6145 val_auc=0.7811
model=gcn top_k=200 fold=9 epoch=5 loss=16.0720 val_auc=0.6683
model=gcn top_k=200 fold=9 epoch=6 loss=19.5677 val_auc=0.7505
model=gcn top_k=200 fold=9 epoch=7 loss=15.7979 val_auc=0.7790
model=gcn top_k=200 fold=9 epoch=8 loss=16.2789 val_auc=0.7770
model=gcn top_k=200 fold=9 epoch=9 loss=15.4247 val_auc=0.7774
model=gcn top_k=200 fold=9 epoch=10 loss=11.5501 val_auc=0.7543
model=gcn top_k=200 fold=9 epoch=11 loss=13.0105 val_auc=0.7662
model=gcn top_k=200 fold=9 epoch=12 loss=13.8769 val_auc=0.7818
model=gcn top_k=200 fold=9 epoch=13 loss=13.5314 val_auc=0.7846
model=gcn top_k=200 fold=9 epoch=14 loss=15.7359 val_auc=0.7857
model=gcn top_k=200 fold=9 epoch=15 loss=12.2454 val_auc=0.7268
model=gcn top_k=200 fold=9 epoch=16 loss=17.3444 val_auc=0.6927
model=gcn top_k=200 fold=9 epoch=17 loss=18.4613 val_auc=0.7633
model=gcn top_k=200 fold=9 epoch=18 loss=13.6550 val_auc=0.7841
model=gcn top_k=200 fold=9 epoch=19 loss=13.1177 val_auc=0.7845
model=gcn top_k=200 fold=9 epoch=20 loss=15.0171 val_auc=0.7832
model=gcn top_k=200 fold=9 epoch=21 loss=16.2216 val_auc=0.7819
model=gcn top_k=200 fold=9 epoch=22 loss=12.2430 val_auc=0.7745
model=gcn top_k=200 fold=9 epoch=23 loss=12.4102 val_auc=0.7646
model=gcn top_k=200 fold=9 epoch=24 loss=12.6712 val_auc=0.7725
model=gcn top_k=200 fold=9 epoch=25 loss=11.6503 val_auc=0.7800
model=gcn top_k=200 fold=9 epoch=26 loss=11.7991 val_auc=0.7821
gcn top_k=200 fold=9: early stopping at epoch 26

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

######## Model=gcn top_k=500 ########

===== Model=gcn top_k=500 fold=0 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=500 fold=0 epoch=0 loss=283.8492 val_auc=0.5294
model=gcn top_k=500 fold=0 epoch=1 loss=88.8793 val_auc=0.5321
model=gcn top_k=500 fold=0 epoch=2 loss=32.9661 val_auc=0.7229
model=gcn top_k=500 fold=0 epoch=3 loss=18.6196 val_auc=0.5734
model=gcn top_k=500 fold=0 epoch=4 loss=20.4259 val_auc=0.6780
model=gcn top_k=500 fold=0 epoch=5 loss=15.6322 val_auc=0.7602
model=gcn top_k=500 fold=0 epoch=6 loss=14.4626 val_auc=0.7606
model=gcn top_k=500 fold=0 epoch=7 loss=14.3216 val_auc=0.6470
model=gcn top_k=500 fold=0 epoch=8 loss=20.8024 val_auc=0.6289
model=gcn top_k=500 fold=0 epoch=9 loss=20.4314 val_auc=0.7473
model=gcn top_k=500 fold=0 epoch=10 loss=13.7458 val_auc=0.7613
model=gcn top_k=500 fold=0 epoch=11 loss=14.9744 val_auc=0.7626
model=gcn top_k=500 fold=0 epoch=12 loss=15.5108 val_auc=0.7622
model=gcn top_k=500 fold=0 epoch=13 loss=14.8609 val_auc=0.7191
model=gcn top_k=500 fold=0 epoch=14 loss=13.5491 val_auc=0.6964
model=gcn top_k=500 fold=0 epoch=15 loss=12.4292 val_auc=0.7360
model=gcn top_k=500 fold=0 epoch=16 loss=15.3475 val_auc=0.7502
model=gcn top_k=500 fold=0 epoch=17 loss=16.1543 val_auc=0.7715
model=gcn top_k=500 fold=0 epoch=18 loss=12.5527 val_auc=0.7737
model=gcn top_k=500 fold=0 epoch=19 loss=11.1228 val_auc=0.7707
model=gcn top_k=500 fold=0 epoch=20 loss=12.0212 val_auc=0.7658
model=gcn top_k=500 fold=0 epoch=21 loss=12.3511 val_auc=0.7731
model=gcn top_k=500 fold=0 epoch=22 loss=13.4932 val_auc=0.7770
model=gcn top_k=500 fold=0 epoch=23 loss=12.7283 val_auc=0.7779
model=gcn top_k=500 fold=0 epoch=24 loss=12.8741 val_auc=0.7780
model=gcn top_k=500 fold=0 epoch=25 loss=10.5403 val_auc=0.7757
model=gcn top_k=500 fold=0 epoch=26 loss=11.7045 val_auc=0.7656
model=gcn top_k=500 fold=0 epoch=27 loss=13.2882 val_auc=0.7593
model=gcn top_k=500 fold=0 epoch=28 loss=14.7474 val_auc=0.7715
model=gcn top_k=500 fold=0 epoch=29 loss=12.9532 val_auc=0.7777
model=gcn top_k=500 fold=0 epoch=30 loss=10.6573 val_auc=0.7803
model=gcn top_k=500 fold=0 epoch=31 loss=13.4954 val_auc=0.7817
model=gcn top_k=500 fold=0 epoch=32 loss=13.8108 val_auc=0.7821
model=gcn top_k=500 fold=0 epoch=33 loss=15.9022 val_auc=0.7819
model=gcn top_k=500 fold=0 epoch=34 loss=13.8921 val_auc=0.7808
model=gcn top_k=500 fold=0 epoch=35 loss=12.1423 val_auc=0.7783
model=gcn top_k=500 fold=0 epoch=36 loss=13.4674 val_auc=0.7782
model=gcn top_k=500 fold=0 epoch=37 loss=11.1756 val_auc=0.7788
model=gcn top_k=500 fold=0 epoch=38 loss=12.4089 val_auc=0.7791
model=gcn top_k=500 fold=0 epoch=39 loss=11.5825 val_auc=0.7794
model=gcn top_k=500 fold=0 epoch=40 loss=10.7630 val_auc=0.7787
model=gcn top_k=500 fold=0 epoch=41 loss=10.9526 val_auc=0.7792
model=gcn top_k=500 fold=0 epoch=42 loss=10.8596 val_auc=0.7813
model=gcn top_k=500 fold=0 epoch=43 loss=10.6716 val_auc=0.7841
model=gcn top_k=500 fold=0 epoch=44 loss=10.1703 val_auc=0.7811
model=gcn top_k=500 fold=0 epoch=45 loss=11.0372 val_auc=0.7758
model=gcn top_k=500 fold=0 epoch=46 loss=10.6915 val_auc=0.7818
model=gcn top_k=500 fold=0 epoch=47 loss=9.7795 val_auc=0.7835
model=gcn top_k=500 fold=0 epoch=48 loss=10.1408 val_auc=0.7836
model=gcn top_k=500 fold=0 epoch=49 loss=10.5824 val_auc=0.7849
model=gcn top_k=500 fold=0 epoch=50 loss=13.4387 val_auc=0.7881
model=gcn top_k=500 fold=0 epoch=51 loss=10.2645 val_auc=0.7887
model=gcn top_k=500 fold=0 epoch=52 loss=10.2203 val_auc=0.7888
model=gcn top_k=500 fold=0 epoch=53 loss=13.5038 val_auc=0.7883
model=gcn top_k=500 fold=0 epoch=54 loss=11.3926 val_auc=0.7875
model=gcn top_k=500 fold=0 epoch=55 loss=10.2121 val_auc=0.7843
model=gcn top_k=500 fold=0 epoch=56 loss=9.3187 val_auc=0.7788
model=gcn top_k=500 fold=0 epoch=57 loss=10.2583 val_auc=0.7825
model=gcn top_k=500 fold=0 epoch=58 loss=11.0932 val_auc=0.7867
model=gcn top_k=500 fold=0 epoch=59 loss=10.8404 val_auc=0.7873
model=gcn top_k=500 fold=0 epoch=60 loss=10.9604 val_auc=0.7878
model=gcn top_k=500 fold=0 epoch=61 loss=13.4054 val_auc=0.7880
model=gcn top_k=500 fold=0 epoch=62 loss=12.1264 val_auc=0.7877
model=gcn top_k=500 fold=0 epoch=63 loss=11.3297 val_auc=0.7852
model=gcn top_k=500 fold=0 epoch=64 loss=9.9047 val_auc=0.7772
gcn top_k=500 fold=0: early stopping at epoch 64

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=500 fold=1 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=500 fold=1 epoch=0 loss=231.7529 val_auc=0.5139

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=500 fold=1 epoch=1 loss=85.1696 val_auc=0.5574
model=gcn top_k=500 fold=1 epoch=2 loss=22.0066 val_auc=0.7159
model=gcn top_k=500 fold=1 epoch=3 loss=15.1951 val_auc=0.5000
model=gcn top_k=500 fold=1 epoch=4 loss=39.1696 val_auc=0.5178
model=gcn top_k=500 fold=1 epoch=5 loss=28.1363 val_auc=0.7674
model=gcn top_k=500 fold=1 epoch=6 loss=14.2880 val_auc=0.7714
model=gcn top_k=500 fold=1 epoch=7 loss=16.0129 val_auc=0.5789
model=gcn top_k=500 fold=1 epoch=8 loss=20.2768 val_auc=0.5835
model=gcn top_k=500 fold=1 epoch=9 loss=17.3231 val_auc=0.7722
model=gcn top_k=500 fold=1 epoch=10 loss=14.2232 val_auc=0.7802
model=gcn top_k=500 fold=1 epoch=11 loss=16.9252 val_auc=0.7815
model=gcn top_k=500 fold=1 epoch=12 loss=16.9190 val_auc=0.7822
model=gcn top_k=500 fold=1 epoch=13 loss=13.1983 val_auc=0.7481
model=gcn top_k=500 fold=1 epoch=14 loss=17.0952 val_auc=0.7062
model=gcn top_k=500 fold=1 epoch=15 loss=14.5620 val_auc=0.7714
model=gcn top_k=500 fold=1 epoch=16 loss=12.4759 val_auc=0.7840
model=gcn top_k=500 fold=1 epoch=17 loss=10.7981 val_auc=0.7848
model=gcn top_k=500 fold=1 epoch=18 loss=14.6513 val_auc=0.7854
model=gcn top_k=500 fold=1 epoch=19 loss=14.1923 val_auc=0.7857
model=gcn top_k=500 fold=1 epoch=20 loss=12.3585 val_auc=0.7513
model=gcn top_k=500 fold=1 epoch=21 loss=13.5457 val_auc=0.7082
model=gcn top_k=500 fold=1 epoch=22 loss=17.6237 val_auc=0.7397
model=gcn top_k=500 fold=1 epoch=23 loss=16.1900 val_auc=0.7805
model=gcn top_k=500 fold=1 epoch=24 loss=10.7399 val_auc=0.7868
model=gcn top_k=500 fold=1 epoch=25 loss=14.8427 val_auc=0.7873
model=gcn top_k=500 fold=1 epoch=26 loss=14.5726 val_auc=0.7877
model=gcn top_k=500 fold=1 epoch=27 loss=14.0829 val_auc=0.7874
model=gcn top_k=500 fold=1 epoch=28 loss=10.1330 val_auc=0.7871
model=gcn top_k=500 fold=1 epoch=29 loss=14.7101 val_auc=0.7882
model=gcn top_k=500 fold=1 epoch=30 loss=12.9469 val_auc=0.7893
model=gcn top_k=500 fold=1 epoch=31 loss=12.4358 val_auc=0.7891
model=gcn top_k=500 fold=1 epoch=32 loss=12.5798 val_auc=0.7887
model=gcn top_k=500 fold=1 epoch=33 loss=10.8426 val_auc=0.7848
model=gcn top_k=500 fold=1 epoch=34 loss=15.1145 val_auc=0.7844
model=gcn top_k=500 fold=1 epoch=35 loss=14.1776 val_auc=0.7882
model=gcn top_k=500 fold=1 epoch=36 loss=12.7225 val_auc=0.7893
model=gcn top_k=500 fold=1 epoch=37 loss=11.4970 val_auc=0.7895
model=gcn top_k=500 fold=1 epoch=38 loss=12.2129 val_auc=0.7860
model=gcn top_k=500 fold=1 epoch=39 loss=11.2009 val_auc=0.7850
model=gcn top_k=500 fold=1 epoch=40 loss=11.1057 val_auc=0.7863
model=gcn top_k=500 fold=1 epoch=41 loss=13.2326 val_auc=0.7886
model=gcn top_k=500 fold=1 epoch=42 loss=10.0629 val_auc=0.7898
model=gcn top_k=500 fold=1 epoch=43 loss=10.5433 val_auc=0.7906
model=gcn top_k=500 fold=1 epoch=44 loss=9.5207 val_auc=0.7915
model=gcn top_k=500 fold=1 epoch=45 loss=10.3784 val_auc=0.7911
model=gcn top_k=500 fold=1 epoch=46 loss=10.6692 val_auc=0.7935
model=gcn top_k=500 fold=1 epoch=47 loss=10.7359 val_auc=0.7953
model=gcn top_k=500 fold=1 epoch=48 loss=12.3201 val_auc=0.7963
model=gcn top_k=500 fold=1 epoch=49 loss=11.4736 val_auc=0.7965
model=gcn top_k=500 fold=1 epoch=50 loss=10.1136 val_auc=0.7972
model=gcn top_k=500 fold=1 epoch=51 loss=10.4024 val_auc=0.7966
model=gcn top_k=500 fold=1 epoch=52 loss=11.2617 val_auc=0.7972
model=gcn top_k=500 fold=1 epoch=53 loss=9.8730 val_auc=0.7979
model=gcn top_k=500 fold=1 epoch=54 loss=9.9416 val_auc=0.7973
model=gcn top_k=500 fold=1 epoch=55 loss=10.1149 val_auc=0.7961
model=gcn top_k=500 fold=1 epoch=56 loss=11.2451 val_auc=0.7961
model=gcn top_k=500 fold=1 epoch=57 loss=9.0294 val_auc=0.7986
model=gcn top_k=500 fold=1 epoch=58 loss=14.3179 val_auc=0.7996
model=gcn top_k=500 fold=1 epoch=59 loss=10.5291 val_auc=0.8004
model=gcn top_k=500 fold=1 epoch=60 loss=11.3159 val_auc=0.8009
model=gcn top_k=500 fold=1 epoch=61 loss=10.7722 val_auc=0.8001
model=gcn top_k=500 fold=1 epoch=62 loss=9.9713 val_auc=0.7997
model=gcn top_k=500 fold=1 epoch=63 loss=9.0593 val_auc=0.8003
model=gcn top_k=500 fold=1 epoch=64 loss=9.3384 val_auc=0.8005
model=gcn top_k=500 fold=1 epoch=65 loss=10.0784 val_auc=0.8010
model=gcn top_k=500 fold=1 epoch=66 loss=9.4859 val_auc=0.8018
model=gcn top_k=500 fold=1 epoch=67 loss=9.7819 val_auc=0.8020
model=gcn top_k=500 fold=1 epoch=68 loss=11.7661 val_auc=0.8013
model=gcn top_k=500 fold=1 epoch=69 loss=12.2116 val_auc=0.8011
model=gcn top_k=500 fold=1 epoch=70 loss=9.6783 val_auc=0.8017
model=gcn top_k=500 fold=1 epoch=71 loss=9.6194 val_auc=0.8014
model=gcn top_k=500 fold=1 epoch=72 loss=8.5221 val_auc=0.8006
model=gcn top_k=500 fold=1 epoch=73 loss=12.0945 val_auc=0.8017
model=gcn top_k=500 fold=1 epoch=74 loss=11.0297 val_auc=0.8020
model=gcn top_k=500 fold=1 epoch=75 loss=8.0186 val_auc=0.8022
model=gcn top_k=500 fold=1 epoch=76 loss=11.0476 val_auc=0.8014
model=gcn top_k=500 fold=1 epoch=77 loss=10.1285 val_auc=0.8019
model=gcn top_k=500 fold=1 epoch=78 loss=9.8125 val_auc=0.8028
model=gcn top_k=500 fold=1 epoch=79 loss=9.1497 val_auc=0.8033
model=gcn top_k=500 fold=1 epoch=80 loss=8.9876 val_auc=0.8037
model=gcn top_k=500 fold=1 epoch=81 loss=9.3010 val_auc=0.8039
model=gcn top_k=500 fold=1 epoch=82 loss=8.5454 val_auc=0.8037
model=gcn top_k=500 fold=1 epoch=83 loss=10.0560 val_auc=0.8011
model=gcn top_k=500 fold=1 epoch=84 loss=9.4843 val_auc=0.8035
model=gcn top_k=500 fold=1 epoch=85 loss=12.5040 val_auc=0.8057
model=gcn top_k=500 fold=1 epoch=86 loss=9.2935 val_auc=0.8059
model=gcn top_k=500 fold=1 epoch=87 loss=9.6987 val_auc=0.8054
model=gcn top_k=500 fold=1 epoch=88 loss=7.8582 val_auc=0.8057
model=gcn top_k=500 fold=1 epoch=89 loss=9.4177 val_auc=0.8055
model=gcn top_k=500 fold=1 epoch=90 loss=9.0237 val_auc=0.8055
model=gcn top_k=500 fold=1 epoch=91 loss=8.5999 val_auc=0.8050
model=gcn top_k=500 fold=1 epoch=92 loss=10.4430 val_auc=0.7984
model=gcn top_k=500 fold=1 epoch=93 loss=9.7301 val_auc=0.7947
model=gcn top_k=500 fold=1 epoch=94 loss=9.5096 val_auc=0.8014
model=gcn top_k=500 fold=1 epoch=95 loss=9.3995 val_auc=0.8066
model=gcn top_k=500 fold=1 epoch=96 loss=9.0005 val_auc=0.8082
model=gcn top_k=500 fold=1 epoch=97 loss=8.2515 val_auc=0.8094
model=gcn top_k=500 fold=1 epoch=98 loss=10.0809 val_auc=0.8098
model=gcn top_k=500 fold=1 epoch=99 loss=8.9829 val_auc=0.8099

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=500 fold=2 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=500 fold=2 epoch=0 loss=193.6432 val_auc=0.5300
model=gcn top_k=500 fold=2 epoch=1 loss=69.5652 val_auc=0.6502
model=gcn top_k=500 fold=2 epoch=2 loss=16.5022 val_auc=0.7735
model=gcn top_k=500 fold=2 epoch=3 loss=22.3914 val_auc=0.5467
model=gcn top_k=500 fold=2 epoch=4 loss=28.6068 val_auc=0.6050
model=gcn top_k=500 fold=2 epoch=5 loss=20.6565 val_auc=0.7802
model=gcn top_k=500 fold=2 epoch=6 loss=14.8210 val_auc=0.7747
model=gcn top_k=500 fold=2 epoch=7 loss=12.5109 val_auc=0.7232
model=gcn top_k=500 fold=2 epoch=8 loss=16.9434 val_auc=0.6880
model=gcn top_k=500 fold=2 epoch=9 loss=15.6746 val_auc=0.7741
model=gcn top_k=500 fold=2 epoch=10 loss=13.9941 val_auc=0.7826
model=gcn top_k=500 fold=2 epoch=11 loss=13.6405 val_auc=0.7836
model=gcn top_k=500 fold=2 epoch=12 loss=11.7120 val_auc=0.7844
model=gcn top_k=500 fold=2 epoch=13 loss=13.6562 val_auc=0.7857
model=gcn top_k=500 fold=2 epoch=14 loss=12.1483 val_auc=0.7860
model=gcn top_k=500 fold=2 epoch=15 loss=17.4297 val_auc=0.7841
model=gcn top_k=500 fold=2 epoch=16 loss=15.6089 val_auc=0.7799
model=gcn top_k=500 fold=2 epoch=17 loss=11.5226 val_auc=0.7680
model=gcn top_k=500 fold=2 epoch=18 loss=15.1954 val_auc=0.7535
model=gcn top_k=500 fold=2 epoch=19 loss=15.4059 val_auc=0.7596
model=gcn top_k=500 fold=2 epoch=20 loss=12.7507 val_auc=0.7744
model=gcn top_k=500 fold=2 epoch=21 loss=12.6133 val_auc=0.7758
model=gcn top_k=500 fold=2 epoch=22 loss=12.8579 val_auc=0.7774
model=gcn top_k=500 fold=2 epoch=23 loss=10.4245 val_auc=0.7775
model=gcn top_k=500 fold=2 epoch=24 loss=11.6799 val_auc=0.7759
model=gcn top_k=500 fold=2 epoch=25 loss=12.7990 val_auc=0.7781
model=gcn top_k=500 fold=2 epoch=26 loss=14.5051 val_auc=0.7815
gcn top_k=500 fold=2: early stopping at epoch 26

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=500 fold=3 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=gcn top_k=500 fold=3 epoch=0 loss=240.3393 val_auc=0.5062
model=gcn top_k=500 fold=3 epoch=1 loss=102.5284 val_auc=0.5002
model=gcn top_k=500 fold=3 epoch=2 loss=47.1274 val_auc=0.6745
model=gcn top_k=500 fold=3 epoch=3 loss=15.9579 val_auc=0.7123
model=gcn top_k=500 fold=3 epoch=4 loss=20.8795 val_auc=0.6001
model=gcn top_k=500 fold=3 epoch=5 loss=17.8689 val_auc=0.6665

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=500 fold=3 epoch=6 loss=16.8078 val_auc=0.7716

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=500 fold=3 epoch=7 loss=16.4763 val_auc=0.7707
model=gcn top_k=500 fold=3 epoch=8 loss=15.8883 val_auc=0.6662
model=gcn top_k=500 fold=3 epoch=9 loss=17.2966 val_auc=0.7195
model=gcn top_k=500 fold=3 epoch=10 loss=14.0089 val_auc=0.7754
model=gcn top_k=500 fold=3 epoch=11 loss=13.7373 val_auc=0.7793
model=gcn top_k=500 fold=3 epoch=12 loss=15.4055 val_auc=0.7804
model=gcn top_k=500 fold=3 epoch=13 loss=12.4514 val_auc=0.7620
model=gcn top_k=500 fold=3 epoch=14 loss=14.3390 val_auc=0.7142
model=gcn top_k=500 fold=3 epoch=15 loss=16.3720 val_auc=0.7710
model=gcn top_k=500 fold=3 epoch=16 loss=16.6707 val_auc=0.7830
model=gcn top_k=500 fold=3 epoch=17 loss=16.6876 val_auc=0.7837
model=gcn top_k=500 fold=3 epoch=18 loss=16.6976 val_auc=0.7833
model=gcn top_k=500 fold=3 epoch=19 loss=12.4490 val_auc=0.7672
model=gcn top_k=500 fold=3 epoch=20 loss=15.7774 val_auc=0.7670
model=gcn top_k=500 fold=3 epoch=21 loss=14.3663 val_auc=0.7785
model=gcn top_k=500 fold=3 epoch=22 loss=12.1526 val_auc=0.7815
model=gcn top_k=500 fold=3 epoch=23 loss=12.9207 val_auc=0.7808
model=gcn top_k=500 fold=3 epoch=24 loss=11.9527 val_auc=0.7794
model=gcn top_k=500 fold=3 epoch=25 loss=11.4966 val_auc=0.7589
model=gcn top_k=500 fold=3 epoch=26 loss=15.4737 val_auc=0.7232
model=gcn top_k=500 fold=3 epoch=27 loss=17.7020 val_auc=0.7359
model=gcn top_k=500 fold=3 epoch=28 loss=16.4894 val_auc=0.7705
model=gcn top_k=500 fold=3 epoch=29 loss=12.9345 val_auc=0.7833
gcn top_k=500 fold=3: early stopping at epoch 29

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=500 fold=4 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=gcn top_k=500 fold=4 epoch=0 loss=215.3302 val_auc=0.5249
model=gcn top_k=500 fold=4 epoch=1 loss=102.0458 val_auc=0.5312

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=500 fold=4 epoch=2 loss=38.1478 val_auc=0.7577
model=gcn top_k=500 fold=4 epoch=3 loss=20.6784 val_auc=0.6028
model=gcn top_k=500 fold=4 epoch=4 loss=18.2638 val_auc=0.7129
model=gcn top_k=500 fold=4 epoch=5 loss=14.3736 val_auc=0.7669
model=gcn top_k=500 fold=4 epoch=6 loss=16.2576 val_auc=0.7650
model=gcn top_k=500 fold=4 epoch=7 loss=12.5307 val_auc=0.5827
model=gcn top_k=500 fold=4 epoch=8 loss=17.5037 val_auc=0.5710
model=gcn top_k=500 fold=4 epoch=9 loss=29.1134 val_auc=0.7190
model=gcn top_k=500 fold=4 epoch=10 loss=20.0926 val_auc=0.7696
model=gcn top_k=500 fold=4 epoch=11 loss=12.2573 val_auc=0.7696
model=gcn top_k=500 fold=4 epoch=12 loss=17.4716 val_auc=0.7720
model=gcn top_k=500 fold=4 epoch=13 loss=16.3948 val_auc=0.7742
model=gcn top_k=500 fold=4 epoch=14 loss=15.3606 val_auc=0.7718
model=gcn top_k=500 fold=4 epoch=15 loss=14.2286 val_auc=0.7476
model=gcn top_k=500 fold=4 epoch=16 loss=15.9538 val_auc=0.7515
model=gcn top_k=500 fold=4 epoch=17 loss=18.6833 val_auc=0.7612
model=gcn top_k=500 fold=4 epoch=18 loss=17.1622 val_auc=0.7766
model=gcn top_k=500 fold=4 epoch=19 loss=12.9674 val_auc=0.7769
model=gcn top_k=500 fold=4 epoch=20 loss=13.9417 val_auc=0.7750
model=gcn top_k=500 fold=4 epoch=21 loss=13.4862 val_auc=0.7738
model=gcn top_k=500 fold=4 epoch=22 loss=11.3916 val_auc=0.7765
model=gcn top_k=500 fold=4 epoch=23 loss=13.0635 val_auc=0.7783
model=gcn top_k=500 fold=4 epoch=24 loss=10.7962 val_auc=0.7581
model=gcn top_k=500 fold=4 epoch=25 loss=14.1844 val_auc=0.7580
model=gcn top_k=500 fold=4 epoch=26 loss=18.5630 val_auc=0.7596
model=gcn top_k=500 fold=4 epoch=27 loss=15.4566 val_auc=0.7766
model=gcn top_k=500 fold=4 epoch=28 loss=12.6583 val_auc=0.7792
model=gcn top_k=500 fold=4 epoch=29 loss=10.6101 val_auc=0.7788
model=gcn top_k=500 fold=4 epoch=30 loss=10.7546 val_auc=0.7788
model=gcn top_k=500 fold=4 epoch=31 loss=11.2969 val_auc=0.7803
model=gcn top_k=500 fold=4 epoch=32 loss=11.3453 val_auc=0.7791
model=gcn top_k=500 fold=4 epoch=33 loss=10.8804 val_auc=0.7787
model=gcn top_k=500 fold=4 epoch=34 loss=10.6733 val_auc=0.7722
model=gcn top_k=500 fold=4 epoch=35 loss=12.2850 val_auc=0.7647
model=gcn top_k=500 fold=4 epoch=36 loss=12.7573 val_auc=0.7664
model=gcn top_k=500 fold=4 epoch=37 loss=11.5078 val_auc=0.7819
model=gcn top_k=500 fold=4 epoch=38 loss=10.2571 val_auc=0.7850
model=gcn top_k=500 fold=4 epoch=39 loss=11.9338 val_auc=0.7858
model=gcn top_k=500 fold=4 epoch=40 loss=13.0289 val_auc=0.7829
model=gcn top_k=500 fold=4 epoch=41 loss=10.5959 val_auc=0.7832
model=gcn top_k=500 fold=4 epoch=42 loss=14.1161 val_auc=0.7860
model=gcn top_k=500 fold=4 epoch=43 loss=10.2075 val_auc=0.7872
model=gcn top_k=500 fold=4 epoch=44 loss=10.6714 val_auc=0.7878
model=gcn top_k=500 fold=4 epoch=45 loss=9.4582 val_auc=0.7886
model=gcn top_k=500 fold=4 epoch=46 loss=13.3318 val_auc=0.7895
model=gcn top_k=500 fold=4 epoch=47 loss=11.0095 val_auc=0.7892
model=gcn top_k=500 fold=4 epoch=48 loss=12.7909 val_auc=0.7847
model=gcn top_k=500 fold=4 epoch=49 loss=13.6358 val_auc=0.7862
model=gcn top_k=500 fold=4 epoch=50 loss=11.2930 val_auc=0.7878
model=gcn top_k=500 fold=4 epoch=51 loss=10.9701 val_auc=0.7867
model=gcn top_k=500 fold=4 epoch=52 loss=13.2229 val_auc=0.7845
model=gcn top_k=500 fold=4 epoch=53 loss=13.5880 val_auc=0.7829
model=gcn top_k=500 fold=4 epoch=54 loss=12.5751 val_auc=0.7813
model=gcn top_k=500 fold=4 epoch=55 loss=9.5393 val_auc=0.7755
model=gcn top_k=500 fold=4 epoch=56 loss=10.3417 val_auc=0.7699
model=gcn top_k=500 fold=4 epoch=57 loss=14.8252 val_auc=0.7713
model=gcn top_k=500 fold=4 epoch=58 loss=11.6459 val_auc=0.7787
gcn top_k=500 fold=4: early stopping at epoch 58

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=500 fold=5 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=gcn top_k=500 fold=5 epoch=0 loss=298.9400 val_auc=0.5374

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=500 fold=5 epoch=1 loss=123.4466 val_auc=0.5211

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=500 fold=5 epoch=2 loss=58.8278 val_auc=0.6519
model=gcn top_k=500 fold=5 epoch=3 loss=17.3047 val_auc=0.6536
model=gcn top_k=500 fold=5 epoch=4 loss=17.8831 val_auc=0.7724
model=gcn top_k=500 fold=5 epoch=5 loss=16.0648 val_auc=0.6382
model=gcn top_k=500 fold=5 epoch=6 loss=23.6403 val_auc=0.7165
model=gcn top_k=500 fold=5 epoch=7 loss=15.4743 val_auc=0.7815
model=gcn top_k=500 fold=5 epoch=8 loss=14.7414 val_auc=0.7832
model=gcn top_k=500 fold=5 epoch=9 loss=14.0016 val_auc=0.7816
model=gcn top_k=500 fold=5 epoch=10 loss=14.4499 val_auc=0.7823
model=gcn top_k=500 fold=5 epoch=11 loss=14.2730 val_auc=0.7820
model=gcn top_k=500 fold=5 epoch=12 loss=12.2117 val_auc=0.7635
model=gcn top_k=500 fold=5 epoch=13 loss=17.5738 val_auc=0.7789
model=gcn top_k=500 fold=5 epoch=14 loss=10.7278 val_auc=0.7806
model=gcn top_k=500 fold=5 epoch=15 loss=13.7114 val_auc=0.7794
model=gcn top_k=500 fold=5 epoch=16 loss=13.7223 val_auc=0.7796
model=gcn top_k=500 fold=5 epoch=17 loss=14.9245 val_auc=0.7839
model=gcn top_k=500 fold=5 epoch=18 loss=12.0951 val_auc=0.7827
model=gcn top_k=500 fold=5 epoch=19 loss=11.4619 val_auc=0.7718
model=gcn top_k=500 fold=5 epoch=20 loss=12.0022 val_auc=0.7856
model=gcn top_k=500 fold=5 epoch=21 loss=12.4993 val_auc=0.7866
model=gcn top_k=500 fold=5 epoch=22 loss=11.5998 val_auc=0.7883
model=gcn top_k=500 fold=5 epoch=23 loss=12.0562 val_auc=0.7874
model=gcn top_k=500 fold=5 epoch=24 loss=12.7101 val_auc=0.7848
model=gcn top_k=500 fold=5 epoch=25 loss=11.0435 val_auc=0.7895
model=gcn top_k=500 fold=5 epoch=26 loss=10.6406 val_auc=0.7919
model=gcn top_k=500 fold=5 epoch=27 loss=11.7813 val_auc=0.7931
model=gcn top_k=500 fold=5 epoch=28 loss=10.9326 val_auc=0.7921
model=gcn top_k=500 fold=5 epoch=29 loss=10.5040 val_auc=0.7918
model=gcn top_k=500 fold=5 epoch=30 loss=11.8183 val_auc=0.7954
model=gcn top_k=500 fold=5 epoch=31 loss=10.0590 val_auc=0.7963
model=gcn top_k=500 fold=5 epoch=32 loss=12.7496 val_auc=0.7968
model=gcn top_k=500 fold=5 epoch=33 loss=10.0714 val_auc=0.7956
model=gcn top_k=500 fold=5 epoch=34 loss=11.3939 val_auc=0.7954
model=gcn top_k=500 fold=5 epoch=35 loss=11.4051 val_auc=0.7885
model=gcn top_k=500 fold=5 epoch=36 loss=16.3021 val_auc=0.7896
model=gcn top_k=500 fold=5 epoch=37 loss=11.0725 val_auc=0.7950
model=gcn top_k=500 fold=5 epoch=38 loss=9.5774 val_auc=0.7927
model=gcn top_k=500 fold=5 epoch=39 loss=10.9824 val_auc=0.7912
model=gcn top_k=500 fold=5 epoch=40 loss=10.7538 val_auc=0.7933
model=gcn top_k=500 fold=5 epoch=41 loss=10.2977 val_auc=0.7948
model=gcn top_k=500 fold=5 epoch=42 loss=13.4814 val_auc=0.7952
model=gcn top_k=500 fold=5 epoch=43 loss=10.5929 val_auc=0.7960
model=gcn top_k=500 fold=5 epoch=44 loss=10.0017 val_auc=0.7963
gcn top_k=500 fold=5: early stopping at epoch 44

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=500 fold=6 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}
model=gcn top_k=500 fold=6 epoch=0 loss=232.0227 val_auc=0.5165

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=500 fold=6 epoch=1 loss=91.0337 val_auc=0.5133

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=500 fold=6 epoch=2 loss=41.0051 val_auc=0.7033
model=gcn top_k=500 fold=6 epoch=3 loss=18.3322 val_auc=0.5664
model=gcn top_k=500 fold=6 epoch=4 loss=18.4310 val_auc=0.7459
model=gcn top_k=500 fold=6 epoch=5 loss=18.4497 val_auc=0.7746
model=gcn top_k=500 fold=6 epoch=6 loss=18.4042 val_auc=0.7843
model=gcn top_k=500 fold=6 epoch=7 loss=14.2188 val_auc=0.7901
model=gcn top_k=500 fold=6 epoch=8 loss=13.6066 val_auc=0.6804
model=gcn top_k=500 fold=6 epoch=9 loss=19.8151 val_auc=0.7599
model=gcn top_k=500 fold=6 epoch=10 loss=15.1630 val_auc=0.7976
model=gcn top_k=500 fold=6 epoch=11 loss=13.3533 val_auc=0.7974
model=gcn top_k=500 fold=6 epoch=12 loss=14.8353 val_auc=0.7748
model=gcn top_k=500 fold=6 epoch=13 loss=17.5717 val_auc=0.7769
model=gcn top_k=500 fold=6 epoch=14 loss=16.2363 val_auc=0.7925
model=gcn top_k=500 fold=6 epoch=15 loss=14.1052 val_auc=0.7983
model=gcn top_k=500 fold=6 epoch=16 loss=14.7370 val_auc=0.7992
model=gcn top_k=500 fold=6 epoch=17 loss=14.8581 val_auc=0.7972
model=gcn top_k=500 fold=6 epoch=18 loss=13.6488 val_auc=0.7912
model=gcn top_k=500 fold=6 epoch=19 loss=11.6971 val_auc=0.7761
model=gcn top_k=500 fold=6 epoch=20 loss=14.9888 val_auc=0.7744
model=gcn top_k=500 fold=6 epoch=21 loss=14.9663 val_auc=0.7994
model=gcn top_k=500 fold=6 epoch=22 loss=11.6069 val_auc=0.8008
model=gcn top_k=500 fold=6 epoch=23 loss=13.6548 val_auc=0.8009
model=gcn top_k=500 fold=6 epoch=24 loss=12.1174 val_auc=0.7988
model=gcn top_k=500 fold=6 epoch=25 loss=12.3002 val_auc=0.7987
model=gcn top_k=500 fold=6 epoch=26 loss=12.0671 val_auc=0.8022
model=gcn top_k=500 fold=6 epoch=27 loss=12.3719 val_auc=0.8035
model=gcn top_k=500 fold=6 epoch=28 loss=12.0545 val_auc=0.8034
model=gcn top_k=500 fold=6 epoch=29 loss=16.1735 val_auc=0.8031
model=gcn top_k=500 fold=6 epoch=30 loss=11.4883 val_auc=0.8025
model=gcn top_k=500 fold=6 epoch=31 loss=15.1216 val_auc=0.8021
model=gcn top_k=500 fold=6 epoch=32 loss=9.9959 val_auc=0.8028
model=gcn top_k=500 fold=6 epoch=33 loss=10.9232 val_auc=0.8034
model=gcn top_k=500 fold=6 epoch=34 loss=9.3493 val_auc=0.8036
model=gcn top_k=500 fold=6 epoch=35 loss=11.2359 val_auc=0.8026
model=gcn top_k=500 fold=6 epoch=36 loss=11.1009 val_auc=0.8047
model=gcn top_k=500 fold=6 epoch=37 loss=11.5338 val_auc=0.8050
model=gcn top_k=500 fold=6 epoch=38 loss=9.0749 val_auc=0.8051
model=gcn top_k=500 fold=6 epoch=39 loss=9.8767 val_auc=0.8039
model=gcn top_k=500 fold=6 epoch=40 loss=11.7249 val_auc=0.8035
model=gcn top_k=500 fold=6 epoch=41 loss=10.1338 val_auc=0.8059
model=gcn top_k=500 fold=6 epoch=42 loss=11.1045 val_auc=0.8072
model=gcn top_k=500 fold=6 epoch=43 loss=11.4588 val_auc=0.8078
model=gcn top_k=500 fold=6 epoch=44 loss=10.9635 val_auc=0.8075
model=gcn top_k=500 fold=6 epoch=45 loss=10.2954 val_auc=0.8073
model=gcn top_k=500 fold=6 epoch=46 loss=11.6132 val_auc=0.8000
model=gcn top_k=500 fold=6 epoch=47 loss=10.5700 val_auc=0.7861
model=gcn top_k=500 fold=6 epoch=48 loss=12.6345 val_auc=0.7926
model=gcn top_k=500 fold=6 epoch=49 loss=13.7964 val_auc=0.8025
model=gcn top_k=500 fold=6 epoch=50 loss=10.1087 val_auc=0.8046
model=gcn top_k=500 fold=6 epoch=51 loss=10.1127 val_auc=0.8041
model=gcn top_k=500 fold=6 epoch=52 loss=10.1456 val_auc=0.8028
model=gcn top_k=500 fold=6 epoch=53 loss=11.3828 val_auc=0.8025
model=gcn top_k=500 fold=6 epoch=54 loss=11.2840 val_auc=0.8024
model=gcn top_k=500 fold=6 epoch=55 loss=9.9785 val_auc=0.8039
gcn top_k=500 fold=6: early stopping at epoch 55

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=500 fold=7 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=500 fold=7 epoch=0 loss=251.5178 val_auc=0.5019
model=gcn top_k=500 fold=7 epoch=1 loss=89.2338 val_auc=0.5910
model=gcn top_k=500 fold=7 epoch=2 loss=18.0234 val_auc=0.6746
model=gcn top_k=500 fold=7 epoch=3 loss=27.4798 val_auc=0.5423
model=gcn top_k=500 fold=7 epoch=4 loss=35.9754 val_auc=0.6038

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=500 fold=7 epoch=5 loss=21.8390 val_auc=0.7622
model=gcn top_k=500 fold=7 epoch=6 loss=19.7657 val_auc=0.7735
model=gcn top_k=500 fold=7 epoch=7 loss=12.3173 val_auc=0.7636
model=gcn top_k=500 fold=7 epoch=8 loss=14.1904 val_auc=0.7798
model=gcn top_k=500 fold=7 epoch=9 loss=13.1873 val_auc=0.7840
model=gcn top_k=500 fold=7 epoch=10 loss=17.5482 val_auc=0.7851
model=gcn top_k=500 fold=7 epoch=11 loss=17.6501 val_auc=0.7682
model=gcn top_k=500 fold=7 epoch=12 loss=13.5452 val_auc=0.7493
model=gcn top_k=500 fold=7 epoch=13 loss=17.3089 val_auc=0.7831
model=gcn top_k=500 fold=7 epoch=14 loss=13.4823 val_auc=0.7852
model=gcn top_k=500 fold=7 epoch=15 loss=13.6428 val_auc=0.7850
model=gcn top_k=500 fold=7 epoch=16 loss=14.9572 val_auc=0.7850
model=gcn top_k=500 fold=7 epoch=17 loss=14.9339 val_auc=0.7789
model=gcn top_k=500 fold=7 epoch=18 loss=14.1491 val_auc=0.7563
model=gcn top_k=500 fold=7 epoch=19 loss=16.1967 val_auc=0.7719
model=gcn top_k=500 fold=7 epoch=20 loss=14.7637 val_auc=0.7856
model=gcn top_k=500 fold=7 epoch=21 loss=14.1461 val_auc=0.7866
model=gcn top_k=500 fold=7 epoch=22 loss=13.7170 val_auc=0.7870
model=gcn top_k=500 fold=7 epoch=23 loss=16.7049 val_auc=0.7869
model=gcn top_k=500 fold=7 epoch=24 loss=13.7570 val_auc=0.7858
model=gcn top_k=500 fold=7 epoch=25 loss=11.9435 val_auc=0.7847
model=gcn top_k=500 fold=7 epoch=26 loss=13.9443 val_auc=0.7785
model=gcn top_k=500 fold=7 epoch=27 loss=12.0923 val_auc=0.7814
model=gcn top_k=500 fold=7 epoch=28 loss=11.2360 val_auc=0.7876
model=gcn top_k=500 fold=7 epoch=29 loss=10.6760 val_auc=0.7890
model=gcn top_k=500 fold=7 epoch=30 loss=12.1191 val_auc=0.7896
model=gcn top_k=500 fold=7 epoch=31 loss=13.6841 val_auc=0.7698
model=gcn top_k=500 fold=7 epoch=32 loss=14.0363 val_auc=0.7701
model=gcn top_k=500 fold=7 epoch=33 loss=14.7124 val_auc=0.7694
model=gcn top_k=500 fold=7 epoch=34 loss=12.3614 val_auc=0.7890
model=gcn top_k=500 fold=7 epoch=35 loss=12.7636 val_auc=0.7900
model=gcn top_k=500 fold=7 epoch=36 loss=12.4111 val_auc=0.7907
model=gcn top_k=500 fold=7 epoch=37 loss=13.7206 val_auc=0.7910
model=gcn top_k=500 fold=7 epoch=38 loss=10.2880 val_auc=0.7911
model=gcn top_k=500 fold=7 epoch=39 loss=11.2848 val_auc=0.7892
model=gcn top_k=500 fold=7 epoch=40 loss=11.3052 val_auc=0.7819
model=gcn top_k=500 fold=7 epoch=41 loss=13.0445 val_auc=0.7860
model=gcn top_k=500 fold=7 epoch=42 loss=12.0651 val_auc=0.7906
model=gcn top_k=500 fold=7 epoch=43 loss=11.6302 val_auc=0.7918
model=gcn top_k=500 fold=7 epoch=44 loss=11.4165 val_auc=0.7915
model=gcn top_k=500 fold=7 epoch=45 loss=14.3130 val_auc=0.7910
model=gcn top_k=500 fold=7 epoch=46 loss=10.9740 val_auc=0.7870
model=gcn top_k=500 fold=7 epoch=47 loss=11.7607 val_auc=0.7852
model=gcn top_k=500 fold=7 epoch=48 loss=10.7058 val_auc=0.7872
model=gcn top_k=500 fold=7 epoch=49 loss=11.8928 val_auc=0.7907
model=gcn top_k=500 fold=7 epoch=50 loss=12.1315 val_auc=0.7920
model=gcn top_k=500 fold=7 epoch=51 loss=10.9877 val_auc=0.7927
model=gcn top_k=500 fold=7 epoch=52 loss=11.9237 val_auc=0.7931
model=gcn top_k=500 fold=7 epoch=53 loss=10.5849 val_auc=0.7935
model=gcn top_k=500 fold=7 epoch=54 loss=10.7844 val_auc=0.7940
model=gcn top_k=500 fold=7 epoch=55 loss=9.5669 val_auc=0.7940
model=gcn top_k=500 fold=7 epoch=56 loss=10.9818 val_auc=0.7958
model=gcn top_k=500 fold=7 epoch=57 loss=10.1478 val_auc=0.7971
model=gcn top_k=500 fold=7 epoch=58 loss=9.0609 val_auc=0.7978
model=gcn top_k=500 fold=7 epoch=59 loss=12.2163 val_auc=0.7979
model=gcn top_k=500 fold=7 epoch=60 loss=11.1063 val_auc=0.7973
model=gcn top_k=500 fold=7 epoch=61 loss=10.1585 val_auc=0.7964
model=gcn top_k=500 fold=7 epoch=62 loss=11.4928 val_auc=0.7978
model=gcn top_k=500 fold=7 epoch=63 loss=9.2870 val_auc=0.7986
model=gcn top_k=500 fold=7 epoch=64 loss=9.2808 val_auc=0.7989
model=gcn top_k=500 fold=7 epoch=65 loss=12.1728 val_auc=0.7989
model=gcn top_k=500 fold=7 epoch=66 loss=10.9646 val_auc=0.7989
model=gcn top_k=500 fold=7 epoch=67 loss=12.9536 val_auc=0.7985
model=gcn top_k=500 fold=7 epoch=68 loss=10.4631 val_auc=0.7982
model=gcn top_k=500 fold=7 epoch=69 loss=10.1401 val_auc=0.7988
model=gcn top_k=500 fold=7 epoch=70 loss=9.4759 val_auc=0.7980
model=gcn top_k=500 fold=7 epoch=71 loss=10.4074 val_auc=0.7990
model=gcn top_k=500 fold=7 epoch=72 loss=9.7060 val_auc=0.7988
model=gcn top_k=500 fold=7 epoch=73 loss=9.8071 val_auc=0.7986
model=gcn top_k=500 fold=7 epoch=74 loss=11.1257 val_auc=0.7995
model=gcn top_k=500 fold=7 epoch=75 loss=9.6137 val_auc=0.8004
model=gcn top_k=500 fold=7 epoch=76 loss=10.8467 val_auc=0.8005
model=gcn top_k=500 fold=7 epoch=77 loss=11.8234 val_auc=0.7994
model=gcn top_k=500 fold=7 epoch=78 loss=9.2769 val_auc=0.7929
model=gcn top_k=500 fold=7 epoch=79 loss=11.3420 val_auc=0.7927
model=gcn top_k=500 fold=7 epoch=80 loss=14.6693 val_auc=0.7989
model=gcn top_k=500 fold=7 epoch=81 loss=10.2884 val_auc=0.8015
model=gcn top_k=500 fold=7 epoch=82 loss=10.2513 val_auc=0.8022
model=gcn top_k=500 fold=7 epoch=83 loss=10.3372 val_auc=0.8026
model=gcn top_k=500 fold=7 epoch=84 loss=9.3026 val_auc=0.8006
model=gcn top_k=500 fold=7 epoch=85 loss=12.8222 val_auc=0.8000
model=gcn top_k=500 fold=7 epoch=86 loss=10.5863 val_auc=0.8014
model=gcn top_k=500 fold=7 epoch=87 loss=9.9838 val_auc=0.8027
model=gcn top_k=500 fold=7 epoch=88 loss=11.0142 val_auc=0.8021
model=gcn top_k=500 fold=7 epoch=89 loss=9.4234 val_auc=0.8020
model=gcn top_k=500 fold=7 epoch=90 loss=8.7469 val_auc=0.8006
model=gcn top_k=500 fold=7 epoch=91 loss=9.2358 val_auc=0.7999
model=gcn top_k=500 fold=7 epoch=92 loss=10.4725 val_auc=0.8012
model=gcn top_k=500 fold=7 epoch=93 loss=10.7149 val_auc=0.8048
model=gcn top_k=500 fold=7 epoch=94 loss=9.3687 val_auc=0.8060
model=gcn top_k=500 fold=7 epoch=95 loss=9.8460 val_auc=0.8064
model=gcn top_k=500 fold=7 epoch=96 loss=10.0723 val_auc=0.8055
model=gcn top_k=500 fold=7 epoch=97 loss=8.7128 val_auc=0.8059
model=gcn top_k=500 fold=7 epoch=98 loss=9.8754 val_auc=0.8068
model=gcn top_k=500 fold=7 epoch=99 loss=9.8277 val_auc=0.8058

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=500 fold=8 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=500 fold=8 epoch=0 loss=194.5841 val_auc=0.5198
model=gcn top_k=500 fold=8 epoch=1 loss=74.0463 val_auc=0.6152
model=gcn top_k=500 fold=8 epoch=2 loss=20.3779 val_auc=0.7296
model=gcn top_k=500 fold=8 epoch=3 loss=23.7537 val_auc=0.5327
model=gcn top_k=500 fold=8 epoch=4 loss=27.3085 val_auc=0.5971
model=gcn top_k=500 fold=8 epoch=5 loss=19.3228 val_auc=0.7562
model=gcn top_k=500 fold=8 epoch=6 loss=17.8925 val_auc=0.7612
model=gcn top_k=500 fold=8 epoch=7 loss=15.7454 val_auc=0.7264
model=gcn top_k=500 fold=8 epoch=8 loss=16.8841 val_auc=0.7277
model=gcn top_k=500 fold=8 epoch=9 loss=15.1260 val_auc=0.7639
model=gcn top_k=500 fold=8 epoch=10 loss=14.0010 val_auc=0.7600
model=gcn top_k=500 fold=8 epoch=11 loss=11.8365 val_auc=0.7642
model=gcn top_k=500 fold=8 epoch=12 loss=13.5446 val_auc=0.7624
model=gcn top_k=500 fold=8 epoch=13 loss=11.8942 val_auc=0.7638
model=gcn top_k=500 fold=8 epoch=14 loss=12.9155 val_auc=0.7664
model=gcn top_k=500 fold=8 epoch=15 loss=13.7565 val_auc=0.7678
model=gcn top_k=500 fold=8 epoch=16 loss=11.3394 val_auc=0.7652
model=gcn top_k=500 fold=8 epoch=17 loss=11.9260 val_auc=0.7657
model=gcn top_k=500 fold=8 epoch=18 loss=12.8760 val_auc=0.7685
model=gcn top_k=500 fold=8 epoch=19 loss=11.7556 val_auc=0.7693
model=gcn top_k=500 fold=8 epoch=20 loss=13.0749 val_auc=0.7683
model=gcn top_k=500 fold=8 epoch=21 loss=10.5687 val_auc=0.7317
model=gcn top_k=500 fold=8 epoch=22 loss=13.0327 val_auc=0.7061
model=gcn top_k=500 fold=8 epoch=23 loss=12.8262 val_auc=0.7488
model=gcn top_k=500 fold=8 epoch=24 loss=12.2302 val_auc=0.7722
model=gcn top_k=500 fold=8 epoch=25 loss=11.0503 val_auc=0.7738
model=gcn top_k=500 fold=8 epoch=26 loss=15.3014 val_auc=0.7730
model=gcn top_k=500 fold=8 epoch=27 loss=16.3126 val_auc=0.7718
model=gcn top_k=500 fold=8 epoch=28 loss=14.7225 val_auc=0.7712
model=gcn top_k=500 fold=8 epoch=29 loss=12.6374 val_auc=0.7452
model=gcn top_k=500 fold=8 epoch=30 loss=15.0221 val_auc=0.6949
model=gcn top_k=500 fold=8 epoch=31 loss=13.3797 val_auc=0.7265
model=gcn top_k=500 fold=8 epoch=32 loss=16.4139 val_auc=0.7688
model=gcn top_k=500 fold=8 epoch=33 loss=12.1320 val_auc=0.7729
model=gcn top_k=500 fold=8 epoch=34 loss=11.9053 val_auc=0.7732
model=gcn top_k=500 fold=8 epoch=35 loss=12.7382 val_auc=0.7735
model=gcn top_k=500 fold=8 epoch=36 loss=13.2207 val_auc=0.7728
model=gcn top_k=500 fold=8 epoch=37 loss=13.6366 val_auc=0.7613
gcn top_k=500 fold=8: early stopping at epoch 37

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

===== Model=gcn top_k=500 fold=9 =====
Config for gcn: {'hidden_dim': 256, 'num_layers': 2, 'num_heads': 1, 'dropout': 0.2, 'max_train_similar_edges_per_node': None, 'query_inference_chunk_size': 512}

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gcn top_k=500 fold=9 epoch=0 loss=226.4469 val_auc=0.5317
model=gcn top_k=500 fold=9 epoch=1 loss=66.1645 val_auc=0.6339
model=gcn top_k=500 fold=9 epoch=2 loss=18.3841 val_auc=0.7631
model=gcn top_k=500 fold=9 epoch=3 loss=14.5951 val_auc=0.5319
model=gcn top_k=500 fold=9 epoch=4 loss=35.5050 val_auc=0.6359
model=gcn top_k=500 fold=9 epoch=5 loss=17.0018 val_auc=0.7703
model=gcn top_k=500 fold=9 epoch=6 loss=16.5327 val_auc=0.7675
model=gcn top_k=500 fold=9 epoch=7 loss=15.4608 val_auc=0.6426
model=gcn top_k=500 fold=9 epoch=8 loss=21.6229 val_auc=0.6538
model=gcn top_k=500 fold=9 epoch=9 loss=20.0456 val_auc=0.7687
model=gcn top_k=500 fold=9 epoch=10 loss=12.5591 val_auc=0.7750
model=gcn top_k=500 fold=9 epoch=11 loss=15.6813 val_auc=0.7586
model=gcn top_k=500 fold=9 epoch=12 loss=13.5965 val_auc=0.7736
model=gcn top_k=500 fold=9 epoch=13 loss=15.9297 val_auc=0.7800
model=gcn top_k=500 fold=9 epoch=14 loss=13.4863 val_auc=0.7804
model=gcn top_k=500 fold=9 epoch=15 loss=15.6986 val_auc=0.7765
model=gcn top_k=500 fold=9 epoch=16 loss=13.0781 val_auc=0.7700
model=gcn top_k=500 fold=9 epoch=17 loss=12.6379 val_auc=0.7720
model=gcn top_k=500 fold=9 epoch=18 loss=12.1410 val_auc=0.7760
model=gcn top_k=500 fold=9 epoch=19 loss=11.1377 val_auc=0.7770
model=gcn top_k=500 fold=9 epoch=20 loss=12.9185 val_auc=0.7797
model=gcn top_k=500 fold=9 epoch=21 loss=12.1865 val_auc=0.7547
model=gcn top_k=500 fold=9 epoch=22 loss=13.2939 val_auc=0.7454
model=gcn top_k=500 fold=9 epoch=23 loss=16.0096 val_auc=0.7798
model=gcn top_k=500 fold=9 epoch=24 loss=12.9821 val_auc=0.7895
model=gcn top_k=500 fold=9 epoch=25 loss=11.4272 val_auc=0.7902
model=gcn top_k=500 fold=9 epoch=26 loss=12.7136 val_auc=0.7903
model=gcn top_k=500 fold=9 epoch=27 loss=19.2718 val_auc=0.7903
model=gcn top_k=500 fold=9 epoch=28 loss=12.2365 val_auc=0.7875
model=gcn top_k=500 fold=9 epoch=29 loss=13.6518 val_auc=0.7308
model=gcn top_k=500 fold=9 epoch=30 loss=15.3531 val_auc=0.6990
model=gcn top_k=500 fold=9 epoch=31 loss=18.5550 val_auc=0.7539
model=gcn top_k=500 fold=9 epoch=32 loss=13.2617 val_auc=0.7838
model=gcn top_k=500 fold=9 epoch=33 loss=15.6303 val_auc=0.7886
model=gcn top_k=500 fold=9 epoch=34 loss=15.3983 val_auc=0.7877
model=gcn top_k=500 fold=9 epoch=35 loss=12.1907 val_auc=0.7867
model=gcn top_k=500 fold=9 epoch=36 loss=13.5632 val_auc=0.7861
model=gcn top_k=500 fold=9 epoch=37 loss=11.1374 val_auc=0.7839
model=gcn top_k=500 fold=9 epoch=38 loss=10.1729 val_auc=0.7821
model=gcn top_k=500 fold=9 epoch=39 loss=11.9793 val_auc=0.7845
gcn top_k=500 fold=9: early stopping at epoch 39

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

######## Model=gat top_k=50 ########

===== Model=gat top_k=50 fold=0 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782165 edges

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=50 fold=0 epoch=0 loss=14.5151 val_auc=0.5295
model=gat top_k=50 fold=0 epoch=1 loss=68.2716 val_auc=0.4734
model=gat top_k=50 fold=0 epoch=2 loss=18.1134 val_auc=0.6194
model=gat top_k=50 fold=0 epoch=3 loss=11.4066 val_auc=0.7207
model=gat top_k=50 fold=0 epoch=4 loss=19.0966 val_auc=0.7443
model=gat top_k=50 fold=0 epoch=5 loss=8.7849 val_auc=0.7026
model=gat top_k=50 fold=0 epoch=6 loss=15.3931 val_auc=0.7573
model=gat top_k=50 fold=0 epoch=7 loss=10.5771 val_auc=0.7691
model=gat top_k=50 fold=0 epoch=8 loss=8.2934 val_auc=0.7786
model=gat top_k=50 fold=0 epoch=9 loss=8.2986 val_auc=0.7814
model=gat top_k=50 fold=0 epoch=10 loss=7.5780 val_auc=0.7841
model=gat top_k=50 fold=0 epoch=11 loss=7.2391 val_auc=0.7874
model=gat top_k=50 fold=0 epoch=12 loss=6.5766 val_auc=0.7912
model=gat top_k=50 fold=0 epoch=13 loss=5.7910 val_auc=0.7937
model=gat top_k=50 fold=0 epoch=14 loss=8.1409 val_auc=0.7943
model=gat top_k=50 fold=0 epoch=15 loss=6.2563 val_auc=0.7942
model=gat top_k=50 fold=0 epoch=16 loss=6.8429 val_auc=0.7945
model=gat top_k=50 fold=0 epoch=17 loss=5.6724 val_auc=0.7948
model=gat top_k=50 fold=0 epoch=18 loss=8.6378 val_auc=0.7943
model=gat top_k=50 fold=0 epoch=19 loss=7.7908 val_auc=0.7923
model=gat top_k=50 fold=0 epoch=20 loss=6.8693 val_auc=0.7933
model=gat top_k=50 fold=0 epoch=21 loss=6.6595 val_auc=0.7948
model=gat top_k=50 fold=0 epoch=22 loss=7.8971 val_auc=0.7965
model=gat top_k=50 fold=0 epoch=23 loss=7.0275 val_auc=0.7976
model=gat top_k=50 fold=0 epoch=24 loss=4.7348 val_auc=0.7939
model=gat top_k=50 fold=0 epoch=25 loss=8.1212 val_auc=0.7945
model=gat top_k=50 fold=0 epoch=26 loss=7.1748 val_auc=0.7995
model=gat top_k=50 fold=0 epoch=27 loss=4.6152 val_auc=0.8003
model=gat top_k=50 fold=0 epoch=28 loss=6.5027 val_auc=0.8019
model=gat top_k=50 fold=0 epoch=29 loss=6.3955 val_auc=0.8035
model=gat top_k=50 fold=0 epoch=30 loss=5.3585 val_auc=0.8037
model=gat top_k=50 fold=0 epoch=31 loss=4.6823 val_auc=0.8029
model=gat top_k=50 fold=0 epoch=32 loss=5.5879 val_auc=0.8025
model=gat top_k=50 fold=0 epoch=33 loss=7.5867 val_auc=0.8041
model=gat top_k=50 fold=0 epoch=34 loss=6.0018 val_auc=0.8011
model=gat top_k=50 fold=0 epoch=35 loss=5.0266 val_auc=0.7987
model=gat top_k=50 fold=0 epoch=36 loss=6.2969 val_auc=0.8005
model=gat top_k=50 fold=0 epoch=37 loss=6.3033 val_auc=0.8048
model=gat top_k=50 fold=0 epoch=38 loss=4.1122 val_auc=0.8050
model=gat top_k=50 fold=0 epoch=39 loss=5.2913 val_auc=0.8076
model=gat top_k=50 fold=0 epoch=40 loss=5.2247 val_auc=0.8102
model=gat top_k=50 fold=0 epoch=41 loss=4.9239 val_auc=0.8106
model=gat top_k=50 fold=0 epoch=42 loss=4.8240 val_auc=0.8095
model=gat top_k=50 fold=0 epoch=43 loss=4.1160 val_auc=0.8004
model=gat top_k=50 fold=0 epoch=44 loss=4.5512 val_auc=0.7841
model=gat top_k=50 fold=0 epoch=45 loss=4.6413 val_auc=0.7807
model=gat top_k=50 fold=0 epoch=46 loss=3.8884 val_auc=0.7850
model=gat top_k=50 fold=0 epoch=47 loss=4.2339 val_auc=0.7889
model=gat top_k=50 fold=0 epoch=48 loss=4.0030 val_auc=0.7973
model=gat top_k=50 fold=0 epoch=49 loss=4.5220 val_auc=0.7968
model=gat top_k=50 fold=0 epoch=50 loss=4.3728 val_auc=0.7944
model=gat top_k=50 fold=0 epoch=51 loss=3.8110 val_auc=0.7857
model=gat top_k=50 fold=0 epoch=52 loss=4.5947 val_auc=0.7784
model=gat top_k=50 fold=0 epoch=53 loss=4.9112 val_auc=0.7748
gat top_k=50 fold=0: early stopping at epoch 53
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782165 edges

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=50 fold=1 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782386 edges

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=50 fold=1 epoch=0 loss=14.4252 val_auc=0.6198
model=gat top_k=50 fold=1 epoch=1 loss=55.4219 val_auc=0.4992
model=gat top_k=50 fold=1 epoch=2 loss=26.7458 val_auc=0.6333
model=gat top_k=50 fold=1 epoch=3 loss=11.4655 val_auc=0.6845
model=gat top_k=50 fold=1 epoch=4 loss=24.4534 val_auc=0.7195
model=gat top_k=50 fold=1 epoch=5 loss=13.1149 val_auc=0.6683
model=gat top_k=50 fold=1 epoch=6 loss=14.9680 val_auc=0.7316
model=gat top_k=50 fold=1 epoch=7 loss=12.2764 val_auc=0.7483
model=gat top_k=50 fold=1 epoch=8 loss=10.4156 val_auc=0.7559
model=gat top_k=50 fold=1 epoch=9 loss=13.0827 val_auc=0.7601
model=gat top_k=50 fold=1 epoch=10 loss=8.2532 val_auc=0.7660
model=gat top_k=50 fold=1 epoch=11 loss=10.2691 val_auc=0.7790
model=gat top_k=50 fold=1 epoch=12 loss=7.6182 val_auc=0.7850
model=gat top_k=50 fold=1 epoch=13 loss=9.5627 val_auc=0.7893
model=gat top_k=50 fold=1 epoch=14 loss=7.5514 val_auc=0.7938
model=gat top_k=50 fold=1 epoch=15 loss=7.6559 val_auc=0.7954
model=gat top_k=50 fold=1 epoch=16 loss=10.2535 val_auc=0.7955
model=gat top_k=50 fold=1 epoch=17 loss=11.5005 val_auc=0.7947
model=gat top_k=50 fold=1 epoch=18 loss=7.4902 val_auc=0.7910
model=gat top_k=50 fold=1 epoch=19 loss=7.2780 val_auc=0.7907
model=gat top_k=50 fold=1 epoch=20 loss=7.8392 val_auc=0.7931
model=gat top_k=50 fold=1 epoch=21 loss=7.5027 val_auc=0.7938
model=gat top_k=50 fold=1 epoch=22 loss=5.8901 val_auc=0.7946
model=gat top_k=50 fold=1 epoch=23 loss=7.3322 val_auc=0.7971
model=gat top_k=50 fold=1 epoch=24 loss=10.2606 val_auc=0.8006
model=gat top_k=50 fold=1 epoch=25 loss=5.8855 val_auc=0.8022
model=gat top_k=50 fold=1 epoch=26 loss=5.9250 val_auc=0.8041
model=gat top_k=50 fold=1 epoch=27 loss=6.2079 val_auc=0.8056
model=gat top_k=50 fold=1 epoch=28 loss=6.9314 val_auc=0.8053
model=gat top_k=50 fold=1 epoch=29 loss=5.2903 val_auc=0.8041
model=gat top_k=50 fold=1 epoch=30 loss=5.9738 val_auc=0.8019
model=gat top_k=50 fold=1 epoch=31 loss=6.2354 val_auc=0.8025
model=gat top_k=50 fold=1 epoch=32 loss=5.5671 val_auc=0.8044
model=gat top_k=50 fold=1 epoch=33 loss=5.2394 val_auc=0.8064
model=gat top_k=50 fold=1 epoch=34 loss=4.5133 val_auc=0.8073
model=gat top_k=50 fold=1 epoch=35 loss=5.0934 val_auc=0.8095
model=gat top_k=50 fold=1 epoch=36 loss=5.1916 val_auc=0.8123
model=gat top_k=50 fold=1 epoch=37 loss=4.1174 val_auc=0.8117
model=gat top_k=50 fold=1 epoch=38 loss=5.8094 val_auc=0.8091
model=gat top_k=50 fold=1 epoch=39 loss=4.6490 val_auc=0.8104
model=gat top_k=50 fold=1 epoch=40 loss=4.1985 val_auc=0.8163
model=gat top_k=50 fold=1 epoch=41 loss=3.9216 val_auc=0.8207
model=gat top_k=50 fold=1 epoch=42 loss=4.9075 val_auc=0.8207
model=gat top_k=50 fold=1 epoch=43 loss=5.8608 val_auc=0.8142
model=gat top_k=50 fold=1 epoch=44 loss=4.7052 val_auc=0.8143
model=gat top_k=50 fold=1 epoch=45 loss=4.5403 val_auc=0.8112
model=gat top_k=50 fold=1 epoch=46 loss=5.1948 val_auc=0.8034
model=gat top_k=50 fold=1 epoch=47 loss=4.1134 val_auc=0.7988
model=gat top_k=50 fold=1 epoch=48 loss=3.9748 val_auc=0.8010
model=gat top_k=50 fold=1 epoch=49 loss=4.7207 val_auc=0.8077
model=gat top_k=50 fold=1 epoch=50 loss=4.3801 val_auc=0.8155
model=gat top_k=50 fold=1 epoch=51 loss=4.3096 val_auc=0.8205
model=gat top_k=50 fold=1 epoch=52 loss=5.1334 val_auc=0.8227
model=gat top_k=50 fold=1 epoch=53 loss=4.3158 val_auc=0.8241
model=gat top_k=50 fold=1 epoch=54 loss=4.6508 val_auc=0.8255
model=gat top_k=50 fold=1 epoch=55 loss=3.5703 val_auc=0.8285
model=gat top_k=50 fold=1 epoch=56 loss=3.4790 val_auc=0.8315
model=gat top_k=50 fold=1 epoch=57 loss=3.8556 val_auc=0.8338
model=gat top_k=50 fold=1 epoch=58 loss=3.6025 val_auc=0.8350
model=gat top_k=50 fold=1 epoch=59 loss=3.0361 val_auc=0.8369
model=gat top_k=50 fold=1 epoch=60 loss=3.8503 val_auc=0.8377
model=gat top_k=50 fold=1 epoch=61 loss=3.7479 val_auc=0.8373
model=gat top_k=50 fold=1 epoch=62 loss=4.0023 val_auc=0.8383
model=gat top_k=50 fold=1 epoch=63 loss=3.3011 val_auc=0.8387
model=gat top_k=50 fold=1 epoch=64 loss=2.7469 val_auc=0.8396
model=gat top_k=50 fold=1 epoch=65 loss=3.6447 val_auc=0.8395
model=gat top_k=50 fold=1 epoch=66 loss=3.6339 val_auc=0.8377
model=gat top_k=50 fold=1 epoch=67 loss=3.5470 val_auc=0.8361
model=gat top_k=50 fold=1 epoch=68 loss=3.4567 val_auc=0.8359
model=gat top_k=50 fold=1 epoch=69 loss=2.6638 val_auc=0.8368
model=gat top_k=50 fold=1 epoch=70 loss=3.6857 val_auc=0.8352
model=gat top_k=50 fold=1 epoch=71 loss=5.7303 val_auc=0.8362
model=gat top_k=50 fold=1 epoch=72 loss=5.2659 val_auc=0.8351
model=gat top_k=50 fold=1 epoch=73 loss=2.6536 val_auc=0.8352
model=gat top_k=50 fold=1 epoch=74 loss=2.9971 val_auc=0.8364
model=gat top_k=50 fold=1 epoch=75 loss=4.3880 val_auc=0.8390
model=gat top_k=50 fold=1 epoch=76 loss=3.6089 val_auc=0.8406
model=gat top_k=50 fold=1 epoch=77 loss=3.5151 val_auc=0.8412
model=gat top_k=50 fold=1 epoch=78 loss=3.2595 val_auc=0.8411
model=gat top_k=50 fold=1 epoch=79 loss=4.9768 val_auc=0.8410
model=gat top_k=50 fold=1 epoch=80 loss=3.1969 val_auc=0.8399
model=gat top_k=50 fold=1 epoch=81 loss=2.4606 val_auc=0.8380
model=gat top_k=50 fold=1 epoch=82 loss=3.3116 val_auc=0.8357
model=gat top_k=50 fold=1 epoch=83 loss=4.2622 val_auc=0.8357
model=gat top_k=50 fold=1 epoch=84 loss=3.9957 val_auc=0.8361
model=gat top_k=50 fold=1 epoch=85 loss=2.3408 val_auc=0.8375
model=gat top_k=50 fold=1 epoch=86 loss=2.5782 val_auc=0.8362
model=gat top_k=50 fold=1 epoch=87 loss=3.1376 val_auc=0.8339
model=gat top_k=50 fold=1 epoch=88 loss=3.0103 val_auc=0.8276
model=gat top_k=50 fold=1 epoch=89 loss=2.4417 val_auc=0.8198
gat top_k=50 fold=1: early stopping at epoch 89
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782386 edges

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=50 fold=2 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782205 edges
model=gat top_k=50 fold=2 epoch=0 loss=12.8452 val_auc=0.5001
model=gat top_k=50 fold=2 epoch=1 loss=103.0715 val_auc=0.6498

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=50 fold=2 epoch=2 loss=17.9986 val_auc=0.6241
model=gat top_k=50 fold=2 epoch=3 loss=37.2195 val_auc=0.6062
model=gat top_k=50 fold=2 epoch=4 loss=28.1029 val_auc=0.6140
model=gat top_k=50 fold=2 epoch=5 loss=11.2719 val_auc=0.5174
model=gat top_k=50 fold=2 epoch=6 loss=18.4818 val_auc=0.5097
model=gat top_k=50 fold=2 epoch=7 loss=18.9538 val_auc=0.6579
model=gat top_k=50 fold=2 epoch=8 loss=10.9575 val_auc=0.6824
model=gat top_k=50 fold=2 epoch=9 loss=10.1723 val_auc=0.6986
model=gat top_k=50 fold=2 epoch=10 loss=14.2413 val_auc=0.7158
model=gat top_k=50 fold=2 epoch=11 loss=9.4776 val_auc=0.7344
model=gat top_k=50 fold=2 epoch=12 loss=10.1608 val_auc=0.7455
model=gat top_k=50 fold=2 epoch=13 loss=10.7792 val_auc=0.7271
model=gat top_k=50 fold=2 epoch=14 loss=11.8925 val_auc=0.7640
model=gat top_k=50 fold=2 epoch=15 loss=7.4206 val_auc=0.7694
model=gat top_k=50 fold=2 epoch=16 loss=7.8852 val_auc=0.7749
model=gat top_k=50 fold=2 epoch=17 loss=9.6106 val_auc=0.7803
model=gat top_k=50 fold=2 epoch=18 loss=8.4923 val_auc=0.7817
model=gat top_k=50 fold=2 epoch=19 loss=7.7704 val_auc=0.7827
model=gat top_k=50 fold=2 epoch=20 loss=7.9005 val_auc=0.7818
model=gat top_k=50 fold=2 epoch=21 loss=9.0841 val_auc=0.7807
model=gat top_k=50 fold=2 epoch=22 loss=11.6977 val_auc=0.7823
model=gat top_k=50 fold=2 epoch=23 loss=7.4236 val_auc=0.7807
model=gat top_k=50 fold=2 epoch=24 loss=6.1094 val_auc=0.7683
model=gat top_k=50 fold=2 epoch=25 loss=8.1870 val_auc=0.7579
model=gat top_k=50 fold=2 epoch=26 loss=8.2715 val_auc=0.7566
model=gat top_k=50 fold=2 epoch=27 loss=8.5103 val_auc=0.7558
model=gat top_k=50 fold=2 epoch=28 loss=7.4643 val_auc=0.7557
model=gat top_k=50 fold=2 epoch=29 loss=7.6526 val_auc=0.7556
model=gat top_k=50 fold=2 epoch=30 loss=7.1595 val_auc=0.7490
model=gat top_k=50 fold=2 epoch=31 loss=10.3378 val_auc=0.7481
gat top_k=50 fold=2: early stopping at epoch 31
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782205 edges

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=50 fold=3 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 781933 edges
model=gat top_k=50 fold=3 epoch=0 loss=17.2378 val_auc=0.5000
model=gat top_k=50 fold=3 epoch=1 loss=107.5100 val_auc=0.4926

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=50 fold=3 epoch=2 loss=19.8123 val_auc=0.6277
model=gat top_k=50 fold=3 epoch=3 loss=44.9940 val_auc=0.6418
model=gat top_k=50 fold=3 epoch=4 loss=39.9127 val_auc=0.6485
model=gat top_k=50 fold=3 epoch=5 loss=13.3957 val_auc=0.4797
model=gat top_k=50 fold=3 epoch=6 loss=23.7080 val_auc=0.4879
model=gat top_k=50 fold=3 epoch=7 loss=25.3470 val_auc=0.7203
model=gat top_k=50 fold=3 epoch=8 loss=10.8122 val_auc=0.7408
model=gat top_k=50 fold=3 epoch=9 loss=12.1076 val_auc=0.7516
model=gat top_k=50 fold=3 epoch=10 loss=15.4025 val_auc=0.7589
model=gat top_k=50 fold=3 epoch=11 loss=9.6656 val_auc=0.7624
model=gat top_k=50 fold=3 epoch=12 loss=8.5156 val_auc=0.7622
model=gat top_k=50 fold=3 epoch=13 loss=12.9205 val_auc=0.7652
model=gat top_k=50 fold=3 epoch=14 loss=9.6429 val_auc=0.7730
model=gat top_k=50 fold=3 epoch=15 loss=7.2836 val_auc=0.7766
model=gat top_k=50 fold=3 epoch=16 loss=8.8664 val_auc=0.7800
model=gat top_k=50 fold=3 epoch=17 loss=8.7898 val_auc=0.7831
model=gat top_k=50 fold=3 epoch=18 loss=6.5584 val_auc=0.7861
model=gat top_k=50 fold=3 epoch=19 loss=7.8343 val_auc=0.7882
model=gat top_k=50 fold=3 epoch=20 loss=7.9823 val_auc=0.7901
model=gat top_k=50 fold=3 epoch=21 loss=7.5834 val_auc=0.7908
model=gat top_k=50 fold=3 epoch=22 loss=5.9497 val_auc=0.7914
model=gat top_k=50 fold=3 epoch=23 loss=6.7091 val_auc=0.7932
model=gat top_k=50 fold=3 epoch=24 loss=5.6882 val_auc=0.7947
model=gat top_k=50 fold=3 epoch=25 loss=6.0462 val_auc=0.7959
model=gat top_k=50 fold=3 epoch=26 loss=5.5228 val_auc=0.7960
model=gat top_k=50 fold=3 epoch=27 loss=5.7748 val_auc=0.7959
model=gat top_k=50 fold=3 epoch=28 loss=5.6198 val_auc=0.7963
model=gat top_k=50 fold=3 epoch=29 loss=5.6454 val_auc=0.7972
model=gat top_k=50 fold=3 epoch=30 loss=5.5813 val_auc=0.7983
model=gat top_k=50 fold=3 epoch=31 loss=5.2413 val_auc=0.7993
model=gat top_k=50 fold=3 epoch=32 loss=5.2838 val_auc=0.8012
model=gat top_k=50 fold=3 epoch=33 loss=5.0724 val_auc=0.8032
model=gat top_k=50 fold=3 epoch=34 loss=5.5553 val_auc=0.8052
model=gat top_k=50 fold=3 epoch=35 loss=4.1989 val_auc=0.8068
model=gat top_k=50 fold=3 epoch=36 loss=4.7243 val_auc=0.8073
model=gat top_k=50 fold=3 epoch=37 loss=4.6428 val_auc=0.8063
model=gat top_k=50 fold=3 epoch=38 loss=4.6775 val_auc=0.8041
model=gat top_k=50 fold=3 epoch=39 loss=4.0944 val_auc=0.8016
model=gat top_k=50 fold=3 epoch=40 loss=4.9616 val_auc=0.8028
model=gat top_k=50 fold=3 epoch=41 loss=4.1385 val_auc=0.8066
model=gat top_k=50 fold=3 epoch=42 loss=4.3042 val_auc=0.8070
model=gat top_k=50 fold=3 epoch=43 loss=5.6656 val_auc=0.8066
model=gat top_k=50 fold=3 epoch=44 loss=4.5257 val_auc=0.8065
model=gat top_k=50 fold=3 epoch=45 loss=5.2408 val_auc=0.8070
model=gat top_k=50 fold=3 epoch=46 loss=4.8027 val_auc=0.8072
model=gat top_k=50 fold=3 epoch=47 loss=4.1369 val_auc=0.8104
model=gat top_k=50 fold=3 epoch=48 loss=3.5242 val_auc=0.8135
model=gat top_k=50 fold=3 epoch=49 loss=3.4137 val_auc=0.8104
model=gat top_k=50 fold=3 epoch=50 loss=3.7437 val_auc=0.8052
model=gat top_k=50 fold=3 epoch=51 loss=3.9088 val_auc=0.8036
model=gat top_k=50 fold=3 epoch=52 loss=3.8337 val_auc=0.8029
model=gat top_k=50 fold=3 epoch=53 loss=4.3894 val_auc=0.8098
model=gat top_k=50 fold=3 epoch=54 loss=3.7638 val_auc=0.8135
model=gat top_k=50 fold=3 epoch=55 loss=3.9962 val_auc=0.8149
model=gat top_k=50 fold=3 epoch=56 loss=3.9332 val_auc=0.8150
model=gat top_k=50 fold=3 epoch=57 loss=3.3090 val_auc=0.8144
model=gat top_k=50 fold=3 epoch=58 loss=4.0646 val_auc=0.8149
model=gat top_k=50 fold=3 epoch=59 loss=3.5736 val_auc=0.8125
model=gat top_k=50 fold=3 epoch=60 loss=3.3723 val_auc=0.8146
model=gat top_k=50 fold=3 epoch=61 loss=4.8217 val_auc=0.8183
model=gat top_k=50 fold=3 epoch=62 loss=5.4348 val_auc=0.8203
model=gat top_k=50 fold=3 epoch=63 loss=3.3174 val_auc=0.8216
model=gat top_k=50 fold=3 epoch=64 loss=3.6121 val_auc=0.8218
model=gat top_k=50 fold=3 epoch=65 loss=5.0213 val_auc=0.8219
model=gat top_k=50 fold=3 epoch=66 loss=3.1461 val_auc=0.8213
model=gat top_k=50 fold=3 epoch=67 loss=3.0830 val_auc=0.8194
model=gat top_k=50 fold=3 epoch=68 loss=3.1089 val_auc=0.8175
model=gat top_k=50 fold=3 epoch=69 loss=3.2946 val_auc=0.8190
model=gat top_k=50 fold=3 epoch=70 loss=4.7586 val_auc=0.8191
model=gat top_k=50 fold=3 epoch=71 loss=4.7643 val_auc=0.8186
model=gat top_k=50 fold=3 epoch=72 loss=3.8259 val_auc=0.8184
model=gat top_k=50 fold=3 epoch=73 loss=2.8504 val_auc=0.8187
model=gat top_k=50 fold=3 epoch=74 loss=3.1863 val_auc=0.8184
model=gat top_k=50 fold=3 epoch=75 loss=2.5432 val_auc=0.8193
model=gat top_k=50 fold=3 epoch=76 loss=2.5867 val_auc=0.8200
model=gat top_k=50 fold=3 epoch=77 loss=3.6286 val_auc=0.8201
gat top_k=50 fold=3: early stopping at epoch 77
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 781933 edges

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=50 fold=4 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782579 edges

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=50 fold=4 epoch=0 loss=16.8672 val_auc=0.5041
model=gat top_k=50 fold=4 epoch=1 loss=66.9646 val_auc=0.5077
model=gat top_k=50 fold=4 epoch=2 loss=10.8090 val_auc=0.6817
model=gat top_k=50 fold=4 epoch=3 loss=11.2499 val_auc=0.7422
model=gat top_k=50 fold=4 epoch=4 loss=14.5790 val_auc=0.7577
model=gat top_k=50 fold=4 epoch=5 loss=8.8945 val_auc=0.6892
model=gat top_k=50 fold=4 epoch=6 loss=18.3331 val_auc=0.7526
model=gat top_k=50 fold=4 epoch=7 loss=11.2065 val_auc=0.7715
model=gat top_k=50 fold=4 epoch=8 loss=11.2211 val_auc=0.7744
model=gat top_k=50 fold=4 epoch=9 loss=12.9433 val_auc=0.7758
model=gat top_k=50 fold=4 epoch=10 loss=9.1556 val_auc=0.7724
model=gat top_k=50 fold=4 epoch=11 loss=8.6389 val_auc=0.7770
model=gat top_k=50 fold=4 epoch=12 loss=7.6668 val_auc=0.7799
model=gat top_k=50 fold=4 epoch=13 loss=7.4985 val_auc=0.7813
model=gat top_k=50 fold=4 epoch=14 loss=9.4919 val_auc=0.7832
model=gat top_k=50 fold=4 epoch=15 loss=6.9505 val_auc=0.7865
model=gat top_k=50 fold=4 epoch=16 loss=6.7043 val_auc=0.7897
model=gat top_k=50 fold=4 epoch=17 loss=5.8737 val_auc=0.7896
model=gat top_k=50 fold=4 epoch=18 loss=7.1882 val_auc=0.7888
model=gat top_k=50 fold=4 epoch=19 loss=5.7772 val_auc=0.7913
model=gat top_k=50 fold=4 epoch=20 loss=5.5153 val_auc=0.7935
model=gat top_k=50 fold=4 epoch=21 loss=7.1799 val_auc=0.7950
model=gat top_k=50 fold=4 epoch=22 loss=6.4613 val_auc=0.7969
model=gat top_k=50 fold=4 epoch=23 loss=5.1007 val_auc=0.7986
model=gat top_k=50 fold=4 epoch=24 loss=6.8630 val_auc=0.7992
model=gat top_k=50 fold=4 epoch=25 loss=6.0386 val_auc=0.8002
model=gat top_k=50 fold=4 epoch=26 loss=5.9537 val_auc=0.8013
model=gat top_k=50 fold=4 epoch=27 loss=5.9051 val_auc=0.8028
model=gat top_k=50 fold=4 epoch=28 loss=6.2214 val_auc=0.8036
model=gat top_k=50 fold=4 epoch=29 loss=4.8059 val_auc=0.8046
model=gat top_k=50 fold=4 epoch=30 loss=4.7659 val_auc=0.8056
model=gat top_k=50 fold=4 epoch=31 loss=4.8717 val_auc=0.8049
model=gat top_k=50 fold=4 epoch=32 loss=5.0273 val_auc=0.7998
model=gat top_k=50 fold=4 epoch=33 loss=5.4039 val_auc=0.7980
model=gat top_k=50 fold=4 epoch=34 loss=5.4418 val_auc=0.8015
model=gat top_k=50 fold=4 epoch=35 loss=4.8094 val_auc=0.8050
model=gat top_k=50 fold=4 epoch=36 loss=4.1363 val_auc=0.8063
model=gat top_k=50 fold=4 epoch=37 loss=4.5910 val_auc=0.8096
model=gat top_k=50 fold=4 epoch=38 loss=4.5635 val_auc=0.8114
model=gat top_k=50 fold=4 epoch=39 loss=3.8561 val_auc=0.8121
model=gat top_k=50 fold=4 epoch=40 loss=6.1191 val_auc=0.8124
model=gat top_k=50 fold=4 epoch=41 loss=5.5093 val_auc=0.8132
model=gat top_k=50 fold=4 epoch=42 loss=4.7760 val_auc=0.8128
model=gat top_k=50 fold=4 epoch=43 loss=5.6022 val_auc=0.8128
model=gat top_k=50 fold=4 epoch=44 loss=4.8649 val_auc=0.8134
model=gat top_k=50 fold=4 epoch=45 loss=4.6843 val_auc=0.8140
model=gat top_k=50 fold=4 epoch=46 loss=5.7391 val_auc=0.8149
model=gat top_k=50 fold=4 epoch=47 loss=7.7106 val_auc=0.8160
model=gat top_k=50 fold=4 epoch=48 loss=5.6183 val_auc=0.8168
model=gat top_k=50 fold=4 epoch=49 loss=4.1500 val_auc=0.8184
model=gat top_k=50 fold=4 epoch=50 loss=4.4305 val_auc=0.8189
model=gat top_k=50 fold=4 epoch=51 loss=4.0265 val_auc=0.8185
model=gat top_k=50 fold=4 epoch=52 loss=3.8291 val_auc=0.8179
model=gat top_k=50 fold=4 epoch=53 loss=6.3882 val_auc=0.8176
model=gat top_k=50 fold=4 epoch=54 loss=7.5322 val_auc=0.8178
model=gat top_k=50 fold=4 epoch=55 loss=4.6291 val_auc=0.8177
model=gat top_k=50 fold=4 epoch=56 loss=3.6777 val_auc=0.8189
model=gat top_k=50 fold=4 epoch=57 loss=5.2404 val_auc=0.8109
model=gat top_k=50 fold=4 epoch=58 loss=7.4358 val_auc=0.8080
model=gat top_k=50 fold=4 epoch=59 loss=7.3797 val_auc=0.8006
model=gat top_k=50 fold=4 epoch=60 loss=7.6457 val_auc=0.7788
model=gat top_k=50 fold=4 epoch=61 loss=3.6915 val_auc=0.7855
model=gat top_k=50 fold=4 epoch=62 loss=4.4065 val_auc=0.7885
model=gat top_k=50 fold=4 epoch=63 loss=3.9035 val_auc=0.7984
model=gat top_k=50 fold=4 epoch=64 loss=3.8645 val_auc=0.8125
model=gat top_k=50 fold=4 epoch=65 loss=3.6672 val_auc=0.8168
model=gat top_k=50 fold=4 epoch=66 loss=4.5339 val_auc=0.8176
model=gat top_k=50 fold=4 epoch=67 loss=4.3169 val_auc=0.8176
model=gat top_k=50 fold=4 epoch=68 loss=3.1879 val_auc=0.8187
gat top_k=50 fold=4: early stopping at epoch 68
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782579 edges

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=50 fold=5 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782265 edges
model=gat top_k=50 fold=5 epoch=0 loss=12.1136 val_auc=0.7407
model=gat top_k=50 fold=5 epoch=1 loss=30.6995 val_auc=0.5007
model=gat top_k=50 fold=5 epoch=2 loss=48.0284 val_auc=0.5570
model=gat top_k=50 fold=5 epoch=3 loss=25.3786 val_auc=0.7311
model=gat top_k=50 fold=5 epoch=4 loss=18.3076 val_auc=0.7311
model=gat top_k=50 fold=5 epoch=5 loss=12.2197 val_auc=0.7291
model=gat top_k=50 fold=5 epoch=6 loss=10.4466 val_auc=0.7363
model=gat top_k=50 fold=5 epoch=7 loss=13.2126 val_auc=0.7403
model=gat top_k=50 fold=5 epoch=8 loss=10.0714 val_auc=0.7416
model=gat top_k=50 fold=5 epoch=9 loss=7.2990 val_auc=0.7459
model=gat top_k=50 fold=5 epoch=10 loss=8.5005 val_auc=0.7523
model=gat top_k=50 fold=5 epoch=11 loss=8.3548 val_auc=0.7572
model=gat top_k=50 fold=5 epoch=12 loss=8.2447 val_auc=0.7633
model=gat top_k=50 fold=5 epoch=13 loss=9.1258 val_auc=0.7744
model=gat top_k=50 fold=5 epoch=14 loss=7.5113 val_auc=0.7884
model=gat top_k=50 fold=5 epoch=15 loss=6.9817 val_auc=0.7977
model=gat top_k=50 fold=5 epoch=16 loss=7.7384 val_auc=0.8009
model=gat top_k=50 fold=5 epoch=17 loss=7.5621 val_auc=0.8019
model=gat top_k=50 fold=5 epoch=18 loss=7.4370 val_auc=0.8022
model=gat top_k=50 fold=5 epoch=19 loss=6.9832 val_auc=0.8033
model=gat top_k=50 fold=5 epoch=20 loss=5.7498 val_auc=0.8043
model=gat top_k=50 fold=5 epoch=21 loss=6.6500 val_auc=0.8058
model=gat top_k=50 fold=5 epoch=22 loss=5.8259 val_auc=0.8069
model=gat top_k=50 fold=5 epoch=23 loss=6.6592 val_auc=0.8082
model=gat top_k=50 fold=5 epoch=24 loss=5.1016 val_auc=0.8085
model=gat top_k=50 fold=5 epoch=25 loss=5.8727 val_auc=0.8078
model=gat top_k=50 fold=5 epoch=26 loss=6.2358 val_auc=0.8072
model=gat top_k=50 fold=5 epoch=27 loss=5.1135 val_auc=0.8075
model=gat top_k=50 fold=5 epoch=28 loss=4.9967 val_auc=0.8079
model=gat top_k=50 fold=5 epoch=29 loss=5.5812 val_auc=0.8086
model=gat top_k=50 fold=5 epoch=30 loss=4.7396 val_auc=0.8110
model=gat top_k=50 fold=5 epoch=31 loss=6.3429 val_auc=0.8118
model=gat top_k=50 fold=5 epoch=32 loss=6.9767 val_auc=0.8147
model=gat top_k=50 fold=5 epoch=33 loss=4.5543 val_auc=0.8155
model=gat top_k=50 fold=5 epoch=34 loss=4.1452 val_auc=0.8159
model=gat top_k=50 fold=5 epoch=35 loss=3.9351 val_auc=0.8162
model=gat top_k=50 fold=5 epoch=36 loss=4.5826 val_auc=0.8164
model=gat top_k=50 fold=5 epoch=37 loss=4.6884 val_auc=0.8163
model=gat top_k=50 fold=5 epoch=38 loss=3.9908 val_auc=0.8162
model=gat top_k=50 fold=5 epoch=39 loss=4.6723 val_auc=0.8160
model=gat top_k=50 fold=5 epoch=40 loss=3.9501 val_auc=0.8162
model=gat top_k=50 fold=5 epoch=41 loss=3.9604 val_auc=0.8157
model=gat top_k=50 fold=5 epoch=42 loss=4.2864 val_auc=0.8151
model=gat top_k=50 fold=5 epoch=43 loss=3.9660 val_auc=0.8158
model=gat top_k=50 fold=5 epoch=44 loss=5.6345 val_auc=0.8151
model=gat top_k=50 fold=5 epoch=45 loss=5.2317 val_auc=0.8145
model=gat top_k=50 fold=5 epoch=46 loss=5.9546 val_auc=0.8138
model=gat top_k=50 fold=5 epoch=47 loss=4.1415 val_auc=0.8150
model=gat top_k=50 fold=5 epoch=48 loss=5.6567 val_auc=0.8161
gat top_k=50 fold=5: early stopping at epoch 48
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782265 edges

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=50 fold=6 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 781867 edges
model=gat top_k=50 fold=6 epoch=0 loss=11.5595 val_auc=0.5003
model=gat top_k=50 fold=6 epoch=1 loss=108.0279 val_auc=0.5075
model=gat top_k=50 fold=6 epoch=2 loss=25.1164 val_auc=0.7032
model=gat top_k=50 fold=6 epoch=3 loss=35.4062 val_auc=0.7150
model=gat top_k=50 fold=6 epoch=4 loss=31.3058 val_auc=0.7337
model=gat top_k=50 fold=6 epoch=5 loss=13.8799 val_auc=0.5809
model=gat top_k=50 fold=6 epoch=6 loss=22.0342 val_auc=0.5806
model=gat top_k=50 fold=6 epoch=7 loss=20.8289 val_auc=0.7460
model=gat top_k=50 fold=6 epoch=8 loss=10.9347 val_auc=0.7545
model=gat top_k=50 fold=6 epoch=9 loss=11.7097 val_auc=0.7574
model=gat top_k=50 fold=6 epoch=10 loss=13.3202 val_auc=0.7600
model=gat top_k=50 fold=6 epoch=11 loss=9.4352 val_auc=0.7596
model=gat top_k=50 fold=6 epoch=12 loss=9.2361 val_auc=0.7600
model=gat top_k=50 fold=6 epoch=13 loss=10.8804 val_auc=0.7618
model=gat top_k=50 fold=6 epoch=14 loss=11.3461 val_auc=0.7694
model=gat top_k=50 fold=6 epoch=15 loss=7.8281 val_auc=0.7752
model=gat top_k=50 fold=6 epoch=16 loss=9.3866 val_auc=0.7778
model=gat top_k=50 fold=6 epoch=17 loss=7.9538 val_auc=0.7788
model=gat top_k=50 fold=6 epoch=18 loss=8.5136 val_auc=0.7782
model=gat top_k=50 fold=6 epoch=19 loss=6.4260 val_auc=0.7785
model=gat top_k=50 fold=6 epoch=20 loss=8.6336 val_auc=0.7800
model=gat top_k=50 fold=6 epoch=21 loss=6.4263 val_auc=0.7815
model=gat top_k=50 fold=6 epoch=22 loss=6.2445 val_auc=0.7815
model=gat top_k=50 fold=6 epoch=23 loss=9.1347 val_auc=0.7836
model=gat top_k=50 fold=6 epoch=24 loss=5.6593 val_auc=0.7882
model=gat top_k=50 fold=6 epoch=25 loss=5.7631 val_auc=0.7938
model=gat top_k=50 fold=6 epoch=26 loss=6.2111 val_auc=0.7994
model=gat top_k=50 fold=6 epoch=27 loss=5.1399 val_auc=0.8044
model=gat top_k=50 fold=6 epoch=28 loss=6.0509 val_auc=0.8052
model=gat top_k=50 fold=6 epoch=29 loss=6.9128 val_auc=0.8007
model=gat top_k=50 fold=6 epoch=30 loss=5.1916 val_auc=0.7992
model=gat top_k=50 fold=6 epoch=31 loss=5.6390 val_auc=0.7998
model=gat top_k=50 fold=6 epoch=32 loss=6.7543 val_auc=0.8007
model=gat top_k=50 fold=6 epoch=33 loss=5.5904 val_auc=0.8035
model=gat top_k=50 fold=6 epoch=34 loss=5.0668 val_auc=0.8067
model=gat top_k=50 fold=6 epoch=35 loss=5.9458 val_auc=0.8099
model=gat top_k=50 fold=6 epoch=36 loss=4.8607 val_auc=0.8109
model=gat top_k=50 fold=6 epoch=37 loss=5.9389 val_auc=0.8109
model=gat top_k=50 fold=6 epoch=38 loss=5.6925 val_auc=0.8109
model=gat top_k=50 fold=6 epoch=39 loss=7.3376 val_auc=0.8109
model=gat top_k=50 fold=6 epoch=40 loss=5.2491 val_auc=0.8116
model=gat top_k=50 fold=6 epoch=41 loss=5.7891 val_auc=0.8099
model=gat top_k=50 fold=6 epoch=42 loss=8.1756 val_auc=0.8079
model=gat top_k=50 fold=6 epoch=43 loss=9.8658 val_auc=0.8107
model=gat top_k=50 fold=6 epoch=44 loss=5.7108 val_auc=0.8083
model=gat top_k=50 fold=6 epoch=45 loss=4.3581 val_auc=0.8099
model=gat top_k=50 fold=6 epoch=46 loss=7.1564 val_auc=0.8111
model=gat top_k=50 fold=6 epoch=47 loss=6.0331 val_auc=0.8106
model=gat top_k=50 fold=6 epoch=48 loss=4.6823 val_auc=0.8104
model=gat top_k=50 fold=6 epoch=49 loss=4.0475 val_auc=0.8115
model=gat top_k=50 fold=6 epoch=50 loss=5.4780 val_auc=0.8135
model=gat top_k=50 fold=6 epoch=51 loss=6.8025 val_auc=0.8153
model=gat top_k=50 fold=6 epoch=52 loss=3.9462 val_auc=0.8171
model=gat top_k=50 fold=6 epoch=53 loss=4.3044 val_auc=0.8162
model=gat top_k=50 fold=6 epoch=54 loss=4.1296 val_auc=0.8160
model=gat top_k=50 fold=6 epoch=55 loss=3.7383 val_auc=0.8189
model=gat top_k=50 fold=6 epoch=56 loss=5.5262 val_auc=0.8190
model=gat top_k=50 fold=6 epoch=57 loss=5.0305 val_auc=0.8189
model=gat top_k=50 fold=6 epoch=58 loss=3.4070 val_auc=0.8193
model=gat top_k=50 fold=6 epoch=59 loss=4.1425 val_auc=0.8198
model=gat top_k=50 fold=6 epoch=60 loss=4.6547 val_auc=0.8205
model=gat top_k=50 fold=6 epoch=61 loss=4.2838 val_auc=0.8218
model=gat top_k=50 fold=6 epoch=62 loss=3.3756 val_auc=0.8241
model=gat top_k=50 fold=6 epoch=63 loss=3.5243 val_auc=0.8257
model=gat top_k=50 fold=6 epoch=64 loss=3.4482 val_auc=0.8273
model=gat top_k=50 fold=6 epoch=65 loss=3.7608 val_auc=0.8276
model=gat top_k=50 fold=6 epoch=66 loss=3.7804 val_auc=0.8271
model=gat top_k=50 fold=6 epoch=67 loss=3.6586 val_auc=0.8272
model=gat top_k=50 fold=6 epoch=68 loss=3.4976 val_auc=0.8289
model=gat top_k=50 fold=6 epoch=69 loss=3.8694 val_auc=0.8303
model=gat top_k=50 fold=6 epoch=70 loss=2.8734 val_auc=0.8309
model=gat top_k=50 fold=6 epoch=71 loss=3.8887 val_auc=0.8306
model=gat top_k=50 fold=6 epoch=72 loss=3.4379 val_auc=0.8303
model=gat top_k=50 fold=6 epoch=73 loss=2.6992 val_auc=0.8307
model=gat top_k=50 fold=6 epoch=74 loss=3.1817 val_auc=0.8320
model=gat top_k=50 fold=6 epoch=75 loss=2.9968 val_auc=0.8305
model=gat top_k=50 fold=6 epoch=76 loss=3.6499 val_auc=0.8286
model=gat top_k=50 fold=6 epoch=77 loss=2.9684 val_auc=0.8283
model=gat top_k=50 fold=6 epoch=78 loss=3.5371 val_auc=0.8290
model=gat top_k=50 fold=6 epoch=79 loss=4.0458 val_auc=0.8300
model=gat top_k=50 fold=6 epoch=80 loss=2.7681 val_auc=0.8313
model=gat top_k=50 fold=6 epoch=81 loss=2.9912 val_auc=0.8318
model=gat top_k=50 fold=6 epoch=82 loss=3.4071 val_auc=0.8318
model=gat top_k=50 fold=6 epoch=83 loss=3.1298 val_auc=0.8313
model=gat top_k=50 fold=6 epoch=84 loss=3.0641 val_auc=0.8310
model=gat top_k=50 fold=6 epoch=85 loss=2.6422 val_auc=0.8307
model=gat top_k=50 fold=6 epoch=86 loss=2.9858 val_auc=0.8311
gat top_k=50 fold=6: early stopping at epoch 86
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 781867 edges

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=50 fold=7 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782278 edges

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=50 fold=7 epoch=0 loss=11.6651 val_auc=0.5219
model=gat top_k=50 fold=7 epoch=1 loss=78.5327 val_auc=0.7000
model=gat top_k=50 fold=7 epoch=2 loss=11.8349 val_auc=0.5356
model=gat top_k=50 fold=7 epoch=3 loss=25.1618 val_auc=0.7299
model=gat top_k=50 fold=7 epoch=4 loss=11.7020 val_auc=0.7377
model=gat top_k=50 fold=7 epoch=5 loss=9.0829 val_auc=0.7459
model=gat top_k=50 fold=7 epoch=6 loss=10.2060 val_auc=0.7588
model=gat top_k=50 fold=7 epoch=7 loss=9.1704 val_auc=0.7697
model=gat top_k=50 fold=7 epoch=8 loss=7.9801 val_auc=0.7775
model=gat top_k=50 fold=7 epoch=9 loss=8.9925 val_auc=0.7819
model=gat top_k=50 fold=7 epoch=10 loss=7.5199 val_auc=0.7885
model=gat top_k=50 fold=7 epoch=11 loss=9.7278 val_auc=0.7911
model=gat top_k=50 fold=7 epoch=12 loss=6.8323 val_auc=0.7934
model=gat top_k=50 fold=7 epoch=13 loss=6.1239 val_auc=0.7955
model=gat top_k=50 fold=7 epoch=14 loss=6.7367 val_auc=0.7957
model=gat top_k=50 fold=7 epoch=15 loss=6.2184 val_auc=0.7942
model=gat top_k=50 fold=7 epoch=16 loss=6.2003 val_auc=0.7927
model=gat top_k=50 fold=7 epoch=17 loss=9.8676 val_auc=0.7917
model=gat top_k=50 fold=7 epoch=18 loss=5.6028 val_auc=0.7873
model=gat top_k=50 fold=7 epoch=19 loss=7.4279 val_auc=0.7932
model=gat top_k=50 fold=7 epoch=20 loss=8.7852 val_auc=0.7978
model=gat top_k=50 fold=7 epoch=21 loss=6.4571 val_auc=0.7998
model=gat top_k=50 fold=7 epoch=22 loss=8.6488 val_auc=0.8002
model=gat top_k=50 fold=7 epoch=23 loss=5.0288 val_auc=0.7981
model=gat top_k=50 fold=7 epoch=24 loss=6.7043 val_auc=0.7964
model=gat top_k=50 fold=7 epoch=25 loss=6.3403 val_auc=0.7991
model=gat top_k=50 fold=7 epoch=26 loss=5.2250 val_auc=0.8004
model=gat top_k=50 fold=7 epoch=27 loss=5.2529 val_auc=0.8012
model=gat top_k=50 fold=7 epoch=28 loss=5.7288 val_auc=0.8014
model=gat top_k=50 fold=7 epoch=29 loss=5.7748 val_auc=0.8015
model=gat top_k=50 fold=7 epoch=30 loss=5.0330 val_auc=0.8008
model=gat top_k=50 fold=7 epoch=31 loss=6.1760 val_auc=0.8026
model=gat top_k=50 fold=7 epoch=32 loss=5.1600 val_auc=0.8030
model=gat top_k=50 fold=7 epoch=33 loss=4.9270 val_auc=0.8038
model=gat top_k=50 fold=7 epoch=34 loss=6.0355 val_auc=0.8039
model=gat top_k=50 fold=7 epoch=35 loss=4.1411 val_auc=0.8045
model=gat top_k=50 fold=7 epoch=36 loss=4.6808 val_auc=0.8053
model=gat top_k=50 fold=7 epoch=37 loss=4.6796 val_auc=0.8059
model=gat top_k=50 fold=7 epoch=38 loss=3.9388 val_auc=0.8073
model=gat top_k=50 fold=7 epoch=39 loss=3.6595 val_auc=0.8108
model=gat top_k=50 fold=7 epoch=40 loss=5.6910 val_auc=0.8133
model=gat top_k=50 fold=7 epoch=41 loss=4.8809 val_auc=0.8135
model=gat top_k=50 fold=7 epoch=42 loss=4.0594 val_auc=0.8161
model=gat top_k=50 fold=7 epoch=43 loss=4.6468 val_auc=0.8179
model=gat top_k=50 fold=7 epoch=44 loss=4.7945 val_auc=0.8182
model=gat top_k=50 fold=7 epoch=45 loss=4.1137 val_auc=0.8188
model=gat top_k=50 fold=7 epoch=46 loss=5.3437 val_auc=0.8186
model=gat top_k=50 fold=7 epoch=47 loss=4.1661 val_auc=0.8181
model=gat top_k=50 fold=7 epoch=48 loss=4.4705 val_auc=0.8182
model=gat top_k=50 fold=7 epoch=49 loss=4.5504 val_auc=0.8179
model=gat top_k=50 fold=7 epoch=50 loss=3.9360 val_auc=0.8187
model=gat top_k=50 fold=7 epoch=51 loss=4.2769 val_auc=0.8191
model=gat top_k=50 fold=7 epoch=52 loss=4.6171 val_auc=0.8196
model=gat top_k=50 fold=7 epoch=53 loss=4.9681 val_auc=0.8201
model=gat top_k=50 fold=7 epoch=54 loss=4.0789 val_auc=0.8206
model=gat top_k=50 fold=7 epoch=55 loss=4.1573 val_auc=0.8209
model=gat top_k=50 fold=7 epoch=56 loss=3.3219 val_auc=0.8212
model=gat top_k=50 fold=7 epoch=57 loss=4.2568 val_auc=0.8214
model=gat top_k=50 fold=7 epoch=58 loss=3.3246 val_auc=0.8208
model=gat top_k=50 fold=7 epoch=59 loss=2.7787 val_auc=0.8196
model=gat top_k=50 fold=7 epoch=60 loss=3.3965 val_auc=0.8175
model=gat top_k=50 fold=7 epoch=61 loss=3.2152 val_auc=0.8137
model=gat top_k=50 fold=7 epoch=62 loss=2.9308 val_auc=0.8152
model=gat top_k=50 fold=7 epoch=63 loss=3.4266 val_auc=0.8182
model=gat top_k=50 fold=7 epoch=64 loss=3.9414 val_auc=0.8234
model=gat top_k=50 fold=7 epoch=65 loss=3.6432 val_auc=0.8271
model=gat top_k=50 fold=7 epoch=66 loss=4.2124 val_auc=0.8268
model=gat top_k=50 fold=7 epoch=67 loss=2.8586 val_auc=0.8251
model=gat top_k=50 fold=7 epoch=68 loss=3.6141 val_auc=0.8248
model=gat top_k=50 fold=7 epoch=69 loss=2.9941 val_auc=0.8262
model=gat top_k=50 fold=7 epoch=70 loss=2.6924 val_auc=0.8293
model=gat top_k=50 fold=7 epoch=71 loss=3.2267 val_auc=0.8315
model=gat top_k=50 fold=7 epoch=72 loss=3.3760 val_auc=0.8323
model=gat top_k=50 fold=7 epoch=73 loss=3.5247 val_auc=0.8331
model=gat top_k=50 fold=7 epoch=74 loss=3.5130 val_auc=0.8338
model=gat top_k=50 fold=7 epoch=75 loss=2.7722 val_auc=0.8337
model=gat top_k=50 fold=7 epoch=76 loss=3.3289 val_auc=0.8323
model=gat top_k=50 fold=7 epoch=77 loss=3.5939 val_auc=0.8330
model=gat top_k=50 fold=7 epoch=78 loss=3.1135 val_auc=0.8335
model=gat top_k=50 fold=7 epoch=79 loss=2.4033 val_auc=0.8342
model=gat top_k=50 fold=7 epoch=80 loss=3.8293 val_auc=0.8348
model=gat top_k=50 fold=7 epoch=81 loss=4.5112 val_auc=0.8357
model=gat top_k=50 fold=7 epoch=82 loss=4.5814 val_auc=0.8370
model=gat top_k=50 fold=7 epoch=83 loss=2.6275 val_auc=0.8374
model=gat top_k=50 fold=7 epoch=84 loss=3.3165 val_auc=0.8373
model=gat top_k=50 fold=7 epoch=85 loss=4.4207 val_auc=0.8361
model=gat top_k=50 fold=7 epoch=86 loss=4.9025 val_auc=0.8341
model=gat top_k=50 fold=7 epoch=87 loss=3.4704 val_auc=0.8316
model=gat top_k=50 fold=7 epoch=88 loss=2.2722 val_auc=0.8307
model=gat top_k=50 fold=7 epoch=89 loss=2.4008 val_auc=0.8316
model=gat top_k=50 fold=7 epoch=90 loss=3.1834 val_auc=0.8334
model=gat top_k=50 fold=7 epoch=91 loss=2.3677 val_auc=0.8354
model=gat top_k=50 fold=7 epoch=92 loss=2.1204 val_auc=0.8366
model=gat top_k=50 fold=7 epoch=93 loss=2.6916 val_auc=0.8366
model=gat top_k=50 fold=7 epoch=94 loss=2.1090 val_auc=0.8368
model=gat top_k=50 fold=7 epoch=95 loss=2.2826 val_auc=0.8369
gat top_k=50 fold=7: early stopping at epoch 95
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782278 edges

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=50 fold=8 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782047 edges

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=50 fold=8 epoch=0 loss=10.9237 val_auc=0.5843
model=gat top_k=50 fold=8 epoch=1 loss=61.2962 val_auc=0.5210
model=gat top_k=50 fold=8 epoch=2 loss=23.6288 val_auc=0.7116
model=gat top_k=50 fold=8 epoch=3 loss=9.6662 val_auc=0.5632
model=gat top_k=50 fold=8 epoch=4 loss=20.5097 val_auc=0.7455
model=gat top_k=50 fold=8 epoch=5 loss=13.9595 val_auc=0.7583
model=gat top_k=50 fold=8 epoch=6 loss=14.7225 val_auc=0.7512
model=gat top_k=50 fold=8 epoch=7 loss=15.7817 val_auc=0.7422
model=gat top_k=50 fold=8 epoch=8 loss=9.3070 val_auc=0.7041
model=gat top_k=50 fold=8 epoch=9 loss=13.6267 val_auc=0.5625
model=gat top_k=50 fold=8 epoch=10 loss=16.3872 val_auc=0.7628
model=gat top_k=50 fold=8 epoch=11 loss=11.5366 val_auc=0.7727
model=gat top_k=50 fold=8 epoch=12 loss=7.3006 val_auc=0.7621
model=gat top_k=50 fold=8 epoch=13 loss=9.2338 val_auc=0.7465
model=gat top_k=50 fold=8 epoch=14 loss=7.8862 val_auc=0.7461
model=gat top_k=50 fold=8 epoch=15 loss=5.9829 val_auc=0.7491
model=gat top_k=50 fold=8 epoch=16 loss=6.6384 val_auc=0.7293
model=gat top_k=50 fold=8 epoch=17 loss=11.2368 val_auc=0.7181
model=gat top_k=50 fold=8 epoch=18 loss=14.4560 val_auc=0.7809
model=gat top_k=50 fold=8 epoch=19 loss=8.5521 val_auc=0.7860
model=gat top_k=50 fold=8 epoch=20 loss=6.7338 val_auc=0.7885
model=gat top_k=50 fold=8 epoch=21 loss=8.6925 val_auc=0.7902
model=gat top_k=50 fold=8 epoch=22 loss=9.5357 val_auc=0.7909
model=gat top_k=50 fold=8 epoch=23 loss=7.1964 val_auc=0.7916
model=gat top_k=50 fold=8 epoch=24 loss=6.2700 val_auc=0.7896
model=gat top_k=50 fold=8 epoch=25 loss=8.3356 val_auc=0.7790
model=gat top_k=50 fold=8 epoch=26 loss=11.7243 val_auc=0.7850
model=gat top_k=50 fold=8 epoch=27 loss=8.3999 val_auc=0.7873
model=gat top_k=50 fold=8 epoch=28 loss=6.5373 val_auc=0.7877
model=gat top_k=50 fold=8 epoch=29 loss=5.4244 val_auc=0.7875
model=gat top_k=50 fold=8 epoch=30 loss=7.0445 val_auc=0.7878
model=gat top_k=50 fold=8 epoch=31 loss=9.5970 val_auc=0.7884
model=gat top_k=50 fold=8 epoch=32 loss=9.1565 val_auc=0.7896
model=gat top_k=50 fold=8 epoch=33 loss=5.9773 val_auc=0.7922
model=gat top_k=50 fold=8 epoch=34 loss=5.6823 val_auc=0.7904
model=gat top_k=50 fold=8 epoch=35 loss=8.6177 val_auc=0.7837
model=gat top_k=50 fold=8 epoch=36 loss=8.1600 val_auc=0.7903
model=gat top_k=50 fold=8 epoch=37 loss=7.9236 val_auc=0.7933
model=gat top_k=50 fold=8 epoch=38 loss=6.0119 val_auc=0.7920
model=gat top_k=50 fold=8 epoch=39 loss=4.4568 val_auc=0.7896
model=gat top_k=50 fold=8 epoch=40 loss=6.3534 val_auc=0.7870
model=gat top_k=50 fold=8 epoch=41 loss=6.0001 val_auc=0.7839
model=gat top_k=50 fold=8 epoch=42 loss=4.7362 val_auc=0.7845
model=gat top_k=50 fold=8 epoch=43 loss=4.0082 val_auc=0.7870
model=gat top_k=50 fold=8 epoch=44 loss=5.6662 val_auc=0.7883
model=gat top_k=50 fold=8 epoch=45 loss=5.0979 val_auc=0.7896
model=gat top_k=50 fold=8 epoch=46 loss=4.8096 val_auc=0.7918
model=gat top_k=50 fold=8 epoch=47 loss=4.4906 val_auc=0.7967
model=gat top_k=50 fold=8 epoch=48 loss=4.6383 val_auc=0.8012
model=gat top_k=50 fold=8 epoch=49 loss=3.7089 val_auc=0.8041
model=gat top_k=50 fold=8 epoch=50 loss=4.0949 val_auc=0.8061
model=gat top_k=50 fold=8 epoch=51 loss=3.8587 val_auc=0.8067
model=gat top_k=50 fold=8 epoch=52 loss=3.9905 val_auc=0.8075
model=gat top_k=50 fold=8 epoch=53 loss=4.1390 val_auc=0.8086
model=gat top_k=50 fold=8 epoch=54 loss=3.7837 val_auc=0.8097
model=gat top_k=50 fold=8 epoch=55 loss=3.0674 val_auc=0.8114
model=gat top_k=50 fold=8 epoch=56 loss=3.0069 val_auc=0.8132
model=gat top_k=50 fold=8 epoch=57 loss=3.2029 val_auc=0.8150
model=gat top_k=50 fold=8 epoch=58 loss=3.5481 val_auc=0.8161
model=gat top_k=50 fold=8 epoch=59 loss=4.2981 val_auc=0.8172
model=gat top_k=50 fold=8 epoch=60 loss=4.2071 val_auc=0.8174
model=gat top_k=50 fold=8 epoch=61 loss=2.8890 val_auc=0.8167
model=gat top_k=50 fold=8 epoch=62 loss=3.3005 val_auc=0.8167
model=gat top_k=50 fold=8 epoch=63 loss=2.8034 val_auc=0.8176
model=gat top_k=50 fold=8 epoch=64 loss=4.8671 val_auc=0.8169
model=gat top_k=50 fold=8 epoch=65 loss=3.8143 val_auc=0.8157
model=gat top_k=50 fold=8 epoch=66 loss=2.9554 val_auc=0.8153
model=gat top_k=50 fold=8 epoch=67 loss=2.7837 val_auc=0.8162
model=gat top_k=50 fold=8 epoch=68 loss=3.4179 val_auc=0.8176
model=gat top_k=50 fold=8 epoch=69 loss=4.2697 val_auc=0.8183
model=gat top_k=50 fold=8 epoch=70 loss=3.2726 val_auc=0.8191
model=gat top_k=50 fold=8 epoch=71 loss=3.5072 val_auc=0.8192
model=gat top_k=50 fold=8 epoch=72 loss=3.6774 val_auc=0.8200
model=gat top_k=50 fold=8 epoch=73 loss=2.6933 val_auc=0.8203
model=gat top_k=50 fold=8 epoch=74 loss=3.2670 val_auc=0.8196
model=gat top_k=50 fold=8 epoch=75 loss=2.3968 val_auc=0.8193
model=gat top_k=50 fold=8 epoch=76 loss=2.4165 val_auc=0.8196
model=gat top_k=50 fold=8 epoch=77 loss=2.3434 val_auc=0.8197
model=gat top_k=50 fold=8 epoch=78 loss=2.3299 val_auc=0.8189
model=gat top_k=50 fold=8 epoch=79 loss=3.6179 val_auc=0.8183
model=gat top_k=50 fold=8 epoch=80 loss=2.8017 val_auc=0.8180
model=gat top_k=50 fold=8 epoch=81 loss=2.2347 val_auc=0.8179
model=gat top_k=50 fold=8 epoch=82 loss=3.0285 val_auc=0.8177
model=gat top_k=50 fold=8 epoch=83 loss=2.8858 val_auc=0.8173
model=gat top_k=50 fold=8 epoch=84 loss=2.3810 val_auc=0.8183
model=gat top_k=50 fold=8 epoch=85 loss=2.8273 val_auc=0.8193
gat top_k=50 fold=8: early stopping at epoch 85
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782047 edges

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=50 fold=9 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 781970 edges

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=50 fold=9 epoch=0 loss=17.1816 val_auc=0.5267
model=gat top_k=50 fold=9 epoch=1 loss=76.7618 val_auc=0.6116
model=gat top_k=50 fold=9 epoch=2 loss=14.6368 val_auc=0.6420
model=gat top_k=50 fold=9 epoch=3 loss=14.3791 val_auc=0.6666
model=gat top_k=50 fold=9 epoch=4 loss=22.6153 val_auc=0.6955
model=gat top_k=50 fold=9 epoch=5 loss=18.1199 val_auc=0.7162
model=gat top_k=50 fold=9 epoch=6 loss=10.3493 val_auc=0.7104
model=gat top_k=50 fold=9 epoch=7 loss=11.4048 val_auc=0.7271
model=gat top_k=50 fold=9 epoch=8 loss=8.5030 val_auc=0.7351
model=gat top_k=50 fold=9 epoch=9 loss=8.5994 val_auc=0.7588
model=gat top_k=50 fold=9 epoch=10 loss=10.3334 val_auc=0.7712
model=gat top_k=50 fold=9 epoch=11 loss=7.4306 val_auc=0.7475
model=gat top_k=50 fold=9 epoch=12 loss=11.8453 val_auc=0.7778
model=gat top_k=50 fold=9 epoch=13 loss=7.5777 val_auc=0.7757
model=gat top_k=50 fold=9 epoch=14 loss=8.3006 val_auc=0.7776
model=gat top_k=50 fold=9 epoch=15 loss=7.8287 val_auc=0.7825
model=gat top_k=50 fold=9 epoch=16 loss=7.6502 val_auc=0.7878
model=gat top_k=50 fold=9 epoch=17 loss=6.7451 val_auc=0.7888
model=gat top_k=50 fold=9 epoch=18 loss=10.1298 val_auc=0.7933
model=gat top_k=50 fold=9 epoch=19 loss=8.6008 val_auc=0.7944
model=gat top_k=50 fold=9 epoch=20 loss=7.8454 val_auc=0.7960
model=gat top_k=50 fold=9 epoch=21 loss=7.7242 val_auc=0.7971
model=gat top_k=50 fold=9 epoch=22 loss=7.0774 val_auc=0.7973
model=gat top_k=50 fold=9 epoch=23 loss=6.1537 val_auc=0.7980
model=gat top_k=50 fold=9 epoch=24 loss=5.4380 val_auc=0.7991
model=gat top_k=50 fold=9 epoch=25 loss=5.9053 val_auc=0.7999
model=gat top_k=50 fold=9 epoch=26 loss=5.6244 val_auc=0.8020
model=gat top_k=50 fold=9 epoch=27 loss=5.1137 val_auc=0.8033
model=gat top_k=50 fold=9 epoch=28 loss=4.5871 val_auc=0.8048
model=gat top_k=50 fold=9 epoch=29 loss=4.9110 val_auc=0.8055
model=gat top_k=50 fold=9 epoch=30 loss=5.3212 val_auc=0.8057
model=gat top_k=50 fold=9 epoch=31 loss=5.3240 val_auc=0.8053
model=gat top_k=50 fold=9 epoch=32 loss=6.6330 val_auc=0.7985
model=gat top_k=50 fold=9 epoch=33 loss=10.1845 val_auc=0.8006
model=gat top_k=50 fold=9 epoch=34 loss=6.7845 val_auc=0.7979
model=gat top_k=50 fold=9 epoch=35 loss=4.8197 val_auc=0.7984
model=gat top_k=50 fold=9 epoch=36 loss=4.4701 val_auc=0.8011
model=gat top_k=50 fold=9 epoch=37 loss=6.1500 val_auc=0.8044
model=gat top_k=50 fold=9 epoch=38 loss=4.8701 val_auc=0.8059
model=gat top_k=50 fold=9 epoch=39 loss=4.4994 val_auc=0.8060
model=gat top_k=50 fold=9 epoch=40 loss=6.2178 val_auc=0.8058
model=gat top_k=50 fold=9 epoch=41 loss=4.3017 val_auc=0.8060
model=gat top_k=50 fold=9 epoch=42 loss=4.5102 val_auc=0.8070
model=gat top_k=50 fold=9 epoch=43 loss=5.7439 val_auc=0.8094
model=gat top_k=50 fold=9 epoch=44 loss=6.1829 val_auc=0.8112
model=gat top_k=50 fold=9 epoch=45 loss=3.8257 val_auc=0.8126
model=gat top_k=50 fold=9 epoch=46 loss=4.0495 val_auc=0.8142
model=gat top_k=50 fold=9 epoch=47 loss=4.3281 val_auc=0.8152
model=gat top_k=50 fold=9 epoch=48 loss=3.9807 val_auc=0.8152
model=gat top_k=50 fold=9 epoch=49 loss=4.2489 val_auc=0.8149
model=gat top_k=50 fold=9 epoch=50 loss=3.8902 val_auc=0.8131
model=gat top_k=50 fold=9 epoch=51 loss=3.7018 val_auc=0.8135
model=gat top_k=50 fold=9 epoch=52 loss=3.2096 val_auc=0.8151
model=gat top_k=50 fold=9 epoch=53 loss=3.4197 val_auc=0.8176
model=gat top_k=50 fold=9 epoch=54 loss=3.6568 val_auc=0.8196
model=gat top_k=50 fold=9 epoch=55 loss=3.9886 val_auc=0.8211
model=gat top_k=50 fold=9 epoch=56 loss=3.4629 val_auc=0.8220
model=gat top_k=50 fold=9 epoch=57 loss=3.3524 val_auc=0.8228
model=gat top_k=50 fold=9 epoch=58 loss=3.2894 val_auc=0.8236
model=gat top_k=50 fold=9 epoch=59 loss=3.0877 val_auc=0.8242
model=gat top_k=50 fold=9 epoch=60 loss=3.5811 val_auc=0.8244
model=gat top_k=50 fold=9 epoch=61 loss=3.3682 val_auc=0.8256
model=gat top_k=50 fold=9 epoch=62 loss=4.3620 val_auc=0.8273
model=gat top_k=50 fold=9 epoch=63 loss=2.6959 val_auc=0.8290
model=gat top_k=50 fold=9 epoch=64 loss=3.8512 val_auc=0.8290
model=gat top_k=50 fold=9 epoch=65 loss=3.2852 val_auc=0.8303
model=gat top_k=50 fold=9 epoch=66 loss=2.6269 val_auc=0.8311
model=gat top_k=50 fold=9 epoch=67 loss=2.3526 val_auc=0.8324
model=gat top_k=50 fold=9 epoch=68 loss=2.9322 val_auc=0.8329
model=gat top_k=50 fold=9 epoch=69 loss=3.2348 val_auc=0.8328
model=gat top_k=50 fold=9 epoch=70 loss=2.5529 val_auc=0.8328
model=gat top_k=50 fold=9 epoch=71 loss=3.1330 val_auc=0.8325
model=gat top_k=50 fold=9 epoch=72 loss=3.1347 val_auc=0.8316
model=gat top_k=50 fold=9 epoch=73 loss=2.9919 val_auc=0.8309
model=gat top_k=50 fold=9 epoch=74 loss=2.4319 val_auc=0.8309
model=gat top_k=50 fold=9 epoch=75 loss=2.5106 val_auc=0.8313
model=gat top_k=50 fold=9 epoch=76 loss=2.9146 val_auc=0.8319
model=gat top_k=50 fold=9 epoch=77 loss=2.2483 val_auc=0.8327
model=gat top_k=50 fold=9 epoch=78 loss=2.3953 val_auc=0.8333
model=gat top_k=50 fold=9 epoch=79 loss=2.0523 val_auc=0.8343
model=gat top_k=50 fold=9 epoch=80 loss=2.0354 val_auc=0.8350
model=gat top_k=50 fold=9 epoch=81 loss=2.8812 val_auc=0.8354
model=gat top_k=50 fold=9 epoch=82 loss=2.1477 val_auc=0.8357
model=gat top_k=50 fold=9 epoch=83 loss=1.7774 val_auc=0.8366
model=gat top_k=50 fold=9 epoch=84 loss=1.9322 val_auc=0.8370
model=gat top_k=50 fold=9 epoch=85 loss=1.8857 val_auc=0.8361
model=gat top_k=50 fold=9 epoch=86 loss=2.1004 val_auc=0.8356
model=gat top_k=50 fold=9 epoch=87 loss=1.8053 val_auc=0.8352
model=gat top_k=50 fold=9 epoch=88 loss=1.7458 val_auc=0.8352
model=gat top_k=50 fold=9 epoch=89 loss=1.8280 val_auc=0.8355
model=gat top_k=50 fold=9 epoch=90 loss=1.8366 val_auc=0.8365
model=gat top_k=50 fold=9 epoch=91 loss=1.6056 val_auc=0.8376
model=gat top_k=50 fold=9 epoch=92 loss=1.6814 val_auc=0.8383
model=gat top_k=50 fold=9 epoch=93 loss=1.6875 val_auc=0.8387
model=gat top_k=50 fold=9 epoch=94 loss=1.8562 val_auc=0.8383
model=gat top_k=50 fold=9 epoch=95 loss=1.6782 val_auc=0.8382
model=gat top_k=50 fold=9 epoch=96 loss=1.6242 val_auc=0.8381
model=gat top_k=50 fold=9 epoch=97 loss=1.7672 val_auc=0.8375
model=gat top_k=50 fold=9 epoch=98 loss=1.8541 val_auc=0.8368
model=gat top_k=50 fold=9 epoch=99 loss=1.5802 val_auc=0.8361
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 781970 edges

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/35 [00:00<?, ?it/s]

######## Model=gat top_k=100 ########

===== Model=gat top_k=100 fold=0 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782165 edges

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=100 fold=0 epoch=0 loss=17.9033 val_auc=0.6188
model=gat top_k=100 fold=0 epoch=1 loss=57.2418 val_auc=0.6312
model=gat top_k=100 fold=0 epoch=2 loss=15.9550 val_auc=0.7393
model=gat top_k=100 fold=0 epoch=3 loss=13.2932 val_auc=0.7374
model=gat top_k=100 fold=0 epoch=4 loss=8.4834 val_auc=0.7547
model=gat top_k=100 fold=0 epoch=5 loss=9.0678 val_auc=0.7642
model=gat top_k=100 fold=0 epoch=6 loss=12.8186 val_auc=0.7661
model=gat top_k=100 fold=0 epoch=7 loss=11.6858 val_auc=0.7595
model=gat top_k=100 fold=0 epoch=8 loss=6.7448 val_auc=0.6367
model=gat top_k=100 fold=0 epoch=9 loss=15.1717 val_auc=0.6165
model=gat top_k=100 fold=0 epoch=10 loss=14.5050 val_auc=0.7768
model=gat top_k=100 fold=0 epoch=11 loss=9.7110 val_auc=0.7817
model=gat top_k=100 fold=0 epoch=12 loss=11.7091 val_auc=0.7804
model=gat top_k=100 fold=0 epoch=13 loss=14.2657 val_auc=0.7778
model=gat top_k=100 fold=0 epoch=14 loss=14.1281 val_auc=0.7737
model=gat top_k=100 fold=0 epoch=15 loss=8.4724 val_auc=0.7632
model=gat top_k=100 fold=0 epoch=16 loss=8.3227 val_auc=0.7194
model=gat top_k=100 fold=0 epoch=17 loss=11.6142 val_auc=0.6330
model=gat top_k=100 fold=0 epoch=18 loss=20.1556 val_auc=0.6863
model=gat top_k=100 fold=0 epoch=19 loss=14.9392 val_auc=0.7590
model=gat top_k=100 fold=0 epoch=20 loss=8.8396 val_auc=0.7666
model=gat top_k=100 fold=0 epoch=21 loss=6.6172 val_auc=0.7656
model=gat top_k=100 fold=0 epoch=22 loss=9.4799 val_auc=0.7628
model=gat top_k=100 fold=0 epoch=23 loss=10.0563 val_auc=0.7598
gat top_k=100 fold=0: early stopping at epoch 23
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782165 edges

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=100 fold=1 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782386 edges
model=gat top_k=100 fold=1 epoch=0 loss=12.2891 val_auc=0.5007
model=gat top_k=100 fold=1 epoch=1 loss=96.7824 val_auc=0.6023

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=100 fold=1 epoch=2 loss=14.9482 val_auc=0.6993

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=100 fold=1 epoch=3 loss=53.4879 val_auc=0.7446
model=gat top_k=100 fold=1 epoch=4 loss=48.5243 val_auc=0.7454
model=gat top_k=100 fold=1 epoch=5 loss=21.0850 val_auc=0.5201
model=gat top_k=100 fold=1 epoch=6 loss=20.0343 val_auc=0.5056
model=gat top_k=100 fold=1 epoch=7 loss=36.0771 val_auc=0.5292
model=gat top_k=100 fold=1 epoch=8 loss=34.9951 val_auc=0.7227
model=gat top_k=100 fold=1 epoch=9 loss=13.4239 val_auc=0.7590
model=gat top_k=100 fold=1 epoch=10 loss=13.4981 val_auc=0.7631
model=gat top_k=100 fold=1 epoch=11 loss=20.8853 val_auc=0.7653
model=gat top_k=100 fold=1 epoch=12 loss=16.0862 val_auc=0.7655
model=gat top_k=100 fold=1 epoch=13 loss=9.6697 val_auc=0.7603
model=gat top_k=100 fold=1 epoch=14 loss=10.4355 val_auc=0.6303
model=gat top_k=100 fold=1 epoch=15 loss=17.3538 val_auc=0.5499
model=gat top_k=100 fold=1 epoch=16 loss=21.1869 val_auc=0.5543
model=gat top_k=100 fold=1 epoch=17 loss=20.7059 val_auc=0.7491
model=gat top_k=100 fold=1 epoch=18 loss=15.8184 val_auc=0.7743
model=gat top_k=100 fold=1 epoch=19 loss=7.4019 val_auc=0.7669
model=gat top_k=100 fold=1 epoch=20 loss=9.7310 val_auc=0.7614
model=gat top_k=100 fold=1 epoch=21 loss=12.8012 val_auc=0.7596
model=gat top_k=100 fold=1 epoch=22 loss=10.3399 val_auc=0.7560
model=gat top_k=100 fold=1 epoch=23 loss=7.7095 val_auc=0.7550
model=gat top_k=100 fold=1 epoch=24 loss=7.1074 val_auc=0.7599
model=gat top_k=100 fold=1 epoch=25 loss=7.9547 val_auc=0.7710
model=gat top_k=100 fold=1 epoch=26 loss=10.1181 val_auc=0.7800
model=gat top_k=100 fold=1 epoch=27 loss=8.2018 val_auc=0.7819
model=gat top_k=100 fold=1 epoch=28 loss=6.7537 val_auc=0.7841
model=gat top_k=100 fold=1 epoch=29 loss=6.9091 val_auc=0.7859
model=gat top_k=100 fold=1 epoch=30 loss=7.6081 val_auc=0.7874
model=gat top_k=100 fold=1 epoch=31 loss=6.2198 val_auc=0.7887
model=gat top_k=100 fold=1 epoch=32 loss=5.9739 val_auc=0.7903
model=gat top_k=100 fold=1 epoch=33 loss=6.2224 val_auc=0.7921
model=gat top_k=100 fold=1 epoch=34 loss=7.0756 val_auc=0.7956
model=gat top_k=100 fold=1 epoch=35 loss=6.4378 val_auc=0.7984
model=gat top_k=100 fold=1 epoch=36 loss=6.4250 val_auc=0.8005
model=gat top_k=100 fold=1 epoch=37 loss=6.8937 val_auc=0.8015
model=gat top_k=100 fold=1 epoch=38 loss=7.9616 val_auc=0.8019
model=gat top_k=100 fold=1 epoch=39 loss=6.1710 val_auc=0.8024
model=gat top_k=100 fold=1 epoch=40 loss=5.5564 val_auc=0.8027
model=gat top_k=100 fold=1 epoch=41 loss=5.7796 val_auc=0.8033
model=gat top_k=100 fold=1 epoch=42 loss=5.0923 val_auc=0.8038
model=gat top_k=100 fold=1 epoch=43 loss=5.8930 val_auc=0.8047
model=gat top_k=100 fold=1 epoch=44 loss=4.3696 val_auc=0.8050
model=gat top_k=100 fold=1 epoch=45 loss=5.1240 val_auc=0.8012
model=gat top_k=100 fold=1 epoch=46 loss=5.1143 val_auc=0.8020
model=gat top_k=100 fold=1 epoch=47 loss=4.5376 val_auc=0.8025
model=gat top_k=100 fold=1 epoch=48 loss=4.4747 val_auc=0.8008
model=gat top_k=100 fold=1 epoch=49 loss=5.8267 val_auc=0.7979
model=gat top_k=100 fold=1 epoch=50 loss=5.6064 val_auc=0.7930
model=gat top_k=100 fold=1 epoch=51 loss=4.5533 val_auc=0.7843
model=gat top_k=100 fold=1 epoch=52 loss=4.0652 val_auc=0.7869
model=gat top_k=100 fold=1 epoch=53 loss=5.9427 val_auc=0.7858
model=gat top_k=100 fold=1 epoch=54 loss=5.0905 val_auc=0.7774
model=gat top_k=100 fold=1 epoch=55 loss=4.9966 val_auc=0.7774
model=gat top_k=100 fold=1 epoch=56 loss=4.5264 val_auc=0.7782
gat top_k=100 fold=1: early stopping at epoch 56
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782386 edges

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=100 fold=2 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782205 edges

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=100 fold=2 epoch=0 loss=15.7791 val_auc=0.5320
model=gat top_k=100 fold=2 epoch=1 loss=64.8061 val_auc=0.5346
model=gat top_k=100 fold=2 epoch=2 loss=23.2983 val_auc=0.7010
model=gat top_k=100 fold=2 epoch=3 loss=11.1088 val_auc=0.6877
model=gat top_k=100 fold=2 epoch=4 loss=14.0997 val_auc=0.7497
model=gat top_k=100 fold=2 epoch=5 loss=9.0878 val_auc=0.7624
model=gat top_k=100 fold=2 epoch=6 loss=8.4626 val_auc=0.7523
model=gat top_k=100 fold=2 epoch=7 loss=7.8558 val_auc=0.7442
model=gat top_k=100 fold=2 epoch=8 loss=7.8200 val_auc=0.7473
model=gat top_k=100 fold=2 epoch=9 loss=7.3473 val_auc=0.7491
model=gat top_k=100 fold=2 epoch=10 loss=11.3930 val_auc=0.7538
model=gat top_k=100 fold=2 epoch=11 loss=10.3507 val_auc=0.7563
model=gat top_k=100 fold=2 epoch=12 loss=8.8595 val_auc=0.7639
model=gat top_k=100 fold=2 epoch=13 loss=11.0780 val_auc=0.7821
model=gat top_k=100 fold=2 epoch=14 loss=7.4052 val_auc=0.7914
model=gat top_k=100 fold=2 epoch=15 loss=9.7501 val_auc=0.7940
model=gat top_k=100 fold=2 epoch=16 loss=15.3906 val_auc=0.7943
model=gat top_k=100 fold=2 epoch=17 loss=12.9241 val_auc=0.7953
model=gat top_k=100 fold=2 epoch=18 loss=5.9005 val_auc=0.7932
model=gat top_k=100 fold=2 epoch=19 loss=7.4568 val_auc=0.7708
model=gat top_k=100 fold=2 epoch=20 loss=11.2247 val_auc=0.7829
model=gat top_k=100 fold=2 epoch=21 loss=9.5792 val_auc=0.7961
model=gat top_k=100 fold=2 epoch=22 loss=6.9002 val_auc=0.7953
model=gat top_k=100 fold=2 epoch=23 loss=6.3950 val_auc=0.7949
model=gat top_k=100 fold=2 epoch=24 loss=11.2487 val_auc=0.7949
model=gat top_k=100 fold=2 epoch=25 loss=11.2050 val_auc=0.7957
model=gat top_k=100 fold=2 epoch=26 loss=7.9927 val_auc=0.7969
model=gat top_k=100 fold=2 epoch=27 loss=5.5679 val_auc=0.7984
model=gat top_k=100 fold=2 epoch=28 loss=6.6634 val_auc=0.7931
model=gat top_k=100 fold=2 epoch=29 loss=9.1099 val_auc=0.7935
model=gat top_k=100 fold=2 epoch=30 loss=8.7411 val_auc=0.7964
model=gat top_k=100 fold=2 epoch=31 loss=5.9591 val_auc=0.7953
model=gat top_k=100 fold=2 epoch=32 loss=4.8263 val_auc=0.7944
model=gat top_k=100 fold=2 epoch=33 loss=8.3954 val_auc=0.7944
model=gat top_k=100 fold=2 epoch=34 loss=9.5246 val_auc=0.7953
model=gat top_k=100 fold=2 epoch=35 loss=12.2845 val_auc=0.7971
model=gat top_k=100 fold=2 epoch=36 loss=6.7709 val_auc=0.7988
model=gat top_k=100 fold=2 epoch=37 loss=5.6503 val_auc=0.7991
model=gat top_k=100 fold=2 epoch=38 loss=6.8536 val_auc=0.7978
model=gat top_k=100 fold=2 epoch=39 loss=7.2356 val_auc=0.7956
model=gat top_k=100 fold=2 epoch=40 loss=9.2900 val_auc=0.7974
model=gat top_k=100 fold=2 epoch=41 loss=9.4214 val_auc=0.7962
model=gat top_k=100 fold=2 epoch=42 loss=5.2048 val_auc=0.7951
model=gat top_k=100 fold=2 epoch=43 loss=5.7655 val_auc=0.7962
model=gat top_k=100 fold=2 epoch=44 loss=6.8755 val_auc=0.7987
model=gat top_k=100 fold=2 epoch=45 loss=5.8239 val_auc=0.8021
model=gat top_k=100 fold=2 epoch=46 loss=4.3299 val_auc=0.8052
model=gat top_k=100 fold=2 epoch=47 loss=4.3717 val_auc=0.8068
model=gat top_k=100 fold=2 epoch=48 loss=7.8231 val_auc=0.8077
model=gat top_k=100 fold=2 epoch=49 loss=5.5001 val_auc=0.8077
model=gat top_k=100 fold=2 epoch=50 loss=4.7436 val_auc=0.8061
model=gat top_k=100 fold=2 epoch=51 loss=4.4213 val_auc=0.8041
model=gat top_k=100 fold=2 epoch=52 loss=4.7656 val_auc=0.8037
model=gat top_k=100 fold=2 epoch=53 loss=5.3613 val_auc=0.8055
model=gat top_k=100 fold=2 epoch=54 loss=3.7560 val_auc=0.8062
model=gat top_k=100 fold=2 epoch=55 loss=3.6000 val_auc=0.8089
model=gat top_k=100 fold=2 epoch=56 loss=3.5684 val_auc=0.8101
model=gat top_k=100 fold=2 epoch=57 loss=3.8320 val_auc=0.8098
model=gat top_k=100 fold=2 epoch=58 loss=4.2773 val_auc=0.8097
model=gat top_k=100 fold=2 epoch=59 loss=5.3094 val_auc=0.8105
model=gat top_k=100 fold=2 epoch=60 loss=4.1701 val_auc=0.8114
model=gat top_k=100 fold=2 epoch=61 loss=3.0999 val_auc=0.8099
model=gat top_k=100 fold=2 epoch=62 loss=4.1403 val_auc=0.8055
model=gat top_k=100 fold=2 epoch=63 loss=3.1602 val_auc=0.7981
model=gat top_k=100 fold=2 epoch=64 loss=3.1522 val_auc=0.7906
model=gat top_k=100 fold=2 epoch=65 loss=3.6113 val_auc=0.7880
model=gat top_k=100 fold=2 epoch=66 loss=2.7232 val_auc=0.7900
model=gat top_k=100 fold=2 epoch=67 loss=3.0868 val_auc=0.7894
model=gat top_k=100 fold=2 epoch=68 loss=3.3942 val_auc=0.7873
model=gat top_k=100 fold=2 epoch=69 loss=3.4534 val_auc=0.7805
model=gat top_k=100 fold=2 epoch=70 loss=3.0079 val_auc=0.7757
model=gat top_k=100 fold=2 epoch=71 loss=2.8544 val_auc=0.7771
model=gat top_k=100 fold=2 epoch=72 loss=3.3779 val_auc=0.7740
gat top_k=100 fold=2: early stopping at epoch 72
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782205 edges

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=100 fold=3 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 781933 edges
model=gat top_k=100 fold=3 epoch=0 loss=14.0063 val_auc=0.5001
model=gat top_k=100 fold=3 epoch=1 loss=106.1785 val_auc=0.5240
model=gat top_k=100 fold=3 epoch=2 loss=34.7585 val_auc=0.7077
model=gat top_k=100 fold=3 epoch=3 loss=38.5768 val_auc=0.6961
model=gat top_k=100 fold=3 epoch=4 loss=32.0117 val_auc=0.6843
model=gat top_k=100 fold=3 epoch=5 loss=14.6590 val_auc=0.5083
model=gat top_k=100 fold=3 epoch=6 loss=22.6293 val_auc=0.5089
model=gat top_k=100 fold=3 epoch=7 loss=26.6347 val_auc=0.5264
model=gat top_k=100 fold=3 epoch=8 loss=21.6579 val_auc=0.7232
model=gat top_k=100 fold=3 epoch=9 loss=9.1463 val_auc=0.7298
model=gat top_k=100 fold=3 epoch=10 loss=11.8283 val_auc=0.7354
model=gat top_k=100 fold=3 epoch=11 loss=15.0411 val_auc=0.7404
model=gat top_k=100 fold=3 epoch=12 loss=13.0428 val_auc=0.7406
model=gat top_k=100 fold=3 epoch=13 loss=9.6514 val_auc=0.7415
model=gat top_k=100 fold=3 epoch=14 loss=9.3257 val_auc=0.7434
model=gat top_k=100 fold=3 epoch=15 loss=10.3965 val_auc=0.7479
model=gat top_k=100 fold=3 epoch=16 loss=10.3997 val_auc=0.7537
model=gat top_k=100 fold=3 epoch=17 loss=9.4150 val_auc=0.7595
model=gat top_k=100 fold=3 epoch=18 loss=8.1508 val_auc=0.7660
model=gat top_k=100 fold=3 epoch=19 loss=10.8310 val_auc=0.7708
model=gat top_k=100 fold=3 epoch=20 loss=13.8640 val_auc=0.7736
model=gat top_k=100 fold=3 epoch=21 loss=9.8197 val_auc=0.7752
model=gat top_k=100 fold=3 epoch=22 loss=6.8234 val_auc=0.7755
model=gat top_k=100 fold=3 epoch=23 loss=9.4056 val_auc=0.7735
model=gat top_k=100 fold=3 epoch=24 loss=8.3251 val_auc=0.7748
model=gat top_k=100 fold=3 epoch=25 loss=9.7867 val_auc=0.7794
model=gat top_k=100 fold=3 epoch=26 loss=6.2078 val_auc=0.7829
model=gat top_k=100 fold=3 epoch=27 loss=6.4570 val_auc=0.7868
model=gat top_k=100 fold=3 epoch=28 loss=6.5281 val_auc=0.7894
model=gat top_k=100 fold=3 epoch=29 loss=7.8722 val_auc=0.7917
model=gat top_k=100 fold=3 epoch=30 loss=5.5779 val_auc=0.7933
model=gat top_k=100 fold=3 epoch=31 loss=7.2456 val_auc=0.7927
model=gat top_k=100 fold=3 epoch=32 loss=7.4658 val_auc=0.7935
model=gat top_k=100 fold=3 epoch=33 loss=7.7197 val_auc=0.7953
model=gat top_k=100 fold=3 epoch=34 loss=5.1356 val_auc=0.7964
model=gat top_k=100 fold=3 epoch=35 loss=5.2184 val_auc=0.7974
model=gat top_k=100 fold=3 epoch=36 loss=5.2172 val_auc=0.7982
model=gat top_k=100 fold=3 epoch=37 loss=5.3941 val_auc=0.7988
model=gat top_k=100 fold=3 epoch=38 loss=4.5741 val_auc=0.7996
model=gat top_k=100 fold=3 epoch=39 loss=5.8503 val_auc=0.7996
model=gat top_k=100 fold=3 epoch=40 loss=5.4719 val_auc=0.8009
model=gat top_k=100 fold=3 epoch=41 loss=5.6636 val_auc=0.8018
model=gat top_k=100 fold=3 epoch=42 loss=4.9066 val_auc=0.8026
model=gat top_k=100 fold=3 epoch=43 loss=6.4652 val_auc=0.8034
model=gat top_k=100 fold=3 epoch=44 loss=7.2319 val_auc=0.8037
model=gat top_k=100 fold=3 epoch=45 loss=5.7991 val_auc=0.8038
model=gat top_k=100 fold=3 epoch=46 loss=4.5665 val_auc=0.8044
model=gat top_k=100 fold=3 epoch=47 loss=6.2792 val_auc=0.8053
model=gat top_k=100 fold=3 epoch=48 loss=4.8954 val_auc=0.8068
model=gat top_k=100 fold=3 epoch=49 loss=5.5455 val_auc=0.8086
model=gat top_k=100 fold=3 epoch=50 loss=5.2991 val_auc=0.8095
model=gat top_k=100 fold=3 epoch=51 loss=4.1228 val_auc=0.8095
model=gat top_k=100 fold=3 epoch=52 loss=5.5277 val_auc=0.8091
model=gat top_k=100 fold=3 epoch=53 loss=5.9325 val_auc=0.8091
model=gat top_k=100 fold=3 epoch=54 loss=4.6179 val_auc=0.8082
model=gat top_k=100 fold=3 epoch=55 loss=4.3091 val_auc=0.8059
model=gat top_k=100 fold=3 epoch=56 loss=5.3836 val_auc=0.8014
model=gat top_k=100 fold=3 epoch=57 loss=4.6254 val_auc=0.8003
model=gat top_k=100 fold=3 epoch=58 loss=4.7421 val_auc=0.8015
model=gat top_k=100 fold=3 epoch=59 loss=4.5542 val_auc=0.8024
model=gat top_k=100 fold=3 epoch=60 loss=3.7498 val_auc=0.8047
model=gat top_k=100 fold=3 epoch=61 loss=4.1640 val_auc=0.8058
model=gat top_k=100 fold=3 epoch=62 loss=4.5620 val_auc=0.8060
gat top_k=100 fold=3: early stopping at epoch 62
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 781933 edges

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=100 fold=4 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782579 edges

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=100 fold=4 epoch=0 loss=13.4138 val_auc=0.6992
model=gat top_k=100 fold=4 epoch=1 loss=39.9717 val_auc=0.5190
model=gat top_k=100 fold=4 epoch=2 loss=31.1667 val_auc=0.6729
model=gat top_k=100 fold=4 epoch=3 loss=18.1661 val_auc=0.7122
model=gat top_k=100 fold=4 epoch=4 loss=15.5114 val_auc=0.7120
model=gat top_k=100 fold=4 epoch=5 loss=16.0583 val_auc=0.6992
model=gat top_k=100 fold=4 epoch=6 loss=10.6921 val_auc=0.6971
model=gat top_k=100 fold=4 epoch=7 loss=9.7228 val_auc=0.7074
model=gat top_k=100 fold=4 epoch=8 loss=9.1626 val_auc=0.7198
model=gat top_k=100 fold=4 epoch=9 loss=8.0643 val_auc=0.7210
model=gat top_k=100 fold=4 epoch=10 loss=8.1493 val_auc=0.7325
model=gat top_k=100 fold=4 epoch=11 loss=7.3878 val_auc=0.7370
model=gat top_k=100 fold=4 epoch=12 loss=6.7549 val_auc=0.7369
model=gat top_k=100 fold=4 epoch=13 loss=8.8991 val_auc=0.7425
model=gat top_k=100 fold=4 epoch=14 loss=8.9105 val_auc=0.7567
model=gat top_k=100 fold=4 epoch=15 loss=5.8215 val_auc=0.7673
model=gat top_k=100 fold=4 epoch=16 loss=9.7948 val_auc=0.7722
model=gat top_k=100 fold=4 epoch=17 loss=8.5294 val_auc=0.7785
model=gat top_k=100 fold=4 epoch=18 loss=6.7425 val_auc=0.7848
model=gat top_k=100 fold=4 epoch=19 loss=6.8738 val_auc=0.7688
model=gat top_k=100 fold=4 epoch=20 loss=14.2039 val_auc=0.7767
model=gat top_k=100 fold=4 epoch=21 loss=12.6194 val_auc=0.7861
model=gat top_k=100 fold=4 epoch=22 loss=7.5467 val_auc=0.7882
model=gat top_k=100 fold=4 epoch=23 loss=5.9092 val_auc=0.7884
model=gat top_k=100 fold=4 epoch=24 loss=7.7385 val_auc=0.7884
model=gat top_k=100 fold=4 epoch=25 loss=10.2585 val_auc=0.7892
model=gat top_k=100 fold=4 epoch=26 loss=8.0313 val_auc=0.7912
model=gat top_k=100 fold=4 epoch=27 loss=6.5691 val_auc=0.7932
model=gat top_k=100 fold=4 epoch=28 loss=6.3450 val_auc=0.7961
model=gat top_k=100 fold=4 epoch=29 loss=5.1466 val_auc=0.8003
model=gat top_k=100 fold=4 epoch=30 loss=7.9256 val_auc=0.8005
model=gat top_k=100 fold=4 epoch=31 loss=6.1756 val_auc=0.7994
model=gat top_k=100 fold=4 epoch=32 loss=5.5627 val_auc=0.7996
model=gat top_k=100 fold=4 epoch=33 loss=5.6199 val_auc=0.8008
model=gat top_k=100 fold=4 epoch=34 loss=5.1979 val_auc=0.8021
model=gat top_k=100 fold=4 epoch=35 loss=5.0656 val_auc=0.8032
model=gat top_k=100 fold=4 epoch=36 loss=5.5599 val_auc=0.8038
model=gat top_k=100 fold=4 epoch=37 loss=4.7854 val_auc=0.8041
model=gat top_k=100 fold=4 epoch=38 loss=4.9676 val_auc=0.8043
model=gat top_k=100 fold=4 epoch=39 loss=3.8869 val_auc=0.8047
model=gat top_k=100 fold=4 epoch=40 loss=3.9266 val_auc=0.8050
model=gat top_k=100 fold=4 epoch=41 loss=4.1246 val_auc=0.8056
model=gat top_k=100 fold=4 epoch=42 loss=3.7962 val_auc=0.8065
model=gat top_k=100 fold=4 epoch=43 loss=4.2199 val_auc=0.8071
model=gat top_k=100 fold=4 epoch=44 loss=3.9073 val_auc=0.8089
model=gat top_k=100 fold=4 epoch=45 loss=4.8029 val_auc=0.8102
model=gat top_k=100 fold=4 epoch=46 loss=5.1703 val_auc=0.8111
model=gat top_k=100 fold=4 epoch=47 loss=4.1903 val_auc=0.8095
model=gat top_k=100 fold=4 epoch=48 loss=4.0343 val_auc=0.8105
model=gat top_k=100 fold=4 epoch=49 loss=3.8354 val_auc=0.8142
model=gat top_k=100 fold=4 epoch=50 loss=3.9647 val_auc=0.8169
model=gat top_k=100 fold=4 epoch=51 loss=3.3516 val_auc=0.8180
model=gat top_k=100 fold=4 epoch=52 loss=3.4583 val_auc=0.8191
model=gat top_k=100 fold=4 epoch=53 loss=3.0797 val_auc=0.8196
model=gat top_k=100 fold=4 epoch=54 loss=4.8682 val_auc=0.8198
model=gat top_k=100 fold=4 epoch=55 loss=3.7359 val_auc=0.8205
model=gat top_k=100 fold=4 epoch=56 loss=4.0495 val_auc=0.8203
model=gat top_k=100 fold=4 epoch=57 loss=4.1195 val_auc=0.8194
model=gat top_k=100 fold=4 epoch=58 loss=3.4556 val_auc=0.8179
model=gat top_k=100 fold=4 epoch=59 loss=4.1276 val_auc=0.8196
model=gat top_k=100 fold=4 epoch=60 loss=3.8341 val_auc=0.8228
model=gat top_k=100 fold=4 epoch=61 loss=3.3447 val_auc=0.8238
model=gat top_k=100 fold=4 epoch=62 loss=3.6975 val_auc=0.8240
model=gat top_k=100 fold=4 epoch=63 loss=3.5183 val_auc=0.8246
model=gat top_k=100 fold=4 epoch=64 loss=3.1557 val_auc=0.8239
model=gat top_k=100 fold=4 epoch=65 loss=3.3097 val_auc=0.8233
model=gat top_k=100 fold=4 epoch=66 loss=3.0226 val_auc=0.8233
model=gat top_k=100 fold=4 epoch=67 loss=4.5713 val_auc=0.8231
model=gat top_k=100 fold=4 epoch=68 loss=3.1216 val_auc=0.8227
model=gat top_k=100 fold=4 epoch=69 loss=3.4112 val_auc=0.8220
model=gat top_k=100 fold=4 epoch=70 loss=4.5442 val_auc=0.8206
model=gat top_k=100 fold=4 epoch=71 loss=3.8056 val_auc=0.8217
model=gat top_k=100 fold=4 epoch=72 loss=3.2318 val_auc=0.8217
model=gat top_k=100 fold=4 epoch=73 loss=2.5298 val_auc=0.8222
model=gat top_k=100 fold=4 epoch=74 loss=2.6443 val_auc=0.8223
model=gat top_k=100 fold=4 epoch=75 loss=2.4387 val_auc=0.8224
gat top_k=100 fold=4: early stopping at epoch 75
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782579 edges

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=100 fold=5 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782265 edges
model=gat top_k=100 fold=5 epoch=0 loss=13.1313 val_auc=0.7479
model=gat top_k=100 fold=5 epoch=1 loss=13.4061 val_auc=0.5015
model=gat top_k=100 fold=5 epoch=2 loss=69.3957 val_auc=0.5136
model=gat top_k=100 fold=5 epoch=3 loss=39.5710 val_auc=0.7441
model=gat top_k=100 fold=5 epoch=4 loss=8.9536 val_auc=0.7452
model=gat top_k=100 fold=5 epoch=5 loss=9.0669 val_auc=0.7488
model=gat top_k=100 fold=5 epoch=6 loss=8.1838 val_auc=0.7580
model=gat top_k=100 fold=5 epoch=7 loss=12.0974 val_auc=0.7719
model=gat top_k=100 fold=5 epoch=8 loss=8.7069 val_auc=0.7817
model=gat top_k=100 fold=5 epoch=9 loss=6.5657 val_auc=0.7862
model=gat top_k=100 fold=5 epoch=10 loss=8.3270 val_auc=0.7956
model=gat top_k=100 fold=5 epoch=11 loss=9.2119 val_auc=0.7989
model=gat top_k=100 fold=5 epoch=12 loss=7.5974 val_auc=0.7953
model=gat top_k=100 fold=5 epoch=13 loss=9.4822 val_auc=0.7969
model=gat top_k=100 fold=5 epoch=14 loss=8.3982 val_auc=0.7991
model=gat top_k=100 fold=5 epoch=15 loss=6.8469 val_auc=0.7996
model=gat top_k=100 fold=5 epoch=16 loss=6.2784 val_auc=0.8010
model=gat top_k=100 fold=5 epoch=17 loss=5.9461 val_auc=0.8027
model=gat top_k=100 fold=5 epoch=18 loss=5.0673 val_auc=0.8043
model=gat top_k=100 fold=5 epoch=19 loss=5.6445 val_auc=0.8061
model=gat top_k=100 fold=5 epoch=20 loss=5.5781 val_auc=0.8081
model=gat top_k=100 fold=5 epoch=21 loss=6.5181 val_auc=0.8089
model=gat top_k=100 fold=5 epoch=22 loss=6.0390 val_auc=0.8108
model=gat top_k=100 fold=5 epoch=23 loss=5.3158 val_auc=0.8126
model=gat top_k=100 fold=5 epoch=24 loss=4.7633 val_auc=0.8141
model=gat top_k=100 fold=5 epoch=25 loss=5.4694 val_auc=0.8145
model=gat top_k=100 fold=5 epoch=26 loss=4.6279 val_auc=0.8133
model=gat top_k=100 fold=5 epoch=27 loss=5.3090 val_auc=0.8134
model=gat top_k=100 fold=5 epoch=28 loss=5.1740 val_auc=0.8139
model=gat top_k=100 fold=5 epoch=29 loss=4.2843 val_auc=0.8143
model=gat top_k=100 fold=5 epoch=30 loss=4.4837 val_auc=0.8152
model=gat top_k=100 fold=5 epoch=31 loss=6.5956 val_auc=0.8156
model=gat top_k=100 fold=5 epoch=32 loss=5.5603 val_auc=0.8161
model=gat top_k=100 fold=5 epoch=33 loss=3.8648 val_auc=0.8170
model=gat top_k=100 fold=5 epoch=34 loss=4.5903 val_auc=0.8184
model=gat top_k=100 fold=5 epoch=35 loss=5.0541 val_auc=0.8195
model=gat top_k=100 fold=5 epoch=36 loss=5.2289 val_auc=0.8201
model=gat top_k=100 fold=5 epoch=37 loss=4.2676 val_auc=0.8212
model=gat top_k=100 fold=5 epoch=38 loss=4.5345 val_auc=0.8217
model=gat top_k=100 fold=5 epoch=39 loss=3.5985 val_auc=0.8206
model=gat top_k=100 fold=5 epoch=40 loss=4.0343 val_auc=0.8188
model=gat top_k=100 fold=5 epoch=41 loss=3.7361 val_auc=0.8180
model=gat top_k=100 fold=5 epoch=42 loss=4.6799 val_auc=0.8173
model=gat top_k=100 fold=5 epoch=43 loss=3.4332 val_auc=0.8154
model=gat top_k=100 fold=5 epoch=44 loss=4.3584 val_auc=0.8138
model=gat top_k=100 fold=5 epoch=45 loss=4.7150 val_auc=0.8135
model=gat top_k=100 fold=5 epoch=46 loss=4.2764 val_auc=0.8128
model=gat top_k=100 fold=5 epoch=47 loss=4.3549 val_auc=0.8125
model=gat top_k=100 fold=5 epoch=48 loss=5.2806 val_auc=0.8131
model=gat top_k=100 fold=5 epoch=49 loss=4.6154 val_auc=0.8151
model=gat top_k=100 fold=5 epoch=50 loss=3.5755 val_auc=0.8175
gat top_k=100 fold=5: early stopping at epoch 50
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782265 edges

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=100 fold=6 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 781867 edges

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=100 fold=6 epoch=0 loss=16.5342 val_auc=0.6599
model=gat top_k=100 fold=6 epoch=1 loss=59.0160 val_auc=0.5018
model=gat top_k=100 fold=6 epoch=2 loss=34.6785 val_auc=0.7503
model=gat top_k=100 fold=6 epoch=3 loss=10.5585 val_auc=0.7515
model=gat top_k=100 fold=6 epoch=4 loss=15.8509 val_auc=0.7381
model=gat top_k=100 fold=6 epoch=5 loss=8.9059 val_auc=0.4833
model=gat top_k=100 fold=6 epoch=6 loss=21.8732 val_auc=0.6096
model=gat top_k=100 fold=6 epoch=7 loss=17.6081 val_auc=0.7278
model=gat top_k=100 fold=6 epoch=8 loss=7.7363 val_auc=0.7311
model=gat top_k=100 fold=6 epoch=9 loss=12.2268 val_auc=0.7348
model=gat top_k=100 fold=6 epoch=10 loss=15.9940 val_auc=0.7368
model=gat top_k=100 fold=6 epoch=11 loss=9.1827 val_auc=0.7169
model=gat top_k=100 fold=6 epoch=12 loss=9.6924 val_auc=0.6645
model=gat top_k=100 fold=6 epoch=13 loss=14.9027 val_auc=0.7454
model=gat top_k=100 fold=6 epoch=14 loss=12.2264 val_auc=0.7585
model=gat top_k=100 fold=6 epoch=15 loss=7.4164 val_auc=0.7650
model=gat top_k=100 fold=6 epoch=16 loss=10.0647 val_auc=0.7703
model=gat top_k=100 fold=6 epoch=17 loss=10.4475 val_auc=0.7795
model=gat top_k=100 fold=6 epoch=18 loss=6.1991 val_auc=0.7858
model=gat top_k=100 fold=6 epoch=19 loss=8.4998 val_auc=0.7804
model=gat top_k=100 fold=6 epoch=20 loss=12.8295 val_auc=0.7901
model=gat top_k=100 fold=6 epoch=21 loss=9.4719 val_auc=0.7985
model=gat top_k=100 fold=6 epoch=22 loss=6.7720 val_auc=0.8017
model=gat top_k=100 fold=6 epoch=23 loss=5.6525 val_auc=0.8041
model=gat top_k=100 fold=6 epoch=24 loss=7.4054 val_auc=0.8055
model=gat top_k=100 fold=6 epoch=25 loss=7.2288 val_auc=0.8062
model=gat top_k=100 fold=6 epoch=26 loss=5.3549 val_auc=0.8066
model=gat top_k=100 fold=6 epoch=27 loss=5.5710 val_auc=0.8073
model=gat top_k=100 fold=6 epoch=28 loss=6.0520 val_auc=0.8077
model=gat top_k=100 fold=6 epoch=29 loss=5.0356 val_auc=0.8081
model=gat top_k=100 fold=6 epoch=30 loss=5.0188 val_auc=0.8083
model=gat top_k=100 fold=6 epoch=31 loss=4.9604 val_auc=0.8081
model=gat top_k=100 fold=6 epoch=32 loss=4.9210 val_auc=0.8080
model=gat top_k=100 fold=6 epoch=33 loss=5.5317 val_auc=0.8080
model=gat top_k=100 fold=6 epoch=34 loss=5.1185 val_auc=0.8087
model=gat top_k=100 fold=6 epoch=35 loss=4.6885 val_auc=0.8089
model=gat top_k=100 fold=6 epoch=36 loss=5.7102 val_auc=0.8087
model=gat top_k=100 fold=6 epoch=37 loss=4.8405 val_auc=0.8086
model=gat top_k=100 fold=6 epoch=38 loss=4.8149 val_auc=0.8091
model=gat top_k=100 fold=6 epoch=39 loss=4.4124 val_auc=0.8106
model=gat top_k=100 fold=6 epoch=40 loss=4.1884 val_auc=0.8126
model=gat top_k=100 fold=6 epoch=41 loss=4.7560 val_auc=0.8140
model=gat top_k=100 fold=6 epoch=42 loss=4.1265 val_auc=0.8157
model=gat top_k=100 fold=6 epoch=43 loss=3.6541 val_auc=0.8175
model=gat top_k=100 fold=6 epoch=44 loss=4.9554 val_auc=0.8191
model=gat top_k=100 fold=6 epoch=45 loss=4.6318 val_auc=0.8202
model=gat top_k=100 fold=6 epoch=46 loss=4.0963 val_auc=0.8200
model=gat top_k=100 fold=6 epoch=47 loss=4.7913 val_auc=0.8211
model=gat top_k=100 fold=6 epoch=48 loss=5.3856 val_auc=0.8224
model=gat top_k=100 fold=6 epoch=49 loss=4.5941 val_auc=0.8238
model=gat top_k=100 fold=6 epoch=50 loss=5.2295 val_auc=0.8236
model=gat top_k=100 fold=6 epoch=51 loss=6.2423 val_auc=0.8237
model=gat top_k=100 fold=6 epoch=52 loss=5.8133 val_auc=0.8231
model=gat top_k=100 fold=6 epoch=53 loss=3.8742 val_auc=0.8236
model=gat top_k=100 fold=6 epoch=54 loss=7.0930 val_auc=0.8184
model=gat top_k=100 fold=6 epoch=55 loss=8.4522 val_auc=0.8211
model=gat top_k=100 fold=6 epoch=56 loss=5.5946 val_auc=0.8199
model=gat top_k=100 fold=6 epoch=57 loss=4.7351 val_auc=0.8188
model=gat top_k=100 fold=6 epoch=58 loss=4.3754 val_auc=0.8168
model=gat top_k=100 fold=6 epoch=59 loss=6.2137 val_auc=0.8136
model=gat top_k=100 fold=6 epoch=60 loss=5.4031 val_auc=0.8115
model=gat top_k=100 fold=6 epoch=61 loss=4.8573 val_auc=0.8108
gat top_k=100 fold=6: early stopping at epoch 61
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 781867 edges

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=100 fold=7 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782278 edges
model=gat top_k=100 fold=7 epoch=0 loss=24.3557 val_auc=0.5003
model=gat top_k=100 fold=7 epoch=1 loss=93.2886 val_auc=0.5147

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=100 fold=7 epoch=2 loss=13.1848 val_auc=0.6586
model=gat top_k=100 fold=7 epoch=3 loss=47.8685 val_auc=0.6848
model=gat top_k=100 fold=7 epoch=4 loss=40.4359 val_auc=0.6965
model=gat top_k=100 fold=7 epoch=5 loss=12.1900 val_auc=0.5166
model=gat top_k=100 fold=7 epoch=6 loss=32.1128 val_auc=0.5215
model=gat top_k=100 fold=7 epoch=7 loss=41.8599 val_auc=0.5397
model=gat top_k=100 fold=7 epoch=8 loss=23.5549 val_auc=0.7380
model=gat top_k=100 fold=7 epoch=9 loss=9.4096 val_auc=0.7522
model=gat top_k=100 fold=7 epoch=10 loss=14.4341 val_auc=0.7635
model=gat top_k=100 fold=7 epoch=11 loss=18.4856 val_auc=0.7699
model=gat top_k=100 fold=7 epoch=12 loss=16.7418 val_auc=0.7749
model=gat top_k=100 fold=7 epoch=13 loss=11.5614 val_auc=0.7776
model=gat top_k=100 fold=7 epoch=14 loss=14.1856 val_auc=0.7755
model=gat top_k=100 fold=7 epoch=15 loss=13.8577 val_auc=0.7604
model=gat top_k=100 fold=7 epoch=16 loss=13.0291 val_auc=0.7784
model=gat top_k=100 fold=7 epoch=17 loss=13.0492 val_auc=0.7815
model=gat top_k=100 fold=7 epoch=18 loss=9.4488 val_auc=0.7845
model=gat top_k=100 fold=7 epoch=19 loss=7.7946 val_auc=0.7843
model=gat top_k=100 fold=7 epoch=20 loss=9.4323 val_auc=0.7848
model=gat top_k=100 fold=7 epoch=21 loss=12.4754 val_auc=0.7860
model=gat top_k=100 fold=7 epoch=22 loss=13.7655 val_auc=0.7868
model=gat top_k=100 fold=7 epoch=23 loss=10.2732 val_auc=0.7872
model=gat top_k=100 fold=7 epoch=24 loss=7.7870 val_auc=0.7847
model=gat top_k=100 fold=7 epoch=25 loss=10.0519 val_auc=0.7846
model=gat top_k=100 fold=7 epoch=26 loss=9.8778 val_auc=0.7847
model=gat top_k=100 fold=7 epoch=27 loss=11.6376 val_auc=0.7856
model=gat top_k=100 fold=7 epoch=28 loss=8.9840 val_auc=0.7879
model=gat top_k=100 fold=7 epoch=29 loss=5.8958 val_auc=0.7885
model=gat top_k=100 fold=7 epoch=30 loss=8.7275 val_auc=0.7894
model=gat top_k=100 fold=7 epoch=31 loss=11.0083 val_auc=0.7905
model=gat top_k=100 fold=7 epoch=32 loss=11.9031 val_auc=0.7911
model=gat top_k=100 fold=7 epoch=33 loss=10.2477 val_auc=0.7908
model=gat top_k=100 fold=7 epoch=34 loss=8.4276 val_auc=0.7890
model=gat top_k=100 fold=7 epoch=35 loss=5.1510 val_auc=0.7879
model=gat top_k=100 fold=7 epoch=36 loss=7.5122 val_auc=0.7874
model=gat top_k=100 fold=7 epoch=37 loss=6.5066 val_auc=0.7893
model=gat top_k=100 fold=7 epoch=38 loss=7.0272 val_auc=0.7916
model=gat top_k=100 fold=7 epoch=39 loss=7.6795 val_auc=0.7932
model=gat top_k=100 fold=7 epoch=40 loss=5.8349 val_auc=0.7939
model=gat top_k=100 fold=7 epoch=41 loss=4.7810 val_auc=0.7947
model=gat top_k=100 fold=7 epoch=42 loss=5.0373 val_auc=0.7947
model=gat top_k=100 fold=7 epoch=43 loss=5.1014 val_auc=0.7942
model=gat top_k=100 fold=7 epoch=44 loss=6.4935 val_auc=0.7934
model=gat top_k=100 fold=7 epoch=45 loss=4.5088 val_auc=0.7949
model=gat top_k=100 fold=7 epoch=46 loss=4.3893 val_auc=0.7977
model=gat top_k=100 fold=7 epoch=47 loss=4.3522 val_auc=0.7995
model=gat top_k=100 fold=7 epoch=48 loss=5.0449 val_auc=0.8018
model=gat top_k=100 fold=7 epoch=49 loss=5.2196 val_auc=0.8042
model=gat top_k=100 fold=7 epoch=50 loss=4.9177 val_auc=0.8058
model=gat top_k=100 fold=7 epoch=51 loss=5.1552 val_auc=0.8054
model=gat top_k=100 fold=7 epoch=52 loss=3.9382 val_auc=0.8043
model=gat top_k=100 fold=7 epoch=53 loss=4.9000 val_auc=0.8033
model=gat top_k=100 fold=7 epoch=54 loss=4.4239 val_auc=0.8028
model=gat top_k=100 fold=7 epoch=55 loss=3.9670 val_auc=0.8031
model=gat top_k=100 fold=7 epoch=56 loss=4.0821 val_auc=0.8033
model=gat top_k=100 fold=7 epoch=57 loss=3.8703 val_auc=0.8031
model=gat top_k=100 fold=7 epoch=58 loss=3.9026 val_auc=0.8021
model=gat top_k=100 fold=7 epoch=59 loss=4.2825 val_auc=0.8009
model=gat top_k=100 fold=7 epoch=60 loss=4.4202 val_auc=0.7994
model=gat top_k=100 fold=7 epoch=61 loss=3.8726 val_auc=0.7981
model=gat top_k=100 fold=7 epoch=62 loss=4.0378 val_auc=0.8005
gat top_k=100 fold=7: early stopping at epoch 62
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782278 edges

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=100 fold=8 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782047 edges

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=100 fold=8 epoch=0 loss=13.6255 val_auc=0.6524
model=gat top_k=100 fold=8 epoch=1 loss=58.8247 val_auc=0.5389
model=gat top_k=100 fold=8 epoch=2 loss=20.1362 val_auc=0.7249
model=gat top_k=100 fold=8 epoch=3 loss=8.8562 val_auc=0.7351
model=gat top_k=100 fold=8 epoch=4 loss=12.2734 val_auc=0.7566
model=gat top_k=100 fold=8 epoch=5 loss=9.4148 val_auc=0.7461
model=gat top_k=100 fold=8 epoch=6 loss=16.1151 val_auc=0.7486
model=gat top_k=100 fold=8 epoch=7 loss=16.5235 val_auc=0.7551
model=gat top_k=100 fold=8 epoch=8 loss=8.9025 val_auc=0.7048
model=gat top_k=100 fold=8 epoch=9 loss=12.7355 val_auc=0.7496
model=gat top_k=100 fold=8 epoch=10 loss=11.7611 val_auc=0.7796
model=gat top_k=100 fold=8 epoch=11 loss=7.9598 val_auc=0.7792
model=gat top_k=100 fold=8 epoch=12 loss=10.1120 val_auc=0.7787
model=gat top_k=100 fold=8 epoch=13 loss=11.6789 val_auc=0.7805
model=gat top_k=100 fold=8 epoch=14 loss=7.2491 val_auc=0.7828
model=gat top_k=100 fold=8 epoch=15 loss=8.2756 val_auc=0.7806
model=gat top_k=100 fold=8 epoch=16 loss=9.8786 val_auc=0.7833
model=gat top_k=100 fold=8 epoch=17 loss=8.4466 val_auc=0.7866
model=gat top_k=100 fold=8 epoch=18 loss=6.5250 val_auc=0.7876
model=gat top_k=100 fold=8 epoch=19 loss=6.7096 val_auc=0.7875
model=gat top_k=100 fold=8 epoch=20 loss=7.6291 val_auc=0.7864
model=gat top_k=100 fold=8 epoch=21 loss=6.3589 val_auc=0.7850
model=gat top_k=100 fold=8 epoch=22 loss=6.3154 val_auc=0.7845
model=gat top_k=100 fold=8 epoch=23 loss=5.5872 val_auc=0.7866
model=gat top_k=100 fold=8 epoch=24 loss=5.3519 val_auc=0.7879
model=gat top_k=100 fold=8 epoch=25 loss=6.0520 val_auc=0.7910
model=gat top_k=100 fold=8 epoch=26 loss=6.9488 val_auc=0.7936
model=gat top_k=100 fold=8 epoch=27 loss=6.8665 val_auc=0.7956
model=gat top_k=100 fold=8 epoch=28 loss=6.1516 val_auc=0.7959
model=gat top_k=100 fold=8 epoch=29 loss=7.0618 val_auc=0.7967
model=gat top_k=100 fold=8 epoch=30 loss=6.1964 val_auc=0.7996
model=gat top_k=100 fold=8 epoch=31 loss=5.1258 val_auc=0.8008
model=gat top_k=100 fold=8 epoch=32 loss=5.3184 val_auc=0.8019
model=gat top_k=100 fold=8 epoch=33 loss=6.6456 val_auc=0.8028
model=gat top_k=100 fold=8 epoch=34 loss=5.0404 val_auc=0.8035
model=gat top_k=100 fold=8 epoch=35 loss=6.7582 val_auc=0.8039
model=gat top_k=100 fold=8 epoch=36 loss=5.9660 val_auc=0.8052
model=gat top_k=100 fold=8 epoch=37 loss=4.8408 val_auc=0.8027
model=gat top_k=100 fold=8 epoch=38 loss=4.4740 val_auc=0.7958
model=gat top_k=100 fold=8 epoch=39 loss=4.7306 val_auc=0.7866
model=gat top_k=100 fold=8 epoch=40 loss=5.8818 val_auc=0.7849
model=gat top_k=100 fold=8 epoch=41 loss=5.3667 val_auc=0.7908
model=gat top_k=100 fold=8 epoch=42 loss=4.7300 val_auc=0.8025
model=gat top_k=100 fold=8 epoch=43 loss=4.7071 val_auc=0.8085
model=gat top_k=100 fold=8 epoch=44 loss=4.4689 val_auc=0.8087
model=gat top_k=100 fold=8 epoch=45 loss=3.7997 val_auc=0.8097
model=gat top_k=100 fold=8 epoch=46 loss=4.4773 val_auc=0.8106
model=gat top_k=100 fold=8 epoch=47 loss=3.9992 val_auc=0.8107
model=gat top_k=100 fold=8 epoch=48 loss=4.5730 val_auc=0.8091
model=gat top_k=100 fold=8 epoch=49 loss=4.1609 val_auc=0.8096
model=gat top_k=100 fold=8 epoch=50 loss=4.3011 val_auc=0.8119
model=gat top_k=100 fold=8 epoch=51 loss=3.9695 val_auc=0.8131
model=gat top_k=100 fold=8 epoch=52 loss=3.8767 val_auc=0.8140
model=gat top_k=100 fold=8 epoch=53 loss=3.5060 val_auc=0.8134
model=gat top_k=100 fold=8 epoch=54 loss=5.4328 val_auc=0.8147
model=gat top_k=100 fold=8 epoch=55 loss=5.2028 val_auc=0.8163
model=gat top_k=100 fold=8 epoch=56 loss=3.7155 val_auc=0.8186
model=gat top_k=100 fold=8 epoch=57 loss=4.0525 val_auc=0.8191
model=gat top_k=100 fold=8 epoch=58 loss=4.3920 val_auc=0.8191
model=gat top_k=100 fold=8 epoch=59 loss=3.6690 val_auc=0.8185
model=gat top_k=100 fold=8 epoch=60 loss=3.7969 val_auc=0.8178
model=gat top_k=100 fold=8 epoch=61 loss=4.4698 val_auc=0.8172
model=gat top_k=100 fold=8 epoch=62 loss=3.6720 val_auc=0.8169
model=gat top_k=100 fold=8 epoch=63 loss=2.9535 val_auc=0.8169
model=gat top_k=100 fold=8 epoch=64 loss=3.0620 val_auc=0.8170
model=gat top_k=100 fold=8 epoch=65 loss=2.8886 val_auc=0.8176
model=gat top_k=100 fold=8 epoch=66 loss=3.4173 val_auc=0.8174
model=gat top_k=100 fold=8 epoch=67 loss=3.2346 val_auc=0.8171
model=gat top_k=100 fold=8 epoch=68 loss=3.1892 val_auc=0.8140
model=gat top_k=100 fold=8 epoch=69 loss=3.2107 val_auc=0.8025
gat top_k=100 fold=8: early stopping at epoch 69
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782047 edges

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=100 fold=9 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 781970 edges
model=gat top_k=100 fold=9 epoch=0 loss=10.7006 val_auc=0.7216

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=100 fold=9 epoch=1 loss=12.0585 val_auc=0.6598
model=gat top_k=100 fold=9 epoch=2 loss=57.3372 val_auc=0.7168
model=gat top_k=100 fold=9 epoch=3 loss=23.6557 val_auc=0.5060
model=gat top_k=100 fold=9 epoch=4 loss=20.9232 val_auc=0.5433
model=gat top_k=100 fold=9 epoch=5 loss=22.0150 val_auc=0.6936
model=gat top_k=100 fold=9 epoch=6 loss=8.6569 val_auc=0.6932
model=gat top_k=100 fold=9 epoch=7 loss=9.8479 val_auc=0.6967
model=gat top_k=100 fold=9 epoch=8 loss=8.6421 val_auc=0.7028
model=gat top_k=100 fold=9 epoch=9 loss=6.6104 val_auc=0.7142
model=gat top_k=100 fold=9 epoch=10 loss=8.7529 val_auc=0.7243
model=gat top_k=100 fold=9 epoch=11 loss=8.0658 val_auc=0.7334
model=gat top_k=100 fold=9 epoch=12 loss=9.2825 val_auc=0.7451
model=gat top_k=100 fold=9 epoch=13 loss=8.9016 val_auc=0.7565
model=gat top_k=100 fold=9 epoch=14 loss=13.0359 val_auc=0.7188
model=gat top_k=100 fold=9 epoch=15 loss=16.0439 val_auc=0.7462
model=gat top_k=100 fold=9 epoch=16 loss=11.5594 val_auc=0.7845
model=gat top_k=100 fold=9 epoch=17 loss=5.6432 val_auc=0.7865
model=gat top_k=100 fold=9 epoch=18 loss=9.1595 val_auc=0.7882
model=gat top_k=100 fold=9 epoch=19 loss=11.4310 val_auc=0.7901
model=gat top_k=100 fold=9 epoch=20 loss=10.7290 val_auc=0.7911
model=gat top_k=100 fold=9 epoch=21 loss=6.6550 val_auc=0.7912
model=gat top_k=100 fold=9 epoch=22 loss=6.3105 val_auc=0.7826
model=gat top_k=100 fold=9 epoch=23 loss=10.0235 val_auc=0.7800
model=gat top_k=100 fold=9 epoch=24 loss=9.2856 val_auc=0.7912
model=gat top_k=100 fold=9 epoch=25 loss=7.8423 val_auc=0.7940
model=gat top_k=100 fold=9 epoch=26 loss=6.3152 val_auc=0.7943
model=gat top_k=100 fold=9 epoch=27 loss=7.5233 val_auc=0.7945
model=gat top_k=100 fold=9 epoch=28 loss=5.9454 val_auc=0.7949
model=gat top_k=100 fold=9 epoch=29 loss=5.2270 val_auc=0.7940
model=gat top_k=100 fold=9 epoch=30 loss=5.2420 val_auc=0.7918
model=gat top_k=100 fold=9 epoch=31 loss=8.4420 val_auc=0.7918
model=gat top_k=100 fold=9 epoch=32 loss=7.8111 val_auc=0.7902
model=gat top_k=100 fold=9 epoch=33 loss=5.9532 val_auc=0.7903
model=gat top_k=100 fold=9 epoch=34 loss=7.7757 val_auc=0.7893
model=gat top_k=100 fold=9 epoch=35 loss=6.6181 val_auc=0.7884
model=gat top_k=100 fold=9 epoch=36 loss=8.0009 val_auc=0.7876
model=gat top_k=100 fold=9 epoch=37 loss=5.6928 val_auc=0.7873
model=gat top_k=100 fold=9 epoch=38 loss=4.9758 val_auc=0.7842
model=gat top_k=100 fold=9 epoch=39 loss=6.6590 val_auc=0.7738
model=gat top_k=100 fold=9 epoch=40 loss=7.3641 val_auc=0.7675
gat top_k=100 fold=9: early stopping at epoch 40
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 781970 edges

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/35 [00:00<?, ?it/s]

######## Model=gat top_k=200 ########

===== Model=gat top_k=200 fold=0 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782165 edges
model=gat top_k=200 fold=0 epoch=0 loss=17.4678 val_auc=0.4991
model=gat top_k=200 fold=0 epoch=1 loss=119.5366 val_auc=0.5013
model=gat top_k=200 fold=0 epoch=2 loss=30.3609 val_auc=0.6792
model=gat top_k=200 fold=0 epoch=3 loss=34.1500 val_auc=0.6790
model=gat top_k=200 fold=0 epoch=4 loss=25.4703 val_auc=0.6824
model=gat top_k=200 fold=0 epoch=5 loss=11.5847 val_auc=0.4987
model=gat top_k=200 fold=0 epoch=6 loss=19.7810 val_auc=0.4937
model=gat top_k=200 fold=0 epoch=7 loss=24.5154 val_auc=0.6944
model=gat top_k=200 fold=0 epoch=8 loss=9.8934 val_auc=0.7078
model=gat top_k=200 fold=0 epoch=9 loss=9.2608 val_auc=0.7202
model=gat top_k=200 fold=0 epoch=10 loss=11.6903 val_auc=0.7318
model=gat top_k=200 fold=0 epoch=11 loss=9.0075 val_auc=0.7394
model=gat top_k=200 fold=0 epoch=12 loss=7.3837 val_auc=0.7485
model=gat top_k=200 fold=0 epoch=13 loss=10.1687 val_auc=0.7647
model=gat top_k=200 fold=0 epoch=14 loss=6.9525 val_auc=0.7768
model=gat top_k=200 fold=0 epoch=15 loss=7.4973 val_auc=0.7824
model=gat top_k=200 fold=0 epoch=16 loss=5.6063 val_auc=0.7874
model=gat top_k=200 fold=0 epoch=17 loss=5.3198 val_auc=0.7929
model=gat top_k=200 fold=0 epoch=18 loss=4.7621 val_auc=0.7958
model=gat top_k=200 fold=0 epoch=19 loss=5.2690 val_auc=0.7960
model=gat top_k=200 fold=0 epoch=20 loss=5.2783 val_auc=0.7960
model=gat top_k=200 fold=0 epoch=21 loss=6.5166 val_auc=0.7967
model=gat top_k=200 fold=0 epoch=22 loss=5.7044 val_auc=0.8000
model=gat top_k=200 fold=0 epoch=23 loss=5.6100 val_auc=0.8004
model=gat top_k=200 fold=0 epoch=24 loss=8.2003 val_auc=0.8004
model=gat top_k=200 fold=0 epoch=25 loss=8.1263 val_auc=0.8006
model=gat top_k=200 fold=0 epoch=26 loss=4.5565 val_auc=0.8009
model=gat top_k=200 fold=0 epoch=27 loss=4.9649 val_auc=0.8016
model=gat top_k=200 fold=0 epoch=28 loss=5.7746 val_auc=0.8001
model=gat top_k=200 fold=0 epoch=29 loss=4.6261 val_auc=0.8001
model=gat top_k=200 fold=0 epoch=30 loss=4.4286 val_auc=0.8007
model=gat top_k=200 fold=0 epoch=31 loss=5.7665 val_auc=0.8010
model=gat top_k=200 fold=0 epoch=32 loss=4.8847 val_auc=0.8013
model=gat top_k=200 fold=0 epoch=33 loss=4.6689 val_auc=0.8000
model=gat top_k=200 fold=0 epoch=34 loss=5.3801 val_auc=0.8001
model=gat top_k=200 fold=0 epoch=35 loss=5.9185 val_auc=0.8017
model=gat top_k=200 fold=0 epoch=36 loss=5.3850 val_auc=0.8012
model=gat top_k=200 fold=0 epoch=37 loss=5.3108 val_auc=0.8014
model=gat top_k=200 fold=0 epoch=38 loss=6.5614 val_auc=0.8019
model=gat top_k=200 fold=0 epoch=39 loss=4.3755 val_auc=0.8023
model=gat top_k=200 fold=0 epoch=40 loss=4.6542 val_auc=0.8025
model=gat top_k=200 fold=0 epoch=41 loss=3.9103 val_auc=0.8030
model=gat top_k=200 fold=0 epoch=42 loss=4.4490 val_auc=0.8035
model=gat top_k=200 fold=0 epoch=43 loss=3.9879 val_auc=0.8037
model=gat top_k=200 fold=0 epoch=44 loss=4.0387 val_auc=0.8034
model=gat top_k=200 fold=0 epoch=45 loss=4.2711 val_auc=0.8020
model=gat top_k=200 fold=0 epoch=46 loss=4.6074 val_auc=0.8008
model=gat top_k=200 fold=0 epoch=47 loss=3.7655 val_auc=0.7988
model=gat top_k=200 fold=0 epoch=48 loss=3.4499 val_auc=0.7978
model=gat top_k=200 fold=0 epoch=49 loss=3.4117 val_auc=0.7997
model=gat top_k=200 fold=0 epoch=50 loss=4.7990 val_auc=0.8019
model=gat top_k=200 fold=0 epoch=51 loss=3.3554 val_auc=0.8034
model=gat top_k=200 fold=0 epoch=52 loss=3.2603 val_auc=0.8052
model=gat top_k=200 fold=0 epoch=53 loss=4.6728 val_auc=0.8056
model=gat top_k=200 fold=0 epoch=54 loss=4.8219 val_auc=0.8052
model=gat top_k=200 fold=0 epoch=55 loss=3.6271 val_auc=0.8045
model=gat top_k=200 fold=0 epoch=56 loss=4.0870 val_auc=0.8039
model=gat top_k=200 fold=0 epoch=57 loss=5.0504 val_auc=0.8042
model=gat top_k=200 fold=0 epoch=58 loss=5.4584 val_auc=0.8057
model=gat top_k=200 fold=0 epoch=59 loss=3.4068 val_auc=0.8080
model=gat top_k=200 fold=0 epoch=60 loss=4.5947 val_auc=0.8090
model=gat top_k=200 fold=0 epoch=61 loss=4.9086 val_auc=0.8096
model=gat top_k=200 fold=0 epoch=62 loss=3.4491 val_auc=0.8104
model=gat top_k=200 fold=0 epoch=63 loss=4.0261 val_auc=0.8111
model=gat top_k=200 fold=0 epoch=64 loss=3.3484 val_auc=0.8119
model=gat top_k=200 fold=0 epoch=65 loss=4.0385 val_auc=0.8124
model=gat top_k=200 fold=0 epoch=66 loss=2.7425 val_auc=0.8126
model=gat top_k=200 fold=0 epoch=67 loss=4.9413 val_auc=0.8130
model=gat top_k=200 fold=0 epoch=68 loss=4.3048 val_auc=0.8132
model=gat top_k=200 fold=0 epoch=69 loss=3.1519 val_auc=0.8134
model=gat top_k=200 fold=0 epoch=70 loss=2.5840 val_auc=0.8140
model=gat top_k=200 fold=0 epoch=71 loss=4.4645 val_auc=0.8140
model=gat top_k=200 fold=0 epoch=72 loss=4.8643 val_auc=0.8139
model=gat top_k=200 fold=0 epoch=73 loss=3.1550 val_auc=0.8142
model=gat top_k=200 fold=0 epoch=74 loss=3.4748 val_auc=0.8150
model=gat top_k=200 fold=0 epoch=75 loss=5.1661 val_auc=0.8151
model=gat top_k=200 fold=0 epoch=76 loss=4.1815 val_auc=0.8150
model=gat top_k=200 fold=0 epoch=77 loss=3.4918 val_auc=0.8152
model=gat top_k=200 fold=0 epoch=78 loss=2.8904 val_auc=0.8157
model=gat top_k=200 fold=0 epoch=79 loss=4.0351 val_auc=0.8162
model=gat top_k=200 fold=0 epoch=80 loss=4.0812 val_auc=0.8164
model=gat top_k=200 fold=0 epoch=81 loss=2.8443 val_auc=0.8164
model=gat top_k=200 fold=0 epoch=82 loss=2.9757 val_auc=0.8163
model=gat top_k=200 fold=0 epoch=83 loss=3.0112 val_auc=0.8165
model=gat top_k=200 fold=0 epoch=84 loss=2.7599 val_auc=0.8170
model=gat top_k=200 fold=0 epoch=85 loss=2.4909 val_auc=0.8178
model=gat top_k=200 fold=0 epoch=86 loss=2.5830 val_auc=0.8185
model=gat top_k=200 fold=0 epoch=87 loss=2.4333 val_auc=0.8187
model=gat top_k=200 fold=0 epoch=88 loss=2.6620 val_auc=0.8187
model=gat top_k=200 fold=0 epoch=89 loss=2.6361 val_auc=0.8193
model=gat top_k=200 fold=0 epoch=90 loss=3.2780 val_auc=0.8199
model=gat top_k=200 fold=0 epoch=91 loss=2.3706 val_auc=0.8211
model=gat top_k=200 fold=0 epoch=92 loss=2.1639 val_auc=0.8216
model=gat top_k=200 fold=0 epoch=93 loss=3.2333 val_auc=0.8222
model=gat top_k=200 fold=0 epoch=94 loss=3.4418 val_auc=0.8224
model=gat top_k=200 fold=0 epoch=95 loss=2.5829 val_auc=0.8223
model=gat top_k=200 fold=0 epoch=96 loss=2.4564 val_auc=0.8224
model=gat top_k=200 fold=0 epoch=97 loss=2.5904 val_auc=0.8219
model=gat top_k=200 fold=0 epoch=98 loss=2.5921 val_auc=0.8214
model=gat top_k=200 fold=0 epoch=99 loss=2.5568 val_auc=0.8216
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782165 edges

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=200 fold=1 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782386 edges

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=200 fold=1 epoch=0 loss=16.0150 val_auc=0.6626
model=gat top_k=200 fold=1 epoch=1 loss=50.4413 val_auc=0.5145
model=gat top_k=200 fold=1 epoch=2 loss=27.8819 val_auc=0.7152
model=gat top_k=200 fold=1 epoch=3 loss=12.0138 val_auc=0.7296
model=gat top_k=200 fold=1 epoch=4 loss=24.5273 val_auc=0.7370
model=gat top_k=200 fold=1 epoch=5 loss=15.3224 val_auc=0.7374
model=gat top_k=200 fold=1 epoch=6 loss=8.6294 val_auc=0.7382
model=gat top_k=200 fold=1 epoch=7 loss=11.0226 val_auc=0.7394
model=gat top_k=200 fold=1 epoch=8 loss=8.9963 val_auc=0.7379
model=gat top_k=200 fold=1 epoch=9 loss=8.1537 val_auc=0.7332
model=gat top_k=200 fold=1 epoch=10 loss=7.6636 val_auc=0.7396
model=gat top_k=200 fold=1 epoch=11 loss=8.3593 val_auc=0.7466
model=gat top_k=200 fold=1 epoch=12 loss=7.9142 val_auc=0.7516
model=gat top_k=200 fold=1 epoch=13 loss=7.1380 val_auc=0.7646
model=gat top_k=200 fold=1 epoch=14 loss=6.8033 val_auc=0.7634
model=gat top_k=200 fold=1 epoch=15 loss=11.1606 val_auc=0.7740
model=gat top_k=200 fold=1 epoch=16 loss=11.8458 val_auc=0.7819
model=gat top_k=200 fold=1 epoch=17 loss=5.5834 val_auc=0.7805
model=gat top_k=200 fold=1 epoch=18 loss=9.1258 val_auc=0.7796
model=gat top_k=200 fold=1 epoch=19 loss=9.8875 val_auc=0.7804
model=gat top_k=200 fold=1 epoch=20 loss=5.5662 val_auc=0.7797
model=gat top_k=200 fold=1 epoch=21 loss=7.5267 val_auc=0.7762
model=gat top_k=200 fold=1 epoch=22 loss=7.6877 val_auc=0.7759
model=gat top_k=200 fold=1 epoch=23 loss=10.1686 val_auc=0.7796
model=gat top_k=200 fold=1 epoch=24 loss=5.7723 val_auc=0.7807
model=gat top_k=200 fold=1 epoch=25 loss=6.0980 val_auc=0.7833
model=gat top_k=200 fold=1 epoch=26 loss=7.8844 val_auc=0.7870
model=gat top_k=200 fold=1 epoch=27 loss=5.8205 val_auc=0.7903
model=gat top_k=200 fold=1 epoch=28 loss=5.3543 val_auc=0.7933
model=gat top_k=200 fold=1 epoch=29 loss=5.5357 val_auc=0.7961
model=gat top_k=200 fold=1 epoch=30 loss=6.4757 val_auc=0.7973
model=gat top_k=200 fold=1 epoch=31 loss=6.9026 val_auc=0.7973
model=gat top_k=200 fold=1 epoch=32 loss=5.2857 val_auc=0.7963
model=gat top_k=200 fold=1 epoch=33 loss=4.9537 val_auc=0.7957
model=gat top_k=200 fold=1 epoch=34 loss=6.6423 val_auc=0.7972
model=gat top_k=200 fold=1 epoch=35 loss=5.2553 val_auc=0.8002
model=gat top_k=200 fold=1 epoch=36 loss=4.4082 val_auc=0.8019
model=gat top_k=200 fold=1 epoch=37 loss=4.7017 val_auc=0.8022
model=gat top_k=200 fold=1 epoch=38 loss=4.9405 val_auc=0.8027
model=gat top_k=200 fold=1 epoch=39 loss=5.1214 val_auc=0.8027
model=gat top_k=200 fold=1 epoch=40 loss=4.0882 val_auc=0.8029
model=gat top_k=200 fold=1 epoch=41 loss=4.8861 val_auc=0.8050
model=gat top_k=200 fold=1 epoch=42 loss=4.6949 val_auc=0.8076
model=gat top_k=200 fold=1 epoch=43 loss=4.0678 val_auc=0.8106
model=gat top_k=200 fold=1 epoch=44 loss=3.9334 val_auc=0.8129
model=gat top_k=200 fold=1 epoch=45 loss=4.6034 val_auc=0.8153
model=gat top_k=200 fold=1 epoch=46 loss=5.1599 val_auc=0.8171
model=gat top_k=200 fold=1 epoch=47 loss=3.7026 val_auc=0.8179
model=gat top_k=200 fold=1 epoch=48 loss=4.1930 val_auc=0.8185
model=gat top_k=200 fold=1 epoch=49 loss=4.3815 val_auc=0.8197
model=gat top_k=200 fold=1 epoch=50 loss=3.6610 val_auc=0.8205
model=gat top_k=200 fold=1 epoch=51 loss=4.1466 val_auc=0.8203
model=gat top_k=200 fold=1 epoch=52 loss=3.7215 val_auc=0.8192
model=gat top_k=200 fold=1 epoch=53 loss=3.7610 val_auc=0.8178
model=gat top_k=200 fold=1 epoch=54 loss=3.6965 val_auc=0.8169
model=gat top_k=200 fold=1 epoch=55 loss=3.4844 val_auc=0.8174
model=gat top_k=200 fold=1 epoch=56 loss=3.8012 val_auc=0.8193
model=gat top_k=200 fold=1 epoch=57 loss=3.4976 val_auc=0.8203
model=gat top_k=200 fold=1 epoch=58 loss=3.7424 val_auc=0.8208
model=gat top_k=200 fold=1 epoch=59 loss=3.7219 val_auc=0.8210
model=gat top_k=200 fold=1 epoch=60 loss=2.9021 val_auc=0.8212
model=gat top_k=200 fold=1 epoch=61 loss=3.2921 val_auc=0.8224
model=gat top_k=200 fold=1 epoch=62 loss=3.4887 val_auc=0.8228
model=gat top_k=200 fold=1 epoch=63 loss=3.4334 val_auc=0.8248
model=gat top_k=200 fold=1 epoch=64 loss=3.3008 val_auc=0.8264
model=gat top_k=200 fold=1 epoch=65 loss=3.2825 val_auc=0.8269
model=gat top_k=200 fold=1 epoch=66 loss=2.9719 val_auc=0.8266
model=gat top_k=200 fold=1 epoch=67 loss=3.5920 val_auc=0.8271
model=gat top_k=200 fold=1 epoch=68 loss=3.4079 val_auc=0.8278
model=gat top_k=200 fold=1 epoch=69 loss=3.8195 val_auc=0.8276
model=gat top_k=200 fold=1 epoch=70 loss=3.3735 val_auc=0.8267
model=gat top_k=200 fold=1 epoch=71 loss=3.7097 val_auc=0.8270
model=gat top_k=200 fold=1 epoch=72 loss=3.2407 val_auc=0.8281
model=gat top_k=200 fold=1 epoch=73 loss=2.6880 val_auc=0.8296
model=gat top_k=200 fold=1 epoch=74 loss=2.9911 val_auc=0.8300
model=gat top_k=200 fold=1 epoch=75 loss=3.3330 val_auc=0.8301
model=gat top_k=200 fold=1 epoch=76 loss=2.6198 val_auc=0.8304
model=gat top_k=200 fold=1 epoch=77 loss=3.4032 val_auc=0.8305
model=gat top_k=200 fold=1 epoch=78 loss=3.1439 val_auc=0.8311
model=gat top_k=200 fold=1 epoch=79 loss=3.1647 val_auc=0.8326
model=gat top_k=200 fold=1 epoch=80 loss=2.4426 val_auc=0.8335
model=gat top_k=200 fold=1 epoch=81 loss=3.1233 val_auc=0.8333
model=gat top_k=200 fold=1 epoch=82 loss=2.8144 val_auc=0.8325
model=gat top_k=200 fold=1 epoch=83 loss=2.7798 val_auc=0.8320
model=gat top_k=200 fold=1 epoch=84 loss=2.6059 val_auc=0.8319
model=gat top_k=200 fold=1 epoch=85 loss=2.5680 val_auc=0.8330
model=gat top_k=200 fold=1 epoch=86 loss=2.4660 val_auc=0.8334
model=gat top_k=200 fold=1 epoch=87 loss=2.6679 val_auc=0.8328
model=gat top_k=200 fold=1 epoch=88 loss=3.3795 val_auc=0.8313
model=gat top_k=200 fold=1 epoch=89 loss=2.5157 val_auc=0.8299
model=gat top_k=200 fold=1 epoch=90 loss=2.6097 val_auc=0.8288
model=gat top_k=200 fold=1 epoch=91 loss=3.0536 val_auc=0.8301
model=gat top_k=200 fold=1 epoch=92 loss=2.8238 val_auc=0.8327
gat top_k=200 fold=1: early stopping at epoch 92
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782386 edges

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=200 fold=2 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782205 edges
model=gat top_k=200 fold=2 epoch=0 loss=16.8039 val_auc=0.5000
model=gat top_k=200 fold=2 epoch=1 loss=128.0158 val_auc=0.4886

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=200 fold=2 epoch=2 loss=32.5675 val_auc=0.5564
model=gat top_k=200 fold=2 epoch=3 loss=45.0041 val_auc=0.5837
model=gat top_k=200 fold=2 epoch=4 loss=46.9422 val_auc=0.6305
model=gat top_k=200 fold=2 epoch=5 loss=18.3516 val_auc=0.6392
model=gat top_k=200 fold=2 epoch=6 loss=21.7857 val_auc=0.5368
model=gat top_k=200 fold=2 epoch=7 loss=25.6428 val_auc=0.6414
model=gat top_k=200 fold=2 epoch=8 loss=12.1519 val_auc=0.7189
model=gat top_k=200 fold=2 epoch=9 loss=9.6249 val_auc=0.7286
model=gat top_k=200 fold=2 epoch=10 loss=12.0696 val_auc=0.7376
model=gat top_k=200 fold=2 epoch=11 loss=12.1778 val_auc=0.7435
model=gat top_k=200 fold=2 epoch=12 loss=8.5650 val_auc=0.7412
model=gat top_k=200 fold=2 epoch=13 loss=14.6527 val_auc=0.5895
model=gat top_k=200 fold=2 epoch=14 loss=19.4688 val_auc=0.6126
model=gat top_k=200 fold=2 epoch=15 loss=16.8944 val_auc=0.7442
model=gat top_k=200 fold=2 epoch=16 loss=10.7789 val_auc=0.7552
model=gat top_k=200 fold=2 epoch=17 loss=9.1448 val_auc=0.7560
model=gat top_k=200 fold=2 epoch=18 loss=9.1643 val_auc=0.7591
model=gat top_k=200 fold=2 epoch=19 loss=13.1811 val_auc=0.7622
model=gat top_k=200 fold=2 epoch=20 loss=12.2286 val_auc=0.7648
model=gat top_k=200 fold=2 epoch=21 loss=14.3888 val_auc=0.7669
model=gat top_k=200 fold=2 epoch=22 loss=7.7081 val_auc=0.7678
model=gat top_k=200 fold=2 epoch=23 loss=7.9757 val_auc=0.7481
model=gat top_k=200 fold=2 epoch=24 loss=12.6562 val_auc=0.7056
model=gat top_k=200 fold=2 epoch=25 loss=13.0046 val_auc=0.7339
model=gat top_k=200 fold=2 epoch=26 loss=11.9493 val_auc=0.7699
model=gat top_k=200 fold=2 epoch=27 loss=8.7980 val_auc=0.7732
model=gat top_k=200 fold=2 epoch=28 loss=6.4036 val_auc=0.7750
model=gat top_k=200 fold=2 epoch=29 loss=7.7473 val_auc=0.7764
model=gat top_k=200 fold=2 epoch=30 loss=10.7571 val_auc=0.7774
model=gat top_k=200 fold=2 epoch=31 loss=7.4888 val_auc=0.7781
model=gat top_k=200 fold=2 epoch=32 loss=6.5362 val_auc=0.7787
model=gat top_k=200 fold=2 epoch=33 loss=6.3616 val_auc=0.7790
model=gat top_k=200 fold=2 epoch=34 loss=6.5200 val_auc=0.7794
model=gat top_k=200 fold=2 epoch=35 loss=7.9414 val_auc=0.7797
model=gat top_k=200 fold=2 epoch=36 loss=10.5464 val_auc=0.7807
model=gat top_k=200 fold=2 epoch=37 loss=8.9236 val_auc=0.7818
model=gat top_k=200 fold=2 epoch=38 loss=6.4114 val_auc=0.7828
model=gat top_k=200 fold=2 epoch=39 loss=5.4745 val_auc=0.7837
model=gat top_k=200 fold=2 epoch=40 loss=5.7766 val_auc=0.7844
model=gat top_k=200 fold=2 epoch=41 loss=5.4062 val_auc=0.7851
model=gat top_k=200 fold=2 epoch=42 loss=5.0333 val_auc=0.7860
model=gat top_k=200 fold=2 epoch=43 loss=5.7709 val_auc=0.7862
model=gat top_k=200 fold=2 epoch=44 loss=5.0099 val_auc=0.7860
model=gat top_k=200 fold=2 epoch=45 loss=5.1907 val_auc=0.7852
model=gat top_k=200 fold=2 epoch=46 loss=4.4787 val_auc=0.7853
model=gat top_k=200 fold=2 epoch=47 loss=4.9647 val_auc=0.7869
model=gat top_k=200 fold=2 epoch=48 loss=4.5337 val_auc=0.7892
model=gat top_k=200 fold=2 epoch=49 loss=5.1625 val_auc=0.7900
model=gat top_k=200 fold=2 epoch=50 loss=5.3144 val_auc=0.7890
model=gat top_k=200 fold=2 epoch=51 loss=4.3663 val_auc=0.7855
model=gat top_k=200 fold=2 epoch=52 loss=4.4723 val_auc=0.7856
model=gat top_k=200 fold=2 epoch=53 loss=5.0731 val_auc=0.7878
model=gat top_k=200 fold=2 epoch=54 loss=5.4442 val_auc=0.7909
model=gat top_k=200 fold=2 epoch=55 loss=3.6205 val_auc=0.7933
model=gat top_k=200 fold=2 epoch=56 loss=4.7504 val_auc=0.7960
model=gat top_k=200 fold=2 epoch=57 loss=4.9392 val_auc=0.7983
model=gat top_k=200 fold=2 epoch=58 loss=4.1494 val_auc=0.8017
model=gat top_k=200 fold=2 epoch=59 loss=3.3416 val_auc=0.8038
model=gat top_k=200 fold=2 epoch=60 loss=3.5639 val_auc=0.8055
model=gat top_k=200 fold=2 epoch=61 loss=3.4743 val_auc=0.8071
model=gat top_k=200 fold=2 epoch=62 loss=4.4536 val_auc=0.8078
model=gat top_k=200 fold=2 epoch=63 loss=3.9547 val_auc=0.8076
model=gat top_k=200 fold=2 epoch=64 loss=4.3534 val_auc=0.8083
model=gat top_k=200 fold=2 epoch=65 loss=3.5671 val_auc=0.8095
model=gat top_k=200 fold=2 epoch=66 loss=3.4041 val_auc=0.8115
model=gat top_k=200 fold=2 epoch=67 loss=3.6598 val_auc=0.8128
model=gat top_k=200 fold=2 epoch=68 loss=3.5488 val_auc=0.8144
model=gat top_k=200 fold=2 epoch=69 loss=4.1006 val_auc=0.8152
model=gat top_k=200 fold=2 epoch=70 loss=3.6548 val_auc=0.8147
model=gat top_k=200 fold=2 epoch=71 loss=4.2304 val_auc=0.8134
model=gat top_k=200 fold=2 epoch=72 loss=4.0872 val_auc=0.8128
model=gat top_k=200 fold=2 epoch=73 loss=5.7353 val_auc=0.8129
model=gat top_k=200 fold=2 epoch=74 loss=3.8291 val_auc=0.8132
model=gat top_k=200 fold=2 epoch=75 loss=2.9516 val_auc=0.8145
model=gat top_k=200 fold=2 epoch=76 loss=3.0647 val_auc=0.8152
model=gat top_k=200 fold=2 epoch=77 loss=4.9857 val_auc=0.8160
model=gat top_k=200 fold=2 epoch=78 loss=2.9233 val_auc=0.8149
model=gat top_k=200 fold=2 epoch=79 loss=3.2407 val_auc=0.8147
model=gat top_k=200 fold=2 epoch=80 loss=3.5396 val_auc=0.8166
model=gat top_k=200 fold=2 epoch=81 loss=3.2208 val_auc=0.8169
model=gat top_k=200 fold=2 epoch=82 loss=3.2828 val_auc=0.8164
model=gat top_k=200 fold=2 epoch=83 loss=3.4227 val_auc=0.8167
model=gat top_k=200 fold=2 epoch=84 loss=2.9381 val_auc=0.8178
model=gat top_k=200 fold=2 epoch=85 loss=3.8186 val_auc=0.8175
model=gat top_k=200 fold=2 epoch=86 loss=3.4067 val_auc=0.8173
model=gat top_k=200 fold=2 epoch=87 loss=2.8013 val_auc=0.8177
model=gat top_k=200 fold=2 epoch=88 loss=2.9434 val_auc=0.8180
model=gat top_k=200 fold=2 epoch=89 loss=4.2109 val_auc=0.8176
model=gat top_k=200 fold=2 epoch=90 loss=4.0844 val_auc=0.8168
model=gat top_k=200 fold=2 epoch=91 loss=5.2271 val_auc=0.8157
model=gat top_k=200 fold=2 epoch=92 loss=3.4533 val_auc=0.8143
model=gat top_k=200 fold=2 epoch=93 loss=2.7092 val_auc=0.8136
model=gat top_k=200 fold=2 epoch=94 loss=4.4411 val_auc=0.8127
model=gat top_k=200 fold=2 epoch=95 loss=4.5418 val_auc=0.8124
model=gat top_k=200 fold=2 epoch=96 loss=5.9732 val_auc=0.8136
model=gat top_k=200 fold=2 epoch=97 loss=5.2528 val_auc=0.8157
model=gat top_k=200 fold=2 epoch=98 loss=2.7877 val_auc=0.8164
model=gat top_k=200 fold=2 epoch=99 loss=3.5058 val_auc=0.8147
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782205 edges

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=200 fold=3 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 781933 edges

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=200 fold=3 epoch=0 loss=28.2799 val_auc=0.5561
model=gat top_k=200 fold=3 epoch=1 loss=68.3216 val_auc=0.5366
model=gat top_k=200 fold=3 epoch=2 loss=19.5331 val_auc=0.7128
model=gat top_k=200 fold=3 epoch=3 loss=10.2823 val_auc=0.7282
model=gat top_k=200 fold=3 epoch=4 loss=9.7559 val_auc=0.7643
model=gat top_k=200 fold=3 epoch=5 loss=8.9121 val_auc=0.7719
model=gat top_k=200 fold=3 epoch=6 loss=8.6364 val_auc=0.7752
model=gat top_k=200 fold=3 epoch=7 loss=7.8969 val_auc=0.7679
model=gat top_k=200 fold=3 epoch=8 loss=8.9738 val_auc=0.7743
model=gat top_k=200 fold=3 epoch=9 loss=7.2078 val_auc=0.7753
model=gat top_k=200 fold=3 epoch=10 loss=14.8845 val_auc=0.7812
model=gat top_k=200 fold=3 epoch=11 loss=14.3650 val_auc=0.7849
model=gat top_k=200 fold=3 epoch=12 loss=7.9674 val_auc=0.7766
model=gat top_k=200 fold=3 epoch=13 loss=11.6951 val_auc=0.7802
model=gat top_k=200 fold=3 epoch=14 loss=10.2639 val_auc=0.7909
model=gat top_k=200 fold=3 epoch=15 loss=7.2265 val_auc=0.7947
model=gat top_k=200 fold=3 epoch=16 loss=11.0759 val_auc=0.7962
model=gat top_k=200 fold=3 epoch=17 loss=8.6256 val_auc=0.7970
model=gat top_k=200 fold=3 epoch=18 loss=6.6729 val_auc=0.7957
model=gat top_k=200 fold=3 epoch=19 loss=7.1041 val_auc=0.7704
model=gat top_k=200 fold=3 epoch=20 loss=10.1912 val_auc=0.7533
model=gat top_k=200 fold=3 epoch=21 loss=12.9478 val_auc=0.7905
model=gat top_k=200 fold=3 epoch=22 loss=9.1922 val_auc=0.8034
model=gat top_k=200 fold=3 epoch=23 loss=6.7136 val_auc=0.8045
model=gat top_k=200 fold=3 epoch=24 loss=8.5013 val_auc=0.8056
model=gat top_k=200 fold=3 epoch=25 loss=10.3877 val_auc=0.8064
model=gat top_k=200 fold=3 epoch=26 loss=9.2080 val_auc=0.8053
model=gat top_k=200 fold=3 epoch=27 loss=6.5303 val_auc=0.8034
model=gat top_k=200 fold=3 epoch=28 loss=6.2611 val_auc=0.7920
model=gat top_k=200 fold=3 epoch=29 loss=7.1265 val_auc=0.7911
model=gat top_k=200 fold=3 epoch=30 loss=10.4392 val_auc=0.8016
model=gat top_k=200 fold=3 epoch=31 loss=7.1822 val_auc=0.8038
model=gat top_k=200 fold=3 epoch=32 loss=5.1559 val_auc=0.8041
model=gat top_k=200 fold=3 epoch=33 loss=7.8053 val_auc=0.8037
model=gat top_k=200 fold=3 epoch=34 loss=7.5608 val_auc=0.8028
model=gat top_k=200 fold=3 epoch=35 loss=6.9806 val_auc=0.8023
model=gat top_k=200 fold=3 epoch=36 loss=5.0185 val_auc=0.8021
model=gat top_k=200 fold=3 epoch=37 loss=5.9716 val_auc=0.7985
gat top_k=200 fold=3: early stopping at epoch 37
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 781933 edges

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=200 fold=4 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782579 edges
model=gat top_k=200 fold=4 epoch=0 loss=11.0889 val_auc=0.7559
model=gat top_k=200 fold=4 epoch=1 loss=24.7152 val_auc=0.5000
model=gat top_k=200 fold=4 epoch=2 loss=69.9832 val_auc=0.5203
model=gat top_k=200 fold=4 epoch=3 loss=44.4852 val_auc=0.7311
model=gat top_k=200 fold=4 epoch=4 loss=8.5133 val_auc=0.7264
model=gat top_k=200 fold=4 epoch=5 loss=29.2771 val_auc=0.7376
model=gat top_k=200 fold=4 epoch=6 loss=24.0115 val_auc=0.7396
model=gat top_k=200 fold=4 epoch=7 loss=9.9674 val_auc=0.6674
model=gat top_k=200 fold=4 epoch=8 loss=15.2663 val_auc=0.5394
model=gat top_k=200 fold=4 epoch=9 loss=18.2741 val_auc=0.6400
model=gat top_k=200 fold=4 epoch=10 loss=14.3316 val_auc=0.7352
model=gat top_k=200 fold=4 epoch=11 loss=8.2472 val_auc=0.7355
model=gat top_k=200 fold=4 epoch=12 loss=12.4825 val_auc=0.7341
gat top_k=200 fold=4: early stopping at epoch 12
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782579 edges

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=200 fold=5 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782265 edges

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=200 fold=5 epoch=0 loss=10.7336 val_auc=0.5131
model=gat top_k=200 fold=5 epoch=1 loss=80.0321 val_auc=0.7302
model=gat top_k=200 fold=5 epoch=2 loss=10.5151 val_auc=0.5243
model=gat top_k=200 fold=5 epoch=3 loss=57.1207 val_auc=0.5202
model=gat top_k=200 fold=5 epoch=4 loss=44.5487 val_auc=0.7523
model=gat top_k=200 fold=5 epoch=5 loss=11.3217 val_auc=0.7373
model=gat top_k=200 fold=5 epoch=6 loss=23.6935 val_auc=0.7459
model=gat top_k=200 fold=5 epoch=7 loss=29.1318 val_auc=0.7535
model=gat top_k=200 fold=5 epoch=8 loss=22.4179 val_auc=0.7646
model=gat top_k=200 fold=5 epoch=9 loss=10.1243 val_auc=0.7182
model=gat top_k=200 fold=5 epoch=10 loss=15.6993 val_auc=0.5340
model=gat top_k=200 fold=5 epoch=11 loss=21.0205 val_auc=0.5521
model=gat top_k=200 fold=5 epoch=12 loss=19.5783 val_auc=0.7493
model=gat top_k=200 fold=5 epoch=13 loss=14.6422 val_auc=0.7549
model=gat top_k=200 fold=5 epoch=14 loss=9.8933 val_auc=0.7562
model=gat top_k=200 fold=5 epoch=15 loss=13.6625 val_auc=0.7612
model=gat top_k=200 fold=5 epoch=16 loss=12.8184 val_auc=0.7680
model=gat top_k=200 fold=5 epoch=17 loss=9.4662 val_auc=0.7719
model=gat top_k=200 fold=5 epoch=18 loss=9.9372 val_auc=0.7745
model=gat top_k=200 fold=5 epoch=19 loss=6.8023 val_auc=0.7737
model=gat top_k=200 fold=5 epoch=20 loss=10.5375 val_auc=0.7751
model=gat top_k=200 fold=5 epoch=21 loss=10.0288 val_auc=0.7772
model=gat top_k=200 fold=5 epoch=22 loss=14.5539 val_auc=0.7788
model=gat top_k=200 fold=5 epoch=23 loss=10.7535 val_auc=0.7831
model=gat top_k=200 fold=5 epoch=24 loss=7.6077 val_auc=0.7861
model=gat top_k=200 fold=5 epoch=25 loss=6.7030 val_auc=0.7887
model=gat top_k=200 fold=5 epoch=26 loss=6.3982 val_auc=0.7920
model=gat top_k=200 fold=5 epoch=27 loss=7.0069 val_auc=0.7958
model=gat top_k=200 fold=5 epoch=28 loss=8.6352 val_auc=0.7993
model=gat top_k=200 fold=5 epoch=29 loss=6.0068 val_auc=0.8017
model=gat top_k=200 fold=5 epoch=30 loss=5.7199 val_auc=0.8030
model=gat top_k=200 fold=5 epoch=31 loss=6.4736 val_auc=0.8035
model=gat top_k=200 fold=5 epoch=32 loss=6.4102 val_auc=0.8036
model=gat top_k=200 fold=5 epoch=33 loss=6.8326 val_auc=0.8039
model=gat top_k=200 fold=5 epoch=34 loss=5.4934 val_auc=0.8039
model=gat top_k=200 fold=5 epoch=35 loss=6.0691 val_auc=0.8036
model=gat top_k=200 fold=5 epoch=36 loss=6.1983 val_auc=0.8034
model=gat top_k=200 fold=5 epoch=37 loss=6.3056 val_auc=0.8041
model=gat top_k=200 fold=5 epoch=38 loss=4.9014 val_auc=0.8049
model=gat top_k=200 fold=5 epoch=39 loss=4.9190 val_auc=0.8050
model=gat top_k=200 fold=5 epoch=40 loss=6.1619 val_auc=0.8046
model=gat top_k=200 fold=5 epoch=41 loss=6.3869 val_auc=0.8048
model=gat top_k=200 fold=5 epoch=42 loss=5.7588 val_auc=0.8037
model=gat top_k=200 fold=5 epoch=43 loss=4.1384 val_auc=0.8014
model=gat top_k=200 fold=5 epoch=44 loss=5.4004 val_auc=0.7982
model=gat top_k=200 fold=5 epoch=45 loss=8.5628 val_auc=0.7950
model=gat top_k=200 fold=5 epoch=46 loss=8.8716 val_auc=0.7920
model=gat top_k=200 fold=5 epoch=47 loss=6.2673 val_auc=0.7895
model=gat top_k=200 fold=5 epoch=48 loss=4.8923 val_auc=0.7837
model=gat top_k=200 fold=5 epoch=49 loss=5.2861 val_auc=0.7794
model=gat top_k=200 fold=5 epoch=50 loss=6.7131 val_auc=0.7740
model=gat top_k=200 fold=5 epoch=51 loss=6.8384 val_auc=0.7765
gat top_k=200 fold=5: early stopping at epoch 51
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782265 edges

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=200 fold=6 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 781867 edges

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=200 fold=6 epoch=0 loss=26.6921 val_auc=0.6246
model=gat top_k=200 fold=6 epoch=1 loss=52.3715 val_auc=0.5132
model=gat top_k=200 fold=6 epoch=2 loss=26.8394 val_auc=0.5859
model=gat top_k=200 fold=6 epoch=3 loss=17.7934 val_auc=0.6860
model=gat top_k=200 fold=6 epoch=4 loss=17.2699 val_auc=0.6984
model=gat top_k=200 fold=6 epoch=5 loss=14.4986 val_auc=0.7079
model=gat top_k=200 fold=6 epoch=6 loss=10.6201 val_auc=0.7207
model=gat top_k=200 fold=6 epoch=7 loss=11.1409 val_auc=0.7392
model=gat top_k=200 fold=6 epoch=8 loss=7.7535 val_auc=0.7540
model=gat top_k=200 fold=6 epoch=9 loss=7.9373 val_auc=0.7709
model=gat top_k=200 fold=6 epoch=10 loss=8.0470 val_auc=0.7766
model=gat top_k=200 fold=6 epoch=11 loss=7.7757 val_auc=0.7456
model=gat top_k=200 fold=6 epoch=12 loss=11.8838 val_auc=0.7929
model=gat top_k=200 fold=6 epoch=13 loss=9.0097 val_auc=0.7931
model=gat top_k=200 fold=6 epoch=14 loss=7.2358 val_auc=0.7948
model=gat top_k=200 fold=6 epoch=15 loss=13.0823 val_auc=0.7972
model=gat top_k=200 fold=6 epoch=16 loss=12.1258 val_auc=0.7967
model=gat top_k=200 fold=6 epoch=17 loss=7.7103 val_auc=0.7952
model=gat top_k=200 fold=6 epoch=18 loss=7.2666 val_auc=0.7900
model=gat top_k=200 fold=6 epoch=19 loss=10.0938 val_auc=0.7934
model=gat top_k=200 fold=6 epoch=20 loss=13.4009 val_auc=0.7947
model=gat top_k=200 fold=6 epoch=21 loss=8.6963 val_auc=0.7947
model=gat top_k=200 fold=6 epoch=22 loss=9.2859 val_auc=0.7945
model=gat top_k=200 fold=6 epoch=23 loss=8.4826 val_auc=0.7934
model=gat top_k=200 fold=6 epoch=24 loss=5.9181 val_auc=0.7921
model=gat top_k=200 fold=6 epoch=25 loss=5.5735 val_auc=0.7905
model=gat top_k=200 fold=6 epoch=26 loss=7.8562 val_auc=0.7876
model=gat top_k=200 fold=6 epoch=27 loss=7.3278 val_auc=0.7882
gat top_k=200 fold=6: early stopping at epoch 27
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 781867 edges

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=200 fold=7 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782278 edges

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=200 fold=7 epoch=0 loss=23.8732 val_auc=0.4695
model=gat top_k=200 fold=7 epoch=1 loss=64.7214 val_auc=0.4912
model=gat top_k=200 fold=7 epoch=2 loss=15.6589 val_auc=0.6015
model=gat top_k=200 fold=7 epoch=3 loss=12.4597 val_auc=0.6869
model=gat top_k=200 fold=7 epoch=4 loss=17.5443 val_auc=0.7192
model=gat top_k=200 fold=7 epoch=5 loss=11.1008 val_auc=0.5510
model=gat top_k=200 fold=7 epoch=6 loss=18.7782 val_auc=0.6574
model=gat top_k=200 fold=7 epoch=7 loss=14.3811 val_auc=0.7645
model=gat top_k=200 fold=7 epoch=8 loss=11.2668 val_auc=0.7722
model=gat top_k=200 fold=7 epoch=9 loss=11.5593 val_auc=0.7750
model=gat top_k=200 fold=7 epoch=10 loss=16.2731 val_auc=0.7736
model=gat top_k=200 fold=7 epoch=11 loss=7.2276 val_auc=0.7517
model=gat top_k=200 fold=7 epoch=12 loss=13.9960 val_auc=0.7224
model=gat top_k=200 fold=7 epoch=13 loss=11.0703 val_auc=0.7764
model=gat top_k=200 fold=7 epoch=14 loss=7.9146 val_auc=0.7733
model=gat top_k=200 fold=7 epoch=15 loss=8.0399 val_auc=0.7678
model=gat top_k=200 fold=7 epoch=16 loss=8.5237 val_auc=0.7669
model=gat top_k=200 fold=7 epoch=17 loss=8.2860 val_auc=0.7678
model=gat top_k=200 fold=7 epoch=18 loss=6.5521 val_auc=0.7697
model=gat top_k=200 fold=7 epoch=19 loss=6.9106 val_auc=0.7746
model=gat top_k=200 fold=7 epoch=20 loss=6.4437 val_auc=0.7829
model=gat top_k=200 fold=7 epoch=21 loss=5.8687 val_auc=0.7880
model=gat top_k=200 fold=7 epoch=22 loss=5.7535 val_auc=0.7905
model=gat top_k=200 fold=7 epoch=23 loss=6.3569 val_auc=0.7924
model=gat top_k=200 fold=7 epoch=24 loss=5.7403 val_auc=0.7923
model=gat top_k=200 fold=7 epoch=25 loss=5.8388 val_auc=0.7913
model=gat top_k=200 fold=7 epoch=26 loss=6.2697 val_auc=0.7913
model=gat top_k=200 fold=7 epoch=27 loss=5.9791 val_auc=0.7922
model=gat top_k=200 fold=7 epoch=28 loss=7.1354 val_auc=0.7940
model=gat top_k=200 fold=7 epoch=29 loss=5.3632 val_auc=0.7958
model=gat top_k=200 fold=7 epoch=30 loss=5.4645 val_auc=0.7988
model=gat top_k=200 fold=7 epoch=31 loss=6.2876 val_auc=0.8024
model=gat top_k=200 fold=7 epoch=32 loss=5.8464 val_auc=0.8042
model=gat top_k=200 fold=7 epoch=33 loss=6.6860 val_auc=0.8035
model=gat top_k=200 fold=7 epoch=34 loss=5.1275 val_auc=0.8029
model=gat top_k=200 fold=7 epoch=35 loss=9.3887 val_auc=0.8024
model=gat top_k=200 fold=7 epoch=36 loss=10.5968 val_auc=0.8035
model=gat top_k=200 fold=7 epoch=37 loss=5.1679 val_auc=0.8056
model=gat top_k=200 fold=7 epoch=38 loss=7.4853 val_auc=0.8069
model=gat top_k=200 fold=7 epoch=39 loss=7.9681 val_auc=0.8052
model=gat top_k=200 fold=7 epoch=40 loss=8.6446 val_auc=0.8073
model=gat top_k=200 fold=7 epoch=41 loss=6.2038 val_auc=0.8069
model=gat top_k=200 fold=7 epoch=42 loss=5.0394 val_auc=0.8069
model=gat top_k=200 fold=7 epoch=43 loss=8.2082 val_auc=0.8069
model=gat top_k=200 fold=7 epoch=44 loss=8.2373 val_auc=0.8070
model=gat top_k=200 fold=7 epoch=45 loss=7.4431 val_auc=0.8073
model=gat top_k=200 fold=7 epoch=46 loss=5.0987 val_auc=0.8077
model=gat top_k=200 fold=7 epoch=47 loss=5.1434 val_auc=0.8068
model=gat top_k=200 fold=7 epoch=48 loss=6.9844 val_auc=0.8094
model=gat top_k=200 fold=7 epoch=49 loss=6.1712 val_auc=0.8099
model=gat top_k=200 fold=7 epoch=50 loss=4.4118 val_auc=0.8110
model=gat top_k=200 fold=7 epoch=51 loss=5.9307 val_auc=0.8117
model=gat top_k=200 fold=7 epoch=52 loss=7.6612 val_auc=0.8119
model=gat top_k=200 fold=7 epoch=53 loss=8.5996 val_auc=0.8115
model=gat top_k=200 fold=7 epoch=54 loss=4.8882 val_auc=0.8107
model=gat top_k=200 fold=7 epoch=55 loss=3.9104 val_auc=0.7948
model=gat top_k=200 fold=7 epoch=56 loss=9.6347 val_auc=0.7894
model=gat top_k=200 fold=7 epoch=57 loss=11.1126 val_auc=0.8065
model=gat top_k=200 fold=7 epoch=58 loss=7.6457 val_auc=0.8072
model=gat top_k=200 fold=7 epoch=59 loss=5.0641 val_auc=0.8035
model=gat top_k=200 fold=7 epoch=60 loss=5.7326 val_auc=0.7972
model=gat top_k=200 fold=7 epoch=61 loss=7.3923 val_auc=0.7911
model=gat top_k=200 fold=7 epoch=62 loss=7.1418 val_auc=0.7902
model=gat top_k=200 fold=7 epoch=63 loss=5.6065 val_auc=0.7908
model=gat top_k=200 fold=7 epoch=64 loss=3.7861 val_auc=0.7948
gat top_k=200 fold=7: early stopping at epoch 64
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782278 edges

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=200 fold=8 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782047 edges
model=gat top_k=200 fold=8 epoch=0 loss=16.8982 val_auc=0.5000
model=gat top_k=200 fold=8 epoch=1 loss=127.2687 val_auc=0.4871
model=gat top_k=200 fold=8 epoch=2 loss=27.0270 val_auc=0.5748
model=gat top_k=200 fold=8 epoch=3 loss=45.7425 val_auc=0.6097
model=gat top_k=200 fold=8 epoch=4 loss=35.6958 val_auc=0.6694
model=gat top_k=200 fold=8 epoch=5 loss=16.6645 val_auc=0.4879
model=gat top_k=200 fold=8 epoch=6 loss=23.8870 val_auc=0.5024
model=gat top_k=200 fold=8 epoch=7 loss=32.8826 val_auc=0.5064
model=gat top_k=200 fold=8 epoch=8 loss=20.9467 val_auc=0.7301
model=gat top_k=200 fold=8 epoch=9 loss=9.8767 val_auc=0.7336
model=gat top_k=200 fold=8 epoch=10 loss=13.5785 val_auc=0.7368
model=gat top_k=200 fold=8 epoch=11 loss=16.5533 val_auc=0.7396
model=gat top_k=200 fold=8 epoch=12 loss=12.7912 val_auc=0.7416
model=gat top_k=200 fold=8 epoch=13 loss=8.1446 val_auc=0.7418
model=gat top_k=200 fold=8 epoch=14 loss=9.9041 val_auc=0.7416
model=gat top_k=200 fold=8 epoch=15 loss=13.2484 val_auc=0.7508
model=gat top_k=200 fold=8 epoch=16 loss=11.9351 val_auc=0.7596
model=gat top_k=200 fold=8 epoch=17 loss=10.7191 val_auc=0.7620
model=gat top_k=200 fold=8 epoch=18 loss=9.1128 val_auc=0.7655
model=gat top_k=200 fold=8 epoch=19 loss=9.8987 val_auc=0.7681
model=gat top_k=200 fold=8 epoch=20 loss=7.6697 val_auc=0.7699
model=gat top_k=200 fold=8 epoch=21 loss=9.3073 val_auc=0.7694
model=gat top_k=200 fold=8 epoch=22 loss=10.6929 val_auc=0.7715
model=gat top_k=200 fold=8 epoch=23 loss=10.5644 val_auc=0.7781
model=gat top_k=200 fold=8 epoch=24 loss=6.8981 val_auc=0.7800
model=gat top_k=200 fold=8 epoch=25 loss=7.2281 val_auc=0.7819
model=gat top_k=200 fold=8 epoch=26 loss=7.4898 val_auc=0.7832
model=gat top_k=200 fold=8 epoch=27 loss=7.3686 val_auc=0.7843
model=gat top_k=200 fold=8 epoch=28 loss=5.3310 val_auc=0.7849
model=gat top_k=200 fold=8 epoch=29 loss=5.9193 val_auc=0.7861
model=gat top_k=200 fold=8 epoch=30 loss=5.8390 val_auc=0.7871
model=gat top_k=200 fold=8 epoch=31 loss=6.6393 val_auc=0.7880
model=gat top_k=200 fold=8 epoch=32 loss=5.6934 val_auc=0.7887
model=gat top_k=200 fold=8 epoch=33 loss=6.0242 val_auc=0.7891
model=gat top_k=200 fold=8 epoch=34 loss=6.1716 val_auc=0.7898
model=gat top_k=200 fold=8 epoch=35 loss=6.2753 val_auc=0.7907
model=gat top_k=200 fold=8 epoch=36 loss=4.6820 val_auc=0.7908
model=gat top_k=200 fold=8 epoch=37 loss=5.5853 val_auc=0.7908
model=gat top_k=200 fold=8 epoch=38 loss=6.6860 val_auc=0.7906
model=gat top_k=200 fold=8 epoch=39 loss=6.9929 val_auc=0.7916
model=gat top_k=200 fold=8 epoch=40 loss=5.2295 val_auc=0.7922
model=gat top_k=200 fold=8 epoch=41 loss=6.5683 val_auc=0.7927
model=gat top_k=200 fold=8 epoch=42 loss=5.3047 val_auc=0.7935
model=gat top_k=200 fold=8 epoch=43 loss=4.2634 val_auc=0.7947
model=gat top_k=200 fold=8 epoch=44 loss=5.3285 val_auc=0.7955
model=gat top_k=200 fold=8 epoch=45 loss=5.6182 val_auc=0.7957
model=gat top_k=200 fold=8 epoch=46 loss=5.0254 val_auc=0.7961
model=gat top_k=200 fold=8 epoch=47 loss=4.4717 val_auc=0.7965
model=gat top_k=200 fold=8 epoch=48 loss=4.6002 val_auc=0.7969
model=gat top_k=200 fold=8 epoch=49 loss=4.5705 val_auc=0.7973
model=gat top_k=200 fold=8 epoch=50 loss=5.4908 val_auc=0.7975
model=gat top_k=200 fold=8 epoch=51 loss=5.4821 val_auc=0.7977
model=gat top_k=200 fold=8 epoch=52 loss=4.5815 val_auc=0.7981
model=gat top_k=200 fold=8 epoch=53 loss=5.5798 val_auc=0.7982
model=gat top_k=200 fold=8 epoch=54 loss=4.0479 val_auc=0.7985
model=gat top_k=200 fold=8 epoch=55 loss=3.9842 val_auc=0.7992
model=gat top_k=200 fold=8 epoch=56 loss=4.6108 val_auc=0.7996
model=gat top_k=200 fold=8 epoch=57 loss=4.0930 val_auc=0.7993
model=gat top_k=200 fold=8 epoch=58 loss=4.2695 val_auc=0.7988
model=gat top_k=200 fold=8 epoch=59 loss=3.5918 val_auc=0.8013
model=gat top_k=200 fold=8 epoch=60 loss=3.7333 val_auc=0.8025
model=gat top_k=200 fold=8 epoch=61 loss=4.6195 val_auc=0.8029
model=gat top_k=200 fold=8 epoch=62 loss=4.0199 val_auc=0.8021
model=gat top_k=200 fold=8 epoch=63 loss=4.4101 val_auc=0.7962
model=gat top_k=200 fold=8 epoch=64 loss=3.6587 val_auc=0.7924
model=gat top_k=200 fold=8 epoch=65 loss=3.8676 val_auc=0.7935
model=gat top_k=200 fold=8 epoch=66 loss=3.6525 val_auc=0.7982
model=gat top_k=200 fold=8 epoch=67 loss=3.4265 val_auc=0.8013
model=gat top_k=200 fold=8 epoch=68 loss=3.7451 val_auc=0.8021
model=gat top_k=200 fold=8 epoch=69 loss=3.2791 val_auc=0.8012
model=gat top_k=200 fold=8 epoch=70 loss=3.3082 val_auc=0.7985
model=gat top_k=200 fold=8 epoch=71 loss=3.2342 val_auc=0.8008
model=gat top_k=200 fold=8 epoch=72 loss=3.1405 val_auc=0.8032
model=gat top_k=200 fold=8 epoch=73 loss=4.4226 val_auc=0.8037
model=gat top_k=200 fold=8 epoch=74 loss=3.2736 val_auc=0.8023
model=gat top_k=200 fold=8 epoch=75 loss=2.9635 val_auc=0.7993
model=gat top_k=200 fold=8 epoch=76 loss=4.7035 val_auc=0.7961
model=gat top_k=200 fold=8 epoch=77 loss=7.9549 val_auc=0.7937
model=gat top_k=200 fold=8 epoch=78 loss=6.9759 val_auc=0.7926
model=gat top_k=200 fold=8 epoch=79 loss=3.4272 val_auc=0.7933
model=gat top_k=200 fold=8 epoch=80 loss=2.9890 val_auc=0.7954
model=gat top_k=200 fold=8 epoch=81 loss=4.6109 val_auc=0.7987
model=gat top_k=200 fold=8 epoch=82 loss=3.2691 val_auc=0.8002
model=gat top_k=200 fold=8 epoch=83 loss=3.2211 val_auc=0.8018
model=gat top_k=200 fold=8 epoch=84 loss=2.5840 val_auc=0.8042
model=gat top_k=200 fold=8 epoch=85 loss=2.7346 val_auc=0.8063
model=gat top_k=200 fold=8 epoch=86 loss=2.8921 val_auc=0.8091
model=gat top_k=200 fold=8 epoch=87 loss=3.2394 val_auc=0.8115
model=gat top_k=200 fold=8 epoch=88 loss=2.7676 val_auc=0.8132
model=gat top_k=200 fold=8 epoch=89 loss=3.4690 val_auc=0.8139
model=gat top_k=200 fold=8 epoch=90 loss=3.6954 val_auc=0.8140
model=gat top_k=200 fold=8 epoch=91 loss=2.5561 val_auc=0.8138
model=gat top_k=200 fold=8 epoch=92 loss=2.7094 val_auc=0.8138
model=gat top_k=200 fold=8 epoch=93 loss=2.4204 val_auc=0.8138
model=gat top_k=200 fold=8 epoch=94 loss=2.7180 val_auc=0.8141
model=gat top_k=200 fold=8 epoch=95 loss=2.5567 val_auc=0.8142
model=gat top_k=200 fold=8 epoch=96 loss=2.5237 val_auc=0.8141
model=gat top_k=200 fold=8 epoch=97 loss=2.4481 val_auc=0.8142
model=gat top_k=200 fold=8 epoch=98 loss=2.1499 val_auc=0.8145
model=gat top_k=200 fold=8 epoch=99 loss=2.4606 val_auc=0.8145
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782047 edges

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=200 fold=9 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 781970 edges

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=200 fold=9 epoch=0 loss=16.6131 val_auc=0.5220
model=gat top_k=200 fold=9 epoch=1 loss=84.4694 val_auc=0.6827
model=gat top_k=200 fold=9 epoch=2 loss=13.1903 val_auc=0.5202
model=gat top_k=200 fold=9 epoch=3 loss=57.9383 val_auc=0.5255
model=gat top_k=200 fold=9 epoch=4 loss=53.1151 val_auc=0.5577
model=gat top_k=200 fold=9 epoch=5 loss=21.9195 val_auc=0.7244
model=gat top_k=200 fold=9 epoch=6 loss=19.8347 val_auc=0.7283
model=gat top_k=200 fold=9 epoch=7 loss=23.7176 val_auc=0.7334
model=gat top_k=200 fold=9 epoch=8 loss=17.9146 val_auc=0.7391
model=gat top_k=200 fold=9 epoch=9 loss=12.7698 val_auc=0.7407
model=gat top_k=200 fold=9 epoch=10 loss=12.7763 val_auc=0.6076
model=gat top_k=200 fold=9 epoch=11 loss=16.6362 val_auc=0.5921
model=gat top_k=200 fold=9 epoch=12 loss=16.2810 val_auc=0.7402
model=gat top_k=200 fold=9 epoch=13 loss=11.4953 val_auc=0.7386
model=gat top_k=200 fold=9 epoch=14 loss=8.6965 val_auc=0.7400
model=gat top_k=200 fold=9 epoch=15 loss=7.9340 val_auc=0.7410
model=gat top_k=200 fold=9 epoch=16 loss=12.0957 val_auc=0.7435
model=gat top_k=200 fold=9 epoch=17 loss=11.9583 val_auc=0.7461
model=gat top_k=200 fold=9 epoch=18 loss=7.6770 val_auc=0.7466
model=gat top_k=200 fold=9 epoch=19 loss=8.9645 val_auc=0.7470
model=gat top_k=200 fold=9 epoch=20 loss=9.8160 val_auc=0.7480
model=gat top_k=200 fold=9 epoch=21 loss=8.1949 val_auc=0.7479
model=gat top_k=200 fold=9 epoch=22 loss=6.0850 val_auc=0.7444
model=gat top_k=200 fold=9 epoch=23 loss=7.0693 val_auc=0.7400
model=gat top_k=200 fold=9 epoch=24 loss=6.4882 val_auc=0.7387
model=gat top_k=200 fold=9 epoch=25 loss=5.4040 val_auc=0.7471
model=gat top_k=200 fold=9 epoch=26 loss=7.7215 val_auc=0.7564
model=gat top_k=200 fold=9 epoch=27 loss=5.5859 val_auc=0.7689
model=gat top_k=200 fold=9 epoch=28 loss=5.4202 val_auc=0.7745
model=gat top_k=200 fold=9 epoch=29 loss=5.9251 val_auc=0.7756
model=gat top_k=200 fold=9 epoch=30 loss=7.6739 val_auc=0.7831
model=gat top_k=200 fold=9 epoch=31 loss=7.1073 val_auc=0.7843
model=gat top_k=200 fold=9 epoch=32 loss=5.3882 val_auc=0.7824
model=gat top_k=200 fold=9 epoch=33 loss=7.4819 val_auc=0.7828
model=gat top_k=200 fold=9 epoch=34 loss=9.3657 val_auc=0.7831
model=gat top_k=200 fold=9 epoch=35 loss=4.9127 val_auc=0.7850
model=gat top_k=200 fold=9 epoch=36 loss=5.6725 val_auc=0.7856
model=gat top_k=200 fold=9 epoch=37 loss=6.9455 val_auc=0.7857
model=gat top_k=200 fold=9 epoch=38 loss=5.1855 val_auc=0.7871
model=gat top_k=200 fold=9 epoch=39 loss=7.9675 val_auc=0.7869
model=gat top_k=200 fold=9 epoch=40 loss=4.8096 val_auc=0.7865
model=gat top_k=200 fold=9 epoch=41 loss=6.2036 val_auc=0.7878
model=gat top_k=200 fold=9 epoch=42 loss=6.2658 val_auc=0.7858
model=gat top_k=200 fold=9 epoch=43 loss=4.8876 val_auc=0.7698
model=gat top_k=200 fold=9 epoch=44 loss=4.2658 val_auc=0.7634
model=gat top_k=200 fold=9 epoch=45 loss=5.7357 val_auc=0.7692
model=gat top_k=200 fold=9 epoch=46 loss=7.2167 val_auc=0.7789
model=gat top_k=200 fold=9 epoch=47 loss=5.4374 val_auc=0.7864
model=gat top_k=200 fold=9 epoch=48 loss=5.4918 val_auc=0.7879
model=gat top_k=200 fold=9 epoch=49 loss=4.2021 val_auc=0.7886
model=gat top_k=200 fold=9 epoch=50 loss=4.2694 val_auc=0.7900
model=gat top_k=200 fold=9 epoch=51 loss=4.2996 val_auc=0.7965
model=gat top_k=200 fold=9 epoch=52 loss=3.9602 val_auc=0.7997
model=gat top_k=200 fold=9 epoch=53 loss=4.5209 val_auc=0.8022
model=gat top_k=200 fold=9 epoch=54 loss=4.2368 val_auc=0.8041
model=gat top_k=200 fold=9 epoch=55 loss=3.8290 val_auc=0.8060
model=gat top_k=200 fold=9 epoch=56 loss=4.3629 val_auc=0.8077
model=gat top_k=200 fold=9 epoch=57 loss=3.7613 val_auc=0.8080
model=gat top_k=200 fold=9 epoch=58 loss=3.5744 val_auc=0.8079
model=gat top_k=200 fold=9 epoch=59 loss=3.7782 val_auc=0.8098
model=gat top_k=200 fold=9 epoch=60 loss=3.4601 val_auc=0.8105
model=gat top_k=200 fold=9 epoch=61 loss=4.1373 val_auc=0.8100
model=gat top_k=200 fold=9 epoch=62 loss=3.3757 val_auc=0.8106
model=gat top_k=200 fold=9 epoch=63 loss=3.0670 val_auc=0.8114
model=gat top_k=200 fold=9 epoch=64 loss=3.4048 val_auc=0.8107
model=gat top_k=200 fold=9 epoch=65 loss=3.1404 val_auc=0.8089
model=gat top_k=200 fold=9 epoch=66 loss=3.7177 val_auc=0.8086
model=gat top_k=200 fold=9 epoch=67 loss=4.3573 val_auc=0.8060
model=gat top_k=200 fold=9 epoch=68 loss=4.2936 val_auc=0.8092
model=gat top_k=200 fold=9 epoch=69 loss=3.4429 val_auc=0.8122
model=gat top_k=200 fold=9 epoch=70 loss=3.1170 val_auc=0.8158
model=gat top_k=200 fold=9 epoch=71 loss=2.9883 val_auc=0.8195
model=gat top_k=200 fold=9 epoch=72 loss=3.1469 val_auc=0.8219
model=gat top_k=200 fold=9 epoch=73 loss=3.1431 val_auc=0.8227
model=gat top_k=200 fold=9 epoch=74 loss=2.7686 val_auc=0.8235
model=gat top_k=200 fold=9 epoch=75 loss=3.2971 val_auc=0.8229
model=gat top_k=200 fold=9 epoch=76 loss=3.3049 val_auc=0.8200
model=gat top_k=200 fold=9 epoch=77 loss=3.0373 val_auc=0.8149
model=gat top_k=200 fold=9 epoch=78 loss=2.5929 val_auc=0.8137
model=gat top_k=200 fold=9 epoch=79 loss=3.0493 val_auc=0.8153
model=gat top_k=200 fold=9 epoch=80 loss=2.9263 val_auc=0.8156
model=gat top_k=200 fold=9 epoch=81 loss=3.3137 val_auc=0.8179
model=gat top_k=200 fold=9 epoch=82 loss=2.6945 val_auc=0.8177
model=gat top_k=200 fold=9 epoch=83 loss=3.0657 val_auc=0.8169
model=gat top_k=200 fold=9 epoch=84 loss=3.2569 val_auc=0.8174
model=gat top_k=200 fold=9 epoch=85 loss=2.8341 val_auc=0.8174
model=gat top_k=200 fold=9 epoch=86 loss=2.4364 val_auc=0.8182
gat top_k=200 fold=9: early stopping at epoch 86
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 781970 edges

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/35 [00:00<?, ?it/s]

######## Model=gat top_k=500 ########

===== Model=gat top_k=500 fold=0 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782165 edges

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=500 fold=0 epoch=0 loss=15.7353 val_auc=0.5004
model=gat top_k=500 fold=0 epoch=1 loss=75.0544 val_auc=0.5863
model=gat top_k=500 fold=0 epoch=2 loss=13.3359 val_auc=0.4829
model=gat top_k=500 fold=0 epoch=3 loss=27.2620 val_auc=0.6900
model=gat top_k=500 fold=0 epoch=4 loss=13.0673 val_auc=0.7059
model=gat top_k=500 fold=0 epoch=5 loss=9.0688 val_auc=0.6815
model=gat top_k=500 fold=0 epoch=6 loss=11.5473 val_auc=0.7124
model=gat top_k=500 fold=0 epoch=7 loss=11.8283 val_auc=0.7332
model=gat top_k=500 fold=0 epoch=8 loss=11.0421 val_auc=0.7520
model=gat top_k=500 fold=0 epoch=9 loss=8.0449 val_auc=0.7404
model=gat top_k=500 fold=0 epoch=10 loss=6.9409 val_auc=0.7410
model=gat top_k=500 fold=0 epoch=11 loss=6.9513 val_auc=0.7287
model=gat top_k=500 fold=0 epoch=12 loss=11.6363 val_auc=0.7522
model=gat top_k=500 fold=0 epoch=13 loss=6.0385 val_auc=0.7581
model=gat top_k=500 fold=0 epoch=14 loss=7.3967 val_auc=0.7628
model=gat top_k=500 fold=0 epoch=15 loss=8.5816 val_auc=0.7668
model=gat top_k=500 fold=0 epoch=16 loss=7.8554 val_auc=0.7792
model=gat top_k=500 fold=0 epoch=17 loss=6.9850 val_auc=0.7927
model=gat top_k=500 fold=0 epoch=18 loss=6.5501 val_auc=0.7948
model=gat top_k=500 fold=0 epoch=19 loss=6.3409 val_auc=0.7960
model=gat top_k=500 fold=0 epoch=20 loss=6.0410 val_auc=0.7958
model=gat top_k=500 fold=0 epoch=21 loss=7.2185 val_auc=0.7958
model=gat top_k=500 fold=0 epoch=22 loss=6.0739 val_auc=0.7957
model=gat top_k=500 fold=0 epoch=23 loss=6.4321 val_auc=0.7915
model=gat top_k=500 fold=0 epoch=24 loss=7.3635 val_auc=0.7831
model=gat top_k=500 fold=0 epoch=25 loss=10.7106 val_auc=0.7923
model=gat top_k=500 fold=0 epoch=26 loss=8.0315 val_auc=0.7955
model=gat top_k=500 fold=0 epoch=27 loss=5.8186 val_auc=0.7967
model=gat top_k=500 fold=0 epoch=28 loss=7.2584 val_auc=0.7972
model=gat top_k=500 fold=0 epoch=29 loss=8.8714 val_auc=0.7977
model=gat top_k=500 fold=0 epoch=30 loss=7.0975 val_auc=0.7957
model=gat top_k=500 fold=0 epoch=31 loss=6.8735 val_auc=0.7956
model=gat top_k=500 fold=0 epoch=32 loss=7.9945 val_auc=0.7987
model=gat top_k=500 fold=0 epoch=33 loss=4.8430 val_auc=0.7985
model=gat top_k=500 fold=0 epoch=34 loss=5.2249 val_auc=0.7985
model=gat top_k=500 fold=0 epoch=35 loss=4.5995 val_auc=0.7982
model=gat top_k=500 fold=0 epoch=36 loss=6.0601 val_auc=0.7983
model=gat top_k=500 fold=0 epoch=37 loss=5.4435 val_auc=0.7990
model=gat top_k=500 fold=0 epoch=38 loss=4.3610 val_auc=0.8007
model=gat top_k=500 fold=0 epoch=39 loss=4.5583 val_auc=0.8026
model=gat top_k=500 fold=0 epoch=40 loss=4.7105 val_auc=0.8043
model=gat top_k=500 fold=0 epoch=41 loss=4.1398 val_auc=0.8050
model=gat top_k=500 fold=0 epoch=42 loss=3.7768 val_auc=0.8059
model=gat top_k=500 fold=0 epoch=43 loss=4.0608 val_auc=0.8069
model=gat top_k=500 fold=0 epoch=44 loss=3.8516 val_auc=0.8071
model=gat top_k=500 fold=0 epoch=45 loss=4.1568 val_auc=0.8058
model=gat top_k=500 fold=0 epoch=46 loss=4.5374 val_auc=0.8042
model=gat top_k=500 fold=0 epoch=47 loss=4.2268 val_auc=0.8032
model=gat top_k=500 fold=0 epoch=48 loss=3.6201 val_auc=0.8031
model=gat top_k=500 fold=0 epoch=49 loss=3.9904 val_auc=0.8070
model=gat top_k=500 fold=0 epoch=50 loss=3.5122 val_auc=0.8081
model=gat top_k=500 fold=0 epoch=51 loss=3.9500 val_auc=0.8084
model=gat top_k=500 fold=0 epoch=52 loss=3.4462 val_auc=0.8064
model=gat top_k=500 fold=0 epoch=53 loss=5.6921 val_auc=0.8026
model=gat top_k=500 fold=0 epoch=54 loss=4.9342 val_auc=0.8017
model=gat top_k=500 fold=0 epoch=55 loss=3.6767 val_auc=0.8054
model=gat top_k=500 fold=0 epoch=56 loss=4.4081 val_auc=0.8045
model=gat top_k=500 fold=0 epoch=57 loss=4.7151 val_auc=0.8102
model=gat top_k=500 fold=0 epoch=58 loss=3.7188 val_auc=0.8121
model=gat top_k=500 fold=0 epoch=59 loss=3.3309 val_auc=0.8117
model=gat top_k=500 fold=0 epoch=60 loss=3.7839 val_auc=0.8132
model=gat top_k=500 fold=0 epoch=61 loss=5.4447 val_auc=0.8156
model=gat top_k=500 fold=0 epoch=62 loss=3.9772 val_auc=0.8171
model=gat top_k=500 fold=0 epoch=63 loss=3.4936 val_auc=0.8177
model=gat top_k=500 fold=0 epoch=64 loss=3.6993 val_auc=0.8173
model=gat top_k=500 fold=0 epoch=65 loss=4.0672 val_auc=0.8174
model=gat top_k=500 fold=0 epoch=66 loss=3.1213 val_auc=0.8183
model=gat top_k=500 fold=0 epoch=67 loss=3.5599 val_auc=0.8189
model=gat top_k=500 fold=0 epoch=68 loss=3.0247 val_auc=0.8197
model=gat top_k=500 fold=0 epoch=69 loss=3.7790 val_auc=0.8202
model=gat top_k=500 fold=0 epoch=70 loss=4.0912 val_auc=0.8200
model=gat top_k=500 fold=0 epoch=71 loss=2.7952 val_auc=0.8201
model=gat top_k=500 fold=0 epoch=72 loss=2.7514 val_auc=0.8206
model=gat top_k=500 fold=0 epoch=73 loss=3.3032 val_auc=0.8206
model=gat top_k=500 fold=0 epoch=74 loss=3.8993 val_auc=0.8204
model=gat top_k=500 fold=0 epoch=75 loss=4.3335 val_auc=0.8205
model=gat top_k=500 fold=0 epoch=76 loss=3.2819 val_auc=0.8197
model=gat top_k=500 fold=0 epoch=77 loss=3.2058 val_auc=0.8196
model=gat top_k=500 fold=0 epoch=78 loss=3.5714 val_auc=0.8193
model=gat top_k=500 fold=0 epoch=79 loss=3.3488 val_auc=0.8189
model=gat top_k=500 fold=0 epoch=80 loss=2.8909 val_auc=0.8193
model=gat top_k=500 fold=0 epoch=81 loss=3.1623 val_auc=0.8194
model=gat top_k=500 fold=0 epoch=82 loss=3.9328 val_auc=0.8195
model=gat top_k=500 fold=0 epoch=83 loss=2.8984 val_auc=0.8193
model=gat top_k=500 fold=0 epoch=84 loss=2.6371 val_auc=0.8194
model=gat top_k=500 fold=0 epoch=85 loss=3.3202 val_auc=0.8195
gat top_k=500 fold=0: early stopping at epoch 85
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782165 edges

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=500 fold=1 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782386 edges

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=500 fold=1 epoch=0 loss=17.1588 val_auc=0.6364
model=gat top_k=500 fold=1 epoch=1 loss=52.7838 val_auc=0.5901
model=gat top_k=500 fold=1 epoch=2 loss=16.4637 val_auc=0.7338
model=gat top_k=500 fold=1 epoch=3 loss=11.3617 val_auc=0.7320
model=gat top_k=500 fold=1 epoch=4 loss=12.5753 val_auc=0.7690
model=gat top_k=500 fold=1 epoch=5 loss=9.7954 val_auc=0.7750
model=gat top_k=500 fold=1 epoch=6 loss=14.6794 val_auc=0.7793
model=gat top_k=500 fold=1 epoch=7 loss=9.8399 val_auc=0.7819
model=gat top_k=500 fold=1 epoch=8 loss=7.7194 val_auc=0.7745
model=gat top_k=500 fold=1 epoch=9 loss=11.6055 val_auc=0.7836
model=gat top_k=500 fold=1 epoch=10 loss=8.9316 val_auc=0.7882
model=gat top_k=500 fold=1 epoch=11 loss=10.1158 val_auc=0.7902
model=gat top_k=500 fold=1 epoch=12 loss=10.3529 val_auc=0.7920
model=gat top_k=500 fold=1 epoch=13 loss=7.7704 val_auc=0.7924
model=gat top_k=500 fold=1 epoch=14 loss=6.9157 val_auc=0.7854
model=gat top_k=500 fold=1 epoch=15 loss=11.4599 val_auc=0.7886
model=gat top_k=500 fold=1 epoch=16 loss=8.3227 val_auc=0.7941
model=gat top_k=500 fold=1 epoch=17 loss=6.4942 val_auc=0.7971
model=gat top_k=500 fold=1 epoch=18 loss=6.1703 val_auc=0.7992
model=gat top_k=500 fold=1 epoch=19 loss=5.5130 val_auc=0.8013
model=gat top_k=500 fold=1 epoch=20 loss=6.0527 val_auc=0.8035
model=gat top_k=500 fold=1 epoch=21 loss=5.5694 val_auc=0.8057
model=gat top_k=500 fold=1 epoch=22 loss=5.7186 val_auc=0.8083
model=gat top_k=500 fold=1 epoch=23 loss=6.4258 val_auc=0.8090
model=gat top_k=500 fold=1 epoch=24 loss=5.5214 val_auc=0.8097
model=gat top_k=500 fold=1 epoch=25 loss=5.4730 val_auc=0.8109
model=gat top_k=500 fold=1 epoch=26 loss=6.2222 val_auc=0.8119
model=gat top_k=500 fold=1 epoch=27 loss=6.7156 val_auc=0.8110
model=gat top_k=500 fold=1 epoch=28 loss=6.4535 val_auc=0.8123
model=gat top_k=500 fold=1 epoch=29 loss=6.4721 val_auc=0.8106
model=gat top_k=500 fold=1 epoch=30 loss=7.4419 val_auc=0.8108
model=gat top_k=500 fold=1 epoch=31 loss=11.9390 val_auc=0.8118
model=gat top_k=500 fold=1 epoch=32 loss=9.3784 val_auc=0.8120
model=gat top_k=500 fold=1 epoch=33 loss=7.8485 val_auc=0.8085
model=gat top_k=500 fold=1 epoch=34 loss=5.9897 val_auc=0.7922
model=gat top_k=500 fold=1 epoch=35 loss=11.0864 val_auc=0.7783
model=gat top_k=500 fold=1 epoch=36 loss=11.0021 val_auc=0.8009
model=gat top_k=500 fold=1 epoch=37 loss=7.4707 val_auc=0.8104
model=gat top_k=500 fold=1 epoch=38 loss=4.9124 val_auc=0.8109
model=gat top_k=500 fold=1 epoch=39 loss=6.6759 val_auc=0.8116
model=gat top_k=500 fold=1 epoch=40 loss=5.2209 val_auc=0.8134
model=gat top_k=500 fold=1 epoch=41 loss=7.4596 val_auc=0.8156
model=gat top_k=500 fold=1 epoch=42 loss=5.7848 val_auc=0.8179
model=gat top_k=500 fold=1 epoch=43 loss=5.6270 val_auc=0.8196
model=gat top_k=500 fold=1 epoch=44 loss=6.2186 val_auc=0.8214
model=gat top_k=500 fold=1 epoch=45 loss=7.4066 val_auc=0.8226
model=gat top_k=500 fold=1 epoch=46 loss=4.6708 val_auc=0.8232
model=gat top_k=500 fold=1 epoch=47 loss=4.3059 val_auc=0.8231
model=gat top_k=500 fold=1 epoch=48 loss=6.0595 val_auc=0.8232
model=gat top_k=500 fold=1 epoch=49 loss=6.2191 val_auc=0.8228
model=gat top_k=500 fold=1 epoch=50 loss=4.6995 val_auc=0.8212
model=gat top_k=500 fold=1 epoch=51 loss=4.3353 val_auc=0.8203
model=gat top_k=500 fold=1 epoch=52 loss=5.1226 val_auc=0.8198
model=gat top_k=500 fold=1 epoch=53 loss=3.9653 val_auc=0.8211
model=gat top_k=500 fold=1 epoch=54 loss=4.5129 val_auc=0.8230
model=gat top_k=500 fold=1 epoch=55 loss=4.7174 val_auc=0.8241
model=gat top_k=500 fold=1 epoch=56 loss=3.7847 val_auc=0.8250
model=gat top_k=500 fold=1 epoch=57 loss=3.6408 val_auc=0.8247
model=gat top_k=500 fold=1 epoch=58 loss=6.6233 val_auc=0.8250
model=gat top_k=500 fold=1 epoch=59 loss=5.6790 val_auc=0.8273
model=gat top_k=500 fold=1 epoch=60 loss=4.1104 val_auc=0.8273
model=gat top_k=500 fold=1 epoch=61 loss=3.2689 val_auc=0.8283
model=gat top_k=500 fold=1 epoch=62 loss=4.3311 val_auc=0.8295
model=gat top_k=500 fold=1 epoch=63 loss=3.2306 val_auc=0.8298
model=gat top_k=500 fold=1 epoch=64 loss=3.5430 val_auc=0.8288
model=gat top_k=500 fold=1 epoch=65 loss=3.4959 val_auc=0.8298
model=gat top_k=500 fold=1 epoch=66 loss=3.2585 val_auc=0.8318
model=gat top_k=500 fold=1 epoch=67 loss=3.6960 val_auc=0.8325
model=gat top_k=500 fold=1 epoch=68 loss=3.6969 val_auc=0.8327
model=gat top_k=500 fold=1 epoch=69 loss=2.8726 val_auc=0.8334
model=gat top_k=500 fold=1 epoch=70 loss=3.8902 val_auc=0.8341
model=gat top_k=500 fold=1 epoch=71 loss=3.6835 val_auc=0.8343
model=gat top_k=500 fold=1 epoch=72 loss=3.2727 val_auc=0.8361
model=gat top_k=500 fold=1 epoch=73 loss=3.1851 val_auc=0.8370
model=gat top_k=500 fold=1 epoch=74 loss=2.6866 val_auc=0.8372
model=gat top_k=500 fold=1 epoch=75 loss=4.1193 val_auc=0.8369
model=gat top_k=500 fold=1 epoch=76 loss=4.2344 val_auc=0.8373
model=gat top_k=500 fold=1 epoch=77 loss=3.2630 val_auc=0.8379
model=gat top_k=500 fold=1 epoch=78 loss=3.7959 val_auc=0.8383
model=gat top_k=500 fold=1 epoch=79 loss=5.0456 val_auc=0.8385
model=gat top_k=500 fold=1 epoch=80 loss=3.2899 val_auc=0.8391
model=gat top_k=500 fold=1 epoch=81 loss=3.8654 val_auc=0.8401
model=gat top_k=500 fold=1 epoch=82 loss=3.8181 val_auc=0.8399
model=gat top_k=500 fold=1 epoch=83 loss=3.9114 val_auc=0.8378
model=gat top_k=500 fold=1 epoch=84 loss=2.8470 val_auc=0.8354
model=gat top_k=500 fold=1 epoch=85 loss=3.4784 val_auc=0.8339
model=gat top_k=500 fold=1 epoch=86 loss=3.1794 val_auc=0.8344
model=gat top_k=500 fold=1 epoch=87 loss=3.5192 val_auc=0.8360
model=gat top_k=500 fold=1 epoch=88 loss=3.5390 val_auc=0.8370
model=gat top_k=500 fold=1 epoch=89 loss=4.5557 val_auc=0.8372
model=gat top_k=500 fold=1 epoch=90 loss=4.4618 val_auc=0.8360
model=gat top_k=500 fold=1 epoch=91 loss=2.7970 val_auc=0.8339
model=gat top_k=500 fold=1 epoch=92 loss=2.5736 val_auc=0.8346
model=gat top_k=500 fold=1 epoch=93 loss=2.9663 val_auc=0.8361
gat top_k=500 fold=1: early stopping at epoch 93
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782386 edges

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=500 fold=2 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782205 edges
model=gat top_k=500 fold=2 epoch=0 loss=17.6710 val_auc=0.4993
model=gat top_k=500 fold=2 epoch=1 loss=113.2161 val_auc=0.5142
model=gat top_k=500 fold=2 epoch=2 loss=33.8265 val_auc=0.6351
model=gat top_k=500 fold=2 epoch=3 loss=29.9223 val_auc=0.6604
model=gat top_k=500 fold=2 epoch=4 loss=27.2520 val_auc=0.6438
model=gat top_k=500 fold=2 epoch=5 loss=10.5581 val_auc=0.5352
model=gat top_k=500 fold=2 epoch=6 loss=23.4540 val_auc=0.6649
model=gat top_k=500 fold=2 epoch=7 loss=12.2179 val_auc=0.7193
model=gat top_k=500 fold=2 epoch=8 loss=8.4954 val_auc=0.7303
model=gat top_k=500 fold=2 epoch=9 loss=20.8497 val_auc=0.7339
model=gat top_k=500 fold=2 epoch=10 loss=21.1907 val_auc=0.7336
model=gat top_k=500 fold=2 epoch=11 loss=14.2914 val_auc=0.7330
model=gat top_k=500 fold=2 epoch=12 loss=10.0763 val_auc=0.7302
model=gat top_k=500 fold=2 epoch=13 loss=12.4511 val_auc=0.6811
model=gat top_k=500 fold=2 epoch=14 loss=17.7692 val_auc=0.6906
model=gat top_k=500 fold=2 epoch=15 loss=12.8878 val_auc=0.7315
model=gat top_k=500 fold=2 epoch=16 loss=8.9001 val_auc=0.7384
model=gat top_k=500 fold=2 epoch=17 loss=9.3595 val_auc=0.7405
model=gat top_k=500 fold=2 epoch=18 loss=10.9728 val_auc=0.7403
model=gat top_k=500 fold=2 epoch=19 loss=13.0908 val_auc=0.7287
model=gat top_k=500 fold=2 epoch=20 loss=13.9856 val_auc=0.7176
model=gat top_k=500 fold=2 epoch=21 loss=8.2296 val_auc=0.7125
model=gat top_k=500 fold=2 epoch=22 loss=9.1886 val_auc=0.7112
model=gat top_k=500 fold=2 epoch=23 loss=10.2397 val_auc=0.7047
model=gat top_k=500 fold=2 epoch=24 loss=16.8708 val_auc=0.7014
model=gat top_k=500 fold=2 epoch=25 loss=11.4024 val_auc=0.7263
model=gat top_k=500 fold=2 epoch=26 loss=12.4577 val_auc=0.7455
model=gat top_k=500 fold=2 epoch=27 loss=8.3011 val_auc=0.7619
model=gat top_k=500 fold=2 epoch=28 loss=8.0812 val_auc=0.7670
model=gat top_k=500 fold=2 epoch=29 loss=9.7573 val_auc=0.7698
model=gat top_k=500 fold=2 epoch=30 loss=9.1912 val_auc=0.7706
model=gat top_k=500 fold=2 epoch=31 loss=9.8948 val_auc=0.7703
model=gat top_k=500 fold=2 epoch=32 loss=5.7589 val_auc=0.7717
model=gat top_k=500 fold=2 epoch=33 loss=7.4036 val_auc=0.7711
model=gat top_k=500 fold=2 epoch=34 loss=9.7269 val_auc=0.7755
model=gat top_k=500 fold=2 epoch=35 loss=8.3963 val_auc=0.7787
model=gat top_k=500 fold=2 epoch=36 loss=6.5434 val_auc=0.7809
model=gat top_k=500 fold=2 epoch=37 loss=4.9895 val_auc=0.7825
model=gat top_k=500 fold=2 epoch=38 loss=7.0385 val_auc=0.7837
model=gat top_k=500 fold=2 epoch=39 loss=6.9740 val_auc=0.7851
model=gat top_k=500 fold=2 epoch=40 loss=6.5788 val_auc=0.7869
model=gat top_k=500 fold=2 epoch=41 loss=5.5862 val_auc=0.7890
model=gat top_k=500 fold=2 epoch=42 loss=5.1874 val_auc=0.7908
model=gat top_k=500 fold=2 epoch=43 loss=9.2154 val_auc=0.7920
model=gat top_k=500 fold=2 epoch=44 loss=6.5211 val_auc=0.7925
model=gat top_k=500 fold=2 epoch=45 loss=5.5266 val_auc=0.7927
model=gat top_k=500 fold=2 epoch=46 loss=5.6103 val_auc=0.7924
model=gat top_k=500 fold=2 epoch=47 loss=5.0865 val_auc=0.7910
model=gat top_k=500 fold=2 epoch=48 loss=5.3064 val_auc=0.7893
model=gat top_k=500 fold=2 epoch=49 loss=5.2891 val_auc=0.7876
model=gat top_k=500 fold=2 epoch=50 loss=6.3383 val_auc=0.7888
model=gat top_k=500 fold=2 epoch=51 loss=5.2138 val_auc=0.7910
model=gat top_k=500 fold=2 epoch=52 loss=5.4850 val_auc=0.7922
model=gat top_k=500 fold=2 epoch=53 loss=5.7414 val_auc=0.7930
model=gat top_k=500 fold=2 epoch=54 loss=5.5644 val_auc=0.7964
model=gat top_k=500 fold=2 epoch=55 loss=4.1407 val_auc=0.7981
model=gat top_k=500 fold=2 epoch=56 loss=4.3508 val_auc=0.7993
model=gat top_k=500 fold=2 epoch=57 loss=5.1098 val_auc=0.8000
model=gat top_k=500 fold=2 epoch=58 loss=6.1190 val_auc=0.8002
model=gat top_k=500 fold=2 epoch=59 loss=3.7807 val_auc=0.8013
model=gat top_k=500 fold=2 epoch=60 loss=4.1063 val_auc=0.8023
model=gat top_k=500 fold=2 epoch=61 loss=3.5996 val_auc=0.8037
model=gat top_k=500 fold=2 epoch=62 loss=4.0897 val_auc=0.8034
model=gat top_k=500 fold=2 epoch=63 loss=4.3843 val_auc=0.8034
model=gat top_k=500 fold=2 epoch=64 loss=4.0657 val_auc=0.8042
model=gat top_k=500 fold=2 epoch=65 loss=5.3657 val_auc=0.8064
model=gat top_k=500 fold=2 epoch=66 loss=3.5649 val_auc=0.8089
model=gat top_k=500 fold=2 epoch=67 loss=3.5709 val_auc=0.8120
model=gat top_k=500 fold=2 epoch=68 loss=3.8880 val_auc=0.8143
model=gat top_k=500 fold=2 epoch=69 loss=3.5003 val_auc=0.8151
model=gat top_k=500 fold=2 epoch=70 loss=3.1333 val_auc=0.8159
model=gat top_k=500 fold=2 epoch=71 loss=3.1089 val_auc=0.8164
model=gat top_k=500 fold=2 epoch=72 loss=3.4643 val_auc=0.8178
model=gat top_k=500 fold=2 epoch=73 loss=3.3489 val_auc=0.8189
model=gat top_k=500 fold=2 epoch=74 loss=3.6598 val_auc=0.8189
model=gat top_k=500 fold=2 epoch=75 loss=3.8351 val_auc=0.8182
model=gat top_k=500 fold=2 epoch=76 loss=2.9475 val_auc=0.8203
model=gat top_k=500 fold=2 epoch=77 loss=3.6110 val_auc=0.8211
model=gat top_k=500 fold=2 epoch=78 loss=3.0624 val_auc=0.8218
model=gat top_k=500 fold=2 epoch=79 loss=3.6678 val_auc=0.8220
model=gat top_k=500 fold=2 epoch=80 loss=3.2505 val_auc=0.8215
model=gat top_k=500 fold=2 epoch=81 loss=3.0646 val_auc=0.8201
model=gat top_k=500 fold=2 epoch=82 loss=3.4993 val_auc=0.8204
model=gat top_k=500 fold=2 epoch=83 loss=2.7787 val_auc=0.8214
model=gat top_k=500 fold=2 epoch=84 loss=2.9249 val_auc=0.8222
model=gat top_k=500 fold=2 epoch=85 loss=3.1029 val_auc=0.8216
model=gat top_k=500 fold=2 epoch=86 loss=2.6421 val_auc=0.8222
model=gat top_k=500 fold=2 epoch=87 loss=2.9025 val_auc=0.8230
model=gat top_k=500 fold=2 epoch=88 loss=2.6745 val_auc=0.8243
model=gat top_k=500 fold=2 epoch=89 loss=2.7882 val_auc=0.8252
model=gat top_k=500 fold=2 epoch=90 loss=2.9957 val_auc=0.8253
model=gat top_k=500 fold=2 epoch=91 loss=3.0274 val_auc=0.8259
model=gat top_k=500 fold=2 epoch=92 loss=2.7933 val_auc=0.8267
model=gat top_k=500 fold=2 epoch=93 loss=2.8703 val_auc=0.8270
model=gat top_k=500 fold=2 epoch=94 loss=2.8915 val_auc=0.8270
model=gat top_k=500 fold=2 epoch=95 loss=3.3466 val_auc=0.8261
model=gat top_k=500 fold=2 epoch=96 loss=2.8049 val_auc=0.8265
model=gat top_k=500 fold=2 epoch=97 loss=3.1213 val_auc=0.8272
model=gat top_k=500 fold=2 epoch=98 loss=2.4200 val_auc=0.8286
model=gat top_k=500 fold=2 epoch=99 loss=3.3597 val_auc=0.8287
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782205 edges

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=500 fold=3 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 781933 edges

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=500 fold=3 epoch=0 loss=12.5246 val_auc=0.7162
model=gat top_k=500 fold=3 epoch=1 loss=40.5138 val_auc=0.5008
model=gat top_k=500 fold=3 epoch=2 loss=49.4692 val_auc=0.5987
model=gat top_k=500 fold=3 epoch=3 loss=25.2049 val_auc=0.7345
model=gat top_k=500 fold=3 epoch=4 loss=20.4686 val_auc=0.7379
model=gat top_k=500 fold=3 epoch=5 loss=17.6495 val_auc=0.7315
model=gat top_k=500 fold=3 epoch=6 loss=11.0239 val_auc=0.7212
model=gat top_k=500 fold=3 epoch=7 loss=15.6531 val_auc=0.7350
model=gat top_k=500 fold=3 epoch=8 loss=8.3999 val_auc=0.7399
model=gat top_k=500 fold=3 epoch=9 loss=11.3220 val_auc=0.7421
model=gat top_k=500 fold=3 epoch=10 loss=8.4687 val_auc=0.7391
model=gat top_k=500 fold=3 epoch=11 loss=10.2108 val_auc=0.7446
model=gat top_k=500 fold=3 epoch=12 loss=10.0392 val_auc=0.7551
model=gat top_k=500 fold=3 epoch=13 loss=7.7491 val_auc=0.7592
model=gat top_k=500 fold=3 epoch=14 loss=10.3347 val_auc=0.7626
model=gat top_k=500 fold=3 epoch=15 loss=12.8453 val_auc=0.7674
model=gat top_k=500 fold=3 epoch=16 loss=6.7754 val_auc=0.7743
model=gat top_k=500 fold=3 epoch=17 loss=7.6821 val_auc=0.7803
model=gat top_k=500 fold=3 epoch=18 loss=7.7087 val_auc=0.7866
model=gat top_k=500 fold=3 epoch=19 loss=7.3323 val_auc=0.7907
model=gat top_k=500 fold=3 epoch=20 loss=6.6223 val_auc=0.7938
model=gat top_k=500 fold=3 epoch=21 loss=6.3579 val_auc=0.7951
model=gat top_k=500 fold=3 epoch=22 loss=6.7509 val_auc=0.7943
model=gat top_k=500 fold=3 epoch=23 loss=6.1950 val_auc=0.7936
model=gat top_k=500 fold=3 epoch=24 loss=7.2810 val_auc=0.7977
model=gat top_k=500 fold=3 epoch=25 loss=6.2628 val_auc=0.7993
model=gat top_k=500 fold=3 epoch=26 loss=5.6158 val_auc=0.8010
model=gat top_k=500 fold=3 epoch=27 loss=6.1955 val_auc=0.8013
model=gat top_k=500 fold=3 epoch=28 loss=6.1480 val_auc=0.8010
model=gat top_k=500 fold=3 epoch=29 loss=5.8150 val_auc=0.8009
model=gat top_k=500 fold=3 epoch=30 loss=6.0627 val_auc=0.8017
model=gat top_k=500 fold=3 epoch=31 loss=6.7089 val_auc=0.8038
model=gat top_k=500 fold=3 epoch=32 loss=5.2699 val_auc=0.8054
model=gat top_k=500 fold=3 epoch=33 loss=7.0192 val_auc=0.8059
model=gat top_k=500 fold=3 epoch=34 loss=8.3772 val_auc=0.8059
model=gat top_k=500 fold=3 epoch=35 loss=8.5125 val_auc=0.8050
model=gat top_k=500 fold=3 epoch=36 loss=6.4518 val_auc=0.8041
model=gat top_k=500 fold=3 epoch=37 loss=4.7270 val_auc=0.8041
model=gat top_k=500 fold=3 epoch=38 loss=4.9290 val_auc=0.8042
model=gat top_k=500 fold=3 epoch=39 loss=8.0896 val_auc=0.8050
model=gat top_k=500 fold=3 epoch=40 loss=4.6297 val_auc=0.8064
model=gat top_k=500 fold=3 epoch=41 loss=4.5948 val_auc=0.8077
model=gat top_k=500 fold=3 epoch=42 loss=4.7070 val_auc=0.8085
model=gat top_k=500 fold=3 epoch=43 loss=5.1329 val_auc=0.8092
model=gat top_k=500 fold=3 epoch=44 loss=3.7901 val_auc=0.8090
model=gat top_k=500 fold=3 epoch=45 loss=5.4244 val_auc=0.8080
model=gat top_k=500 fold=3 epoch=46 loss=4.9530 val_auc=0.8078
model=gat top_k=500 fold=3 epoch=47 loss=5.5406 val_auc=0.8091
model=gat top_k=500 fold=3 epoch=48 loss=5.3590 val_auc=0.8093
model=gat top_k=500 fold=3 epoch=49 loss=4.2565 val_auc=0.8091
model=gat top_k=500 fold=3 epoch=50 loss=3.9393 val_auc=0.8085
model=gat top_k=500 fold=3 epoch=51 loss=4.0237 val_auc=0.8080
model=gat top_k=500 fold=3 epoch=52 loss=4.3127 val_auc=0.8079
model=gat top_k=500 fold=3 epoch=53 loss=3.7243 val_auc=0.8091
model=gat top_k=500 fold=3 epoch=54 loss=3.6299 val_auc=0.8102
model=gat top_k=500 fold=3 epoch=55 loss=3.9983 val_auc=0.8113
model=gat top_k=500 fold=3 epoch=56 loss=4.0835 val_auc=0.8123
model=gat top_k=500 fold=3 epoch=57 loss=4.3460 val_auc=0.8128
model=gat top_k=500 fold=3 epoch=58 loss=3.7232 val_auc=0.8131
model=gat top_k=500 fold=3 epoch=59 loss=4.9104 val_auc=0.8130
model=gat top_k=500 fold=3 epoch=60 loss=4.6490 val_auc=0.8133
model=gat top_k=500 fold=3 epoch=61 loss=3.7936 val_auc=0.8137
model=gat top_k=500 fold=3 epoch=62 loss=5.1290 val_auc=0.8136
model=gat top_k=500 fold=3 epoch=63 loss=5.6612 val_auc=0.8124
model=gat top_k=500 fold=3 epoch=64 loss=3.9853 val_auc=0.8111
model=gat top_k=500 fold=3 epoch=65 loss=3.9608 val_auc=0.8100
model=gat top_k=500 fold=3 epoch=66 loss=3.5967 val_auc=0.8106
model=gat top_k=500 fold=3 epoch=67 loss=3.3165 val_auc=0.8122
model=gat top_k=500 fold=3 epoch=68 loss=3.9412 val_auc=0.8130
model=gat top_k=500 fold=3 epoch=69 loss=3.1086 val_auc=0.8143
model=gat top_k=500 fold=3 epoch=70 loss=3.3066 val_auc=0.8160
model=gat top_k=500 fold=3 epoch=71 loss=3.9782 val_auc=0.8157
model=gat top_k=500 fold=3 epoch=72 loss=3.2554 val_auc=0.8164
model=gat top_k=500 fold=3 epoch=73 loss=3.7810 val_auc=0.8172
model=gat top_k=500 fold=3 epoch=74 loss=3.1166 val_auc=0.8188
model=gat top_k=500 fold=3 epoch=75 loss=3.3642 val_auc=0.8200
model=gat top_k=500 fold=3 epoch=76 loss=3.4037 val_auc=0.8207
model=gat top_k=500 fold=3 epoch=77 loss=4.0966 val_auc=0.8215
model=gat top_k=500 fold=3 epoch=78 loss=3.0841 val_auc=0.8224
model=gat top_k=500 fold=3 epoch=79 loss=3.4122 val_auc=0.8231
model=gat top_k=500 fold=3 epoch=80 loss=3.6374 val_auc=0.8233
model=gat top_k=500 fold=3 epoch=81 loss=2.9693 val_auc=0.8230
model=gat top_k=500 fold=3 epoch=82 loss=3.2003 val_auc=0.8238
model=gat top_k=500 fold=3 epoch=83 loss=3.3487 val_auc=0.8246
model=gat top_k=500 fold=3 epoch=84 loss=3.6962 val_auc=0.8246
model=gat top_k=500 fold=3 epoch=85 loss=2.6843 val_auc=0.8245
model=gat top_k=500 fold=3 epoch=86 loss=3.4497 val_auc=0.8249
model=gat top_k=500 fold=3 epoch=87 loss=3.1308 val_auc=0.8245
model=gat top_k=500 fold=3 epoch=88 loss=3.2053 val_auc=0.8246
model=gat top_k=500 fold=3 epoch=89 loss=3.9848 val_auc=0.8250
model=gat top_k=500 fold=3 epoch=90 loss=2.7627 val_auc=0.8259
model=gat top_k=500 fold=3 epoch=91 loss=3.5229 val_auc=0.8263
model=gat top_k=500 fold=3 epoch=92 loss=4.1640 val_auc=0.8263
model=gat top_k=500 fold=3 epoch=93 loss=4.0747 val_auc=0.8257
model=gat top_k=500 fold=3 epoch=94 loss=2.4849 val_auc=0.8254
model=gat top_k=500 fold=3 epoch=95 loss=3.8300 val_auc=0.8252
model=gat top_k=500 fold=3 epoch=96 loss=4.4756 val_auc=0.8256
model=gat top_k=500 fold=3 epoch=97 loss=3.5824 val_auc=0.8267
model=gat top_k=500 fold=3 epoch=98 loss=3.0985 val_auc=0.8279
model=gat top_k=500 fold=3 epoch=99 loss=2.7538 val_auc=0.8284
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 781933 edges

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=500 fold=4 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782579 edges

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=500 fold=4 epoch=0 loss=13.1793 val_auc=0.6383
model=gat top_k=500 fold=4 epoch=1 loss=63.5411 val_auc=0.5559
model=gat top_k=500 fold=4 epoch=2 loss=24.7802 val_auc=0.7252
model=gat top_k=500 fold=4 epoch=3 loss=10.0736 val_auc=0.7439
model=gat top_k=500 fold=4 epoch=4 loss=19.5649 val_auc=0.7439
model=gat top_k=500 fold=4 epoch=5 loss=12.1247 val_auc=0.7523
model=gat top_k=500 fold=4 epoch=6 loss=8.3884 val_auc=0.7643
model=gat top_k=500 fold=4 epoch=7 loss=13.5021 val_auc=0.7749
model=gat top_k=500 fold=4 epoch=8 loss=9.4760 val_auc=0.7708
model=gat top_k=500 fold=4 epoch=9 loss=14.5819 val_auc=0.7847
model=gat top_k=500 fold=4 epoch=10 loss=9.9712 val_auc=0.7876
model=gat top_k=500 fold=4 epoch=11 loss=7.9444 val_auc=0.7890
model=gat top_k=500 fold=4 epoch=12 loss=9.0465 val_auc=0.7887
model=gat top_k=500 fold=4 epoch=13 loss=7.2473 val_auc=0.7868
model=gat top_k=500 fold=4 epoch=14 loss=7.2457 val_auc=0.7907
model=gat top_k=500 fold=4 epoch=15 loss=6.7422 val_auc=0.7922
model=gat top_k=500 fold=4 epoch=16 loss=6.6203 val_auc=0.7945
model=gat top_k=500 fold=4 epoch=17 loss=8.1926 val_auc=0.7949
model=gat top_k=500 fold=4 epoch=18 loss=6.6431 val_auc=0.7936
model=gat top_k=500 fold=4 epoch=19 loss=7.7563 val_auc=0.7921
model=gat top_k=500 fold=4 epoch=20 loss=6.7744 val_auc=0.7929
model=gat top_k=500 fold=4 epoch=21 loss=7.6426 val_auc=0.7935
model=gat top_k=500 fold=4 epoch=22 loss=5.2370 val_auc=0.7950
model=gat top_k=500 fold=4 epoch=23 loss=5.5116 val_auc=0.7961
model=gat top_k=500 fold=4 epoch=24 loss=5.2468 val_auc=0.7911
model=gat top_k=500 fold=4 epoch=25 loss=5.8782 val_auc=0.7808
model=gat top_k=500 fold=4 epoch=26 loss=5.5682 val_auc=0.7747
model=gat top_k=500 fold=4 epoch=27 loss=5.6408 val_auc=0.7738
model=gat top_k=500 fold=4 epoch=28 loss=5.3184 val_auc=0.7732
model=gat top_k=500 fold=4 epoch=29 loss=6.0233 val_auc=0.7772
model=gat top_k=500 fold=4 epoch=30 loss=6.8514 val_auc=0.7792
model=gat top_k=500 fold=4 epoch=31 loss=5.9287 val_auc=0.7771
model=gat top_k=500 fold=4 epoch=32 loss=6.2353 val_auc=0.7754
model=gat top_k=500 fold=4 epoch=33 loss=7.1831 val_auc=0.7745
model=gat top_k=500 fold=4 epoch=34 loss=4.7995 val_auc=0.7774
model=gat top_k=500 fold=4 epoch=35 loss=7.6403 val_auc=0.7739
gat top_k=500 fold=4: early stopping at epoch 35
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782579 edges

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=500 fold=5 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782265 edges

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=500 fold=5 epoch=0 loss=15.3523 val_auc=0.5743
model=gat top_k=500 fold=5 epoch=1 loss=70.0774 val_auc=0.5780
model=gat top_k=500 fold=5 epoch=2 loss=12.6661 val_auc=0.6831
model=gat top_k=500 fold=5 epoch=3 loss=11.1434 val_auc=0.6674
model=gat top_k=500 fold=5 epoch=4 loss=15.9022 val_auc=0.7557
model=gat top_k=500 fold=5 epoch=5 loss=8.0341 val_auc=0.7700
model=gat top_k=500 fold=5 epoch=6 loss=8.3985 val_auc=0.7370
model=gat top_k=500 fold=5 epoch=7 loss=12.6959 val_auc=0.7653
model=gat top_k=500 fold=5 epoch=8 loss=8.7925 val_auc=0.7899
model=gat top_k=500 fold=5 epoch=9 loss=9.9228 val_auc=0.7896
model=gat top_k=500 fold=5 epoch=10 loss=11.0619 val_auc=0.7893
model=gat top_k=500 fold=5 epoch=11 loss=6.7235 val_auc=0.7892
model=gat top_k=500 fold=5 epoch=12 loss=8.3947 val_auc=0.7923
model=gat top_k=500 fold=5 epoch=13 loss=9.3177 val_auc=0.8007
model=gat top_k=500 fold=5 epoch=14 loss=7.4475 val_auc=0.8012
model=gat top_k=500 fold=5 epoch=15 loss=6.8488 val_auc=0.8034
model=gat top_k=500 fold=5 epoch=16 loss=7.1531 val_auc=0.8062
model=gat top_k=500 fold=5 epoch=17 loss=6.6070 val_auc=0.8012
model=gat top_k=500 fold=5 epoch=18 loss=6.6832 val_auc=0.8007
model=gat top_k=500 fold=5 epoch=19 loss=8.2967 val_auc=0.8044
model=gat top_k=500 fold=5 epoch=20 loss=6.5404 val_auc=0.8023
model=gat top_k=500 fold=5 epoch=21 loss=8.6887 val_auc=0.7923
model=gat top_k=500 fold=5 epoch=22 loss=6.9958 val_auc=0.7804
model=gat top_k=500 fold=5 epoch=23 loss=5.6973 val_auc=0.7779
model=gat top_k=500 fold=5 epoch=24 loss=5.4067 val_auc=0.7786
model=gat top_k=500 fold=5 epoch=25 loss=6.2981 val_auc=0.7816
model=gat top_k=500 fold=5 epoch=26 loss=6.6291 val_auc=0.7896
model=gat top_k=500 fold=5 epoch=27 loss=4.9213 val_auc=0.8015
model=gat top_k=500 fold=5 epoch=28 loss=5.7248 val_auc=0.8046
gat top_k=500 fold=5: early stopping at epoch 28
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782265 edges

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=500 fold=6 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 781867 edges
model=gat top_k=500 fold=6 epoch=0 loss=17.7795 val_auc=0.5001
model=gat top_k=500 fold=6 epoch=1 loss=104.0258 val_auc=0.5277
model=gat top_k=500 fold=6 epoch=2 loss=32.9659 val_auc=0.6754
model=gat top_k=500 fold=6 epoch=3 loss=27.8224 val_auc=0.7095
model=gat top_k=500 fold=6 epoch=4 loss=25.4755 val_auc=0.7305
model=gat top_k=500 fold=6 epoch=5 loss=13.0673 val_auc=0.7018
model=gat top_k=500 fold=6 epoch=6 loss=16.5647 val_auc=0.7315
model=gat top_k=500 fold=6 epoch=7 loss=8.4255 val_auc=0.7344
model=gat top_k=500 fold=6 epoch=8 loss=9.3105 val_auc=0.7442
model=gat top_k=500 fold=6 epoch=9 loss=12.4781 val_auc=0.7534
model=gat top_k=500 fold=6 epoch=10 loss=9.3863 val_auc=0.7576
model=gat top_k=500 fold=6 epoch=11 loss=11.1721 val_auc=0.7613
model=gat top_k=500 fold=6 epoch=12 loss=8.8319 val_auc=0.7675
model=gat top_k=500 fold=6 epoch=13 loss=7.6093 val_auc=0.7723
model=gat top_k=500 fold=6 epoch=14 loss=8.0565 val_auc=0.7785
model=gat top_k=500 fold=6 epoch=15 loss=9.5064 val_auc=0.7830
model=gat top_k=500 fold=6 epoch=16 loss=6.2742 val_auc=0.7814
model=gat top_k=500 fold=6 epoch=17 loss=8.8471 val_auc=0.7795
model=gat top_k=500 fold=6 epoch=18 loss=11.6224 val_auc=0.7813
model=gat top_k=500 fold=6 epoch=19 loss=6.4306 val_auc=0.7829
model=gat top_k=500 fold=6 epoch=20 loss=5.6941 val_auc=0.7900
model=gat top_k=500 fold=6 epoch=21 loss=8.1162 val_auc=0.7944
model=gat top_k=500 fold=6 epoch=22 loss=9.7707 val_auc=0.7975
model=gat top_k=500 fold=6 epoch=23 loss=7.2358 val_auc=0.7984
model=gat top_k=500 fold=6 epoch=24 loss=5.6330 val_auc=0.7999
model=gat top_k=500 fold=6 epoch=25 loss=7.1094 val_auc=0.8019
model=gat top_k=500 fold=6 epoch=26 loss=5.7302 val_auc=0.8044
model=gat top_k=500 fold=6 epoch=27 loss=4.4976 val_auc=0.8068
model=gat top_k=500 fold=6 epoch=28 loss=5.6520 val_auc=0.8079
model=gat top_k=500 fold=6 epoch=29 loss=6.2694 val_auc=0.8086
model=gat top_k=500 fold=6 epoch=30 loss=4.5888 val_auc=0.8104
model=gat top_k=500 fold=6 epoch=31 loss=5.8146 val_auc=0.8114
model=gat top_k=500 fold=6 epoch=32 loss=5.5622 val_auc=0.8119
model=gat top_k=500 fold=6 epoch=33 loss=5.7653 val_auc=0.8124
model=gat top_k=500 fold=6 epoch=34 loss=4.8110 val_auc=0.8130
model=gat top_k=500 fold=6 epoch=35 loss=4.5074 val_auc=0.8140
model=gat top_k=500 fold=6 epoch=36 loss=5.5465 val_auc=0.8152
model=gat top_k=500 fold=6 epoch=37 loss=5.1378 val_auc=0.8151
model=gat top_k=500 fold=6 epoch=38 loss=3.9983 val_auc=0.8020
model=gat top_k=500 fold=6 epoch=39 loss=4.6470 val_auc=0.8009
model=gat top_k=500 fold=6 epoch=40 loss=4.3508 val_auc=0.8016
model=gat top_k=500 fold=6 epoch=41 loss=4.5556 val_auc=0.7998
model=gat top_k=500 fold=6 epoch=42 loss=3.5364 val_auc=0.7992
model=gat top_k=500 fold=6 epoch=43 loss=4.6961 val_auc=0.8071
model=gat top_k=500 fold=6 epoch=44 loss=4.1300 val_auc=0.8143
model=gat top_k=500 fold=6 epoch=45 loss=3.9479 val_auc=0.8170
model=gat top_k=500 fold=6 epoch=46 loss=4.3216 val_auc=0.8179
model=gat top_k=500 fold=6 epoch=47 loss=3.6912 val_auc=0.8216
model=gat top_k=500 fold=6 epoch=48 loss=4.5929 val_auc=0.8230
model=gat top_k=500 fold=6 epoch=49 loss=3.8850 val_auc=0.8234
model=gat top_k=500 fold=6 epoch=50 loss=4.1066 val_auc=0.8230
model=gat top_k=500 fold=6 epoch=51 loss=3.8197 val_auc=0.8238
model=gat top_k=500 fold=6 epoch=52 loss=3.3288 val_auc=0.8252
model=gat top_k=500 fold=6 epoch=53 loss=3.5732 val_auc=0.8254
model=gat top_k=500 fold=6 epoch=54 loss=4.4612 val_auc=0.8265
model=gat top_k=500 fold=6 epoch=55 loss=3.2484 val_auc=0.8263
model=gat top_k=500 fold=6 epoch=56 loss=3.6916 val_auc=0.8262
model=gat top_k=500 fold=6 epoch=57 loss=3.5681 val_auc=0.8271
model=gat top_k=500 fold=6 epoch=58 loss=3.0822 val_auc=0.8274
model=gat top_k=500 fold=6 epoch=59 loss=3.3916 val_auc=0.8276
model=gat top_k=500 fold=6 epoch=60 loss=3.2979 val_auc=0.8278
model=gat top_k=500 fold=6 epoch=61 loss=3.4114 val_auc=0.8278
model=gat top_k=500 fold=6 epoch=62 loss=3.6546 val_auc=0.8280
model=gat top_k=500 fold=6 epoch=63 loss=2.6788 val_auc=0.8286
model=gat top_k=500 fold=6 epoch=64 loss=3.0665 val_auc=0.8293
model=gat top_k=500 fold=6 epoch=65 loss=2.8264 val_auc=0.8296
model=gat top_k=500 fold=6 epoch=66 loss=3.4316 val_auc=0.8296
model=gat top_k=500 fold=6 epoch=67 loss=3.3207 val_auc=0.8296
model=gat top_k=500 fold=6 epoch=68 loss=2.7202 val_auc=0.8294
model=gat top_k=500 fold=6 epoch=69 loss=3.9688 val_auc=0.8288
model=gat top_k=500 fold=6 epoch=70 loss=4.2773 val_auc=0.8284
model=gat top_k=500 fold=6 epoch=71 loss=4.6366 val_auc=0.8285
model=gat top_k=500 fold=6 epoch=72 loss=2.8456 val_auc=0.8289
model=gat top_k=500 fold=6 epoch=73 loss=3.7394 val_auc=0.8289
model=gat top_k=500 fold=6 epoch=74 loss=5.2609 val_auc=0.8284
model=gat top_k=500 fold=6 epoch=75 loss=4.5445 val_auc=0.8277
model=gat top_k=500 fold=6 epoch=76 loss=3.0110 val_auc=0.8270
model=gat top_k=500 fold=6 epoch=77 loss=3.0432 val_auc=0.8266
model=gat top_k=500 fold=6 epoch=78 loss=3.3450 val_auc=0.8266
gat top_k=500 fold=6: early stopping at epoch 78
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 781867 edges

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=500 fold=7 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782278 edges

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=500 fold=7 epoch=0 loss=19.1723 val_auc=0.5063
model=gat top_k=500 fold=7 epoch=1 loss=81.7287 val_auc=0.5808
model=gat top_k=500 fold=7 epoch=2 loss=13.8350 val_auc=0.6765
model=gat top_k=500 fold=7 epoch=3 loss=16.7932 val_auc=0.5423
model=gat top_k=500 fold=7 epoch=4 loss=22.3840 val_auc=0.7359
model=gat top_k=500 fold=7 epoch=5 loss=11.7874 val_auc=0.7506
model=gat top_k=500 fold=7 epoch=6 loss=13.6022 val_auc=0.7586
model=gat top_k=500 fold=7 epoch=7 loss=13.6880 val_auc=0.7677
model=gat top_k=500 fold=7 epoch=8 loss=8.5773 val_auc=0.7622
model=gat top_k=500 fold=7 epoch=9 loss=13.2295 val_auc=0.7536
model=gat top_k=500 fold=7 epoch=10 loss=11.0878 val_auc=0.7780
model=gat top_k=500 fold=7 epoch=11 loss=9.7736 val_auc=0.7814
model=gat top_k=500 fold=7 epoch=12 loss=10.8072 val_auc=0.7838
model=gat top_k=500 fold=7 epoch=13 loss=11.3696 val_auc=0.7862
model=gat top_k=500 fold=7 epoch=14 loss=7.0365 val_auc=0.7882
model=gat top_k=500 fold=7 epoch=15 loss=7.6102 val_auc=0.7877
model=gat top_k=500 fold=7 epoch=16 loss=8.0736 val_auc=0.7892
model=gat top_k=500 fold=7 epoch=17 loss=11.0077 val_auc=0.7902
model=gat top_k=500 fold=7 epoch=18 loss=7.3047 val_auc=0.7907
model=gat top_k=500 fold=7 epoch=19 loss=6.3717 val_auc=0.7920
model=gat top_k=500 fold=7 epoch=20 loss=7.4992 val_auc=0.7935
model=gat top_k=500 fold=7 epoch=21 loss=6.2249 val_auc=0.7946
model=gat top_k=500 fold=7 epoch=22 loss=5.6839 val_auc=0.7940
model=gat top_k=500 fold=7 epoch=23 loss=6.0286 val_auc=0.7913
model=gat top_k=500 fold=7 epoch=24 loss=6.4642 val_auc=0.7887
model=gat top_k=500 fold=7 epoch=25 loss=6.4691 val_auc=0.7868
model=gat top_k=500 fold=7 epoch=26 loss=5.5822 val_auc=0.7890
model=gat top_k=500 fold=7 epoch=27 loss=5.6174 val_auc=0.7912
model=gat top_k=500 fold=7 epoch=28 loss=5.5840 val_auc=0.7923
model=gat top_k=500 fold=7 epoch=29 loss=6.1686 val_auc=0.7927
model=gat top_k=500 fold=7 epoch=30 loss=5.6339 val_auc=0.7933
model=gat top_k=500 fold=7 epoch=31 loss=7.3130 val_auc=0.7943
model=gat top_k=500 fold=7 epoch=32 loss=6.6297 val_auc=0.7959
model=gat top_k=500 fold=7 epoch=33 loss=5.4151 val_auc=0.7967
model=gat top_k=500 fold=7 epoch=34 loss=4.5949 val_auc=0.7972
model=gat top_k=500 fold=7 epoch=35 loss=5.4871 val_auc=0.7984
model=gat top_k=500 fold=7 epoch=36 loss=5.1316 val_auc=0.7995
model=gat top_k=500 fold=7 epoch=37 loss=4.9336 val_auc=0.8004
model=gat top_k=500 fold=7 epoch=38 loss=4.8784 val_auc=0.8005
model=gat top_k=500 fold=7 epoch=39 loss=4.5971 val_auc=0.7994
model=gat top_k=500 fold=7 epoch=40 loss=4.0517 val_auc=0.7961
model=gat top_k=500 fold=7 epoch=41 loss=4.3526 val_auc=0.7998
model=gat top_k=500 fold=7 epoch=42 loss=4.0720 val_auc=0.8065
model=gat top_k=500 fold=7 epoch=43 loss=4.5449 val_auc=0.8098
model=gat top_k=500 fold=7 epoch=44 loss=3.9426 val_auc=0.8100
model=gat top_k=500 fold=7 epoch=45 loss=4.1651 val_auc=0.8085
model=gat top_k=500 fold=7 epoch=46 loss=4.0955 val_auc=0.8047
model=gat top_k=500 fold=7 epoch=47 loss=3.5974 val_auc=0.8014
model=gat top_k=500 fold=7 epoch=48 loss=4.2648 val_auc=0.8007
model=gat top_k=500 fold=7 epoch=49 loss=4.2255 val_auc=0.7992
model=gat top_k=500 fold=7 epoch=50 loss=4.1851 val_auc=0.7985
model=gat top_k=500 fold=7 epoch=51 loss=3.7091 val_auc=0.8010
model=gat top_k=500 fold=7 epoch=52 loss=3.8718 val_auc=0.8028
model=gat top_k=500 fold=7 epoch=53 loss=3.9204 val_auc=0.7974
model=gat top_k=500 fold=7 epoch=54 loss=4.6706 val_auc=0.7823
model=gat top_k=500 fold=7 epoch=55 loss=3.7281 val_auc=0.7888
model=gat top_k=500 fold=7 epoch=56 loss=4.1840 val_auc=0.7921
gat top_k=500 fold=7: early stopping at epoch 56
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782278 edges

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=500 fold=8 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782047 edges
model=gat top_k=500 fold=8 epoch=0 loss=10.3453 val_auc=0.5000
model=gat top_k=500 fold=8 epoch=1 loss=123.7321 val_auc=0.4947
model=gat top_k=500 fold=8 epoch=2 loss=39.3745 val_auc=0.6778
model=gat top_k=500 fold=8 epoch=3 loss=31.9455 val_auc=0.6988
model=gat top_k=500 fold=8 epoch=4 loss=22.2606 val_auc=0.6937
model=gat top_k=500 fold=8 epoch=5 loss=13.0401 val_auc=0.6819
model=gat top_k=500 fold=8 epoch=6 loss=13.5465 val_auc=0.7150
model=gat top_k=500 fold=8 epoch=7 loss=13.7276 val_auc=0.7417
model=gat top_k=500 fold=8 epoch=8 loss=8.7161 val_auc=0.7492
model=gat top_k=500 fold=8 epoch=9 loss=12.3381 val_auc=0.7466
model=gat top_k=500 fold=8 epoch=10 loss=9.6491 val_auc=0.7422
model=gat top_k=500 fold=8 epoch=11 loss=7.5687 val_auc=0.7435
model=gat top_k=500 fold=8 epoch=12 loss=7.8788 val_auc=0.7493
model=gat top_k=500 fold=8 epoch=13 loss=7.4630 val_auc=0.7471
model=gat top_k=500 fold=8 epoch=14 loss=7.1919 val_auc=0.7392
model=gat top_k=500 fold=8 epoch=15 loss=8.9524 val_auc=0.7301
model=gat top_k=500 fold=8 epoch=16 loss=8.4330 val_auc=0.7214
model=gat top_k=500 fold=8 epoch=17 loss=6.3855 val_auc=0.7217
model=gat top_k=500 fold=8 epoch=18 loss=9.6979 val_auc=0.7291
model=gat top_k=500 fold=8 epoch=19 loss=7.6455 val_auc=0.7436
model=gat top_k=500 fold=8 epoch=20 loss=6.4735 val_auc=0.7566
model=gat top_k=500 fold=8 epoch=21 loss=8.3910 val_auc=0.7611
model=gat top_k=500 fold=8 epoch=22 loss=11.8477 val_auc=0.7675
model=gat top_k=500 fold=8 epoch=23 loss=7.2459 val_auc=0.7709
model=gat top_k=500 fold=8 epoch=24 loss=5.4433 val_auc=0.7734
model=gat top_k=500 fold=8 epoch=25 loss=6.7984 val_auc=0.7743
model=gat top_k=500 fold=8 epoch=26 loss=9.6056 val_auc=0.7817
model=gat top_k=500 fold=8 epoch=27 loss=8.9706 val_auc=0.7896
model=gat top_k=500 fold=8 epoch=28 loss=6.0816 val_auc=0.7909
model=gat top_k=500 fold=8 epoch=29 loss=6.3755 val_auc=0.7915
model=gat top_k=500 fold=8 epoch=30 loss=8.0811 val_auc=0.7923
model=gat top_k=500 fold=8 epoch=31 loss=7.8942 val_auc=0.7918
model=gat top_k=500 fold=8 epoch=32 loss=6.1925 val_auc=0.7921
model=gat top_k=500 fold=8 epoch=33 loss=6.1849 val_auc=0.7906
model=gat top_k=500 fold=8 epoch=34 loss=7.5251 val_auc=0.7891
model=gat top_k=500 fold=8 epoch=35 loss=11.6974 val_auc=0.7923
model=gat top_k=500 fold=8 epoch=36 loss=6.9411 val_auc=0.7974
model=gat top_k=500 fold=8 epoch=37 loss=5.1497 val_auc=0.7988
model=gat top_k=500 fold=8 epoch=38 loss=4.7283 val_auc=0.8006
model=gat top_k=500 fold=8 epoch=39 loss=6.2579 val_auc=0.8021
model=gat top_k=500 fold=8 epoch=40 loss=6.0014 val_auc=0.8037
model=gat top_k=500 fold=8 epoch=41 loss=5.4667 val_auc=0.8044
model=gat top_k=500 fold=8 epoch=42 loss=4.4435 val_auc=0.8047
model=gat top_k=500 fold=8 epoch=43 loss=4.3066 val_auc=0.8054
model=gat top_k=500 fold=8 epoch=44 loss=4.8721 val_auc=0.8062
model=gat top_k=500 fold=8 epoch=45 loss=6.5444 val_auc=0.8068
model=gat top_k=500 fold=8 epoch=46 loss=4.9319 val_auc=0.8067
model=gat top_k=500 fold=8 epoch=47 loss=4.7592 val_auc=0.8067
model=gat top_k=500 fold=8 epoch=48 loss=6.2368 val_auc=0.8070
model=gat top_k=500 fold=8 epoch=49 loss=4.7895 val_auc=0.8077
model=gat top_k=500 fold=8 epoch=50 loss=3.7368 val_auc=0.8087
model=gat top_k=500 fold=8 epoch=51 loss=4.7821 val_auc=0.8097
model=gat top_k=500 fold=8 epoch=52 loss=3.9754 val_auc=0.8101
model=gat top_k=500 fold=8 epoch=53 loss=4.0275 val_auc=0.8104
model=gat top_k=500 fold=8 epoch=54 loss=4.3840 val_auc=0.8113
model=gat top_k=500 fold=8 epoch=55 loss=4.7908 val_auc=0.8123
model=gat top_k=500 fold=8 epoch=56 loss=4.2552 val_auc=0.8134
model=gat top_k=500 fold=8 epoch=57 loss=3.2490 val_auc=0.8145
model=gat top_k=500 fold=8 epoch=58 loss=4.4538 val_auc=0.8147
model=gat top_k=500 fold=8 epoch=59 loss=4.6093 val_auc=0.8142
model=gat top_k=500 fold=8 epoch=60 loss=3.6361 val_auc=0.8153
model=gat top_k=500 fold=8 epoch=61 loss=3.7825 val_auc=0.8153
model=gat top_k=500 fold=8 epoch=62 loss=3.6204 val_auc=0.8153
model=gat top_k=500 fold=8 epoch=63 loss=3.9083 val_auc=0.8166
model=gat top_k=500 fold=8 epoch=64 loss=5.0290 val_auc=0.8164
model=gat top_k=500 fold=8 epoch=65 loss=4.0321 val_auc=0.8158
model=gat top_k=500 fold=8 epoch=66 loss=3.3705 val_auc=0.8166
model=gat top_k=500 fold=8 epoch=67 loss=4.1651 val_auc=0.8154
model=gat top_k=500 fold=8 epoch=68 loss=4.4989 val_auc=0.8132
model=gat top_k=500 fold=8 epoch=69 loss=3.5361 val_auc=0.8124
model=gat top_k=500 fold=8 epoch=70 loss=3.4834 val_auc=0.8145
model=gat top_k=500 fold=8 epoch=71 loss=3.0953 val_auc=0.8161
model=gat top_k=500 fold=8 epoch=72 loss=3.3490 val_auc=0.8183
model=gat top_k=500 fold=8 epoch=73 loss=3.8595 val_auc=0.8179
model=gat top_k=500 fold=8 epoch=74 loss=3.2911 val_auc=0.8176
model=gat top_k=500 fold=8 epoch=75 loss=3.4225 val_auc=0.8174
model=gat top_k=500 fold=8 epoch=76 loss=2.9325 val_auc=0.8190
model=gat top_k=500 fold=8 epoch=77 loss=3.4781 val_auc=0.8200
model=gat top_k=500 fold=8 epoch=78 loss=2.6673 val_auc=0.8212
model=gat top_k=500 fold=8 epoch=79 loss=2.7161 val_auc=0.8224
model=gat top_k=500 fold=8 epoch=80 loss=2.8059 val_auc=0.8238
model=gat top_k=500 fold=8 epoch=81 loss=2.8718 val_auc=0.8244
model=gat top_k=500 fold=8 epoch=82 loss=2.7550 val_auc=0.8248
model=gat top_k=500 fold=8 epoch=83 loss=2.9568 val_auc=0.8254
model=gat top_k=500 fold=8 epoch=84 loss=2.5653 val_auc=0.8258
model=gat top_k=500 fold=8 epoch=85 loss=2.6059 val_auc=0.8265
model=gat top_k=500 fold=8 epoch=86 loss=2.6845 val_auc=0.8267
model=gat top_k=500 fold=8 epoch=87 loss=2.6976 val_auc=0.8263
model=gat top_k=500 fold=8 epoch=88 loss=2.5581 val_auc=0.8257
model=gat top_k=500 fold=8 epoch=89 loss=2.6529 val_auc=0.8252
model=gat top_k=500 fold=8 epoch=90 loss=2.6252 val_auc=0.8246
model=gat top_k=500 fold=8 epoch=91 loss=2.2852 val_auc=0.8243
model=gat top_k=500 fold=8 epoch=92 loss=2.5048 val_auc=0.8246
model=gat top_k=500 fold=8 epoch=93 loss=2.3213 val_auc=0.8251
model=gat top_k=500 fold=8 epoch=94 loss=2.1678 val_auc=0.8255
model=gat top_k=500 fold=8 epoch=95 loss=1.9952 val_auc=0.8269
model=gat top_k=500 fold=8 epoch=96 loss=2.3710 val_auc=0.8273
model=gat top_k=500 fold=8 epoch=97 loss=2.1747 val_auc=0.8273
model=gat top_k=500 fold=8 epoch=98 loss=2.3702 val_auc=0.8269
model=gat top_k=500 fold=8 epoch=99 loss=2.3593 val_auc=0.8269
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 782047 edges

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=gat top_k=500 fold=9 =====
Config for gat: {'hidden_dim': 128, 'num_layers': 2, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 100, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 781970 edges
model=gat top_k=500 fold=9 epoch=0 loss=16.0975 val_auc=0.5014
model=gat top_k=500 fold=9 epoch=1 loss=104.2703 val_auc=0.6657

/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))
/tmp/ipykernel_384487/2878965116.py:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-logits))

model=gat top_k=500 fold=9 epoch=2 loss=13.1837 val_auc=0.7006
model=gat top_k=500 fold=9 epoch=3 loss=50.9471 val_auc=0.7271
model=gat top_k=500 fold=9 epoch=4 loss=39.8697 val_auc=0.7100
model=gat top_k=500 fold=9 epoch=5 loss=12.5535 val_auc=0.5051
model=gat top_k=500 fold=9 epoch=6 loss=25.7297 val_auc=0.5351
model=gat top_k=500 fold=9 epoch=7 loss=23.3941 val_auc=0.7357
model=gat top_k=500 fold=9 epoch=8 loss=10.8504 val_auc=0.7444
model=gat top_k=500 fold=9 epoch=9 loss=14.2180 val_auc=0.7434
model=gat top_k=500 fold=9 epoch=10 loss=19.4800 val_auc=0.7451
model=gat top_k=500 fold=9 epoch=11 loss=14.7268 val_auc=0.7458
model=gat top_k=500 fold=9 epoch=12 loss=9.8011 val_auc=0.7413
model=gat top_k=500 fold=9 epoch=13 loss=12.0183 val_auc=0.7108
model=gat top_k=500 fold=9 epoch=14 loss=15.4771 val_auc=0.7320
model=gat top_k=500 fold=9 epoch=15 loss=12.4795 val_auc=0.7468
model=gat top_k=500 fold=9 epoch=16 loss=8.8451 val_auc=0.7513
model=gat top_k=500 fold=9 epoch=17 loss=8.6819 val_auc=0.7526
model=gat top_k=500 fold=9 epoch=18 loss=7.6282 val_auc=0.7554
model=gat top_k=500 fold=9 epoch=19 loss=13.4608 val_auc=0.7591
model=gat top_k=500 fold=9 epoch=20 loss=8.4229 val_auc=0.7646
model=gat top_k=500 fold=9 epoch=21 loss=7.6281 val_auc=0.7689
model=gat top_k=500 fold=9 epoch=22 loss=9.3761 val_auc=0.7723
model=gat top_k=500 fold=9 epoch=23 loss=7.5130 val_auc=0.7759
model=gat top_k=500 fold=9 epoch=24 loss=7.9621 val_auc=0.7808
model=gat top_k=500 fold=9 epoch=25 loss=7.6751 val_auc=0.7850
model=gat top_k=500 fold=9 epoch=26 loss=6.8819 val_auc=0.7881
model=gat top_k=500 fold=9 epoch=27 loss=7.6516 val_auc=0.7900
model=gat top_k=500 fold=9 epoch=28 loss=8.3403 val_auc=0.7902
model=gat top_k=500 fold=9 epoch=29 loss=6.1885 val_auc=0.7924
model=gat top_k=500 fold=9 epoch=30 loss=7.2388 val_auc=0.7940
model=gat top_k=500 fold=9 epoch=31 loss=6.4266 val_auc=0.7945
model=gat top_k=500 fold=9 epoch=32 loss=7.4969 val_auc=0.7944
model=gat top_k=500 fold=9 epoch=33 loss=6.2355 val_auc=0.7949
model=gat top_k=500 fold=9 epoch=34 loss=5.6959 val_auc=0.7951
model=gat top_k=500 fold=9 epoch=35 loss=6.4408 val_auc=0.7945
model=gat top_k=500 fold=9 epoch=36 loss=7.8465 val_auc=0.7941
model=gat top_k=500 fold=9 epoch=37 loss=6.3214 val_auc=0.7936
model=gat top_k=500 fold=9 epoch=38 loss=4.9567 val_auc=0.7942
model=gat top_k=500 fold=9 epoch=39 loss=5.6933 val_auc=0.7924
model=gat top_k=500 fold=9 epoch=40 loss=9.6548 val_auc=0.7927
model=gat top_k=500 fold=9 epoch=41 loss=7.1923 val_auc=0.7948
model=gat top_k=500 fold=9 epoch=42 loss=5.4530 val_auc=0.7928
model=gat top_k=500 fold=9 epoch=43 loss=5.8469 val_auc=0.7909
model=gat top_k=500 fold=9 epoch=44 loss=6.6954 val_auc=0.7918
model=gat top_k=500 fold=9 epoch=45 loss=4.6133 val_auc=0.7922
model=gat top_k=500 fold=9 epoch=46 loss=6.4099 val_auc=0.7921
gat top_k=500 fold=9: early stopping at epoch 46
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 781970 edges

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/35 [00:00<?, ?it/s]

,fold,method,disease_macro_auroc,disease_macro_auprc,disease_macro_f1,all_macro_auroc,all_macro_auprc,all_macro_f1,num_scored_labels,model_name,...,include_has_finding_in_message_passing,model_path,best_epoch,best_val_disease_macro_auroc,hidden_dim,num_layers,num_heads,max_train_similar_edges_per_node,threshold_mode,metrics_path
0,0,hetero_graphsage,0.767383,0.144593,0.186127,0.768346,0.193313,0.229433,14,graphsage,...,False,/data/liangz2/openi/multi_kg/kg_non_transforme...,99,0.823203,256,2,1,NaN,fixed_0.5,/data/liangz2/openi/multi_kg/kg_non_transforme...
1,0,hetero_graphsage,0.767383,0.144593,0.170041,0.768346,0.193313,0.215921,14,graphsage,...,False,/data/liangz2/openi/multi_kg/kg_non_transforme...,99,0.823203,256,2,1,NaN,val_tuned_f1,/data/liangz2/openi/multi_kg/kg_non_transforme...
2,1,hetero_graphsage,0.775836,0.147896,0.170219,0.733929,0.171826,0.212334,14,graphsage,...,False,/data/liangz2/openi/multi_kg/kg_non_transforme...,50,0.821555,256,2,1,NaN,fixed_0.5,/data/liangz2/openi/multi_kg/kg_non_transforme...
3,1,hetero_graphsage,0.775836,0.147896,0.197041,0.733929,0.171826,0.239451,14,graphsage,...,False,/data/liangz2/openi/multi_kg/kg_non_transforme...,50,0.821555,256,2,1,NaN,val_tuned_f1,/data/liangz2/openi/multi_kg/kg_non_transforme...
4,2,hetero_graphsage,0.765188,0.142824,0.184764,0.764647,0.189922,0.228261,14,graphsage,...,False,/data/liangz2/openi/multi_kg/kg_non_transforme...,99,0.822643,256,2,1,NaN,fixed_0.5,/data/liangz2/openi/multi_kg/kg_non_transforme...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,7,hetero_gat,0.683165,0.130537,0.148773,0.685630,0.178094,0.194619,14,gat,...,False,/data/liangz2/openi/multi_kg/kg_non_transforme...,44,0.810033,128,2,2,100.0,val_tuned_f1,/data/liangz2/openi/multi_kg/kg_non_transforme...
236,8,hetero_gat,0.692756,0.132774,0.000000,0.674824,0.165532,0.056497,14,gat,...,False,/data/liangz2/openi/multi_kg/kg_non_transforme...,96,0.827331,128,2,2,100.0,fixed_0.5,/data/liangz2/openi/multi_kg/kg_non_transforme...
237,8,hetero_gat,0.692756,0.132774,0.002355,0.674824,0.165532,0.058683,14,gat,...,False,/data/liangz2/openi/multi_kg/kg_non_transforme...,96,0.827331,128,2,2,100.0,val_tuned_f1,/data/liangz2/openi/multi_kg/kg_non_transforme...
238,9,hetero_gat,0.725849,0.134945,0.001817,0.694397,0.162270,0.031871,14,gat,...,False,/data/liangz2/openi/multi_kg/kg_non_transforme...,34,0.795112,128,2,2,100.0,fixed_0.5,/data/liangz2/openi/multi_kg/kg_non_transforme...
239,9,hetero_gat,0.725849,0.134945,0.002937,0.694397,0.162270,0.059212,14,gat,...,False,/data/liangz2/openi/multi_kg/kg_non_transforme...,34,0.795112,128,2,2,100.0,val_tuned_f1,/data/liangz2/openi/multi_kg/kg_non_transforme...

## Aggregate Results for Tables

In [9]:
def collect_non_transformer_gnn_results(output_root: Path) -> pd.DataFrame:
    candidate_files = []
    final_path = output_root / "non_transformer_gnn_10fold_all_results.csv"
    progress_path = output_root / "non_transformer_gnn_10fold_all_results_progress.csv"
    if final_path.exists():
        candidate_files.append(final_path)
    if progress_path.exists():
        candidate_files.append(progress_path)
    candidate_files.extend(sorted(output_root.glob("*/top_k_*/*_10fold_summary.csv")))
    candidate_files.extend(sorted(output_root.glob("*/top_k_*/*_10fold_summary_progress.csv")))
    candidate_files.extend(sorted(output_root.glob("*/top_k_*/fold*/metrics/*_method_summary.csv")))

    frames = []
    seen = set()
    for path in candidate_files:
        if path in seen or not path.exists():
            continue
        seen.add(path)
        try:
            frame = pd.read_csv(path)
        except Exception as exc:
            print(f"Skipping unreadable file {path}: {exc}")
            continue
        if frame.empty or "fold" not in frame.columns or "threshold_mode" not in frame.columns:
            continue
        if "model_name" not in frame.columns:
            try:
                frame["model_name"] = path.relative_to(output_root).parts[0]
            except Exception:
                frame["model_name"] = frame.get("method", "unknown")
        if "query_top_k" not in frame.columns:
            top_k = None
            for part in path.parts:
                if part.startswith("top_k_"):
                    top_k = int(part.split("top_k_", 1)[1])
                    break
            frame["query_top_k"] = top_k
        frame["source_file"] = str(path)
        frames.append(frame)

    if not frames:
        raise FileNotFoundError(
            "No non-transformer GNN result files found. Run at least one fold first. "
            f"Searched under: {output_root}"
        )

    results = pd.concat(frames, ignore_index=True)
    key_cols = [c for c in ["model_name", "query_top_k", "fold", "threshold_mode"] if c in results.columns]
    if key_cols:
        results = results.sort_values("source_file").drop_duplicates(subset=key_cols, keep="last")
    return results.reset_index(drop=True)


results = collect_non_transformer_gnn_results(OUTPUT_ROOT)
all_results_path = OUTPUT_ROOT / "non_transformer_gnn_10fold_all_results_collected.csv"
results.to_csv(all_results_path, index=False)
print("Collected rows:", len(results))
print("Saved collected long table:", all_results_path)

metric_cols = [
    "disease_macro_auroc", "disease_macro_auprc", "disease_macro_f1",
    "all_macro_auroc", "all_macro_auprc", "all_macro_f1",
]
summary_rows = []
for (model_name, query_top_k, threshold_mode), group in results.groupby(["model_name", "query_top_k", "threshold_mode"], sort=True):
    row = {
        "model_name": model_name,
        "method": group["method"].iloc[0] if "method" in group.columns else f"hetero_{model_name}",
        "query_top_k": int(query_top_k),
        "threshold_mode": threshold_mode,
        "n_folds": int(group["fold"].nunique()),
        "completed_folds": ",".join(str(int(x)) for x in sorted(group["fold"].dropna().unique())),
        "include_has_finding_in_message_passing": bool(group["include_has_finding_in_message_passing"].iloc[0]) if "include_has_finding_in_message_passing" in group.columns else False,
    }
    for metric in metric_cols:
        row[f"{metric}_mean"] = group[metric].mean()
        row[f"{metric}_std"] = group[metric].std(ddof=1)
    summary_rows.append(row)

aggregate = pd.DataFrame(summary_rows)
aggregate_path = OUTPUT_ROOT / "non_transformer_gnn_10fold_aggregate_summary.csv"
aggregate.to_csv(aggregate_path, index=False)
print("Saved aggregate summary:", aggregate_path)
display(aggregate.sort_values(["threshold_mode", "disease_macro_auroc_mean"], ascending=[True, False]))

Collected rows: 240
Saved collected long table: /data/liangz2/openi/multi_kg/kg_non_transformer_gnn_10fold/non_transformer_gnn_10fold_all_results_collected.csv
Saved aggregate summary: /data/liangz2/openi/multi_kg/kg_non_transformer_gnn_10fold/non_transformer_gnn_10fold_aggregate_summary.csv

,model_name,method,query_top_k,threshold_mode,n_folds,completed_folds,include_has_finding_in_message_passing,disease_macro_auroc_mean,disease_macro_auroc_std,disease_macro_auprc_mean,disease_macro_auprc_std,disease_macro_f1_mean,disease_macro_f1_std,all_macro_auroc_mean,all_macro_auroc_std,all_macro_auprc_mean,all_macro_auprc_std,all_macro_f1_mean,all_macro_f1_std
22,graphsage,hetero_graphsage,500,fixed_0.5,10,"0,1,2,3,4,5,6,7,8,9",False,0.770312,0.004826,0.145194,0.004379,0.134401,0.061763,0.764076,0.011968,0.189450,0.008952,0.165037,0.071761
20,graphsage,hetero_graphsage,200,fixed_0.5,10,"0,1,2,3,4,5,6,7,8,9",False,0.769437,0.007617,0.147647,0.005284,0.108766,0.047124,0.759904,0.024850,0.190986,0.014857,0.147702,0.066470
18,graphsage,hetero_graphsage,100,fixed_0.5,10,"0,1,2,3,4,5,6,7,8,9",False,0.769413,0.005545,0.145746,0.004478,0.110763,0.044060,0.761882,0.017911,0.190231,0.012258,0.154719,0.049699
16,graphsage,hetero_graphsage,50,fixed_0.5,10,"0,1,2,3,4,5,6,7,8,9",False,0.766751,0.011642,0.145905,0.003310,0.144871,0.055372,0.748913,0.025447,0.183456,0.012521,0.185412,0.067853
8,gcn,hetero_gcn,50,fixed_0.5,10,"0,1,2,3,4,5,6,7,8,9",False,0.762297,0.015368,0.150151,0.006475,0.168626,0.021218,0.759897,0.020167,0.196583,0.008436,0.215162,0.020249
12,gcn,hetero_gcn,200,fixed_0.5,10,"0,1,2,3,4,5,6,7,8,9",False,0.757254,0.013574,0.146498,0.008222,0.157832,0.043358,0.750847,0.017759,0.190066,0.010931,0.198272,0.051373
10,gcn,hetero_gcn,100,fixed_0.5,10,"0,1,2,3,4,5,6,7,8,9",False,0.754530,0.011509,0.145221,0.005601,0.132304,0.037240,0.745765,0.014729,0.187355,0.008598,0.174704,0.043743
14,gcn,hetero_gcn,500,fixed_0.5,10,"0,1,2,3,4,5,6,7,8,9",False,0.752979,0.012808,0.143852,0.005921,0.127808,0.059312,0.747090,0.013255,0.188263,0.005601,0.166527,0.064491
6,gat,hetero_gat,500,fixed_0.5,10,"0,1,2,3,4,5,6,7,8,9",False,0.730210,0.026128,0.138274,0.006391,0.116021,0.068739,0.702407,0.016709,0.167954,0.005548,0.161622,0.069036
0,gat,hetero_gat,50,fixed_0.5,10,"0,1,2,3,4,5,6,7,8,9",False,0.727393,0.026876,0.141167,0.003771,0.095064,0.062343,0.704234,0.019701,0.173140,0.009171,0.136232,0.061159
4,gat,hetero_gat,200,fixed_0.5,10,"0,1,2,3,4,5,6,7,8,9",False,0.726445,0.029022,0.134153,0.007917,0.054136,0.050262,0.695467,0.024880,0.162374,0.007763,0.106743,0.046688
2,gat,hetero_gat,100,fixed_0.5,10,"0,1,2,3,4,5,6,7,8,9",False,0.720304,0.052672,0.134891,0.009712,0.061450,0.051603,0.689862,0.036612,0.163643,0.006375,0.084605,0.056436
23,graphsage,hetero_graphsage,500,val_tuned_f1,10,"0,1,2,3,4,5,6,7,8,9",False,0.770312,0.004826,0.145194,0.004379,0.128494,0.065424,0.764076,0.011968,0.189450,0.008952,0.176818,0.060211
21,graphsage,hetero_graphsage,200,val_tuned_f1,10,"0,1,2,3,4,5,6,7,8,9",False,0.769437,0.007617,0.147647,0.005284,0.153124,0.058707,0.759904,0.024850,0.190986,0.014857,0.189295,0.076933
19,graphsage,hetero_graphsage,100,val_tuned_f1,10,"0,1,2,3,4,5,6,7,8,9",False,0.769413,0.005545,0.145746,0.004478,0.143382,0.049689,0.761882,0.017911,0.190231,0.012258,0.185595,0.048973
17,graphsage,hetero_graphsage,50,val_tuned_f1,10,"0,1,2,3,4,5,6,7,8,9",False,0.766751,0.011642,0.145905,0.003310,0.159182,0.046472,0.748913,0.025447,0.183456,0.012521,0.199374,0.060278
9,gcn,hetero_gcn,50,val_tuned_f1,10,"0,1,2,3,4,5,6,7,8,9",False,0.762297,0.015368,0.150151,0.006475,0.164654,0.022898,0.759897,0.020167,0.196583,0.008436,0.211786,0.021730
13,gcn,hetero_gcn,200,val_tuned_f1,10,"0,1,2,3,4,5,6,7,8,9",False,0.757254,0.013574,0.146498,0.008222,0.156638,0.036476,0.750847,0.017759,0.190066,0.010931,0.197727,0.045010
11,gcn,hetero_gcn,100,val_tuned_f1,10,"0,1,2,3,4,5,6,7,8,9",False,0.754530,0.011509,0.145221,0.005601,0.142935,0.029259,0.745765,0.014729,0.187355,0.008598,0.189323,0.027737
15,gcn,hetero_gcn,500,val_tuned_f1,10,"0,1,2,3,4,5,6,7,8,9",False,0.752979,0.012808,0.143852,0.005921,0.116495,0.044103,0.747090,0.013255,0.188263,0.005601,0.162136,0.044484
7,gat,hetero_gat,500,val_tuned_f1,10,"0,1,2,3,4,5,6,7,8,9",False,0.730210,0.026128,0.138274,0.006391,0.086485,0.073140,0.702407,0.016709,0.167954,0.005548,0.136795,0.067913
1,gat,hetero_gat,50,val_tuned_f1,10,"0,1,2,3,4,5,6,7,8,9",False,0.727393,0.026876,0.141167,0.003771,0.083436,0.074239,0.704234,0.019701,0.173140,0.009171,0.131815,0.068797
5,gat,hetero_gat,200,val_tuned_f1,10,"0,1,2,3,4,5,6,7,8,9",False,0.726445,0.029022,0.134153,0.007917,0.049447,0.065659,0.695467,0.024880,0.162374,0.007763,0.096755,0.067917
3,gat,hetero_gat,100,val_tuned_f1,10,"0,1,2,3,4,5,6,7,8,9",False,0.720304,0.052672,0.134891,0.009712,0.061560,0.055959,0.689862,0.036612,0.163643,0.006375,0.103918,0.061979

## Notes

For paper tables, compare this notebook against:

- BiomedCLIP zero-shot and BiomedCLIP + MLP.
- FAISS retrieval and BiomedCLIP + FAISS fusion.
- GraphSAGE results from the earlier dedicated notebook.
- Transformer-GNN variants: HGTConv, HANConv, TransformerConv.

Use `fixed_0.5` as the primary operating-point comparison and AUROC/AUPRC as ranking metrics. Use `val_tuned_f1` only for threshold-calibrated F1.