# 10-Fold Transformer-Based Heterogeneous GNN Training for CXR KG

This notebook extends `hetero_graphsage_10fold_training.ipynb` by testing transformer-style GNN layers on the same fold-specific chest X-ray knowledge graphs.

Ablations:

- `HGTConv`: heterogeneous graph transformer.
- `HANConv`: heterogeneous attention network.
- `TransformerConv`: edge-type-specific transformer convolution wrapped by `HeteroConv`.
- Query retrieval `top_k`: `50`, `100`, `200`, `500`.

Outputs are saved under `/data/liangz2/openi/multi_kg/kg_transformer_gnn_10fold/{model_name}/top_k_{k}/fold{fold}/` so each model/top-k/fold run is isolated and resumable.

In [1]:
# Optional dependency installation. Set True only in a fresh cloud environment.
INSTALL_DEPS = False

if INSTALL_DEPS:
    import subprocess
    import sys
    packages = [
        "torch",
        "torch_geometric",
        "faiss-cpu",
        "scikit-learn",
        "pandas",
        "numpy",
        "tqdm",
    ]
    subprocess.check_call([sys.executable, "-m", "pip", "install", *packages])

In [2]:
import copy
import json
import random
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
from tqdm.auto import tqdm

import torch
import torch.nn as nn
import torch.nn.functional as F

from sklearn.metrics import average_precision_score, f1_score, roc_auc_score

try:
    from torch_geometric.data import HeteroData
    from torch_geometric.nn import HeteroConv, HGTConv, HANConv, TransformerConv
except ImportError as exc:
    raise ImportError(
        "Install torch_geometric before running this notebook. "
        "In your diffuser2 environment, try: pip install torch_geometric faiss-cpu"
    ) from exc

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

DATA_ROOT = Path("/data/liangz2/openi/multi_kg") if Path("/data/liangz2/openi/multi_kg").exists() else Path.cwd()
KG_10FOLD_DIR = DATA_ROOT / "kg_10fold"
OUTPUT_ROOT = DATA_ROOT / "kg_transformer_gnn_10fold"
OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)

# Main ablation settings.
MODEL_NAMES = ["hgtconv", "hanconv", "transformerconv"]
QUERY_TOP_K_VALUES = [50, 100, 200, 500]
FOLD_INDICES = list(range(10))

SKIP_COMPLETED = True
FORCE_RERUN = []  # Optional list of (model_name, top_k, fold), e.g. [("hgtconv", 100, 0)]

# Training config. These are the defaults for HGT/HAN.
VAL_FRAC = 0.10
HIDDEN_DIM = 256
NUM_LAYERS = 2
NUM_HEADS = 4
DROPOUT = 0.20
LR = 1e-3
WEIGHT_DECAY = 1e-4
EPOCHS = 100
PATIENCE = 12
GRAD_CLIP_NORM = 5.0

# Per-model overrides. TransformerConv is much more memory intensive because it
# computes attention per edge type, especially on image-image similar_to edges.
# Keep the transformerconv setting conservative first; increase later only if it fits.
MODEL_CONFIGS = {
    "hgtconv": {
        "hidden_dim": HIDDEN_DIM,
        "num_layers": NUM_LAYERS,
        "num_heads": NUM_HEADS,
        "dropout": DROPOUT,
        "max_train_similar_edges_per_node": None,
        "query_inference_chunk_size": QUERY_INFERENCE_CHUNK_SIZE if "QUERY_INFERENCE_CHUNK_SIZE" in globals() else 512,
    },
    "hanconv": {
        "hidden_dim": HIDDEN_DIM,
        "num_layers": NUM_LAYERS,
        "num_heads": NUM_HEADS,
        "dropout": DROPOUT,
        "max_train_similar_edges_per_node": None,
        "query_inference_chunk_size": QUERY_INFERENCE_CHUNK_SIZE if "QUERY_INFERENCE_CHUNK_SIZE" in globals() else 512,
    },
    "transformerconv": {
        "hidden_dim": 128,
        "num_layers": 1,
        "num_heads": 2,
        "dropout": DROPOUT,
        "max_train_similar_edges_per_node": 50,
        "query_inference_chunk_size": 128,
    },
}


def get_model_config(model_name: str) -> Dict:
    base = {
        "hidden_dim": HIDDEN_DIM,
        "num_layers": NUM_LAYERS,
        "num_heads": NUM_HEADS,
        "dropout": DROPOUT,
        "max_train_similar_edges_per_node": None,
        "query_inference_chunk_size": QUERY_INFERENCE_CHUNK_SIZE if "QUERY_INFERENCE_CHUNK_SIZE" in globals() else 512,
    }
    base.update(MODEL_CONFIGS.get(model_name.lower(), {}))
    return base

# Decoding config.
DECODER = "dot"  # "dot" or "mlp"

# Query inference config.
TEST_QUERY_BATCH_SIZE = 512
QUERY_INFERENCE_CHUNK_SIZE = 512

# Leakage control. Keep False for the primary experiment.
INCLUDE_HAS_FINDING_IN_MESSAGE_PASSING = False

SCORING_LABELS = (
    "normal",
    "enlarged cardiomediastinum", "cardiomegaly", "lung opacity", "lung lesion", "edema",
    "consolidation", "pneumonia", "atelectasis", "pneumothorax",
    "pleural effusion", "pleural other", "fracture", "support devices",
)
TARGET_COLUMNS = ["y_" + label.replace(" ", "_") for label in SCORING_LABELS]
FINDING_LABELS = SCORING_LABELS[1:]

print("DEVICE", DEVICE)
print("DATA_ROOT", DATA_ROOT)
print("KG_10FOLD_DIR", KG_10FOLD_DIR)
print("OUTPUT_ROOT", OUTPUT_ROOT)
print("MODEL_NAMES", MODEL_NAMES)
print("QUERY_TOP_K_VALUES", QUERY_TOP_K_VALUES)
print("INCLUDE_HAS_FINDING_IN_MESSAGE_PASSING", INCLUDE_HAS_FINDING_IN_MESSAGE_PASSING)

DEVICE cuda
DATA_ROOT /data/liangz2/openi/multi_kg
KG_10FOLD_DIR /data/liangz2/openi/multi_kg/kg_10fold
OUTPUT_ROOT /data/liangz2/openi/multi_kg/kg_transformer_gnn_10fold
MODEL_NAMES ['hgtconv', 'hanconv', 'transformerconv']
QUERY_TOP_K_VALUES [50, 100, 200, 500]
INCLUDE_HAS_FINDING_IN_MESSAGE_PASSING False

## Metrics and Utility Functions

In [3]:
def sigmoid_np(logits: np.ndarray) -> np.ndarray:
    return 1.0 / (1.0 + np.exp(-logits))


def evaluate_prob_matrix(probs: np.ndarray, targets: np.ndarray, thresholds: Optional[np.ndarray] = None) -> pd.DataFrame:
    y = targets.astype(int)
    if thresholds is None:
        thresholds = np.full((probs.shape[1],), 0.5, dtype=np.float32)
    rows = []
    for j, label in enumerate(SCORING_LABELS):
        if len(np.unique(y[:, j])) < 2:
            continue
        pred = (probs[:, j] >= thresholds[j]).astype(int)
        rows.append({
            "label": label,
            "auroc": roc_auc_score(y[:, j], probs[:, j]),
            "auprc": average_precision_score(y[:, j], probs[:, j]),
            "f1": f1_score(y[:, j], pred, zero_division=0),
            "threshold": float(thresholds[j]),
            "support": int(y[:, j].sum()),
        })
    return pd.DataFrame(rows)


def macro_metric(metrics: pd.DataFrame, metric: str = "auroc", disease_only: bool = True) -> float:
    if metrics.empty:
        return float("nan")
    frame = metrics[metrics["label"] != "normal"] if disease_only else metrics
    if frame.empty:
        return float("nan")
    return float(frame[metric].mean())


def tune_f1_thresholds(probs: np.ndarray, targets: np.ndarray, grid: Optional[np.ndarray] = None) -> np.ndarray:
    if grid is None:
        grid = np.linspace(0.01, 0.99, 99)
    thresholds = np.full((probs.shape[1],), 0.5, dtype=np.float32)
    y = targets.astype(int)
    for j in range(probs.shape[1]):
        if len(np.unique(y[:, j])) < 2:
            continue
        best_f1, best_thr = -1.0, 0.5
        for thr in grid:
            pred = (probs[:, j] >= thr).astype(int)
            value = f1_score(y[:, j], pred, zero_division=0)
            if value > best_f1:
                best_f1, best_thr = value, float(thr)
        thresholds[j] = best_thr
    return thresholds


def metric_summary(metrics: pd.DataFrame, fold: int, method: str, extra: Optional[Dict] = None) -> Dict:
    disease = metrics[metrics["label"] != "normal"] if not metrics.empty else metrics
    out = {
        "fold": int(fold),
        "method": method,
        "disease_macro_auroc": float(disease["auroc"].mean()) if len(disease) else float("nan"),
        "disease_macro_auprc": float(disease["auprc"].mean()) if len(disease) else float("nan"),
        "disease_macro_f1": float(disease["f1"].mean()) if len(disease) else float("nan"),
        "all_macro_auroc": float(metrics["auroc"].mean()) if len(metrics) else float("nan"),
        "all_macro_auprc": float(metrics["auprc"].mean()) if len(metrics) else float("nan"),
        "all_macro_f1": float(metrics["f1"].mean()) if len(metrics) else float("nan"),
        "num_scored_labels": int(len(metrics)),
    }
    if extra:
        out.update(extra)
    return out


def save_json(obj: Dict, path: Path) -> None:
    path.write_text(json.dumps(obj, indent=2, default=str), encoding="utf-8")

## Load Fold Graphs

The fold graph is expected at `kg_10fold/fold{i}/kg_heterodata_fold{i}.pt`. The graph should contain training image nodes and their labels. Test images are added later as query nodes connected only through `similar_to` retrieval edges.

In [4]:
def torch_load_any(path: Path, map_location="cpu"):
    try:
        return torch.load(path, map_location=map_location, weights_only=False)
    except TypeError:
        return torch.load(path, map_location=map_location)


def dict_to_heterodata(obj: Dict) -> HeteroData:
    data = HeteroData()
    for node_type, x in obj.get("x_dict", {}).items():
        data[node_type].x = x.float()
        node_ids = obj.get("node_ids", {}).get(node_type)
        if node_ids is not None:
            data[node_type].node_id = list(node_ids)
        if node_type in obj.get("y_dict", {}):
            data[node_type].y = obj["y_dict"][node_type].float()
    for etype, edge_index in obj.get("edge_index_dict", {}).items():
        data[etype].edge_index = edge_index.long()
        edge_weight = obj.get("edge_weight_dict", {}).get(etype)
        if edge_weight is not None:
            data[etype].edge_weight = edge_weight.float()
    return data


def load_fold_data(fold: int) -> Tuple[HeteroData, pd.DataFrame, pd.DataFrame, np.ndarray]:
    fold_dir = KG_10FOLD_DIR / f"fold{fold}"
    kg_path = fold_dir / f"kg_heterodata_fold{fold}.pt"
    train_meta_path = fold_dir / f"train_metadata_fold{fold}.csv"
    test_meta_path = fold_dir / f"test_query_metadata_fold{fold}.csv"
    test_emb_path = fold_dir / f"test_query_embeddings_fold{fold}.npy"
    if not kg_path.exists():
        raise FileNotFoundError(f"Missing fold KG file: {kg_path}")
    obj = torch_load_any(kg_path, map_location="cpu")
    data = obj if isinstance(obj, HeteroData) else dict_to_heterodata(obj)
    train_df = pd.read_csv(train_meta_path)
    test_df = pd.read_csv(test_meta_path)
    test_embeddings = np.load(test_emb_path).astype("float32")
    return data, train_df, test_df, test_embeddings


def label_names_from_data(data: HeteroData) -> List[str]:
    if hasattr(data["label"], "label_name"):
        return [str(x) for x in data["label"].label_name]
    if hasattr(data["label"], "node_id"):
        names = []
        for node_id in data["label"].node_id:
            text = str(node_id)
            names.append(text.split("label::", 1)[-1] if text.startswith("label::") else text)
        return names
    raise RuntimeError("Label node names are missing from HeteroData. Regenerate KG with label_name/node_id metadata.")


def label_indices_for_scoring(data: HeteroData) -> List[int]:
    label_names = label_names_from_data(data)
    lookup = {name: i for i, name in enumerate(label_names)}
    missing = [label for label in SCORING_LABELS if label not in lookup]
    if missing:
        raise RuntimeError(f"Missing label nodes: {missing}. Available labels: {label_names}")
    return [lookup[label] for label in SCORING_LABELS]


def split_train_val_indices(num_images: int, val_frac: float, seed: int) -> Tuple[torch.Tensor, torch.Tensor]:
    rng = np.random.default_rng(seed)
    indices = np.arange(num_images)
    rng.shuffle(indices)
    val_size = max(1, int(round(num_images * val_frac)))
    val_idx = np.sort(indices[:val_size])
    train_idx = np.sort(indices[val_size:])
    return torch.from_numpy(train_idx).long(), torch.from_numpy(val_idx).long()

## Transformer-Based Heterogeneous GNN Models

All three models share the same input projections and image-label decoder. The difference is the message-passing layer:

- `HGTConv`: native heterogeneous graph transformer.
- `HANConv`: semantic attention over heterogeneous neighborhoods.
- `TransformerConv`: per-edge-type transformer convolution inside `HeteroConv`.

The `has_finding` and `rev_has_finding` edges are excluded from message passing by default to avoid label leakage. They remain supervision targets only.

In [5]:
def merge_layer_output(prev_z: Dict[str, torch.Tensor], out_z: Dict[str, torch.Tensor], norm_dict: nn.ModuleDict, dropout: float, training: bool) -> Dict[str, torch.Tensor]:
    next_z = {}
    for node_type, x in prev_z.items():
        y = out_z.get(node_type)
        if y is None:
            next_z[node_type] = x
            continue
        y = F.relu(y)
        y = norm_dict[node_type](y)
        y = F.dropout(y, p=dropout, training=training)
        next_z[node_type] = x + y if x.shape == y.shape else y
    return next_z


class BaseImageLabelDecoder(nn.Module):
    def _init_decoder(self, hidden_dim: int, dropout: float, decoder: str):
        self.decoder = decoder
        if decoder == "mlp":
            self.decoder_mlp = nn.Sequential(
                nn.Linear(2 * hidden_dim, hidden_dim),
                nn.ReLU(),
                nn.Dropout(dropout),
                nn.Linear(hidden_dim, 1),
            )
        elif decoder != "dot":
            raise ValueError(f"Unknown decoder: {decoder}")

    def decode_image_label_logits(self, z_dict, label_indices: Sequence[int]) -> torch.Tensor:
        image_z = z_dict["image"]
        label_z = z_dict["label"][torch.as_tensor(label_indices, device=image_z.device)]
        if self.decoder == "dot":
            return image_z @ label_z.t()
        image_expanded = image_z[:, None, :].expand(-1, len(label_indices), -1)
        label_expanded = label_z[None, :, :].expand(image_z.size(0), -1, -1)
        pair = torch.cat([image_expanded, label_expanded], dim=-1)
        return self.decoder_mlp(pair).squeeze(-1)


def make_hgt_conv(hidden_dim: int, metadata, heads: int):
    try:
        return HGTConv(hidden_dim, hidden_dim, metadata, heads=heads, group="sum")
    except TypeError as exc:
        # Older torch_geometric versions do not expose the HGTConv group argument.
        if "group" in str(exc):
            return HGTConv(hidden_dim, hidden_dim, metadata, heads=heads)
        raise


class HeteroHGT(BaseImageLabelDecoder):
    def __init__(self, metadata, input_dims: Dict[str, int], hidden_dim=HIDDEN_DIM, num_layers=NUM_LAYERS, heads=NUM_HEADS, dropout=DROPOUT, decoder=DECODER):
        super().__init__()
        node_types, edge_types = metadata
        self.dropout = dropout
        self.proj = nn.ModuleDict({node_type: nn.Linear(int(input_dims[node_type]), hidden_dim) for node_type in node_types if node_type in input_dims})
        self.convs = nn.ModuleList([make_hgt_conv(hidden_dim, metadata, heads) for _ in range(num_layers)])
        self.norms = nn.ModuleList([nn.ModuleDict({node_type: nn.LayerNorm(hidden_dim) for node_type in self.proj}) for _ in range(num_layers)])
        self._init_decoder(hidden_dim, dropout, decoder)

    def forward(self, x_dict, edge_index_dict):
        z = {node_type: F.relu(self.proj[node_type](x.float())) for node_type, x in x_dict.items() if node_type in self.proj}
        for conv, norm_dict in zip(self.convs, self.norms):
            out = conv(z, edge_index_dict)
            z = merge_layer_output(z, out, norm_dict, self.dropout, self.training)
        return z


class HeteroHAN(BaseImageLabelDecoder):
    def __init__(self, metadata, input_dims: Dict[str, int], hidden_dim=HIDDEN_DIM, num_layers=NUM_LAYERS, heads=NUM_HEADS, dropout=DROPOUT, decoder=DECODER):
        super().__init__()
        node_types, edge_types = metadata
        self.dropout = dropout
        self.proj = nn.ModuleDict({node_type: nn.Linear(int(input_dims[node_type]), hidden_dim) for node_type in node_types if node_type in input_dims})
        in_channels = {node_type: hidden_dim for node_type in node_types if node_type in input_dims}
        self.convs = nn.ModuleList([HANConv(in_channels, hidden_dim, metadata=metadata, heads=heads, dropout=dropout) for _ in range(num_layers)])
        self.norms = nn.ModuleList([nn.ModuleDict({node_type: nn.LayerNorm(hidden_dim) for node_type in self.proj}) for _ in range(num_layers)])
        self._init_decoder(hidden_dim, dropout, decoder)

    def forward(self, x_dict, edge_index_dict):
        z = {node_type: F.relu(self.proj[node_type](x.float())) for node_type, x in x_dict.items() if node_type in self.proj}
        for conv, norm_dict in zip(self.convs, self.norms):
            out = conv(z, edge_index_dict)
            z = merge_layer_output(z, out, norm_dict, self.dropout, self.training)
        return z


class HeteroTransformerConv(BaseImageLabelDecoder):
    def __init__(self, metadata, input_dims: Dict[str, int], hidden_dim=HIDDEN_DIM, num_layers=NUM_LAYERS, heads=NUM_HEADS, dropout=DROPOUT, decoder=DECODER):
        super().__init__()
        node_types, edge_types = metadata
        self.dropout = dropout
        self.proj = nn.ModuleDict({node_type: nn.Linear(int(input_dims[node_type]), hidden_dim) for node_type in node_types if node_type in input_dims})
        self.convs = nn.ModuleList()
        self.norms = nn.ModuleList()
        for _ in range(num_layers):
            conv = HeteroConv({
                edge_type: TransformerConv((hidden_dim, hidden_dim), hidden_dim, heads=heads, concat=False, dropout=dropout)
                for edge_type in edge_types
            }, aggr="sum")
            self.convs.append(conv)
            self.norms.append(nn.ModuleDict({node_type: nn.LayerNorm(hidden_dim) for node_type in self.proj}))
        self._init_decoder(hidden_dim, dropout, decoder)

    def forward(self, x_dict, edge_index_dict):
        z = {node_type: F.relu(self.proj[node_type](x.float())) for node_type, x in x_dict.items() if node_type in self.proj}
        for conv, norm_dict in zip(self.convs, self.norms):
            out = conv(z, edge_index_dict)
            z = merge_layer_output(z, out, norm_dict, self.dropout, self.training)
        return z


def build_model(model_name: str, metadata, input_dims: Dict[str, int], cfg: Optional[Dict] = None):
    model_name = model_name.lower()
    cfg = cfg or get_model_config(model_name)
    kwargs = {
        "hidden_dim": int(cfg["hidden_dim"]),
        "num_layers": int(cfg["num_layers"]),
        "heads": int(cfg["num_heads"]),
        "dropout": float(cfg["dropout"]),
        "decoder": DECODER,
    }
    if model_name == "hgtconv":
        return HeteroHGT(metadata, input_dims, **kwargs)
    if model_name == "hanconv":
        return HeteroHAN(metadata, input_dims, **kwargs)
    if model_name == "transformerconv":
        return HeteroTransformerConv(metadata, input_dims, **kwargs)
    raise ValueError(f"Unknown model_name={model_name}. Expected one of: hgtconv, hanconv, transformerconv")


def keep_first_edges_per_src(edge_index: torch.Tensor, max_edges_per_src: Optional[int]) -> torch.Tensor:
    if max_edges_per_src is None or max_edges_per_src <= 0 or edge_index.numel() == 0:
        return torch.arange(edge_index.size(1), dtype=torch.long)
    src_nodes = edge_index[0].cpu().tolist()
    counts = {}
    keep = []
    for col, src in enumerate(src_nodes):
        used = counts.get(src, 0)
        if used < max_edges_per_src:
            keep.append(col)
            counts[src] = used + 1
    return torch.tensor(keep, dtype=torch.long)


def cap_similar_edges_in_data(data: HeteroData, max_edges_per_src: Optional[int]) -> HeteroData:
    if max_edges_per_src is None:
        return data
    for edge_type in [("image", "similar_to", "image"), ("image", "rev_similar_to", "image")]:
        if edge_type not in data.edge_types or not hasattr(data[edge_type], "edge_index"):
            continue
        edge_index = data[edge_type].edge_index.cpu()
        keep = keep_first_edges_per_src(edge_index, max_edges_per_src)
        old_edges = edge_index.size(1)
        data[edge_type].edge_index = edge_index[:, keep]
        if hasattr(data[edge_type], "edge_weight"):
            data[edge_type].edge_weight = data[edge_type].edge_weight.cpu()[keep]
        print(f"Capped {edge_type}: {old_edges} -> {data[edge_type].edge_index.size(1)} edges")
    return data


def message_passing_edge_index_dict(data: HeteroData, include_has_finding: bool = INCLUDE_HAS_FINDING_IN_MESSAGE_PASSING):
    edge_dict = {}
    for edge_type in data.edge_types:
        relation = edge_type[1]
        if not include_has_finding and (relation == "has_finding" or relation == "rev_has_finding"):
            continue
        if hasattr(data[edge_type], "edge_index"):
            edge_dict[edge_type] = data[edge_type].edge_index
    return edge_dict


def input_dims_from_data(data: HeteroData) -> Dict[str, int]:
    return {node_type: int(data[node_type].x.size(-1)) for node_type in data.node_types if hasattr(data[node_type], "x")}


def pos_weight_from_targets(y: torch.Tensor) -> torch.Tensor:
    pos = y.sum(dim=0)
    neg = y.size(0) - pos
    return torch.clamp(neg / torch.clamp(pos, min=1.0), min=1.0, max=50.0)

## Query Graph Construction

For each test image, we add a query image node and connect it to the `top_k` nearest training image nodes through `similar_to` edges. The query node has no `has_finding` edges. To keep the transformer models memory-safe at `top_k=500`, test inference is performed in chunks.

In [6]:
def l2_normalize_np(x: np.ndarray, eps: float = 1e-12) -> np.ndarray:
    return (x / np.maximum(np.linalg.norm(x, axis=1, keepdims=True), eps)).astype("float32")


def topk_inner_product(train_embeddings: np.ndarray, query_embeddings: np.ndarray, top_k: int, batch_size: int = TEST_QUERY_BATCH_SIZE):
    train = l2_normalize_np(train_embeddings.astype("float32"))
    query = l2_normalize_np(query_embeddings.astype("float32"))
    all_sims, all_idx = [], []
    try:
        import faiss
        index = faiss.IndexFlatIP(train.shape[1])
        index.add(np.ascontiguousarray(train))
        for start in tqdm(range(0, len(query), batch_size), desc=f"query FAISS top_k={top_k}"):
            sims, idx = index.search(np.ascontiguousarray(query[start:start + batch_size]), min(top_k, len(train)))
            all_sims.append(sims.astype("float32"))
            all_idx.append(idx.astype("int64"))
    except ImportError:
        for start in tqdm(range(0, len(query), batch_size), desc=f"query dense top_k={top_k}"):
            scores = query[start:start + batch_size] @ train.T
            kth = min(top_k, scores.shape[1]) - 1
            idx = np.argpartition(-scores, kth=kth, axis=1)[:, :top_k]
            sorted_order = np.take_along_axis(scores, idx, axis=1).argsort(axis=1)[:, ::-1]
            idx = np.take_along_axis(idx, sorted_order, axis=1)
            sims = np.take_along_axis(scores, idx, axis=1)
            all_sims.append(sims.astype("float32"))
            all_idx.append(idx.astype("int64"))
    return np.concatenate(all_sims, axis=0), np.concatenate(all_idx, axis=0)


def append_edge_index(data: HeteroData, edge_type, edge_index_new: torch.Tensor, edge_weight_new: Optional[torch.Tensor] = None):
    store = data[edge_type]
    if hasattr(store, "edge_index"):
        store.edge_index = torch.cat([store.edge_index.cpu(), edge_index_new.cpu()], dim=1)
    else:
        store.edge_index = edge_index_new.cpu()
    if edge_weight_new is not None:
        if hasattr(store, "edge_weight"):
            store.edge_weight = torch.cat([store.edge_weight.cpu(), edge_weight_new.cpu()], dim=0)
        else:
            store.edge_weight = edge_weight_new.cpu()


def target_matrix_from_metadata(frame: pd.DataFrame) -> np.ndarray:
    missing = [col for col in TARGET_COLUMNS if col not in frame.columns]
    if missing:
        raise RuntimeError(f"Missing target columns in metadata: {missing}")
    return frame[TARGET_COLUMNS].to_numpy(dtype=np.float32)


def append_query_chunk_to_graph(data: HeteroData, query_embeddings: np.ndarray, query_targets: np.ndarray, neighbor_idx: np.ndarray, neighbor_sims: np.ndarray) -> Tuple[HeteroData, int]:
    query_data = copy.deepcopy(data).cpu()
    train_count = int(query_data["image"].x.size(0))
    query_data["image"].x = torch.cat([query_data["image"].x.float(), torch.from_numpy(query_embeddings).float()], dim=0)
    if hasattr(query_data["image"], "y"):
        query_data["image"].y = torch.cat([query_data["image"].y.float(), torch.from_numpy(query_targets).float()], dim=0)
    else:
        query_data["image"].y = torch.from_numpy(query_targets).float()

    src, dst, weights = [], [], []
    for qi in range(neighbor_idx.shape[0]):
        query_node = train_count + qi
        for rank in range(neighbor_idx.shape[1]):
            src.append(query_node)
            dst.append(int(neighbor_idx[qi, rank]))
            weights.append(float(neighbor_sims[qi, rank]))
    edge_index = torch.tensor([src, dst], dtype=torch.long)
    edge_weight = torch.tensor(weights, dtype=torch.float32)
    append_edge_index(query_data, ("image", "similar_to", "image"), edge_index, edge_weight)
    append_edge_index(query_data, ("image", "rev_similar_to", "image"), edge_index.flip(0), edge_weight)
    return query_data, train_count


def predict_test_queries(model: nn.Module, data_cpu: HeteroData, test_df: pd.DataFrame, test_embeddings: np.ndarray, top_k: int, label_indices: Sequence[int], chunk_size: int = QUERY_INFERENCE_CHUNK_SIZE) -> Tuple[np.ndarray, np.ndarray]:
    train_embeddings = data_cpu["image"].x.cpu().numpy().astype("float32")
    test_targets = target_matrix_from_metadata(test_df)
    sims, idx = topk_inner_product(train_embeddings, test_embeddings, top_k=top_k)
    probs_chunks = []
    model.eval()
    for start in tqdm(range(0, len(test_embeddings), chunk_size), desc=f"test query chunks top_k={top_k}"):
        end = min(start + chunk_size, len(test_embeddings))
        query_data, train_count = append_query_chunk_to_graph(
            data_cpu,
            test_embeddings[start:end],
            test_targets[start:end],
            idx[start:end],
            sims[start:end],
        )
        query_edges = message_passing_edge_index_dict(query_data, include_has_finding=INCLUDE_HAS_FINDING_IN_MESSAGE_PASSING)
        query_data = query_data.to(DEVICE)
        query_edges = {etype: edge_index.to(DEVICE) for etype, edge_index in query_edges.items()}
        with torch.no_grad():
            z = model(query_data.x_dict, query_edges)
            query_logits_all = model.decode_image_label_logits(z, label_indices)
            logits = query_logits_all[train_count:train_count + (end - start)].detach().cpu().numpy().astype("float32")
            probs_chunks.append(sigmoid_np(logits))
        del query_data, query_edges, z, query_logits_all
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    return np.concatenate(probs_chunks, axis=0), test_targets

## Train and Evaluate One Fold

In [7]:
def experiment_root(model_name: str, query_top_k: int) -> Path:
    root = OUTPUT_ROOT / model_name / f"top_k_{query_top_k}"
    root.mkdir(parents=True, exist_ok=True)
    return root


def fold_dirs(model_name: str, query_top_k: int, fold: int) -> Dict[str, Path]:
    root = experiment_root(model_name, query_top_k) / f"fold{fold}"
    dirs = {
        "root": root,
        "models": root / "models",
        "metrics": root / "metrics",
        "predictions": root / "predictions",
        "logs": root / "logs",
    }
    for path in dirs.values():
        path.mkdir(parents=True, exist_ok=True)
    return dirs


def fold_complete(model_name: str, query_top_k: int, fold: int, dirs: Dict[str, Path]) -> bool:
    metrics_file = dirs["metrics"] / f"{model_name}_test_metrics.csv"
    tuned_file = dirs["metrics"] / f"{model_name}_test_metrics_val_tuned_thresholds.csv"
    return (dirs["root"] / "FOLD_COMPLETE.json").exists() and metrics_file.exists() and tuned_file.exists()


def save_predictions(path: Path, test_df: pd.DataFrame, probs: np.ndarray, targets: np.ndarray) -> pd.DataFrame:
    rows = []
    for i, row in test_df.reset_index(drop=True).iterrows():
        out = {
            "study_id": str(row.get("study_id", "")),
            "subject_id": str(row.get("subject_id", "")),
            "image_path": str(row.get("image_path", "")),
        }
        for j, label in enumerate(SCORING_LABELS):
            out[f"prob_{label}"] = float(probs[i, j])
            out[f"target_{label}"] = int(targets[i, j] >= 0.5)
        rows.append(out)
    pred_df = pd.DataFrame(rows)
    pred_df.to_csv(path, index=False)
    return pred_df


def train_one_fold(model_name: str, query_top_k: int, fold: int) -> List[Dict]:
    model_name = model_name.lower()
    method_name = f"hetero_{model_name}"
    dirs = fold_dirs(model_name, query_top_k, fold)
    force_key = (model_name, int(query_top_k), int(fold))
    if SKIP_COMPLETED and force_key not in FORCE_RERUN and fold_complete(model_name, query_top_k, fold, dirs):
        print(f"{model_name} top_k={query_top_k} fold={fold}: already complete, skipping.")
        summary_csv = dirs["metrics"] / f"{model_name}_method_summary.csv"
        if summary_csv.exists():
            return pd.read_csv(summary_csv).to_dict(orient="records")
        summary_path = dirs["metrics"] / f"{model_name}_summary.json"
        return list(json.loads(summary_path.read_text()).values()) if summary_path.exists() else [{"fold": fold, "skipped": True}]

    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    cfg = get_model_config(model_name)
    print(f"Config for {model_name}:", cfg)

    data, train_df, test_df, test_embeddings = load_fold_data(fold)
    data = cap_similar_edges_in_data(data, cfg.get("max_train_similar_edges_per_node"))
    label_indices = label_indices_for_scoring(data)
    if not hasattr(data["image"], "y"):
        raise RuntimeError("data['image'].y is missing. Regenerate fold KG with train labels.")

    num_images = int(data["image"].x.size(0))
    train_idx, val_idx = split_train_val_indices(num_images, VAL_FRAC, seed=SEED + fold)
    y = data["image"].y.float()
    train_y = y[train_idx]
    val_y = y[val_idx]
    pos_weight = pos_weight_from_targets(train_y).to(DEVICE)

    mp_edges = message_passing_edge_index_dict(data, include_has_finding=INCLUDE_HAS_FINDING_IN_MESSAGE_PASSING)
    metadata = (data.node_types, list(mp_edges.keys()))
    input_dims = input_dims_from_data(data)

    data = data.to(DEVICE)
    mp_edges = {etype: edge_index.to(DEVICE) for etype, edge_index in mp_edges.items()}

    model = build_model(model_name, metadata=metadata, input_dims=input_dims, cfg=cfg).to(DEVICE)
    optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
    criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)

    best_score = -float("inf")
    best_state = None
    best_epoch = -1
    stale_epochs = 0
    logs = []

    train_idx_dev = train_idx.to(DEVICE)
    val_idx_dev = val_idx.to(DEVICE)

    for epoch in range(EPOCHS):
        model.train()
        optimizer.zero_grad(set_to_none=True)
        z = model(data.x_dict, mp_edges)
        logits = model.decode_image_label_logits(z, label_indices)
        loss = criterion(logits[train_idx_dev], data["image"].y[train_idx_dev].float())
        loss.backward()
        if GRAD_CLIP_NORM is not None:
            torch.nn.utils.clip_grad_norm_(model.parameters(), GRAD_CLIP_NORM)
        optimizer.step()

        model.eval()
        with torch.no_grad():
            z = model(data.x_dict, mp_edges)
            logits = model.decode_image_label_logits(z, label_indices)
            val_logits = logits[val_idx_dev].detach().cpu().numpy().astype("float32")
            val_probs = sigmoid_np(val_logits)
            val_metrics = evaluate_prob_matrix(val_probs, val_y.numpy())
            val_macro_auroc = macro_metric(val_metrics, "auroc", disease_only=True)
            train_logits = logits[train_idx_dev].detach().cpu().numpy().astype("float32")
            train_probs = sigmoid_np(train_logits)
            train_metrics = evaluate_prob_matrix(train_probs, train_y.numpy())
            train_macro_auroc = macro_metric(train_metrics, "auroc", disease_only=True)

        log_row = {
            "fold": int(fold),
            "model_name": model_name,
            "query_top_k": int(query_top_k),
            "epoch": int(epoch),
            "loss": float(loss.detach().cpu()),
            "train_disease_macro_auroc": float(train_macro_auroc),
            "val_disease_macro_auroc": float(val_macro_auroc),
        }
        logs.append(log_row)
        print(f"model={model_name} top_k={query_top_k} fold={fold} epoch={epoch} loss={log_row['loss']:.4f} val_auc={val_macro_auroc:.4f}")

        if np.isfinite(val_macro_auroc) and val_macro_auroc > best_score:
            best_score = float(val_macro_auroc)
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            best_epoch = int(epoch)
            stale_epochs = 0
        else:
            stale_epochs += 1
        if stale_epochs >= PATIENCE:
            print(f"{model_name} top_k={query_top_k} fold={fold}: early stopping at epoch {epoch}")
            break

    if best_state is not None:
        model.load_state_dict(best_state)
    pd.DataFrame(logs).to_csv(dirs["logs"] / f"{model_name}_training_log.csv", index=False)

    # Tune thresholds on validation nodes.
    model.eval()
    with torch.no_grad():
        z = model(data.x_dict, mp_edges)
        all_logits = model.decode_image_label_logits(z, label_indices)
        val_probs = sigmoid_np(all_logits[val_idx_dev].detach().cpu().numpy().astype("float32"))
    thresholds = tune_f1_thresholds(val_probs, val_y.numpy())
    pd.DataFrame({"label": SCORING_LABELS, "threshold": thresholds}).to_csv(dirs["metrics"] / f"{model_name}_val_f1_thresholds.csv", index=False)

    # Test-time query graph. Reload CPU graph to avoid carrying CUDA graph state.
    data_cpu, _, test_df, test_embeddings = load_fold_data(fold)
    data_cpu = cap_similar_edges_in_data(data_cpu, cfg.get("max_train_similar_edges_per_node"))
    test_probs, test_targets = predict_test_queries(
        model,
        data_cpu,
        test_df,
        test_embeddings,
        top_k=query_top_k,
        label_indices=label_indices,
        chunk_size=int(cfg.get("query_inference_chunk_size", QUERY_INFERENCE_CHUNK_SIZE)),
    )

    metrics_fixed = evaluate_prob_matrix(test_probs, test_targets)
    metrics_tuned = evaluate_prob_matrix(test_probs, test_targets, thresholds=thresholds)
    fixed_metrics_path = dirs["metrics"] / f"{model_name}_test_metrics.csv"
    tuned_metrics_path = dirs["metrics"] / f"{model_name}_test_metrics_val_tuned_thresholds.csv"
    metrics_fixed.to_csv(fixed_metrics_path, index=False)
    metrics_tuned.to_csv(tuned_metrics_path, index=False)
    save_predictions(dirs["predictions"] / f"{model_name}_test_predictions.csv", test_df, test_probs, test_targets)

    model_path = dirs["models"] / f"hetero_{model_name}_fold{fold}_topk{query_top_k}.pt"
    torch.save({
        "state_dict": model.state_dict(),
        "fold": int(fold),
        "model_name": model_name,
        "labels": list(SCORING_LABELS),
        "label_indices": list(label_indices),
        "input_dims": input_dims,
        "hidden_dim": int(cfg["hidden_dim"]),
        "num_layers": int(cfg["num_layers"]),
        "num_heads": int(cfg["num_heads"]),
        "max_train_similar_edges_per_node": cfg.get("max_train_similar_edges_per_node"),
        "dropout": DROPOUT,
        "decoder": DECODER,
        "include_has_finding_in_message_passing": INCLUDE_HAS_FINDING_IN_MESSAGE_PASSING,
        "query_top_k": int(query_top_k),
        "best_epoch": int(best_epoch),
        "best_val_disease_macro_auroc": float(best_score),
    }, model_path)

    common_extra = {
        "model_name": model_name,
        "query_top_k": int(query_top_k),
        "include_has_finding_in_message_passing": bool(INCLUDE_HAS_FINDING_IN_MESSAGE_PASSING),
        "model_path": str(model_path),
        "best_epoch": int(best_epoch),
        "best_val_disease_macro_auroc": float(best_score),
        "hidden_dim": int(cfg["hidden_dim"]),
        "num_layers": int(cfg["num_layers"]),
        "num_heads": int(cfg["num_heads"]),
        "max_train_similar_edges_per_node": cfg.get("max_train_similar_edges_per_node"),
    }
    summary = metric_summary(metrics_fixed, fold, method_name, extra={
        **common_extra,
        "threshold_mode": "fixed_0.5",
        "metrics_path": str(fixed_metrics_path),
    })
    summary_tuned = metric_summary(metrics_tuned, fold, method_name, extra={
        **common_extra,
        "threshold_mode": "val_tuned_f1",
        "metrics_path": str(tuned_metrics_path),
    })
    pd.DataFrame([summary, summary_tuned]).to_csv(dirs["metrics"] / f"{model_name}_method_summary.csv", index=False)
    save_json({"fixed_0.5": summary, "val_tuned_f1": summary_tuned}, dirs["metrics"] / f"{model_name}_summary.json")
    save_json({
        "fold": int(fold),
        "status": "complete",
        "model_name": model_name,
        "query_top_k": int(query_top_k),
        "model_path": str(model_path),
    }, dirs["root"] / "FOLD_COMPLETE.json")
    return [summary, summary_tuned]

## Run 10-Fold Ablations

This cell runs `3 models × 4 top_k values × 10 folds`. It can take a long time. Because `SKIP_COMPLETED=True`, it is safe to interrupt and resume.

In [8]:
all_summaries = []

for model_name in MODEL_NAMES:
    for query_top_k in QUERY_TOP_K_VALUES:
        print(f"\n######## Model={model_name} top_k={query_top_k} ########")
        run_rows = []
        run_root = experiment_root(model_name, query_top_k)
        for fold in FOLD_INDICES:
            print(f"\n===== Model={model_name} top_k={query_top_k} fold={fold} =====")
            rows = train_one_fold(model_name, query_top_k, fold)
            run_rows.extend(rows)
            all_summaries.extend(rows)
            pd.DataFrame(run_rows).to_csv(run_root / f"{model_name}_topk{query_top_k}_10fold_summary_progress.csv", index=False)
            pd.DataFrame(all_summaries).to_csv(OUTPUT_ROOT / "transformer_gnn_10fold_all_results_progress.csv", index=False)
        pd.DataFrame(run_rows).to_csv(run_root / f"{model_name}_topk{query_top_k}_10fold_summary.csv", index=False)

all_results_df = pd.DataFrame(all_summaries)
all_results_df.to_csv(OUTPUT_ROOT / "transformer_gnn_10fold_all_results.csv", index=False)
display(all_results_df)

######## Model=hgtconv top_k=50 ########

===== Model=hgtconv top_k=50 fold=0 =====
hgtconv top_k=50 fold=0: already complete, skipping.

===== Model=hgtconv top_k=50 fold=1 =====
hgtconv top_k=50 fold=1: already complete, skipping.

===== Model=hgtconv top_k=50 fold=2 =====
hgtconv top_k=50 fold=2: already complete, skipping.

===== Model=hgtconv top_k=50 fold=3 =====
hgtconv top_k=50 fold=3: already complete, skipping.

===== Model=hgtconv top_k=50 fold=4 =====
hgtconv top_k=50 fold=4: already complete, skipping.

===== Model=hgtconv top_k=50 fold=5 =====
hgtconv top_k=50 fold=5: already complete, skipping.

===== Model=hgtconv top_k=50 fold=6 =====
hgtconv top_k=50 fold=6: already complete, skipping.

===== Model=hgtconv top_k=50 fold=7 =====
hgtconv top_k=50 fold=7: already complete, skipping.

===== Model=hgtconv top_k=50 fold=8 =====
hgtconv top_k=50 fold=8: already complete, skipping.

===== Model=hgtconv top_k=50 fold=9 =====
hgtconv top_k=50 fold=9: already complete, skipping.

######## Model=hgtconv top_k=100 ########

===== Model=hgtconv top_k=100 fold=0 =====
hgtconv top_k=100 fold=0: already complete, skipping.

===== Model=hgtconv top_k=100 fold=1 =====
hgtconv top_k=100 fold=1: already complete, skipping.

===== Model=hgtconv top_k=100 fold=2 =====
hgtconv top_k=100 fold=2: already complete, skipping.

===== Model=hgtconv top_k=100 fold=3 =====
hgtconv top_k=100 fold=3: already complete, skipping.

===== Model=hgtconv top_k=100 fold=4 =====
hgtconv top_k=100 fold=4: already complete, skipping.

===== Model=hgtconv top_k=100 fold=5 =====
hgtconv top_k=100 fold=5: already complete, skipping.

===== Model=hgtconv top_k=100 fold=6 =====
hgtconv top_k=100 fold=6: already complete, skipping.

===== Model=hgtconv top_k=100 fold=7 =====
hgtconv top_k=100 fold=7: already complete, skipping.

===== Model=hgtconv top_k=100 fold=8 =====
hgtconv top_k=100 fold=8: already complete, skipping.

===== Model=hgtconv top_k=100 fold=9 =====
hgtconv top_k=100 fold=9: already complete, skipping.

######## Model=hgtconv top_k=200 ########

===== Model=hgtconv top_k=200 fold=0 =====
hgtconv top_k=200 fold=0: already complete, skipping.

===== Model=hgtconv top_k=200 fold=1 =====
hgtconv top_k=200 fold=1: already complete, skipping.

===== Model=hgtconv top_k=200 fold=2 =====
hgtconv top_k=200 fold=2: already complete, skipping.

===== Model=hgtconv top_k=200 fold=3 =====
hgtconv top_k=200 fold=3: already complete, skipping.

===== Model=hgtconv top_k=200 fold=4 =====
hgtconv top_k=200 fold=4: already complete, skipping.

===== Model=hgtconv top_k=200 fold=5 =====
hgtconv top_k=200 fold=5: already complete, skipping.

===== Model=hgtconv top_k=200 fold=6 =====
hgtconv top_k=200 fold=6: already complete, skipping.

===== Model=hgtconv top_k=200 fold=7 =====
hgtconv top_k=200 fold=7: already complete, skipping.

===== Model=hgtconv top_k=200 fold=8 =====
hgtconv top_k=200 fold=8: already complete, skipping.

===== Model=hgtconv top_k=200 fold=9 =====
hgtconv top_k=200 fold=9: already complete, skipping.

######## Model=hgtconv top_k=500 ########

===== Model=hgtconv top_k=500 fold=0 =====
hgtconv top_k=500 fold=0: already complete, skipping.

===== Model=hgtconv top_k=500 fold=1 =====
hgtconv top_k=500 fold=1: already complete, skipping.

===== Model=hgtconv top_k=500 fold=2 =====
hgtconv top_k=500 fold=2: already complete, skipping.

===== Model=hgtconv top_k=500 fold=3 =====
hgtconv top_k=500 fold=3: already complete, skipping.

===== Model=hgtconv top_k=500 fold=4 =====
hgtconv top_k=500 fold=4: already complete, skipping.

===== Model=hgtconv top_k=500 fold=5 =====
hgtconv top_k=500 fold=5: already complete, skipping.

===== Model=hgtconv top_k=500 fold=6 =====
hgtconv top_k=500 fold=6: already complete, skipping.

===== Model=hgtconv top_k=500 fold=7 =====
hgtconv top_k=500 fold=7: already complete, skipping.

===== Model=hgtconv top_k=500 fold=8 =====
hgtconv top_k=500 fold=8: already complete, skipping.

===== Model=hgtconv top_k=500 fold=9 =====
hgtconv top_k=500 fold=9: already complete, skipping.

######## Model=hanconv top_k=50 ########

===== Model=hanconv top_k=50 fold=0 =====
hanconv top_k=50 fold=0: already complete, skipping.

===== Model=hanconv top_k=50 fold=1 =====
hanconv top_k=50 fold=1: already complete, skipping.

===== Model=hanconv top_k=50 fold=2 =====
hanconv top_k=50 fold=2: already complete, skipping.

===== Model=hanconv top_k=50 fold=3 =====
hanconv top_k=50 fold=3: already complete, skipping.

===== Model=hanconv top_k=50 fold=4 =====
hanconv top_k=50 fold=4: already complete, skipping.

===== Model=hanconv top_k=50 fold=5 =====
hanconv top_k=50 fold=5: already complete, skipping.

===== Model=hanconv top_k=50 fold=6 =====
hanconv top_k=50 fold=6: already complete, skipping.

===== Model=hanconv top_k=50 fold=7 =====
hanconv top_k=50 fold=7: already complete, skipping.

===== Model=hanconv top_k=50 fold=8 =====
hanconv top_k=50 fold=8: already complete, skipping.

===== Model=hanconv top_k=50 fold=9 =====
hanconv top_k=50 fold=9: already complete, skipping.

######## Model=hanconv top_k=100 ########

===== Model=hanconv top_k=100 fold=0 =====
hanconv top_k=100 fold=0: already complete, skipping.

===== Model=hanconv top_k=100 fold=1 =====
hanconv top_k=100 fold=1: already complete, skipping.

===== Model=hanconv top_k=100 fold=2 =====
hanconv top_k=100 fold=2: already complete, skipping.

===== Model=hanconv top_k=100 fold=3 =====
hanconv top_k=100 fold=3: already complete, skipping.

===== Model=hanconv top_k=100 fold=4 =====
hanconv top_k=100 fold=4: already complete, skipping.

===== Model=hanconv top_k=100 fold=5 =====
hanconv top_k=100 fold=5: already complete, skipping.

===== Model=hanconv top_k=100 fold=6 =====
hanconv top_k=100 fold=6: already complete, skipping.

===== Model=hanconv top_k=100 fold=7 =====
hanconv top_k=100 fold=7: already complete, skipping.

===== Model=hanconv top_k=100 fold=8 =====
hanconv top_k=100 fold=8: already complete, skipping.

===== Model=hanconv top_k=100 fold=9 =====
hanconv top_k=100 fold=9: already complete, skipping.

######## Model=hanconv top_k=200 ########

===== Model=hanconv top_k=200 fold=0 =====
hanconv top_k=200 fold=0: already complete, skipping.

===== Model=hanconv top_k=200 fold=1 =====
hanconv top_k=200 fold=1: already complete, skipping.

===== Model=hanconv top_k=200 fold=2 =====
hanconv top_k=200 fold=2: already complete, skipping.

===== Model=hanconv top_k=200 fold=3 =====
hanconv top_k=200 fold=3: already complete, skipping.

===== Model=hanconv top_k=200 fold=4 =====
hanconv top_k=200 fold=4: already complete, skipping.

===== Model=hanconv top_k=200 fold=5 =====
hanconv top_k=200 fold=5: already complete, skipping.

===== Model=hanconv top_k=200 fold=6 =====
hanconv top_k=200 fold=6: already complete, skipping.

===== Model=hanconv top_k=200 fold=7 =====
hanconv top_k=200 fold=7: already complete, skipping.

===== Model=hanconv top_k=200 fold=8 =====
hanconv top_k=200 fold=8: already complete, skipping.

===== Model=hanconv top_k=200 fold=9 =====
hanconv top_k=200 fold=9: already complete, skipping.

######## Model=hanconv top_k=500 ########

===== Model=hanconv top_k=500 fold=0 =====
hanconv top_k=500 fold=0: already complete, skipping.

===== Model=hanconv top_k=500 fold=1 =====
hanconv top_k=500 fold=1: already complete, skipping.

===== Model=hanconv top_k=500 fold=2 =====
hanconv top_k=500 fold=2: already complete, skipping.

===== Model=hanconv top_k=500 fold=3 =====
hanconv top_k=500 fold=3: already complete, skipping.

===== Model=hanconv top_k=500 fold=4 =====
hanconv top_k=500 fold=4: already complete, skipping.

===== Model=hanconv top_k=500 fold=5 =====
hanconv top_k=500 fold=5: already complete, skipping.

===== Model=hanconv top_k=500 fold=6 =====
hanconv top_k=500 fold=6: already complete, skipping.

===== Model=hanconv top_k=500 fold=7 =====
hanconv top_k=500 fold=7: already complete, skipping.

===== Model=hanconv top_k=500 fold=8 =====
hanconv top_k=500 fold=8: already complete, skipping.

===== Model=hanconv top_k=500 fold=9 =====
hanconv top_k=500 fold=9: already complete, skipping.

######## Model=transformerconv top_k=50 ########

===== Model=transformerconv top_k=50 fold=0 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718731 edges
model=transformerconv top_k=50 fold=0 epoch=0 loss=8.4999 val_auc=0.5000
model=transformerconv top_k=50 fold=0 epoch=1 loss=34.0270 val_auc=0.5001
model=transformerconv top_k=50 fold=0 epoch=2 loss=28.2103 val_auc=0.6922
model=transformerconv top_k=50 fold=0 epoch=3 loss=15.5844 val_auc=0.7580
model=transformerconv top_k=50 fold=0 epoch=4 loss=6.1603 val_auc=0.7661
model=transformerconv top_k=50 fold=0 epoch=5 loss=6.9682 val_auc=0.7696
model=transformerconv top_k=50 fold=0 epoch=6 loss=5.8114 val_auc=0.7706
model=transformerconv top_k=50 fold=0 epoch=7 loss=5.5000 val_auc=0.7725
model=transformerconv top_k=50 fold=0 epoch=8 loss=4.5766 val_auc=0.7753
model=transformerconv top_k=50 fold=0 epoch=9 loss=4.0269 val_auc=0.7770
model=transformerconv top_k=50 fold=0 epoch=10 loss=3.9700 val_auc=0.7798
model=transformerconv top_k=50 fold=0 epoch=11 loss=5.5949 val_auc=0.7822
model=transformerconv top_k=50 fold=0 epoch=12 loss=4.2257 val_auc=0.7838
model=transformerconv top_k=50 fold=0 epoch=13 loss=3.4577 val_auc=0.7866
model=transformerconv top_k=50 fold=0 epoch=14 loss=3.4970 val_auc=0.7888
model=transformerconv top_k=50 fold=0 epoch=15 loss=3.8832 val_auc=0.7904
model=transformerconv top_k=50 fold=0 epoch=16 loss=2.9789 val_auc=0.7913
model=transformerconv top_k=50 fold=0 epoch=17 loss=3.3649 val_auc=0.7918
model=transformerconv top_k=50 fold=0 epoch=18 loss=3.8945 val_auc=0.7923
model=transformerconv top_k=50 fold=0 epoch=19 loss=2.4385 val_auc=0.7929
model=transformerconv top_k=50 fold=0 epoch=20 loss=2.3666 val_auc=0.7939
model=transformerconv top_k=50 fold=0 epoch=21 loss=3.0718 val_auc=0.7947
model=transformerconv top_k=50 fold=0 epoch=22 loss=2.6724 val_auc=0.7954
model=transformerconv top_k=50 fold=0 epoch=23 loss=2.6529 val_auc=0.7958
model=transformerconv top_k=50 fold=0 epoch=24 loss=2.6722 val_auc=0.7964
model=transformerconv top_k=50 fold=0 epoch=25 loss=3.4679 val_auc=0.7968
model=transformerconv top_k=50 fold=0 epoch=26 loss=2.7169 val_auc=0.7971
model=transformerconv top_k=50 fold=0 epoch=27 loss=2.1912 val_auc=0.7974
model=transformerconv top_k=50 fold=0 epoch=28 loss=2.2008 val_auc=0.7978
model=transformerconv top_k=50 fold=0 epoch=29 loss=2.6065 val_auc=0.7981
model=transformerconv top_k=50 fold=0 epoch=30 loss=2.5464 val_auc=0.7985
model=transformerconv top_k=50 fold=0 epoch=31 loss=2.5523 val_auc=0.7985
model=transformerconv top_k=50 fold=0 epoch=32 loss=2.2274 val_auc=0.7983
model=transformerconv top_k=50 fold=0 epoch=33 loss=2.3565 val_auc=0.7980
model=transformerconv top_k=50 fold=0 epoch=34 loss=2.3915 val_auc=0.7979
model=transformerconv top_k=50 fold=0 epoch=35 loss=2.1135 val_auc=0.7982
model=transformerconv top_k=50 fold=0 epoch=36 loss=1.8653 val_auc=0.7991
model=transformerconv top_k=50 fold=0 epoch=37 loss=1.8582 val_auc=0.7998
model=transformerconv top_k=50 fold=0 epoch=38 loss=1.9048 val_auc=0.8009
model=transformerconv top_k=50 fold=0 epoch=39 loss=1.7155 val_auc=0.8023
model=transformerconv top_k=50 fold=0 epoch=40 loss=1.7658 val_auc=0.8034
model=transformerconv top_k=50 fold=0 epoch=41 loss=1.5529 val_auc=0.8044
model=transformerconv top_k=50 fold=0 epoch=42 loss=1.5987 val_auc=0.8048
model=transformerconv top_k=50 fold=0 epoch=43 loss=1.8116 val_auc=0.8054
model=transformerconv top_k=50 fold=0 epoch=44 loss=1.6384 val_auc=0.8063
model=transformerconv top_k=50 fold=0 epoch=45 loss=1.5052 val_auc=0.8074
model=transformerconv top_k=50 fold=0 epoch=46 loss=1.4184 val_auc=0.8083
model=transformerconv top_k=50 fold=0 epoch=47 loss=1.4248 val_auc=0.8090
model=transformerconv top_k=50 fold=0 epoch=48 loss=1.6831 val_auc=0.8092
model=transformerconv top_k=50 fold=0 epoch=49 loss=1.5106 val_auc=0.8093
model=transformerconv top_k=50 fold=0 epoch=50 loss=1.9333 val_auc=0.8090
model=transformerconv top_k=50 fold=0 epoch=51 loss=1.6245 val_auc=0.8082
model=transformerconv top_k=50 fold=0 epoch=52 loss=1.6401 val_auc=0.8078
model=transformerconv top_k=50 fold=0 epoch=53 loss=1.7492 val_auc=0.8071
model=transformerconv top_k=50 fold=0 epoch=54 loss=1.4359 val_auc=0.8070
model=transformerconv top_k=50 fold=0 epoch=55 loss=1.4900 val_auc=0.8082
model=transformerconv top_k=50 fold=0 epoch=56 loss=1.3614 val_auc=0.8089
model=transformerconv top_k=50 fold=0 epoch=57 loss=1.3261 val_auc=0.8096
model=transformerconv top_k=50 fold=0 epoch=58 loss=1.3561 val_auc=0.8105
model=transformerconv top_k=50 fold=0 epoch=59 loss=1.2581 val_auc=0.8114
model=transformerconv top_k=50 fold=0 epoch=60 loss=1.3506 val_auc=0.8117
model=transformerconv top_k=50 fold=0 epoch=61 loss=1.3424 val_auc=0.8118
model=transformerconv top_k=50 fold=0 epoch=62 loss=1.3130 val_auc=0.8120
model=transformerconv top_k=50 fold=0 epoch=63 loss=1.4134 val_auc=0.8119
model=transformerconv top_k=50 fold=0 epoch=64 loss=1.2243 val_auc=0.8124
model=transformerconv top_k=50 fold=0 epoch=65 loss=1.2670 val_auc=0.8129
model=transformerconv top_k=50 fold=0 epoch=66 loss=1.2436 val_auc=0.8136
model=transformerconv top_k=50 fold=0 epoch=67 loss=1.2726 val_auc=0.8139
model=transformerconv top_k=50 fold=0 epoch=68 loss=1.2900 val_auc=0.8144
model=transformerconv top_k=50 fold=0 epoch=69 loss=1.2985 val_auc=0.8149
model=transformerconv top_k=50 fold=0 epoch=70 loss=1.1747 val_auc=0.8153
model=transformerconv top_k=50 fold=0 epoch=71 loss=1.2487 val_auc=0.8155
model=transformerconv top_k=50 fold=0 epoch=72 loss=1.5063 val_auc=0.8153
model=transformerconv top_k=50 fold=0 epoch=73 loss=1.4216 val_auc=0.8147
model=transformerconv top_k=50 fold=0 epoch=74 loss=1.2193 val_auc=0.8146
model=transformerconv top_k=50 fold=0 epoch=75 loss=1.2695 val_auc=0.8148
model=transformerconv top_k=50 fold=0 epoch=76 loss=1.2576 val_auc=0.8155
model=transformerconv top_k=50 fold=0 epoch=77 loss=1.1379 val_auc=0.8159
model=transformerconv top_k=50 fold=0 epoch=78 loss=1.1637 val_auc=0.8154
model=transformerconv top_k=50 fold=0 epoch=79 loss=1.1325 val_auc=0.8156
model=transformerconv top_k=50 fold=0 epoch=80 loss=1.1452 val_auc=0.8167
model=transformerconv top_k=50 fold=0 epoch=81 loss=1.0822 val_auc=0.8173
model=transformerconv top_k=50 fold=0 epoch=82 loss=1.1020 val_auc=0.8176
model=transformerconv top_k=50 fold=0 epoch=83 loss=1.2082 val_auc=0.8175
model=transformerconv top_k=50 fold=0 epoch=84 loss=1.0829 val_auc=0.8177
model=transformerconv top_k=50 fold=0 epoch=85 loss=1.1758 val_auc=0.8181
model=transformerconv top_k=50 fold=0 epoch=86 loss=1.1271 val_auc=0.8182
model=transformerconv top_k=50 fold=0 epoch=87 loss=1.0581 val_auc=0.8179
model=transformerconv top_k=50 fold=0 epoch=88 loss=1.2695 val_auc=0.8183
model=transformerconv top_k=50 fold=0 epoch=89 loss=1.1107 val_auc=0.8192
model=transformerconv top_k=50 fold=0 epoch=90 loss=1.1140 val_auc=0.8194
model=transformerconv top_k=50 fold=0 epoch=91 loss=1.0576 val_auc=0.8201
model=transformerconv top_k=50 fold=0 epoch=92 loss=1.0801 val_auc=0.8204
model=transformerconv top_k=50 fold=0 epoch=93 loss=1.0620 val_auc=0.8202
model=transformerconv top_k=50 fold=0 epoch=94 loss=1.1317 val_auc=0.8207
model=transformerconv top_k=50 fold=0 epoch=95 loss=1.0466 val_auc=0.8219
model=transformerconv top_k=50 fold=0 epoch=96 loss=1.0989 val_auc=0.8225
model=transformerconv top_k=50 fold=0 epoch=97 loss=1.1096 val_auc=0.8217
model=transformerconv top_k=50 fold=0 epoch=98 loss=1.1512 val_auc=0.8216
model=transformerconv top_k=50 fold=0 epoch=99 loss=1.0761 val_auc=0.8224
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718731 edges

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=50 fold=1 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719209 edges
model=transformerconv top_k=50 fold=1 epoch=0 loss=5.7026 val_auc=0.5000
model=transformerconv top_k=50 fold=1 epoch=1 loss=38.4121 val_auc=0.5002
model=transformerconv top_k=50 fold=1 epoch=2 loss=30.6416 val_auc=0.7527
model=transformerconv top_k=50 fold=1 epoch=3 loss=10.9973 val_auc=0.7664
model=transformerconv top_k=50 fold=1 epoch=4 loss=6.0571 val_auc=0.7673
model=transformerconv top_k=50 fold=1 epoch=5 loss=7.5592 val_auc=0.7688
model=transformerconv top_k=50 fold=1 epoch=6 loss=6.5128 val_auc=0.7705
model=transformerconv top_k=50 fold=1 epoch=7 loss=4.2421 val_auc=0.7711
model=transformerconv top_k=50 fold=1 epoch=8 loss=5.7969 val_auc=0.7720
model=transformerconv top_k=50 fold=1 epoch=9 loss=10.8380 val_auc=0.7756
model=transformerconv top_k=50 fold=1 epoch=10 loss=7.9100 val_auc=0.7793
model=transformerconv top_k=50 fold=1 epoch=11 loss=5.2517 val_auc=0.7823
model=transformerconv top_k=50 fold=1 epoch=12 loss=3.7942 val_auc=0.7846
model=transformerconv top_k=50 fold=1 epoch=13 loss=4.8272 val_auc=0.7860
model=transformerconv top_k=50 fold=1 epoch=14 loss=6.5241 val_auc=0.7871
model=transformerconv top_k=50 fold=1 epoch=15 loss=6.5143 val_auc=0.7882
model=transformerconv top_k=50 fold=1 epoch=16 loss=5.6964 val_auc=0.7885
model=transformerconv top_k=50 fold=1 epoch=17 loss=4.3163 val_auc=0.7882
model=transformerconv top_k=50 fold=1 epoch=18 loss=3.4878 val_auc=0.7886
model=transformerconv top_k=50 fold=1 epoch=19 loss=4.2491 val_auc=0.7896
model=transformerconv top_k=50 fold=1 epoch=20 loss=4.4797 val_auc=0.7907
model=transformerconv top_k=50 fold=1 epoch=21 loss=4.5578 val_auc=0.7918
model=transformerconv top_k=50 fold=1 epoch=22 loss=3.8248 val_auc=0.7934
model=transformerconv top_k=50 fold=1 epoch=23 loss=4.2653 val_auc=0.7945
model=transformerconv top_k=50 fold=1 epoch=24 loss=4.1595 val_auc=0.7956
model=transformerconv top_k=50 fold=1 epoch=25 loss=4.2224 val_auc=0.7964
model=transformerconv top_k=50 fold=1 epoch=26 loss=3.3836 val_auc=0.7969
model=transformerconv top_k=50 fold=1 epoch=27 loss=2.8743 val_auc=0.7977
model=transformerconv top_k=50 fold=1 epoch=28 loss=3.9666 val_auc=0.7986
model=transformerconv top_k=50 fold=1 epoch=29 loss=4.2378 val_auc=0.7997
model=transformerconv top_k=50 fold=1 epoch=30 loss=4.8615 val_auc=0.8008
model=transformerconv top_k=50 fold=1 epoch=31 loss=3.8637 val_auc=0.8019
model=transformerconv top_k=50 fold=1 epoch=32 loss=3.0719 val_auc=0.8030
model=transformerconv top_k=50 fold=1 epoch=33 loss=3.5134 val_auc=0.8035
model=transformerconv top_k=50 fold=1 epoch=34 loss=3.2841 val_auc=0.8041
model=transformerconv top_k=50 fold=1 epoch=35 loss=3.4229 val_auc=0.8046
model=transformerconv top_k=50 fold=1 epoch=36 loss=2.9202 val_auc=0.8049
model=transformerconv top_k=50 fold=1 epoch=37 loss=2.4923 val_auc=0.8055
model=transformerconv top_k=50 fold=1 epoch=38 loss=2.7129 val_auc=0.8061
model=transformerconv top_k=50 fold=1 epoch=39 loss=3.5146 val_auc=0.8069
model=transformerconv top_k=50 fold=1 epoch=40 loss=3.4337 val_auc=0.8077
model=transformerconv top_k=50 fold=1 epoch=41 loss=2.6590 val_auc=0.8085
model=transformerconv top_k=50 fold=1 epoch=42 loss=2.2631 val_auc=0.8095
model=transformerconv top_k=50 fold=1 epoch=43 loss=2.8004 val_auc=0.8103
model=transformerconv top_k=50 fold=1 epoch=44 loss=2.6004 val_auc=0.8110
model=transformerconv top_k=50 fold=1 epoch=45 loss=2.3711 val_auc=0.8119
model=transformerconv top_k=50 fold=1 epoch=46 loss=2.3654 val_auc=0.8127
model=transformerconv top_k=50 fold=1 epoch=47 loss=2.1195 val_auc=0.8133
model=transformerconv top_k=50 fold=1 epoch=48 loss=2.7109 val_auc=0.8137
model=transformerconv top_k=50 fold=1 epoch=49 loss=3.8211 val_auc=0.8141
model=transformerconv top_k=50 fold=1 epoch=50 loss=3.5812 val_auc=0.8144
model=transformerconv top_k=50 fold=1 epoch=51 loss=3.2275 val_auc=0.8146
model=transformerconv top_k=50 fold=1 epoch=52 loss=1.9686 val_auc=0.8147
model=transformerconv top_k=50 fold=1 epoch=53 loss=1.9870 val_auc=0.8151
model=transformerconv top_k=50 fold=1 epoch=54 loss=1.9285 val_auc=0.8154
model=transformerconv top_k=50 fold=1 epoch=55 loss=2.0253 val_auc=0.8158
model=transformerconv top_k=50 fold=1 epoch=56 loss=2.0387 val_auc=0.8161
model=transformerconv top_k=50 fold=1 epoch=57 loss=1.6038 val_auc=0.8171
model=transformerconv top_k=50 fold=1 epoch=58 loss=1.8285 val_auc=0.8182
model=transformerconv top_k=50 fold=1 epoch=59 loss=1.6868 val_auc=0.8194
model=transformerconv top_k=50 fold=1 epoch=60 loss=1.8796 val_auc=0.8206
model=transformerconv top_k=50 fold=1 epoch=61 loss=1.5800 val_auc=0.8219
model=transformerconv top_k=50 fold=1 epoch=62 loss=1.5545 val_auc=0.8232
model=transformerconv top_k=50 fold=1 epoch=63 loss=1.7555 val_auc=0.8237
model=transformerconv top_k=50 fold=1 epoch=64 loss=1.5803 val_auc=0.8244
model=transformerconv top_k=50 fold=1 epoch=65 loss=1.6127 val_auc=0.8249
model=transformerconv top_k=50 fold=1 epoch=66 loss=1.4967 val_auc=0.8250
model=transformerconv top_k=50 fold=1 epoch=67 loss=1.3783 val_auc=0.8253
model=transformerconv top_k=50 fold=1 epoch=68 loss=1.5409 val_auc=0.8256
model=transformerconv top_k=50 fold=1 epoch=69 loss=1.6126 val_auc=0.8262
model=transformerconv top_k=50 fold=1 epoch=70 loss=1.3885 val_auc=0.8268
model=transformerconv top_k=50 fold=1 epoch=71 loss=1.4497 val_auc=0.8278
model=transformerconv top_k=50 fold=1 epoch=72 loss=1.4305 val_auc=0.8287
model=transformerconv top_k=50 fold=1 epoch=73 loss=1.4065 val_auc=0.8294
model=transformerconv top_k=50 fold=1 epoch=74 loss=1.3072 val_auc=0.8300
model=transformerconv top_k=50 fold=1 epoch=75 loss=1.2830 val_auc=0.8305
model=transformerconv top_k=50 fold=1 epoch=76 loss=1.2774 val_auc=0.8306
model=transformerconv top_k=50 fold=1 epoch=77 loss=1.4209 val_auc=0.8305
model=transformerconv top_k=50 fold=1 epoch=78 loss=1.3441 val_auc=0.8307
model=transformerconv top_k=50 fold=1 epoch=79 loss=1.3955 val_auc=0.8310
model=transformerconv top_k=50 fold=1 epoch=80 loss=1.1760 val_auc=0.8318
model=transformerconv top_k=50 fold=1 epoch=81 loss=1.2520 val_auc=0.8328
model=transformerconv top_k=50 fold=1 epoch=82 loss=1.2122 val_auc=0.8334
model=transformerconv top_k=50 fold=1 epoch=83 loss=1.2999 val_auc=0.8340
model=transformerconv top_k=50 fold=1 epoch=84 loss=1.3015 val_auc=0.8353
model=transformerconv top_k=50 fold=1 epoch=85 loss=1.2257 val_auc=0.8358
model=transformerconv top_k=50 fold=1 epoch=86 loss=1.2473 val_auc=0.8353
model=transformerconv top_k=50 fold=1 epoch=87 loss=1.1415 val_auc=0.8357
model=transformerconv top_k=50 fold=1 epoch=88 loss=1.2408 val_auc=0.8354
model=transformerconv top_k=50 fold=1 epoch=89 loss=1.1814 val_auc=0.8358
model=transformerconv top_k=50 fold=1 epoch=90 loss=1.1306 val_auc=0.8358
model=transformerconv top_k=50 fold=1 epoch=91 loss=1.0987 val_auc=0.8354
model=transformerconv top_k=50 fold=1 epoch=92 loss=1.1698 val_auc=0.8359
model=transformerconv top_k=50 fold=1 epoch=93 loss=1.1669 val_auc=0.8369
model=transformerconv top_k=50 fold=1 epoch=94 loss=1.1664 val_auc=0.8372
model=transformerconv top_k=50 fold=1 epoch=95 loss=1.1237 val_auc=0.8370
model=transformerconv top_k=50 fold=1 epoch=96 loss=1.1012 val_auc=0.8374
model=transformerconv top_k=50 fold=1 epoch=97 loss=1.0613 val_auc=0.8381
model=transformerconv top_k=50 fold=1 epoch=98 loss=1.0670 val_auc=0.8383
model=transformerconv top_k=50 fold=1 epoch=99 loss=1.0786 val_auc=0.8385
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719209 edges

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=50 fold=2 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718855 edges
model=transformerconv top_k=50 fold=2 epoch=0 loss=7.5940 val_auc=0.4988
model=transformerconv top_k=50 fold=2 epoch=1 loss=24.5023 val_auc=0.5171
model=transformerconv top_k=50 fold=2 epoch=2 loss=18.2560 val_auc=0.7545
model=transformerconv top_k=50 fold=2 epoch=3 loss=5.6491 val_auc=0.7642
model=transformerconv top_k=50 fold=2 epoch=4 loss=8.3378 val_auc=0.7622
model=transformerconv top_k=50 fold=2 epoch=5 loss=9.4381 val_auc=0.7653
model=transformerconv top_k=50 fold=2 epoch=6 loss=5.7913 val_auc=0.7691
model=transformerconv top_k=50 fold=2 epoch=7 loss=5.0239 val_auc=0.7711
model=transformerconv top_k=50 fold=2 epoch=8 loss=3.9114 val_auc=0.7723
model=transformerconv top_k=50 fold=2 epoch=9 loss=3.4027 val_auc=0.7756
model=transformerconv top_k=50 fold=2 epoch=10 loss=4.5472 val_auc=0.7776
model=transformerconv top_k=50 fold=2 epoch=11 loss=4.2044 val_auc=0.7785
model=transformerconv top_k=50 fold=2 epoch=12 loss=3.7653 val_auc=0.7810
model=transformerconv top_k=50 fold=2 epoch=13 loss=3.5551 val_auc=0.7844
model=transformerconv top_k=50 fold=2 epoch=14 loss=3.2874 val_auc=0.7873
model=transformerconv top_k=50 fold=2 epoch=15 loss=3.2528 val_auc=0.7902
model=transformerconv top_k=50 fold=2 epoch=16 loss=3.3179 val_auc=0.7924
model=transformerconv top_k=50 fold=2 epoch=17 loss=2.9324 val_auc=0.7947
model=transformerconv top_k=50 fold=2 epoch=18 loss=2.9153 val_auc=0.7962
model=transformerconv top_k=50 fold=2 epoch=19 loss=2.9762 val_auc=0.7978
model=transformerconv top_k=50 fold=2 epoch=20 loss=2.7434 val_auc=0.7985
model=transformerconv top_k=50 fold=2 epoch=21 loss=2.8481 val_auc=0.7997
model=transformerconv top_k=50 fold=2 epoch=22 loss=2.4142 val_auc=0.8017
model=transformerconv top_k=50 fold=2 epoch=23 loss=2.3614 val_auc=0.8036
model=transformerconv top_k=50 fold=2 epoch=24 loss=2.2826 val_auc=0.8056
model=transformerconv top_k=50 fold=2 epoch=25 loss=2.3409 val_auc=0.8073
model=transformerconv top_k=50 fold=2 epoch=26 loss=2.2492 val_auc=0.8087
model=transformerconv top_k=50 fold=2 epoch=27 loss=2.2336 val_auc=0.8109
model=transformerconv top_k=50 fold=2 epoch=28 loss=2.7548 val_auc=0.8126
model=transformerconv top_k=50 fold=2 epoch=29 loss=2.1449 val_auc=0.8140
model=transformerconv top_k=50 fold=2 epoch=30 loss=2.2752 val_auc=0.8147
model=transformerconv top_k=50 fold=2 epoch=31 loss=2.3062 val_auc=0.8151
model=transformerconv top_k=50 fold=2 epoch=32 loss=1.9810 val_auc=0.8153
model=transformerconv top_k=50 fold=2 epoch=33 loss=1.9186 val_auc=0.8156
model=transformerconv top_k=50 fold=2 epoch=34 loss=1.9121 val_auc=0.8157
model=transformerconv top_k=50 fold=2 epoch=35 loss=1.8303 val_auc=0.8159
model=transformerconv top_k=50 fold=2 epoch=36 loss=1.9718 val_auc=0.8164
model=transformerconv top_k=50 fold=2 epoch=37 loss=1.9263 val_auc=0.8168
model=transformerconv top_k=50 fold=2 epoch=38 loss=1.9589 val_auc=0.8169
model=transformerconv top_k=50 fold=2 epoch=39 loss=2.1086 val_auc=0.8172
model=transformerconv top_k=50 fold=2 epoch=40 loss=2.1226 val_auc=0.8181
model=transformerconv top_k=50 fold=2 epoch=41 loss=1.6839 val_auc=0.8193
model=transformerconv top_k=50 fold=2 epoch=42 loss=1.8244 val_auc=0.8202
model=transformerconv top_k=50 fold=2 epoch=43 loss=1.9228 val_auc=0.8211
model=transformerconv top_k=50 fold=2 epoch=44 loss=1.5999 val_auc=0.8218
model=transformerconv top_k=50 fold=2 epoch=45 loss=1.8117 val_auc=0.8225
model=transformerconv top_k=50 fold=2 epoch=46 loss=1.8963 val_auc=0.8230
model=transformerconv top_k=50 fold=2 epoch=47 loss=1.7120 val_auc=0.8235
model=transformerconv top_k=50 fold=2 epoch=48 loss=1.6338 val_auc=0.8238
model=transformerconv top_k=50 fold=2 epoch=49 loss=1.8461 val_auc=0.8240
model=transformerconv top_k=50 fold=2 epoch=50 loss=1.6240 val_auc=0.8242
model=transformerconv top_k=50 fold=2 epoch=51 loss=1.3408 val_auc=0.8247
model=transformerconv top_k=50 fold=2 epoch=52 loss=1.4648 val_auc=0.8252
model=transformerconv top_k=50 fold=2 epoch=53 loss=1.3878 val_auc=0.8256
model=transformerconv top_k=50 fold=2 epoch=54 loss=1.3701 val_auc=0.8259
model=transformerconv top_k=50 fold=2 epoch=55 loss=1.6413 val_auc=0.8260
model=transformerconv top_k=50 fold=2 epoch=56 loss=1.2573 val_auc=0.8262
model=transformerconv top_k=50 fold=2 epoch=57 loss=1.2485 val_auc=0.8265
model=transformerconv top_k=50 fold=2 epoch=58 loss=1.6262 val_auc=0.8268
model=transformerconv top_k=50 fold=2 epoch=59 loss=1.6057 val_auc=0.8270
model=transformerconv top_k=50 fold=2 epoch=60 loss=1.2746 val_auc=0.8271
model=transformerconv top_k=50 fold=2 epoch=61 loss=1.3274 val_auc=0.8269
model=transformerconv top_k=50 fold=2 epoch=62 loss=1.5343 val_auc=0.8268
model=transformerconv top_k=50 fold=2 epoch=63 loss=1.3480 val_auc=0.8267
model=transformerconv top_k=50 fold=2 epoch=64 loss=1.3024 val_auc=0.8267
model=transformerconv top_k=50 fold=2 epoch=65 loss=1.1968 val_auc=0.8261
model=transformerconv top_k=50 fold=2 epoch=66 loss=1.2860 val_auc=0.8253
model=transformerconv top_k=50 fold=2 epoch=67 loss=1.3792 val_auc=0.8248
model=transformerconv top_k=50 fold=2 epoch=68 loss=1.3308 val_auc=0.8247
model=transformerconv top_k=50 fold=2 epoch=69 loss=1.2089 val_auc=0.8250
model=transformerconv top_k=50 fold=2 epoch=70 loss=1.2331 val_auc=0.8255
model=transformerconv top_k=50 fold=2 epoch=71 loss=1.3485 val_auc=0.8258
model=transformerconv top_k=50 fold=2 epoch=72 loss=1.0819 val_auc=0.8266
transformerconv top_k=50 fold=2: early stopping at epoch 72
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718855 edges

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=50 fold=3 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719213 edges
model=transformerconv top_k=50 fold=3 epoch=0 loss=8.1436 val_auc=0.5023
model=transformerconv top_k=50 fold=3 epoch=1 loss=26.9975 val_auc=0.5231
model=transformerconv top_k=50 fold=3 epoch=2 loss=23.3174 val_auc=0.7286
model=transformerconv top_k=50 fold=3 epoch=3 loss=11.0879 val_auc=0.7570
model=transformerconv top_k=50 fold=3 epoch=4 loss=5.4258 val_auc=0.7647
model=transformerconv top_k=50 fold=3 epoch=5 loss=6.0312 val_auc=0.7655
model=transformerconv top_k=50 fold=3 epoch=6 loss=5.8143 val_auc=0.7640
model=transformerconv top_k=50 fold=3 epoch=7 loss=4.5187 val_auc=0.7661
model=transformerconv top_k=50 fold=3 epoch=8 loss=4.7651 val_auc=0.7703
model=transformerconv top_k=50 fold=3 epoch=9 loss=6.2156 val_auc=0.7743
model=transformerconv top_k=50 fold=3 epoch=10 loss=5.2031 val_auc=0.7786
model=transformerconv top_k=50 fold=3 epoch=11 loss=4.5477 val_auc=0.7824
model=transformerconv top_k=50 fold=3 epoch=12 loss=4.2332 val_auc=0.7851
model=transformerconv top_k=50 fold=3 epoch=13 loss=3.6671 val_auc=0.7873
model=transformerconv top_k=50 fold=3 epoch=14 loss=3.6346 val_auc=0.7899
model=transformerconv top_k=50 fold=3 epoch=15 loss=3.7515 val_auc=0.7926
model=transformerconv top_k=50 fold=3 epoch=16 loss=3.8290 val_auc=0.7947
model=transformerconv top_k=50 fold=3 epoch=17 loss=3.2892 val_auc=0.7962
model=transformerconv top_k=50 fold=3 epoch=18 loss=2.9153 val_auc=0.7983
model=transformerconv top_k=50 fold=3 epoch=19 loss=2.9574 val_auc=0.8002
model=transformerconv top_k=50 fold=3 epoch=20 loss=3.2450 val_auc=0.8019
model=transformerconv top_k=50 fold=3 epoch=21 loss=2.6464 val_auc=0.8031
model=transformerconv top_k=50 fold=3 epoch=22 loss=3.3979 val_auc=0.8041
model=transformerconv top_k=50 fold=3 epoch=23 loss=2.5368 val_auc=0.8054
model=transformerconv top_k=50 fold=3 epoch=24 loss=3.0514 val_auc=0.8069
model=transformerconv top_k=50 fold=3 epoch=25 loss=2.8724 val_auc=0.8082
model=transformerconv top_k=50 fold=3 epoch=26 loss=2.5667 val_auc=0.8090
model=transformerconv top_k=50 fold=3 epoch=27 loss=2.1330 val_auc=0.8103
model=transformerconv top_k=50 fold=3 epoch=28 loss=2.4603 val_auc=0.8111
model=transformerconv top_k=50 fold=3 epoch=29 loss=2.3707 val_auc=0.8122
model=transformerconv top_k=50 fold=3 epoch=30 loss=2.3507 val_auc=0.8129
model=transformerconv top_k=50 fold=3 epoch=31 loss=2.1523 val_auc=0.8142
model=transformerconv top_k=50 fold=3 epoch=32 loss=2.1124 val_auc=0.8151
model=transformerconv top_k=50 fold=3 epoch=33 loss=2.4090 val_auc=0.8157
model=transformerconv top_k=50 fold=3 epoch=34 loss=1.9940 val_auc=0.8162
model=transformerconv top_k=50 fold=3 epoch=35 loss=1.7875 val_auc=0.8160
model=transformerconv top_k=50 fold=3 epoch=36 loss=1.8981 val_auc=0.8163
model=transformerconv top_k=50 fold=3 epoch=37 loss=2.2184 val_auc=0.8168
model=transformerconv top_k=50 fold=3 epoch=38 loss=2.5902 val_auc=0.8177
model=transformerconv top_k=50 fold=3 epoch=39 loss=1.4659 val_auc=0.8184
model=transformerconv top_k=50 fold=3 epoch=40 loss=1.6497 val_auc=0.8185
model=transformerconv top_k=50 fold=3 epoch=41 loss=1.7895 val_auc=0.8187
model=transformerconv top_k=50 fold=3 epoch=42 loss=1.7691 val_auc=0.8191
model=transformerconv top_k=50 fold=3 epoch=43 loss=1.5250 val_auc=0.8192
model=transformerconv top_k=50 fold=3 epoch=44 loss=1.5226 val_auc=0.8195
model=transformerconv top_k=50 fold=3 epoch=45 loss=1.5513 val_auc=0.8193
model=transformerconv top_k=50 fold=3 epoch=46 loss=1.5411 val_auc=0.8195
model=transformerconv top_k=50 fold=3 epoch=47 loss=1.7409 val_auc=0.8203
model=transformerconv top_k=50 fold=3 epoch=48 loss=1.3598 val_auc=0.8201
model=transformerconv top_k=50 fold=3 epoch=49 loss=1.7194 val_auc=0.8200
model=transformerconv top_k=50 fold=3 epoch=50 loss=1.5333 val_auc=0.8204
model=transformerconv top_k=50 fold=3 epoch=51 loss=1.4658 val_auc=0.8210
model=transformerconv top_k=50 fold=3 epoch=52 loss=1.4105 val_auc=0.8211
model=transformerconv top_k=50 fold=3 epoch=53 loss=1.5393 val_auc=0.8211
model=transformerconv top_k=50 fold=3 epoch=54 loss=1.5525 val_auc=0.8211
model=transformerconv top_k=50 fold=3 epoch=55 loss=1.3590 val_auc=0.8214
model=transformerconv top_k=50 fold=3 epoch=56 loss=1.8871 val_auc=0.8217
model=transformerconv top_k=50 fold=3 epoch=57 loss=2.1112 val_auc=0.8219
model=transformerconv top_k=50 fold=3 epoch=58 loss=1.7614 val_auc=0.8216
model=transformerconv top_k=50 fold=3 epoch=59 loss=1.5265 val_auc=0.8209
model=transformerconv top_k=50 fold=3 epoch=60 loss=1.4758 val_auc=0.8208
model=transformerconv top_k=50 fold=3 epoch=61 loss=1.8553 val_auc=0.8211
model=transformerconv top_k=50 fold=3 epoch=62 loss=1.8345 val_auc=0.8219
model=transformerconv top_k=50 fold=3 epoch=63 loss=1.4974 val_auc=0.8228
model=transformerconv top_k=50 fold=3 epoch=64 loss=1.3345 val_auc=0.8241
model=transformerconv top_k=50 fold=3 epoch=65 loss=1.5426 val_auc=0.8249
model=transformerconv top_k=50 fold=3 epoch=66 loss=1.6406 val_auc=0.8257
model=transformerconv top_k=50 fold=3 epoch=67 loss=1.5353 val_auc=0.8267
model=transformerconv top_k=50 fold=3 epoch=68 loss=1.3791 val_auc=0.8272
model=transformerconv top_k=50 fold=3 epoch=69 loss=1.3456 val_auc=0.8274
model=transformerconv top_k=50 fold=3 epoch=70 loss=1.2467 val_auc=0.8272
model=transformerconv top_k=50 fold=3 epoch=71 loss=1.3038 val_auc=0.8266
model=transformerconv top_k=50 fold=3 epoch=72 loss=1.4878 val_auc=0.8266
model=transformerconv top_k=50 fold=3 epoch=73 loss=1.4092 val_auc=0.8268
model=transformerconv top_k=50 fold=3 epoch=74 loss=1.3374 val_auc=0.8270
model=transformerconv top_k=50 fold=3 epoch=75 loss=1.1872 val_auc=0.8270
model=transformerconv top_k=50 fold=3 epoch=76 loss=1.1964 val_auc=0.8270
model=transformerconv top_k=50 fold=3 epoch=77 loss=1.2702 val_auc=0.8272
model=transformerconv top_k=50 fold=3 epoch=78 loss=1.0918 val_auc=0.8277
model=transformerconv top_k=50 fold=3 epoch=79 loss=1.1498 val_auc=0.8278
model=transformerconv top_k=50 fold=3 epoch=80 loss=1.2578 val_auc=0.8281
model=transformerconv top_k=50 fold=3 epoch=81 loss=1.2140 val_auc=0.8282
model=transformerconv top_k=50 fold=3 epoch=82 loss=1.2331 val_auc=0.8282
model=transformerconv top_k=50 fold=3 epoch=83 loss=1.2034 val_auc=0.8285
model=transformerconv top_k=50 fold=3 epoch=84 loss=1.1377 val_auc=0.8286
model=transformerconv top_k=50 fold=3 epoch=85 loss=1.3573 val_auc=0.8289
model=transformerconv top_k=50 fold=3 epoch=86 loss=1.2850 val_auc=0.8291
model=transformerconv top_k=50 fold=3 epoch=87 loss=1.0395 val_auc=0.8294
model=transformerconv top_k=50 fold=3 epoch=88 loss=1.2345 val_auc=0.8298
model=transformerconv top_k=50 fold=3 epoch=89 loss=1.0953 val_auc=0.8303
model=transformerconv top_k=50 fold=3 epoch=90 loss=1.1831 val_auc=0.8305
model=transformerconv top_k=50 fold=3 epoch=91 loss=1.2041 val_auc=0.8306
model=transformerconv top_k=50 fold=3 epoch=92 loss=1.1735 val_auc=0.8309
model=transformerconv top_k=50 fold=3 epoch=93 loss=1.1075 val_auc=0.8312
model=transformerconv top_k=50 fold=3 epoch=94 loss=1.0556 val_auc=0.8313
model=transformerconv top_k=50 fold=3 epoch=95 loss=1.0414 val_auc=0.8315
model=transformerconv top_k=50 fold=3 epoch=96 loss=1.1202 val_auc=0.8317
model=transformerconv top_k=50 fold=3 epoch=97 loss=1.1444 val_auc=0.8317
model=transformerconv top_k=50 fold=3 epoch=98 loss=1.0532 val_auc=0.8315
model=transformerconv top_k=50 fold=3 epoch=99 loss=1.0557 val_auc=0.8316
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719213 edges

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=50 fold=4 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719233 edges
model=transformerconv top_k=50 fold=4 epoch=0 loss=6.8173 val_auc=0.5012
model=transformerconv top_k=50 fold=4 epoch=1 loss=33.0490 val_auc=0.5191
model=transformerconv top_k=50 fold=4 epoch=2 loss=23.8128 val_auc=0.7067
model=transformerconv top_k=50 fold=4 epoch=3 loss=9.7102 val_auc=0.7252
model=transformerconv top_k=50 fold=4 epoch=4 loss=6.7408 val_auc=0.7310
model=transformerconv top_k=50 fold=4 epoch=5 loss=9.0676 val_auc=0.7334
model=transformerconv top_k=50 fold=4 epoch=6 loss=6.8438 val_auc=0.7331
model=transformerconv top_k=50 fold=4 epoch=7 loss=4.0746 val_auc=0.7476
model=transformerconv top_k=50 fold=4 epoch=8 loss=4.8995 val_auc=0.7625
model=transformerconv top_k=50 fold=4 epoch=9 loss=4.3479 val_auc=0.7750
model=transformerconv top_k=50 fold=4 epoch=10 loss=4.4292 val_auc=0.7826
model=transformerconv top_k=50 fold=4 epoch=11 loss=4.0670 val_auc=0.7877
model=transformerconv top_k=50 fold=4 epoch=12 loss=3.8838 val_auc=0.7911
model=transformerconv top_k=50 fold=4 epoch=13 loss=3.4493 val_auc=0.7923
model=transformerconv top_k=50 fold=4 epoch=14 loss=3.6370 val_auc=0.7928
model=transformerconv top_k=50 fold=4 epoch=15 loss=3.3324 val_auc=0.7933
model=transformerconv top_k=50 fold=4 epoch=16 loss=3.6933 val_auc=0.7947
model=transformerconv top_k=50 fold=4 epoch=17 loss=3.3471 val_auc=0.7968
model=transformerconv top_k=50 fold=4 epoch=18 loss=3.1209 val_auc=0.7983
model=transformerconv top_k=50 fold=4 epoch=19 loss=3.3284 val_auc=0.8003
model=transformerconv top_k=50 fold=4 epoch=20 loss=2.6058 val_auc=0.8029
model=transformerconv top_k=50 fold=4 epoch=21 loss=2.8013 val_auc=0.8054
model=transformerconv top_k=50 fold=4 epoch=22 loss=3.3847 val_auc=0.8073
model=transformerconv top_k=50 fold=4 epoch=23 loss=2.9236 val_auc=0.8091
model=transformerconv top_k=50 fold=4 epoch=24 loss=2.8949 val_auc=0.8109
model=transformerconv top_k=50 fold=4 epoch=25 loss=2.6715 val_auc=0.8129
model=transformerconv top_k=50 fold=4 epoch=26 loss=2.8111 val_auc=0.8148
model=transformerconv top_k=50 fold=4 epoch=27 loss=2.5418 val_auc=0.8161
model=transformerconv top_k=50 fold=4 epoch=28 loss=2.5518 val_auc=0.8169
model=transformerconv top_k=50 fold=4 epoch=29 loss=2.6753 val_auc=0.8172
model=transformerconv top_k=50 fold=4 epoch=30 loss=2.2710 val_auc=0.8178
model=transformerconv top_k=50 fold=4 epoch=31 loss=2.6049 val_auc=0.8186
model=transformerconv top_k=50 fold=4 epoch=32 loss=2.2022 val_auc=0.8193
model=transformerconv top_k=50 fold=4 epoch=33 loss=2.2575 val_auc=0.8197
model=transformerconv top_k=50 fold=4 epoch=34 loss=2.2126 val_auc=0.8200
model=transformerconv top_k=50 fold=4 epoch=35 loss=2.0476 val_auc=0.8200
model=transformerconv top_k=50 fold=4 epoch=36 loss=2.1790 val_auc=0.8201
model=transformerconv top_k=50 fold=4 epoch=37 loss=2.1872 val_auc=0.8202
model=transformerconv top_k=50 fold=4 epoch=38 loss=1.9711 val_auc=0.8209
model=transformerconv top_k=50 fold=4 epoch=39 loss=1.7321 val_auc=0.8219
model=transformerconv top_k=50 fold=4 epoch=40 loss=1.7337 val_auc=0.8227
model=transformerconv top_k=50 fold=4 epoch=41 loss=1.6134 val_auc=0.8234
model=transformerconv top_k=50 fold=4 epoch=42 loss=1.7350 val_auc=0.8243
model=transformerconv top_k=50 fold=4 epoch=43 loss=1.8834 val_auc=0.8250
model=transformerconv top_k=50 fold=4 epoch=44 loss=1.7513 val_auc=0.8256
model=transformerconv top_k=50 fold=4 epoch=45 loss=1.8069 val_auc=0.8257
model=transformerconv top_k=50 fold=4 epoch=46 loss=1.7885 val_auc=0.8252
model=transformerconv top_k=50 fold=4 epoch=47 loss=1.8123 val_auc=0.8245
model=transformerconv top_k=50 fold=4 epoch=48 loss=1.7139 val_auc=0.8246
model=transformerconv top_k=50 fold=4 epoch=49 loss=1.5999 val_auc=0.8255
model=transformerconv top_k=50 fold=4 epoch=50 loss=1.5417 val_auc=0.8264
model=transformerconv top_k=50 fold=4 epoch=51 loss=1.3599 val_auc=0.8272
model=transformerconv top_k=50 fold=4 epoch=52 loss=1.5938 val_auc=0.8273
model=transformerconv top_k=50 fold=4 epoch=53 loss=1.6934 val_auc=0.8270
model=transformerconv top_k=50 fold=4 epoch=54 loss=1.4403 val_auc=0.8262
model=transformerconv top_k=50 fold=4 epoch=55 loss=1.7732 val_auc=0.8252
model=transformerconv top_k=50 fold=4 epoch=56 loss=1.8515 val_auc=0.8254
model=transformerconv top_k=50 fold=4 epoch=57 loss=1.7134 val_auc=0.8262
model=transformerconv top_k=50 fold=4 epoch=58 loss=1.6294 val_auc=0.8270
model=transformerconv top_k=50 fold=4 epoch=59 loss=1.4877 val_auc=0.8268
model=transformerconv top_k=50 fold=4 epoch=60 loss=1.6071 val_auc=0.8262
model=transformerconv top_k=50 fold=4 epoch=61 loss=1.5262 val_auc=0.8258
model=transformerconv top_k=50 fold=4 epoch=62 loss=1.5732 val_auc=0.8259
model=transformerconv top_k=50 fold=4 epoch=63 loss=1.5287 val_auc=0.8262
model=transformerconv top_k=50 fold=4 epoch=64 loss=1.3796 val_auc=0.8270
transformerconv top_k=50 fold=4: early stopping at epoch 64
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719233 edges

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=50 fold=5 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718759 edges
model=transformerconv top_k=50 fold=5 epoch=0 loss=7.4818 val_auc=0.4407
model=transformerconv top_k=50 fold=5 epoch=1 loss=20.4735 val_auc=0.5405
model=transformerconv top_k=50 fold=5 epoch=2 loss=15.2655 val_auc=0.6521
model=transformerconv top_k=50 fold=5 epoch=3 loss=8.1582 val_auc=0.6719
model=transformerconv top_k=50 fold=5 epoch=4 loss=5.5449 val_auc=0.7101
model=transformerconv top_k=50 fold=5 epoch=5 loss=5.9365 val_auc=0.7288
model=transformerconv top_k=50 fold=5 epoch=6 loss=5.7509 val_auc=0.7476
model=transformerconv top_k=50 fold=5 epoch=7 loss=4.8894 val_auc=0.7612
model=transformerconv top_k=50 fold=5 epoch=8 loss=4.0083 val_auc=0.7690
model=transformerconv top_k=50 fold=5 epoch=9 loss=3.8778 val_auc=0.7726
model=transformerconv top_k=50 fold=5 epoch=10 loss=3.6097 val_auc=0.7782
model=transformerconv top_k=50 fold=5 epoch=11 loss=4.3733 val_auc=0.7810
model=transformerconv top_k=50 fold=5 epoch=12 loss=3.5364 val_auc=0.7843
model=transformerconv top_k=50 fold=5 epoch=13 loss=3.7994 val_auc=0.7888
model=transformerconv top_k=50 fold=5 epoch=14 loss=4.1091 val_auc=0.7928
model=transformerconv top_k=50 fold=5 epoch=15 loss=3.2881 val_auc=0.7965
model=transformerconv top_k=50 fold=5 epoch=16 loss=2.9042 val_auc=0.7997
model=transformerconv top_k=50 fold=5 epoch=17 loss=2.7697 val_auc=0.8026
model=transformerconv top_k=50 fold=5 epoch=18 loss=3.0089 val_auc=0.8050
model=transformerconv top_k=50 fold=5 epoch=19 loss=2.6909 val_auc=0.8065
model=transformerconv top_k=50 fold=5 epoch=20 loss=2.8592 val_auc=0.8073
model=transformerconv top_k=50 fold=5 epoch=21 loss=2.7563 val_auc=0.8082
model=transformerconv top_k=50 fold=5 epoch=22 loss=2.7611 val_auc=0.8090
model=transformerconv top_k=50 fold=5 epoch=23 loss=2.3460 val_auc=0.8107
model=transformerconv top_k=50 fold=5 epoch=24 loss=2.7301 val_auc=0.8125
model=transformerconv top_k=50 fold=5 epoch=25 loss=2.1447 val_auc=0.8141
model=transformerconv top_k=50 fold=5 epoch=26 loss=2.6046 val_auc=0.8154
model=transformerconv top_k=50 fold=5 epoch=27 loss=2.9551 val_auc=0.8163
model=transformerconv top_k=50 fold=5 epoch=28 loss=2.3463 val_auc=0.8172
model=transformerconv top_k=50 fold=5 epoch=29 loss=2.4572 val_auc=0.8180
model=transformerconv top_k=50 fold=5 epoch=30 loss=2.3311 val_auc=0.8190
model=transformerconv top_k=50 fold=5 epoch=31 loss=2.2167 val_auc=0.8201
model=transformerconv top_k=50 fold=5 epoch=32 loss=2.2280 val_auc=0.8210
model=transformerconv top_k=50 fold=5 epoch=33 loss=2.3098 val_auc=0.8215
model=transformerconv top_k=50 fold=5 epoch=34 loss=1.8601 val_auc=0.8221
model=transformerconv top_k=50 fold=5 epoch=35 loss=2.0494 val_auc=0.8228
model=transformerconv top_k=50 fold=5 epoch=36 loss=1.9415 val_auc=0.8234
model=transformerconv top_k=50 fold=5 epoch=37 loss=1.7757 val_auc=0.8241
model=transformerconv top_k=50 fold=5 epoch=38 loss=1.7841 val_auc=0.8247
model=transformerconv top_k=50 fold=5 epoch=39 loss=1.8942 val_auc=0.8252
model=transformerconv top_k=50 fold=5 epoch=40 loss=1.6315 val_auc=0.8261
model=transformerconv top_k=50 fold=5 epoch=41 loss=1.6572 val_auc=0.8269
model=transformerconv top_k=50 fold=5 epoch=42 loss=1.6358 val_auc=0.8279
model=transformerconv top_k=50 fold=5 epoch=43 loss=1.5460 val_auc=0.8288
model=transformerconv top_k=50 fold=5 epoch=44 loss=1.6878 val_auc=0.8297
model=transformerconv top_k=50 fold=5 epoch=45 loss=1.6935 val_auc=0.8302
model=transformerconv top_k=50 fold=5 epoch=46 loss=1.6498 val_auc=0.8307
model=transformerconv top_k=50 fold=5 epoch=47 loss=1.6738 val_auc=0.8311
model=transformerconv top_k=50 fold=5 epoch=48 loss=1.4410 val_auc=0.8316
model=transformerconv top_k=50 fold=5 epoch=49 loss=1.5779 val_auc=0.8323
model=transformerconv top_k=50 fold=5 epoch=50 loss=1.4909 val_auc=0.8328
model=transformerconv top_k=50 fold=5 epoch=51 loss=1.5254 val_auc=0.8332
model=transformerconv top_k=50 fold=5 epoch=52 loss=1.4171 val_auc=0.8333
model=transformerconv top_k=50 fold=5 epoch=53 loss=1.2601 val_auc=0.8335
model=transformerconv top_k=50 fold=5 epoch=54 loss=1.4547 val_auc=0.8335
model=transformerconv top_k=50 fold=5 epoch=55 loss=1.4045 val_auc=0.8335
model=transformerconv top_k=50 fold=5 epoch=56 loss=1.4974 val_auc=0.8335
model=transformerconv top_k=50 fold=5 epoch=57 loss=1.6355 val_auc=0.8336
model=transformerconv top_k=50 fold=5 epoch=58 loss=1.3576 val_auc=0.8335
model=transformerconv top_k=50 fold=5 epoch=59 loss=1.4371 val_auc=0.8336
model=transformerconv top_k=50 fold=5 epoch=60 loss=1.2362 val_auc=0.8340
model=transformerconv top_k=50 fold=5 epoch=61 loss=1.2659 val_auc=0.8344
model=transformerconv top_k=50 fold=5 epoch=62 loss=1.3325 val_auc=0.8347
model=transformerconv top_k=50 fold=5 epoch=63 loss=1.3222 val_auc=0.8349
model=transformerconv top_k=50 fold=5 epoch=64 loss=1.2996 val_auc=0.8350
model=transformerconv top_k=50 fold=5 epoch=65 loss=1.2227 val_auc=0.8349
model=transformerconv top_k=50 fold=5 epoch=66 loss=1.2774 val_auc=0.8351
model=transformerconv top_k=50 fold=5 epoch=67 loss=1.2520 val_auc=0.8356
model=transformerconv top_k=50 fold=5 epoch=68 loss=1.1645 val_auc=0.8364
model=transformerconv top_k=50 fold=5 epoch=69 loss=1.2911 val_auc=0.8370
model=transformerconv top_k=50 fold=5 epoch=70 loss=1.1599 val_auc=0.8378
model=transformerconv top_k=50 fold=5 epoch=71 loss=1.1963 val_auc=0.8385
model=transformerconv top_k=50 fold=5 epoch=72 loss=1.2840 val_auc=0.8388
model=transformerconv top_k=50 fold=5 epoch=73 loss=1.2614 val_auc=0.8389
model=transformerconv top_k=50 fold=5 epoch=74 loss=1.0930 val_auc=0.8390
model=transformerconv top_k=50 fold=5 epoch=75 loss=1.1723 val_auc=0.8392
model=transformerconv top_k=50 fold=5 epoch=76 loss=1.6358 val_auc=0.8395
model=transformerconv top_k=50 fold=5 epoch=77 loss=1.2768 val_auc=0.8396
model=transformerconv top_k=50 fold=5 epoch=78 loss=1.1054 val_auc=0.8395
model=transformerconv top_k=50 fold=5 epoch=79 loss=1.1647 val_auc=0.8394
model=transformerconv top_k=50 fold=5 epoch=80 loss=1.1890 val_auc=0.8391
model=transformerconv top_k=50 fold=5 epoch=81 loss=1.1233 val_auc=0.8388
model=transformerconv top_k=50 fold=5 epoch=82 loss=1.2675 val_auc=0.8384
model=transformerconv top_k=50 fold=5 epoch=83 loss=1.0870 val_auc=0.8379
model=transformerconv top_k=50 fold=5 epoch=84 loss=1.2125 val_auc=0.8374
model=transformerconv top_k=50 fold=5 epoch=85 loss=1.3570 val_auc=0.8374
model=transformerconv top_k=50 fold=5 epoch=86 loss=1.2937 val_auc=0.8377
model=transformerconv top_k=50 fold=5 epoch=87 loss=1.0727 val_auc=0.8388
model=transformerconv top_k=50 fold=5 epoch=88 loss=1.3877 val_auc=0.8395
model=transformerconv top_k=50 fold=5 epoch=89 loss=1.7126 val_auc=0.8400
model=transformerconv top_k=50 fold=5 epoch=90 loss=1.4718 val_auc=0.8402
model=transformerconv top_k=50 fold=5 epoch=91 loss=1.2162 val_auc=0.8400
model=transformerconv top_k=50 fold=5 epoch=92 loss=1.1081 val_auc=0.8401
model=transformerconv top_k=50 fold=5 epoch=93 loss=1.2827 val_auc=0.8404
model=transformerconv top_k=50 fold=5 epoch=94 loss=1.2123 val_auc=0.8407
model=transformerconv top_k=50 fold=5 epoch=95 loss=1.0864 val_auc=0.8412
model=transformerconv top_k=50 fold=5 epoch=96 loss=1.1228 val_auc=0.8414
model=transformerconv top_k=50 fold=5 epoch=97 loss=1.3532 val_auc=0.8415
model=transformerconv top_k=50 fold=5 epoch=98 loss=1.3135 val_auc=0.8413
model=transformerconv top_k=50 fold=5 epoch=99 loss=1.0248 val_auc=0.8411
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718759 edges

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=50 fold=6 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718481 edges
model=transformerconv top_k=50 fold=6 epoch=0 loss=7.0209 val_auc=0.5002
model=transformerconv top_k=50 fold=6 epoch=1 loss=28.8786 val_auc=0.5127
model=transformerconv top_k=50 fold=6 epoch=2 loss=24.6665 val_auc=0.7340
model=transformerconv top_k=50 fold=6 epoch=3 loss=10.9691 val_auc=0.7531
model=transformerconv top_k=50 fold=6 epoch=4 loss=5.9388 val_auc=0.7579
model=transformerconv top_k=50 fold=6 epoch=5 loss=5.7447 val_auc=0.7603
model=transformerconv top_k=50 fold=6 epoch=6 loss=5.5933 val_auc=0.7644
model=transformerconv top_k=50 fold=6 epoch=7 loss=4.8249 val_auc=0.7699
model=transformerconv top_k=50 fold=6 epoch=8 loss=4.6459 val_auc=0.7739
model=transformerconv top_k=50 fold=6 epoch=9 loss=4.2339 val_auc=0.7786
model=transformerconv top_k=50 fold=6 epoch=10 loss=4.7411 val_auc=0.7837
model=transformerconv top_k=50 fold=6 epoch=11 loss=4.1813 val_auc=0.7878
model=transformerconv top_k=50 fold=6 epoch=12 loss=4.1426 val_auc=0.7906
model=transformerconv top_k=50 fold=6 epoch=13 loss=5.1405 val_auc=0.7919
model=transformerconv top_k=50 fold=6 epoch=14 loss=3.7162 val_auc=0.7931
model=transformerconv top_k=50 fold=6 epoch=15 loss=3.8898 val_auc=0.7956
model=transformerconv top_k=50 fold=6 epoch=16 loss=4.1995 val_auc=0.7982
model=transformerconv top_k=50 fold=6 epoch=17 loss=4.5215 val_auc=0.8007
model=transformerconv top_k=50 fold=6 epoch=18 loss=3.7049 val_auc=0.8027
model=transformerconv top_k=50 fold=6 epoch=19 loss=4.6702 val_auc=0.8042
model=transformerconv top_k=50 fold=6 epoch=20 loss=3.4738 val_auc=0.8054
model=transformerconv top_k=50 fold=6 epoch=21 loss=3.8026 val_auc=0.8066
model=transformerconv top_k=50 fold=6 epoch=22 loss=2.8668 val_auc=0.8077
model=transformerconv top_k=50 fold=6 epoch=23 loss=3.4098 val_auc=0.8087
model=transformerconv top_k=50 fold=6 epoch=24 loss=3.2132 val_auc=0.8097
model=transformerconv top_k=50 fold=6 epoch=25 loss=3.7188 val_auc=0.8106
model=transformerconv top_k=50 fold=6 epoch=26 loss=2.6406 val_auc=0.8118
model=transformerconv top_k=50 fold=6 epoch=27 loss=2.8790 val_auc=0.8129
model=transformerconv top_k=50 fold=6 epoch=28 loss=2.9964 val_auc=0.8141
model=transformerconv top_k=50 fold=6 epoch=29 loss=2.4984 val_auc=0.8151
model=transformerconv top_k=50 fold=6 epoch=30 loss=2.4967 val_auc=0.8156
model=transformerconv top_k=50 fold=6 epoch=31 loss=2.8089 val_auc=0.8162
model=transformerconv top_k=50 fold=6 epoch=32 loss=3.6214 val_auc=0.8169
model=transformerconv top_k=50 fold=6 epoch=33 loss=3.0564 val_auc=0.8177
model=transformerconv top_k=50 fold=6 epoch=34 loss=2.5319 val_auc=0.8183
model=transformerconv top_k=50 fold=6 epoch=35 loss=2.5361 val_auc=0.8185
model=transformerconv top_k=50 fold=6 epoch=36 loss=2.4220 val_auc=0.8192
model=transformerconv top_k=50 fold=6 epoch=37 loss=2.6225 val_auc=0.8200
model=transformerconv top_k=50 fold=6 epoch=38 loss=2.2261 val_auc=0.8203
model=transformerconv top_k=50 fold=6 epoch=39 loss=1.9909 val_auc=0.8205
model=transformerconv top_k=50 fold=6 epoch=40 loss=2.2843 val_auc=0.8208
model=transformerconv top_k=50 fold=6 epoch=41 loss=2.1982 val_auc=0.8212
model=transformerconv top_k=50 fold=6 epoch=42 loss=1.9325 val_auc=0.8220
model=transformerconv top_k=50 fold=6 epoch=43 loss=2.1678 val_auc=0.8223
model=transformerconv top_k=50 fold=6 epoch=44 loss=2.8691 val_auc=0.8228
model=transformerconv top_k=50 fold=6 epoch=45 loss=2.1509 val_auc=0.8232
model=transformerconv top_k=50 fold=6 epoch=46 loss=2.1417 val_auc=0.8231
model=transformerconv top_k=50 fold=6 epoch=47 loss=1.8345 val_auc=0.8233
model=transformerconv top_k=50 fold=6 epoch=48 loss=2.1543 val_auc=0.8238
model=transformerconv top_k=50 fold=6 epoch=49 loss=1.8963 val_auc=0.8242
model=transformerconv top_k=50 fold=6 epoch=50 loss=1.7099 val_auc=0.8247
model=transformerconv top_k=50 fold=6 epoch=51 loss=1.7433 val_auc=0.8252
model=transformerconv top_k=50 fold=6 epoch=52 loss=1.5980 val_auc=0.8260
model=transformerconv top_k=50 fold=6 epoch=53 loss=1.5861 val_auc=0.8270
model=transformerconv top_k=50 fold=6 epoch=54 loss=1.9309 val_auc=0.8266
model=transformerconv top_k=50 fold=6 epoch=55 loss=1.8509 val_auc=0.8265
model=transformerconv top_k=50 fold=6 epoch=56 loss=2.1442 val_auc=0.8256
model=transformerconv top_k=50 fold=6 epoch=57 loss=1.7713 val_auc=0.8245
model=transformerconv top_k=50 fold=6 epoch=58 loss=1.6807 val_auc=0.8243
model=transformerconv top_k=50 fold=6 epoch=59 loss=2.0628 val_auc=0.8242
model=transformerconv top_k=50 fold=6 epoch=60 loss=1.9149 val_auc=0.8250
model=transformerconv top_k=50 fold=6 epoch=61 loss=1.7353 val_auc=0.8252
model=transformerconv top_k=50 fold=6 epoch=62 loss=1.6925 val_auc=0.8252
model=transformerconv top_k=50 fold=6 epoch=63 loss=1.6911 val_auc=0.8254
model=transformerconv top_k=50 fold=6 epoch=64 loss=1.4655 val_auc=0.8256
model=transformerconv top_k=50 fold=6 epoch=65 loss=1.3761 val_auc=0.8268
transformerconv top_k=50 fold=6: early stopping at epoch 65
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718481 edges

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=50 fold=7 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719141 edges
model=transformerconv top_k=50 fold=7 epoch=0 loss=6.9675 val_auc=0.6845
model=transformerconv top_k=50 fold=7 epoch=1 loss=23.1680 val_auc=0.7218
model=transformerconv top_k=50 fold=7 epoch=2 loss=15.9671 val_auc=0.7422
model=transformerconv top_k=50 fold=7 epoch=3 loss=4.5912 val_auc=0.7534
model=transformerconv top_k=50 fold=7 epoch=4 loss=5.2459 val_auc=0.7581
model=transformerconv top_k=50 fold=7 epoch=5 loss=4.7105 val_auc=0.7660
model=transformerconv top_k=50 fold=7 epoch=6 loss=4.3447 val_auc=0.7715
model=transformerconv top_k=50 fold=7 epoch=7 loss=4.3756 val_auc=0.7741
model=transformerconv top_k=50 fold=7 epoch=8 loss=3.8165 val_auc=0.7768
model=transformerconv top_k=50 fold=7 epoch=9 loss=4.0286 val_auc=0.7800
model=transformerconv top_k=50 fold=7 epoch=10 loss=3.4441 val_auc=0.7840
model=transformerconv top_k=50 fold=7 epoch=11 loss=3.8130 val_auc=0.7884
model=transformerconv top_k=50 fold=7 epoch=12 loss=3.3252 val_auc=0.7924
model=transformerconv top_k=50 fold=7 epoch=13 loss=4.3996 val_auc=0.7947
model=transformerconv top_k=50 fold=7 epoch=14 loss=5.6130 val_auc=0.7962
model=transformerconv top_k=50 fold=7 epoch=15 loss=3.0202 val_auc=0.7973
model=transformerconv top_k=50 fold=7 epoch=16 loss=2.8472 val_auc=0.7986
model=transformerconv top_k=50 fold=7 epoch=17 loss=3.3145 val_auc=0.8005
model=transformerconv top_k=50 fold=7 epoch=18 loss=2.8985 val_auc=0.8025
model=transformerconv top_k=50 fold=7 epoch=19 loss=2.6623 val_auc=0.8046
model=transformerconv top_k=50 fold=7 epoch=20 loss=2.6070 val_auc=0.8062
model=transformerconv top_k=50 fold=7 epoch=21 loss=2.9251 val_auc=0.8073
model=transformerconv top_k=50 fold=7 epoch=22 loss=3.1277 val_auc=0.8084
model=transformerconv top_k=50 fold=7 epoch=23 loss=3.1369 val_auc=0.8098
model=transformerconv top_k=50 fold=7 epoch=24 loss=2.3149 val_auc=0.8106
model=transformerconv top_k=50 fold=7 epoch=25 loss=2.0750 val_auc=0.8109
model=transformerconv top_k=50 fold=7 epoch=26 loss=2.6025 val_auc=0.8112
model=transformerconv top_k=50 fold=7 epoch=27 loss=3.6655 val_auc=0.8115
model=transformerconv top_k=50 fold=7 epoch=28 loss=2.2845 val_auc=0.8116
model=transformerconv top_k=50 fold=7 epoch=29 loss=2.3440 val_auc=0.8116
model=transformerconv top_k=50 fold=7 epoch=30 loss=2.5239 val_auc=0.8118
model=transformerconv top_k=50 fold=7 epoch=31 loss=2.4625 val_auc=0.8124
model=transformerconv top_k=50 fold=7 epoch=32 loss=2.2911 val_auc=0.8131
model=transformerconv top_k=50 fold=7 epoch=33 loss=2.5537 val_auc=0.8138
model=transformerconv top_k=50 fold=7 epoch=34 loss=3.0805 val_auc=0.8145
model=transformerconv top_k=50 fold=7 epoch=35 loss=2.3923 val_auc=0.8149
model=transformerconv top_k=50 fold=7 epoch=36 loss=2.1915 val_auc=0.8150
model=transformerconv top_k=50 fold=7 epoch=37 loss=2.3492 val_auc=0.8150
model=transformerconv top_k=50 fold=7 epoch=38 loss=2.9714 val_auc=0.8152
model=transformerconv top_k=50 fold=7 epoch=39 loss=2.7258 val_auc=0.8156
model=transformerconv top_k=50 fold=7 epoch=40 loss=2.1978 val_auc=0.8162
model=transformerconv top_k=50 fold=7 epoch=41 loss=2.0537 val_auc=0.8167
model=transformerconv top_k=50 fold=7 epoch=42 loss=2.1050 val_auc=0.8170
model=transformerconv top_k=50 fold=7 epoch=43 loss=2.5731 val_auc=0.8169
model=transformerconv top_k=50 fold=7 epoch=44 loss=2.1542 val_auc=0.8166
model=transformerconv top_k=50 fold=7 epoch=45 loss=1.7857 val_auc=0.8166
model=transformerconv top_k=50 fold=7 epoch=46 loss=1.8959 val_auc=0.8171
model=transformerconv top_k=50 fold=7 epoch=47 loss=1.6413 val_auc=0.8176
model=transformerconv top_k=50 fold=7 epoch=48 loss=1.6836 val_auc=0.8181
model=transformerconv top_k=50 fold=7 epoch=49 loss=1.8078 val_auc=0.8187
model=transformerconv top_k=50 fold=7 epoch=50 loss=1.6437 val_auc=0.8191
model=transformerconv top_k=50 fold=7 epoch=51 loss=1.6201 val_auc=0.8195
model=transformerconv top_k=50 fold=7 epoch=52 loss=1.7679 val_auc=0.8189
model=transformerconv top_k=50 fold=7 epoch=53 loss=1.5313 val_auc=0.8187
model=transformerconv top_k=50 fold=7 epoch=54 loss=1.8912 val_auc=0.8179
model=transformerconv top_k=50 fold=7 epoch=55 loss=1.4844 val_auc=0.8173
model=transformerconv top_k=50 fold=7 epoch=56 loss=1.5822 val_auc=0.8168
model=transformerconv top_k=50 fold=7 epoch=57 loss=1.7937 val_auc=0.8170
model=transformerconv top_k=50 fold=7 epoch=58 loss=2.0507 val_auc=0.8175
model=transformerconv top_k=50 fold=7 epoch=59 loss=1.8215 val_auc=0.8180
model=transformerconv top_k=50 fold=7 epoch=60 loss=1.4269 val_auc=0.8188
model=transformerconv top_k=50 fold=7 epoch=61 loss=1.9815 val_auc=0.8197
model=transformerconv top_k=50 fold=7 epoch=62 loss=2.4767 val_auc=0.8207
model=transformerconv top_k=50 fold=7 epoch=63 loss=2.7538 val_auc=0.8215
model=transformerconv top_k=50 fold=7 epoch=64 loss=1.6117 val_auc=0.8220
model=transformerconv top_k=50 fold=7 epoch=65 loss=1.2744 val_auc=0.8225
model=transformerconv top_k=50 fold=7 epoch=66 loss=1.5340 val_auc=0.8228
model=transformerconv top_k=50 fold=7 epoch=67 loss=1.4861 val_auc=0.8231
model=transformerconv top_k=50 fold=7 epoch=68 loss=1.3120 val_auc=0.8236
model=transformerconv top_k=50 fold=7 epoch=69 loss=1.5469 val_auc=0.8239
model=transformerconv top_k=50 fold=7 epoch=70 loss=1.8264 val_auc=0.8240
model=transformerconv top_k=50 fold=7 epoch=71 loss=1.8492 val_auc=0.8238
model=transformerconv top_k=50 fold=7 epoch=72 loss=1.3530 val_auc=0.8235
model=transformerconv top_k=50 fold=7 epoch=73 loss=1.2999 val_auc=0.8237
model=transformerconv top_k=50 fold=7 epoch=74 loss=1.2946 val_auc=0.8242
model=transformerconv top_k=50 fold=7 epoch=75 loss=1.4597 val_auc=0.8247
model=transformerconv top_k=50 fold=7 epoch=76 loss=1.2670 val_auc=0.8252
model=transformerconv top_k=50 fold=7 epoch=77 loss=1.2507 val_auc=0.8256
model=transformerconv top_k=50 fold=7 epoch=78 loss=1.2980 val_auc=0.8259
model=transformerconv top_k=50 fold=7 epoch=79 loss=1.3543 val_auc=0.8257
model=transformerconv top_k=50 fold=7 epoch=80 loss=1.2907 val_auc=0.8253
model=transformerconv top_k=50 fold=7 epoch=81 loss=1.3441 val_auc=0.8250
model=transformerconv top_k=50 fold=7 epoch=82 loss=1.2186 val_auc=0.8253
model=transformerconv top_k=50 fold=7 epoch=83 loss=1.3358 val_auc=0.8256
model=transformerconv top_k=50 fold=7 epoch=84 loss=1.2980 val_auc=0.8258
model=transformerconv top_k=50 fold=7 epoch=85 loss=1.2728 val_auc=0.8261
model=transformerconv top_k=50 fold=7 epoch=86 loss=1.3255 val_auc=0.8262
model=transformerconv top_k=50 fold=7 epoch=87 loss=1.4896 val_auc=0.8265
model=transformerconv top_k=50 fold=7 epoch=88 loss=1.5601 val_auc=0.8268
model=transformerconv top_k=50 fold=7 epoch=89 loss=1.3066 val_auc=0.8274
model=transformerconv top_k=50 fold=7 epoch=90 loss=1.2302 val_auc=0.8280
model=transformerconv top_k=50 fold=7 epoch=91 loss=1.2087 val_auc=0.8284
model=transformerconv top_k=50 fold=7 epoch=92 loss=1.1722 val_auc=0.8286
model=transformerconv top_k=50 fold=7 epoch=93 loss=1.1786 val_auc=0.8291
model=transformerconv top_k=50 fold=7 epoch=94 loss=1.1991 val_auc=0.8299
model=transformerconv top_k=50 fold=7 epoch=95 loss=1.0775 val_auc=0.8305
model=transformerconv top_k=50 fold=7 epoch=96 loss=1.1917 val_auc=0.8311
model=transformerconv top_k=50 fold=7 epoch=97 loss=1.3281 val_auc=0.8314
model=transformerconv top_k=50 fold=7 epoch=98 loss=1.1472 val_auc=0.8314
model=transformerconv top_k=50 fold=7 epoch=99 loss=1.1776 val_auc=0.8308
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719141 edges

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=50 fold=8 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718578 edges
model=transformerconv top_k=50 fold=8 epoch=0 loss=13.2483 val_auc=0.5165
model=transformerconv top_k=50 fold=8 epoch=1 loss=21.7185 val_auc=0.5641
model=transformerconv top_k=50 fold=8 epoch=2 loss=15.1138 val_auc=0.6528
model=transformerconv top_k=50 fold=8 epoch=3 loss=5.5949 val_auc=0.6778
model=transformerconv top_k=50 fold=8 epoch=4 loss=6.9975 val_auc=0.6950
model=transformerconv top_k=50 fold=8 epoch=5 loss=8.4732 val_auc=0.7139
model=transformerconv top_k=50 fold=8 epoch=6 loss=6.4970 val_auc=0.7271
model=transformerconv top_k=50 fold=8 epoch=7 loss=4.3724 val_auc=0.7309
model=transformerconv top_k=50 fold=8 epoch=8 loss=4.5928 val_auc=0.7438
model=transformerconv top_k=50 fold=8 epoch=9 loss=6.9371 val_auc=0.7553
model=transformerconv top_k=50 fold=8 epoch=10 loss=5.4782 val_auc=0.7626
model=transformerconv top_k=50 fold=8 epoch=11 loss=3.6801 val_auc=0.7671
model=transformerconv top_k=50 fold=8 epoch=12 loss=3.9826 val_auc=0.7690
model=transformerconv top_k=50 fold=8 epoch=13 loss=3.7444 val_auc=0.7703
model=transformerconv top_k=50 fold=8 epoch=14 loss=4.2718 val_auc=0.7718
model=transformerconv top_k=50 fold=8 epoch=15 loss=3.5010 val_auc=0.7749
model=transformerconv top_k=50 fold=8 epoch=16 loss=3.5738 val_auc=0.7781
model=transformerconv top_k=50 fold=8 epoch=17 loss=3.9950 val_auc=0.7815
model=transformerconv top_k=50 fold=8 epoch=18 loss=2.9250 val_auc=0.7844
model=transformerconv top_k=50 fold=8 epoch=19 loss=3.4757 val_auc=0.7863
model=transformerconv top_k=50 fold=8 epoch=20 loss=3.4410 val_auc=0.7869
model=transformerconv top_k=50 fold=8 epoch=21 loss=3.2373 val_auc=0.7877
model=transformerconv top_k=50 fold=8 epoch=22 loss=2.9859 val_auc=0.7886
model=transformerconv top_k=50 fold=8 epoch=23 loss=2.9558 val_auc=0.7892
model=transformerconv top_k=50 fold=8 epoch=24 loss=3.4570 val_auc=0.7900
model=transformerconv top_k=50 fold=8 epoch=25 loss=2.6042 val_auc=0.7904
model=transformerconv top_k=50 fold=8 epoch=26 loss=2.8129 val_auc=0.7920
model=transformerconv top_k=50 fold=8 epoch=27 loss=2.8154 val_auc=0.7933
model=transformerconv top_k=50 fold=8 epoch=28 loss=2.9704 val_auc=0.7949
model=transformerconv top_k=50 fold=8 epoch=29 loss=2.6685 val_auc=0.7959
model=transformerconv top_k=50 fold=8 epoch=30 loss=2.4954 val_auc=0.7978
model=transformerconv top_k=50 fold=8 epoch=31 loss=2.6756 val_auc=0.7999
model=transformerconv top_k=50 fold=8 epoch=32 loss=2.4243 val_auc=0.8017
model=transformerconv top_k=50 fold=8 epoch=33 loss=2.2903 val_auc=0.8033
model=transformerconv top_k=50 fold=8 epoch=34 loss=2.4121 val_auc=0.8049
model=transformerconv top_k=50 fold=8 epoch=35 loss=2.0977 val_auc=0.8062
model=transformerconv top_k=50 fold=8 epoch=36 loss=2.2987 val_auc=0.8071
model=transformerconv top_k=50 fold=8 epoch=37 loss=1.9669 val_auc=0.8080
model=transformerconv top_k=50 fold=8 epoch=38 loss=2.0725 val_auc=0.8089
model=transformerconv top_k=50 fold=8 epoch=39 loss=1.8320 val_auc=0.8099
model=transformerconv top_k=50 fold=8 epoch=40 loss=2.1501 val_auc=0.8105
model=transformerconv top_k=50 fold=8 epoch=41 loss=1.8646 val_auc=0.8109
model=transformerconv top_k=50 fold=8 epoch=42 loss=2.4621 val_auc=0.8113
model=transformerconv top_k=50 fold=8 epoch=43 loss=1.8477 val_auc=0.8117
model=transformerconv top_k=50 fold=8 epoch=44 loss=2.0297 val_auc=0.8118
model=transformerconv top_k=50 fold=8 epoch=45 loss=1.9299 val_auc=0.8122
model=transformerconv top_k=50 fold=8 epoch=46 loss=2.0109 val_auc=0.8127
model=transformerconv top_k=50 fold=8 epoch=47 loss=2.0258 val_auc=0.8130
model=transformerconv top_k=50 fold=8 epoch=48 loss=1.9521 val_auc=0.8128
model=transformerconv top_k=50 fold=8 epoch=49 loss=1.9064 val_auc=0.8128
model=transformerconv top_k=50 fold=8 epoch=50 loss=1.6145 val_auc=0.8131
model=transformerconv top_k=50 fold=8 epoch=51 loss=1.9110 val_auc=0.8132
model=transformerconv top_k=50 fold=8 epoch=52 loss=1.6678 val_auc=0.8129
model=transformerconv top_k=50 fold=8 epoch=53 loss=1.6947 val_auc=0.8131
model=transformerconv top_k=50 fold=8 epoch=54 loss=1.9710 val_auc=0.8136
model=transformerconv top_k=50 fold=8 epoch=55 loss=1.7585 val_auc=0.8138
model=transformerconv top_k=50 fold=8 epoch=56 loss=1.6610 val_auc=0.8147
model=transformerconv top_k=50 fold=8 epoch=57 loss=1.4536 val_auc=0.8157
model=transformerconv top_k=50 fold=8 epoch=58 loss=1.4902 val_auc=0.8166
model=transformerconv top_k=50 fold=8 epoch=59 loss=1.5434 val_auc=0.8171
model=transformerconv top_k=50 fold=8 epoch=60 loss=1.4232 val_auc=0.8178
model=transformerconv top_k=50 fold=8 epoch=61 loss=1.4805 val_auc=0.8185
model=transformerconv top_k=50 fold=8 epoch=62 loss=1.6589 val_auc=0.8193
model=transformerconv top_k=50 fold=8 epoch=63 loss=1.5879 val_auc=0.8197
model=transformerconv top_k=50 fold=8 epoch=64 loss=1.5281 val_auc=0.8199
model=transformerconv top_k=50 fold=8 epoch=65 loss=1.5977 val_auc=0.8195
model=transformerconv top_k=50 fold=8 epoch=66 loss=1.3869 val_auc=0.8195
model=transformerconv top_k=50 fold=8 epoch=67 loss=1.4603 val_auc=0.8194
model=transformerconv top_k=50 fold=8 epoch=68 loss=1.3439 val_auc=0.8192
model=transformerconv top_k=50 fold=8 epoch=69 loss=1.4447 val_auc=0.8189
model=transformerconv top_k=50 fold=8 epoch=70 loss=1.4592 val_auc=0.8178
model=transformerconv top_k=50 fold=8 epoch=71 loss=1.4202 val_auc=0.8171
model=transformerconv top_k=50 fold=8 epoch=72 loss=1.4905 val_auc=0.8176
model=transformerconv top_k=50 fold=8 epoch=73 loss=1.4623 val_auc=0.8182
model=transformerconv top_k=50 fold=8 epoch=74 loss=1.2279 val_auc=0.8189
model=transformerconv top_k=50 fold=8 epoch=75 loss=1.3735 val_auc=0.8194
model=transformerconv top_k=50 fold=8 epoch=76 loss=1.2925 val_auc=0.8198
transformerconv top_k=50 fold=8: early stopping at epoch 76
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718578 edges

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=50 fold=9 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718994 edges
model=transformerconv top_k=50 fold=9 epoch=0 loss=9.1180 val_auc=0.5238
model=transformerconv top_k=50 fold=9 epoch=1 loss=24.3484 val_auc=0.5884
model=transformerconv top_k=50 fold=9 epoch=2 loss=17.8607 val_auc=0.6701
model=transformerconv top_k=50 fold=9 epoch=3 loss=8.0209 val_auc=0.6941
model=transformerconv top_k=50 fold=9 epoch=4 loss=7.9917 val_auc=0.7220
model=transformerconv top_k=50 fold=9 epoch=5 loss=9.7317 val_auc=0.7414
model=transformerconv top_k=50 fold=9 epoch=6 loss=6.6917 val_auc=0.7485
model=transformerconv top_k=50 fold=9 epoch=7 loss=4.9934 val_auc=0.7576
model=transformerconv top_k=50 fold=9 epoch=8 loss=4.9375 val_auc=0.7655
model=transformerconv top_k=50 fold=9 epoch=9 loss=5.4782 val_auc=0.7716
model=transformerconv top_k=50 fold=9 epoch=10 loss=4.0682 val_auc=0.7753
model=transformerconv top_k=50 fold=9 epoch=11 loss=5.7236 val_auc=0.7779
model=transformerconv top_k=50 fold=9 epoch=12 loss=4.4985 val_auc=0.7808
model=transformerconv top_k=50 fold=9 epoch=13 loss=5.4463 val_auc=0.7835
model=transformerconv top_k=50 fold=9 epoch=14 loss=4.2880 val_auc=0.7859
model=transformerconv top_k=50 fold=9 epoch=15 loss=5.1677 val_auc=0.7872
model=transformerconv top_k=50 fold=9 epoch=16 loss=5.4003 val_auc=0.7879
model=transformerconv top_k=50 fold=9 epoch=17 loss=4.5933 val_auc=0.7882
model=transformerconv top_k=50 fold=9 epoch=18 loss=3.3926 val_auc=0.7894
model=transformerconv top_k=50 fold=9 epoch=19 loss=3.9076 val_auc=0.7902
model=transformerconv top_k=50 fold=9 epoch=20 loss=3.6877 val_auc=0.7914
model=transformerconv top_k=50 fold=9 epoch=21 loss=3.7498 val_auc=0.7926
model=transformerconv top_k=50 fold=9 epoch=22 loss=4.2210 val_auc=0.7938
model=transformerconv top_k=50 fold=9 epoch=23 loss=3.0935 val_auc=0.7949
model=transformerconv top_k=50 fold=9 epoch=24 loss=3.9207 val_auc=0.7955
model=transformerconv top_k=50 fold=9 epoch=25 loss=3.6433 val_auc=0.7964
model=transformerconv top_k=50 fold=9 epoch=26 loss=3.0086 val_auc=0.7975
model=transformerconv top_k=50 fold=9 epoch=27 loss=3.5578 val_auc=0.7983
model=transformerconv top_k=50 fold=9 epoch=28 loss=2.9901 val_auc=0.7999
model=transformerconv top_k=50 fold=9 epoch=29 loss=2.6338 val_auc=0.8012
model=transformerconv top_k=50 fold=9 epoch=30 loss=2.6773 val_auc=0.8032
model=transformerconv top_k=50 fold=9 epoch=31 loss=2.5752 val_auc=0.8048
model=transformerconv top_k=50 fold=9 epoch=32 loss=3.3334 val_auc=0.8064
model=transformerconv top_k=50 fold=9 epoch=33 loss=2.9679 val_auc=0.8072
model=transformerconv top_k=50 fold=9 epoch=34 loss=2.6809 val_auc=0.8086
model=transformerconv top_k=50 fold=9 epoch=35 loss=2.4188 val_auc=0.8102
model=transformerconv top_k=50 fold=9 epoch=36 loss=2.3610 val_auc=0.8120
model=transformerconv top_k=50 fold=9 epoch=37 loss=2.6114 val_auc=0.8137
model=transformerconv top_k=50 fold=9 epoch=38 loss=2.5343 val_auc=0.8151
model=transformerconv top_k=50 fold=9 epoch=39 loss=2.5548 val_auc=0.8159
model=transformerconv top_k=50 fold=9 epoch=40 loss=2.3481 val_auc=0.8164
model=transformerconv top_k=50 fold=9 epoch=41 loss=2.4728 val_auc=0.8169
model=transformerconv top_k=50 fold=9 epoch=42 loss=1.9204 val_auc=0.8176
model=transformerconv top_k=50 fold=9 epoch=43 loss=2.2055 val_auc=0.8179
model=transformerconv top_k=50 fold=9 epoch=44 loss=1.9725 val_auc=0.8184
model=transformerconv top_k=50 fold=9 epoch=45 loss=2.0565 val_auc=0.8189
model=transformerconv top_k=50 fold=9 epoch=46 loss=1.8719 val_auc=0.8191
model=transformerconv top_k=50 fold=9 epoch=47 loss=2.0122 val_auc=0.8193
model=transformerconv top_k=50 fold=9 epoch=48 loss=2.4871 val_auc=0.8197
model=transformerconv top_k=50 fold=9 epoch=49 loss=1.7386 val_auc=0.8204
model=transformerconv top_k=50 fold=9 epoch=50 loss=2.2139 val_auc=0.8209
model=transformerconv top_k=50 fold=9 epoch=51 loss=1.8499 val_auc=0.8213
model=transformerconv top_k=50 fold=9 epoch=52 loss=1.7339 val_auc=0.8214
model=transformerconv top_k=50 fold=9 epoch=53 loss=1.6825 val_auc=0.8216
model=transformerconv top_k=50 fold=9 epoch=54 loss=1.9937 val_auc=0.8219
model=transformerconv top_k=50 fold=9 epoch=55 loss=1.6624 val_auc=0.8223
model=transformerconv top_k=50 fold=9 epoch=56 loss=1.7479 val_auc=0.8228
model=transformerconv top_k=50 fold=9 epoch=57 loss=1.7280 val_auc=0.8229
model=transformerconv top_k=50 fold=9 epoch=58 loss=1.4252 val_auc=0.8229
model=transformerconv top_k=50 fold=9 epoch=59 loss=1.6084 val_auc=0.8233
model=transformerconv top_k=50 fold=9 epoch=60 loss=1.6829 val_auc=0.8239
model=transformerconv top_k=50 fold=9 epoch=61 loss=1.5328 val_auc=0.8242
model=transformerconv top_k=50 fold=9 epoch=62 loss=1.3521 val_auc=0.8245
model=transformerconv top_k=50 fold=9 epoch=63 loss=1.3598 val_auc=0.8248
model=transformerconv top_k=50 fold=9 epoch=64 loss=1.6220 val_auc=0.8252
model=transformerconv top_k=50 fold=9 epoch=65 loss=1.9117 val_auc=0.8257
model=transformerconv top_k=50 fold=9 epoch=66 loss=1.4010 val_auc=0.8260
model=transformerconv top_k=50 fold=9 epoch=67 loss=1.4525 val_auc=0.8262
model=transformerconv top_k=50 fold=9 epoch=68 loss=1.5906 val_auc=0.8262
model=transformerconv top_k=50 fold=9 epoch=69 loss=1.3190 val_auc=0.8263
model=transformerconv top_k=50 fold=9 epoch=70 loss=1.4469 val_auc=0.8263
model=transformerconv top_k=50 fold=9 epoch=71 loss=1.3011 val_auc=0.8263
model=transformerconv top_k=50 fold=9 epoch=72 loss=1.3740 val_auc=0.8268
model=transformerconv top_k=50 fold=9 epoch=73 loss=1.4818 val_auc=0.8272
model=transformerconv top_k=50 fold=9 epoch=74 loss=1.2730 val_auc=0.8277
model=transformerconv top_k=50 fold=9 epoch=75 loss=1.1528 val_auc=0.8288
model=transformerconv top_k=50 fold=9 epoch=76 loss=1.2948 val_auc=0.8298
model=transformerconv top_k=50 fold=9 epoch=77 loss=1.4358 val_auc=0.8306
model=transformerconv top_k=50 fold=9 epoch=78 loss=1.4889 val_auc=0.8315
model=transformerconv top_k=50 fold=9 epoch=79 loss=1.2839 val_auc=0.8321
model=transformerconv top_k=50 fold=9 epoch=80 loss=1.4614 val_auc=0.8324
model=transformerconv top_k=50 fold=9 epoch=81 loss=1.7830 val_auc=0.8323
model=transformerconv top_k=50 fold=9 epoch=82 loss=1.6494 val_auc=0.8320
model=transformerconv top_k=50 fold=9 epoch=83 loss=1.4382 val_auc=0.8315
model=transformerconv top_k=50 fold=9 epoch=84 loss=1.0823 val_auc=0.8311
model=transformerconv top_k=50 fold=9 epoch=85 loss=1.7621 val_auc=0.8308
model=transformerconv top_k=50 fold=9 epoch=86 loss=2.0475 val_auc=0.8304
model=transformerconv top_k=50 fold=9 epoch=87 loss=2.2065 val_auc=0.8298
model=transformerconv top_k=50 fold=9 epoch=88 loss=1.5885 val_auc=0.8289
model=transformerconv top_k=50 fold=9 epoch=89 loss=1.3913 val_auc=0.8281
model=transformerconv top_k=50 fold=9 epoch=90 loss=1.1777 val_auc=0.8276
model=transformerconv top_k=50 fold=9 epoch=91 loss=1.7310 val_auc=0.8271
model=transformerconv top_k=50 fold=9 epoch=92 loss=1.7206 val_auc=0.8268
transformerconv top_k=50 fold=9: early stopping at epoch 92
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718994 edges

query FAISS top_k=50:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=50:   0%|          | 0/35 [00:00<?, ?it/s]

######## Model=transformerconv top_k=100 ########

===== Model=transformerconv top_k=100 fold=0 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718731 edges
model=transformerconv top_k=100 fold=0 epoch=0 loss=7.5160 val_auc=0.5007
model=transformerconv top_k=100 fold=0 epoch=1 loss=22.7235 val_auc=0.5121
model=transformerconv top_k=100 fold=0 epoch=2 loss=21.0532 val_auc=0.7545
model=transformerconv top_k=100 fold=0 epoch=3 loss=6.7452 val_auc=0.7627
model=transformerconv top_k=100 fold=0 epoch=4 loss=7.2357 val_auc=0.7638
model=transformerconv top_k=100 fold=0 epoch=5 loss=9.9344 val_auc=0.7651
model=transformerconv top_k=100 fold=0 epoch=6 loss=6.1998 val_auc=0.7694
model=transformerconv top_k=100 fold=0 epoch=7 loss=4.5212 val_auc=0.7727
model=transformerconv top_k=100 fold=0 epoch=8 loss=5.7654 val_auc=0.7759
model=transformerconv top_k=100 fold=0 epoch=9 loss=6.9680 val_auc=0.7781
model=transformerconv top_k=100 fold=0 epoch=10 loss=5.4732 val_auc=0.7798
model=transformerconv top_k=100 fold=0 epoch=11 loss=5.1252 val_auc=0.7811
model=transformerconv top_k=100 fold=0 epoch=12 loss=4.1960 val_auc=0.7832
model=transformerconv top_k=100 fold=0 epoch=13 loss=4.8838 val_auc=0.7845
model=transformerconv top_k=100 fold=0 epoch=14 loss=5.3043 val_auc=0.7858
model=transformerconv top_k=100 fold=0 epoch=15 loss=6.0438 val_auc=0.7865
model=transformerconv top_k=100 fold=0 epoch=16 loss=4.7590 val_auc=0.7870
model=transformerconv top_k=100 fold=0 epoch=17 loss=3.9155 val_auc=0.7885
model=transformerconv top_k=100 fold=0 epoch=18 loss=4.2456 val_auc=0.7900
model=transformerconv top_k=100 fold=0 epoch=19 loss=4.2658 val_auc=0.7917
model=transformerconv top_k=100 fold=0 epoch=20 loss=3.7129 val_auc=0.7931
model=transformerconv top_k=100 fold=0 epoch=21 loss=4.0400 val_auc=0.7946
model=transformerconv top_k=100 fold=0 epoch=22 loss=4.4077 val_auc=0.7957
model=transformerconv top_k=100 fold=0 epoch=23 loss=5.4938 val_auc=0.7967
model=transformerconv top_k=100 fold=0 epoch=24 loss=4.8021 val_auc=0.7975
model=transformerconv top_k=100 fold=0 epoch=25 loss=4.1147 val_auc=0.7984
model=transformerconv top_k=100 fold=0 epoch=26 loss=3.1299 val_auc=0.7988
model=transformerconv top_k=100 fold=0 epoch=27 loss=3.8559 val_auc=0.7996
model=transformerconv top_k=100 fold=0 epoch=28 loss=4.7057 val_auc=0.8004
model=transformerconv top_k=100 fold=0 epoch=29 loss=4.2223 val_auc=0.8012
model=transformerconv top_k=100 fold=0 epoch=30 loss=4.0901 val_auc=0.8018
model=transformerconv top_k=100 fold=0 epoch=31 loss=2.8024 val_auc=0.8024
model=transformerconv top_k=100 fold=0 epoch=32 loss=3.2898 val_auc=0.8031
model=transformerconv top_k=100 fold=0 epoch=33 loss=3.8038 val_auc=0.8037
model=transformerconv top_k=100 fold=0 epoch=34 loss=4.1661 val_auc=0.8045
model=transformerconv top_k=100 fold=0 epoch=35 loss=3.9886 val_auc=0.8052
model=transformerconv top_k=100 fold=0 epoch=36 loss=3.4869 val_auc=0.8059
model=transformerconv top_k=100 fold=0 epoch=37 loss=2.7135 val_auc=0.8067
model=transformerconv top_k=100 fold=0 epoch=38 loss=2.7833 val_auc=0.8076
model=transformerconv top_k=100 fold=0 epoch=39 loss=2.8484 val_auc=0.8083
model=transformerconv top_k=100 fold=0 epoch=40 loss=3.1860 val_auc=0.8088
model=transformerconv top_k=100 fold=0 epoch=41 loss=3.1985 val_auc=0.8092
model=transformerconv top_k=100 fold=0 epoch=42 loss=2.4063 val_auc=0.8097
model=transformerconv top_k=100 fold=0 epoch=43 loss=2.8546 val_auc=0.8097
model=transformerconv top_k=100 fold=0 epoch=44 loss=2.6830 val_auc=0.8099
model=transformerconv top_k=100 fold=0 epoch=45 loss=2.4373 val_auc=0.8100
model=transformerconv top_k=100 fold=0 epoch=46 loss=2.8390 val_auc=0.8102
model=transformerconv top_k=100 fold=0 epoch=47 loss=2.6048 val_auc=0.8105
model=transformerconv top_k=100 fold=0 epoch=48 loss=3.5271 val_auc=0.8107
model=transformerconv top_k=100 fold=0 epoch=49 loss=2.8684 val_auc=0.8106
model=transformerconv top_k=100 fold=0 epoch=50 loss=2.7662 val_auc=0.8104
model=transformerconv top_k=100 fold=0 epoch=51 loss=2.2504 val_auc=0.8105
model=transformerconv top_k=100 fold=0 epoch=52 loss=2.8366 val_auc=0.8105
model=transformerconv top_k=100 fold=0 epoch=53 loss=2.2434 val_auc=0.8107
model=transformerconv top_k=100 fold=0 epoch=54 loss=2.7010 val_auc=0.8110
model=transformerconv top_k=100 fold=0 epoch=55 loss=2.3502 val_auc=0.8112
model=transformerconv top_k=100 fold=0 epoch=56 loss=2.0567 val_auc=0.8113
model=transformerconv top_k=100 fold=0 epoch=57 loss=2.9397 val_auc=0.8116
model=transformerconv top_k=100 fold=0 epoch=58 loss=2.6429 val_auc=0.8120
model=transformerconv top_k=100 fold=0 epoch=59 loss=3.1750 val_auc=0.8123
model=transformerconv top_k=100 fold=0 epoch=60 loss=2.7735 val_auc=0.8126
model=transformerconv top_k=100 fold=0 epoch=61 loss=2.1868 val_auc=0.8130
model=transformerconv top_k=100 fold=0 epoch=62 loss=1.9750 val_auc=0.8138
model=transformerconv top_k=100 fold=0 epoch=63 loss=2.3961 val_auc=0.8142
model=transformerconv top_k=100 fold=0 epoch=64 loss=2.8368 val_auc=0.8138
model=transformerconv top_k=100 fold=0 epoch=65 loss=2.5287 val_auc=0.8135
model=transformerconv top_k=100 fold=0 epoch=66 loss=2.8033 val_auc=0.8140
model=transformerconv top_k=100 fold=0 epoch=67 loss=2.1091 val_auc=0.8146
model=transformerconv top_k=100 fold=0 epoch=68 loss=2.2709 val_auc=0.8149
model=transformerconv top_k=100 fold=0 epoch=69 loss=2.3108 val_auc=0.8152
model=transformerconv top_k=100 fold=0 epoch=70 loss=1.9801 val_auc=0.8154
model=transformerconv top_k=100 fold=0 epoch=71 loss=1.9869 val_auc=0.8156
model=transformerconv top_k=100 fold=0 epoch=72 loss=1.7381 val_auc=0.8161
model=transformerconv top_k=100 fold=0 epoch=73 loss=1.7088 val_auc=0.8169
model=transformerconv top_k=100 fold=0 epoch=74 loss=2.0289 val_auc=0.8179
model=transformerconv top_k=100 fold=0 epoch=75 loss=1.7752 val_auc=0.8190
model=transformerconv top_k=100 fold=0 epoch=76 loss=1.4765 val_auc=0.8199
model=transformerconv top_k=100 fold=0 epoch=77 loss=1.6757 val_auc=0.8206
model=transformerconv top_k=100 fold=0 epoch=78 loss=1.7971 val_auc=0.8212
model=transformerconv top_k=100 fold=0 epoch=79 loss=1.6277 val_auc=0.8217
model=transformerconv top_k=100 fold=0 epoch=80 loss=1.7435 val_auc=0.8221
model=transformerconv top_k=100 fold=0 epoch=81 loss=1.7396 val_auc=0.8230
model=transformerconv top_k=100 fold=0 epoch=82 loss=1.3564 val_auc=0.8237
model=transformerconv top_k=100 fold=0 epoch=83 loss=1.4286 val_auc=0.8239
model=transformerconv top_k=100 fold=0 epoch=84 loss=1.5163 val_auc=0.8240
model=transformerconv top_k=100 fold=0 epoch=85 loss=1.5215 val_auc=0.8236
model=transformerconv top_k=100 fold=0 epoch=86 loss=1.5683 val_auc=0.8222
model=transformerconv top_k=100 fold=0 epoch=87 loss=1.3833 val_auc=0.8210
model=transformerconv top_k=100 fold=0 epoch=88 loss=1.5125 val_auc=0.8208
model=transformerconv top_k=100 fold=0 epoch=89 loss=1.7295 val_auc=0.8211
model=transformerconv top_k=100 fold=0 epoch=90 loss=1.4769 val_auc=0.8217
model=transformerconv top_k=100 fold=0 epoch=91 loss=1.5350 val_auc=0.8220
model=transformerconv top_k=100 fold=0 epoch=92 loss=1.4960 val_auc=0.8223
model=transformerconv top_k=100 fold=0 epoch=93 loss=1.5914 val_auc=0.8226
model=transformerconv top_k=100 fold=0 epoch=94 loss=1.3471 val_auc=0.8232
model=transformerconv top_k=100 fold=0 epoch=95 loss=1.3055 val_auc=0.8240
model=transformerconv top_k=100 fold=0 epoch=96 loss=1.2821 val_auc=0.8251
model=transformerconv top_k=100 fold=0 epoch=97 loss=1.2941 val_auc=0.8264
model=transformerconv top_k=100 fold=0 epoch=98 loss=1.2237 val_auc=0.8274
model=transformerconv top_k=100 fold=0 epoch=99 loss=1.2896 val_auc=0.8284
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718731 edges

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=100 fold=1 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719209 edges
model=transformerconv top_k=100 fold=1 epoch=0 loss=9.5203 val_auc=0.4967
model=transformerconv top_k=100 fold=1 epoch=1 loss=30.7144 val_auc=0.5140
model=transformerconv top_k=100 fold=1 epoch=2 loss=21.2669 val_auc=0.6529
model=transformerconv top_k=100 fold=1 epoch=3 loss=7.0093 val_auc=0.7122
model=transformerconv top_k=100 fold=1 epoch=4 loss=5.8489 val_auc=0.7387
model=transformerconv top_k=100 fold=1 epoch=5 loss=9.6848 val_auc=0.7490
model=transformerconv top_k=100 fold=1 epoch=6 loss=6.0160 val_auc=0.7576
model=transformerconv top_k=100 fold=1 epoch=7 loss=5.9011 val_auc=0.7629
model=transformerconv top_k=100 fold=1 epoch=8 loss=6.5067 val_auc=0.7683
model=transformerconv top_k=100 fold=1 epoch=9 loss=7.4687 val_auc=0.7725
model=transformerconv top_k=100 fold=1 epoch=10 loss=4.7741 val_auc=0.7762
model=transformerconv top_k=100 fold=1 epoch=11 loss=5.1090 val_auc=0.7766
model=transformerconv top_k=100 fold=1 epoch=12 loss=4.8512 val_auc=0.7791
model=transformerconv top_k=100 fold=1 epoch=13 loss=4.6599 val_auc=0.7809
model=transformerconv top_k=100 fold=1 epoch=14 loss=4.4652 val_auc=0.7827
model=transformerconv top_k=100 fold=1 epoch=15 loss=4.0067 val_auc=0.7833
model=transformerconv top_k=100 fold=1 epoch=16 loss=3.5052 val_auc=0.7847
model=transformerconv top_k=100 fold=1 epoch=17 loss=3.8053 val_auc=0.7860
model=transformerconv top_k=100 fold=1 epoch=18 loss=4.1458 val_auc=0.7880
model=transformerconv top_k=100 fold=1 epoch=19 loss=3.7071 val_auc=0.7904
model=transformerconv top_k=100 fold=1 epoch=20 loss=3.3092 val_auc=0.7923
model=transformerconv top_k=100 fold=1 epoch=21 loss=2.8963 val_auc=0.7941
model=transformerconv top_k=100 fold=1 epoch=22 loss=3.2102 val_auc=0.7953
model=transformerconv top_k=100 fold=1 epoch=23 loss=3.0124 val_auc=0.7966
model=transformerconv top_k=100 fold=1 epoch=24 loss=3.3380 val_auc=0.7979
model=transformerconv top_k=100 fold=1 epoch=25 loss=2.8748 val_auc=0.7991
model=transformerconv top_k=100 fold=1 epoch=26 loss=2.9396 val_auc=0.8005
model=transformerconv top_k=100 fold=1 epoch=27 loss=2.9792 val_auc=0.8014
model=transformerconv top_k=100 fold=1 epoch=28 loss=4.3107 val_auc=0.8019
model=transformerconv top_k=100 fold=1 epoch=29 loss=3.3278 val_auc=0.8018
model=transformerconv top_k=100 fold=1 epoch=30 loss=2.6452 val_auc=0.8016
model=transformerconv top_k=100 fold=1 epoch=31 loss=2.4835 val_auc=0.8021
model=transformerconv top_k=100 fold=1 epoch=32 loss=3.5468 val_auc=0.8028
model=transformerconv top_k=100 fold=1 epoch=33 loss=4.4724 val_auc=0.8036
model=transformerconv top_k=100 fold=1 epoch=34 loss=3.3117 val_auc=0.8045
model=transformerconv top_k=100 fold=1 epoch=35 loss=3.2163 val_auc=0.8055
model=transformerconv top_k=100 fold=1 epoch=36 loss=2.6962 val_auc=0.8061
model=transformerconv top_k=100 fold=1 epoch=37 loss=2.6361 val_auc=0.8060
model=transformerconv top_k=100 fold=1 epoch=38 loss=3.1269 val_auc=0.8057
model=transformerconv top_k=100 fold=1 epoch=39 loss=3.9563 val_auc=0.8058
model=transformerconv top_k=100 fold=1 epoch=40 loss=4.0950 val_auc=0.8060
model=transformerconv top_k=100 fold=1 epoch=41 loss=2.7673 val_auc=0.8064
model=transformerconv top_k=100 fold=1 epoch=42 loss=2.2127 val_auc=0.8069
model=transformerconv top_k=100 fold=1 epoch=43 loss=2.0737 val_auc=0.8073
model=transformerconv top_k=100 fold=1 epoch=44 loss=2.5074 val_auc=0.8077
model=transformerconv top_k=100 fold=1 epoch=45 loss=2.7666 val_auc=0.8081
model=transformerconv top_k=100 fold=1 epoch=46 loss=3.0520 val_auc=0.8085
model=transformerconv top_k=100 fold=1 epoch=47 loss=1.9333 val_auc=0.8090
model=transformerconv top_k=100 fold=1 epoch=48 loss=2.1533 val_auc=0.8094
model=transformerconv top_k=100 fold=1 epoch=49 loss=2.1766 val_auc=0.8100
model=transformerconv top_k=100 fold=1 epoch=50 loss=2.0211 val_auc=0.8111
model=transformerconv top_k=100 fold=1 epoch=51 loss=2.2454 val_auc=0.8119
model=transformerconv top_k=100 fold=1 epoch=52 loss=1.9780 val_auc=0.8126
model=transformerconv top_k=100 fold=1 epoch=53 loss=1.8349 val_auc=0.8133
model=transformerconv top_k=100 fold=1 epoch=54 loss=2.1620 val_auc=0.8133
model=transformerconv top_k=100 fold=1 epoch=55 loss=2.1508 val_auc=0.8129
model=transformerconv top_k=100 fold=1 epoch=56 loss=2.0612 val_auc=0.8132
model=transformerconv top_k=100 fold=1 epoch=57 loss=1.8352 val_auc=0.8141
model=transformerconv top_k=100 fold=1 epoch=58 loss=1.8051 val_auc=0.8149
model=transformerconv top_k=100 fold=1 epoch=59 loss=1.7667 val_auc=0.8156
model=transformerconv top_k=100 fold=1 epoch=60 loss=1.5923 val_auc=0.8162
model=transformerconv top_k=100 fold=1 epoch=61 loss=1.8526 val_auc=0.8167
model=transformerconv top_k=100 fold=1 epoch=62 loss=1.6554 val_auc=0.8168
model=transformerconv top_k=100 fold=1 epoch=63 loss=1.7526 val_auc=0.8173
model=transformerconv top_k=100 fold=1 epoch=64 loss=1.6746 val_auc=0.8179
model=transformerconv top_k=100 fold=1 epoch=65 loss=1.8847 val_auc=0.8182
model=transformerconv top_k=100 fold=1 epoch=66 loss=1.5452 val_auc=0.8193
model=transformerconv top_k=100 fold=1 epoch=67 loss=1.6636 val_auc=0.8196
model=transformerconv top_k=100 fold=1 epoch=68 loss=2.0912 val_auc=0.8179
model=transformerconv top_k=100 fold=1 epoch=69 loss=2.2291 val_auc=0.8163
model=transformerconv top_k=100 fold=1 epoch=70 loss=2.2159 val_auc=0.8164
model=transformerconv top_k=100 fold=1 epoch=71 loss=1.6479 val_auc=0.8187
model=transformerconv top_k=100 fold=1 epoch=72 loss=1.6295 val_auc=0.8197
model=transformerconv top_k=100 fold=1 epoch=73 loss=1.5735 val_auc=0.8202
model=transformerconv top_k=100 fold=1 epoch=74 loss=1.6260 val_auc=0.8199
model=transformerconv top_k=100 fold=1 epoch=75 loss=1.3935 val_auc=0.8185
model=transformerconv top_k=100 fold=1 epoch=76 loss=1.5910 val_auc=0.8175
model=transformerconv top_k=100 fold=1 epoch=77 loss=1.5232 val_auc=0.8181
model=transformerconv top_k=100 fold=1 epoch=78 loss=1.4276 val_auc=0.8203
model=transformerconv top_k=100 fold=1 epoch=79 loss=1.2623 val_auc=0.8213
model=transformerconv top_k=100 fold=1 epoch=80 loss=1.4452 val_auc=0.8216
model=transformerconv top_k=100 fold=1 epoch=81 loss=1.3868 val_auc=0.8224
model=transformerconv top_k=100 fold=1 epoch=82 loss=1.4018 val_auc=0.8231
model=transformerconv top_k=100 fold=1 epoch=83 loss=1.4305 val_auc=0.8233
model=transformerconv top_k=100 fold=1 epoch=84 loss=1.3755 val_auc=0.8231
model=transformerconv top_k=100 fold=1 epoch=85 loss=1.3543 val_auc=0.8234
model=transformerconv top_k=100 fold=1 epoch=86 loss=1.3625 val_auc=0.8239
model=transformerconv top_k=100 fold=1 epoch=87 loss=1.4285 val_auc=0.8236
model=transformerconv top_k=100 fold=1 epoch=88 loss=1.5949 val_auc=0.8233
model=transformerconv top_k=100 fold=1 epoch=89 loss=1.4113 val_auc=0.8233
model=transformerconv top_k=100 fold=1 epoch=90 loss=1.3687 val_auc=0.8234
model=transformerconv top_k=100 fold=1 epoch=91 loss=1.4313 val_auc=0.8232
model=transformerconv top_k=100 fold=1 epoch=92 loss=1.1994 val_auc=0.8243
model=transformerconv top_k=100 fold=1 epoch=93 loss=1.2501 val_auc=0.8258
model=transformerconv top_k=100 fold=1 epoch=94 loss=1.2282 val_auc=0.8263
model=transformerconv top_k=100 fold=1 epoch=95 loss=1.1843 val_auc=0.8269
model=transformerconv top_k=100 fold=1 epoch=96 loss=1.3991 val_auc=0.8272
model=transformerconv top_k=100 fold=1 epoch=97 loss=1.1288 val_auc=0.8276
model=transformerconv top_k=100 fold=1 epoch=98 loss=1.3220 val_auc=0.8284
model=transformerconv top_k=100 fold=1 epoch=99 loss=1.3864 val_auc=0.8287
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719209 edges

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=100 fold=2 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718855 edges
model=transformerconv top_k=100 fold=2 epoch=0 loss=7.0277 val_auc=0.7349
model=transformerconv top_k=100 fold=2 epoch=1 loss=6.4494 val_auc=0.7406
model=transformerconv top_k=100 fold=2 epoch=2 loss=12.9266 val_auc=0.7635
model=transformerconv top_k=100 fold=2 epoch=3 loss=7.5090 val_auc=0.7638
model=transformerconv top_k=100 fold=2 epoch=4 loss=5.2224 val_auc=0.7613
model=transformerconv top_k=100 fold=2 epoch=5 loss=5.1070 val_auc=0.7603
model=transformerconv top_k=100 fold=2 epoch=6 loss=4.1081 val_auc=0.7631
model=transformerconv top_k=100 fold=2 epoch=7 loss=5.2077 val_auc=0.7657
model=transformerconv top_k=100 fold=2 epoch=8 loss=3.8278 val_auc=0.7702
model=transformerconv top_k=100 fold=2 epoch=9 loss=4.1617 val_auc=0.7737
model=transformerconv top_k=100 fold=2 epoch=10 loss=4.6205 val_auc=0.7745
model=transformerconv top_k=100 fold=2 epoch=11 loss=3.7086 val_auc=0.7756
model=transformerconv top_k=100 fold=2 epoch=12 loss=4.0738 val_auc=0.7769
model=transformerconv top_k=100 fold=2 epoch=13 loss=3.3382 val_auc=0.7779
model=transformerconv top_k=100 fold=2 epoch=14 loss=3.4258 val_auc=0.7801
model=transformerconv top_k=100 fold=2 epoch=15 loss=3.0329 val_auc=0.7824
model=transformerconv top_k=100 fold=2 epoch=16 loss=3.1428 val_auc=0.7837
model=transformerconv top_k=100 fold=2 epoch=17 loss=2.8769 val_auc=0.7854
model=transformerconv top_k=100 fold=2 epoch=18 loss=2.9488 val_auc=0.7869
model=transformerconv top_k=100 fold=2 epoch=19 loss=2.9915 val_auc=0.7879
model=transformerconv top_k=100 fold=2 epoch=20 loss=3.0169 val_auc=0.7884
model=transformerconv top_k=100 fold=2 epoch=21 loss=2.9924 val_auc=0.7885
model=transformerconv top_k=100 fold=2 epoch=22 loss=3.0522 val_auc=0.7888
model=transformerconv top_k=100 fold=2 epoch=23 loss=2.5994 val_auc=0.7897
model=transformerconv top_k=100 fold=2 epoch=24 loss=2.6226 val_auc=0.7908
model=transformerconv top_k=100 fold=2 epoch=25 loss=2.6462 val_auc=0.7917
model=transformerconv top_k=100 fold=2 epoch=26 loss=2.3791 val_auc=0.7927
model=transformerconv top_k=100 fold=2 epoch=27 loss=2.7554 val_auc=0.7937
model=transformerconv top_k=100 fold=2 epoch=28 loss=3.1791 val_auc=0.7947
model=transformerconv top_k=100 fold=2 epoch=29 loss=2.9449 val_auc=0.7950
model=transformerconv top_k=100 fold=2 epoch=30 loss=2.2327 val_auc=0.7951
model=transformerconv top_k=100 fold=2 epoch=31 loss=2.5749 val_auc=0.7956
model=transformerconv top_k=100 fold=2 epoch=32 loss=3.4943 val_auc=0.7962
model=transformerconv top_k=100 fold=2 epoch=33 loss=3.4686 val_auc=0.7968
model=transformerconv top_k=100 fold=2 epoch=34 loss=2.1068 val_auc=0.7968
model=transformerconv top_k=100 fold=2 epoch=35 loss=2.1269 val_auc=0.7966
model=transformerconv top_k=100 fold=2 epoch=36 loss=2.1030 val_auc=0.7968
model=transformerconv top_k=100 fold=2 epoch=37 loss=1.9001 val_auc=0.7979
model=transformerconv top_k=100 fold=2 epoch=38 loss=1.8086 val_auc=0.7990
model=transformerconv top_k=100 fold=2 epoch=39 loss=1.9264 val_auc=0.7998
model=transformerconv top_k=100 fold=2 epoch=40 loss=2.0863 val_auc=0.8004
model=transformerconv top_k=100 fold=2 epoch=41 loss=2.0914 val_auc=0.8000
model=transformerconv top_k=100 fold=2 epoch=42 loss=1.6806 val_auc=0.7986
model=transformerconv top_k=100 fold=2 epoch=43 loss=1.7994 val_auc=0.7970
model=transformerconv top_k=100 fold=2 epoch=44 loss=2.1859 val_auc=0.7974
model=transformerconv top_k=100 fold=2 epoch=45 loss=1.9880 val_auc=0.7998
model=transformerconv top_k=100 fold=2 epoch=46 loss=1.8447 val_auc=0.8018
model=transformerconv top_k=100 fold=2 epoch=47 loss=1.5790 val_auc=0.8025
model=transformerconv top_k=100 fold=2 epoch=48 loss=1.7249 val_auc=0.8027
model=transformerconv top_k=100 fold=2 epoch=49 loss=1.9874 val_auc=0.8010
model=transformerconv top_k=100 fold=2 epoch=50 loss=1.7450 val_auc=0.7970
model=transformerconv top_k=100 fold=2 epoch=51 loss=1.6348 val_auc=0.7947
model=transformerconv top_k=100 fold=2 epoch=52 loss=1.8355 val_auc=0.7954
model=transformerconv top_k=100 fold=2 epoch=53 loss=1.7454 val_auc=0.7983
model=transformerconv top_k=100 fold=2 epoch=54 loss=1.4902 val_auc=0.8025
model=transformerconv top_k=100 fold=2 epoch=55 loss=1.5076 val_auc=0.8038
model=transformerconv top_k=100 fold=2 epoch=56 loss=1.8247 val_auc=0.8037
model=transformerconv top_k=100 fold=2 epoch=57 loss=1.8011 val_auc=0.8026
model=transformerconv top_k=100 fold=2 epoch=58 loss=1.5617 val_auc=0.8013
model=transformerconv top_k=100 fold=2 epoch=59 loss=1.5410 val_auc=0.8024
model=transformerconv top_k=100 fold=2 epoch=60 loss=1.6533 val_auc=0.8037
model=transformerconv top_k=100 fold=2 epoch=61 loss=1.7414 val_auc=0.8051
model=transformerconv top_k=100 fold=2 epoch=62 loss=1.3726 val_auc=0.8068
model=transformerconv top_k=100 fold=2 epoch=63 loss=1.4871 val_auc=0.8077
model=transformerconv top_k=100 fold=2 epoch=64 loss=1.5594 val_auc=0.8077
model=transformerconv top_k=100 fold=2 epoch=65 loss=1.4456 val_auc=0.8073
model=transformerconv top_k=100 fold=2 epoch=66 loss=1.4704 val_auc=0.8077
model=transformerconv top_k=100 fold=2 epoch=67 loss=1.3744 val_auc=0.8085
model=transformerconv top_k=100 fold=2 epoch=68 loss=1.2651 val_auc=0.8098
model=transformerconv top_k=100 fold=2 epoch=69 loss=1.2732 val_auc=0.8105
model=transformerconv top_k=100 fold=2 epoch=70 loss=1.2640 val_auc=0.8105
model=transformerconv top_k=100 fold=2 epoch=71 loss=1.2165 val_auc=0.8116
model=transformerconv top_k=100 fold=2 epoch=72 loss=1.3002 val_auc=0.8119
model=transformerconv top_k=100 fold=2 epoch=73 loss=1.2555 val_auc=0.8109
model=transformerconv top_k=100 fold=2 epoch=74 loss=1.2420 val_auc=0.8102
model=transformerconv top_k=100 fold=2 epoch=75 loss=1.2359 val_auc=0.8091
model=transformerconv top_k=100 fold=2 epoch=76 loss=1.5078 val_auc=0.8081
model=transformerconv top_k=100 fold=2 epoch=77 loss=1.4480 val_auc=0.8083
model=transformerconv top_k=100 fold=2 epoch=78 loss=1.3940 val_auc=0.8102
model=transformerconv top_k=100 fold=2 epoch=79 loss=1.2697 val_auc=0.8147
model=transformerconv top_k=100 fold=2 epoch=80 loss=1.6686 val_auc=0.8156
model=transformerconv top_k=100 fold=2 epoch=81 loss=2.4044 val_auc=0.8152
model=transformerconv top_k=100 fold=2 epoch=82 loss=1.9496 val_auc=0.8145
model=transformerconv top_k=100 fold=2 epoch=83 loss=1.5344 val_auc=0.8119
model=transformerconv top_k=100 fold=2 epoch=84 loss=1.2816 val_auc=0.8083
model=transformerconv top_k=100 fold=2 epoch=85 loss=1.2793 val_auc=0.8067
model=transformerconv top_k=100 fold=2 epoch=86 loss=1.4575 val_auc=0.8066
model=transformerconv top_k=100 fold=2 epoch=87 loss=1.4606 val_auc=0.8077
model=transformerconv top_k=100 fold=2 epoch=88 loss=1.4237 val_auc=0.8099
model=transformerconv top_k=100 fold=2 epoch=89 loss=1.1650 val_auc=0.8130
model=transformerconv top_k=100 fold=2 epoch=90 loss=1.3967 val_auc=0.8147
model=transformerconv top_k=100 fold=2 epoch=91 loss=1.7632 val_auc=0.8156
model=transformerconv top_k=100 fold=2 epoch=92 loss=1.5587 val_auc=0.8160
model=transformerconv top_k=100 fold=2 epoch=93 loss=1.5122 val_auc=0.8144
model=transformerconv top_k=100 fold=2 epoch=94 loss=1.1002 val_auc=0.8105
model=transformerconv top_k=100 fold=2 epoch=95 loss=1.2000 val_auc=0.8078
model=transformerconv top_k=100 fold=2 epoch=96 loss=1.6440 val_auc=0.8068
model=transformerconv top_k=100 fold=2 epoch=97 loss=1.5766 val_auc=0.8081
model=transformerconv top_k=100 fold=2 epoch=98 loss=1.4526 val_auc=0.8106
model=transformerconv top_k=100 fold=2 epoch=99 loss=1.1384 val_auc=0.8143
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718855 edges

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=100 fold=3 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719213 edges
model=transformerconv top_k=100 fold=3 epoch=0 loss=7.6459 val_auc=0.7181
model=transformerconv top_k=100 fold=3 epoch=1 loss=23.8593 val_auc=0.7436
model=transformerconv top_k=100 fold=3 epoch=2 loss=15.3484 val_auc=0.7331
model=transformerconv top_k=100 fold=3 epoch=3 loss=6.6180 val_auc=0.7469
model=transformerconv top_k=100 fold=3 epoch=4 loss=6.1014 val_auc=0.7589
model=transformerconv top_k=100 fold=3 epoch=5 loss=5.6612 val_auc=0.7688
model=transformerconv top_k=100 fold=3 epoch=6 loss=6.7913 val_auc=0.7735
model=transformerconv top_k=100 fold=3 epoch=7 loss=4.7000 val_auc=0.7757
model=transformerconv top_k=100 fold=3 epoch=8 loss=4.3242 val_auc=0.7780
model=transformerconv top_k=100 fold=3 epoch=9 loss=4.6672 val_auc=0.7801
model=transformerconv top_k=100 fold=3 epoch=10 loss=3.6056 val_auc=0.7846
model=transformerconv top_k=100 fold=3 epoch=11 loss=4.5379 val_auc=0.7873
model=transformerconv top_k=100 fold=3 epoch=12 loss=4.3240 val_auc=0.7889
model=transformerconv top_k=100 fold=3 epoch=13 loss=3.4331 val_auc=0.7913
model=transformerconv top_k=100 fold=3 epoch=14 loss=4.2504 val_auc=0.7941
model=transformerconv top_k=100 fold=3 epoch=15 loss=3.7216 val_auc=0.7970
model=transformerconv top_k=100 fold=3 epoch=16 loss=4.1047 val_auc=0.7989
model=transformerconv top_k=100 fold=3 epoch=17 loss=3.4792 val_auc=0.7996
model=transformerconv top_k=100 fold=3 epoch=18 loss=3.2909 val_auc=0.8002
model=transformerconv top_k=100 fold=3 epoch=19 loss=3.0690 val_auc=0.8012
model=transformerconv top_k=100 fold=3 epoch=20 loss=3.3281 val_auc=0.8019
model=transformerconv top_k=100 fold=3 epoch=21 loss=3.4876 val_auc=0.8031
model=transformerconv top_k=100 fold=3 epoch=22 loss=2.6969 val_auc=0.8048
model=transformerconv top_k=100 fold=3 epoch=23 loss=2.7799 val_auc=0.8063
model=transformerconv top_k=100 fold=3 epoch=24 loss=2.7485 val_auc=0.8076
model=transformerconv top_k=100 fold=3 epoch=25 loss=2.6483 val_auc=0.8094
model=transformerconv top_k=100 fold=3 epoch=26 loss=2.5193 val_auc=0.8115
model=transformerconv top_k=100 fold=3 epoch=27 loss=2.1852 val_auc=0.8137
model=transformerconv top_k=100 fold=3 epoch=28 loss=2.4253 val_auc=0.8154
model=transformerconv top_k=100 fold=3 epoch=29 loss=2.3198 val_auc=0.8169
model=transformerconv top_k=100 fold=3 epoch=30 loss=2.2552 val_auc=0.8179
model=transformerconv top_k=100 fold=3 epoch=31 loss=2.3761 val_auc=0.8183
model=transformerconv top_k=100 fold=3 epoch=32 loss=2.1065 val_auc=0.8184
model=transformerconv top_k=100 fold=3 epoch=33 loss=1.9976 val_auc=0.8184
model=transformerconv top_k=100 fold=3 epoch=34 loss=2.0389 val_auc=0.8182
model=transformerconv top_k=100 fold=3 epoch=35 loss=2.2863 val_auc=0.8189
model=transformerconv top_k=100 fold=3 epoch=36 loss=2.1817 val_auc=0.8194
model=transformerconv top_k=100 fold=3 epoch=37 loss=1.6803 val_auc=0.8202
model=transformerconv top_k=100 fold=3 epoch=38 loss=1.5398 val_auc=0.8202
model=transformerconv top_k=100 fold=3 epoch=39 loss=1.6607 val_auc=0.8190
model=transformerconv top_k=100 fold=3 epoch=40 loss=1.6595 val_auc=0.8172
model=transformerconv top_k=100 fold=3 epoch=41 loss=1.9629 val_auc=0.8146
model=transformerconv top_k=100 fold=3 epoch=42 loss=1.9671 val_auc=0.8126
model=transformerconv top_k=100 fold=3 epoch=43 loss=1.6781 val_auc=0.8119
model=transformerconv top_k=100 fold=3 epoch=44 loss=1.9011 val_auc=0.8127
model=transformerconv top_k=100 fold=3 epoch=45 loss=1.6035 val_auc=0.8139
model=transformerconv top_k=100 fold=3 epoch=46 loss=1.5855 val_auc=0.8151
model=transformerconv top_k=100 fold=3 epoch=47 loss=1.6332 val_auc=0.8163
model=transformerconv top_k=100 fold=3 epoch=48 loss=1.5799 val_auc=0.8170
model=transformerconv top_k=100 fold=3 epoch=49 loss=1.4446 val_auc=0.8179
transformerconv top_k=100 fold=3: early stopping at epoch 49
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719213 edges

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=100 fold=4 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719233 edges
model=transformerconv top_k=100 fold=4 epoch=0 loss=8.7617 val_auc=0.4985
model=transformerconv top_k=100 fold=4 epoch=1 loss=28.8096 val_auc=0.5180
model=transformerconv top_k=100 fold=4 epoch=2 loss=28.2359 val_auc=0.6345
model=transformerconv top_k=100 fold=4 epoch=3 loss=14.9843 val_auc=0.6853
model=transformerconv top_k=100 fold=4 epoch=4 loss=4.4869 val_auc=0.7325
model=transformerconv top_k=100 fold=4 epoch=5 loss=11.7176 val_auc=0.7413
model=transformerconv top_k=100 fold=4 epoch=6 loss=15.5756 val_auc=0.7445
model=transformerconv top_k=100 fold=4 epoch=7 loss=13.5445 val_auc=0.7448
model=transformerconv top_k=100 fold=4 epoch=8 loss=9.9694 val_auc=0.7413
model=transformerconv top_k=100 fold=4 epoch=9 loss=7.2113 val_auc=0.7352
model=transformerconv top_k=100 fold=4 epoch=10 loss=4.2414 val_auc=0.7414
model=transformerconv top_k=100 fold=4 epoch=11 loss=5.6495 val_auc=0.7490
model=transformerconv top_k=100 fold=4 epoch=12 loss=6.9910 val_auc=0.7556
model=transformerconv top_k=100 fold=4 epoch=13 loss=4.4208 val_auc=0.7615
model=transformerconv top_k=100 fold=4 epoch=14 loss=3.8297 val_auc=0.7674
model=transformerconv top_k=100 fold=4 epoch=15 loss=3.8848 val_auc=0.7714
model=transformerconv top_k=100 fold=4 epoch=16 loss=4.6167 val_auc=0.7746
model=transformerconv top_k=100 fold=4 epoch=17 loss=3.9677 val_auc=0.7792
model=transformerconv top_k=100 fold=4 epoch=18 loss=3.6637 val_auc=0.7841
model=transformerconv top_k=100 fold=4 epoch=19 loss=4.6271 val_auc=0.7876
model=transformerconv top_k=100 fold=4 epoch=20 loss=3.6493 val_auc=0.7907
model=transformerconv top_k=100 fold=4 epoch=21 loss=2.8048 val_auc=0.7926
model=transformerconv top_k=100 fold=4 epoch=22 loss=4.2678 val_auc=0.7936
model=transformerconv top_k=100 fold=4 epoch=23 loss=4.7044 val_auc=0.7942
model=transformerconv top_k=100 fold=4 epoch=24 loss=3.1725 val_auc=0.7948
model=transformerconv top_k=100 fold=4 epoch=25 loss=3.2141 val_auc=0.7971
model=transformerconv top_k=100 fold=4 epoch=26 loss=2.9506 val_auc=0.7999
model=transformerconv top_k=100 fold=4 epoch=27 loss=3.4157 val_auc=0.8009
model=transformerconv top_k=100 fold=4 epoch=28 loss=3.9760 val_auc=0.8014
model=transformerconv top_k=100 fold=4 epoch=29 loss=4.0586 val_auc=0.8011
model=transformerconv top_k=100 fold=4 epoch=30 loss=2.5613 val_auc=0.8000
model=transformerconv top_k=100 fold=4 epoch=31 loss=2.6091 val_auc=0.8003
model=transformerconv top_k=100 fold=4 epoch=32 loss=2.6363 val_auc=0.8012
model=transformerconv top_k=100 fold=4 epoch=33 loss=3.0791 val_auc=0.8023
model=transformerconv top_k=100 fold=4 epoch=34 loss=2.7565 val_auc=0.8034
model=transformerconv top_k=100 fold=4 epoch=35 loss=2.3786 val_auc=0.8043
model=transformerconv top_k=100 fold=4 epoch=36 loss=2.6106 val_auc=0.8053
model=transformerconv top_k=100 fold=4 epoch=37 loss=2.5801 val_auc=0.8065
model=transformerconv top_k=100 fold=4 epoch=38 loss=2.3306 val_auc=0.8074
model=transformerconv top_k=100 fold=4 epoch=39 loss=2.6405 val_auc=0.8080
model=transformerconv top_k=100 fold=4 epoch=40 loss=2.4953 val_auc=0.8086
model=transformerconv top_k=100 fold=4 epoch=41 loss=2.2370 val_auc=0.8093
model=transformerconv top_k=100 fold=4 epoch=42 loss=2.1852 val_auc=0.8103
model=transformerconv top_k=100 fold=4 epoch=43 loss=2.2388 val_auc=0.8113
model=transformerconv top_k=100 fold=4 epoch=44 loss=2.3480 val_auc=0.8122
model=transformerconv top_k=100 fold=4 epoch=45 loss=2.3841 val_auc=0.8129
model=transformerconv top_k=100 fold=4 epoch=46 loss=2.0338 val_auc=0.8134
model=transformerconv top_k=100 fold=4 epoch=47 loss=2.0756 val_auc=0.8141
model=transformerconv top_k=100 fold=4 epoch=48 loss=2.2599 val_auc=0.8151
model=transformerconv top_k=100 fold=4 epoch=49 loss=2.6597 val_auc=0.8162
model=transformerconv top_k=100 fold=4 epoch=50 loss=1.8717 val_auc=0.8171
model=transformerconv top_k=100 fold=4 epoch=51 loss=1.7860 val_auc=0.8180
model=transformerconv top_k=100 fold=4 epoch=52 loss=2.1785 val_auc=0.8185
model=transformerconv top_k=100 fold=4 epoch=53 loss=1.9173 val_auc=0.8184
model=transformerconv top_k=100 fold=4 epoch=54 loss=2.2297 val_auc=0.8180
model=transformerconv top_k=100 fold=4 epoch=55 loss=1.6075 val_auc=0.8177
model=transformerconv top_k=100 fold=4 epoch=56 loss=1.8728 val_auc=0.8177
model=transformerconv top_k=100 fold=4 epoch=57 loss=1.9720 val_auc=0.8181
model=transformerconv top_k=100 fold=4 epoch=58 loss=1.9090 val_auc=0.8186
model=transformerconv top_k=100 fold=4 epoch=59 loss=1.8757 val_auc=0.8190
model=transformerconv top_k=100 fold=4 epoch=60 loss=1.5336 val_auc=0.8196
model=transformerconv top_k=100 fold=4 epoch=61 loss=2.0122 val_auc=0.8202
model=transformerconv top_k=100 fold=4 epoch=62 loss=1.7402 val_auc=0.8207
model=transformerconv top_k=100 fold=4 epoch=63 loss=1.7874 val_auc=0.8208
model=transformerconv top_k=100 fold=4 epoch=64 loss=1.6962 val_auc=0.8207
model=transformerconv top_k=100 fold=4 epoch=65 loss=1.8628 val_auc=0.8208
model=transformerconv top_k=100 fold=4 epoch=66 loss=1.5472 val_auc=0.8211
model=transformerconv top_k=100 fold=4 epoch=67 loss=1.4478 val_auc=0.8215
model=transformerconv top_k=100 fold=4 epoch=68 loss=1.4886 val_auc=0.8216
model=transformerconv top_k=100 fold=4 epoch=69 loss=1.4359 val_auc=0.8219
model=transformerconv top_k=100 fold=4 epoch=70 loss=1.4733 val_auc=0.8225
model=transformerconv top_k=100 fold=4 epoch=71 loss=1.3873 val_auc=0.8236
model=transformerconv top_k=100 fold=4 epoch=72 loss=1.4653 val_auc=0.8242
model=transformerconv top_k=100 fold=4 epoch=73 loss=1.5541 val_auc=0.8246
model=transformerconv top_k=100 fold=4 epoch=74 loss=1.3312 val_auc=0.8249
model=transformerconv top_k=100 fold=4 epoch=75 loss=1.5226 val_auc=0.8254
model=transformerconv top_k=100 fold=4 epoch=76 loss=1.5754 val_auc=0.8258
model=transformerconv top_k=100 fold=4 epoch=77 loss=1.4370 val_auc=0.8261
model=transformerconv top_k=100 fold=4 epoch=78 loss=1.3253 val_auc=0.8261
model=transformerconv top_k=100 fold=4 epoch=79 loss=1.3239 val_auc=0.8259
model=transformerconv top_k=100 fold=4 epoch=80 loss=1.5308 val_auc=0.8253
model=transformerconv top_k=100 fold=4 epoch=81 loss=1.3248 val_auc=0.8251
model=transformerconv top_k=100 fold=4 epoch=82 loss=1.4334 val_auc=0.8252
model=transformerconv top_k=100 fold=4 epoch=83 loss=1.4503 val_auc=0.8254
model=transformerconv top_k=100 fold=4 epoch=84 loss=1.2694 val_auc=0.8259
model=transformerconv top_k=100 fold=4 epoch=85 loss=1.3721 val_auc=0.8262
model=transformerconv top_k=100 fold=4 epoch=86 loss=1.2956 val_auc=0.8262
model=transformerconv top_k=100 fold=4 epoch=87 loss=1.4260 val_auc=0.8262
model=transformerconv top_k=100 fold=4 epoch=88 loss=1.3847 val_auc=0.8263
model=transformerconv top_k=100 fold=4 epoch=89 loss=1.3159 val_auc=0.8263
model=transformerconv top_k=100 fold=4 epoch=90 loss=1.2206 val_auc=0.8265
model=transformerconv top_k=100 fold=4 epoch=91 loss=1.3447 val_auc=0.8265
model=transformerconv top_k=100 fold=4 epoch=92 loss=1.2015 val_auc=0.8264
model=transformerconv top_k=100 fold=4 epoch=93 loss=1.1234 val_auc=0.8266
model=transformerconv top_k=100 fold=4 epoch=94 loss=1.1766 val_auc=0.8273
model=transformerconv top_k=100 fold=4 epoch=95 loss=1.2218 val_auc=0.8280
model=transformerconv top_k=100 fold=4 epoch=96 loss=1.2124 val_auc=0.8282
model=transformerconv top_k=100 fold=4 epoch=97 loss=1.2287 val_auc=0.8283
model=transformerconv top_k=100 fold=4 epoch=98 loss=1.2065 val_auc=0.8288
model=transformerconv top_k=100 fold=4 epoch=99 loss=1.1858 val_auc=0.8296
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719233 edges

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=100 fold=5 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718759 edges
model=transformerconv top_k=100 fold=5 epoch=0 loss=10.4837 val_auc=0.4998
model=transformerconv top_k=100 fold=5 epoch=1 loss=30.5824 val_auc=0.4919
model=transformerconv top_k=100 fold=5 epoch=2 loss=24.2317 val_auc=0.6223
model=transformerconv top_k=100 fold=5 epoch=3 loss=9.3633 val_auc=0.7111
model=transformerconv top_k=100 fold=5 epoch=4 loss=5.7752 val_auc=0.7360
model=transformerconv top_k=100 fold=5 epoch=5 loss=8.2748 val_auc=0.7407
model=transformerconv top_k=100 fold=5 epoch=6 loss=5.4597 val_auc=0.7369
model=transformerconv top_k=100 fold=5 epoch=7 loss=4.2759 val_auc=0.7493
model=transformerconv top_k=100 fold=5 epoch=8 loss=4.2271 val_auc=0.7634
model=transformerconv top_k=100 fold=5 epoch=9 loss=4.6973 val_auc=0.7755
model=transformerconv top_k=100 fold=5 epoch=10 loss=3.7102 val_auc=0.7824
model=transformerconv top_k=100 fold=5 epoch=11 loss=3.9179 val_auc=0.7859
model=transformerconv top_k=100 fold=5 epoch=12 loss=3.9137 val_auc=0.7890
model=transformerconv top_k=100 fold=5 epoch=13 loss=3.3868 val_auc=0.7924
model=transformerconv top_k=100 fold=5 epoch=14 loss=4.0108 val_auc=0.7958
model=transformerconv top_k=100 fold=5 epoch=15 loss=3.5984 val_auc=0.7984
model=transformerconv top_k=100 fold=5 epoch=16 loss=3.0197 val_auc=0.8006
model=transformerconv top_k=100 fold=5 epoch=17 loss=3.3288 val_auc=0.8028
model=transformerconv top_k=100 fold=5 epoch=18 loss=3.0055 val_auc=0.8051
model=transformerconv top_k=100 fold=5 epoch=19 loss=3.5365 val_auc=0.8066
model=transformerconv top_k=100 fold=5 epoch=20 loss=3.5347 val_auc=0.8075
model=transformerconv top_k=100 fold=5 epoch=21 loss=2.7264 val_auc=0.8084
model=transformerconv top_k=100 fold=5 epoch=22 loss=2.8521 val_auc=0.8093
model=transformerconv top_k=100 fold=5 epoch=23 loss=2.7769 val_auc=0.8103
model=transformerconv top_k=100 fold=5 epoch=24 loss=2.4407 val_auc=0.8115
model=transformerconv top_k=100 fold=5 epoch=25 loss=2.3474 val_auc=0.8130
model=transformerconv top_k=100 fold=5 epoch=26 loss=2.4497 val_auc=0.8145
model=transformerconv top_k=100 fold=5 epoch=27 loss=2.6817 val_auc=0.8158
model=transformerconv top_k=100 fold=5 epoch=28 loss=2.4407 val_auc=0.8166
model=transformerconv top_k=100 fold=5 epoch=29 loss=2.3745 val_auc=0.8170
model=transformerconv top_k=100 fold=5 epoch=30 loss=2.3862 val_auc=0.8180
model=transformerconv top_k=100 fold=5 epoch=31 loss=2.0330 val_auc=0.8194
model=transformerconv top_k=100 fold=5 epoch=32 loss=2.4329 val_auc=0.8209
model=transformerconv top_k=100 fold=5 epoch=33 loss=2.4874 val_auc=0.8218
model=transformerconv top_k=100 fold=5 epoch=34 loss=2.5919 val_auc=0.8222
model=transformerconv top_k=100 fold=5 epoch=35 loss=1.7720 val_auc=0.8223
model=transformerconv top_k=100 fold=5 epoch=36 loss=2.0621 val_auc=0.8227
model=transformerconv top_k=100 fold=5 epoch=37 loss=2.1172 val_auc=0.8229
model=transformerconv top_k=100 fold=5 epoch=38 loss=1.8048 val_auc=0.8234
model=transformerconv top_k=100 fold=5 epoch=39 loss=1.7546 val_auc=0.8237
model=transformerconv top_k=100 fold=5 epoch=40 loss=1.9334 val_auc=0.8242
model=transformerconv top_k=100 fold=5 epoch=41 loss=1.6100 val_auc=0.8250
model=transformerconv top_k=100 fold=5 epoch=42 loss=1.5471 val_auc=0.8259
model=transformerconv top_k=100 fold=5 epoch=43 loss=1.5300 val_auc=0.8267
model=transformerconv top_k=100 fold=5 epoch=44 loss=1.4172 val_auc=0.8274
model=transformerconv top_k=100 fold=5 epoch=45 loss=1.9974 val_auc=0.8278
model=transformerconv top_k=100 fold=5 epoch=46 loss=2.1168 val_auc=0.8278
model=transformerconv top_k=100 fold=5 epoch=47 loss=1.9097 val_auc=0.8271
model=transformerconv top_k=100 fold=5 epoch=48 loss=1.5420 val_auc=0.8269
model=transformerconv top_k=100 fold=5 epoch=49 loss=1.6524 val_auc=0.8276
model=transformerconv top_k=100 fold=5 epoch=50 loss=1.8828 val_auc=0.8278
model=transformerconv top_k=100 fold=5 epoch=51 loss=1.9091 val_auc=0.8281
model=transformerconv top_k=100 fold=5 epoch=52 loss=1.4495 val_auc=0.8278
model=transformerconv top_k=100 fold=5 epoch=53 loss=1.3879 val_auc=0.8280
model=transformerconv top_k=100 fold=5 epoch=54 loss=1.4495 val_auc=0.8279
model=transformerconv top_k=100 fold=5 epoch=55 loss=1.3316 val_auc=0.8280
model=transformerconv top_k=100 fold=5 epoch=56 loss=1.3626 val_auc=0.8272
model=transformerconv top_k=100 fold=5 epoch=57 loss=1.5609 val_auc=0.8262
model=transformerconv top_k=100 fold=5 epoch=58 loss=1.3601 val_auc=0.8266
model=transformerconv top_k=100 fold=5 epoch=59 loss=1.4210 val_auc=0.8273
model=transformerconv top_k=100 fold=5 epoch=60 loss=1.2606 val_auc=0.8286
model=transformerconv top_k=100 fold=5 epoch=61 loss=1.2666 val_auc=0.8295
model=transformerconv top_k=100 fold=5 epoch=62 loss=1.2415 val_auc=0.8296
model=transformerconv top_k=100 fold=5 epoch=63 loss=1.2108 val_auc=0.8296
model=transformerconv top_k=100 fold=5 epoch=64 loss=1.2412 val_auc=0.8294
model=transformerconv top_k=100 fold=5 epoch=65 loss=1.2653 val_auc=0.8291
model=transformerconv top_k=100 fold=5 epoch=66 loss=1.2612 val_auc=0.8293
model=transformerconv top_k=100 fold=5 epoch=67 loss=1.2851 val_auc=0.8305
model=transformerconv top_k=100 fold=5 epoch=68 loss=1.6351 val_auc=0.8314
model=transformerconv top_k=100 fold=5 epoch=69 loss=1.2289 val_auc=0.8315
model=transformerconv top_k=100 fold=5 epoch=70 loss=1.1472 val_auc=0.8307
model=transformerconv top_k=100 fold=5 epoch=71 loss=1.4422 val_auc=0.8298
model=transformerconv top_k=100 fold=5 epoch=72 loss=1.3393 val_auc=0.8296
model=transformerconv top_k=100 fold=5 epoch=73 loss=1.1117 val_auc=0.8298
model=transformerconv top_k=100 fold=5 epoch=74 loss=1.2515 val_auc=0.8292
model=transformerconv top_k=100 fold=5 epoch=75 loss=1.4679 val_auc=0.8283
model=transformerconv top_k=100 fold=5 epoch=76 loss=1.2832 val_auc=0.8272
model=transformerconv top_k=100 fold=5 epoch=77 loss=1.1879 val_auc=0.8250
model=transformerconv top_k=100 fold=5 epoch=78 loss=1.2438 val_auc=0.8248
model=transformerconv top_k=100 fold=5 epoch=79 loss=1.4104 val_auc=0.8266
model=transformerconv top_k=100 fold=5 epoch=80 loss=1.2500 val_auc=0.8293
model=transformerconv top_k=100 fold=5 epoch=81 loss=1.1460 val_auc=0.8307
transformerconv top_k=100 fold=5: early stopping at epoch 81
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718759 edges

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=100 fold=6 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718481 edges
model=transformerconv top_k=100 fold=6 epoch=0 loss=8.3956 val_auc=0.6644
model=transformerconv top_k=100 fold=6 epoch=1 loss=12.2259 val_auc=0.7501
model=transformerconv top_k=100 fold=6 epoch=2 loss=7.2195 val_auc=0.7649
model=transformerconv top_k=100 fold=6 epoch=3 loss=4.2164 val_auc=0.7739
model=transformerconv top_k=100 fold=6 epoch=4 loss=5.4912 val_auc=0.7777
model=transformerconv top_k=100 fold=6 epoch=5 loss=4.5965 val_auc=0.7790
model=transformerconv top_k=100 fold=6 epoch=6 loss=5.0909 val_auc=0.7802
model=transformerconv top_k=100 fold=6 epoch=7 loss=5.0794 val_auc=0.7797
model=transformerconv top_k=100 fold=6 epoch=8 loss=4.4021 val_auc=0.7805
model=transformerconv top_k=100 fold=6 epoch=9 loss=4.0596 val_auc=0.7820
model=transformerconv top_k=100 fold=6 epoch=10 loss=5.0050 val_auc=0.7844
model=transformerconv top_k=100 fold=6 epoch=11 loss=3.3041 val_auc=0.7876
model=transformerconv top_k=100 fold=6 epoch=12 loss=3.8441 val_auc=0.7911
model=transformerconv top_k=100 fold=6 epoch=13 loss=5.9488 val_auc=0.7942
model=transformerconv top_k=100 fold=6 epoch=14 loss=4.3994 val_auc=0.7968
model=transformerconv top_k=100 fold=6 epoch=15 loss=3.3877 val_auc=0.7994
model=transformerconv top_k=100 fold=6 epoch=16 loss=3.6005 val_auc=0.8018
model=transformerconv top_k=100 fold=6 epoch=17 loss=4.4164 val_auc=0.8037
model=transformerconv top_k=100 fold=6 epoch=18 loss=5.2261 val_auc=0.8048
model=transformerconv top_k=100 fold=6 epoch=19 loss=2.9587 val_auc=0.8053
model=transformerconv top_k=100 fold=6 epoch=20 loss=3.8278 val_auc=0.8060
model=transformerconv top_k=100 fold=6 epoch=21 loss=3.2087 val_auc=0.8070
model=transformerconv top_k=100 fold=6 epoch=22 loss=3.0007 val_auc=0.8081
model=transformerconv top_k=100 fold=6 epoch=23 loss=2.3789 val_auc=0.8093
model=transformerconv top_k=100 fold=6 epoch=24 loss=2.5027 val_auc=0.8102
model=transformerconv top_k=100 fold=6 epoch=25 loss=2.5688 val_auc=0.8108
model=transformerconv top_k=100 fold=6 epoch=26 loss=2.9050 val_auc=0.8117
model=transformerconv top_k=100 fold=6 epoch=27 loss=2.2394 val_auc=0.8131
model=transformerconv top_k=100 fold=6 epoch=28 loss=2.1097 val_auc=0.8148
model=transformerconv top_k=100 fold=6 epoch=29 loss=2.4290 val_auc=0.8162
model=transformerconv top_k=100 fold=6 epoch=30 loss=2.1699 val_auc=0.8173
model=transformerconv top_k=100 fold=6 epoch=31 loss=2.1822 val_auc=0.8182
model=transformerconv top_k=100 fold=6 epoch=32 loss=2.5506 val_auc=0.8192
model=transformerconv top_k=100 fold=6 epoch=33 loss=2.6432 val_auc=0.8203
model=transformerconv top_k=100 fold=6 epoch=34 loss=2.1495 val_auc=0.8212
model=transformerconv top_k=100 fold=6 epoch=35 loss=2.1120 val_auc=0.8218
model=transformerconv top_k=100 fold=6 epoch=36 loss=2.1404 val_auc=0.8220
model=transformerconv top_k=100 fold=6 epoch=37 loss=2.1427 val_auc=0.8221
model=transformerconv top_k=100 fold=6 epoch=38 loss=1.8669 val_auc=0.8221
model=transformerconv top_k=100 fold=6 epoch=39 loss=1.8671 val_auc=0.8222
model=transformerconv top_k=100 fold=6 epoch=40 loss=1.7720 val_auc=0.8226
model=transformerconv top_k=100 fold=6 epoch=41 loss=2.0303 val_auc=0.8232
model=transformerconv top_k=100 fold=6 epoch=42 loss=1.9801 val_auc=0.8239
model=transformerconv top_k=100 fold=6 epoch=43 loss=1.6964 val_auc=0.8249
model=transformerconv top_k=100 fold=6 epoch=44 loss=1.6619 val_auc=0.8257
model=transformerconv top_k=100 fold=6 epoch=45 loss=1.6227 val_auc=0.8263
model=transformerconv top_k=100 fold=6 epoch=46 loss=1.5787 val_auc=0.8267
model=transformerconv top_k=100 fold=6 epoch=47 loss=1.7015 val_auc=0.8270
model=transformerconv top_k=100 fold=6 epoch=48 loss=1.7234 val_auc=0.8269
model=transformerconv top_k=100 fold=6 epoch=49 loss=1.5560 val_auc=0.8272
model=transformerconv top_k=100 fold=6 epoch=50 loss=2.1455 val_auc=0.8274
model=transformerconv top_k=100 fold=6 epoch=51 loss=2.5783 val_auc=0.8275
model=transformerconv top_k=100 fold=6 epoch=52 loss=2.1638 val_auc=0.8273
model=transformerconv top_k=100 fold=6 epoch=53 loss=2.0016 val_auc=0.8268
model=transformerconv top_k=100 fold=6 epoch=54 loss=1.7963 val_auc=0.8267
model=transformerconv top_k=100 fold=6 epoch=55 loss=2.3123 val_auc=0.8267
model=transformerconv top_k=100 fold=6 epoch=56 loss=2.0073 val_auc=0.8272
model=transformerconv top_k=100 fold=6 epoch=57 loss=1.6655 val_auc=0.8279
model=transformerconv top_k=100 fold=6 epoch=58 loss=1.6560 val_auc=0.8282
model=transformerconv top_k=100 fold=6 epoch=59 loss=1.9877 val_auc=0.8281
model=transformerconv top_k=100 fold=6 epoch=60 loss=1.6554 val_auc=0.8279
model=transformerconv top_k=100 fold=6 epoch=61 loss=1.4402 val_auc=0.8283
model=transformerconv top_k=100 fold=6 epoch=62 loss=1.4407 val_auc=0.8297
model=transformerconv top_k=100 fold=6 epoch=63 loss=1.3860 val_auc=0.8315
model=transformerconv top_k=100 fold=6 epoch=64 loss=1.3604 val_auc=0.8340
model=transformerconv top_k=100 fold=6 epoch=65 loss=1.2677 val_auc=0.8359
model=transformerconv top_k=100 fold=6 epoch=66 loss=1.5920 val_auc=0.8357
model=transformerconv top_k=100 fold=6 epoch=67 loss=1.5935 val_auc=0.8337
model=transformerconv top_k=100 fold=6 epoch=68 loss=1.6350 val_auc=0.8314
model=transformerconv top_k=100 fold=6 epoch=69 loss=1.5764 val_auc=0.8302
model=transformerconv top_k=100 fold=6 epoch=70 loss=1.6424 val_auc=0.8300
model=transformerconv top_k=100 fold=6 epoch=71 loss=1.7858 val_auc=0.8301
model=transformerconv top_k=100 fold=6 epoch=72 loss=1.4609 val_auc=0.8302
model=transformerconv top_k=100 fold=6 epoch=73 loss=1.6696 val_auc=0.8303
model=transformerconv top_k=100 fold=6 epoch=74 loss=1.5518 val_auc=0.8307
model=transformerconv top_k=100 fold=6 epoch=75 loss=1.4565 val_auc=0.8313
model=transformerconv top_k=100 fold=6 epoch=76 loss=1.6589 val_auc=0.8312
model=transformerconv top_k=100 fold=6 epoch=77 loss=1.6454 val_auc=0.8305
transformerconv top_k=100 fold=6: early stopping at epoch 77
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718481 edges

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=100 fold=7 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719141 edges
model=transformerconv top_k=100 fold=7 epoch=0 loss=10.5359 val_auc=0.5000
model=transformerconv top_k=100 fold=7 epoch=1 loss=29.2269 val_auc=0.5006
model=transformerconv top_k=100 fold=7 epoch=2 loss=21.8794 val_auc=0.6584
model=transformerconv top_k=100 fold=7 epoch=3 loss=8.4226 val_auc=0.6705
model=transformerconv top_k=100 fold=7 epoch=4 loss=6.0751 val_auc=0.7025
model=transformerconv top_k=100 fold=7 epoch=5 loss=7.8144 val_auc=0.7179
model=transformerconv top_k=100 fold=7 epoch=6 loss=7.5401 val_auc=0.7270
model=transformerconv top_k=100 fold=7 epoch=7 loss=5.5585 val_auc=0.7414
model=transformerconv top_k=100 fold=7 epoch=8 loss=6.0843 val_auc=0.7535
model=transformerconv top_k=100 fold=7 epoch=9 loss=5.9201 val_auc=0.7605
model=transformerconv top_k=100 fold=7 epoch=10 loss=5.7445 val_auc=0.7642
model=transformerconv top_k=100 fold=7 epoch=11 loss=5.2629 val_auc=0.7657
model=transformerconv top_k=100 fold=7 epoch=12 loss=5.2465 val_auc=0.7686
model=transformerconv top_k=100 fold=7 epoch=13 loss=5.5974 val_auc=0.7719
model=transformerconv top_k=100 fold=7 epoch=14 loss=4.1154 val_auc=0.7760
model=transformerconv top_k=100 fold=7 epoch=15 loss=3.5470 val_auc=0.7799
model=transformerconv top_k=100 fold=7 epoch=16 loss=3.7164 val_auc=0.7837
model=transformerconv top_k=100 fold=7 epoch=17 loss=3.8169 val_auc=0.7873
model=transformerconv top_k=100 fold=7 epoch=18 loss=3.3234 val_auc=0.7912
model=transformerconv top_k=100 fold=7 epoch=19 loss=2.9522 val_auc=0.7942
model=transformerconv top_k=100 fold=7 epoch=20 loss=3.7376 val_auc=0.7953
model=transformerconv top_k=100 fold=7 epoch=21 loss=2.6453 val_auc=0.7971
model=transformerconv top_k=100 fold=7 epoch=22 loss=2.9429 val_auc=0.7997
model=transformerconv top_k=100 fold=7 epoch=23 loss=3.4175 val_auc=0.8024
model=transformerconv top_k=100 fold=7 epoch=24 loss=3.3525 val_auc=0.8048
model=transformerconv top_k=100 fold=7 epoch=25 loss=3.2565 val_auc=0.8063
model=transformerconv top_k=100 fold=7 epoch=26 loss=2.9551 val_auc=0.8075
model=transformerconv top_k=100 fold=7 epoch=27 loss=2.6824 val_auc=0.8083
model=transformerconv top_k=100 fold=7 epoch=28 loss=3.0598 val_auc=0.8089
model=transformerconv top_k=100 fold=7 epoch=29 loss=3.2313 val_auc=0.8090
model=transformerconv top_k=100 fold=7 epoch=30 loss=2.5612 val_auc=0.8091
model=transformerconv top_k=100 fold=7 epoch=31 loss=2.3426 val_auc=0.8098
model=transformerconv top_k=100 fold=7 epoch=32 loss=2.7246 val_auc=0.8104
model=transformerconv top_k=100 fold=7 epoch=33 loss=2.4868 val_auc=0.8109
model=transformerconv top_k=100 fold=7 epoch=34 loss=2.2381 val_auc=0.8118
model=transformerconv top_k=100 fold=7 epoch=35 loss=2.3249 val_auc=0.8132
model=transformerconv top_k=100 fold=7 epoch=36 loss=2.0831 val_auc=0.8148
model=transformerconv top_k=100 fold=7 epoch=37 loss=2.3248 val_auc=0.8161
model=transformerconv top_k=100 fold=7 epoch=38 loss=2.3141 val_auc=0.8169
model=transformerconv top_k=100 fold=7 epoch=39 loss=2.2541 val_auc=0.8174
model=transformerconv top_k=100 fold=7 epoch=40 loss=2.2925 val_auc=0.8174
model=transformerconv top_k=100 fold=7 epoch=41 loss=1.8075 val_auc=0.8176
model=transformerconv top_k=100 fold=7 epoch=42 loss=2.1582 val_auc=0.8178
model=transformerconv top_k=100 fold=7 epoch=43 loss=1.7483 val_auc=0.8179
model=transformerconv top_k=100 fold=7 epoch=44 loss=1.9356 val_auc=0.8181
model=transformerconv top_k=100 fold=7 epoch=45 loss=1.9046 val_auc=0.8183
model=transformerconv top_k=100 fold=7 epoch=46 loss=1.7290 val_auc=0.8183
model=transformerconv top_k=100 fold=7 epoch=47 loss=1.6741 val_auc=0.8188
model=transformerconv top_k=100 fold=7 epoch=48 loss=2.3204 val_auc=0.8192
model=transformerconv top_k=100 fold=7 epoch=49 loss=1.9002 val_auc=0.8195
model=transformerconv top_k=100 fold=7 epoch=50 loss=2.1658 val_auc=0.8199
model=transformerconv top_k=100 fold=7 epoch=51 loss=1.6148 val_auc=0.8202
model=transformerconv top_k=100 fold=7 epoch=52 loss=1.9045 val_auc=0.8201
model=transformerconv top_k=100 fold=7 epoch=53 loss=2.3371 val_auc=0.8199
model=transformerconv top_k=100 fold=7 epoch=54 loss=2.2153 val_auc=0.8196
model=transformerconv top_k=100 fold=7 epoch=55 loss=1.7986 val_auc=0.8196
model=transformerconv top_k=100 fold=7 epoch=56 loss=1.5238 val_auc=0.8196
model=transformerconv top_k=100 fold=7 epoch=57 loss=1.8890 val_auc=0.8196
model=transformerconv top_k=100 fold=7 epoch=58 loss=2.6591 val_auc=0.8196
model=transformerconv top_k=100 fold=7 epoch=59 loss=2.4588 val_auc=0.8198
model=transformerconv top_k=100 fold=7 epoch=60 loss=2.0969 val_auc=0.8202
model=transformerconv top_k=100 fold=7 epoch=61 loss=1.6595 val_auc=0.8206
model=transformerconv top_k=100 fold=7 epoch=62 loss=1.6354 val_auc=0.8211
model=transformerconv top_k=100 fold=7 epoch=63 loss=1.8210 val_auc=0.8215
model=transformerconv top_k=100 fold=7 epoch=64 loss=1.6319 val_auc=0.8218
model=transformerconv top_k=100 fold=7 epoch=65 loss=1.5636 val_auc=0.8222
model=transformerconv top_k=100 fold=7 epoch=66 loss=1.4770 val_auc=0.8222
model=transformerconv top_k=100 fold=7 epoch=67 loss=1.8052 val_auc=0.8222
model=transformerconv top_k=100 fold=7 epoch=68 loss=2.2322 val_auc=0.8221
model=transformerconv top_k=100 fold=7 epoch=69 loss=2.0849 val_auc=0.8223
model=transformerconv top_k=100 fold=7 epoch=70 loss=2.0087 val_auc=0.8227
model=transformerconv top_k=100 fold=7 epoch=71 loss=1.5508 val_auc=0.8228
model=transformerconv top_k=100 fold=7 epoch=72 loss=1.6414 val_auc=0.8227
model=transformerconv top_k=100 fold=7 epoch=73 loss=1.6330 val_auc=0.8227
model=transformerconv top_k=100 fold=7 epoch=74 loss=1.6720 val_auc=0.8228
model=transformerconv top_k=100 fold=7 epoch=75 loss=1.5687 val_auc=0.8227
model=transformerconv top_k=100 fold=7 epoch=76 loss=1.3968 val_auc=0.8228
model=transformerconv top_k=100 fold=7 epoch=77 loss=1.4098 val_auc=0.8230
model=transformerconv top_k=100 fold=7 epoch=78 loss=1.3412 val_auc=0.8235
model=transformerconv top_k=100 fold=7 epoch=79 loss=1.4595 val_auc=0.8242
model=transformerconv top_k=100 fold=7 epoch=80 loss=1.5025 val_auc=0.8247
model=transformerconv top_k=100 fold=7 epoch=81 loss=1.6440 val_auc=0.8252
model=transformerconv top_k=100 fold=7 epoch=82 loss=1.4057 val_auc=0.8253
model=transformerconv top_k=100 fold=7 epoch=83 loss=1.5096 val_auc=0.8254
model=transformerconv top_k=100 fold=7 epoch=84 loss=1.6801 val_auc=0.8257
model=transformerconv top_k=100 fold=7 epoch=85 loss=1.7596 val_auc=0.8262
model=transformerconv top_k=100 fold=7 epoch=86 loss=1.2552 val_auc=0.8267
model=transformerconv top_k=100 fold=7 epoch=87 loss=1.3447 val_auc=0.8271
model=transformerconv top_k=100 fold=7 epoch=88 loss=1.4494 val_auc=0.8275
model=transformerconv top_k=100 fold=7 epoch=89 loss=1.6289 val_auc=0.8278
model=transformerconv top_k=100 fold=7 epoch=90 loss=1.2911 val_auc=0.8279
model=transformerconv top_k=100 fold=7 epoch=91 loss=1.2300 val_auc=0.8281
model=transformerconv top_k=100 fold=7 epoch=92 loss=1.3431 val_auc=0.8284
model=transformerconv top_k=100 fold=7 epoch=93 loss=1.2998 val_auc=0.8287
model=transformerconv top_k=100 fold=7 epoch=94 loss=1.4007 val_auc=0.8287
model=transformerconv top_k=100 fold=7 epoch=95 loss=1.2070 val_auc=0.8286
model=transformerconv top_k=100 fold=7 epoch=96 loss=1.2431 val_auc=0.8285
model=transformerconv top_k=100 fold=7 epoch=97 loss=1.1956 val_auc=0.8287
model=transformerconv top_k=100 fold=7 epoch=98 loss=1.2598 val_auc=0.8290
model=transformerconv top_k=100 fold=7 epoch=99 loss=1.1473 val_auc=0.8299
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719141 edges

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=100 fold=8 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718578 edges
model=transformerconv top_k=100 fold=8 epoch=0 loss=14.3052 val_auc=0.5887
model=transformerconv top_k=100 fold=8 epoch=1 loss=14.0563 val_auc=0.6583
model=transformerconv top_k=100 fold=8 epoch=2 loss=8.1670 val_auc=0.6971
model=transformerconv top_k=100 fold=8 epoch=3 loss=3.9034 val_auc=0.7368
model=transformerconv top_k=100 fold=8 epoch=4 loss=9.2266 val_auc=0.7481
model=transformerconv top_k=100 fold=8 epoch=5 loss=9.7459 val_auc=0.7559
model=transformerconv top_k=100 fold=8 epoch=6 loss=5.7725 val_auc=0.7609
model=transformerconv top_k=100 fold=8 epoch=7 loss=4.2001 val_auc=0.7633
model=transformerconv top_k=100 fold=8 epoch=8 loss=4.9964 val_auc=0.7659
model=transformerconv top_k=100 fold=8 epoch=9 loss=7.3598 val_auc=0.7681
model=transformerconv top_k=100 fold=8 epoch=10 loss=7.0408 val_auc=0.7696
model=transformerconv top_k=100 fold=8 epoch=11 loss=5.1249 val_auc=0.7702
model=transformerconv top_k=100 fold=8 epoch=12 loss=3.3144 val_auc=0.7671
model=transformerconv top_k=100 fold=8 epoch=13 loss=3.1304 val_auc=0.7677
model=transformerconv top_k=100 fold=8 epoch=14 loss=4.5127 val_auc=0.7686
model=transformerconv top_k=100 fold=8 epoch=15 loss=4.1257 val_auc=0.7697
model=transformerconv top_k=100 fold=8 epoch=16 loss=3.9607 val_auc=0.7708
model=transformerconv top_k=100 fold=8 epoch=17 loss=3.0607 val_auc=0.7725
model=transformerconv top_k=100 fold=8 epoch=18 loss=3.5864 val_auc=0.7734
model=transformerconv top_k=100 fold=8 epoch=19 loss=4.0637 val_auc=0.7738
model=transformerconv top_k=100 fold=8 epoch=20 loss=4.0053 val_auc=0.7741
model=transformerconv top_k=100 fold=8 epoch=21 loss=3.2668 val_auc=0.7747
model=transformerconv top_k=100 fold=8 epoch=22 loss=2.6465 val_auc=0.7764
model=transformerconv top_k=100 fold=8 epoch=23 loss=2.8270 val_auc=0.7775
model=transformerconv top_k=100 fold=8 epoch=24 loss=2.8944 val_auc=0.7787
model=transformerconv top_k=100 fold=8 epoch=25 loss=2.5104 val_auc=0.7800
model=transformerconv top_k=100 fold=8 epoch=26 loss=2.4543 val_auc=0.7808
model=transformerconv top_k=100 fold=8 epoch=27 loss=2.5336 val_auc=0.7804
model=transformerconv top_k=100 fold=8 epoch=28 loss=2.5639 val_auc=0.7808
model=transformerconv top_k=100 fold=8 epoch=29 loss=2.6131 val_auc=0.7815
model=transformerconv top_k=100 fold=8 epoch=30 loss=2.7226 val_auc=0.7828
model=transformerconv top_k=100 fold=8 epoch=31 loss=2.2636 val_auc=0.7833
model=transformerconv top_k=100 fold=8 epoch=32 loss=2.3038 val_auc=0.7834
model=transformerconv top_k=100 fold=8 epoch=33 loss=2.3236 val_auc=0.7833
model=transformerconv top_k=100 fold=8 epoch=34 loss=1.9565 val_auc=0.7841
model=transformerconv top_k=100 fold=8 epoch=35 loss=1.8980 val_auc=0.7861
model=transformerconv top_k=100 fold=8 epoch=36 loss=1.8486 val_auc=0.7880
model=transformerconv top_k=100 fold=8 epoch=37 loss=1.8973 val_auc=0.7890
model=transformerconv top_k=100 fold=8 epoch=38 loss=1.8440 val_auc=0.7890
model=transformerconv top_k=100 fold=8 epoch=39 loss=1.5969 val_auc=0.7903
model=transformerconv top_k=100 fold=8 epoch=40 loss=1.8985 val_auc=0.7924
model=transformerconv top_k=100 fold=8 epoch=41 loss=1.7621 val_auc=0.7933
model=transformerconv top_k=100 fold=8 epoch=42 loss=1.6015 val_auc=0.7936
model=transformerconv top_k=100 fold=8 epoch=43 loss=1.6333 val_auc=0.7943
model=transformerconv top_k=100 fold=8 epoch=44 loss=1.6401 val_auc=0.7952
model=transformerconv top_k=100 fold=8 epoch=45 loss=1.6349 val_auc=0.7957
model=transformerconv top_k=100 fold=8 epoch=46 loss=1.6355 val_auc=0.7962
model=transformerconv top_k=100 fold=8 epoch=47 loss=1.5910 val_auc=0.7961
model=transformerconv top_k=100 fold=8 epoch=48 loss=1.4825 val_auc=0.7961
model=transformerconv top_k=100 fold=8 epoch=49 loss=1.4628 val_auc=0.7963
model=transformerconv top_k=100 fold=8 epoch=50 loss=1.4333 val_auc=0.7970
model=transformerconv top_k=100 fold=8 epoch=51 loss=1.4610 val_auc=0.7980
model=transformerconv top_k=100 fold=8 epoch=52 loss=1.4488 val_auc=0.7993
model=transformerconv top_k=100 fold=8 epoch=53 loss=1.4146 val_auc=0.8002
model=transformerconv top_k=100 fold=8 epoch=54 loss=1.5474 val_auc=0.8009
model=transformerconv top_k=100 fold=8 epoch=55 loss=1.4052 val_auc=0.8012
model=transformerconv top_k=100 fold=8 epoch=56 loss=1.3736 val_auc=0.8010
model=transformerconv top_k=100 fold=8 epoch=57 loss=1.4238 val_auc=0.8010
model=transformerconv top_k=100 fold=8 epoch=58 loss=1.2827 val_auc=0.8019
model=transformerconv top_k=100 fold=8 epoch=59 loss=1.3106 val_auc=0.8028
model=transformerconv top_k=100 fold=8 epoch=60 loss=1.2261 val_auc=0.8042
model=transformerconv top_k=100 fold=8 epoch=61 loss=1.2158 val_auc=0.8053
model=transformerconv top_k=100 fold=8 epoch=62 loss=1.3598 val_auc=0.8056
model=transformerconv top_k=100 fold=8 epoch=63 loss=1.2953 val_auc=0.8047
model=transformerconv top_k=100 fold=8 epoch=64 loss=1.1226 val_auc=0.8023
model=transformerconv top_k=100 fold=8 epoch=65 loss=1.4179 val_auc=0.8019
model=transformerconv top_k=100 fold=8 epoch=66 loss=1.2937 val_auc=0.8032
model=transformerconv top_k=100 fold=8 epoch=67 loss=1.3966 val_auc=0.8060
model=transformerconv top_k=100 fold=8 epoch=68 loss=1.1646 val_auc=0.8070
model=transformerconv top_k=100 fold=8 epoch=69 loss=1.3517 val_auc=0.8072
model=transformerconv top_k=100 fold=8 epoch=70 loss=1.3959 val_auc=0.8071
model=transformerconv top_k=100 fold=8 epoch=71 loss=1.2245 val_auc=0.8063
model=transformerconv top_k=100 fold=8 epoch=72 loss=1.1934 val_auc=0.8033
model=transformerconv top_k=100 fold=8 epoch=73 loss=1.2823 val_auc=0.8008
model=transformerconv top_k=100 fold=8 epoch=74 loss=1.6352 val_auc=0.8008
model=transformerconv top_k=100 fold=8 epoch=75 loss=1.5884 val_auc=0.8026
model=transformerconv top_k=100 fold=8 epoch=76 loss=1.5189 val_auc=0.8053
model=transformerconv top_k=100 fold=8 epoch=77 loss=1.2882 val_auc=0.8071
model=transformerconv top_k=100 fold=8 epoch=78 loss=1.1677 val_auc=0.8078
model=transformerconv top_k=100 fold=8 epoch=79 loss=1.2596 val_auc=0.8082
model=transformerconv top_k=100 fold=8 epoch=80 loss=1.3028 val_auc=0.8080
model=transformerconv top_k=100 fold=8 epoch=81 loss=1.1701 val_auc=0.8072
model=transformerconv top_k=100 fold=8 epoch=82 loss=1.0815 val_auc=0.8039
model=transformerconv top_k=100 fold=8 epoch=83 loss=1.2359 val_auc=0.7998
model=transformerconv top_k=100 fold=8 epoch=84 loss=1.3516 val_auc=0.7983
model=transformerconv top_k=100 fold=8 epoch=85 loss=1.4212 val_auc=0.7975
model=transformerconv top_k=100 fold=8 epoch=86 loss=1.3086 val_auc=0.7842
model=transformerconv top_k=100 fold=8 epoch=87 loss=1.1544 val_auc=0.7767
model=transformerconv top_k=100 fold=8 epoch=88 loss=1.4262 val_auc=0.7875
model=transformerconv top_k=100 fold=8 epoch=89 loss=1.3289 val_auc=0.8009
model=transformerconv top_k=100 fold=8 epoch=90 loss=1.2784 val_auc=0.8010
model=transformerconv top_k=100 fold=8 epoch=91 loss=1.1154 val_auc=0.8007
transformerconv top_k=100 fold=8: early stopping at epoch 91
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718578 edges

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=100 fold=9 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718994 edges
model=transformerconv top_k=100 fold=9 epoch=0 loss=6.5697 val_auc=0.5002
model=transformerconv top_k=100 fold=9 epoch=1 loss=27.1341 val_auc=0.5529
model=transformerconv top_k=100 fold=9 epoch=2 loss=18.7192 val_auc=0.7686
model=transformerconv top_k=100 fold=9 epoch=3 loss=6.9055 val_auc=0.7665
model=transformerconv top_k=100 fold=9 epoch=4 loss=9.2386 val_auc=0.7651
model=transformerconv top_k=100 fold=9 epoch=5 loss=12.4336 val_auc=0.7687
model=transformerconv top_k=100 fold=9 epoch=6 loss=7.4682 val_auc=0.7703
model=transformerconv top_k=100 fold=9 epoch=7 loss=5.8176 val_auc=0.7586
model=transformerconv top_k=100 fold=9 epoch=8 loss=4.3933 val_auc=0.7541
model=transformerconv top_k=100 fold=9 epoch=9 loss=6.5053 val_auc=0.7586
model=transformerconv top_k=100 fold=9 epoch=10 loss=6.0005 val_auc=0.7663
model=transformerconv top_k=100 fold=9 epoch=11 loss=4.5981 val_auc=0.7727
model=transformerconv top_k=100 fold=9 epoch=12 loss=3.7776 val_auc=0.7753
model=transformerconv top_k=100 fold=9 epoch=13 loss=4.5211 val_auc=0.7769
model=transformerconv top_k=100 fold=9 epoch=14 loss=4.1929 val_auc=0.7797
model=transformerconv top_k=100 fold=9 epoch=15 loss=4.1368 val_auc=0.7832
model=transformerconv top_k=100 fold=9 epoch=16 loss=4.2658 val_auc=0.7864
model=transformerconv top_k=100 fold=9 epoch=17 loss=3.8901 val_auc=0.7884
model=transformerconv top_k=100 fold=9 epoch=18 loss=3.4530 val_auc=0.7907
model=transformerconv top_k=100 fold=9 epoch=19 loss=3.9096 val_auc=0.7931
model=transformerconv top_k=100 fold=9 epoch=20 loss=3.4014 val_auc=0.7943
model=transformerconv top_k=100 fold=9 epoch=21 loss=3.6416 val_auc=0.7950
model=transformerconv top_k=100 fold=9 epoch=22 loss=3.6216 val_auc=0.7963
model=transformerconv top_k=100 fold=9 epoch=23 loss=3.0542 val_auc=0.7971
model=transformerconv top_k=100 fold=9 epoch=24 loss=3.0815 val_auc=0.7983
model=transformerconv top_k=100 fold=9 epoch=25 loss=2.6966 val_auc=0.7996
model=transformerconv top_k=100 fold=9 epoch=26 loss=3.1451 val_auc=0.8002
model=transformerconv top_k=100 fold=9 epoch=27 loss=2.7250 val_auc=0.8010
model=transformerconv top_k=100 fold=9 epoch=28 loss=2.9519 val_auc=0.8022
model=transformerconv top_k=100 fold=9 epoch=29 loss=2.8999 val_auc=0.8033
model=transformerconv top_k=100 fold=9 epoch=30 loss=2.6177 val_auc=0.8045
model=transformerconv top_k=100 fold=9 epoch=31 loss=2.7906 val_auc=0.8058
model=transformerconv top_k=100 fold=9 epoch=32 loss=2.5966 val_auc=0.8070
model=transformerconv top_k=100 fold=9 epoch=33 loss=2.1664 val_auc=0.8082
model=transformerconv top_k=100 fold=9 epoch=34 loss=2.1112 val_auc=0.8099
model=transformerconv top_k=100 fold=9 epoch=35 loss=2.2580 val_auc=0.8113
model=transformerconv top_k=100 fold=9 epoch=36 loss=2.5796 val_auc=0.8120
model=transformerconv top_k=100 fold=9 epoch=37 loss=2.3930 val_auc=0.8124
model=transformerconv top_k=100 fold=9 epoch=38 loss=1.9035 val_auc=0.8126
model=transformerconv top_k=100 fold=9 epoch=39 loss=2.0092 val_auc=0.8123
model=transformerconv top_k=100 fold=9 epoch=40 loss=2.4925 val_auc=0.8123
model=transformerconv top_k=100 fold=9 epoch=41 loss=2.2358 val_auc=0.8123
model=transformerconv top_k=100 fold=9 epoch=42 loss=1.8065 val_auc=0.8121
model=transformerconv top_k=100 fold=9 epoch=43 loss=2.7772 val_auc=0.8116
model=transformerconv top_k=100 fold=9 epoch=44 loss=2.1530 val_auc=0.8111
model=transformerconv top_k=100 fold=9 epoch=45 loss=1.8516 val_auc=0.8108
model=transformerconv top_k=100 fold=9 epoch=46 loss=1.9180 val_auc=0.8117
model=transformerconv top_k=100 fold=9 epoch=47 loss=1.8949 val_auc=0.8125
model=transformerconv top_k=100 fold=9 epoch=48 loss=1.9269 val_auc=0.8128
model=transformerconv top_k=100 fold=9 epoch=49 loss=1.7576 val_auc=0.8128
model=transformerconv top_k=100 fold=9 epoch=50 loss=1.5511 val_auc=0.8131
model=transformerconv top_k=100 fold=9 epoch=51 loss=2.2595 val_auc=0.8136
model=transformerconv top_k=100 fold=9 epoch=52 loss=1.9887 val_auc=0.8144
model=transformerconv top_k=100 fold=9 epoch=53 loss=1.4707 val_auc=0.8153
model=transformerconv top_k=100 fold=9 epoch=54 loss=1.4226 val_auc=0.8162
model=transformerconv top_k=100 fold=9 epoch=55 loss=1.5432 val_auc=0.8167
model=transformerconv top_k=100 fold=9 epoch=56 loss=1.3809 val_auc=0.8166
model=transformerconv top_k=100 fold=9 epoch=57 loss=1.4991 val_auc=0.8168
model=transformerconv top_k=100 fold=9 epoch=58 loss=1.2493 val_auc=0.8173
model=transformerconv top_k=100 fold=9 epoch=59 loss=1.5207 val_auc=0.8181
model=transformerconv top_k=100 fold=9 epoch=60 loss=1.3446 val_auc=0.8187
model=transformerconv top_k=100 fold=9 epoch=61 loss=1.3463 val_auc=0.8189
model=transformerconv top_k=100 fold=9 epoch=62 loss=1.2179 val_auc=0.8194
model=transformerconv top_k=100 fold=9 epoch=63 loss=1.5364 val_auc=0.8201
model=transformerconv top_k=100 fold=9 epoch=64 loss=2.2816 val_auc=0.8209
model=transformerconv top_k=100 fold=9 epoch=65 loss=1.9049 val_auc=0.8215
model=transformerconv top_k=100 fold=9 epoch=66 loss=1.6732 val_auc=0.8217
model=transformerconv top_k=100 fold=9 epoch=67 loss=1.3772 val_auc=0.8217
model=transformerconv top_k=100 fold=9 epoch=68 loss=1.3830 val_auc=0.8218
model=transformerconv top_k=100 fold=9 epoch=69 loss=1.4319 val_auc=0.8217
model=transformerconv top_k=100 fold=9 epoch=70 loss=1.3357 val_auc=0.8215
model=transformerconv top_k=100 fold=9 epoch=71 loss=1.2192 val_auc=0.8214
model=transformerconv top_k=100 fold=9 epoch=72 loss=1.3581 val_auc=0.8213
model=transformerconv top_k=100 fold=9 epoch=73 loss=1.1058 val_auc=0.8213
model=transformerconv top_k=100 fold=9 epoch=74 loss=1.1671 val_auc=0.8213
model=transformerconv top_k=100 fold=9 epoch=75 loss=1.1924 val_auc=0.8215
model=transformerconv top_k=100 fold=9 epoch=76 loss=1.0775 val_auc=0.8217
model=transformerconv top_k=100 fold=9 epoch=77 loss=1.0567 val_auc=0.8224
model=transformerconv top_k=100 fold=9 epoch=78 loss=1.1042 val_auc=0.8229
model=transformerconv top_k=100 fold=9 epoch=79 loss=1.0210 val_auc=0.8230
model=transformerconv top_k=100 fold=9 epoch=80 loss=1.1655 val_auc=0.8227
model=transformerconv top_k=100 fold=9 epoch=81 loss=1.0899 val_auc=0.8229
model=transformerconv top_k=100 fold=9 epoch=82 loss=1.0644 val_auc=0.8232
model=transformerconv top_k=100 fold=9 epoch=83 loss=1.1800 val_auc=0.8238
model=transformerconv top_k=100 fold=9 epoch=84 loss=1.2124 val_auc=0.8247
model=transformerconv top_k=100 fold=9 epoch=85 loss=1.0713 val_auc=0.8255
model=transformerconv top_k=100 fold=9 epoch=86 loss=1.1329 val_auc=0.8257
model=transformerconv top_k=100 fold=9 epoch=87 loss=1.1483 val_auc=0.8260
model=transformerconv top_k=100 fold=9 epoch=88 loss=1.1475 val_auc=0.8263
model=transformerconv top_k=100 fold=9 epoch=89 loss=1.0623 val_auc=0.8263
model=transformerconv top_k=100 fold=9 epoch=90 loss=1.0185 val_auc=0.8261
model=transformerconv top_k=100 fold=9 epoch=91 loss=1.0431 val_auc=0.8252
model=transformerconv top_k=100 fold=9 epoch=92 loss=1.0938 val_auc=0.8243
model=transformerconv top_k=100 fold=9 epoch=93 loss=1.0797 val_auc=0.8245
model=transformerconv top_k=100 fold=9 epoch=94 loss=1.0401 val_auc=0.8262
model=transformerconv top_k=100 fold=9 epoch=95 loss=1.0144 val_auc=0.8272
model=transformerconv top_k=100 fold=9 epoch=96 loss=1.1813 val_auc=0.8275
model=transformerconv top_k=100 fold=9 epoch=97 loss=1.0541 val_auc=0.8273
model=transformerconv top_k=100 fold=9 epoch=98 loss=1.0346 val_auc=0.8275
model=transformerconv top_k=100 fold=9 epoch=99 loss=1.0931 val_auc=0.8286
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718994 edges

query FAISS top_k=100:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=100:   0%|          | 0/35 [00:00<?, ?it/s]

######## Model=transformerconv top_k=200 ########

===== Model=transformerconv top_k=200 fold=0 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718731 edges
model=transformerconv top_k=200 fold=0 epoch=0 loss=9.7517 val_auc=0.5000
model=transformerconv top_k=200 fold=0 epoch=1 loss=33.7280 val_auc=0.5034
model=transformerconv top_k=200 fold=0 epoch=2 loss=25.4764 val_auc=0.7340
model=transformerconv top_k=200 fold=0 epoch=3 loss=12.0526 val_auc=0.7518
model=transformerconv top_k=200 fold=0 epoch=4 loss=5.8984 val_auc=0.7543
model=transformerconv top_k=200 fold=0 epoch=5 loss=7.0589 val_auc=0.7609
model=transformerconv top_k=200 fold=0 epoch=6 loss=6.5931 val_auc=0.7660
model=transformerconv top_k=200 fold=0 epoch=7 loss=5.0314 val_auc=0.7707
model=transformerconv top_k=200 fold=0 epoch=8 loss=4.7607 val_auc=0.7758
model=transformerconv top_k=200 fold=0 epoch=9 loss=4.5623 val_auc=0.7800
model=transformerconv top_k=200 fold=0 epoch=10 loss=3.8802 val_auc=0.7829
model=transformerconv top_k=200 fold=0 epoch=11 loss=3.7706 val_auc=0.7857
model=transformerconv top_k=200 fold=0 epoch=12 loss=3.7760 val_auc=0.7872
model=transformerconv top_k=200 fold=0 epoch=13 loss=3.8156 val_auc=0.7886
model=transformerconv top_k=200 fold=0 epoch=14 loss=3.7437 val_auc=0.7909
model=transformerconv top_k=200 fold=0 epoch=15 loss=3.9953 val_auc=0.7925
model=transformerconv top_k=200 fold=0 epoch=16 loss=2.8758 val_auc=0.7942
model=transformerconv top_k=200 fold=0 epoch=17 loss=3.1757 val_auc=0.7953
model=transformerconv top_k=200 fold=0 epoch=18 loss=3.5761 val_auc=0.7962
model=transformerconv top_k=200 fold=0 epoch=19 loss=2.8691 val_auc=0.7968
model=transformerconv top_k=200 fold=0 epoch=20 loss=3.1181 val_auc=0.7979
model=transformerconv top_k=200 fold=0 epoch=21 loss=3.2785 val_auc=0.7989
model=transformerconv top_k=200 fold=0 epoch=22 loss=2.6469 val_auc=0.7998
model=transformerconv top_k=200 fold=0 epoch=23 loss=2.7823 val_auc=0.8009
model=transformerconv top_k=200 fold=0 epoch=24 loss=2.8541 val_auc=0.8021
model=transformerconv top_k=200 fold=0 epoch=25 loss=2.7714 val_auc=0.8031
model=transformerconv top_k=200 fold=0 epoch=26 loss=2.4502 val_auc=0.8042
model=transformerconv top_k=200 fold=0 epoch=27 loss=2.4631 val_auc=0.8053
model=transformerconv top_k=200 fold=0 epoch=28 loss=2.4971 val_auc=0.8060
model=transformerconv top_k=200 fold=0 epoch=29 loss=2.6855 val_auc=0.8067
model=transformerconv top_k=200 fold=0 epoch=30 loss=2.6979 val_auc=0.8071
model=transformerconv top_k=200 fold=0 epoch=31 loss=2.2881 val_auc=0.8079
model=transformerconv top_k=200 fold=0 epoch=32 loss=2.1746 val_auc=0.8090
model=transformerconv top_k=200 fold=0 epoch=33 loss=2.0871 val_auc=0.8097
model=transformerconv top_k=200 fold=0 epoch=34 loss=2.4606 val_auc=0.8102
model=transformerconv top_k=200 fold=0 epoch=35 loss=2.3830 val_auc=0.8104
model=transformerconv top_k=200 fold=0 epoch=36 loss=2.4894 val_auc=0.8107
model=transformerconv top_k=200 fold=0 epoch=37 loss=2.1748 val_auc=0.8111
model=transformerconv top_k=200 fold=0 epoch=38 loss=2.2360 val_auc=0.8118
model=transformerconv top_k=200 fold=0 epoch=39 loss=2.2041 val_auc=0.8123
model=transformerconv top_k=200 fold=0 epoch=40 loss=2.2765 val_auc=0.8127
model=transformerconv top_k=200 fold=0 epoch=41 loss=2.3475 val_auc=0.8129
model=transformerconv top_k=200 fold=0 epoch=42 loss=2.0085 val_auc=0.8132
model=transformerconv top_k=200 fold=0 epoch=43 loss=2.0402 val_auc=0.8137
model=transformerconv top_k=200 fold=0 epoch=44 loss=1.9144 val_auc=0.8143
model=transformerconv top_k=200 fold=0 epoch=45 loss=1.9712 val_auc=0.8151
model=transformerconv top_k=200 fold=0 epoch=46 loss=1.8507 val_auc=0.8158
model=transformerconv top_k=200 fold=0 epoch=47 loss=2.4197 val_auc=0.8162
model=transformerconv top_k=200 fold=0 epoch=48 loss=2.1544 val_auc=0.8164
model=transformerconv top_k=200 fold=0 epoch=49 loss=1.7707 val_auc=0.8163
model=transformerconv top_k=200 fold=0 epoch=50 loss=1.9113 val_auc=0.8164
model=transformerconv top_k=200 fold=0 epoch=51 loss=1.6120 val_auc=0.8167
model=transformerconv top_k=200 fold=0 epoch=52 loss=1.8145 val_auc=0.8169
model=transformerconv top_k=200 fold=0 epoch=53 loss=1.6459 val_auc=0.8170
model=transformerconv top_k=200 fold=0 epoch=54 loss=1.6622 val_auc=0.8171
model=transformerconv top_k=200 fold=0 epoch=55 loss=1.5888 val_auc=0.8170
model=transformerconv top_k=200 fold=0 epoch=56 loss=1.5071 val_auc=0.8172
model=transformerconv top_k=200 fold=0 epoch=57 loss=1.4786 val_auc=0.8176
model=transformerconv top_k=200 fold=0 epoch=58 loss=1.4488 val_auc=0.8181
model=transformerconv top_k=200 fold=0 epoch=59 loss=2.0005 val_auc=0.8185
model=transformerconv top_k=200 fold=0 epoch=60 loss=1.7131 val_auc=0.8186
model=transformerconv top_k=200 fold=0 epoch=61 loss=1.4450 val_auc=0.8187
model=transformerconv top_k=200 fold=0 epoch=62 loss=1.6436 val_auc=0.8187
model=transformerconv top_k=200 fold=0 epoch=63 loss=1.9892 val_auc=0.8188
model=transformerconv top_k=200 fold=0 epoch=64 loss=1.6197 val_auc=0.8192
model=transformerconv top_k=200 fold=0 epoch=65 loss=1.6900 val_auc=0.8192
model=transformerconv top_k=200 fold=0 epoch=66 loss=1.6129 val_auc=0.8193
model=transformerconv top_k=200 fold=0 epoch=67 loss=1.3793 val_auc=0.8192
model=transformerconv top_k=200 fold=0 epoch=68 loss=1.3203 val_auc=0.8193
model=transformerconv top_k=200 fold=0 epoch=69 loss=1.6518 val_auc=0.8198
model=transformerconv top_k=200 fold=0 epoch=70 loss=1.4211 val_auc=0.8202
model=transformerconv top_k=200 fold=0 epoch=71 loss=1.2334 val_auc=0.8206
model=transformerconv top_k=200 fold=0 epoch=72 loss=1.4549 val_auc=0.8209
model=transformerconv top_k=200 fold=0 epoch=73 loss=1.2988 val_auc=0.8212
model=transformerconv top_k=200 fold=0 epoch=74 loss=1.3041 val_auc=0.8212
model=transformerconv top_k=200 fold=0 epoch=75 loss=1.2167 val_auc=0.8211
model=transformerconv top_k=200 fold=0 epoch=76 loss=1.2424 val_auc=0.8212
model=transformerconv top_k=200 fold=0 epoch=77 loss=1.3524 val_auc=0.8212
model=transformerconv top_k=200 fold=0 epoch=78 loss=1.5769 val_auc=0.8213
model=transformerconv top_k=200 fold=0 epoch=79 loss=1.6613 val_auc=0.8214
model=transformerconv top_k=200 fold=0 epoch=80 loss=1.3841 val_auc=0.8215
model=transformerconv top_k=200 fold=0 epoch=81 loss=1.4268 val_auc=0.8214
model=transformerconv top_k=200 fold=0 epoch=82 loss=1.8122 val_auc=0.8216
model=transformerconv top_k=200 fold=0 epoch=83 loss=1.8288 val_auc=0.8219
model=transformerconv top_k=200 fold=0 epoch=84 loss=1.5398 val_auc=0.8221
model=transformerconv top_k=200 fold=0 epoch=85 loss=1.2618 val_auc=0.8227
model=transformerconv top_k=200 fold=0 epoch=86 loss=1.4647 val_auc=0.8231
model=transformerconv top_k=200 fold=0 epoch=87 loss=1.5920 val_auc=0.8233
model=transformerconv top_k=200 fold=0 epoch=88 loss=1.3583 val_auc=0.8233
model=transformerconv top_k=200 fold=0 epoch=89 loss=1.2479 val_auc=0.8234
model=transformerconv top_k=200 fold=0 epoch=90 loss=1.3123 val_auc=0.8234
model=transformerconv top_k=200 fold=0 epoch=91 loss=1.4706 val_auc=0.8235
model=transformerconv top_k=200 fold=0 epoch=92 loss=1.5708 val_auc=0.8236
model=transformerconv top_k=200 fold=0 epoch=93 loss=1.5449 val_auc=0.8239
model=transformerconv top_k=200 fold=0 epoch=94 loss=1.1508 val_auc=0.8241
model=transformerconv top_k=200 fold=0 epoch=95 loss=1.1802 val_auc=0.8243
model=transformerconv top_k=200 fold=0 epoch=96 loss=1.2851 val_auc=0.8242
model=transformerconv top_k=200 fold=0 epoch=97 loss=1.2137 val_auc=0.8241
model=transformerconv top_k=200 fold=0 epoch=98 loss=1.1752 val_auc=0.8244
model=transformerconv top_k=200 fold=0 epoch=99 loss=1.1672 val_auc=0.8247
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718731 edges

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=200 fold=1 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719209 edges
model=transformerconv top_k=200 fold=1 epoch=0 loss=7.9536 val_auc=0.5000
model=transformerconv top_k=200 fold=1 epoch=1 loss=31.3140 val_auc=0.5279
model=transformerconv top_k=200 fold=1 epoch=2 loss=23.5446 val_auc=0.7247
model=transformerconv top_k=200 fold=1 epoch=3 loss=11.6796 val_auc=0.7368
model=transformerconv top_k=200 fold=1 epoch=4 loss=6.4934 val_auc=0.7412
model=transformerconv top_k=200 fold=1 epoch=5 loss=6.6407 val_auc=0.7452
model=transformerconv top_k=200 fold=1 epoch=6 loss=6.3086 val_auc=0.7484
model=transformerconv top_k=200 fold=1 epoch=7 loss=4.4747 val_auc=0.7542
model=transformerconv top_k=200 fold=1 epoch=8 loss=4.2292 val_auc=0.7650
model=transformerconv top_k=200 fold=1 epoch=9 loss=4.3862 val_auc=0.7695
model=transformerconv top_k=200 fold=1 epoch=10 loss=5.3616 val_auc=0.7723
model=transformerconv top_k=200 fold=1 epoch=11 loss=4.2605 val_auc=0.7756
model=transformerconv top_k=200 fold=1 epoch=12 loss=3.4793 val_auc=0.7795
model=transformerconv top_k=200 fold=1 epoch=13 loss=3.6122 val_auc=0.7837
model=transformerconv top_k=200 fold=1 epoch=14 loss=3.1781 val_auc=0.7862
model=transformerconv top_k=200 fold=1 epoch=15 loss=3.3293 val_auc=0.7886
model=transformerconv top_k=200 fold=1 epoch=16 loss=3.2168 val_auc=0.7902
model=transformerconv top_k=200 fold=1 epoch=17 loss=3.7494 val_auc=0.7928
model=transformerconv top_k=200 fold=1 epoch=18 loss=3.1713 val_auc=0.7952
model=transformerconv top_k=200 fold=1 epoch=19 loss=3.1501 val_auc=0.7970
model=transformerconv top_k=200 fold=1 epoch=20 loss=3.6134 val_auc=0.7984
model=transformerconv top_k=200 fold=1 epoch=21 loss=2.6334 val_auc=0.8002
model=transformerconv top_k=200 fold=1 epoch=22 loss=3.2736 val_auc=0.8017
model=transformerconv top_k=200 fold=1 epoch=23 loss=2.4649 val_auc=0.8038
model=transformerconv top_k=200 fold=1 epoch=24 loss=2.2720 val_auc=0.8063
model=transformerconv top_k=200 fold=1 epoch=25 loss=2.3080 val_auc=0.8091
model=transformerconv top_k=200 fold=1 epoch=26 loss=2.5485 val_auc=0.8117
model=transformerconv top_k=200 fold=1 epoch=27 loss=2.4362 val_auc=0.8133
model=transformerconv top_k=200 fold=1 epoch=28 loss=2.2063 val_auc=0.8149
model=transformerconv top_k=200 fold=1 epoch=29 loss=2.2565 val_auc=0.8164
model=transformerconv top_k=200 fold=1 epoch=30 loss=2.2876 val_auc=0.8175
model=transformerconv top_k=200 fold=1 epoch=31 loss=2.1406 val_auc=0.8183
model=transformerconv top_k=200 fold=1 epoch=32 loss=2.0505 val_auc=0.8186
model=transformerconv top_k=200 fold=1 epoch=33 loss=1.9577 val_auc=0.8179
model=transformerconv top_k=200 fold=1 epoch=34 loss=1.9689 val_auc=0.8173
model=transformerconv top_k=200 fold=1 epoch=35 loss=1.7481 val_auc=0.8176
model=transformerconv top_k=200 fold=1 epoch=36 loss=1.8456 val_auc=0.8192
model=transformerconv top_k=200 fold=1 epoch=37 loss=1.9661 val_auc=0.8203
model=transformerconv top_k=200 fold=1 epoch=38 loss=2.6102 val_auc=0.8208
model=transformerconv top_k=200 fold=1 epoch=39 loss=1.9428 val_auc=0.8210
model=transformerconv top_k=200 fold=1 epoch=40 loss=1.9172 val_auc=0.8214
model=transformerconv top_k=200 fold=1 epoch=41 loss=1.9326 val_auc=0.8220
model=transformerconv top_k=200 fold=1 epoch=42 loss=1.8590 val_auc=0.8226
model=transformerconv top_k=200 fold=1 epoch=43 loss=1.7253 val_auc=0.8230
model=transformerconv top_k=200 fold=1 epoch=44 loss=1.6237 val_auc=0.8233
model=transformerconv top_k=200 fold=1 epoch=45 loss=1.7365 val_auc=0.8234
model=transformerconv top_k=200 fold=1 epoch=46 loss=1.6535 val_auc=0.8236
model=transformerconv top_k=200 fold=1 epoch=47 loss=1.9315 val_auc=0.8238
model=transformerconv top_k=200 fold=1 epoch=48 loss=1.7694 val_auc=0.8240
model=transformerconv top_k=200 fold=1 epoch=49 loss=1.7279 val_auc=0.8242
model=transformerconv top_k=200 fold=1 epoch=50 loss=1.8164 val_auc=0.8242
model=transformerconv top_k=200 fold=1 epoch=51 loss=1.7351 val_auc=0.8240
model=transformerconv top_k=200 fold=1 epoch=52 loss=1.5254 val_auc=0.8239
model=transformerconv top_k=200 fold=1 epoch=53 loss=1.5479 val_auc=0.8241
model=transformerconv top_k=200 fold=1 epoch=54 loss=1.4685 val_auc=0.8242
model=transformerconv top_k=200 fold=1 epoch=55 loss=1.3147 val_auc=0.8247
model=transformerconv top_k=200 fold=1 epoch=56 loss=1.4520 val_auc=0.8252
model=transformerconv top_k=200 fold=1 epoch=57 loss=1.5228 val_auc=0.8261
model=transformerconv top_k=200 fold=1 epoch=58 loss=1.3431 val_auc=0.8270
model=transformerconv top_k=200 fold=1 epoch=59 loss=1.2820 val_auc=0.8280
model=transformerconv top_k=200 fold=1 epoch=60 loss=1.4186 val_auc=0.8289
model=transformerconv top_k=200 fold=1 epoch=61 loss=1.4605 val_auc=0.8294
model=transformerconv top_k=200 fold=1 epoch=62 loss=1.6489 val_auc=0.8298
model=transformerconv top_k=200 fold=1 epoch=63 loss=1.3886 val_auc=0.8298
model=transformerconv top_k=200 fold=1 epoch=64 loss=1.3715 val_auc=0.8297
model=transformerconv top_k=200 fold=1 epoch=65 loss=1.4401 val_auc=0.8299
model=transformerconv top_k=200 fold=1 epoch=66 loss=1.3003 val_auc=0.8298
model=transformerconv top_k=200 fold=1 epoch=67 loss=1.3566 val_auc=0.8295
model=transformerconv top_k=200 fold=1 epoch=68 loss=1.4366 val_auc=0.8289
model=transformerconv top_k=200 fold=1 epoch=69 loss=1.2679 val_auc=0.8286
model=transformerconv top_k=200 fold=1 epoch=70 loss=1.4804 val_auc=0.8287
model=transformerconv top_k=200 fold=1 epoch=71 loss=1.4346 val_auc=0.8290
model=transformerconv top_k=200 fold=1 epoch=72 loss=1.4118 val_auc=0.8290
model=transformerconv top_k=200 fold=1 epoch=73 loss=1.3688 val_auc=0.8288
model=transformerconv top_k=200 fold=1 epoch=74 loss=1.4154 val_auc=0.8284
model=transformerconv top_k=200 fold=1 epoch=75 loss=1.2697 val_auc=0.8286
model=transformerconv top_k=200 fold=1 epoch=76 loss=1.3900 val_auc=0.8291
model=transformerconv top_k=200 fold=1 epoch=77 loss=1.1866 val_auc=0.8305
model=transformerconv top_k=200 fold=1 epoch=78 loss=1.1449 val_auc=0.8320
model=transformerconv top_k=200 fold=1 epoch=79 loss=1.1581 val_auc=0.8334
model=transformerconv top_k=200 fold=1 epoch=80 loss=1.2652 val_auc=0.8344
model=transformerconv top_k=200 fold=1 epoch=81 loss=1.2462 val_auc=0.8351
model=transformerconv top_k=200 fold=1 epoch=82 loss=1.2609 val_auc=0.8356
model=transformerconv top_k=200 fold=1 epoch=83 loss=1.2747 val_auc=0.8363
model=transformerconv top_k=200 fold=1 epoch=84 loss=1.2382 val_auc=0.8368
model=transformerconv top_k=200 fold=1 epoch=85 loss=1.2684 val_auc=0.8371
model=transformerconv top_k=200 fold=1 epoch=86 loss=1.5029 val_auc=0.8370
model=transformerconv top_k=200 fold=1 epoch=87 loss=1.2810 val_auc=0.8365
model=transformerconv top_k=200 fold=1 epoch=88 loss=1.3563 val_auc=0.8355
model=transformerconv top_k=200 fold=1 epoch=89 loss=1.3795 val_auc=0.8346
model=transformerconv top_k=200 fold=1 epoch=90 loss=1.4854 val_auc=0.8340
model=transformerconv top_k=200 fold=1 epoch=91 loss=1.2313 val_auc=0.8338
model=transformerconv top_k=200 fold=1 epoch=92 loss=1.0881 val_auc=0.8341
model=transformerconv top_k=200 fold=1 epoch=93 loss=1.1514 val_auc=0.8343
model=transformerconv top_k=200 fold=1 epoch=94 loss=1.1611 val_auc=0.8345
model=transformerconv top_k=200 fold=1 epoch=95 loss=1.2176 val_auc=0.8352
model=transformerconv top_k=200 fold=1 epoch=96 loss=1.1246 val_auc=0.8365
model=transformerconv top_k=200 fold=1 epoch=97 loss=1.0565 val_auc=0.8380
model=transformerconv top_k=200 fold=1 epoch=98 loss=1.1887 val_auc=0.8389
model=transformerconv top_k=200 fold=1 epoch=99 loss=1.4512 val_auc=0.8393
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719209 edges

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=200 fold=2 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718855 edges
model=transformerconv top_k=200 fold=2 epoch=0 loss=5.8386 val_auc=0.7149
model=transformerconv top_k=200 fold=2 epoch=1 loss=11.9383 val_auc=0.7444
model=transformerconv top_k=200 fold=2 epoch=2 loss=5.3198 val_auc=0.7495
model=transformerconv top_k=200 fold=2 epoch=3 loss=5.3155 val_auc=0.7556
model=transformerconv top_k=200 fold=2 epoch=4 loss=4.6694 val_auc=0.7588
model=transformerconv top_k=200 fold=2 epoch=5 loss=3.9122 val_auc=0.7652
model=transformerconv top_k=200 fold=2 epoch=6 loss=3.9133 val_auc=0.7718
model=transformerconv top_k=200 fold=2 epoch=7 loss=3.7632 val_auc=0.7754
model=transformerconv top_k=200 fold=2 epoch=8 loss=4.1225 val_auc=0.7780
model=transformerconv top_k=200 fold=2 epoch=9 loss=3.1865 val_auc=0.7809
model=transformerconv top_k=200 fold=2 epoch=10 loss=3.0417 val_auc=0.7847
model=transformerconv top_k=200 fold=2 epoch=11 loss=3.0283 val_auc=0.7882
model=transformerconv top_k=200 fold=2 epoch=12 loss=3.3500 val_auc=0.7917
model=transformerconv top_k=200 fold=2 epoch=13 loss=3.4368 val_auc=0.7949
model=transformerconv top_k=200 fold=2 epoch=14 loss=3.7328 val_auc=0.7970
model=transformerconv top_k=200 fold=2 epoch=15 loss=3.4550 val_auc=0.7979
model=transformerconv top_k=200 fold=2 epoch=16 loss=3.0073 val_auc=0.7984
model=transformerconv top_k=200 fold=2 epoch=17 loss=2.7349 val_auc=0.7990
model=transformerconv top_k=200 fold=2 epoch=18 loss=3.7261 val_auc=0.7998
model=transformerconv top_k=200 fold=2 epoch=19 loss=2.9589 val_auc=0.8006
model=transformerconv top_k=200 fold=2 epoch=20 loss=2.4392 val_auc=0.8010
model=transformerconv top_k=200 fold=2 epoch=21 loss=2.3234 val_auc=0.8013
model=transformerconv top_k=200 fold=2 epoch=22 loss=2.3225 val_auc=0.8019
model=transformerconv top_k=200 fold=2 epoch=23 loss=2.1667 val_auc=0.8021
model=transformerconv top_k=200 fold=2 epoch=24 loss=1.8813 val_auc=0.8027
model=transformerconv top_k=200 fold=2 epoch=25 loss=2.5625 val_auc=0.8032
model=transformerconv top_k=200 fold=2 epoch=26 loss=2.2463 val_auc=0.8036
model=transformerconv top_k=200 fold=2 epoch=27 loss=2.0519 val_auc=0.8044
model=transformerconv top_k=200 fold=2 epoch=28 loss=2.4860 val_auc=0.8055
model=transformerconv top_k=200 fold=2 epoch=29 loss=2.2782 val_auc=0.8065
model=transformerconv top_k=200 fold=2 epoch=30 loss=2.0515 val_auc=0.8074
model=transformerconv top_k=200 fold=2 epoch=31 loss=1.9429 val_auc=0.8080
model=transformerconv top_k=200 fold=2 epoch=32 loss=2.0971 val_auc=0.8083
model=transformerconv top_k=200 fold=2 epoch=33 loss=2.0483 val_auc=0.8083
model=transformerconv top_k=200 fold=2 epoch=34 loss=2.3608 val_auc=0.8083
model=transformerconv top_k=200 fold=2 epoch=35 loss=2.2368 val_auc=0.8084
model=transformerconv top_k=200 fold=2 epoch=36 loss=2.1633 val_auc=0.8087
model=transformerconv top_k=200 fold=2 epoch=37 loss=1.5265 val_auc=0.8093
model=transformerconv top_k=200 fold=2 epoch=38 loss=1.4533 val_auc=0.8104
model=transformerconv top_k=200 fold=2 epoch=39 loss=1.6793 val_auc=0.8112
model=transformerconv top_k=200 fold=2 epoch=40 loss=1.6965 val_auc=0.8115
model=transformerconv top_k=200 fold=2 epoch=41 loss=1.5709 val_auc=0.8123
model=transformerconv top_k=200 fold=2 epoch=42 loss=1.5711 val_auc=0.8129
model=transformerconv top_k=200 fold=2 epoch=43 loss=1.7529 val_auc=0.8138
model=transformerconv top_k=200 fold=2 epoch=44 loss=1.5764 val_auc=0.8148
model=transformerconv top_k=200 fold=2 epoch=45 loss=1.5368 val_auc=0.8154
model=transformerconv top_k=200 fold=2 epoch=46 loss=1.7056 val_auc=0.8157
model=transformerconv top_k=200 fold=2 epoch=47 loss=1.5069 val_auc=0.8161
model=transformerconv top_k=200 fold=2 epoch=48 loss=1.4751 val_auc=0.8163
model=transformerconv top_k=200 fold=2 epoch=49 loss=1.3552 val_auc=0.8168
model=transformerconv top_k=200 fold=2 epoch=50 loss=1.4005 val_auc=0.8173
model=transformerconv top_k=200 fold=2 epoch=51 loss=1.5335 val_auc=0.8176
model=transformerconv top_k=200 fold=2 epoch=52 loss=1.3328 val_auc=0.8180
model=transformerconv top_k=200 fold=2 epoch=53 loss=1.6017 val_auc=0.8183
model=transformerconv top_k=200 fold=2 epoch=54 loss=1.7227 val_auc=0.8186
model=transformerconv top_k=200 fold=2 epoch=55 loss=1.3787 val_auc=0.8187
model=transformerconv top_k=200 fold=2 epoch=56 loss=1.4061 val_auc=0.8188
model=transformerconv top_k=200 fold=2 epoch=57 loss=1.4597 val_auc=0.8191
model=transformerconv top_k=200 fold=2 epoch=58 loss=1.4092 val_auc=0.8195
model=transformerconv top_k=200 fold=2 epoch=59 loss=1.3499 val_auc=0.8198
model=transformerconv top_k=200 fold=2 epoch=60 loss=1.4910 val_auc=0.8201
model=transformerconv top_k=200 fold=2 epoch=61 loss=1.2811 val_auc=0.8208
model=transformerconv top_k=200 fold=2 epoch=62 loss=1.4483 val_auc=0.8214
model=transformerconv top_k=200 fold=2 epoch=63 loss=1.6377 val_auc=0.8220
model=transformerconv top_k=200 fold=2 epoch=64 loss=1.3987 val_auc=0.8226
model=transformerconv top_k=200 fold=2 epoch=65 loss=1.3336 val_auc=0.8231
model=transformerconv top_k=200 fold=2 epoch=66 loss=1.2817 val_auc=0.8238
model=transformerconv top_k=200 fold=2 epoch=67 loss=1.3388 val_auc=0.8245
model=transformerconv top_k=200 fold=2 epoch=68 loss=1.4650 val_auc=0.8251
model=transformerconv top_k=200 fold=2 epoch=69 loss=1.4295 val_auc=0.8257
model=transformerconv top_k=200 fold=2 epoch=70 loss=1.1602 val_auc=0.8263
model=transformerconv top_k=200 fold=2 epoch=71 loss=1.2437 val_auc=0.8269
model=transformerconv top_k=200 fold=2 epoch=72 loss=1.4416 val_auc=0.8274
model=transformerconv top_k=200 fold=2 epoch=73 loss=1.3266 val_auc=0.8279
model=transformerconv top_k=200 fold=2 epoch=74 loss=1.2121 val_auc=0.8282
model=transformerconv top_k=200 fold=2 epoch=75 loss=1.2491 val_auc=0.8284
model=transformerconv top_k=200 fold=2 epoch=76 loss=1.2407 val_auc=0.8282
model=transformerconv top_k=200 fold=2 epoch=77 loss=1.1292 val_auc=0.8280
model=transformerconv top_k=200 fold=2 epoch=78 loss=1.4063 val_auc=0.8278
model=transformerconv top_k=200 fold=2 epoch=79 loss=1.2408 val_auc=0.8274
model=transformerconv top_k=200 fold=2 epoch=80 loss=1.5307 val_auc=0.8270
model=transformerconv top_k=200 fold=2 epoch=81 loss=1.5327 val_auc=0.8267
model=transformerconv top_k=200 fold=2 epoch=82 loss=1.2893 val_auc=0.8267
model=transformerconv top_k=200 fold=2 epoch=83 loss=1.1814 val_auc=0.8277
model=transformerconv top_k=200 fold=2 epoch=84 loss=1.2707 val_auc=0.8286
model=transformerconv top_k=200 fold=2 epoch=85 loss=1.2106 val_auc=0.8293
model=transformerconv top_k=200 fold=2 epoch=86 loss=1.3119 val_auc=0.8296
model=transformerconv top_k=200 fold=2 epoch=87 loss=1.1771 val_auc=0.8302
model=transformerconv top_k=200 fold=2 epoch=88 loss=1.3173 val_auc=0.8311
model=transformerconv top_k=200 fold=2 epoch=89 loss=1.2116 val_auc=0.8321
model=transformerconv top_k=200 fold=2 epoch=90 loss=1.1307 val_auc=0.8327
model=transformerconv top_k=200 fold=2 epoch=91 loss=1.1257 val_auc=0.8332
model=transformerconv top_k=200 fold=2 epoch=92 loss=1.1313 val_auc=0.8336
model=transformerconv top_k=200 fold=2 epoch=93 loss=1.2160 val_auc=0.8337
model=transformerconv top_k=200 fold=2 epoch=94 loss=1.2824 val_auc=0.8340
model=transformerconv top_k=200 fold=2 epoch=95 loss=1.1733 val_auc=0.8344
model=transformerconv top_k=200 fold=2 epoch=96 loss=1.1664 val_auc=0.8346
model=transformerconv top_k=200 fold=2 epoch=97 loss=1.2606 val_auc=0.8347
model=transformerconv top_k=200 fold=2 epoch=98 loss=1.0584 val_auc=0.8349
model=transformerconv top_k=200 fold=2 epoch=99 loss=1.1364 val_auc=0.8352
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718855 edges

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=200 fold=3 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719213 edges
model=transformerconv top_k=200 fold=3 epoch=0 loss=12.8985 val_auc=0.5422
model=transformerconv top_k=200 fold=3 epoch=1 loss=21.8650 val_auc=0.6413
model=transformerconv top_k=200 fold=3 epoch=2 loss=16.9523 val_auc=0.7157
model=transformerconv top_k=200 fold=3 epoch=3 loss=6.6984 val_auc=0.7510
model=transformerconv top_k=200 fold=3 epoch=4 loss=9.7335 val_auc=0.7636
model=transformerconv top_k=200 fold=3 epoch=5 loss=12.8846 val_auc=0.7731
model=transformerconv top_k=200 fold=3 epoch=6 loss=8.6560 val_auc=0.7773
model=transformerconv top_k=200 fold=3 epoch=7 loss=6.4245 val_auc=0.7794
model=transformerconv top_k=200 fold=3 epoch=8 loss=4.3549 val_auc=0.7820
model=transformerconv top_k=200 fold=3 epoch=9 loss=6.0468 val_auc=0.7845
model=transformerconv top_k=200 fold=3 epoch=10 loss=5.4042 val_auc=0.7866
model=transformerconv top_k=200 fold=3 epoch=11 loss=4.7583 val_auc=0.7880
model=transformerconv top_k=200 fold=3 epoch=12 loss=4.4746 val_auc=0.7893
model=transformerconv top_k=200 fold=3 epoch=13 loss=4.1105 val_auc=0.7908
model=transformerconv top_k=200 fold=3 epoch=14 loss=4.2966 val_auc=0.7925
model=transformerconv top_k=200 fold=3 epoch=15 loss=4.4249 val_auc=0.7945
model=transformerconv top_k=200 fold=3 epoch=16 loss=3.3451 val_auc=0.7967
model=transformerconv top_k=200 fold=3 epoch=17 loss=3.3052 val_auc=0.7990
model=transformerconv top_k=200 fold=3 epoch=18 loss=3.2590 val_auc=0.8002
model=transformerconv top_k=200 fold=3 epoch=19 loss=3.8726 val_auc=0.8013
model=transformerconv top_k=200 fold=3 epoch=20 loss=3.1650 val_auc=0.8020
model=transformerconv top_k=200 fold=3 epoch=21 loss=3.4711 val_auc=0.8029
model=transformerconv top_k=200 fold=3 epoch=22 loss=3.2607 val_auc=0.8038
model=transformerconv top_k=200 fold=3 epoch=23 loss=3.8749 val_auc=0.8046
model=transformerconv top_k=200 fold=3 epoch=24 loss=3.8255 val_auc=0.8049
model=transformerconv top_k=200 fold=3 epoch=25 loss=3.3918 val_auc=0.8051
model=transformerconv top_k=200 fold=3 epoch=26 loss=2.9652 val_auc=0.8054
model=transformerconv top_k=200 fold=3 epoch=27 loss=2.7400 val_auc=0.8059
model=transformerconv top_k=200 fold=3 epoch=28 loss=3.1377 val_auc=0.8063
model=transformerconv top_k=200 fold=3 epoch=29 loss=2.6883 val_auc=0.8070
model=transformerconv top_k=200 fold=3 epoch=30 loss=2.5211 val_auc=0.8086
model=transformerconv top_k=200 fold=3 epoch=31 loss=2.4297 val_auc=0.8101
model=transformerconv top_k=200 fold=3 epoch=32 loss=2.5594 val_auc=0.8112
model=transformerconv top_k=200 fold=3 epoch=33 loss=2.1398 val_auc=0.8127
model=transformerconv top_k=200 fold=3 epoch=34 loss=2.2505 val_auc=0.8137
model=transformerconv top_k=200 fold=3 epoch=35 loss=2.3640 val_auc=0.8142
model=transformerconv top_k=200 fold=3 epoch=36 loss=1.8844 val_auc=0.8146
model=transformerconv top_k=200 fold=3 epoch=37 loss=2.0858 val_auc=0.8151
model=transformerconv top_k=200 fold=3 epoch=38 loss=1.8553 val_auc=0.8153
model=transformerconv top_k=200 fold=3 epoch=39 loss=2.1379 val_auc=0.8159
model=transformerconv top_k=200 fold=3 epoch=40 loss=1.7543 val_auc=0.8168
model=transformerconv top_k=200 fold=3 epoch=41 loss=1.8139 val_auc=0.8171
model=transformerconv top_k=200 fold=3 epoch=42 loss=1.9255 val_auc=0.8171
model=transformerconv top_k=200 fold=3 epoch=43 loss=1.9154 val_auc=0.8175
model=transformerconv top_k=200 fold=3 epoch=44 loss=1.8197 val_auc=0.8176
model=transformerconv top_k=200 fold=3 epoch=45 loss=1.7689 val_auc=0.8177
model=transformerconv top_k=200 fold=3 epoch=46 loss=1.5842 val_auc=0.8175
model=transformerconv top_k=200 fold=3 epoch=47 loss=1.9584 val_auc=0.8173
model=transformerconv top_k=200 fold=3 epoch=48 loss=1.7533 val_auc=0.8174
model=transformerconv top_k=200 fold=3 epoch=49 loss=1.6000 val_auc=0.8174
model=transformerconv top_k=200 fold=3 epoch=50 loss=1.6008 val_auc=0.8174
model=transformerconv top_k=200 fold=3 epoch=51 loss=1.7213 val_auc=0.8171
model=transformerconv top_k=200 fold=3 epoch=52 loss=1.5658 val_auc=0.8167
model=transformerconv top_k=200 fold=3 epoch=53 loss=1.5138 val_auc=0.8165
model=transformerconv top_k=200 fold=3 epoch=54 loss=1.6448 val_auc=0.8170
model=transformerconv top_k=200 fold=3 epoch=55 loss=1.5762 val_auc=0.8181
model=transformerconv top_k=200 fold=3 epoch=56 loss=1.5542 val_auc=0.8194
model=transformerconv top_k=200 fold=3 epoch=57 loss=1.5959 val_auc=0.8202
model=transformerconv top_k=200 fold=3 epoch=58 loss=1.6092 val_auc=0.8205
model=transformerconv top_k=200 fold=3 epoch=59 loss=1.4632 val_auc=0.8207
model=transformerconv top_k=200 fold=3 epoch=60 loss=1.5814 val_auc=0.8210
model=transformerconv top_k=200 fold=3 epoch=61 loss=1.5280 val_auc=0.8213
model=transformerconv top_k=200 fold=3 epoch=62 loss=1.5091 val_auc=0.8214
model=transformerconv top_k=200 fold=3 epoch=63 loss=1.6923 val_auc=0.8212
model=transformerconv top_k=200 fold=3 epoch=64 loss=1.5251 val_auc=0.8214
model=transformerconv top_k=200 fold=3 epoch=65 loss=1.4750 val_auc=0.8218
model=transformerconv top_k=200 fold=3 epoch=66 loss=1.3455 val_auc=0.8222
model=transformerconv top_k=200 fold=3 epoch=67 loss=1.3529 val_auc=0.8226
model=transformerconv top_k=200 fold=3 epoch=68 loss=1.2456 val_auc=0.8236
model=transformerconv top_k=200 fold=3 epoch=69 loss=1.3768 val_auc=0.8245
model=transformerconv top_k=200 fold=3 epoch=70 loss=1.3493 val_auc=0.8251
model=transformerconv top_k=200 fold=3 epoch=71 loss=1.2814 val_auc=0.8250
model=transformerconv top_k=200 fold=3 epoch=72 loss=1.3559 val_auc=0.8253
model=transformerconv top_k=200 fold=3 epoch=73 loss=1.4507 val_auc=0.8261
model=transformerconv top_k=200 fold=3 epoch=74 loss=1.4802 val_auc=0.8276
model=transformerconv top_k=200 fold=3 epoch=75 loss=1.3057 val_auc=0.8282
model=transformerconv top_k=200 fold=3 epoch=76 loss=1.3618 val_auc=0.8283
model=transformerconv top_k=200 fold=3 epoch=77 loss=1.2625 val_auc=0.8279
model=transformerconv top_k=200 fold=3 epoch=78 loss=1.2200 val_auc=0.8279
model=transformerconv top_k=200 fold=3 epoch=79 loss=1.4765 val_auc=0.8280
model=transformerconv top_k=200 fold=3 epoch=80 loss=1.3975 val_auc=0.8281
model=transformerconv top_k=200 fold=3 epoch=81 loss=1.3549 val_auc=0.8282
model=transformerconv top_k=200 fold=3 epoch=82 loss=1.4698 val_auc=0.8280
model=transformerconv top_k=200 fold=3 epoch=83 loss=1.4648 val_auc=0.8277
model=transformerconv top_k=200 fold=3 epoch=84 loss=1.2031 val_auc=0.8273
model=transformerconv top_k=200 fold=3 epoch=85 loss=1.1641 val_auc=0.8273
model=transformerconv top_k=200 fold=3 epoch=86 loss=1.1968 val_auc=0.8278
model=transformerconv top_k=200 fold=3 epoch=87 loss=1.1383 val_auc=0.8285
model=transformerconv top_k=200 fold=3 epoch=88 loss=1.3167 val_auc=0.8290
model=transformerconv top_k=200 fold=3 epoch=89 loss=1.3629 val_auc=0.8294
model=transformerconv top_k=200 fold=3 epoch=90 loss=1.2508 val_auc=0.8297
model=transformerconv top_k=200 fold=3 epoch=91 loss=1.4853 val_auc=0.8301
model=transformerconv top_k=200 fold=3 epoch=92 loss=1.2919 val_auc=0.8305
model=transformerconv top_k=200 fold=3 epoch=93 loss=1.2199 val_auc=0.8310
model=transformerconv top_k=200 fold=3 epoch=94 loss=1.1117 val_auc=0.8313
model=transformerconv top_k=200 fold=3 epoch=95 loss=1.3451 val_auc=0.8312
model=transformerconv top_k=200 fold=3 epoch=96 loss=1.5408 val_auc=0.8313
model=transformerconv top_k=200 fold=3 epoch=97 loss=1.3856 val_auc=0.8314
model=transformerconv top_k=200 fold=3 epoch=98 loss=1.2020 val_auc=0.8315
model=transformerconv top_k=200 fold=3 epoch=99 loss=1.2600 val_auc=0.8314
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719213 edges

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=200 fold=4 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719233 edges
model=transformerconv top_k=200 fold=4 epoch=0 loss=5.5467 val_auc=0.7480
model=transformerconv top_k=200 fold=4 epoch=1 loss=18.3897 val_auc=0.7626
model=transformerconv top_k=200 fold=4 epoch=2 loss=10.3049 val_auc=0.7663
model=transformerconv top_k=200 fold=4 epoch=3 loss=5.2243 val_auc=0.7701
model=transformerconv top_k=200 fold=4 epoch=4 loss=5.8547 val_auc=0.7719
model=transformerconv top_k=200 fold=4 epoch=5 loss=4.0462 val_auc=0.7756
model=transformerconv top_k=200 fold=4 epoch=6 loss=3.3004 val_auc=0.7790
model=transformerconv top_k=200 fold=4 epoch=7 loss=3.6048 val_auc=0.7812
model=transformerconv top_k=200 fold=4 epoch=8 loss=3.0813 val_auc=0.7840
model=transformerconv top_k=200 fold=4 epoch=9 loss=2.9441 val_auc=0.7860
model=transformerconv top_k=200 fold=4 epoch=10 loss=3.7428 val_auc=0.7870
model=transformerconv top_k=200 fold=4 epoch=11 loss=3.2060 val_auc=0.7881
model=transformerconv top_k=200 fold=4 epoch=12 loss=3.2089 val_auc=0.7892
model=transformerconv top_k=200 fold=4 epoch=13 loss=3.9245 val_auc=0.7907
model=transformerconv top_k=200 fold=4 epoch=14 loss=2.9299 val_auc=0.7916
model=transformerconv top_k=200 fold=4 epoch=15 loss=2.3778 val_auc=0.7923
model=transformerconv top_k=200 fold=4 epoch=16 loss=3.1136 val_auc=0.7932
model=transformerconv top_k=200 fold=4 epoch=17 loss=4.4501 val_auc=0.7944
model=transformerconv top_k=200 fold=4 epoch=18 loss=3.2136 val_auc=0.7950
model=transformerconv top_k=200 fold=4 epoch=19 loss=2.9169 val_auc=0.7963
model=transformerconv top_k=200 fold=4 epoch=20 loss=2.7715 val_auc=0.7970
model=transformerconv top_k=200 fold=4 epoch=21 loss=3.6487 val_auc=0.7969
model=transformerconv top_k=200 fold=4 epoch=22 loss=3.5603 val_auc=0.7960
model=transformerconv top_k=200 fold=4 epoch=23 loss=2.6792 val_auc=0.7939
model=transformerconv top_k=200 fold=4 epoch=24 loss=2.4189 val_auc=0.7939
model=transformerconv top_k=200 fold=4 epoch=25 loss=2.2836 val_auc=0.7941
model=transformerconv top_k=200 fold=4 epoch=26 loss=2.1894 val_auc=0.7943
model=transformerconv top_k=200 fold=4 epoch=27 loss=1.9778 val_auc=0.7954
model=transformerconv top_k=200 fold=4 epoch=28 loss=2.4375 val_auc=0.7969
model=transformerconv top_k=200 fold=4 epoch=29 loss=2.2480 val_auc=0.7985
model=transformerconv top_k=200 fold=4 epoch=30 loss=1.7824 val_auc=0.8009
model=transformerconv top_k=200 fold=4 epoch=31 loss=2.2599 val_auc=0.8028
model=transformerconv top_k=200 fold=4 epoch=32 loss=2.3198 val_auc=0.8044
model=transformerconv top_k=200 fold=4 epoch=33 loss=1.9129 val_auc=0.8057
model=transformerconv top_k=200 fold=4 epoch=34 loss=1.7709 val_auc=0.8070
model=transformerconv top_k=200 fold=4 epoch=35 loss=1.7064 val_auc=0.8082
model=transformerconv top_k=200 fold=4 epoch=36 loss=1.5785 val_auc=0.8091
model=transformerconv top_k=200 fold=4 epoch=37 loss=1.6357 val_auc=0.8098
model=transformerconv top_k=200 fold=4 epoch=38 loss=2.0194 val_auc=0.8096
model=transformerconv top_k=200 fold=4 epoch=39 loss=1.8489 val_auc=0.8096
model=transformerconv top_k=200 fold=4 epoch=40 loss=1.9187 val_auc=0.8104
model=transformerconv top_k=200 fold=4 epoch=41 loss=1.6903 val_auc=0.8115
model=transformerconv top_k=200 fold=4 epoch=42 loss=1.6072 val_auc=0.8123
model=transformerconv top_k=200 fold=4 epoch=43 loss=1.7516 val_auc=0.8123
model=transformerconv top_k=200 fold=4 epoch=44 loss=1.6179 val_auc=0.8120
model=transformerconv top_k=200 fold=4 epoch=45 loss=1.7837 val_auc=0.8120
model=transformerconv top_k=200 fold=4 epoch=46 loss=1.6714 val_auc=0.8122
model=transformerconv top_k=200 fold=4 epoch=47 loss=1.5293 val_auc=0.8126
model=transformerconv top_k=200 fold=4 epoch=48 loss=1.4625 val_auc=0.8124
model=transformerconv top_k=200 fold=4 epoch=49 loss=1.4237 val_auc=0.8124
model=transformerconv top_k=200 fold=4 epoch=50 loss=1.4099 val_auc=0.8125
model=transformerconv top_k=200 fold=4 epoch=51 loss=1.3247 val_auc=0.8126
model=transformerconv top_k=200 fold=4 epoch=52 loss=1.4226 val_auc=0.8129
model=transformerconv top_k=200 fold=4 epoch=53 loss=1.4879 val_auc=0.8130
model=transformerconv top_k=200 fold=4 epoch=54 loss=1.5444 val_auc=0.8129
model=transformerconv top_k=200 fold=4 epoch=55 loss=1.4353 val_auc=0.8128
model=transformerconv top_k=200 fold=4 epoch=56 loss=1.3830 val_auc=0.8129
model=transformerconv top_k=200 fold=4 epoch=57 loss=1.3414 val_auc=0.8133
model=transformerconv top_k=200 fold=4 epoch=58 loss=1.3228 val_auc=0.8136
model=transformerconv top_k=200 fold=4 epoch=59 loss=1.6340 val_auc=0.8139
model=transformerconv top_k=200 fold=4 epoch=60 loss=1.3282 val_auc=0.8140
model=transformerconv top_k=200 fold=4 epoch=61 loss=1.3412 val_auc=0.8140
model=transformerconv top_k=200 fold=4 epoch=62 loss=1.4598 val_auc=0.8144
model=transformerconv top_k=200 fold=4 epoch=63 loss=1.4248 val_auc=0.8146
model=transformerconv top_k=200 fold=4 epoch=64 loss=1.2750 val_auc=0.8147
model=transformerconv top_k=200 fold=4 epoch=65 loss=1.5535 val_auc=0.8151
model=transformerconv top_k=200 fold=4 epoch=66 loss=1.6756 val_auc=0.8155
model=transformerconv top_k=200 fold=4 epoch=67 loss=1.4310 val_auc=0.8155
model=transformerconv top_k=200 fold=4 epoch=68 loss=1.2480 val_auc=0.8155
model=transformerconv top_k=200 fold=4 epoch=69 loss=1.5367 val_auc=0.8153
model=transformerconv top_k=200 fold=4 epoch=70 loss=1.7224 val_auc=0.8153
model=transformerconv top_k=200 fold=4 epoch=71 loss=1.5997 val_auc=0.8156
model=transformerconv top_k=200 fold=4 epoch=72 loss=1.2103 val_auc=0.8161
model=transformerconv top_k=200 fold=4 epoch=73 loss=1.4863 val_auc=0.8164
model=transformerconv top_k=200 fold=4 epoch=74 loss=1.5849 val_auc=0.8164
model=transformerconv top_k=200 fold=4 epoch=75 loss=1.5045 val_auc=0.8160
model=transformerconv top_k=200 fold=4 epoch=76 loss=1.2656 val_auc=0.8151
model=transformerconv top_k=200 fold=4 epoch=77 loss=1.3054 val_auc=0.8147
model=transformerconv top_k=200 fold=4 epoch=78 loss=1.3702 val_auc=0.8151
model=transformerconv top_k=200 fold=4 epoch=79 loss=1.4816 val_auc=0.8159
model=transformerconv top_k=200 fold=4 epoch=80 loss=1.1234 val_auc=0.8171
model=transformerconv top_k=200 fold=4 epoch=81 loss=1.3913 val_auc=0.8174
model=transformerconv top_k=200 fold=4 epoch=82 loss=1.5831 val_auc=0.8173
model=transformerconv top_k=200 fold=4 epoch=83 loss=1.4543 val_auc=0.8166
model=transformerconv top_k=200 fold=4 epoch=84 loss=1.2379 val_auc=0.8159
model=transformerconv top_k=200 fold=4 epoch=85 loss=1.2017 val_auc=0.8154
model=transformerconv top_k=200 fold=4 epoch=86 loss=1.1623 val_auc=0.8156
model=transformerconv top_k=200 fold=4 epoch=87 loss=1.1965 val_auc=0.8156
model=transformerconv top_k=200 fold=4 epoch=88 loss=1.0994 val_auc=0.8154
model=transformerconv top_k=200 fold=4 epoch=89 loss=1.1086 val_auc=0.8154
model=transformerconv top_k=200 fold=4 epoch=90 loss=1.1235 val_auc=0.8157
model=transformerconv top_k=200 fold=4 epoch=91 loss=1.0706 val_auc=0.8163
model=transformerconv top_k=200 fold=4 epoch=92 loss=1.0531 val_auc=0.8173
model=transformerconv top_k=200 fold=4 epoch=93 loss=1.0423 val_auc=0.8185
model=transformerconv top_k=200 fold=4 epoch=94 loss=1.0571 val_auc=0.8195
model=transformerconv top_k=200 fold=4 epoch=95 loss=1.0453 val_auc=0.8206
model=transformerconv top_k=200 fold=4 epoch=96 loss=1.2032 val_auc=0.8210
model=transformerconv top_k=200 fold=4 epoch=97 loss=1.1647 val_auc=0.8209
model=transformerconv top_k=200 fold=4 epoch=98 loss=1.0744 val_auc=0.8208
model=transformerconv top_k=200 fold=4 epoch=99 loss=1.0517 val_auc=0.8214
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719233 edges

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=200 fold=5 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718759 edges
model=transformerconv top_k=200 fold=5 epoch=0 loss=15.4718 val_auc=0.5408
model=transformerconv top_k=200 fold=5 epoch=1 loss=13.5465 val_auc=0.6203
model=transformerconv top_k=200 fold=5 epoch=2 loss=8.1194 val_auc=0.7137
model=transformerconv top_k=200 fold=5 epoch=3 loss=4.9226 val_auc=0.7487
model=transformerconv top_k=200 fold=5 epoch=4 loss=4.8940 val_auc=0.7712
model=transformerconv top_k=200 fold=5 epoch=5 loss=4.3738 val_auc=0.7827
model=transformerconv top_k=200 fold=5 epoch=6 loss=6.8102 val_auc=0.7879
model=transformerconv top_k=200 fold=5 epoch=7 loss=7.4502 val_auc=0.7904
model=transformerconv top_k=200 fold=5 epoch=8 loss=4.8762 val_auc=0.7913
model=transformerconv top_k=200 fold=5 epoch=9 loss=4.1154 val_auc=0.7935
model=transformerconv top_k=200 fold=5 epoch=10 loss=4.8580 val_auc=0.7961
model=transformerconv top_k=200 fold=5 epoch=11 loss=3.8393 val_auc=0.7982
model=transformerconv top_k=200 fold=5 epoch=12 loss=4.0668 val_auc=0.8005
model=transformerconv top_k=200 fold=5 epoch=13 loss=3.7222 val_auc=0.8024
model=transformerconv top_k=200 fold=5 epoch=14 loss=4.0706 val_auc=0.8036
model=transformerconv top_k=200 fold=5 epoch=15 loss=3.9553 val_auc=0.8041
model=transformerconv top_k=200 fold=5 epoch=16 loss=4.3574 val_auc=0.8047
model=transformerconv top_k=200 fold=5 epoch=17 loss=4.2799 val_auc=0.8056
model=transformerconv top_k=200 fold=5 epoch=18 loss=3.3529 val_auc=0.8073
model=transformerconv top_k=200 fold=5 epoch=19 loss=3.1889 val_auc=0.8090
model=transformerconv top_k=200 fold=5 epoch=20 loss=3.9662 val_auc=0.8100
model=transformerconv top_k=200 fold=5 epoch=21 loss=4.8532 val_auc=0.8108
model=transformerconv top_k=200 fold=5 epoch=22 loss=4.5938 val_auc=0.8116
model=transformerconv top_k=200 fold=5 epoch=23 loss=3.2176 val_auc=0.8121
model=transformerconv top_k=200 fold=5 epoch=24 loss=3.3064 val_auc=0.8125
model=transformerconv top_k=200 fold=5 epoch=25 loss=3.9035 val_auc=0.8129
model=transformerconv top_k=200 fold=5 epoch=26 loss=3.4643 val_auc=0.8131
model=transformerconv top_k=200 fold=5 epoch=27 loss=2.8258 val_auc=0.8133
model=transformerconv top_k=200 fold=5 epoch=28 loss=3.0624 val_auc=0.8142
model=transformerconv top_k=200 fold=5 epoch=29 loss=3.7123 val_auc=0.8149
model=transformerconv top_k=200 fold=5 epoch=30 loss=3.6355 val_auc=0.8153
model=transformerconv top_k=200 fold=5 epoch=31 loss=3.0125 val_auc=0.8153
model=transformerconv top_k=200 fold=5 epoch=32 loss=2.9866 val_auc=0.8152
model=transformerconv top_k=200 fold=5 epoch=33 loss=2.9796 val_auc=0.8152
model=transformerconv top_k=200 fold=5 epoch=34 loss=2.8921 val_auc=0.8161
model=transformerconv top_k=200 fold=5 epoch=35 loss=3.1402 val_auc=0.8173
model=transformerconv top_k=200 fold=5 epoch=36 loss=2.7181 val_auc=0.8182
model=transformerconv top_k=200 fold=5 epoch=37 loss=3.1656 val_auc=0.8184
model=transformerconv top_k=200 fold=5 epoch=38 loss=2.3008 val_auc=0.8190
model=transformerconv top_k=200 fold=5 epoch=39 loss=2.2860 val_auc=0.8199
model=transformerconv top_k=200 fold=5 epoch=40 loss=2.7930 val_auc=0.8213
model=transformerconv top_k=200 fold=5 epoch=41 loss=2.2456 val_auc=0.8229
model=transformerconv top_k=200 fold=5 epoch=42 loss=2.3562 val_auc=0.8236
model=transformerconv top_k=200 fold=5 epoch=43 loss=2.0082 val_auc=0.8234
model=transformerconv top_k=200 fold=5 epoch=44 loss=2.0734 val_auc=0.8231
model=transformerconv top_k=200 fold=5 epoch=45 loss=2.2039 val_auc=0.8225
model=transformerconv top_k=200 fold=5 epoch=46 loss=2.0830 val_auc=0.8221
model=transformerconv top_k=200 fold=5 epoch=47 loss=2.5523 val_auc=0.8235
model=transformerconv top_k=200 fold=5 epoch=48 loss=3.0706 val_auc=0.8255
model=transformerconv top_k=200 fold=5 epoch=49 loss=2.6476 val_auc=0.8271
model=transformerconv top_k=200 fold=5 epoch=50 loss=1.6883 val_auc=0.8274
model=transformerconv top_k=200 fold=5 epoch=51 loss=2.5062 val_auc=0.8266
model=transformerconv top_k=200 fold=5 epoch=52 loss=2.7748 val_auc=0.8265
model=transformerconv top_k=200 fold=5 epoch=53 loss=2.3582 val_auc=0.8265
model=transformerconv top_k=200 fold=5 epoch=54 loss=1.8874 val_auc=0.8267
model=transformerconv top_k=200 fold=5 epoch=55 loss=2.0574 val_auc=0.8266
model=transformerconv top_k=200 fold=5 epoch=56 loss=2.7985 val_auc=0.8261
model=transformerconv top_k=200 fold=5 epoch=57 loss=2.5740 val_auc=0.8252
model=transformerconv top_k=200 fold=5 epoch=58 loss=2.6168 val_auc=0.8240
model=transformerconv top_k=200 fold=5 epoch=59 loss=1.8969 val_auc=0.8237
model=transformerconv top_k=200 fold=5 epoch=60 loss=2.0468 val_auc=0.8243
model=transformerconv top_k=200 fold=5 epoch=61 loss=2.7839 val_auc=0.8253
model=transformerconv top_k=200 fold=5 epoch=62 loss=2.3789 val_auc=0.8262
transformerconv top_k=200 fold=5: early stopping at epoch 62
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718759 edges

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=200 fold=6 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718481 edges
model=transformerconv top_k=200 fold=6 epoch=0 loss=11.6454 val_auc=0.5012
model=transformerconv top_k=200 fold=6 epoch=1 loss=22.8828 val_auc=0.5944
model=transformerconv top_k=200 fold=6 epoch=2 loss=15.9844 val_auc=0.7367
model=transformerconv top_k=200 fold=6 epoch=3 loss=5.1196 val_auc=0.7427
model=transformerconv top_k=200 fold=6 epoch=4 loss=7.7615 val_auc=0.7532
model=transformerconv top_k=200 fold=6 epoch=5 loss=9.5679 val_auc=0.7631
model=transformerconv top_k=200 fold=6 epoch=6 loss=9.3705 val_auc=0.7702
model=transformerconv top_k=200 fold=6 epoch=7 loss=5.3210 val_auc=0.7726
model=transformerconv top_k=200 fold=6 epoch=8 loss=4.8687 val_auc=0.7761
model=transformerconv top_k=200 fold=6 epoch=9 loss=5.1762 val_auc=0.7788
model=transformerconv top_k=200 fold=6 epoch=10 loss=5.5990 val_auc=0.7809
model=transformerconv top_k=200 fold=6 epoch=11 loss=4.9889 val_auc=0.7835
model=transformerconv top_k=200 fold=6 epoch=12 loss=4.7794 val_auc=0.7855
model=transformerconv top_k=200 fold=6 epoch=13 loss=3.9130 val_auc=0.7867
model=transformerconv top_k=200 fold=6 epoch=14 loss=4.1088 val_auc=0.7877
model=transformerconv top_k=200 fold=6 epoch=15 loss=3.8599 val_auc=0.7896
model=transformerconv top_k=200 fold=6 epoch=16 loss=3.8580 val_auc=0.7915
model=transformerconv top_k=200 fold=6 epoch=17 loss=3.7158 val_auc=0.7933
model=transformerconv top_k=200 fold=6 epoch=18 loss=3.8012 val_auc=0.7967
model=transformerconv top_k=200 fold=6 epoch=19 loss=3.4464 val_auc=0.8003
model=transformerconv top_k=200 fold=6 epoch=20 loss=4.1115 val_auc=0.8031
model=transformerconv top_k=200 fold=6 epoch=21 loss=3.5599 val_auc=0.8041
model=transformerconv top_k=200 fold=6 epoch=22 loss=3.1285 val_auc=0.8050
model=transformerconv top_k=200 fold=6 epoch=23 loss=3.3906 val_auc=0.8057
model=transformerconv top_k=200 fold=6 epoch=24 loss=3.6113 val_auc=0.8064
model=transformerconv top_k=200 fold=6 epoch=25 loss=4.0567 val_auc=0.8074
model=transformerconv top_k=200 fold=6 epoch=26 loss=3.6922 val_auc=0.8081
model=transformerconv top_k=200 fold=6 epoch=27 loss=2.9060 val_auc=0.8094
model=transformerconv top_k=200 fold=6 epoch=28 loss=2.6967 val_auc=0.8105
model=transformerconv top_k=200 fold=6 epoch=29 loss=3.2725 val_auc=0.8120
model=transformerconv top_k=200 fold=6 epoch=30 loss=2.5921 val_auc=0.8136
model=transformerconv top_k=200 fold=6 epoch=31 loss=2.4076 val_auc=0.8150
model=transformerconv top_k=200 fold=6 epoch=32 loss=2.5404 val_auc=0.8161
model=transformerconv top_k=200 fold=6 epoch=33 loss=2.8042 val_auc=0.8169
model=transformerconv top_k=200 fold=6 epoch=34 loss=2.1952 val_auc=0.8174
model=transformerconv top_k=200 fold=6 epoch=35 loss=2.3982 val_auc=0.8182
model=transformerconv top_k=200 fold=6 epoch=36 loss=2.6951 val_auc=0.8190
model=transformerconv top_k=200 fold=6 epoch=37 loss=1.9917 val_auc=0.8196
model=transformerconv top_k=200 fold=6 epoch=38 loss=2.1537 val_auc=0.8200
model=transformerconv top_k=200 fold=6 epoch=39 loss=2.0881 val_auc=0.8209
model=transformerconv top_k=200 fold=6 epoch=40 loss=2.0517 val_auc=0.8217
model=transformerconv top_k=200 fold=6 epoch=41 loss=2.0324 val_auc=0.8224
model=transformerconv top_k=200 fold=6 epoch=42 loss=2.0642 val_auc=0.8228
model=transformerconv top_k=200 fold=6 epoch=43 loss=1.9436 val_auc=0.8235
model=transformerconv top_k=200 fold=6 epoch=44 loss=2.3969 val_auc=0.8241
model=transformerconv top_k=200 fold=6 epoch=45 loss=1.9775 val_auc=0.8245
model=transformerconv top_k=200 fold=6 epoch=46 loss=1.6049 val_auc=0.8248
model=transformerconv top_k=200 fold=6 epoch=47 loss=1.7342 val_auc=0.8249
model=transformerconv top_k=200 fold=6 epoch=48 loss=1.7027 val_auc=0.8254
model=transformerconv top_k=200 fold=6 epoch=49 loss=1.5410 val_auc=0.8261
model=transformerconv top_k=200 fold=6 epoch=50 loss=1.6729 val_auc=0.8267
model=transformerconv top_k=200 fold=6 epoch=51 loss=1.6752 val_auc=0.8271
model=transformerconv top_k=200 fold=6 epoch=52 loss=1.6765 val_auc=0.8273
model=transformerconv top_k=200 fold=6 epoch=53 loss=1.6347 val_auc=0.8279
model=transformerconv top_k=200 fold=6 epoch=54 loss=1.5888 val_auc=0.8287
model=transformerconv top_k=200 fold=6 epoch=55 loss=1.8007 val_auc=0.8288
model=transformerconv top_k=200 fold=6 epoch=56 loss=1.6306 val_auc=0.8287
model=transformerconv top_k=200 fold=6 epoch=57 loss=1.4220 val_auc=0.8283
model=transformerconv top_k=200 fold=6 epoch=58 loss=1.6002 val_auc=0.8282
model=transformerconv top_k=200 fold=6 epoch=59 loss=1.6581 val_auc=0.8283
model=transformerconv top_k=200 fold=6 epoch=60 loss=1.5842 val_auc=0.8288
model=transformerconv top_k=200 fold=6 epoch=61 loss=1.8617 val_auc=0.8290
model=transformerconv top_k=200 fold=6 epoch=62 loss=1.7895 val_auc=0.8289
model=transformerconv top_k=200 fold=6 epoch=63 loss=1.5879 val_auc=0.8284
model=transformerconv top_k=200 fold=6 epoch=64 loss=1.5451 val_auc=0.8270
model=transformerconv top_k=200 fold=6 epoch=65 loss=1.4362 val_auc=0.8261
model=transformerconv top_k=200 fold=6 epoch=66 loss=1.9028 val_auc=0.8265
model=transformerconv top_k=200 fold=6 epoch=67 loss=1.7295 val_auc=0.8278
model=transformerconv top_k=200 fold=6 epoch=68 loss=1.5184 val_auc=0.8291
model=transformerconv top_k=200 fold=6 epoch=69 loss=1.3944 val_auc=0.8297
model=transformerconv top_k=200 fold=6 epoch=70 loss=1.4898 val_auc=0.8298
model=transformerconv top_k=200 fold=6 epoch=71 loss=1.4454 val_auc=0.8293
model=transformerconv top_k=200 fold=6 epoch=72 loss=1.3945 val_auc=0.8279
model=transformerconv top_k=200 fold=6 epoch=73 loss=1.3554 val_auc=0.8273
model=transformerconv top_k=200 fold=6 epoch=74 loss=1.6620 val_auc=0.8275
model=transformerconv top_k=200 fold=6 epoch=75 loss=1.6364 val_auc=0.8288
model=transformerconv top_k=200 fold=6 epoch=76 loss=1.3016 val_auc=0.8301
model=transformerconv top_k=200 fold=6 epoch=77 loss=1.2848 val_auc=0.8308
model=transformerconv top_k=200 fold=6 epoch=78 loss=1.2891 val_auc=0.8311
model=transformerconv top_k=200 fold=6 epoch=79 loss=1.3732 val_auc=0.8309
model=transformerconv top_k=200 fold=6 epoch=80 loss=1.2103 val_auc=0.8309
model=transformerconv top_k=200 fold=6 epoch=81 loss=1.2457 val_auc=0.8314
model=transformerconv top_k=200 fold=6 epoch=82 loss=1.3266 val_auc=0.8324
model=transformerconv top_k=200 fold=6 epoch=83 loss=1.1734 val_auc=0.8332
model=transformerconv top_k=200 fold=6 epoch=84 loss=1.1678 val_auc=0.8337
model=transformerconv top_k=200 fold=6 epoch=85 loss=1.2263 val_auc=0.8337
model=transformerconv top_k=200 fold=6 epoch=86 loss=1.1614 val_auc=0.8334
model=transformerconv top_k=200 fold=6 epoch=87 loss=1.1514 val_auc=0.8334
model=transformerconv top_k=200 fold=6 epoch=88 loss=1.1714 val_auc=0.8341
model=transformerconv top_k=200 fold=6 epoch=89 loss=1.1882 val_auc=0.8350
model=transformerconv top_k=200 fold=6 epoch=90 loss=1.1288 val_auc=0.8357
model=transformerconv top_k=200 fold=6 epoch=91 loss=1.3145 val_auc=0.8359
model=transformerconv top_k=200 fold=6 epoch=92 loss=1.2795 val_auc=0.8355
model=transformerconv top_k=200 fold=6 epoch=93 loss=1.1787 val_auc=0.8342
model=transformerconv top_k=200 fold=6 epoch=94 loss=1.2282 val_auc=0.8339
model=transformerconv top_k=200 fold=6 epoch=95 loss=1.2927 val_auc=0.8348
model=transformerconv top_k=200 fold=6 epoch=96 loss=1.1669 val_auc=0.8363
model=transformerconv top_k=200 fold=6 epoch=97 loss=1.1272 val_auc=0.8370
model=transformerconv top_k=200 fold=6 epoch=98 loss=1.1188 val_auc=0.8369
model=transformerconv top_k=200 fold=6 epoch=99 loss=1.0777 val_auc=0.8364
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718481 edges

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=200 fold=7 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719141 edges
model=transformerconv top_k=200 fold=7 epoch=0 loss=6.5049 val_auc=0.5000
model=transformerconv top_k=200 fold=7 epoch=1 loss=31.3344 val_auc=0.5126
model=transformerconv top_k=200 fold=7 epoch=2 loss=19.4934 val_auc=0.7683
model=transformerconv top_k=200 fold=7 epoch=3 loss=7.6097 val_auc=0.7688
model=transformerconv top_k=200 fold=7 epoch=4 loss=5.9102 val_auc=0.7686
model=transformerconv top_k=200 fold=7 epoch=5 loss=7.7632 val_auc=0.7689
model=transformerconv top_k=200 fold=7 epoch=6 loss=6.8173 val_auc=0.7690
model=transformerconv top_k=200 fold=7 epoch=7 loss=4.7772 val_auc=0.7706
model=transformerconv top_k=200 fold=7 epoch=8 loss=7.0774 val_auc=0.7739
model=transformerconv top_k=200 fold=7 epoch=9 loss=6.4283 val_auc=0.7760
model=transformerconv top_k=200 fold=7 epoch=10 loss=7.0383 val_auc=0.7773
model=transformerconv top_k=200 fold=7 epoch=11 loss=6.5312 val_auc=0.7779
model=transformerconv top_k=200 fold=7 epoch=12 loss=3.9731 val_auc=0.7786
model=transformerconv top_k=200 fold=7 epoch=13 loss=4.3130 val_auc=0.7796
model=transformerconv top_k=200 fold=7 epoch=14 loss=4.6452 val_auc=0.7815
model=transformerconv top_k=200 fold=7 epoch=15 loss=4.7725 val_auc=0.7835
model=transformerconv top_k=200 fold=7 epoch=16 loss=3.6402 val_auc=0.7855
model=transformerconv top_k=200 fold=7 epoch=17 loss=4.4696 val_auc=0.7872
model=transformerconv top_k=200 fold=7 epoch=18 loss=3.4242 val_auc=0.7893
model=transformerconv top_k=200 fold=7 epoch=19 loss=3.7522 val_auc=0.7914
model=transformerconv top_k=200 fold=7 epoch=20 loss=3.3237 val_auc=0.7934
model=transformerconv top_k=200 fold=7 epoch=21 loss=3.4814 val_auc=0.7942
model=transformerconv top_k=200 fold=7 epoch=22 loss=3.7390 val_auc=0.7953
model=transformerconv top_k=200 fold=7 epoch=23 loss=3.4790 val_auc=0.7961
model=transformerconv top_k=200 fold=7 epoch=24 loss=3.1553 val_auc=0.7969
model=transformerconv top_k=200 fold=7 epoch=25 loss=3.7774 val_auc=0.7980
model=transformerconv top_k=200 fold=7 epoch=26 loss=4.5445 val_auc=0.7988
model=transformerconv top_k=200 fold=7 epoch=27 loss=4.1451 val_auc=0.7993
model=transformerconv top_k=200 fold=7 epoch=28 loss=3.4867 val_auc=0.7995
model=transformerconv top_k=200 fold=7 epoch=29 loss=2.6732 val_auc=0.7999
model=transformerconv top_k=200 fold=7 epoch=30 loss=2.8723 val_auc=0.8006
model=transformerconv top_k=200 fold=7 epoch=31 loss=3.0056 val_auc=0.8012
model=transformerconv top_k=200 fold=7 epoch=32 loss=2.4939 val_auc=0.8024
model=transformerconv top_k=200 fold=7 epoch=33 loss=2.7760 val_auc=0.8032
model=transformerconv top_k=200 fold=7 epoch=34 loss=2.6259 val_auc=0.8039
model=transformerconv top_k=200 fold=7 epoch=35 loss=2.6172 val_auc=0.8046
model=transformerconv top_k=200 fold=7 epoch=36 loss=2.4252 val_auc=0.8052
model=transformerconv top_k=200 fold=7 epoch=37 loss=2.3720 val_auc=0.8058
model=transformerconv top_k=200 fold=7 epoch=38 loss=2.6258 val_auc=0.8063
model=transformerconv top_k=200 fold=7 epoch=39 loss=2.4210 val_auc=0.8068
model=transformerconv top_k=200 fold=7 epoch=40 loss=2.1506 val_auc=0.8075
model=transformerconv top_k=200 fold=7 epoch=41 loss=2.2105 val_auc=0.8084
model=transformerconv top_k=200 fold=7 epoch=42 loss=2.8249 val_auc=0.8089
model=transformerconv top_k=200 fold=7 epoch=43 loss=2.3298 val_auc=0.8092
model=transformerconv top_k=200 fold=7 epoch=44 loss=2.0421 val_auc=0.8097
model=transformerconv top_k=200 fold=7 epoch=45 loss=1.9366 val_auc=0.8100
model=transformerconv top_k=200 fold=7 epoch=46 loss=2.0545 val_auc=0.8107
model=transformerconv top_k=200 fold=7 epoch=47 loss=1.8181 val_auc=0.8109
model=transformerconv top_k=200 fold=7 epoch=48 loss=1.8094 val_auc=0.8098
model=transformerconv top_k=200 fold=7 epoch=49 loss=1.9178 val_auc=0.8099
model=transformerconv top_k=200 fold=7 epoch=50 loss=2.1015 val_auc=0.8104
model=transformerconv top_k=200 fold=7 epoch=51 loss=1.9572 val_auc=0.8108
model=transformerconv top_k=200 fold=7 epoch=52 loss=1.7474 val_auc=0.8120
model=transformerconv top_k=200 fold=7 epoch=53 loss=1.8816 val_auc=0.8133
model=transformerconv top_k=200 fold=7 epoch=54 loss=1.5889 val_auc=0.8142
model=transformerconv top_k=200 fold=7 epoch=55 loss=1.6470 val_auc=0.8152
model=transformerconv top_k=200 fold=7 epoch=56 loss=1.7359 val_auc=0.8158
model=transformerconv top_k=200 fold=7 epoch=57 loss=1.4994 val_auc=0.8158
model=transformerconv top_k=200 fold=7 epoch=58 loss=1.4944 val_auc=0.8162
model=transformerconv top_k=200 fold=7 epoch=59 loss=1.5518 val_auc=0.8167
model=transformerconv top_k=200 fold=7 epoch=60 loss=1.6261 val_auc=0.8172
model=transformerconv top_k=200 fold=7 epoch=61 loss=1.7342 val_auc=0.8174
model=transformerconv top_k=200 fold=7 epoch=62 loss=1.7069 val_auc=0.8175
model=transformerconv top_k=200 fold=7 epoch=63 loss=1.5552 val_auc=0.8177
model=transformerconv top_k=200 fold=7 epoch=64 loss=1.3892 val_auc=0.8177
model=transformerconv top_k=200 fold=7 epoch=65 loss=1.3725 val_auc=0.8181
model=transformerconv top_k=200 fold=7 epoch=66 loss=1.3351 val_auc=0.8187
model=transformerconv top_k=200 fold=7 epoch=67 loss=1.4996 val_auc=0.8191
model=transformerconv top_k=200 fold=7 epoch=68 loss=1.6051 val_auc=0.8193
model=transformerconv top_k=200 fold=7 epoch=69 loss=1.2859 val_auc=0.8195
model=transformerconv top_k=200 fold=7 epoch=70 loss=1.3964 val_auc=0.8184
model=transformerconv top_k=200 fold=7 epoch=71 loss=1.6134 val_auc=0.8174
model=transformerconv top_k=200 fold=7 epoch=72 loss=1.7741 val_auc=0.8176
model=transformerconv top_k=200 fold=7 epoch=73 loss=1.6326 val_auc=0.8186
model=transformerconv top_k=200 fold=7 epoch=74 loss=1.5687 val_auc=0.8201
model=transformerconv top_k=200 fold=7 epoch=75 loss=1.3066 val_auc=0.8206
model=transformerconv top_k=200 fold=7 epoch=76 loss=1.3277 val_auc=0.8209
model=transformerconv top_k=200 fold=7 epoch=77 loss=1.4572 val_auc=0.8208
model=transformerconv top_k=200 fold=7 epoch=78 loss=1.4031 val_auc=0.8207
model=transformerconv top_k=200 fold=7 epoch=79 loss=1.2979 val_auc=0.8208
model=transformerconv top_k=200 fold=7 epoch=80 loss=1.3052 val_auc=0.8215
model=transformerconv top_k=200 fold=7 epoch=81 loss=1.3435 val_auc=0.8219
model=transformerconv top_k=200 fold=7 epoch=82 loss=1.2944 val_auc=0.8219
model=transformerconv top_k=200 fold=7 epoch=83 loss=1.2616 val_auc=0.8217
model=transformerconv top_k=200 fold=7 epoch=84 loss=1.1537 val_auc=0.8215
model=transformerconv top_k=200 fold=7 epoch=85 loss=1.2163 val_auc=0.8218
model=transformerconv top_k=200 fold=7 epoch=86 loss=1.2139 val_auc=0.8220
model=transformerconv top_k=200 fold=7 epoch=87 loss=1.2319 val_auc=0.8222
model=transformerconv top_k=200 fold=7 epoch=88 loss=1.1673 val_auc=0.8226
model=transformerconv top_k=200 fold=7 epoch=89 loss=1.2099 val_auc=0.8230
model=transformerconv top_k=200 fold=7 epoch=90 loss=1.2620 val_auc=0.8235
model=transformerconv top_k=200 fold=7 epoch=91 loss=1.3537 val_auc=0.8239
model=transformerconv top_k=200 fold=7 epoch=92 loss=1.2001 val_auc=0.8242
model=transformerconv top_k=200 fold=7 epoch=93 loss=1.2174 val_auc=0.8247
model=transformerconv top_k=200 fold=7 epoch=94 loss=1.1662 val_auc=0.8251
model=transformerconv top_k=200 fold=7 epoch=95 loss=1.1948 val_auc=0.8253
model=transformerconv top_k=200 fold=7 epoch=96 loss=1.1105 val_auc=0.8256
model=transformerconv top_k=200 fold=7 epoch=97 loss=1.1134 val_auc=0.8260
model=transformerconv top_k=200 fold=7 epoch=98 loss=1.1932 val_auc=0.8262
model=transformerconv top_k=200 fold=7 epoch=99 loss=1.1289 val_auc=0.8260
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719141 edges

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=200 fold=8 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718578 edges
model=transformerconv top_k=200 fold=8 epoch=0 loss=6.7863 val_auc=0.5146
model=transformerconv top_k=200 fold=8 epoch=1 loss=22.9524 val_auc=0.5838
model=transformerconv top_k=200 fold=8 epoch=2 loss=15.6408 val_auc=0.7564
model=transformerconv top_k=200 fold=8 epoch=3 loss=4.8247 val_auc=0.7643
model=transformerconv top_k=200 fold=8 epoch=4 loss=13.4772 val_auc=0.7670
model=transformerconv top_k=200 fold=8 epoch=5 loss=15.6269 val_auc=0.7670
model=transformerconv top_k=200 fold=8 epoch=6 loss=12.2693 val_auc=0.7655
model=transformerconv top_k=200 fold=8 epoch=7 loss=6.1985 val_auc=0.7658
model=transformerconv top_k=200 fold=8 epoch=8 loss=4.9928 val_auc=0.7672
model=transformerconv top_k=200 fold=8 epoch=9 loss=7.6221 val_auc=0.7689
model=transformerconv top_k=200 fold=8 epoch=10 loss=5.4564 val_auc=0.7706
model=transformerconv top_k=200 fold=8 epoch=11 loss=4.9111 val_auc=0.7722
model=transformerconv top_k=200 fold=8 epoch=12 loss=3.1195 val_auc=0.7762
model=transformerconv top_k=200 fold=8 epoch=13 loss=3.8279 val_auc=0.7786
model=transformerconv top_k=200 fold=8 epoch=14 loss=4.0725 val_auc=0.7802
model=transformerconv top_k=200 fold=8 epoch=15 loss=3.1677 val_auc=0.7814
model=transformerconv top_k=200 fold=8 epoch=16 loss=3.3321 val_auc=0.7831
model=transformerconv top_k=200 fold=8 epoch=17 loss=3.7967 val_auc=0.7848
model=transformerconv top_k=200 fold=8 epoch=18 loss=4.0624 val_auc=0.7861
model=transformerconv top_k=200 fold=8 epoch=19 loss=2.7875 val_auc=0.7882
model=transformerconv top_k=200 fold=8 epoch=20 loss=3.1299 val_auc=0.7904
model=transformerconv top_k=200 fold=8 epoch=21 loss=3.1102 val_auc=0.7922
model=transformerconv top_k=200 fold=8 epoch=22 loss=2.9245 val_auc=0.7941
model=transformerconv top_k=200 fold=8 epoch=23 loss=2.8439 val_auc=0.7958
model=transformerconv top_k=200 fold=8 epoch=24 loss=3.5416 val_auc=0.7972
model=transformerconv top_k=200 fold=8 epoch=25 loss=3.1966 val_auc=0.7980
model=transformerconv top_k=200 fold=8 epoch=26 loss=3.3446 val_auc=0.7980
model=transformerconv top_k=200 fold=8 epoch=27 loss=2.7452 val_auc=0.7981
model=transformerconv top_k=200 fold=8 epoch=28 loss=2.3234 val_auc=0.7985
model=transformerconv top_k=200 fold=8 epoch=29 loss=3.5232 val_auc=0.7988
model=transformerconv top_k=200 fold=8 epoch=30 loss=2.6324 val_auc=0.7994
model=transformerconv top_k=200 fold=8 epoch=31 loss=2.3104 val_auc=0.8004
model=transformerconv top_k=200 fold=8 epoch=32 loss=2.4169 val_auc=0.8006
model=transformerconv top_k=200 fold=8 epoch=33 loss=3.3210 val_auc=0.8006
model=transformerconv top_k=200 fold=8 epoch=34 loss=2.5620 val_auc=0.8003
model=transformerconv top_k=200 fold=8 epoch=35 loss=2.1844 val_auc=0.8000
model=transformerconv top_k=200 fold=8 epoch=36 loss=2.0385 val_auc=0.8010
model=transformerconv top_k=200 fold=8 epoch=37 loss=2.4456 val_auc=0.8016
model=transformerconv top_k=200 fold=8 epoch=38 loss=2.4040 val_auc=0.8017
model=transformerconv top_k=200 fold=8 epoch=39 loss=2.1828 val_auc=0.8020
model=transformerconv top_k=200 fold=8 epoch=40 loss=2.2529 val_auc=0.8025
model=transformerconv top_k=200 fold=8 epoch=41 loss=2.6688 val_auc=0.8027
model=transformerconv top_k=200 fold=8 epoch=42 loss=2.3886 val_auc=0.8026
model=transformerconv top_k=200 fold=8 epoch=43 loss=1.8575 val_auc=0.8024
model=transformerconv top_k=200 fold=8 epoch=44 loss=1.9682 val_auc=0.8027
model=transformerconv top_k=200 fold=8 epoch=45 loss=2.7064 val_auc=0.8035
model=transformerconv top_k=200 fold=8 epoch=46 loss=2.5595 val_auc=0.8041
model=transformerconv top_k=200 fold=8 epoch=47 loss=1.8296 val_auc=0.8048
model=transformerconv top_k=200 fold=8 epoch=48 loss=1.9940 val_auc=0.8055
model=transformerconv top_k=200 fold=8 epoch=49 loss=2.2587 val_auc=0.8062
model=transformerconv top_k=200 fold=8 epoch=50 loss=1.9728 val_auc=0.8068
model=transformerconv top_k=200 fold=8 epoch=51 loss=1.8162 val_auc=0.8079
model=transformerconv top_k=200 fold=8 epoch=52 loss=1.6985 val_auc=0.8089
model=transformerconv top_k=200 fold=8 epoch=53 loss=1.9600 val_auc=0.8098
model=transformerconv top_k=200 fold=8 epoch=54 loss=1.7412 val_auc=0.8105
model=transformerconv top_k=200 fold=8 epoch=55 loss=1.7396 val_auc=0.8110
model=transformerconv top_k=200 fold=8 epoch=56 loss=1.7996 val_auc=0.8114
model=transformerconv top_k=200 fold=8 epoch=57 loss=1.7829 val_auc=0.8117
model=transformerconv top_k=200 fold=8 epoch=58 loss=1.5876 val_auc=0.8119
model=transformerconv top_k=200 fold=8 epoch=59 loss=1.9459 val_auc=0.8118
model=transformerconv top_k=200 fold=8 epoch=60 loss=2.0669 val_auc=0.8120
model=transformerconv top_k=200 fold=8 epoch=61 loss=1.6335 val_auc=0.8123
model=transformerconv top_k=200 fold=8 epoch=62 loss=1.6143 val_auc=0.8124
model=transformerconv top_k=200 fold=8 epoch=63 loss=1.6136 val_auc=0.8123
model=transformerconv top_k=200 fold=8 epoch=64 loss=1.4207 val_auc=0.8125
model=transformerconv top_k=200 fold=8 epoch=65 loss=1.4322 val_auc=0.8131
model=transformerconv top_k=200 fold=8 epoch=66 loss=1.4227 val_auc=0.8139
model=transformerconv top_k=200 fold=8 epoch=67 loss=1.5175 val_auc=0.8145
model=transformerconv top_k=200 fold=8 epoch=68 loss=1.4647 val_auc=0.8148
model=transformerconv top_k=200 fold=8 epoch=69 loss=1.4859 val_auc=0.8150
model=transformerconv top_k=200 fold=8 epoch=70 loss=1.4840 val_auc=0.8152
model=transformerconv top_k=200 fold=8 epoch=71 loss=1.3712 val_auc=0.8156
model=transformerconv top_k=200 fold=8 epoch=72 loss=1.4337 val_auc=0.8159
model=transformerconv top_k=200 fold=8 epoch=73 loss=1.5750 val_auc=0.8158
model=transformerconv top_k=200 fold=8 epoch=74 loss=1.4355 val_auc=0.8157
model=transformerconv top_k=200 fold=8 epoch=75 loss=1.3232 val_auc=0.8157
model=transformerconv top_k=200 fold=8 epoch=76 loss=1.3945 val_auc=0.8161
model=transformerconv top_k=200 fold=8 epoch=77 loss=1.2590 val_auc=0.8166
model=transformerconv top_k=200 fold=8 epoch=78 loss=1.5615 val_auc=0.8169
model=transformerconv top_k=200 fold=8 epoch=79 loss=1.4479 val_auc=0.8170
model=transformerconv top_k=200 fold=8 epoch=80 loss=1.4105 val_auc=0.8170
model=transformerconv top_k=200 fold=8 epoch=81 loss=1.2354 val_auc=0.8172
model=transformerconv top_k=200 fold=8 epoch=82 loss=1.3305 val_auc=0.8177
model=transformerconv top_k=200 fold=8 epoch=83 loss=1.2755 val_auc=0.8181
model=transformerconv top_k=200 fold=8 epoch=84 loss=1.1471 val_auc=0.8185
model=transformerconv top_k=200 fold=8 epoch=85 loss=1.2002 val_auc=0.8187
model=transformerconv top_k=200 fold=8 epoch=86 loss=1.2417 val_auc=0.8190
model=transformerconv top_k=200 fold=8 epoch=87 loss=1.2318 val_auc=0.8192
model=transformerconv top_k=200 fold=8 epoch=88 loss=1.2243 val_auc=0.8193
model=transformerconv top_k=200 fold=8 epoch=89 loss=1.2997 val_auc=0.8193
model=transformerconv top_k=200 fold=8 epoch=90 loss=1.3668 val_auc=0.8192
model=transformerconv top_k=200 fold=8 epoch=91 loss=1.2086 val_auc=0.8189
model=transformerconv top_k=200 fold=8 epoch=92 loss=1.1262 val_auc=0.8193
model=transformerconv top_k=200 fold=8 epoch=93 loss=1.0698 val_auc=0.8204
model=transformerconv top_k=200 fold=8 epoch=94 loss=1.1535 val_auc=0.8214
model=transformerconv top_k=200 fold=8 epoch=95 loss=1.1459 val_auc=0.8219
model=transformerconv top_k=200 fold=8 epoch=96 loss=1.1609 val_auc=0.8223
model=transformerconv top_k=200 fold=8 epoch=97 loss=1.2377 val_auc=0.8227
model=transformerconv top_k=200 fold=8 epoch=98 loss=1.1934 val_auc=0.8233
model=transformerconv top_k=200 fold=8 epoch=99 loss=1.2448 val_auc=0.8236
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718578 edges

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=200 fold=9 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718994 edges
model=transformerconv top_k=200 fold=9 epoch=0 loss=6.3360 val_auc=0.7007
model=transformerconv top_k=200 fold=9 epoch=1 loss=26.7336 val_auc=0.7346
model=transformerconv top_k=200 fold=9 epoch=2 loss=19.1883 val_auc=0.7460
model=transformerconv top_k=200 fold=9 epoch=3 loss=6.3707 val_auc=0.7082
model=transformerconv top_k=200 fold=9 epoch=4 loss=14.3524 val_auc=0.5669
model=transformerconv top_k=200 fold=9 epoch=5 loss=17.5078 val_auc=0.7210
model=transformerconv top_k=200 fold=9 epoch=6 loss=11.6922 val_auc=0.7579
model=transformerconv top_k=200 fold=9 epoch=7 loss=7.9797 val_auc=0.7611
model=transformerconv top_k=200 fold=9 epoch=8 loss=4.8686 val_auc=0.7638
model=transformerconv top_k=200 fold=9 epoch=9 loss=6.1520 val_auc=0.7656
model=transformerconv top_k=200 fold=9 epoch=10 loss=5.0963 val_auc=0.7668
model=transformerconv top_k=200 fold=9 epoch=11 loss=4.6468 val_auc=0.7669
model=transformerconv top_k=200 fold=9 epoch=12 loss=4.2019 val_auc=0.7679
model=transformerconv top_k=200 fold=9 epoch=13 loss=5.0325 val_auc=0.7694
model=transformerconv top_k=200 fold=9 epoch=14 loss=6.2249 val_auc=0.7721
model=transformerconv top_k=200 fold=9 epoch=15 loss=3.7478 val_auc=0.7750
model=transformerconv top_k=200 fold=9 epoch=16 loss=2.9595 val_auc=0.7774
model=transformerconv top_k=200 fold=9 epoch=17 loss=4.6319 val_auc=0.7787
model=transformerconv top_k=200 fold=9 epoch=18 loss=4.4513 val_auc=0.7790
model=transformerconv top_k=200 fold=9 epoch=19 loss=3.2486 val_auc=0.7786
model=transformerconv top_k=200 fold=9 epoch=20 loss=2.9764 val_auc=0.7796
model=transformerconv top_k=200 fold=9 epoch=21 loss=3.1437 val_auc=0.7813
model=transformerconv top_k=200 fold=9 epoch=22 loss=3.2001 val_auc=0.7832
model=transformerconv top_k=200 fold=9 epoch=23 loss=2.6310 val_auc=0.7851
model=transformerconv top_k=200 fold=9 epoch=24 loss=3.0970 val_auc=0.7861
model=transformerconv top_k=200 fold=9 epoch=25 loss=3.5502 val_auc=0.7868
model=transformerconv top_k=200 fold=9 epoch=26 loss=3.2169 val_auc=0.7871
model=transformerconv top_k=200 fold=9 epoch=27 loss=2.6047 val_auc=0.7883
model=transformerconv top_k=200 fold=9 epoch=28 loss=2.7843 val_auc=0.7905
model=transformerconv top_k=200 fold=9 epoch=29 loss=3.3940 val_auc=0.7932
model=transformerconv top_k=200 fold=9 epoch=30 loss=3.0861 val_auc=0.7954
model=transformerconv top_k=200 fold=9 epoch=31 loss=2.9020 val_auc=0.7969
model=transformerconv top_k=200 fold=9 epoch=32 loss=2.5987 val_auc=0.7978
model=transformerconv top_k=200 fold=9 epoch=33 loss=2.8474 val_auc=0.7986
model=transformerconv top_k=200 fold=9 epoch=34 loss=2.9958 val_auc=0.7990
model=transformerconv top_k=200 fold=9 epoch=35 loss=2.4888 val_auc=0.7995
model=transformerconv top_k=200 fold=9 epoch=36 loss=2.2393 val_auc=0.7994
model=transformerconv top_k=200 fold=9 epoch=37 loss=2.2866 val_auc=0.7997
model=transformerconv top_k=200 fold=9 epoch=38 loss=2.8049 val_auc=0.8000
model=transformerconv top_k=200 fold=9 epoch=39 loss=2.1522 val_auc=0.8004
model=transformerconv top_k=200 fold=9 epoch=40 loss=2.1189 val_auc=0.8008
model=transformerconv top_k=200 fold=9 epoch=41 loss=2.2408 val_auc=0.8009
model=transformerconv top_k=200 fold=9 epoch=42 loss=2.1754 val_auc=0.8010
model=transformerconv top_k=200 fold=9 epoch=43 loss=2.6053 val_auc=0.8010
model=transformerconv top_k=200 fold=9 epoch=44 loss=1.8808 val_auc=0.8016
model=transformerconv top_k=200 fold=9 epoch=45 loss=2.0921 val_auc=0.8024
model=transformerconv top_k=200 fold=9 epoch=46 loss=2.0949 val_auc=0.8037
model=transformerconv top_k=200 fold=9 epoch=47 loss=1.8884 val_auc=0.8052
model=transformerconv top_k=200 fold=9 epoch=48 loss=2.1762 val_auc=0.8064
model=transformerconv top_k=200 fold=9 epoch=49 loss=2.2023 val_auc=0.8071
model=transformerconv top_k=200 fold=9 epoch=50 loss=2.0947 val_auc=0.8074
model=transformerconv top_k=200 fold=9 epoch=51 loss=1.8368 val_auc=0.8073
model=transformerconv top_k=200 fold=9 epoch=52 loss=1.7901 val_auc=0.8074
model=transformerconv top_k=200 fold=9 epoch=53 loss=2.4356 val_auc=0.8076
model=transformerconv top_k=200 fold=9 epoch=54 loss=2.1052 val_auc=0.8083
model=transformerconv top_k=200 fold=9 epoch=55 loss=1.9055 val_auc=0.8092
model=transformerconv top_k=200 fold=9 epoch=56 loss=1.7714 val_auc=0.8095
model=transformerconv top_k=200 fold=9 epoch=57 loss=1.7826 val_auc=0.8097
model=transformerconv top_k=200 fold=9 epoch=58 loss=1.6851 val_auc=0.8100
model=transformerconv top_k=200 fold=9 epoch=59 loss=1.6073 val_auc=0.8101
model=transformerconv top_k=200 fold=9 epoch=60 loss=1.6394 val_auc=0.8102
model=transformerconv top_k=200 fold=9 epoch=61 loss=1.8502 val_auc=0.8103
model=transformerconv top_k=200 fold=9 epoch=62 loss=1.7358 val_auc=0.8105
model=transformerconv top_k=200 fold=9 epoch=63 loss=1.5010 val_auc=0.8109
model=transformerconv top_k=200 fold=9 epoch=64 loss=1.4366 val_auc=0.8115
model=transformerconv top_k=200 fold=9 epoch=65 loss=1.5820 val_auc=0.8120
model=transformerconv top_k=200 fold=9 epoch=66 loss=1.5465 val_auc=0.8119
model=transformerconv top_k=200 fold=9 epoch=67 loss=1.5535 val_auc=0.8119
model=transformerconv top_k=200 fold=9 epoch=68 loss=1.8366 val_auc=0.8122
model=transformerconv top_k=200 fold=9 epoch=69 loss=1.7174 val_auc=0.8131
model=transformerconv top_k=200 fold=9 epoch=70 loss=1.4814 val_auc=0.8137
model=transformerconv top_k=200 fold=9 epoch=71 loss=1.5132 val_auc=0.8139
model=transformerconv top_k=200 fold=9 epoch=72 loss=2.0104 val_auc=0.8137
model=transformerconv top_k=200 fold=9 epoch=73 loss=2.1212 val_auc=0.8135
model=transformerconv top_k=200 fold=9 epoch=74 loss=1.8678 val_auc=0.8132
model=transformerconv top_k=200 fold=9 epoch=75 loss=1.6767 val_auc=0.8127
model=transformerconv top_k=200 fold=9 epoch=76 loss=1.3511 val_auc=0.8124
model=transformerconv top_k=200 fold=9 epoch=77 loss=1.7824 val_auc=0.8126
model=transformerconv top_k=200 fold=9 epoch=78 loss=1.4343 val_auc=0.8130
model=transformerconv top_k=200 fold=9 epoch=79 loss=1.6031 val_auc=0.8122
model=transformerconv top_k=200 fold=9 epoch=80 loss=1.4286 val_auc=0.8119
model=transformerconv top_k=200 fold=9 epoch=81 loss=1.3502 val_auc=0.8125
model=transformerconv top_k=200 fold=9 epoch=82 loss=1.3073 val_auc=0.8132
model=transformerconv top_k=200 fold=9 epoch=83 loss=1.2701 val_auc=0.8141
model=transformerconv top_k=200 fold=9 epoch=84 loss=1.3740 val_auc=0.8148
model=transformerconv top_k=200 fold=9 epoch=85 loss=1.4632 val_auc=0.8154
model=transformerconv top_k=200 fold=9 epoch=86 loss=1.3721 val_auc=0.8155
model=transformerconv top_k=200 fold=9 epoch=87 loss=1.3703 val_auc=0.8158
model=transformerconv top_k=200 fold=9 epoch=88 loss=1.5372 val_auc=0.8165
model=transformerconv top_k=200 fold=9 epoch=89 loss=1.4657 val_auc=0.8175
model=transformerconv top_k=200 fold=9 epoch=90 loss=1.2840 val_auc=0.8183
model=transformerconv top_k=200 fold=9 epoch=91 loss=1.4286 val_auc=0.8190
model=transformerconv top_k=200 fold=9 epoch=92 loss=1.6853 val_auc=0.8198
model=transformerconv top_k=200 fold=9 epoch=93 loss=1.6225 val_auc=0.8200
model=transformerconv top_k=200 fold=9 epoch=94 loss=1.3746 val_auc=0.8180
model=transformerconv top_k=200 fold=9 epoch=95 loss=1.2291 val_auc=0.8164
model=transformerconv top_k=200 fold=9 epoch=96 loss=1.3710 val_auc=0.8169
model=transformerconv top_k=200 fold=9 epoch=97 loss=1.2607 val_auc=0.8186
model=transformerconv top_k=200 fold=9 epoch=98 loss=1.2281 val_auc=0.8192
model=transformerconv top_k=200 fold=9 epoch=99 loss=1.2732 val_auc=0.8186
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718994 edges

query FAISS top_k=200:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=200:   0%|          | 0/35 [00:00<?, ?it/s]

######## Model=transformerconv top_k=500 ########

===== Model=transformerconv top_k=500 fold=0 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718731 edges
model=transformerconv top_k=500 fold=0 epoch=0 loss=7.7099 val_auc=0.6202
model=transformerconv top_k=500 fold=0 epoch=1 loss=23.3246 val_auc=0.6649
model=transformerconv top_k=500 fold=0 epoch=2 loss=17.9957 val_auc=0.6883
model=transformerconv top_k=500 fold=0 epoch=3 loss=7.4196 val_auc=0.6846
model=transformerconv top_k=500 fold=0 epoch=4 loss=7.4537 val_auc=0.6929
model=transformerconv top_k=500 fold=0 epoch=5 loss=10.1899 val_auc=0.7033
model=transformerconv top_k=500 fold=0 epoch=6 loss=7.2158 val_auc=0.7156
model=transformerconv top_k=500 fold=0 epoch=7 loss=4.5547 val_auc=0.7288
model=transformerconv top_k=500 fold=0 epoch=8 loss=5.2453 val_auc=0.7369
model=transformerconv top_k=500 fold=0 epoch=9 loss=4.9376 val_auc=0.7471
model=transformerconv top_k=500 fold=0 epoch=10 loss=4.7371 val_auc=0.7545
model=transformerconv top_k=500 fold=0 epoch=11 loss=4.0422 val_auc=0.7574
model=transformerconv top_k=500 fold=0 epoch=12 loss=5.6684 val_auc=0.7607
model=transformerconv top_k=500 fold=0 epoch=13 loss=4.9390 val_auc=0.7638
model=transformerconv top_k=500 fold=0 epoch=14 loss=5.4731 val_auc=0.7664
model=transformerconv top_k=500 fold=0 epoch=15 loss=3.8905 val_auc=0.7693
model=transformerconv top_k=500 fold=0 epoch=16 loss=3.0894 val_auc=0.7729
model=transformerconv top_k=500 fold=0 epoch=17 loss=4.2079 val_auc=0.7763
model=transformerconv top_k=500 fold=0 epoch=18 loss=5.4355 val_auc=0.7790
model=transformerconv top_k=500 fold=0 epoch=19 loss=5.3039 val_auc=0.7808
model=transformerconv top_k=500 fold=0 epoch=20 loss=3.5595 val_auc=0.7817
model=transformerconv top_k=500 fold=0 epoch=21 loss=3.3034 val_auc=0.7814
model=transformerconv top_k=500 fold=0 epoch=22 loss=4.4974 val_auc=0.7814
model=transformerconv top_k=500 fold=0 epoch=23 loss=6.5551 val_auc=0.7819
model=transformerconv top_k=500 fold=0 epoch=24 loss=5.2963 val_auc=0.7827
model=transformerconv top_k=500 fold=0 epoch=25 loss=4.8791 val_auc=0.7837
model=transformerconv top_k=500 fold=0 epoch=26 loss=3.8963 val_auc=0.7851
model=transformerconv top_k=500 fold=0 epoch=27 loss=3.0238 val_auc=0.7861
model=transformerconv top_k=500 fold=0 epoch=28 loss=3.3208 val_auc=0.7865
model=transformerconv top_k=500 fold=0 epoch=29 loss=3.7224 val_auc=0.7868
model=transformerconv top_k=500 fold=0 epoch=30 loss=3.8634 val_auc=0.7868
model=transformerconv top_k=500 fold=0 epoch=31 loss=2.6219 val_auc=0.7872
model=transformerconv top_k=500 fold=0 epoch=32 loss=2.8299 val_auc=0.7880
model=transformerconv top_k=500 fold=0 epoch=33 loss=3.5650 val_auc=0.7885
model=transformerconv top_k=500 fold=0 epoch=34 loss=5.0454 val_auc=0.7889
model=transformerconv top_k=500 fold=0 epoch=35 loss=4.4710 val_auc=0.7894
model=transformerconv top_k=500 fold=0 epoch=36 loss=3.9062 val_auc=0.7898
model=transformerconv top_k=500 fold=0 epoch=37 loss=3.5274 val_auc=0.7899
model=transformerconv top_k=500 fold=0 epoch=38 loss=2.3874 val_auc=0.7898
model=transformerconv top_k=500 fold=0 epoch=39 loss=2.4187 val_auc=0.7906
model=transformerconv top_k=500 fold=0 epoch=40 loss=3.1665 val_auc=0.7916
model=transformerconv top_k=500 fold=0 epoch=41 loss=3.4799 val_auc=0.7930
model=transformerconv top_k=500 fold=0 epoch=42 loss=2.8671 val_auc=0.7943
model=transformerconv top_k=500 fold=0 epoch=43 loss=2.3426 val_auc=0.7956
model=transformerconv top_k=500 fold=0 epoch=44 loss=2.2248 val_auc=0.7964
model=transformerconv top_k=500 fold=0 epoch=45 loss=2.4487 val_auc=0.7967
model=transformerconv top_k=500 fold=0 epoch=46 loss=3.0017 val_auc=0.7969
model=transformerconv top_k=500 fold=0 epoch=47 loss=2.4990 val_auc=0.7973
model=transformerconv top_k=500 fold=0 epoch=48 loss=2.2367 val_auc=0.7980
model=transformerconv top_k=500 fold=0 epoch=49 loss=2.1396 val_auc=0.7988
model=transformerconv top_k=500 fold=0 epoch=50 loss=2.0868 val_auc=0.7995
model=transformerconv top_k=500 fold=0 epoch=51 loss=2.1046 val_auc=0.8002
model=transformerconv top_k=500 fold=0 epoch=52 loss=2.0715 val_auc=0.8007
model=transformerconv top_k=500 fold=0 epoch=53 loss=1.9354 val_auc=0.8013
model=transformerconv top_k=500 fold=0 epoch=54 loss=1.8734 val_auc=0.8019
model=transformerconv top_k=500 fold=0 epoch=55 loss=2.3824 val_auc=0.8023
model=transformerconv top_k=500 fold=0 epoch=56 loss=2.6745 val_auc=0.8025
model=transformerconv top_k=500 fold=0 epoch=57 loss=2.6069 val_auc=0.8027
model=transformerconv top_k=500 fold=0 epoch=58 loss=2.1803 val_auc=0.8025
model=transformerconv top_k=500 fold=0 epoch=59 loss=1.9634 val_auc=0.8021
model=transformerconv top_k=500 fold=0 epoch=60 loss=1.8238 val_auc=0.8020
model=transformerconv top_k=500 fold=0 epoch=61 loss=1.8449 val_auc=0.8022
model=transformerconv top_k=500 fold=0 epoch=62 loss=2.0164 val_auc=0.8028
model=transformerconv top_k=500 fold=0 epoch=63 loss=1.7920 val_auc=0.8033
model=transformerconv top_k=500 fold=0 epoch=64 loss=1.6510 val_auc=0.8040
model=transformerconv top_k=500 fold=0 epoch=65 loss=1.7558 val_auc=0.8044
model=transformerconv top_k=500 fold=0 epoch=66 loss=1.6126 val_auc=0.8048
model=transformerconv top_k=500 fold=0 epoch=67 loss=1.9784 val_auc=0.8052
model=transformerconv top_k=500 fold=0 epoch=68 loss=1.7218 val_auc=0.8055
model=transformerconv top_k=500 fold=0 epoch=69 loss=1.4743 val_auc=0.8060
model=transformerconv top_k=500 fold=0 epoch=70 loss=1.6500 val_auc=0.8065
model=transformerconv top_k=500 fold=0 epoch=71 loss=1.5478 val_auc=0.8071
model=transformerconv top_k=500 fold=0 epoch=72 loss=1.4788 val_auc=0.8079
model=transformerconv top_k=500 fold=0 epoch=73 loss=1.5369 val_auc=0.8087
model=transformerconv top_k=500 fold=0 epoch=74 loss=1.4973 val_auc=0.8095
model=transformerconv top_k=500 fold=0 epoch=75 loss=1.4140 val_auc=0.8101
model=transformerconv top_k=500 fold=0 epoch=76 loss=1.4029 val_auc=0.8102
model=transformerconv top_k=500 fold=0 epoch=77 loss=1.3608 val_auc=0.8107
model=transformerconv top_k=500 fold=0 epoch=78 loss=1.4457 val_auc=0.8113
model=transformerconv top_k=500 fold=0 epoch=79 loss=1.4267 val_auc=0.8120
model=transformerconv top_k=500 fold=0 epoch=80 loss=1.2471 val_auc=0.8125
model=transformerconv top_k=500 fold=0 epoch=81 loss=1.3093 val_auc=0.8129
model=transformerconv top_k=500 fold=0 epoch=82 loss=1.3025 val_auc=0.8130
model=transformerconv top_k=500 fold=0 epoch=83 loss=1.3571 val_auc=0.8128
model=transformerconv top_k=500 fold=0 epoch=84 loss=1.3631 val_auc=0.8129
model=transformerconv top_k=500 fold=0 epoch=85 loss=1.2693 val_auc=0.8130
model=transformerconv top_k=500 fold=0 epoch=86 loss=1.2346 val_auc=0.8138
model=transformerconv top_k=500 fold=0 epoch=87 loss=1.2485 val_auc=0.8139
model=transformerconv top_k=500 fold=0 epoch=88 loss=1.1351 val_auc=0.8145
model=transformerconv top_k=500 fold=0 epoch=89 loss=1.2107 val_auc=0.8151
model=transformerconv top_k=500 fold=0 epoch=90 loss=1.1619 val_auc=0.8156
model=transformerconv top_k=500 fold=0 epoch=91 loss=1.2015 val_auc=0.8161
model=transformerconv top_k=500 fold=0 epoch=92 loss=1.1859 val_auc=0.8166
model=transformerconv top_k=500 fold=0 epoch=93 loss=1.2311 val_auc=0.8172
model=transformerconv top_k=500 fold=0 epoch=94 loss=1.1469 val_auc=0.8177
model=transformerconv top_k=500 fold=0 epoch=95 loss=1.1407 val_auc=0.8182
model=transformerconv top_k=500 fold=0 epoch=96 loss=1.0981 val_auc=0.8186
model=transformerconv top_k=500 fold=0 epoch=97 loss=1.0844 val_auc=0.8189
model=transformerconv top_k=500 fold=0 epoch=98 loss=1.0534 val_auc=0.8194
model=transformerconv top_k=500 fold=0 epoch=99 loss=1.0783 val_auc=0.8203
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718731 edges

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=500 fold=1 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719209 edges
model=transformerconv top_k=500 fold=1 epoch=0 loss=7.4545 val_auc=0.5130
model=transformerconv top_k=500 fold=1 epoch=1 loss=22.1343 val_auc=0.7451
model=transformerconv top_k=500 fold=1 epoch=2 loss=8.1304 val_auc=0.7440
model=transformerconv top_k=500 fold=1 epoch=3 loss=7.3995 val_auc=0.7464
model=transformerconv top_k=500 fold=1 epoch=4 loss=7.0946 val_auc=0.7522
model=transformerconv top_k=500 fold=1 epoch=5 loss=4.5781 val_auc=0.7568
model=transformerconv top_k=500 fold=1 epoch=6 loss=5.7152 val_auc=0.7614
model=transformerconv top_k=500 fold=1 epoch=7 loss=8.7893 val_auc=0.7642
model=transformerconv top_k=500 fold=1 epoch=8 loss=6.8029 val_auc=0.7679
model=transformerconv top_k=500 fold=1 epoch=9 loss=4.1254 val_auc=0.7713
model=transformerconv top_k=500 fold=1 epoch=10 loss=4.7080 val_auc=0.7725
model=transformerconv top_k=500 fold=1 epoch=11 loss=5.0847 val_auc=0.7744
model=transformerconv top_k=500 fold=1 epoch=12 loss=4.9037 val_auc=0.7764
model=transformerconv top_k=500 fold=1 epoch=13 loss=4.1659 val_auc=0.7779
model=transformerconv top_k=500 fold=1 epoch=14 loss=4.3505 val_auc=0.7796
model=transformerconv top_k=500 fold=1 epoch=15 loss=4.6979 val_auc=0.7819
model=transformerconv top_k=500 fold=1 epoch=16 loss=4.1303 val_auc=0.7841
model=transformerconv top_k=500 fold=1 epoch=17 loss=4.7993 val_auc=0.7856
model=transformerconv top_k=500 fold=1 epoch=18 loss=3.8074 val_auc=0.7875
model=transformerconv top_k=500 fold=1 epoch=19 loss=3.3562 val_auc=0.7894
model=transformerconv top_k=500 fold=1 epoch=20 loss=3.4231 val_auc=0.7906
model=transformerconv top_k=500 fold=1 epoch=21 loss=3.1756 val_auc=0.7916
model=transformerconv top_k=500 fold=1 epoch=22 loss=3.8845 val_auc=0.7932
model=transformerconv top_k=500 fold=1 epoch=23 loss=4.4103 val_auc=0.7945
model=transformerconv top_k=500 fold=1 epoch=24 loss=5.3977 val_auc=0.7960
model=transformerconv top_k=500 fold=1 epoch=25 loss=3.5622 val_auc=0.7973
model=transformerconv top_k=500 fold=1 epoch=26 loss=3.1617 val_auc=0.7990
model=transformerconv top_k=500 fold=1 epoch=27 loss=3.5051 val_auc=0.8006
model=transformerconv top_k=500 fold=1 epoch=28 loss=3.5673 val_auc=0.8018
model=transformerconv top_k=500 fold=1 epoch=29 loss=4.2252 val_auc=0.8024
model=transformerconv top_k=500 fold=1 epoch=30 loss=3.3631 val_auc=0.8026
model=transformerconv top_k=500 fold=1 epoch=31 loss=2.9118 val_auc=0.8040
model=transformerconv top_k=500 fold=1 epoch=32 loss=2.8355 val_auc=0.8063
model=transformerconv top_k=500 fold=1 epoch=33 loss=2.8710 val_auc=0.8085
model=transformerconv top_k=500 fold=1 epoch=34 loss=2.6957 val_auc=0.8107
model=transformerconv top_k=500 fold=1 epoch=35 loss=2.6381 val_auc=0.8113
model=transformerconv top_k=500 fold=1 epoch=36 loss=2.5350 val_auc=0.8107
model=transformerconv top_k=500 fold=1 epoch=37 loss=2.7408 val_auc=0.8127
model=transformerconv top_k=500 fold=1 epoch=38 loss=2.7140 val_auc=0.8148
model=transformerconv top_k=500 fold=1 epoch=39 loss=2.4036 val_auc=0.8149
model=transformerconv top_k=500 fold=1 epoch=40 loss=2.8269 val_auc=0.8150
model=transformerconv top_k=500 fold=1 epoch=41 loss=2.3106 val_auc=0.8151
model=transformerconv top_k=500 fold=1 epoch=42 loss=2.9619 val_auc=0.8152
model=transformerconv top_k=500 fold=1 epoch=43 loss=2.4014 val_auc=0.8153
model=transformerconv top_k=500 fold=1 epoch=44 loss=2.0435 val_auc=0.8163
model=transformerconv top_k=500 fold=1 epoch=45 loss=2.1173 val_auc=0.8174
model=transformerconv top_k=500 fold=1 epoch=46 loss=2.7493 val_auc=0.8178
model=transformerconv top_k=500 fold=1 epoch=47 loss=2.6806 val_auc=0.8187
model=transformerconv top_k=500 fold=1 epoch=48 loss=2.2894 val_auc=0.8195
model=transformerconv top_k=500 fold=1 epoch=49 loss=2.0513 val_auc=0.8202
model=transformerconv top_k=500 fold=1 epoch=50 loss=2.5371 val_auc=0.8204
model=transformerconv top_k=500 fold=1 epoch=51 loss=2.1968 val_auc=0.8206
model=transformerconv top_k=500 fold=1 epoch=52 loss=2.6201 val_auc=0.8183
model=transformerconv top_k=500 fold=1 epoch=53 loss=1.9793 val_auc=0.8153
model=transformerconv top_k=500 fold=1 epoch=54 loss=2.2217 val_auc=0.8169
model=transformerconv top_k=500 fold=1 epoch=55 loss=2.0618 val_auc=0.8217
model=transformerconv top_k=500 fold=1 epoch=56 loss=1.9648 val_auc=0.8237
model=transformerconv top_k=500 fold=1 epoch=57 loss=2.0775 val_auc=0.8243
model=transformerconv top_k=500 fold=1 epoch=58 loss=1.9407 val_auc=0.8247
model=transformerconv top_k=500 fold=1 epoch=59 loss=2.1321 val_auc=0.8247
model=transformerconv top_k=500 fold=1 epoch=60 loss=1.6569 val_auc=0.8250
model=transformerconv top_k=500 fold=1 epoch=61 loss=1.7200 val_auc=0.8253
model=transformerconv top_k=500 fold=1 epoch=62 loss=1.6402 val_auc=0.8258
model=transformerconv top_k=500 fold=1 epoch=63 loss=1.5726 val_auc=0.8263
model=transformerconv top_k=500 fold=1 epoch=64 loss=1.5274 val_auc=0.8270
model=transformerconv top_k=500 fold=1 epoch=65 loss=1.6181 val_auc=0.8277
model=transformerconv top_k=500 fold=1 epoch=66 loss=1.7284 val_auc=0.8284
model=transformerconv top_k=500 fold=1 epoch=67 loss=1.5304 val_auc=0.8243
model=transformerconv top_k=500 fold=1 epoch=68 loss=1.6014 val_auc=0.8158
model=transformerconv top_k=500 fold=1 epoch=69 loss=1.8326 val_auc=0.8133
model=transformerconv top_k=500 fold=1 epoch=70 loss=1.7187 val_auc=0.8172
model=transformerconv top_k=500 fold=1 epoch=71 loss=1.5274 val_auc=0.8244
model=transformerconv top_k=500 fold=1 epoch=72 loss=1.4194 val_auc=0.8276
model=transformerconv top_k=500 fold=1 epoch=73 loss=1.3767 val_auc=0.8290
model=transformerconv top_k=500 fold=1 epoch=74 loss=1.5035 val_auc=0.8303
model=transformerconv top_k=500 fold=1 epoch=75 loss=1.6176 val_auc=0.8313
model=transformerconv top_k=500 fold=1 epoch=76 loss=1.3115 val_auc=0.8323
model=transformerconv top_k=500 fold=1 epoch=77 loss=1.2552 val_auc=0.8337
model=transformerconv top_k=500 fold=1 epoch=78 loss=1.2779 val_auc=0.8350
model=transformerconv top_k=500 fold=1 epoch=79 loss=1.2540 val_auc=0.8361
model=transformerconv top_k=500 fold=1 epoch=80 loss=1.2291 val_auc=0.8375
model=transformerconv top_k=500 fold=1 epoch=81 loss=1.1439 val_auc=0.8381
model=transformerconv top_k=500 fold=1 epoch=82 loss=1.2943 val_auc=0.8379
model=transformerconv top_k=500 fold=1 epoch=83 loss=1.2233 val_auc=0.8378
model=transformerconv top_k=500 fold=1 epoch=84 loss=1.2783 val_auc=0.8366
model=transformerconv top_k=500 fold=1 epoch=85 loss=1.0743 val_auc=0.8358
model=transformerconv top_k=500 fold=1 epoch=86 loss=1.4180 val_auc=0.8338
model=transformerconv top_k=500 fold=1 epoch=87 loss=1.2390 val_auc=0.8337
model=transformerconv top_k=500 fold=1 epoch=88 loss=1.1631 val_auc=0.8349
model=transformerconv top_k=500 fold=1 epoch=89 loss=1.1396 val_auc=0.8358
model=transformerconv top_k=500 fold=1 epoch=90 loss=1.1882 val_auc=0.8361
model=transformerconv top_k=500 fold=1 epoch=91 loss=1.0596 val_auc=0.8380
model=transformerconv top_k=500 fold=1 epoch=92 loss=1.0672 val_auc=0.8409
model=transformerconv top_k=500 fold=1 epoch=93 loss=1.1640 val_auc=0.8435
model=transformerconv top_k=500 fold=1 epoch=94 loss=1.0216 val_auc=0.8455
model=transformerconv top_k=500 fold=1 epoch=95 loss=1.0208 val_auc=0.8457
model=transformerconv top_k=500 fold=1 epoch=96 loss=1.0111 val_auc=0.8449
model=transformerconv top_k=500 fold=1 epoch=97 loss=1.0106 val_auc=0.8444
model=transformerconv top_k=500 fold=1 epoch=98 loss=0.9865 val_auc=0.8448
model=transformerconv top_k=500 fold=1 epoch=99 loss=0.9856 val_auc=0.8457
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719209 edges

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=500 fold=2 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718855 edges
model=transformerconv top_k=500 fold=2 epoch=0 loss=6.0870 val_auc=0.5000
model=transformerconv top_k=500 fold=2 epoch=1 loss=36.5134 val_auc=0.5165
model=transformerconv top_k=500 fold=2 epoch=2 loss=30.0004 val_auc=0.7410
model=transformerconv top_k=500 fold=2 epoch=3 loss=13.6606 val_auc=0.7457
model=transformerconv top_k=500 fold=2 epoch=4 loss=6.7346 val_auc=0.7528
model=transformerconv top_k=500 fold=2 epoch=5 loss=6.9667 val_auc=0.7557
model=transformerconv top_k=500 fold=2 epoch=6 loss=6.3766 val_auc=0.7590
model=transformerconv top_k=500 fold=2 epoch=7 loss=4.3257 val_auc=0.7621
model=transformerconv top_k=500 fold=2 epoch=8 loss=4.6862 val_auc=0.7637
model=transformerconv top_k=500 fold=2 epoch=9 loss=4.1441 val_auc=0.7679
model=transformerconv top_k=500 fold=2 epoch=10 loss=3.9509 val_auc=0.7721
model=transformerconv top_k=500 fold=2 epoch=11 loss=3.8442 val_auc=0.7793
model=transformerconv top_k=500 fold=2 epoch=12 loss=3.9207 val_auc=0.7849
model=transformerconv top_k=500 fold=2 epoch=13 loss=3.6955 val_auc=0.7890
model=transformerconv top_k=500 fold=2 epoch=14 loss=3.7663 val_auc=0.7929
model=transformerconv top_k=500 fold=2 epoch=15 loss=3.3997 val_auc=0.7949
model=transformerconv top_k=500 fold=2 epoch=16 loss=4.0554 val_auc=0.7966
model=transformerconv top_k=500 fold=2 epoch=17 loss=3.0828 val_auc=0.7984
model=transformerconv top_k=500 fold=2 epoch=18 loss=4.3879 val_auc=0.7995
model=transformerconv top_k=500 fold=2 epoch=19 loss=3.2094 val_auc=0.7999
model=transformerconv top_k=500 fold=2 epoch=20 loss=3.2073 val_auc=0.8007
model=transformerconv top_k=500 fold=2 epoch=21 loss=3.5313 val_auc=0.8014
model=transformerconv top_k=500 fold=2 epoch=22 loss=2.9245 val_auc=0.8024
model=transformerconv top_k=500 fold=2 epoch=23 loss=2.9325 val_auc=0.8032
model=transformerconv top_k=500 fold=2 epoch=24 loss=2.9440 val_auc=0.8044
model=transformerconv top_k=500 fold=2 epoch=25 loss=2.8245 val_auc=0.8055
model=transformerconv top_k=500 fold=2 epoch=26 loss=2.8199 val_auc=0.8067
model=transformerconv top_k=500 fold=2 epoch=27 loss=2.3839 val_auc=0.8078
model=transformerconv top_k=500 fold=2 epoch=28 loss=2.4908 val_auc=0.8090
model=transformerconv top_k=500 fold=2 epoch=29 loss=2.8426 val_auc=0.8103
model=transformerconv top_k=500 fold=2 epoch=30 loss=2.0424 val_auc=0.8119
model=transformerconv top_k=500 fold=2 epoch=31 loss=1.9119 val_auc=0.8140
model=transformerconv top_k=500 fold=2 epoch=32 loss=2.0121 val_auc=0.8159
model=transformerconv top_k=500 fold=2 epoch=33 loss=2.0513 val_auc=0.8174
model=transformerconv top_k=500 fold=2 epoch=34 loss=2.0524 val_auc=0.8186
model=transformerconv top_k=500 fold=2 epoch=35 loss=2.0993 val_auc=0.8191
model=transformerconv top_k=500 fold=2 epoch=36 loss=1.9348 val_auc=0.8191
model=transformerconv top_k=500 fold=2 epoch=37 loss=2.2228 val_auc=0.8187
model=transformerconv top_k=500 fold=2 epoch=38 loss=1.7852 val_auc=0.8182
model=transformerconv top_k=500 fold=2 epoch=39 loss=2.2155 val_auc=0.8180
model=transformerconv top_k=500 fold=2 epoch=40 loss=3.0525 val_auc=0.8177
model=transformerconv top_k=500 fold=2 epoch=41 loss=1.9995 val_auc=0.8174
model=transformerconv top_k=500 fold=2 epoch=42 loss=1.9453 val_auc=0.8171
model=transformerconv top_k=500 fold=2 epoch=43 loss=2.0016 val_auc=0.8171
model=transformerconv top_k=500 fold=2 epoch=44 loss=1.9980 val_auc=0.8173
model=transformerconv top_k=500 fold=2 epoch=45 loss=2.1992 val_auc=0.8179
model=transformerconv top_k=500 fold=2 epoch=46 loss=1.9617 val_auc=0.8184
model=transformerconv top_k=500 fold=2 epoch=47 loss=1.8604 val_auc=0.8186
transformerconv top_k=500 fold=2: early stopping at epoch 47
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718855 edges

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=500 fold=3 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719213 edges
model=transformerconv top_k=500 fold=3 epoch=0 loss=12.3602 val_auc=0.5000
model=transformerconv top_k=500 fold=3 epoch=1 loss=33.4165 val_auc=0.5000
model=transformerconv top_k=500 fold=3 epoch=2 loss=26.3915 val_auc=0.7370
model=transformerconv top_k=500 fold=3 epoch=3 loss=12.2060 val_auc=0.7509
model=transformerconv top_k=500 fold=3 epoch=4 loss=4.6921 val_auc=0.7601
model=transformerconv top_k=500 fold=3 epoch=5 loss=8.4782 val_auc=0.7670
model=transformerconv top_k=500 fold=3 epoch=6 loss=7.2616 val_auc=0.7714
model=transformerconv top_k=500 fold=3 epoch=7 loss=4.9251 val_auc=0.7767
model=transformerconv top_k=500 fold=3 epoch=8 loss=5.8127 val_auc=0.7804
model=transformerconv top_k=500 fold=3 epoch=9 loss=6.1272 val_auc=0.7833
model=transformerconv top_k=500 fold=3 epoch=10 loss=4.7539 val_auc=0.7856
model=transformerconv top_k=500 fold=3 epoch=11 loss=4.0423 val_auc=0.7877
model=transformerconv top_k=500 fold=3 epoch=12 loss=4.6928 val_auc=0.7896
model=transformerconv top_k=500 fold=3 epoch=13 loss=4.4738 val_auc=0.7908
model=transformerconv top_k=500 fold=3 epoch=14 loss=3.8872 val_auc=0.7924
model=transformerconv top_k=500 fold=3 epoch=15 loss=3.9632 val_auc=0.7939
model=transformerconv top_k=500 fold=3 epoch=16 loss=3.8479 val_auc=0.7955
model=transformerconv top_k=500 fold=3 epoch=17 loss=3.1699 val_auc=0.7972
model=transformerconv top_k=500 fold=3 epoch=18 loss=3.9407 val_auc=0.7985
model=transformerconv top_k=500 fold=3 epoch=19 loss=3.6732 val_auc=0.7991
model=transformerconv top_k=500 fold=3 epoch=20 loss=3.5943 val_auc=0.8000
model=transformerconv top_k=500 fold=3 epoch=21 loss=3.1508 val_auc=0.8011
model=transformerconv top_k=500 fold=3 epoch=22 loss=2.9248 val_auc=0.8022
model=transformerconv top_k=500 fold=3 epoch=23 loss=2.9237 val_auc=0.8033
model=transformerconv top_k=500 fold=3 epoch=24 loss=3.0006 val_auc=0.8042
model=transformerconv top_k=500 fold=3 epoch=25 loss=2.9595 val_auc=0.8049
model=transformerconv top_k=500 fold=3 epoch=26 loss=3.2309 val_auc=0.8053
model=transformerconv top_k=500 fold=3 epoch=27 loss=2.8709 val_auc=0.8058
model=transformerconv top_k=500 fold=3 epoch=28 loss=2.7225 val_auc=0.8064
model=transformerconv top_k=500 fold=3 epoch=29 loss=2.6430 val_auc=0.8069
model=transformerconv top_k=500 fold=3 epoch=30 loss=3.2009 val_auc=0.8077
model=transformerconv top_k=500 fold=3 epoch=31 loss=2.6507 val_auc=0.8082
model=transformerconv top_k=500 fold=3 epoch=32 loss=3.1226 val_auc=0.8090
model=transformerconv top_k=500 fold=3 epoch=33 loss=2.5293 val_auc=0.8098
model=transformerconv top_k=500 fold=3 epoch=34 loss=2.3151 val_auc=0.8105
model=transformerconv top_k=500 fold=3 epoch=35 loss=2.6037 val_auc=0.8110
model=transformerconv top_k=500 fold=3 epoch=36 loss=2.3459 val_auc=0.8115
model=transformerconv top_k=500 fold=3 epoch=37 loss=2.2555 val_auc=0.8121
model=transformerconv top_k=500 fold=3 epoch=38 loss=1.8970 val_auc=0.8125
model=transformerconv top_k=500 fold=3 epoch=39 loss=2.3277 val_auc=0.8130
model=transformerconv top_k=500 fold=3 epoch=40 loss=2.2996 val_auc=0.8136
model=transformerconv top_k=500 fold=3 epoch=41 loss=1.9046 val_auc=0.8139
model=transformerconv top_k=500 fold=3 epoch=42 loss=2.6229 val_auc=0.8139
model=transformerconv top_k=500 fold=3 epoch=43 loss=2.5168 val_auc=0.8144
model=transformerconv top_k=500 fold=3 epoch=44 loss=2.5498 val_auc=0.8147
model=transformerconv top_k=500 fold=3 epoch=45 loss=2.0639 val_auc=0.8150
model=transformerconv top_k=500 fold=3 epoch=46 loss=1.8198 val_auc=0.8153
model=transformerconv top_k=500 fold=3 epoch=47 loss=2.2654 val_auc=0.8156
model=transformerconv top_k=500 fold=3 epoch=48 loss=1.7526 val_auc=0.8159
model=transformerconv top_k=500 fold=3 epoch=49 loss=1.8438 val_auc=0.8163
model=transformerconv top_k=500 fold=3 epoch=50 loss=2.0164 val_auc=0.8165
model=transformerconv top_k=500 fold=3 epoch=51 loss=2.1976 val_auc=0.8167
model=transformerconv top_k=500 fold=3 epoch=52 loss=1.8926 val_auc=0.8168
model=transformerconv top_k=500 fold=3 epoch=53 loss=1.5169 val_auc=0.8171
model=transformerconv top_k=500 fold=3 epoch=54 loss=1.5091 val_auc=0.8176
model=transformerconv top_k=500 fold=3 epoch=55 loss=1.5212 val_auc=0.8182
model=transformerconv top_k=500 fold=3 epoch=56 loss=1.7305 val_auc=0.8185
model=transformerconv top_k=500 fold=3 epoch=57 loss=1.7108 val_auc=0.8184
model=transformerconv top_k=500 fold=3 epoch=58 loss=1.3242 val_auc=0.8179
model=transformerconv top_k=500 fold=3 epoch=59 loss=1.5953 val_auc=0.8176
model=transformerconv top_k=500 fold=3 epoch=60 loss=1.5599 val_auc=0.8177
model=transformerconv top_k=500 fold=3 epoch=61 loss=1.5732 val_auc=0.8185
model=transformerconv top_k=500 fold=3 epoch=62 loss=1.4524 val_auc=0.8190
model=transformerconv top_k=500 fold=3 epoch=63 loss=1.4492 val_auc=0.8191
model=transformerconv top_k=500 fold=3 epoch=64 loss=1.5240 val_auc=0.8189
model=transformerconv top_k=500 fold=3 epoch=65 loss=1.3620 val_auc=0.8194
model=transformerconv top_k=500 fold=3 epoch=66 loss=1.5359 val_auc=0.8202
model=transformerconv top_k=500 fold=3 epoch=67 loss=1.3516 val_auc=0.8212
model=transformerconv top_k=500 fold=3 epoch=68 loss=1.3663 val_auc=0.8216
model=transformerconv top_k=500 fold=3 epoch=69 loss=1.4883 val_auc=0.8218
model=transformerconv top_k=500 fold=3 epoch=70 loss=1.2907 val_auc=0.8219
model=transformerconv top_k=500 fold=3 epoch=71 loss=1.3664 val_auc=0.8223
model=transformerconv top_k=500 fold=3 epoch=72 loss=1.3157 val_auc=0.8227
model=transformerconv top_k=500 fold=3 epoch=73 loss=1.4515 val_auc=0.8231
model=transformerconv top_k=500 fold=3 epoch=74 loss=1.2939 val_auc=0.8233
model=transformerconv top_k=500 fold=3 epoch=75 loss=1.3203 val_auc=0.8236
model=transformerconv top_k=500 fold=3 epoch=76 loss=1.2668 val_auc=0.8237
model=transformerconv top_k=500 fold=3 epoch=77 loss=1.3958 val_auc=0.8237
model=transformerconv top_k=500 fold=3 epoch=78 loss=1.3469 val_auc=0.8240
model=transformerconv top_k=500 fold=3 epoch=79 loss=1.2395 val_auc=0.8244
model=transformerconv top_k=500 fold=3 epoch=80 loss=1.3218 val_auc=0.8244
model=transformerconv top_k=500 fold=3 epoch=81 loss=1.4259 val_auc=0.8243
model=transformerconv top_k=500 fold=3 epoch=82 loss=1.3896 val_auc=0.8243
model=transformerconv top_k=500 fold=3 epoch=83 loss=1.2371 val_auc=0.8244
model=transformerconv top_k=500 fold=3 epoch=84 loss=1.1980 val_auc=0.8245
model=transformerconv top_k=500 fold=3 epoch=85 loss=1.4755 val_auc=0.8247
model=transformerconv top_k=500 fold=3 epoch=86 loss=1.4184 val_auc=0.8251
model=transformerconv top_k=500 fold=3 epoch=87 loss=1.1537 val_auc=0.8256
model=transformerconv top_k=500 fold=3 epoch=88 loss=1.2562 val_auc=0.8256
model=transformerconv top_k=500 fold=3 epoch=89 loss=1.2332 val_auc=0.8256
model=transformerconv top_k=500 fold=3 epoch=90 loss=1.2034 val_auc=0.8257
model=transformerconv top_k=500 fold=3 epoch=91 loss=1.2156 val_auc=0.8257
model=transformerconv top_k=500 fold=3 epoch=92 loss=1.2965 val_auc=0.8258
model=transformerconv top_k=500 fold=3 epoch=93 loss=1.1882 val_auc=0.8257
model=transformerconv top_k=500 fold=3 epoch=94 loss=1.2232 val_auc=0.8256
model=transformerconv top_k=500 fold=3 epoch=95 loss=1.2106 val_auc=0.8255
model=transformerconv top_k=500 fold=3 epoch=96 loss=1.1700 val_auc=0.8255
model=transformerconv top_k=500 fold=3 epoch=97 loss=1.1713 val_auc=0.8256
model=transformerconv top_k=500 fold=3 epoch=98 loss=1.2279 val_auc=0.8258
model=transformerconv top_k=500 fold=3 epoch=99 loss=1.2587 val_auc=0.8263
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719213 edges

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=500 fold=4 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719233 edges
model=transformerconv top_k=500 fold=4 epoch=0 loss=7.0840 val_auc=0.5035
model=transformerconv top_k=500 fold=4 epoch=1 loss=27.9495 val_auc=0.5160
model=transformerconv top_k=500 fold=4 epoch=2 loss=20.8824 val_auc=0.7051
model=transformerconv top_k=500 fold=4 epoch=3 loss=9.3687 val_auc=0.7395
model=transformerconv top_k=500 fold=4 epoch=4 loss=7.3086 val_auc=0.7448
model=transformerconv top_k=500 fold=4 epoch=5 loss=8.0809 val_auc=0.7496
model=transformerconv top_k=500 fold=4 epoch=6 loss=7.7366 val_auc=0.7527
model=transformerconv top_k=500 fold=4 epoch=7 loss=5.8936 val_auc=0.7565
model=transformerconv top_k=500 fold=4 epoch=8 loss=5.4886 val_auc=0.7602
model=transformerconv top_k=500 fold=4 epoch=9 loss=6.2550 val_auc=0.7644
model=transformerconv top_k=500 fold=4 epoch=10 loss=7.1289 val_auc=0.7679
model=transformerconv top_k=500 fold=4 epoch=11 loss=5.2827 val_auc=0.7710
model=transformerconv top_k=500 fold=4 epoch=12 loss=4.5025 val_auc=0.7743
model=transformerconv top_k=500 fold=4 epoch=13 loss=4.8210 val_auc=0.7775
model=transformerconv top_k=500 fold=4 epoch=14 loss=4.4765 val_auc=0.7805
model=transformerconv top_k=500 fold=4 epoch=15 loss=4.2101 val_auc=0.7851
model=transformerconv top_k=500 fold=4 epoch=16 loss=4.9859 val_auc=0.7877
model=transformerconv top_k=500 fold=4 epoch=17 loss=4.5516 val_auc=0.7895
model=transformerconv top_k=500 fold=4 epoch=18 loss=4.1480 val_auc=0.7913
model=transformerconv top_k=500 fold=4 epoch=19 loss=3.5320 val_auc=0.7922
model=transformerconv top_k=500 fold=4 epoch=20 loss=4.0550 val_auc=0.7927
model=transformerconv top_k=500 fold=4 epoch=21 loss=3.6986 val_auc=0.7931
model=transformerconv top_k=500 fold=4 epoch=22 loss=3.9833 val_auc=0.7942
model=transformerconv top_k=500 fold=4 epoch=23 loss=3.6498 val_auc=0.7955
model=transformerconv top_k=500 fold=4 epoch=24 loss=3.6737 val_auc=0.7970
model=transformerconv top_k=500 fold=4 epoch=25 loss=3.3122 val_auc=0.7986
model=transformerconv top_k=500 fold=4 epoch=26 loss=3.3125 val_auc=0.7997
model=transformerconv top_k=500 fold=4 epoch=27 loss=4.3686 val_auc=0.8005
model=transformerconv top_k=500 fold=4 epoch=28 loss=3.8120 val_auc=0.8013
model=transformerconv top_k=500 fold=4 epoch=29 loss=3.3309 val_auc=0.8015
model=transformerconv top_k=500 fold=4 epoch=30 loss=3.4567 val_auc=0.8019
model=transformerconv top_k=500 fold=4 epoch=31 loss=2.9283 val_auc=0.8028
model=transformerconv top_k=500 fold=4 epoch=32 loss=3.2239 val_auc=0.8039
model=transformerconv top_k=500 fold=4 epoch=33 loss=2.7934 val_auc=0.8051
model=transformerconv top_k=500 fold=4 epoch=34 loss=2.7802 val_auc=0.8061
model=transformerconv top_k=500 fold=4 epoch=35 loss=2.6475 val_auc=0.8069
model=transformerconv top_k=500 fold=4 epoch=36 loss=2.6735 val_auc=0.8076
model=transformerconv top_k=500 fold=4 epoch=37 loss=2.7046 val_auc=0.8085
model=transformerconv top_k=500 fold=4 epoch=38 loss=2.9585 val_auc=0.8094
model=transformerconv top_k=500 fold=4 epoch=39 loss=2.0915 val_auc=0.8104
model=transformerconv top_k=500 fold=4 epoch=40 loss=2.3137 val_auc=0.8115
model=transformerconv top_k=500 fold=4 epoch=41 loss=2.8456 val_auc=0.8123
model=transformerconv top_k=500 fold=4 epoch=42 loss=2.6359 val_auc=0.8129
model=transformerconv top_k=500 fold=4 epoch=43 loss=1.9782 val_auc=0.8136
model=transformerconv top_k=500 fold=4 epoch=44 loss=2.6666 val_auc=0.8144
model=transformerconv top_k=500 fold=4 epoch=45 loss=2.6573 val_auc=0.8153
model=transformerconv top_k=500 fold=4 epoch=46 loss=2.1259 val_auc=0.8159
model=transformerconv top_k=500 fold=4 epoch=47 loss=2.5812 val_auc=0.8163
model=transformerconv top_k=500 fold=4 epoch=48 loss=1.8178 val_auc=0.8164
model=transformerconv top_k=500 fold=4 epoch=49 loss=2.2223 val_auc=0.8162
model=transformerconv top_k=500 fold=4 epoch=50 loss=1.9760 val_auc=0.8161
model=transformerconv top_k=500 fold=4 epoch=51 loss=2.1044 val_auc=0.8162
model=transformerconv top_k=500 fold=4 epoch=52 loss=1.7975 val_auc=0.8161
model=transformerconv top_k=500 fold=4 epoch=53 loss=1.9494 val_auc=0.8158
model=transformerconv top_k=500 fold=4 epoch=54 loss=1.7050 val_auc=0.8160
model=transformerconv top_k=500 fold=4 epoch=55 loss=1.7518 val_auc=0.8166
model=transformerconv top_k=500 fold=4 epoch=56 loss=1.6145 val_auc=0.8171
model=transformerconv top_k=500 fold=4 epoch=57 loss=1.7029 val_auc=0.8178
model=transformerconv top_k=500 fold=4 epoch=58 loss=1.4878 val_auc=0.8181
model=transformerconv top_k=500 fold=4 epoch=59 loss=1.7558 val_auc=0.8181
model=transformerconv top_k=500 fold=4 epoch=60 loss=1.5755 val_auc=0.8182
model=transformerconv top_k=500 fold=4 epoch=61 loss=1.6345 val_auc=0.8182
model=transformerconv top_k=500 fold=4 epoch=62 loss=1.5102 val_auc=0.8182
model=transformerconv top_k=500 fold=4 epoch=63 loss=1.5928 val_auc=0.8186
model=transformerconv top_k=500 fold=4 epoch=64 loss=1.4578 val_auc=0.8188
model=transformerconv top_k=500 fold=4 epoch=65 loss=1.5962 val_auc=0.8191
model=transformerconv top_k=500 fold=4 epoch=66 loss=1.5383 val_auc=0.8199
model=transformerconv top_k=500 fold=4 epoch=67 loss=1.4650 val_auc=0.8207
model=transformerconv top_k=500 fold=4 epoch=68 loss=1.5083 val_auc=0.8212
model=transformerconv top_k=500 fold=4 epoch=69 loss=1.4872 val_auc=0.8214
model=transformerconv top_k=500 fold=4 epoch=70 loss=1.2866 val_auc=0.8220
model=transformerconv top_k=500 fold=4 epoch=71 loss=1.3890 val_auc=0.8226
model=transformerconv top_k=500 fold=4 epoch=72 loss=1.4558 val_auc=0.8234
model=transformerconv top_k=500 fold=4 epoch=73 loss=1.2753 val_auc=0.8240
model=transformerconv top_k=500 fold=4 epoch=74 loss=1.2920 val_auc=0.8246
model=transformerconv top_k=500 fold=4 epoch=75 loss=1.3977 val_auc=0.8251
model=transformerconv top_k=500 fold=4 epoch=76 loss=1.3181 val_auc=0.8255
model=transformerconv top_k=500 fold=4 epoch=77 loss=1.3058 val_auc=0.8261
model=transformerconv top_k=500 fold=4 epoch=78 loss=1.2363 val_auc=0.8266
model=transformerconv top_k=500 fold=4 epoch=79 loss=1.3386 val_auc=0.8268
model=transformerconv top_k=500 fold=4 epoch=80 loss=1.3726 val_auc=0.8268
model=transformerconv top_k=500 fold=4 epoch=81 loss=1.2225 val_auc=0.8269
model=transformerconv top_k=500 fold=4 epoch=82 loss=1.2629 val_auc=0.8269
model=transformerconv top_k=500 fold=4 epoch=83 loss=1.3489 val_auc=0.8269
model=transformerconv top_k=500 fold=4 epoch=84 loss=1.2965 val_auc=0.8268
model=transformerconv top_k=500 fold=4 epoch=85 loss=1.1417 val_auc=0.8268
model=transformerconv top_k=500 fold=4 epoch=86 loss=1.1049 val_auc=0.8270
model=transformerconv top_k=500 fold=4 epoch=87 loss=1.1072 val_auc=0.8270
model=transformerconv top_k=500 fold=4 epoch=88 loss=1.1608 val_auc=0.8270
model=transformerconv top_k=500 fold=4 epoch=89 loss=1.0837 val_auc=0.8266
model=transformerconv top_k=500 fold=4 epoch=90 loss=1.1531 val_auc=0.8263
model=transformerconv top_k=500 fold=4 epoch=91 loss=1.1225 val_auc=0.8263
model=transformerconv top_k=500 fold=4 epoch=92 loss=1.1072 val_auc=0.8264
model=transformerconv top_k=500 fold=4 epoch=93 loss=1.1097 val_auc=0.8269
model=transformerconv top_k=500 fold=4 epoch=94 loss=1.2541 val_auc=0.8275
model=transformerconv top_k=500 fold=4 epoch=95 loss=1.0411 val_auc=0.8286
model=transformerconv top_k=500 fold=4 epoch=96 loss=0.9996 val_auc=0.8287
model=transformerconv top_k=500 fold=4 epoch=97 loss=1.1754 val_auc=0.8286
model=transformerconv top_k=500 fold=4 epoch=98 loss=1.0411 val_auc=0.8285
model=transformerconv top_k=500 fold=4 epoch=99 loss=1.1214 val_auc=0.8282
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719233 edges

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=500 fold=5 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718759 edges
model=transformerconv top_k=500 fold=5 epoch=0 loss=10.3319 val_auc=0.4993
model=transformerconv top_k=500 fold=5 epoch=1 loss=23.9542 val_auc=0.4982
model=transformerconv top_k=500 fold=5 epoch=2 loss=18.1301 val_auc=0.5898
model=transformerconv top_k=500 fold=5 epoch=3 loss=5.9503 val_auc=0.6776
model=transformerconv top_k=500 fold=5 epoch=4 loss=9.7370 val_auc=0.7147
model=transformerconv top_k=500 fold=5 epoch=5 loss=11.7009 val_auc=0.7324
model=transformerconv top_k=500 fold=5 epoch=6 loss=10.1341 val_auc=0.7447
model=transformerconv top_k=500 fold=5 epoch=7 loss=4.9653 val_auc=0.7548
model=transformerconv top_k=500 fold=5 epoch=8 loss=4.4371 val_auc=0.7662
model=transformerconv top_k=500 fold=5 epoch=9 loss=5.4937 val_auc=0.7748
model=transformerconv top_k=500 fold=5 epoch=10 loss=5.4170 val_auc=0.7808
model=transformerconv top_k=500 fold=5 epoch=11 loss=4.1419 val_auc=0.7841
model=transformerconv top_k=500 fold=5 epoch=12 loss=3.6883 val_auc=0.7872
model=transformerconv top_k=500 fold=5 epoch=13 loss=4.4439 val_auc=0.7920
model=transformerconv top_k=500 fold=5 epoch=14 loss=4.2346 val_auc=0.7955
model=transformerconv top_k=500 fold=5 epoch=15 loss=3.5720 val_auc=0.7969
model=transformerconv top_k=500 fold=5 epoch=16 loss=3.9189 val_auc=0.7975
model=transformerconv top_k=500 fold=5 epoch=17 loss=4.1669 val_auc=0.7978
model=transformerconv top_k=500 fold=5 epoch=18 loss=3.3564 val_auc=0.7985
model=transformerconv top_k=500 fold=5 epoch=19 loss=3.2070 val_auc=0.7993
model=transformerconv top_k=500 fold=5 epoch=20 loss=4.0335 val_auc=0.8000
model=transformerconv top_k=500 fold=5 epoch=21 loss=5.2506 val_auc=0.8005
model=transformerconv top_k=500 fold=5 epoch=22 loss=4.9779 val_auc=0.8010
model=transformerconv top_k=500 fold=5 epoch=23 loss=4.1097 val_auc=0.8016
model=transformerconv top_k=500 fold=5 epoch=24 loss=2.9280 val_auc=0.8037
model=transformerconv top_k=500 fold=5 epoch=25 loss=4.5295 val_auc=0.8057
model=transformerconv top_k=500 fold=5 epoch=26 loss=4.2545 val_auc=0.8072
model=transformerconv top_k=500 fold=5 epoch=27 loss=4.4380 val_auc=0.8082
model=transformerconv top_k=500 fold=5 epoch=28 loss=3.2584 val_auc=0.8085
model=transformerconv top_k=500 fold=5 epoch=29 loss=2.5495 val_auc=0.8089
model=transformerconv top_k=500 fold=5 epoch=30 loss=2.9883 val_auc=0.8097
model=transformerconv top_k=500 fold=5 epoch=31 loss=2.8970 val_auc=0.8107
model=transformerconv top_k=500 fold=5 epoch=32 loss=2.7173 val_auc=0.8123
model=transformerconv top_k=500 fold=5 epoch=33 loss=2.7205 val_auc=0.8136
model=transformerconv top_k=500 fold=5 epoch=34 loss=2.5294 val_auc=0.8144
model=transformerconv top_k=500 fold=5 epoch=35 loss=2.6587 val_auc=0.8148
model=transformerconv top_k=500 fold=5 epoch=36 loss=2.7298 val_auc=0.8153
model=transformerconv top_k=500 fold=5 epoch=37 loss=2.8249 val_auc=0.8154
model=transformerconv top_k=500 fold=5 epoch=38 loss=2.3014 val_auc=0.8159
model=transformerconv top_k=500 fold=5 epoch=39 loss=2.6061 val_auc=0.8165
model=transformerconv top_k=500 fold=5 epoch=40 loss=2.8610 val_auc=0.8169
model=transformerconv top_k=500 fold=5 epoch=41 loss=2.3819 val_auc=0.8172
model=transformerconv top_k=500 fold=5 epoch=42 loss=2.2364 val_auc=0.8174
model=transformerconv top_k=500 fold=5 epoch=43 loss=2.2122 val_auc=0.8176
model=transformerconv top_k=500 fold=5 epoch=44 loss=2.1077 val_auc=0.8181
model=transformerconv top_k=500 fold=5 epoch=45 loss=2.4847 val_auc=0.8190
model=transformerconv top_k=500 fold=5 epoch=46 loss=2.3454 val_auc=0.8202
model=transformerconv top_k=500 fold=5 epoch=47 loss=1.8565 val_auc=0.8216
model=transformerconv top_k=500 fold=5 epoch=48 loss=1.8085 val_auc=0.8228
model=transformerconv top_k=500 fold=5 epoch=49 loss=1.8557 val_auc=0.8236
model=transformerconv top_k=500 fold=5 epoch=50 loss=1.7591 val_auc=0.8243
model=transformerconv top_k=500 fold=5 epoch=51 loss=1.8639 val_auc=0.8253
model=transformerconv top_k=500 fold=5 epoch=52 loss=1.7392 val_auc=0.8260
model=transformerconv top_k=500 fold=5 epoch=53 loss=1.7619 val_auc=0.8262
model=transformerconv top_k=500 fold=5 epoch=54 loss=1.6969 val_auc=0.8270
model=transformerconv top_k=500 fold=5 epoch=55 loss=1.5894 val_auc=0.8280
model=transformerconv top_k=500 fold=5 epoch=56 loss=1.5655 val_auc=0.8285
model=transformerconv top_k=500 fold=5 epoch=57 loss=1.5642 val_auc=0.8284
model=transformerconv top_k=500 fold=5 epoch=58 loss=1.4610 val_auc=0.8282
model=transformerconv top_k=500 fold=5 epoch=59 loss=1.3708 val_auc=0.8284
model=transformerconv top_k=500 fold=5 epoch=60 loss=1.3872 val_auc=0.8285
model=transformerconv top_k=500 fold=5 epoch=61 loss=1.4201 val_auc=0.8282
model=transformerconv top_k=500 fold=5 epoch=62 loss=1.5330 val_auc=0.8278
model=transformerconv top_k=500 fold=5 epoch=63 loss=1.6052 val_auc=0.8265
model=transformerconv top_k=500 fold=5 epoch=64 loss=1.6341 val_auc=0.8263
model=transformerconv top_k=500 fold=5 epoch=65 loss=1.4591 val_auc=0.8280
model=transformerconv top_k=500 fold=5 epoch=66 loss=1.2326 val_auc=0.8295
model=transformerconv top_k=500 fold=5 epoch=67 loss=1.2759 val_auc=0.8299
model=transformerconv top_k=500 fold=5 epoch=68 loss=1.3181 val_auc=0.8301
model=transformerconv top_k=500 fold=5 epoch=69 loss=1.3300 val_auc=0.8303
model=transformerconv top_k=500 fold=5 epoch=70 loss=1.4494 val_auc=0.8306
model=transformerconv top_k=500 fold=5 epoch=71 loss=1.3377 val_auc=0.8309
model=transformerconv top_k=500 fold=5 epoch=72 loss=1.2688 val_auc=0.8311
model=transformerconv top_k=500 fold=5 epoch=73 loss=1.4968 val_auc=0.8312
model=transformerconv top_k=500 fold=5 epoch=74 loss=1.4298 val_auc=0.8309
model=transformerconv top_k=500 fold=5 epoch=75 loss=1.2133 val_auc=0.8300
model=transformerconv top_k=500 fold=5 epoch=76 loss=1.3816 val_auc=0.8298
model=transformerconv top_k=500 fold=5 epoch=77 loss=1.3272 val_auc=0.8301
model=transformerconv top_k=500 fold=5 epoch=78 loss=1.2226 val_auc=0.8305
model=transformerconv top_k=500 fold=5 epoch=79 loss=1.1480 val_auc=0.8309
model=transformerconv top_k=500 fold=5 epoch=80 loss=1.2524 val_auc=0.8313
model=transformerconv top_k=500 fold=5 epoch=81 loss=1.0870 val_auc=0.8323
model=transformerconv top_k=500 fold=5 epoch=82 loss=1.1655 val_auc=0.8331
model=transformerconv top_k=500 fold=5 epoch=83 loss=1.0921 val_auc=0.8337
model=transformerconv top_k=500 fold=5 epoch=84 loss=1.1948 val_auc=0.8338
model=transformerconv top_k=500 fold=5 epoch=85 loss=1.1634 val_auc=0.8334
model=transformerconv top_k=500 fold=5 epoch=86 loss=1.1303 val_auc=0.8324
model=transformerconv top_k=500 fold=5 epoch=87 loss=1.2475 val_auc=0.8320
model=transformerconv top_k=500 fold=5 epoch=88 loss=1.1885 val_auc=0.8326
model=transformerconv top_k=500 fold=5 epoch=89 loss=1.2098 val_auc=0.8331
model=transformerconv top_k=500 fold=5 epoch=90 loss=1.1054 val_auc=0.8329
model=transformerconv top_k=500 fold=5 epoch=91 loss=1.1735 val_auc=0.8328
model=transformerconv top_k=500 fold=5 epoch=92 loss=1.0679 val_auc=0.8331
model=transformerconv top_k=500 fold=5 epoch=93 loss=1.0219 val_auc=0.8336
model=transformerconv top_k=500 fold=5 epoch=94 loss=1.0838 val_auc=0.8340
model=transformerconv top_k=500 fold=5 epoch=95 loss=1.1116 val_auc=0.8343
model=transformerconv top_k=500 fold=5 epoch=96 loss=1.0587 val_auc=0.8352
model=transformerconv top_k=500 fold=5 epoch=97 loss=1.1316 val_auc=0.8360
model=transformerconv top_k=500 fold=5 epoch=98 loss=1.0548 val_auc=0.8367
model=transformerconv top_k=500 fold=5 epoch=99 loss=1.0050 val_auc=0.8376
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718759 edges

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=500 fold=6 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718481 edges
model=transformerconv top_k=500 fold=6 epoch=0 loss=21.0992 val_auc=0.4655
model=transformerconv top_k=500 fold=6 epoch=1 loss=17.0287 val_auc=0.5341
model=transformerconv top_k=500 fold=6 epoch=2 loss=10.3542 val_auc=0.7126
model=transformerconv top_k=500 fold=6 epoch=3 loss=6.6089 val_auc=0.7726
model=transformerconv top_k=500 fold=6 epoch=4 loss=6.6391 val_auc=0.7826
model=transformerconv top_k=500 fold=6 epoch=5 loss=5.3561 val_auc=0.7886
model=transformerconv top_k=500 fold=6 epoch=6 loss=4.0367 val_auc=0.7920
model=transformerconv top_k=500 fold=6 epoch=7 loss=4.3333 val_auc=0.7954
model=transformerconv top_k=500 fold=6 epoch=8 loss=3.7177 val_auc=0.7978
model=transformerconv top_k=500 fold=6 epoch=9 loss=3.8868 val_auc=0.7992
model=transformerconv top_k=500 fold=6 epoch=10 loss=4.7249 val_auc=0.8017
model=transformerconv top_k=500 fold=6 epoch=11 loss=4.6109 val_auc=0.8044
model=transformerconv top_k=500 fold=6 epoch=12 loss=3.1794 val_auc=0.8070
model=transformerconv top_k=500 fold=6 epoch=13 loss=3.8647 val_auc=0.8087
model=transformerconv top_k=500 fold=6 epoch=14 loss=3.7903 val_auc=0.8095
model=transformerconv top_k=500 fold=6 epoch=15 loss=3.6962 val_auc=0.8095
model=transformerconv top_k=500 fold=6 epoch=16 loss=2.9671 val_auc=0.8094
model=transformerconv top_k=500 fold=6 epoch=17 loss=4.7875 val_auc=0.8104
model=transformerconv top_k=500 fold=6 epoch=18 loss=5.0098 val_auc=0.8120
model=transformerconv top_k=500 fold=6 epoch=19 loss=4.7108 val_auc=0.8139
model=transformerconv top_k=500 fold=6 epoch=20 loss=3.4374 val_auc=0.8159
model=transformerconv top_k=500 fold=6 epoch=21 loss=3.0072 val_auc=0.8176
model=transformerconv top_k=500 fold=6 epoch=22 loss=4.2019 val_auc=0.8184
model=transformerconv top_k=500 fold=6 epoch=23 loss=6.0544 val_auc=0.8186
model=transformerconv top_k=500 fold=6 epoch=24 loss=5.9559 val_auc=0.8183
model=transformerconv top_k=500 fold=6 epoch=25 loss=6.2504 val_auc=0.8175
model=transformerconv top_k=500 fold=6 epoch=26 loss=4.2550 val_auc=0.8169
model=transformerconv top_k=500 fold=6 epoch=27 loss=2.6010 val_auc=0.8168
model=transformerconv top_k=500 fold=6 epoch=28 loss=2.7269 val_auc=0.8171
model=transformerconv top_k=500 fold=6 epoch=29 loss=3.7701 val_auc=0.8175
model=transformerconv top_k=500 fold=6 epoch=30 loss=2.6652 val_auc=0.8180
model=transformerconv top_k=500 fold=6 epoch=31 loss=2.6051 val_auc=0.8188
model=transformerconv top_k=500 fold=6 epoch=32 loss=2.7367 val_auc=0.8197
model=transformerconv top_k=500 fold=6 epoch=33 loss=2.7407 val_auc=0.8208
model=transformerconv top_k=500 fold=6 epoch=34 loss=2.1373 val_auc=0.8221
model=transformerconv top_k=500 fold=6 epoch=35 loss=2.1124 val_auc=0.8229
model=transformerconv top_k=500 fold=6 epoch=36 loss=2.3489 val_auc=0.8239
model=transformerconv top_k=500 fold=6 epoch=37 loss=2.0782 val_auc=0.8248
model=transformerconv top_k=500 fold=6 epoch=38 loss=2.5852 val_auc=0.8254
model=transformerconv top_k=500 fold=6 epoch=39 loss=2.2005 val_auc=0.8260
model=transformerconv top_k=500 fold=6 epoch=40 loss=1.9951 val_auc=0.8263
model=transformerconv top_k=500 fold=6 epoch=41 loss=2.0745 val_auc=0.8269
model=transformerconv top_k=500 fold=6 epoch=42 loss=1.9261 val_auc=0.8266
model=transformerconv top_k=500 fold=6 epoch=43 loss=2.1816 val_auc=0.8261
model=transformerconv top_k=500 fold=6 epoch=44 loss=1.8811 val_auc=0.8255
model=transformerconv top_k=500 fold=6 epoch=45 loss=1.9270 val_auc=0.8261
model=transformerconv top_k=500 fold=6 epoch=46 loss=2.2903 val_auc=0.8269
model=transformerconv top_k=500 fold=6 epoch=47 loss=1.7428 val_auc=0.8282
model=transformerconv top_k=500 fold=6 epoch=48 loss=1.9332 val_auc=0.8288
model=transformerconv top_k=500 fold=6 epoch=49 loss=1.6811 val_auc=0.8303
model=transformerconv top_k=500 fold=6 epoch=50 loss=1.7093 val_auc=0.8316
model=transformerconv top_k=500 fold=6 epoch=51 loss=1.5728 val_auc=0.8325
model=transformerconv top_k=500 fold=6 epoch=52 loss=1.6562 val_auc=0.8331
model=transformerconv top_k=500 fold=6 epoch=53 loss=1.5521 val_auc=0.8333
model=transformerconv top_k=500 fold=6 epoch=54 loss=1.5439 val_auc=0.8335
model=transformerconv top_k=500 fold=6 epoch=55 loss=1.5112 val_auc=0.8336
model=transformerconv top_k=500 fold=6 epoch=56 loss=1.6026 val_auc=0.8334
model=transformerconv top_k=500 fold=6 epoch=57 loss=1.5715 val_auc=0.8328
model=transformerconv top_k=500 fold=6 epoch=58 loss=1.7070 val_auc=0.8321
model=transformerconv top_k=500 fold=6 epoch=59 loss=1.7019 val_auc=0.8309
model=transformerconv top_k=500 fold=6 epoch=60 loss=1.5852 val_auc=0.8301
model=transformerconv top_k=500 fold=6 epoch=61 loss=1.6156 val_auc=0.8297
model=transformerconv top_k=500 fold=6 epoch=62 loss=1.4775 val_auc=0.8299
model=transformerconv top_k=500 fold=6 epoch=63 loss=1.4923 val_auc=0.8300
model=transformerconv top_k=500 fold=6 epoch=64 loss=1.5003 val_auc=0.8299
model=transformerconv top_k=500 fold=6 epoch=65 loss=1.3257 val_auc=0.8296
model=transformerconv top_k=500 fold=6 epoch=66 loss=1.2732 val_auc=0.8302
model=transformerconv top_k=500 fold=6 epoch=67 loss=1.2425 val_auc=0.8311
transformerconv top_k=500 fold=6: early stopping at epoch 67
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718481 edges

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=500 fold=7 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719141 edges
model=transformerconv top_k=500 fold=7 epoch=0 loss=5.4183 val_auc=0.5014
model=transformerconv top_k=500 fold=7 epoch=1 loss=30.1674 val_auc=0.5306
model=transformerconv top_k=500 fold=7 epoch=2 loss=25.7500 val_auc=0.7531
model=transformerconv top_k=500 fold=7 epoch=3 loss=10.1080 val_auc=0.7527
model=transformerconv top_k=500 fold=7 epoch=4 loss=6.4347 val_auc=0.7570
model=transformerconv top_k=500 fold=7 epoch=5 loss=8.8918 val_auc=0.7600
model=transformerconv top_k=500 fold=7 epoch=6 loss=8.1902 val_auc=0.7600
model=transformerconv top_k=500 fold=7 epoch=7 loss=5.2113 val_auc=0.7635
model=transformerconv top_k=500 fold=7 epoch=8 loss=5.1650 val_auc=0.7672
model=transformerconv top_k=500 fold=7 epoch=9 loss=5.3820 val_auc=0.7700
model=transformerconv top_k=500 fold=7 epoch=10 loss=4.9467 val_auc=0.7717
model=transformerconv top_k=500 fold=7 epoch=11 loss=3.7476 val_auc=0.7738
model=transformerconv top_k=500 fold=7 epoch=12 loss=3.9332 val_auc=0.7767
model=transformerconv top_k=500 fold=7 epoch=13 loss=3.9378 val_auc=0.7803
model=transformerconv top_k=500 fold=7 epoch=14 loss=3.2969 val_auc=0.7844
model=transformerconv top_k=500 fold=7 epoch=15 loss=3.7782 val_auc=0.7877
model=transformerconv top_k=500 fold=7 epoch=16 loss=3.4068 val_auc=0.7914
model=transformerconv top_k=500 fold=7 epoch=17 loss=3.5278 val_auc=0.7935
model=transformerconv top_k=500 fold=7 epoch=18 loss=3.9239 val_auc=0.7941
model=transformerconv top_k=500 fold=7 epoch=19 loss=3.1113 val_auc=0.7940
model=transformerconv top_k=500 fold=7 epoch=20 loss=3.5221 val_auc=0.7950
model=transformerconv top_k=500 fold=7 epoch=21 loss=3.0368 val_auc=0.7975
model=transformerconv top_k=500 fold=7 epoch=22 loss=3.1015 val_auc=0.8011
model=transformerconv top_k=500 fold=7 epoch=23 loss=2.8218 val_auc=0.8037
model=transformerconv top_k=500 fold=7 epoch=24 loss=3.2605 val_auc=0.8056
model=transformerconv top_k=500 fold=7 epoch=25 loss=2.7226 val_auc=0.8078
model=transformerconv top_k=500 fold=7 epoch=26 loss=2.7604 val_auc=0.8094
model=transformerconv top_k=500 fold=7 epoch=27 loss=2.7327 val_auc=0.8099
model=transformerconv top_k=500 fold=7 epoch=28 loss=3.0580 val_auc=0.8098
model=transformerconv top_k=500 fold=7 epoch=29 loss=2.5536 val_auc=0.8093
model=transformerconv top_k=500 fold=7 epoch=30 loss=3.0761 val_auc=0.8091
model=transformerconv top_k=500 fold=7 epoch=31 loss=3.4646 val_auc=0.8093
model=transformerconv top_k=500 fold=7 epoch=32 loss=2.9845 val_auc=0.8100
model=transformerconv top_k=500 fold=7 epoch=33 loss=2.6189 val_auc=0.8108
model=transformerconv top_k=500 fold=7 epoch=34 loss=2.5003 val_auc=0.8113
model=transformerconv top_k=500 fold=7 epoch=35 loss=3.3045 val_auc=0.8116
model=transformerconv top_k=500 fold=7 epoch=36 loss=2.7508 val_auc=0.8120
model=transformerconv top_k=500 fold=7 epoch=37 loss=2.2493 val_auc=0.8124
model=transformerconv top_k=500 fold=7 epoch=38 loss=2.5061 val_auc=0.8131
model=transformerconv top_k=500 fold=7 epoch=39 loss=2.4270 val_auc=0.8139
model=transformerconv top_k=500 fold=7 epoch=40 loss=2.1247 val_auc=0.8146
model=transformerconv top_k=500 fold=7 epoch=41 loss=2.1027 val_auc=0.8154
model=transformerconv top_k=500 fold=7 epoch=42 loss=2.4154 val_auc=0.8160
model=transformerconv top_k=500 fold=7 epoch=43 loss=1.8893 val_auc=0.8168
model=transformerconv top_k=500 fold=7 epoch=44 loss=2.0106 val_auc=0.8173
model=transformerconv top_k=500 fold=7 epoch=45 loss=2.2029 val_auc=0.8179
model=transformerconv top_k=500 fold=7 epoch=46 loss=1.8719 val_auc=0.8186
model=transformerconv top_k=500 fold=7 epoch=47 loss=2.1671 val_auc=0.8192
model=transformerconv top_k=500 fold=7 epoch=48 loss=1.9378 val_auc=0.8198
model=transformerconv top_k=500 fold=7 epoch=49 loss=1.7684 val_auc=0.8203
model=transformerconv top_k=500 fold=7 epoch=50 loss=1.8281 val_auc=0.8205
model=transformerconv top_k=500 fold=7 epoch=51 loss=1.8159 val_auc=0.8211
model=transformerconv top_k=500 fold=7 epoch=52 loss=1.9015 val_auc=0.8216
model=transformerconv top_k=500 fold=7 epoch=53 loss=1.8472 val_auc=0.8220
model=transformerconv top_k=500 fold=7 epoch=54 loss=1.8058 val_auc=0.8226
model=transformerconv top_k=500 fold=7 epoch=55 loss=2.0596 val_auc=0.8230
model=transformerconv top_k=500 fold=7 epoch=56 loss=1.5567 val_auc=0.8236
model=transformerconv top_k=500 fold=7 epoch=57 loss=1.9537 val_auc=0.8242
model=transformerconv top_k=500 fold=7 epoch=58 loss=1.8036 val_auc=0.8243
model=transformerconv top_k=500 fold=7 epoch=59 loss=1.6761 val_auc=0.8244
model=transformerconv top_k=500 fold=7 epoch=60 loss=1.4483 val_auc=0.8244
model=transformerconv top_k=500 fold=7 epoch=61 loss=1.5303 val_auc=0.8245
model=transformerconv top_k=500 fold=7 epoch=62 loss=1.5859 val_auc=0.8246
model=transformerconv top_k=500 fold=7 epoch=63 loss=1.6489 val_auc=0.8246
model=transformerconv top_k=500 fold=7 epoch=64 loss=1.7065 val_auc=0.8245
model=transformerconv top_k=500 fold=7 epoch=65 loss=1.4782 val_auc=0.8247
model=transformerconv top_k=500 fold=7 epoch=66 loss=1.5928 val_auc=0.8251
model=transformerconv top_k=500 fold=7 epoch=67 loss=1.6801 val_auc=0.8254
model=transformerconv top_k=500 fold=7 epoch=68 loss=1.6826 val_auc=0.8255
model=transformerconv top_k=500 fold=7 epoch=69 loss=1.6210 val_auc=0.8254
model=transformerconv top_k=500 fold=7 epoch=70 loss=1.4280 val_auc=0.8256
model=transformerconv top_k=500 fold=7 epoch=71 loss=1.5216 val_auc=0.8260
model=transformerconv top_k=500 fold=7 epoch=72 loss=1.4721 val_auc=0.8268
model=transformerconv top_k=500 fold=7 epoch=73 loss=1.3806 val_auc=0.8273
model=transformerconv top_k=500 fold=7 epoch=74 loss=1.7467 val_auc=0.8276
model=transformerconv top_k=500 fold=7 epoch=75 loss=1.2247 val_auc=0.8281
model=transformerconv top_k=500 fold=7 epoch=76 loss=1.2289 val_auc=0.8284
model=transformerconv top_k=500 fold=7 epoch=77 loss=1.2549 val_auc=0.8287
model=transformerconv top_k=500 fold=7 epoch=78 loss=1.1715 val_auc=0.8288
model=transformerconv top_k=500 fold=7 epoch=79 loss=1.1888 val_auc=0.8286
model=transformerconv top_k=500 fold=7 epoch=80 loss=1.2101 val_auc=0.8284
model=transformerconv top_k=500 fold=7 epoch=81 loss=1.3255 val_auc=0.8288
model=transformerconv top_k=500 fold=7 epoch=82 loss=1.2509 val_auc=0.8292
model=transformerconv top_k=500 fold=7 epoch=83 loss=1.1824 val_auc=0.8300
model=transformerconv top_k=500 fold=7 epoch=84 loss=1.3107 val_auc=0.8307
model=transformerconv top_k=500 fold=7 epoch=85 loss=1.2569 val_auc=0.8314
model=transformerconv top_k=500 fold=7 epoch=86 loss=1.1670 val_auc=0.8324
model=transformerconv top_k=500 fold=7 epoch=87 loss=1.3179 val_auc=0.8330
model=transformerconv top_k=500 fold=7 epoch=88 loss=1.2022 val_auc=0.8334
model=transformerconv top_k=500 fold=7 epoch=89 loss=1.1388 val_auc=0.8336
model=transformerconv top_k=500 fold=7 epoch=90 loss=1.1282 val_auc=0.8339
model=transformerconv top_k=500 fold=7 epoch=91 loss=1.1389 val_auc=0.8346
model=transformerconv top_k=500 fold=7 epoch=92 loss=1.3027 val_auc=0.8349
model=transformerconv top_k=500 fold=7 epoch=93 loss=1.1912 val_auc=0.8350
model=transformerconv top_k=500 fold=7 epoch=94 loss=1.1180 val_auc=0.8356
model=transformerconv top_k=500 fold=7 epoch=95 loss=1.0329 val_auc=0.8365
model=transformerconv top_k=500 fold=7 epoch=96 loss=1.0310 val_auc=0.8372
model=transformerconv top_k=500 fold=7 epoch=97 loss=1.0361 val_auc=0.8376
model=transformerconv top_k=500 fold=7 epoch=98 loss=1.1381 val_auc=0.8377
model=transformerconv top_k=500 fold=7 epoch=99 loss=1.0558 val_auc=0.8373
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 719141 edges

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=500 fold=8 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718578 edges
model=transformerconv top_k=500 fold=8 epoch=0 loss=5.5011 val_auc=0.7466
model=transformerconv top_k=500 fold=8 epoch=1 loss=14.9222 val_auc=0.7574
model=transformerconv top_k=500 fold=8 epoch=2 loss=5.3900 val_auc=0.7193
model=transformerconv top_k=500 fold=8 epoch=3 loss=14.4783 val_auc=0.7082
model=transformerconv top_k=500 fold=8 epoch=4 loss=14.4141 val_auc=0.7597
model=transformerconv top_k=500 fold=8 epoch=5 loss=9.5720 val_auc=0.7658
model=transformerconv top_k=500 fold=8 epoch=6 loss=4.1677 val_auc=0.7700
model=transformerconv top_k=500 fold=8 epoch=7 loss=7.5468 val_auc=0.7724
model=transformerconv top_k=500 fold=8 epoch=8 loss=7.2902 val_auc=0.7739
model=transformerconv top_k=500 fold=8 epoch=9 loss=6.6043 val_auc=0.7746
model=transformerconv top_k=500 fold=8 epoch=10 loss=3.9008 val_auc=0.7756
model=transformerconv top_k=500 fold=8 epoch=11 loss=4.2052 val_auc=0.7767
model=transformerconv top_k=500 fold=8 epoch=12 loss=4.7176 val_auc=0.7783
model=transformerconv top_k=500 fold=8 epoch=13 loss=5.0660 val_auc=0.7798
model=transformerconv top_k=500 fold=8 epoch=14 loss=3.5940 val_auc=0.7818
model=transformerconv top_k=500 fold=8 epoch=15 loss=3.3966 val_auc=0.7839
model=transformerconv top_k=500 fold=8 epoch=16 loss=3.4017 val_auc=0.7862
model=transformerconv top_k=500 fold=8 epoch=17 loss=3.0411 val_auc=0.7864
model=transformerconv top_k=500 fold=8 epoch=18 loss=3.3245 val_auc=0.7870
model=transformerconv top_k=500 fold=8 epoch=19 loss=3.8940 val_auc=0.7872
model=transformerconv top_k=500 fold=8 epoch=20 loss=2.9364 val_auc=0.7875
model=transformerconv top_k=500 fold=8 epoch=21 loss=2.6209 val_auc=0.7886
model=transformerconv top_k=500 fold=8 epoch=22 loss=3.7964 val_auc=0.7896
model=transformerconv top_k=500 fold=8 epoch=23 loss=2.9113 val_auc=0.7904
model=transformerconv top_k=500 fold=8 epoch=24 loss=3.4840 val_auc=0.7906
model=transformerconv top_k=500 fold=8 epoch=25 loss=2.5241 val_auc=0.7926
model=transformerconv top_k=500 fold=8 epoch=26 loss=3.4554 val_auc=0.7935
model=transformerconv top_k=500 fold=8 epoch=27 loss=2.4421 val_auc=0.7940
model=transformerconv top_k=500 fold=8 epoch=28 loss=2.8654 val_auc=0.7949
model=transformerconv top_k=500 fold=8 epoch=29 loss=3.2000 val_auc=0.7958
model=transformerconv top_k=500 fold=8 epoch=30 loss=2.3769 val_auc=0.7966
model=transformerconv top_k=500 fold=8 epoch=31 loss=2.0959 val_auc=0.7978
model=transformerconv top_k=500 fold=8 epoch=32 loss=2.3702 val_auc=0.7991
model=transformerconv top_k=500 fold=8 epoch=33 loss=2.7084 val_auc=0.8000
model=transformerconv top_k=500 fold=8 epoch=34 loss=2.6873 val_auc=0.8008
model=transformerconv top_k=500 fold=8 epoch=35 loss=2.0499 val_auc=0.8015
model=transformerconv top_k=500 fold=8 epoch=36 loss=2.4257 val_auc=0.8032
model=transformerconv top_k=500 fold=8 epoch=37 loss=3.0903 val_auc=0.8045
model=transformerconv top_k=500 fold=8 epoch=38 loss=2.4018 val_auc=0.8054
model=transformerconv top_k=500 fold=8 epoch=39 loss=2.4803 val_auc=0.8063
model=transformerconv top_k=500 fold=8 epoch=40 loss=2.4379 val_auc=0.8074
model=transformerconv top_k=500 fold=8 epoch=41 loss=2.3513 val_auc=0.8084
model=transformerconv top_k=500 fold=8 epoch=42 loss=2.4930 val_auc=0.8090
model=transformerconv top_k=500 fold=8 epoch=43 loss=1.7646 val_auc=0.8093
model=transformerconv top_k=500 fold=8 epoch=44 loss=1.7713 val_auc=0.8095
model=transformerconv top_k=500 fold=8 epoch=45 loss=1.9975 val_auc=0.8099
model=transformerconv top_k=500 fold=8 epoch=46 loss=1.9645 val_auc=0.8104
model=transformerconv top_k=500 fold=8 epoch=47 loss=1.9685 val_auc=0.8113
model=transformerconv top_k=500 fold=8 epoch=48 loss=1.7343 val_auc=0.8119
model=transformerconv top_k=500 fold=8 epoch=49 loss=2.4770 val_auc=0.8123
model=transformerconv top_k=500 fold=8 epoch=50 loss=2.4823 val_auc=0.8125
model=transformerconv top_k=500 fold=8 epoch=51 loss=2.0441 val_auc=0.8123
model=transformerconv top_k=500 fold=8 epoch=52 loss=1.9932 val_auc=0.8121
model=transformerconv top_k=500 fold=8 epoch=53 loss=1.5814 val_auc=0.8120
model=transformerconv top_k=500 fold=8 epoch=54 loss=1.6599 val_auc=0.8120
model=transformerconv top_k=500 fold=8 epoch=55 loss=1.8962 val_auc=0.8121
model=transformerconv top_k=500 fold=8 epoch=56 loss=1.6604 val_auc=0.8120
model=transformerconv top_k=500 fold=8 epoch=57 loss=1.8589 val_auc=0.8118
model=transformerconv top_k=500 fold=8 epoch=58 loss=2.1935 val_auc=0.8116
model=transformerconv top_k=500 fold=8 epoch=59 loss=1.7963 val_auc=0.8117
model=transformerconv top_k=500 fold=8 epoch=60 loss=1.6140 val_auc=0.8120
model=transformerconv top_k=500 fold=8 epoch=61 loss=1.4706 val_auc=0.8125
model=transformerconv top_k=500 fold=8 epoch=62 loss=1.4079 val_auc=0.8140
model=transformerconv top_k=500 fold=8 epoch=63 loss=1.4621 val_auc=0.8163
model=transformerconv top_k=500 fold=8 epoch=64 loss=1.5443 val_auc=0.8181
model=transformerconv top_k=500 fold=8 epoch=65 loss=1.6501 val_auc=0.8188
model=transformerconv top_k=500 fold=8 epoch=66 loss=1.6502 val_auc=0.8194
model=transformerconv top_k=500 fold=8 epoch=67 loss=1.5452 val_auc=0.8195
model=transformerconv top_k=500 fold=8 epoch=68 loss=1.6530 val_auc=0.8193
model=transformerconv top_k=500 fold=8 epoch=69 loss=1.6464 val_auc=0.8187
model=transformerconv top_k=500 fold=8 epoch=70 loss=1.6397 val_auc=0.8182
model=transformerconv top_k=500 fold=8 epoch=71 loss=1.5658 val_auc=0.8180
model=transformerconv top_k=500 fold=8 epoch=72 loss=1.5876 val_auc=0.8181
model=transformerconv top_k=500 fold=8 epoch=73 loss=1.5107 val_auc=0.8181
model=transformerconv top_k=500 fold=8 epoch=74 loss=1.5401 val_auc=0.8179
model=transformerconv top_k=500 fold=8 epoch=75 loss=1.3222 val_auc=0.8178
model=transformerconv top_k=500 fold=8 epoch=76 loss=1.2536 val_auc=0.8186
model=transformerconv top_k=500 fold=8 epoch=77 loss=1.2767 val_auc=0.8198
model=transformerconv top_k=500 fold=8 epoch=78 loss=1.2808 val_auc=0.8208
model=transformerconv top_k=500 fold=8 epoch=79 loss=1.4324 val_auc=0.8213
model=transformerconv top_k=500 fold=8 epoch=80 loss=1.1856 val_auc=0.8218
model=transformerconv top_k=500 fold=8 epoch=81 loss=1.2409 val_auc=0.8219
model=transformerconv top_k=500 fold=8 epoch=82 loss=1.2745 val_auc=0.8220
model=transformerconv top_k=500 fold=8 epoch=83 loss=1.3092 val_auc=0.8222
model=transformerconv top_k=500 fold=8 epoch=84 loss=1.3237 val_auc=0.8219
model=transformerconv top_k=500 fold=8 epoch=85 loss=1.4336 val_auc=0.8218
model=transformerconv top_k=500 fold=8 epoch=86 loss=1.6581 val_auc=0.8219
model=transformerconv top_k=500 fold=8 epoch=87 loss=1.2910 val_auc=0.8219
model=transformerconv top_k=500 fold=8 epoch=88 loss=1.2712 val_auc=0.8218
model=transformerconv top_k=500 fold=8 epoch=89 loss=1.5284 val_auc=0.8220
model=transformerconv top_k=500 fold=8 epoch=90 loss=1.7293 val_auc=0.8223
model=transformerconv top_k=500 fold=8 epoch=91 loss=1.9316 val_auc=0.8225
model=transformerconv top_k=500 fold=8 epoch=92 loss=1.3761 val_auc=0.8224
model=transformerconv top_k=500 fold=8 epoch=93 loss=1.1484 val_auc=0.8222
model=transformerconv top_k=500 fold=8 epoch=94 loss=1.3946 val_auc=0.8218
model=transformerconv top_k=500 fold=8 epoch=95 loss=1.2933 val_auc=0.8219
model=transformerconv top_k=500 fold=8 epoch=96 loss=1.1941 val_auc=0.8228
model=transformerconv top_k=500 fold=8 epoch=97 loss=1.2107 val_auc=0.8238
model=transformerconv top_k=500 fold=8 epoch=98 loss=1.3089 val_auc=0.8245
model=transformerconv top_k=500 fold=8 epoch=99 loss=1.3923 val_auc=0.8249
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718578 edges

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/35 [00:00<?, ?it/s]

===== Model=transformerconv top_k=500 fold=9 =====
Config for transformerconv: {'hidden_dim': 128, 'num_layers': 1, 'num_heads': 2, 'dropout': 0.2, 'max_train_similar_edges_per_node': 50, 'query_inference_chunk_size': 128}
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718994 edges
model=transformerconv top_k=500 fold=9 epoch=0 loss=6.5812 val_auc=0.6927
model=transformerconv top_k=500 fold=9 epoch=1 loss=28.2920 val_auc=0.7219
model=transformerconv top_k=500 fold=9 epoch=2 loss=21.9694 val_auc=0.7177
model=transformerconv top_k=500 fold=9 epoch=3 loss=8.4224 val_auc=0.6980
model=transformerconv top_k=500 fold=9 epoch=4 loss=6.6233 val_auc=0.7159
model=transformerconv top_k=500 fold=9 epoch=5 loss=7.1836 val_auc=0.7382
model=transformerconv top_k=500 fold=9 epoch=6 loss=5.2840 val_auc=0.7511
model=transformerconv top_k=500 fold=9 epoch=7 loss=4.7431 val_auc=0.7589
model=transformerconv top_k=500 fold=9 epoch=8 loss=3.4358 val_auc=0.7660
model=transformerconv top_k=500 fold=9 epoch=9 loss=4.3190 val_auc=0.7756
model=transformerconv top_k=500 fold=9 epoch=10 loss=3.4433 val_auc=0.7818
model=transformerconv top_k=500 fold=9 epoch=11 loss=4.2622 val_auc=0.7847
model=transformerconv top_k=500 fold=9 epoch=12 loss=4.2141 val_auc=0.7856
model=transformerconv top_k=500 fold=9 epoch=13 loss=3.2504 val_auc=0.7869
model=transformerconv top_k=500 fold=9 epoch=14 loss=3.6735 val_auc=0.7882
model=transformerconv top_k=500 fold=9 epoch=15 loss=3.8726 val_auc=0.7898
model=transformerconv top_k=500 fold=9 epoch=16 loss=3.8694 val_auc=0.7903
model=transformerconv top_k=500 fold=9 epoch=17 loss=2.9916 val_auc=0.7915
model=transformerconv top_k=500 fold=9 epoch=18 loss=3.0359 val_auc=0.7920
model=transformerconv top_k=500 fold=9 epoch=19 loss=3.1714 val_auc=0.7934
model=transformerconv top_k=500 fold=9 epoch=20 loss=3.0289 val_auc=0.7945
model=transformerconv top_k=500 fold=9 epoch=21 loss=2.8794 val_auc=0.7962
model=transformerconv top_k=500 fold=9 epoch=22 loss=3.1027 val_auc=0.7975
model=transformerconv top_k=500 fold=9 epoch=23 loss=2.5907 val_auc=0.7994
model=transformerconv top_k=500 fold=9 epoch=24 loss=2.7412 val_auc=0.8015
model=transformerconv top_k=500 fold=9 epoch=25 loss=2.7060 val_auc=0.8037
model=transformerconv top_k=500 fold=9 epoch=26 loss=2.7618 val_auc=0.8055
model=transformerconv top_k=500 fold=9 epoch=27 loss=2.8122 val_auc=0.8069
model=transformerconv top_k=500 fold=9 epoch=28 loss=2.4209 val_auc=0.8081
model=transformerconv top_k=500 fold=9 epoch=29 loss=2.2898 val_auc=0.8095
model=transformerconv top_k=500 fold=9 epoch=30 loss=2.9704 val_auc=0.8105
model=transformerconv top_k=500 fold=9 epoch=31 loss=2.3718 val_auc=0.8108
model=transformerconv top_k=500 fold=9 epoch=32 loss=2.2553 val_auc=0.8107
model=transformerconv top_k=500 fold=9 epoch=33 loss=2.1676 val_auc=0.8113
model=transformerconv top_k=500 fold=9 epoch=34 loss=2.7301 val_auc=0.8121
model=transformerconv top_k=500 fold=9 epoch=35 loss=2.4233 val_auc=0.8136
model=transformerconv top_k=500 fold=9 epoch=36 loss=2.4212 val_auc=0.8146
model=transformerconv top_k=500 fold=9 epoch=37 loss=2.0644 val_auc=0.8150
model=transformerconv top_k=500 fold=9 epoch=38 loss=1.8009 val_auc=0.8154
model=transformerconv top_k=500 fold=9 epoch=39 loss=2.0735 val_auc=0.8166
model=transformerconv top_k=500 fold=9 epoch=40 loss=2.5373 val_auc=0.8175
model=transformerconv top_k=500 fold=9 epoch=41 loss=1.8419 val_auc=0.8182
model=transformerconv top_k=500 fold=9 epoch=42 loss=2.0136 val_auc=0.8185
model=transformerconv top_k=500 fold=9 epoch=43 loss=2.2164 val_auc=0.8190
model=transformerconv top_k=500 fold=9 epoch=44 loss=2.0103 val_auc=0.8193
model=transformerconv top_k=500 fold=9 epoch=45 loss=2.0497 val_auc=0.8195
model=transformerconv top_k=500 fold=9 epoch=46 loss=1.8714 val_auc=0.8196
model=transformerconv top_k=500 fold=9 epoch=47 loss=1.8994 val_auc=0.8197
model=transformerconv top_k=500 fold=9 epoch=48 loss=1.6664 val_auc=0.8197
model=transformerconv top_k=500 fold=9 epoch=49 loss=1.7948 val_auc=0.8196
model=transformerconv top_k=500 fold=9 epoch=50 loss=1.8479 val_auc=0.8192
model=transformerconv top_k=500 fold=9 epoch=51 loss=1.5375 val_auc=0.8187
model=transformerconv top_k=500 fold=9 epoch=52 loss=1.5679 val_auc=0.8182
model=transformerconv top_k=500 fold=9 epoch=53 loss=1.6509 val_auc=0.8182
model=transformerconv top_k=500 fold=9 epoch=54 loss=1.8520 val_auc=0.8184
model=transformerconv top_k=500 fold=9 epoch=55 loss=1.6202 val_auc=0.8189
model=transformerconv top_k=500 fold=9 epoch=56 loss=1.4977 val_auc=0.8202
model=transformerconv top_k=500 fold=9 epoch=57 loss=1.7283 val_auc=0.8211
model=transformerconv top_k=500 fold=9 epoch=58 loss=1.9291 val_auc=0.8213
model=transformerconv top_k=500 fold=9 epoch=59 loss=1.8764 val_auc=0.8211
model=transformerconv top_k=500 fold=9 epoch=60 loss=1.4286 val_auc=0.8208
model=transformerconv top_k=500 fold=9 epoch=61 loss=1.4148 val_auc=0.8208
model=transformerconv top_k=500 fold=9 epoch=62 loss=1.8898 val_auc=0.8211
model=transformerconv top_k=500 fold=9 epoch=63 loss=1.9037 val_auc=0.8214
model=transformerconv top_k=500 fold=9 epoch=64 loss=1.5239 val_auc=0.8215
model=transformerconv top_k=500 fold=9 epoch=65 loss=1.3966 val_auc=0.8217
model=transformerconv top_k=500 fold=9 epoch=66 loss=1.8215 val_auc=0.8214
model=transformerconv top_k=500 fold=9 epoch=67 loss=1.9315 val_auc=0.8217
model=transformerconv top_k=500 fold=9 epoch=68 loss=1.7302 val_auc=0.8221
model=transformerconv top_k=500 fold=9 epoch=69 loss=1.4707 val_auc=0.8217
model=transformerconv top_k=500 fold=9 epoch=70 loss=1.3350 val_auc=0.8215
model=transformerconv top_k=500 fold=9 epoch=71 loss=1.6661 val_auc=0.8215
model=transformerconv top_k=500 fold=9 epoch=72 loss=2.1979 val_auc=0.8214
model=transformerconv top_k=500 fold=9 epoch=73 loss=2.3310 val_auc=0.8214
model=transformerconv top_k=500 fold=9 epoch=74 loss=1.6828 val_auc=0.8215
model=transformerconv top_k=500 fold=9 epoch=75 loss=1.4628 val_auc=0.8219
model=transformerconv top_k=500 fold=9 epoch=76 loss=1.5034 val_auc=0.8222
model=transformerconv top_k=500 fold=9 epoch=77 loss=1.5065 val_auc=0.8222
model=transformerconv top_k=500 fold=9 epoch=78 loss=1.6803 val_auc=0.8217
model=transformerconv top_k=500 fold=9 epoch=79 loss=1.3427 val_auc=0.8212
model=transformerconv top_k=500 fold=9 epoch=80 loss=1.2581 val_auc=0.8217
model=transformerconv top_k=500 fold=9 epoch=81 loss=1.2868 val_auc=0.8224
model=transformerconv top_k=500 fold=9 epoch=82 loss=1.6291 val_auc=0.8231
model=transformerconv top_k=500 fold=9 epoch=83 loss=1.3711 val_auc=0.8233
model=transformerconv top_k=500 fold=9 epoch=84 loss=1.3763 val_auc=0.8240
model=transformerconv top_k=500 fold=9 epoch=85 loss=1.2312 val_auc=0.8251
model=transformerconv top_k=500 fold=9 epoch=86 loss=1.4405 val_auc=0.8260
model=transformerconv top_k=500 fold=9 epoch=87 loss=1.2832 val_auc=0.8264
model=transformerconv top_k=500 fold=9 epoch=88 loss=1.3180 val_auc=0.8268
model=transformerconv top_k=500 fold=9 epoch=89 loss=1.3227 val_auc=0.8270
model=transformerconv top_k=500 fold=9 epoch=90 loss=1.2627 val_auc=0.8269
model=transformerconv top_k=500 fold=9 epoch=91 loss=1.2716 val_auc=0.8266
model=transformerconv top_k=500 fold=9 epoch=92 loss=1.2160 val_auc=0.8262
model=transformerconv top_k=500 fold=9 epoch=93 loss=1.1922 val_auc=0.8261
model=transformerconv top_k=500 fold=9 epoch=94 loss=1.0563 val_auc=0.8263
model=transformerconv top_k=500 fold=9 epoch=95 loss=1.1966 val_auc=0.8266
model=transformerconv top_k=500 fold=9 epoch=96 loss=1.3055 val_auc=0.8271
model=transformerconv top_k=500 fold=9 epoch=97 loss=1.0943 val_auc=0.8278
model=transformerconv top_k=500 fold=9 epoch=98 loss=1.1475 val_auc=0.8283
model=transformerconv top_k=500 fold=9 epoch=99 loss=1.1767 val_auc=0.8287
Capped ('image', 'similar_to', 'image'): 793800 -> 793800 edges
Capped ('image', 'rev_similar_to', 'image'): 793800 -> 718994 edges

query FAISS top_k=500:   0%|          | 0/9 [00:00<?, ?it/s]

test query chunks top_k=500:   0%|          | 0/35 [00:00<?, ?it/s]

,fold,method,disease_macro_auroc,disease_macro_auprc,disease_macro_f1,all_macro_auroc,all_macro_auprc,all_macro_f1,num_scored_labels,model_name,...,include_has_finding_in_message_passing,model_path,best_epoch,best_val_disease_macro_auroc,hidden_dim,num_layers,num_heads,threshold_mode,metrics_path,max_train_similar_edges_per_node
0,0,hetero_hgtconv,0.721302,0.114645,0.116580,0.700900,0.148488,0.164838,14,hgtconv,...,False,/data/liangz2/openi/multi_kg/kg_transformer_gn...,80,0.824205,256,2,4,fixed_0.5,/data/liangz2/openi/multi_kg/kg_transformer_gn...,NaN
1,0,hetero_hgtconv,0.721302,0.114645,0.035305,0.700900,0.148488,0.089415,14,hgtconv,...,False,/data/liangz2/openi/multi_kg/kg_transformer_gn...,80,0.824205,256,2,4,val_tuned_f1,/data/liangz2/openi/multi_kg/kg_transformer_gn...,NaN
2,1,hetero_hgtconv,0.771815,0.147615,0.065293,0.733847,0.175119,0.117114,14,hgtconv,...,False,/data/liangz2/openi/multi_kg/kg_transformer_gn...,37,0.814668,256,2,4,fixed_0.5,/data/liangz2/openi/multi_kg/kg_transformer_gn...,NaN
3,1,hetero_hgtconv,0.771815,0.147615,0.011913,0.733847,0.175119,0.067547,14,hgtconv,...,False,/data/liangz2/openi/multi_kg/kg_transformer_gn...,37,0.814668,256,2,4,val_tuned_f1,/data/liangz2/openi/multi_kg/kg_transformer_gn...,NaN
4,2,hetero_hgtconv,0.753678,0.134204,0.092787,0.737006,0.171997,0.142644,14,hgtconv,...,False,/data/liangz2/openi/multi_kg/kg_transformer_gn...,74,0.838662,256,2,4,fixed_0.5,/data/liangz2/openi/multi_kg/kg_transformer_gn...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,7,hetero_transformerconv,0.773265,0.138618,0.088419,0.773863,0.188668,0.140739,14,transformerconv,...,False,/data/liangz2/openi/multi_kg/kg_transformer_gn...,98,0.837674,128,1,2,val_tuned_f1,/data/liangz2/openi/multi_kg/kg_transformer_gn...,50.0
236,8,hetero_transformerconv,0.767554,0.143248,0.165308,0.770348,0.195102,0.212266,14,transformerconv,...,False,/data/liangz2/openi/multi_kg/kg_transformer_gn...,99,0.824925,128,1,2,fixed_0.5,/data/liangz2/openi/multi_kg/kg_transformer_gn...,50.0
237,8,hetero_transformerconv,0.767554,0.143248,0.051484,0.770348,0.195102,0.107356,14,transformerconv,...,False,/data/liangz2/openi/multi_kg/kg_transformer_gn...,99,0.824925,128,1,2,val_tuned_f1,/data/liangz2/openi/multi_kg/kg_transformer_gn...,50.0
238,9,hetero_transformerconv,0.771768,0.142709,0.041440,0.773855,0.195686,0.091708,14,transformerconv,...,False,/data/liangz2/openi/multi_kg/kg_transformer_gn...,99,0.828717,128,1,2,fixed_0.5,/data/liangz2/openi/multi_kg/kg_transformer_gn...,50.0
239,9,hetero_transformerconv,0.771768,0.142709,0.025959,0.773855,0.195686,0.070686,14,transformerconv,...,False,/data/liangz2/openi/multi_kg/kg_transformer_gn...,99,0.828717,128,1,2,val_tuned_f1,/data/liangz2/openi/multi_kg/kg_transformer_gn...,50.0

## Aggregate Results for Tables

In [9]:
def collect_transformer_gnn_results(output_root: Path) -> pd.DataFrame:
    """Collect completed transformer-GNN rows from final, progress, run-level, or fold-level files."""
    candidate_files = []

    final_path = output_root / "transformer_gnn_10fold_all_results.csv"
    progress_path = output_root / "transformer_gnn_10fold_all_results_progress.csv"
    if final_path.exists():
        candidate_files.append(final_path)
    if progress_path.exists():
        candidate_files.append(progress_path)

    candidate_files.extend(sorted(output_root.glob("*/top_k_*/*_10fold_summary.csv")))
    candidate_files.extend(sorted(output_root.glob("*/top_k_*/*_10fold_summary_progress.csv")))
    candidate_files.extend(sorted(output_root.glob("*/top_k_*/fold*/metrics/*_method_summary.csv")))

    frames = []
    seen = set()
    for path in candidate_files:
        if path in seen or not path.exists():
            continue
        seen.add(path)
        try:
            frame = pd.read_csv(path)
        except Exception as exc:
            print(f"Skipping unreadable file {path}: {exc}")
            continue
        if frame.empty or "fold" not in frame.columns or "threshold_mode" not in frame.columns:
            continue
        if "model_name" not in frame.columns:
            # Infer from path like OUTPUT_ROOT / model_name / top_k_100 / ...
            try:
                frame["model_name"] = path.relative_to(output_root).parts[0]
            except Exception:
                frame["model_name"] = frame.get("method", "unknown")
        if "query_top_k" not in frame.columns:
            top_k = None
            for part in path.parts:
                if part.startswith("top_k_"):
                    top_k = int(part.split("top_k_", 1)[1])
                    break
            frame["query_top_k"] = top_k
        frame["source_file"] = str(path)
        frames.append(frame)

    if not frames:
        raise FileNotFoundError(
            "No transformer-GNN result files found. Run at least one fold in the ablation cell first. "
            f"Searched under: {output_root}"
        )

    results = pd.concat(frames, ignore_index=True)
    # De-duplicate repeated rows collected from both progress and final files.
    key_cols = [c for c in ["model_name", "query_top_k", "fold", "threshold_mode"] if c in results.columns]
    if key_cols:
        results = results.sort_values("source_file").drop_duplicates(subset=key_cols, keep="last")
    return results.reset_index(drop=True)


results = collect_transformer_gnn_results(OUTPUT_ROOT)
all_results_path = OUTPUT_ROOT / "transformer_gnn_10fold_all_results_collected.csv"
results.to_csv(all_results_path, index=False)
print("Collected rows:", len(results))
print("Saved collected long table:", all_results_path)

metric_cols = [
    "disease_macro_auroc", "disease_macro_auprc", "disease_macro_f1",
    "all_macro_auroc", "all_macro_auprc", "all_macro_f1",
]
missing_metrics = [col for col in metric_cols if col not in results.columns]
if missing_metrics:
    raise RuntimeError(f"Missing metric columns in collected results: {missing_metrics}")

summary_rows = []
for (model_name, query_top_k, threshold_mode), group in results.groupby(["model_name", "query_top_k", "threshold_mode"], sort=True):
    row = {
        "model_name": model_name,
        "method": group["method"].iloc[0] if "method" in group.columns else f"hetero_{model_name}",
        "query_top_k": int(query_top_k),
        "threshold_mode": threshold_mode,
        "n_folds": int(group["fold"].nunique()),
        "completed_folds": ",".join(str(int(x)) for x in sorted(group["fold"].dropna().unique())),
        "include_has_finding_in_message_passing": bool(group["include_has_finding_in_message_passing"].iloc[0]) if "include_has_finding_in_message_passing" in group.columns else False,
    }
    for metric in metric_cols:
        row[f"{metric}_mean"] = group[metric].mean()
        row[f"{metric}_std"] = group[metric].std(ddof=1)
    summary_rows.append(row)

aggregate = pd.DataFrame(summary_rows)
aggregate_path = OUTPUT_ROOT / "transformer_gnn_10fold_aggregate_summary.csv"
aggregate.to_csv(aggregate_path, index=False)
print("Saved aggregate summary:", aggregate_path)
display(aggregate.sort_values(["threshold_mode", "disease_macro_auroc_mean"], ascending=[True, False]))

Collected rows: 240
Saved collected long table: /data/liangz2/openi/multi_kg/kg_transformer_gnn_10fold/transformer_gnn_10fold_all_results_collected.csv
Saved aggregate summary: /data/liangz2/openi/multi_kg/kg_transformer_gnn_10fold/transformer_gnn_10fold_aggregate_summary.csv

,model_name,method,query_top_k,threshold_mode,n_folds,completed_folds,include_has_finding_in_message_passing,disease_macro_auroc_mean,disease_macro_auroc_std,disease_macro_auprc_mean,disease_macro_auprc_std,disease_macro_f1_mean,disease_macro_f1_std,all_macro_auroc_mean,all_macro_auroc_std,all_macro_auprc_mean,all_macro_auprc_std,all_macro_f1_mean,all_macro_f1_std
18,transformerconv,hetero_transformerconv,100,fixed_0.5,10,"0,1,2,3,4,5,6,7,8,9",False,0.770436,0.006498,0.144542,0.004812,0.164655,0.032626,0.761113,0.016541,0.188383,0.009998,0.198711,0.040346
22,transformerconv,hetero_transformerconv,500,fixed_0.5,10,"0,1,2,3,4,5,6,7,8,9",False,0.768704,0.007680,0.144791,0.004352,0.148816,0.049969,0.760038,0.024783,0.188929,0.013171,0.183767,0.060397
16,transformerconv,hetero_transformerconv,50,fixed_0.5,10,"0,1,2,3,4,5,6,7,8,9",False,0.767784,0.007786,0.144768,0.004575,0.119084,0.075968,0.760067,0.016531,0.187605,0.008122,0.157347,0.086729
20,transformerconv,hetero_transformerconv,200,fixed_0.5,10,"0,1,2,3,4,5,6,7,8,9",False,0.766991,0.009821,0.143559,0.006734,0.125617,0.068586,0.757595,0.019068,0.186682,0.011385,0.156708,0.080743
12,hgtconv,hetero_hgtconv,200,fixed_0.5,10,"0,1,2,3,4,5,6,7,8,9",False,0.753658,0.017604,0.138588,0.010191,0.041748,0.056990,0.738013,0.028826,0.177262,0.016989,0.086959,0.058923
10,hgtconv,hetero_hgtconv,100,fixed_0.5,10,"0,1,2,3,4,5,6,7,8,9",False,0.752076,0.016242,0.130203,0.011412,0.053095,0.054758,0.739599,0.020814,0.170634,0.013394,0.087663,0.061102
8,hgtconv,hetero_hgtconv,50,fixed_0.5,10,"0,1,2,3,4,5,6,7,8,9",False,0.749005,0.016486,0.135980,0.011523,0.050116,0.050804,0.730742,0.016132,0.172279,0.013718,0.092385,0.060804
4,hanconv,hetero_hanconv,200,fixed_0.5,10,"0,1,2,3,4,5,6,7,8,9",False,0.740459,0.016762,0.145870,0.005947,0.058952,0.070584,0.746079,0.015654,0.198245,0.005693,0.111229,0.065542
0,hanconv,hetero_hanconv,50,fixed_0.5,10,"0,1,2,3,4,5,6,7,8,9",False,0.729423,0.050156,0.141749,0.021500,0.066345,0.057473,0.732616,0.057102,0.192146,0.027475,0.118095,0.053372
6,hanconv,hetero_hanconv,500,fixed_0.5,10,"0,1,2,3,4,5,6,7,8,9",False,0.716492,0.078828,0.136100,0.030896,0.014210,0.031644,0.721983,0.078035,0.187963,0.032066,0.064061,0.036710
2,hanconv,hetero_hanconv,100,fixed_0.5,10,"0,1,2,3,4,5,6,7,8,9",False,0.714464,0.083553,0.134776,0.033702,0.036575,0.051859,0.715869,0.090567,0.183608,0.040542,0.084804,0.055357
14,hgtconv,hetero_hgtconv,500,fixed_0.5,10,"0,1,2,3,4,5,6,7,8,9",False,0.711356,0.067012,0.117733,0.027855,0.045075,0.053252,0.703188,0.069215,0.160825,0.029271,0.085084,0.060337
19,transformerconv,hetero_transformerconv,100,val_tuned_f1,10,"0,1,2,3,4,5,6,7,8,9",False,0.770436,0.006498,0.144542,0.004812,0.115119,0.078225,0.761113,0.016541,0.188383,0.009998,0.163842,0.071713
23,transformerconv,hetero_transformerconv,500,val_tuned_f1,10,"0,1,2,3,4,5,6,7,8,9",False,0.768704,0.007680,0.144791,0.004352,0.077493,0.046760,0.760038,0.024783,0.188929,0.013171,0.129077,0.044085
17,transformerconv,hetero_transformerconv,50,val_tuned_f1,10,"0,1,2,3,4,5,6,7,8,9",False,0.767784,0.007786,0.144768,0.004575,0.077472,0.062559,0.760067,0.016531,0.187605,0.008122,0.127762,0.056838
21,transformerconv,hetero_transformerconv,200,val_tuned_f1,10,"0,1,2,3,4,5,6,7,8,9",False,0.766991,0.009821,0.143559,0.006734,0.067882,0.034920,0.757595,0.019068,0.186682,0.011385,0.114940,0.044232
13,hgtconv,hetero_hgtconv,200,val_tuned_f1,10,"0,1,2,3,4,5,6,7,8,9",False,0.753658,0.017604,0.138588,0.010191,0.029549,0.023720,0.738013,0.028826,0.177262,0.016989,0.075381,0.019374
11,hgtconv,hetero_hgtconv,100,val_tuned_f1,10,"0,1,2,3,4,5,6,7,8,9",False,0.752076,0.016242,0.130203,0.011412,0.017176,0.025150,0.739599,0.020814,0.170634,0.013394,0.066861,0.028737
9,hgtconv,hetero_hgtconv,50,val_tuned_f1,10,"0,1,2,3,4,5,6,7,8,9",False,0.749005,0.016486,0.135980,0.011523,0.026347,0.047954,0.730742,0.016132,0.172279,0.013718,0.067989,0.056161
5,hanconv,hetero_hanconv,200,val_tuned_f1,10,"0,1,2,3,4,5,6,7,8,9",False,0.740459,0.016762,0.145870,0.005947,0.027526,0.040843,0.746079,0.015654,0.198245,0.005693,0.082049,0.037925
1,hanconv,hetero_hanconv,50,val_tuned_f1,10,"0,1,2,3,4,5,6,7,8,9",False,0.729423,0.050156,0.141749,0.021500,0.026536,0.029991,0.732616,0.057102,0.192146,0.027475,0.081129,0.027853
7,hanconv,hetero_hanconv,500,val_tuned_f1,10,"0,1,2,3,4,5,6,7,8,9",False,0.716492,0.078828,0.136100,0.030896,0.009817,0.017238,0.721983,0.078035,0.187963,0.032066,0.065697,0.015997
3,hanconv,hetero_hanconv,100,val_tuned_f1,10,"0,1,2,3,4,5,6,7,8,9",False,0.714464,0.083553,0.134776,0.033702,0.012395,0.015246,0.715869,0.090567,0.183608,0.040542,0.067998,0.014160
15,hgtconv,hetero_hgtconv,500,val_tuned_f1,10,"0,1,2,3,4,5,6,7,8,9",False,0.711356,0.067012,0.117733,0.027855,0.010854,0.012150,0.703188,0.069215,0.160825,0.029271,0.051545,0.032287

## Notes

Use `fixed_0.5` as the primary threshold-free comparison companion to AUROC/AUPRC, and use `val_tuned_f1` only to report threshold-calibrated F1. The ranking metrics AUROC and AUPRC do not change when thresholds are tuned.

For paper tables, compare this notebook against:

- BiomedCLIP + MLP.
- FAISS retrieval only.
- BiomedCLIP + FAISS fusion.
- BiomedCLIP + FAISS + RoentGen diffusion augmentation.
- Hetero GraphSAGE.
- Transformer-GNN variants in this notebook.