# Retrieval Performance Evaluation: BiomedCLIP, BiomedCLIP+MLP, KG, and GNN

This notebook evaluates retrieval performance only. It does not generate reports.

Retrieval methods:

- `biomedclip_image_embedding`: BiomedCLIP image embedding retrieval.
- `biomedclip_zero_shot_label_vector`: BiomedCLIP zero-shot 14-label probability vector retrieval.
- `biomedclip_mlp_label_vector`: supervised BiomedCLIP+MLP 14-logit label-space retrieval.
- `kg_radgraph_entity_oracle`: KG entity retrieval using RadGraph observation/anatomy entities. This is an oracle semantic upper bound because query report entities are used.
- `gnn_*_label_vector`: GNN/KG prediction-vector retrieval if saved GNN prediction files are available.

Top-k values are `1, 5, 10, 50, 100, 200`. Metrics include MRR@k, Precision@k, Recall@k, mAP@k, nDCG@k, and Hit@k. nDCG@k is especially important here because it penalizes relevant cases placed lower in the retrieved list, which matches the clinical goal of prioritizing diagnostically useful evidence near the top of the context.

## 0. Optional Dependencies

In [ ]:
# Run on the cloud only if dependencies are missing.
# ! pip install -U open_clip_torch transformers faiss-cpu scikit-learn scipy nltk rouge-score bert-score pycocoevalcap radgraph

## 1. Imports and Configuration

In [1]:
import json
import math
import os
import random
import re
from collections import defaultdict
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Set, Tuple

import numpy as np
import pandas as pd
from PIL import Image, ImageFile
from tqdm.auto import tqdm

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset

from sklearn.metrics import average_precision_score, f1_score, roc_auc_score
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.feature_extraction.text import TfidfTransformer

try:
    import faiss
except ImportError as exc:
    raise ImportError("Install faiss-cpu or faiss-gpu before running retrieval evaluation.") from exc

try:
    from scipy import sparse, stats
except Exception:
    sparse = None
    stats = None

ImageFile.LOAD_TRUNCATED_IMAGES = True

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

DEVICE = "cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu"
DTYPE = torch.bfloat16 if DEVICE == "cuda" else torch.float32

DATA_ROOT = Path("/data/liangz2/openi/multi_kg") if Path("/data/liangz2/openi/multi_kg").exists() else Path.cwd()
OUTPUT_ROOT = DATA_ROOT / "retrieval_report_generation_eval"
EMBEDDING_DIR = OUTPUT_ROOT / "embeddings"
RETRIEVAL_RESULT_DIR = OUTPUT_ROOT / "retrieval_results"
for p in [OUTPUT_ROOT, EMBEDDING_DIR, RETRIEVAL_RESULT_DIR]:
    p.mkdir(parents=True, exist_ok=True)

SPLIT_CSV_CANDIDATES = [
    DATA_ROOT / "multi_kg_image_json_10fold.csv",
    Path("/data/liangz2/openi/inverse_diff/multi_kg_image_json_10fold.csv"),
    Path("/Users/liangz2/Documents/inverse_diffusion/multi_kg_image_json_10fold.csv"),
]

PREBUILT_FAISS_ROOTS = [
    Path("/data/liangz2/openi/inverse_diff/faiss_biomedclip"),
    DATA_ROOT / "faiss_biomedclip",
]
PREBUILT_INDEX_NAME = "multi_kg_train_test_biomedclip"

BIOMEDCLIP_BASELINE_ROOT = DATA_ROOT / "biomedclip_10fold_baselines"
KG_GRAPH_TABLE_DIR = DATA_ROOT / "kg_graph_tables"
KG_10FOLD_DIR = DATA_ROOT / "kg_10fold"
NON_TRANSFORMER_GNN_ROOT = DATA_ROOT / "kg_non_transformer_gnn_10fold"
TRANSFORMER_GNN_ROOT = DATA_ROOT / "kg_transformer_gnn_10fold"

BIOMEDCLIP_REPO = "hf-hub:microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224"

FOLD_INDICES = list(range(10))
K_VALUES = [1, 5, 10, 50, 100, 200]
MAX_K = max(K_VALUES)
MAX_FOLDS = None
MAX_TEST_QUERIES = None
SKIP_COMPLETED_RETRIEVAL = True

# GNN prediction-vector retrieval: query vector is saved GNN probabilities/logits;
# gallery vector is the observed training label vector. Change these to compare other GNN models.
GNN_RETRIEVAL_EXPERIMENTS = [
    {"family": "non_transformer_gnn", "model_name": "graphsage", "top_k": 500},
    {"family": "transformer_gnn", "model_name": "transformerconv", "top_k": 100},
]

BATCH_SIZE = 64
TEXT_BATCH_SIZE = 128
NUM_WORKERS = 0

print("DATA_ROOT:", DATA_ROOT)
print("OUTPUT_ROOT:", OUTPUT_ROOT)
print("DEVICE:", DEVICE)

DATA_ROOT: /data/liangz2/openi/multi_kg
OUTPUT_ROOT: /data/liangz2/openi/multi_kg/retrieval_report_generation_eval
DEVICE: cuda

## 2. Label Schema and Split Table

In [2]:
CHEXPERT_LABELS = (
    "enlarged cardiomediastinum", "cardiomegaly", "lung opacity", "lung lesion", "edema",
    "consolidation", "pneumonia", "atelectasis", "pneumothorax",
    "pleural effusion", "pleural other", "fracture", "support devices",
)
SCORING_LABELS = ("normal",) + CHEXPERT_LABELS
TARGET_COLUMNS = ["y_" + label.replace(" ", "_") for label in SCORING_LABELS]

LABEL_ALIASES = {
    "enlarged cardiomediastinum": "enlarged cardiomediastinum",
    "cardiomediastinum": "enlarged cardiomediastinum",
    "cardiomegaly": "cardiomegaly",
    "lung opacity": "lung opacity",
    "opacity": "lung opacity",
    "lung lesion": "lung lesion",
    "lesion": "lung lesion",
    "edema": "edema",
    "pulmonary edema": "edema",
    "consolidation": "consolidation",
    "pneumonia": "pneumonia",
    "atelectasis": "atelectasis",
    "pneumothorax": "pneumothorax",
    "pleural effusion": "pleural effusion",
    "effusion": "pleural effusion",
    "pleural other": "pleural other",
    "fracture": "fracture",
    "support devices": "support devices",
    "support device": "support devices",
}

def find_first_existing(paths: Sequence[Path]) -> Optional[Path]:
    return next((p for p in paths if p.exists()), None)

def resolve_existing_path(path_value, suffix: Optional[str] = None) -> str:
    if path_value is None or str(path_value).lower() == "nan":
        return ""
    path = Path(str(path_value))
    if suffix:
        path = path.with_suffix(suffix)
    candidates = [path]
    text = str(path)
    replacements = [
        ("/vf/users/liangz2/openi/multi_kg", "/data/liangz2/openi/multi_kg"),
        ("/data/liangz2/openi/multi_kg", "/vf/users/liangz2/openi/multi_kg"),
    ]
    for src, dst in replacements:
        if text.startswith(src):
            candidates.append(Path(text.replace(src, dst, 1)))
    for candidate in candidates:
        if candidate.exists():
            return str(candidate)
    return str(path)

def parse_label_list(value) -> List[str]:
    if value is None or (isinstance(value, float) and math.isnan(value)):
        return []
    if isinstance(value, list):
        raw = value
    else:
        text = str(value).strip()
        if not text or text.lower() == "nan":
            return []
        try:
            raw = json.loads(text)
        except Exception:
            raw = re.split(r"[,;|]", text)
    labels = []
    for item in raw:
        key = re.sub(r"\\s+", " ", str(item).strip().lower())
        mapped = LABEL_ALIASES.get(key)
        if mapped and mapped not in labels:
            labels.append(mapped)
    return labels

def load_json_payload(path_value) -> Dict:
    path_text = resolve_existing_path(path_value)
    if not path_text:
        return {}
    path = Path(path_text)
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text())
    except Exception:
        return {}

def report_text_from_payload(payload: Dict) -> str:
    parts = []
    for field in ("INDICATION", "FINDINGS", "IMPRESSION"):
        text = str(payload.get(field, "") or "").strip()
        if text:
            parts.append(f"{field.title()}: {text}")
    if parts:
        return "\\n".join(parts)
    for field in ("Original_Caption", "Caption", "report", "description"):
        text = str(payload.get(field, "") or "").strip()
        if text:
            return text
    return ""

def ensure_targets(frame: pd.DataFrame) -> pd.DataFrame:
    frame = frame.copy()
    for col in TARGET_COLUMNS:
        if col not in frame.columns:
            frame[col] = 0
    if "labels_normalized" not in frame.columns:
        frame["labels_normalized"] = "[]"
    for i, row in frame.iterrows():
        if all(int(row.get(col, 0) or 0) == 0 for col in TARGET_COLUMNS):
            labels = parse_label_list(row.get("labels_normalized", "[]"))
            is_normal = str(row.get("normal", "")).strip().lower() == "yes" or not labels
            if is_normal:
                frame.at[i, "y_normal"] = 1
            for label in labels:
                col = "y_" + label.replace(" ", "_")
                if col in frame.columns:
                    frame.at[i, col] = 1
    for col in TARGET_COLUMNS:
        frame[col] = frame[col].fillna(0).astype(int)
    return frame

def load_split_table() -> pd.DataFrame:
    split_csv = find_first_existing(SPLIT_CSV_CANDIDATES)
    if split_csv is None:
        raise FileNotFoundError(f"Could not find split CSV. Checked: {SPLIT_CSV_CANDIDATES}")
    frame = pd.read_csv(split_csv).copy()
    frame["row_id"] = np.arange(len(frame), dtype=np.int64)
    frame["study_id"] = frame.get("study_id", frame["image_path"].map(lambda p: Path(str(p)).stem)).astype(str)
    frame["image_path"] = frame["image_path"].map(resolve_existing_path)
    if "json_path" not in frame.columns:
        frame["json_path"] = frame["image_path"].map(lambda p: str(Path(str(p)).with_suffix(".json")))
    frame["json_path"] = frame["json_path"].map(resolve_existing_path)
    frame["image_basename"] = frame["image_path"].map(lambda p: Path(str(p)).name)
    frame = ensure_targets(frame)
    if "report_text" not in frame.columns:
        reports = []
        for p in tqdm(frame["json_path"], desc="Load reference report text"):
            reports.append(report_text_from_payload(load_json_payload(p)))
        frame["report_text"] = reports
    return frame

split_df = load_split_table()
y_all = split_df[TARGET_COLUMNS].to_numpy(dtype=np.int8)
print("split rows", len(split_df))
display(split_df[["row_id", "study_id", "image_path", "labels_normalized"]].head())

Load reference report text:   0%|          | 0/44100 [00:00<?, ?it/s]

split rows 44100

,row_id,study_id,image_path,labels_normalized
0,0,50003542,/vf/users/liangz2/openi/multi_kg/train/5000354...,[]
1,1,50003755,/vf/users/liangz2/openi/multi_kg/train/5000375...,[]
2,2,50008255,/vf/users/liangz2/openi/multi_kg/train/5000825...,[]
3,3,50010166,/vf/users/liangz2/openi/multi_kg/train/5001016...,"[""lung opacity"", ""pneumonia""]"
4,4,50010229,/vf/users/liangz2/openi/multi_kg/train/5001022...,"[""atelectasis"", ""cardiomegaly"", ""consolidation..."

## 3. BiomedCLIP Image Embeddings and Zero-Shot Label Vectors

In [3]:
biomedclip_model = None
biomedclip_preprocess = None
biomedclip_tokenizer = None

def l2_normalize_np(x: np.ndarray, eps: float = 1e-12) -> np.ndarray:
    x = np.asarray(x, dtype=np.float32)
    return (x / np.maximum(np.linalg.norm(x, axis=1, keepdims=True), eps)).astype("float32")

def get_biomedclip_model():
    global biomedclip_model, biomedclip_preprocess, biomedclip_tokenizer
    if biomedclip_model is None:
        from open_clip import create_model_from_pretrained, get_tokenizer
        model, preprocess = create_model_from_pretrained(BIOMEDCLIP_REPO)
        tokenizer = get_tokenizer(BIOMEDCLIP_REPO)
        model = model.to(DEVICE).eval()
        for p in model.parameters():
            p.requires_grad_(False)
        biomedclip_model, biomedclip_preprocess, biomedclip_tokenizer = model, preprocess, tokenizer
    return biomedclip_model, biomedclip_preprocess, biomedclip_tokenizer

class ImagePathDataset(Dataset):
    def __init__(self, frame: pd.DataFrame, preprocess):
        self.frame = frame.reset_index(drop=True)
        self.preprocess = preprocess

    def __len__(self):
        return len(self.frame)

    def __getitem__(self, idx):
        image_path = self.frame.loc[idx, "image_path"]
        with Image.open(image_path) as image:
            return self.preprocess(image.convert("RGB")), idx

@torch.inference_mode()
def encode_images(frame: pd.DataFrame) -> np.ndarray:
    model, preprocess, _ = get_biomedclip_model()
    loader = DataLoader(ImagePathDataset(frame, preprocess), batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS)
    chunks = []
    for images, _ in tqdm(loader, desc="BiomedCLIP image embeddings"):
        images = images.to(DEVICE)
        with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=(DEVICE == "cuda")):
            feats = model.encode_image(images)
        chunks.append(F.normalize(feats.float(), dim=-1).cpu().numpy().astype("float32"))
    return np.concatenate(chunks, axis=0)

@torch.inference_mode()
def encode_texts(texts: Sequence[str]) -> np.ndarray:
    model, _, tokenizer = get_biomedclip_model()
    chunks = []
    for start in tqdm(range(0, len(texts), TEXT_BATCH_SIZE), desc="BiomedCLIP text embeddings"):
        tokens = tokenizer(list(texts[start:start + TEXT_BATCH_SIZE]), context_length=256).to(DEVICE)
        with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=(DEVICE == "cuda")):
            feats = model.encode_text(tokens)
        chunks.append(F.normalize(feats.float(), dim=-1).cpu().numpy().astype("float32"))
    return np.concatenate(chunks, axis=0)

def cache_matches(meta_path: Path, frame: pd.DataFrame) -> bool:
    if not meta_path.exists():
        return False
    try:
        meta = pd.read_csv(meta_path)
    except Exception:
        return False
    return len(meta) == len(frame) and "row_id" in meta.columns and meta["row_id"].astype(int).tolist() == frame["row_id"].astype(int).tolist()

def load_prebuilt_image_embeddings(frame: pd.DataFrame) -> Optional[np.ndarray]:
    for root in PREBUILT_FAISS_ROOTS:
        emb_path = root / f"{PREBUILT_INDEX_NAME}_embeddings.npy"
        meta_path = root / f"{PREBUILT_INDEX_NAME}_metadata.csv"
        if not emb_path.exists() or not meta_path.exists():
            continue
        meta = pd.read_csv(meta_path)
        emb = np.load(emb_path).astype("float32")
        if "faiss_id" not in meta.columns:
            meta["faiss_id"] = np.arange(len(meta), dtype=int)
        if "image_basename" not in meta.columns:
            meta["image_basename"] = meta["image_path"].map(lambda p: Path(str(p)).name)
        meta["study_id"] = meta["study_id"].astype(str)
        lookup = meta.drop_duplicates(["study_id", "image_basename"]).set_index(["study_id", "image_basename"])["faiss_id"].to_dict()
        ids = []
        for _, row in frame.iterrows():
            ids.append(lookup.get((str(row["study_id"]), str(row["image_basename"])), -1))
        ids = np.asarray(ids, dtype=int)
        if np.all(ids >= 0):
            print("Loaded prebuilt image embeddings:", emb_path)
            return l2_normalize_np(emb[ids])
    return None

def get_image_embeddings(frame: pd.DataFrame) -> np.ndarray:
    emb_path = EMBEDDING_DIR / "biomedclip_image_embeddings.npy"
    meta_path = EMBEDDING_DIR / "biomedclip_image_embedding_metadata.csv"
    if emb_path.exists() and cache_matches(meta_path, frame):
        return np.load(emb_path).astype("float32")
    emb = load_prebuilt_image_embeddings(frame)
    if emb is None:
        emb = encode_images(frame)
    np.save(emb_path, emb.astype("float32"))
    frame[["row_id", "study_id", "image_basename", "image_path"]].to_csv(meta_path, index=False)
    return emb.astype("float32")

def positive_prompts(label: str) -> List[str]:
    if label == "normal":
        return ["a normal chest x-ray.", "a chest radiograph with no acute cardiopulmonary abnormality."]
    return [f"a chest x-ray showing {label}.", f"a chest radiograph with evidence of {label}."]

def negative_prompts(label: str) -> List[str]:
    if label == "normal":
        return ["an abnormal chest x-ray.", "a chest radiograph with cardiopulmonary abnormality."]
    return [f"a chest x-ray without {label}.", f"no radiographic evidence of {label}."]

def build_zero_shot_vectors(image_emb: np.ndarray) -> np.ndarray:
    cache = EMBEDDING_DIR / "biomedclip_zero_shot_label_probs.npy"
    if cache.exists():
        arr = np.load(cache).astype("float32")
        if arr.shape == (len(image_emb), len(SCORING_LABELS)):
            return arr
    pos_text, neg_text = [], []
    for label in SCORING_LABELS:
        pos_text.append(l2_normalize_np(encode_texts(positive_prompts(label))).mean(axis=0))
        neg_text.append(l2_normalize_np(encode_texts(negative_prompts(label))).mean(axis=0))
    pos_text = l2_normalize_np(np.stack(pos_text))
    neg_text = l2_normalize_np(np.stack(neg_text))
    model, _, _ = get_biomedclip_model()
    scale = float(model.logit_scale.exp().detach().cpu()) if hasattr(model, "logit_scale") else 100.0
    pos_logits = scale * (image_emb @ pos_text.T)
    neg_logits = scale * (image_emb @ neg_text.T)
    pair = np.stack([neg_logits, pos_logits], axis=-1)
    pair = pair - pair.max(axis=-1, keepdims=True)
    exp_pair = np.exp(pair)
    probs = exp_pair[..., 1] / exp_pair.sum(axis=-1)
    np.save(cache, probs.astype("float32"))
    return probs.astype("float32")

image_embeddings = get_image_embeddings(split_df)
zero_shot_vectors = build_zero_shot_vectors(image_embeddings)
print("image_embeddings", image_embeddings.shape, "zero_shot_vectors", zero_shot_vectors.shape)

image_embeddings (44100, 512) zero_shot_vectors (44100, 14)

## 4. BiomedCLIP + MLP Label Vectors

In [4]:
class BiomedClipMLPHead(nn.Module):
    def __init__(self, input_dim: int, num_outputs: int, hidden_dims: Sequence[int] = (512,), dropout: float = 0.20):
        super().__init__()
        layers = []
        prev = input_dim
        for hidden in hidden_dims:
            layers.extend([nn.Linear(prev, int(hidden)), nn.ReLU(inplace=True), nn.Dropout(dropout)])
            prev = int(hidden)
        layers.append(nn.Linear(prev, num_outputs))
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x.float())

def load_mlp_head_for_fold(fold: int, input_dim: int) -> Optional[nn.Module]:
    model_path = BIOMEDCLIP_BASELINE_ROOT / f"fold{fold}" / "models" / f"biomedclip_mlp_14_fold{fold}_seed42.pt"
    if not model_path.exists():
        print("Missing MLP checkpoint:", model_path)
        return None
    try:
        ckpt = torch.load(model_path, map_location=DEVICE, weights_only=False)
    except TypeError:
        ckpt = torch.load(model_path, map_location=DEVICE)
    hidden_dims = tuple(ckpt.get("hidden_dims", [512]))
    dropout = float(ckpt.get("dropout", 0.20))
    head = BiomedClipMLPHead(input_dim, len(SCORING_LABELS), hidden_dims=hidden_dims, dropout=dropout).to(DEVICE)
    state = ckpt.get("state_dict", ckpt)
    head.load_state_dict(state)
    head.eval()
    return head

@torch.inference_mode()
def predict_mlp_vectors(head: nn.Module, emb: np.ndarray, batch_size: int = 8192, output: str = "logits") -> np.ndarray:
    chunks = []
    for start in range(0, len(emb), batch_size):
        x = torch.from_numpy(emb[start:start + batch_size].astype("float32")).to(DEVICE)
        logits = head(x).detach().cpu().numpy().astype("float32")
        chunks.append(logits)
    logits = np.concatenate(chunks, axis=0) if chunks else np.empty((0, len(SCORING_LABELS)), dtype="float32")
    if output == "probs":
        return (1.0 / (1.0 + np.exp(-logits))).astype("float32")
    return logits.astype("float32")

def fold_mlp_vectors(fold: int, row_ids: np.ndarray) -> Optional[np.ndarray]:
    cache = EMBEDDING_DIR / f"fold{fold}_biomedclip_mlp_logits.npy"
    meta = EMBEDDING_DIR / f"fold{fold}_biomedclip_mlp_logits_meta.csv"
    if cache.exists() and meta.exists():
        meta_df = pd.read_csv(meta)
        if meta_df["row_id"].astype(int).tolist() == row_ids.astype(int).tolist():
            return np.load(cache).astype("float32")
    head = load_mlp_head_for_fold(fold, image_embeddings.shape[1])
    if head is None:
        return None
    logits = predict_mlp_vectors(head, image_embeddings[row_ids], output="logits")
    np.save(cache, logits.astype("float32"))
    pd.DataFrame({"row_id": row_ids.astype(int)}).to_csv(meta, index=False)
    return logits

## 5. KG Entity Sets from RadGraph

In [5]:
def load_kg_entity_sets(frame: pd.DataFrame) -> Dict[str, Set[str]]:
    edge_path = KG_GRAPH_TABLE_DIR / "kg_edges_radgraph_and_labels.csv"
    if not edge_path.exists():
        print("KG RadGraph edge table not found:", edge_path)
        return {str(sid): set() for sid in frame["study_id"].astype(str)}
    edges = pd.read_csv(edge_path)
    keep = edges["edge_type"].isin(["mentions", "uncertain_mentions", "located_at", "suggestive_of", "modify"])
    edges = edges[keep].copy()
    study_entities: Dict[str, Set[str]] = defaultdict(set)
    for _, row in edges.iterrows():
        sid = str(row.get("study_id", ""))
        etype = str(row.get("edge_type", ""))
        if not sid:
            continue
        if etype in {"mentions", "uncertain_mentions"}:
            dst = str(row.get("dst", ""))
            if dst:
                study_entities[sid].add(dst)
        elif etype in {"located_at", "suggestive_of", "modify"}:
            src, dst = str(row.get("src", "")), str(row.get("dst", ""))
            if src:
                study_entities[sid].add(src)
            if dst:
                study_entities[sid].add(dst)
    return {str(sid): study_entities.get(str(sid), set()) for sid in frame["study_id"].astype(str)}

kg_entity_sets_by_study = load_kg_entity_sets(split_df)
split_df["kg_entity_count"] = split_df["study_id"].astype(str).map(lambda sid: len(kg_entity_sets_by_study.get(sid, set())))
print("KG entity coverage:", float((split_df["kg_entity_count"] > 0).mean()))
display(split_df[["study_id", "kg_entity_count"]].head())

def entity_sets_for_rows(row_ids: np.ndarray) -> List[Set[str]]:
    return [kg_entity_sets_by_study.get(str(split_df.iloc[int(r)]["study_id"]), set()) for r in row_ids]

def build_entity_sparse_matrix(entity_sets: Sequence[Set[str]]):
    mlb = MultiLabelBinarizer(sparse_output=True)
    binary = mlb.fit_transform([sorted(s) for s in entity_sets])
    tfidf = TfidfTransformer(norm="l2", use_idf=True)
    matrix = tfidf.fit_transform(binary)
    return matrix, mlb, tfidf

def transform_entity_sparse_matrix(entity_sets: Sequence[Set[str]], mlb: MultiLabelBinarizer, tfidf: TfidfTransformer):
    binary = mlb.transform([sorted(s) for s in entity_sets])
    return tfidf.transform(binary)

KG entity coverage: 0.9777551020408163

   study_id  kg_entity_count
0  50003542                8
1  50003755                2
2  50008255                9
3  50010166               20
4  50010229               13

## 6. Retrieval Metrics

In [6]:
def fold_row_ids(fold: int) -> Tuple[np.ndarray, np.ndarray]:
    col = f"fold_{fold}"
    values = split_df[col].astype(str).str.lower()
    train_ids = np.flatnonzero(values.eq("train").to_numpy()).astype(np.int64)
    test_ids = np.flatnonzero(values.eq("test").to_numpy()).astype(np.int64)
    if MAX_TEST_QUERIES is not None:
        test_ids = test_ids[: int(MAX_TEST_QUERIES)]
    return train_ids, test_ids

def dense_search(train_vec: np.ndarray, test_vec: np.ndarray, k: int = MAX_K) -> Tuple[np.ndarray, np.ndarray]:
    train_vec = l2_normalize_np(train_vec.astype("float32"))
    test_vec = l2_normalize_np(test_vec.astype("float32"))
    index = faiss.IndexFlatIP(train_vec.shape[1])
    index.add(np.ascontiguousarray(train_vec))
    sims, idx = index.search(np.ascontiguousarray(test_vec), min(k, len(train_vec)))
    return sims.astype("float32"), idx.astype(np.int64)

def sparse_search(train_matrix, test_matrix, k: int = MAX_K) -> Tuple[np.ndarray, np.ndarray]:
    nn = NearestNeighbors(n_neighbors=min(k, train_matrix.shape[0]), metric="cosine", algorithm="brute")
    nn.fit(train_matrix)
    distances, idx = nn.kneighbors(test_matrix, return_distance=True)
    sims = 1.0 - distances
    return sims.astype("float32"), idx.astype(np.int64)

def relevant_indices_for_query(q_y: np.ndarray, train_y: np.ndarray, q_entities: Set[str], train_entity_sets: List[Set[str]], relevance: str) -> Set[int]:
    relevant: Set[int] = set()
    if relevance in {"label", "combined"}:
        q_disease = np.flatnonzero(q_y[1:] > 0) + 1
        if len(q_disease):
            hits = np.flatnonzero(train_y[:, q_disease].sum(axis=1) > 0)
        else:
            hits = np.flatnonzero(train_y[:, 0] > 0)
        relevant.update(map(int, hits))
    if relevance in {"entity", "combined"} and q_entities:
        for i, ents in enumerate(train_entity_sets):
            if q_entities.intersection(ents):
                relevant.add(int(i))
    return relevant

def apk(relevant_flags: np.ndarray, total_relevant: int) -> float:
    if total_relevant <= 0:
        return np.nan
    flags = relevant_flags.astype(bool)
    if flags.sum() == 0:
        return 0.0
    precision = np.cumsum(flags) / np.arange(1, len(flags) + 1)
    return float((precision * flags).sum() / min(total_relevant, len(flags)))

def mrr(relevant_flags: np.ndarray) -> float:
    hits = np.flatnonzero(relevant_flags.astype(bool))
    return 0.0 if len(hits) == 0 else float(1.0 / (hits[0] + 1))

def ndcg(relevant_flags: np.ndarray, total_relevant: int) -> float:
    flags = relevant_flags.astype(float)
    if total_relevant <= 0:
        return np.nan
    discounts = 1.0 / np.log2(np.arange(2, len(flags) + 2))
    dcg = float((flags * discounts).sum())
    ideal_len = min(total_relevant, len(flags))
    ideal = float(discounts[:ideal_len].sum())
    return dcg / ideal if ideal > 0 else np.nan

def evaluate_neighbors(
    train_ids: np.ndarray,
    test_ids: np.ndarray,
    sims: np.ndarray,
    idx: np.ndarray,
    method_name: str,
    fold: int,
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    train_y = y_all[train_ids]
    test_y = y_all[test_ids]
    train_entities = entity_sets_for_rows(train_ids)
    test_entities = entity_sets_for_rows(test_ids)

    summary_rows = []
    query_rows = []
    for relevance in ["label", "entity", "combined"]:
        for k in K_VALUES:
            values = defaultdict(list)
            for qi in range(len(test_ids)):
                nn_idx = idx[qi, :k]
                rel = relevant_indices_for_query(test_y[qi], train_y, test_entities[qi], train_entities, relevance)
                flags = np.array([int(int(j) in rel) for j in nn_idx if int(j) >= 0], dtype=int)
                total_rel = len(rel)
                precision = float(flags.mean()) if len(flags) else np.nan
                recall = float(flags.sum() / total_rel) if total_rel else np.nan
                row = {
                    "fold": fold,
                    "retrieval_method": method_name,
                    "relevance": relevance,
                    "k": int(k),
                    "query_row_id": int(test_ids[qi]),
                    "num_relevant_gallery": int(total_rel),
                    "precision_at_k": precision,
                    "recall_at_k": recall,
                    "ap_at_k": apk(flags, total_rel),
                    "mrr_at_k": mrr(flags),
                    "ndcg_at_k": ndcg(flags, total_rel),
                    "hit_at_k": float(flags.sum() > 0) if len(flags) else np.nan,
                }
                query_rows.append(row)
                for metric in ["precision_at_k", "recall_at_k", "ap_at_k", "mrr_at_k", "ndcg_at_k", "hit_at_k"]:
                    values[metric].append(row[metric])
            summary = {
                "fold": fold,
                "retrieval_method": method_name,
                "relevance": relevance,
                "k": int(k),
                "num_queries": int(len(test_ids)),
            }
            for metric, vals in values.items():
                summary[metric] = float(np.nanmean(vals))
            summary_rows.append(summary)
    return pd.DataFrame(summary_rows), pd.DataFrame(query_rows)

def save_neighbor_audit(method_dir: Path, fold: int, method_name: str, train_ids: np.ndarray, test_ids: np.ndarray, sims: np.ndarray, idx: np.ndarray, max_queries: int = 25):
    rows = []
    for qi in range(min(max_queries, len(test_ids))):
        q = split_df.iloc[int(test_ids[qi])]
        for rank, j in enumerate(idx[qi, :min(MAX_K, idx.shape[1])], start=1):
            if j < 0:
                continue
            n = split_df.iloc[int(train_ids[int(j)])]
            rows.append({
                "fold": fold,
                "retrieval_method": method_name,
                "query_row_id": int(test_ids[qi]),
                "query_study_id": q["study_id"],
                "query_labels": q.get("labels_normalized", ""),
                "rank": rank,
                "similarity": float(sims[qi, rank - 1]),
                "neighbor_row_id": int(train_ids[int(j)]),
                "neighbor_study_id": n["study_id"],
                "neighbor_labels": n.get("labels_normalized", ""),
                "neighbor_report": str(n.get("report_text", ""))[:800],
            })
    pd.DataFrame(rows).to_csv(method_dir / f"{method_name}_fold{fold}_neighbor_audit.csv", index=False)

## 7. Retrieval Vector Builders

In [7]:
def gnn_prediction_path(fold: int, family: str, model_name: str, top_k: int) -> Optional[Path]:
    root = TRANSFORMER_GNN_ROOT if family == "transformer_gnn" else NON_TRANSFORMER_GNN_ROOT
    candidates = [
        root / model_name / f"top_k_{top_k}" / f"fold{fold}" / "predictions" / f"{model_name}_test_predictions.csv",
        root / model_name / f"top_k_{top_k}" / f"fold{fold}" / "predictions" / "graphsage_test_predictions.csv",
    ]
    return next((p for p in candidates if p.exists()), None)

def load_gnn_test_vectors(fold: int, family: str, model_name: str, top_k: int, test_ids: np.ndarray) -> Optional[np.ndarray]:
    path = gnn_prediction_path(fold, family, model_name, top_k)
    if path is None:
        print("Missing GNN prediction file:", family, model_name, top_k, "fold", fold)
        return None
    pred = pd.read_csv(path)
    prob_cols = [f"prob_{label}" for label in SCORING_LABELS]
    if not set(prob_cols).issubset(pred.columns):
        print("GNN prediction file missing probability columns:", path)
        return None
    if "study_id" in pred.columns:
        pred["study_id"] = pred["study_id"].astype(str)
        lookup = pred.drop_duplicates("study_id").set_index("study_id")
        rows = []
        for rid in test_ids:
            sid = str(split_df.iloc[int(rid)]["study_id"])
            if sid not in lookup.index:
                return None
            rows.append(lookup.loc[sid, prob_cols].to_numpy(dtype=np.float32))
        return np.stack(rows).astype("float32")
    return pred[prob_cols].to_numpy(dtype=np.float32)[: len(test_ids)]

def build_retrieval_candidates_for_fold(fold: int) -> List[Dict]:
    train_ids, test_ids = fold_row_ids(fold)
    out = []

    out.append({
        "name": "biomedclip_image_embedding",
        "type": "dense",
        "train_vec": image_embeddings[train_ids],
        "test_vec": image_embeddings[test_ids],
        "description": "BiomedCLIP image embedding cosine retrieval.",
    })
    out.append({
        "name": "biomedclip_zero_shot_label_vector",
        "type": "dense",
        "train_vec": zero_shot_vectors[train_ids],
        "test_vec": zero_shot_vectors[test_ids],
        "description": "BiomedCLIP zero-shot 14-label probability-vector retrieval.",
    })

    all_ids_for_fold = np.concatenate([train_ids, test_ids])
    mlp_all = fold_mlp_vectors(fold, all_ids_for_fold)
    if mlp_all is not None:
        out.append({
            "name": "biomedclip_mlp_label_vector",
            "type": "dense",
            "train_vec": mlp_all[: len(train_ids)],
            "test_vec": mlp_all[len(train_ids):],
            "description": "Supervised BiomedCLIP+MLP 14-logit label-space retrieval.",
        })

    # Oracle KG entity retrieval: uses true report-derived RadGraph entities for query and gallery.
    train_entity_sets = entity_sets_for_rows(train_ids)
    test_entity_sets = entity_sets_for_rows(test_ids)
    if any(len(s) for s in train_entity_sets) and any(len(s) for s in test_entity_sets):
        train_sparse, mlb, tfidf = build_entity_sparse_matrix(train_entity_sets)
        test_sparse = transform_entity_sparse_matrix(test_entity_sets, mlb, tfidf)
        out.append({
            "name": "kg_radgraph_entity_oracle",
            "type": "sparse",
            "train_vec": train_sparse,
            "test_vec": test_sparse,
            "description": "Oracle KG retrieval from RadGraph observation/anatomy entity TF-IDF vectors.",
        })

    # GNN/KG prediction-vector retrieval: query GNN probabilities vs observed training label vectors.
    for exp in GNN_RETRIEVAL_EXPERIMENTS:
        test_gnn = load_gnn_test_vectors(fold, exp["family"], exp["model_name"], int(exp["top_k"]), test_ids)
        if test_gnn is not None:
            out.append({
                "name": f"gnn_{exp['family']}_{exp['model_name']}_topk{int(exp['top_k'])}_label_vector",
                "type": "dense",
                "train_vec": y_all[train_ids].astype("float32"),
                "test_vec": test_gnn.astype("float32"),
                "description": "GNN/KG predicted 14-label vector retrieval against training label vectors.",
            })
    return out

## 8. Run Retrieval Evaluation

In [8]:
all_summary = []
all_query_metrics = []
folds_to_run = FOLD_INDICES[:MAX_FOLDS] if MAX_FOLDS is not None else FOLD_INDICES

for fold in folds_to_run:
    train_ids, test_ids = fold_row_ids(fold)
    candidates = build_retrieval_candidates_for_fold(fold)
    print(f"\\n===== fold={fold} train={len(train_ids)} test={len(test_ids)} methods={len(candidates)} =====")
    for cand in candidates:
        method = cand["name"]
        method_dir = RETRIEVAL_RESULT_DIR / method / f"fold{fold}"
        method_dir.mkdir(parents=True, exist_ok=True)
        complete = method_dir / "FOLD_COMPLETE.json"
        summary_path = method_dir / f"{method}_fold{fold}_retrieval_summary.csv"
        query_path = method_dir / f"{method}_fold{fold}_query_metrics.csv"
        if SKIP_COMPLETED_RETRIEVAL and complete.exists() and summary_path.exists():
            print("skip", method, "fold", fold)
            summary = pd.read_csv(summary_path)
            query_metrics = pd.read_csv(query_path) if query_path.exists() else pd.DataFrame()
        else:
            print("run", method, cand["description"])
            if cand["type"] == "sparse":
                sims, idx = sparse_search(cand["train_vec"], cand["test_vec"], MAX_K)
            else:
                sims, idx = dense_search(cand["train_vec"], cand["test_vec"], MAX_K)
            summary, query_metrics = evaluate_neighbors(train_ids, test_ids, sims, idx, method, fold)
            summary["description"] = cand["description"]
            summary.to_csv(summary_path, index=False)
            query_metrics.to_csv(query_path, index=False)
            save_neighbor_audit(method_dir, fold, method, train_ids, test_ids, sims, idx)
            complete.write_text(json.dumps({"fold": fold, "method": method, "status": "complete"}, indent=2))

        all_summary.append(summary)
        if len(query_metrics):
            all_query_metrics.append(query_metrics)
        pd.concat(all_summary, ignore_index=True).to_csv(OUTPUT_ROOT / "retrieval_10fold_summary_progress.csv", index=False)

retrieval_summary = pd.concat(all_summary, ignore_index=True)
retrieval_summary.to_csv(OUTPUT_ROOT / "retrieval_10fold_summary.csv", index=False)
if all_query_metrics:
    pd.concat(all_query_metrics, ignore_index=True).to_csv(OUTPUT_ROOT / "retrieval_10fold_query_metrics.csv", index=False)
display(retrieval_summary.head())

/data/liangz2/diffuser2/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:1016: UserWarning: unknown class(es) ['anatomy::1', 'anatomy::10th', 'anatomy::adrenal', 'anatomy::anteromedially', 'anatomy::aortopulmonic', 'anatomy::bibasalir', 'anatomy::cartilages', 'anatomy::compliance', 'anatomy::conduction', 'anatomy::currently', 'anatomy::cvc', 'anatomy::deserves', 'anatomy::diameters', 'anatomy::diaphgragm', 'anatomy::ending', 'anatomy::extending', 'anatomy::extrathoracic', 'anatomy::fracutre', 'anatomy::gross', 'anatomy::history', 'anatomy::hypertrophy', 'anatomy::indwelling', 'anatomy::l2 vertebral', 'anatomy::laterall', 'anatomy::look', 'anatomy::lucencies', 'anatomy::minimally', 'anatomy::monitor', 'anatomy::much', 'anatomy::overlap', 'anatomy::ower', 'anatomy::pancoast', 'anatomy::pelves', 'anatomy::periaortic', 'anatomy::pheresis', 'anatomy::pleurex', 'anatomy::reaction', 'anatomy::rhonchi', 'anatomy::sabersheath', 'anatomy::side has', 'anatomy::sided medial', 'anatomy::sided mid', 'anatomy::sided prior', 'anatomy::stenosis', 'anatomy::step', 'anatomy::sterni', 'anatomy::subjacent', 'anatomy::t12 / l1', 'anatomy::t7 that', 'anatomy::then', 'anatomy::tissue structures', 'anatomy::trapezius', 'anatomy::ventricl', 'anatomy::via', 'observation::1cm nodular', 'observation::2 cm wide', 'observation::2 x 2 2 cm', 'observation::4 x 1 5 cm', 'observation::5 cm round', 'observation::6 cm density', 'observation::6 cm left', 'observation::6 cm right', 'observation::6 cm rounded', 'observation::7 cm lung', 'observation::7 cm which', 'observation::7 x 1 3 cm', 'observation::9 x 3 2 cm', 'observation::agent has', 'observation::amorphous', 'observation::appearing left', 'observation::assess though', 'observation::atelecatis', 'observation::bars', 'observation::baseline', 'observation::bleeding', 'observation::blurring', 'observation::braid', 'observation::bronchiolectasis', 'observation::bulbous', 'observation::bulk', 'observation::bulla', 'observation::cath device', 'observation::cath positioning', 'observation::cath projects', 'observation::cath terminates', 'observation::cell', 'observation::choroid', 'observation::chronic heart', 'observation::clearly localized', 'observation::cm dense', 'observation::cm density', 'observation::cm triangular', 'observation::colorectal', 'observation::com', 'observation::comment', 'observation::completely characterized but', 'observation::compressing', 'observation::constructs', 'observation::contiguity', 'observation::contrast', 'observation::contribute', 'observation::convexed', 'observation::cortical', 'observation::cryptococcosis', 'observation::cylindrical', 'observation::defined hazy', 'observation::defined rightupper', 'observation::density material', 'observation::devloping', 'observation::dextroconvex upper', 'observation::dichotomy', 'observation::dimension but', 'observation::diminshed', 'observation::dislocated', 'observation::dislodged', 'observation::domed', 'observation::echinococcal cyst', 'observation::eighth', 'observation::en', 'observation::encapsulated', 'observation::encroaching', 'observation::end however', 'observation::estimated', 'observation::eventuration', 'observation::exceedingly', 'observation::extrapleural', 'observation::favors', 'observation::feature', 'observation::fecalization', 'observation::fiducial seeds', 'observation::flow but', 'observation::fluid level along', 'observation::fluid level consistent', 'observation::fluid level similar', 'observation::full', 'observation::granular', 'observation::had', 'observation::healed old', 'observation::hemangioma', 'observation::hemodynamically', 'observation::hepatectomy', 'observation::history', 'observation::increasing but', 'observation::indeterminate wedge', 'observation::induced lung', 'observation::intervention', 'observation::ipf', 'observation::l', 'observation::lacerations', 'observation::leukemia', 'observation::level one', 'observation::level rising', 'observation::like device', 'observation::like quality', 'observation::line lies', 'observation::linearly', 'observation::longitudinal', 'observation::lymphangiomyomatosis', 'observation::lymphatic', 'observation::major', 'observation::making', 'observation::milldy', 'observation::mimic', 'observation::mm apical', 'observation::mm could', 'observation::mm versus', 'observation::nephropathy', 'observation::node dissection', 'observation::node related', 'observation::nodes can', 'observation::nonsmall cell', 'observation::oapcity', 'observation::opacitie', 'observation::operative small', 'observation::operative volume', 'observation::ossoues', 'observation::osteotomies', 'observation::overlap', 'observation::pacer leads', 'observation::pad which', 'observation::pancreatectomy', 'observation::penetrating', 'observation::pericardiotomy', 'observation::persisient', 'observation::placed left', 'observation::pleurx projects', 'observation::pneumatoceles', 'observation::pooling', 'observation::possibility', 'observation::posterolaterally', 'observation::predominating', 'observation::proportion', 'observation::pseudotumor', 'observation::reactions', 'observation::reflux', 'observation::resorbed', 'observation::restrictive', 'observation::rests', 'observation::reversal', 'observation::runs', 'observation::severe upper', 'observation::signs', 'observation::sized partially', 'observation::slignt', 'observation::smildly', 'observation::solid', 'observation::stabilized', 'observation::ste', 'observation::strands', 'observation::subtly', 'observation::surgical appearance', 'observation::surgical material', 'observation::surgical rib', 'observation::tethering', 'observation::tracheomegaly', 'observation::ulceration', 'observation::variant but', 'observation::ventriculoperitoneal shunt again', 'observation::well evaluated due', 'observation::x 3 cm'] will be ignored
  warnings.warn(

\n===== fold=0 train=39690 test=4410 methods=6 =====
skip biomedclip_image_embedding fold 0
skip biomedclip_zero_shot_label_vector fold 0
skip biomedclip_mlp_label_vector fold 0
skip kg_radgraph_entity_oracle fold 0
skip gnn_non_transformer_gnn_graphsage_topk500_label_vector fold 0
skip gnn_transformer_gnn_transformerconv_topk100_label_vector fold 0

/data/liangz2/diffuser2/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:1016: UserWarning: unknown class(es) ['anatomy::antero', 'anatomy::arteriovenous', 'anatomy::assist', 'anatomy::atriuym', 'anatomy::based lass', 'anatomy::behind', 'anatomy::canthus', 'anatomy::chains', 'anatomy::confirmed', 'anatomy::degeneration', 'anatomy::described', 'anatomy::deviating', 'anatomy::dorsally', 'anatomy::earlier', 'anatomy::esophagogastric', 'anatomy::external', 'anatomy::fall', 'anatomy::form', 'anatomy::four', 'anatomy::heavy', 'anatomy::identified', 'anatomy::inflammatory', 'anatomy::inflated', 'anatomy::infradiaphragmatic', 'anatomy::issues', 'anatomy::juxtacardiac', 'anatomy::known', 'anatomy::leading', 'anatomy::levels along', 'anatomy::luminal', 'anatomy::lung that', 'anatomy::majority', 'anatomy::markedly', 'anatomy::measure', 'anatomy::most sternal', 'anatomy::motility', 'anatomy::old', 'anatomy::pe', 'anatomy::piriform', 'anatomy::plana', 'anatomy::plane', 'anatomy::plexopathy', 'anatomy::popliteal', 'anatomy::posterion', 'anatomy::remained', 'anatomy::screw', 'anatomy::side related', 'anatomy::sided generator', 'anatomy::sided increasing', 'anatomy::sided linear', 'anatomy::sided vascular', 'anatomy::sound', 'anatomy::stentbetter', 'anatomy::style', 'anatomy::surrounding', 'anatomy::t12 vertebral', 'anatomy::tracheo', 'anatomy::transjugular', 'anatomy::tricsupid', 'anatomy::valvuloplasty', 'observation::1 3 5 cm', 'observation::3 x 1 0 cm right', 'observation::4 cm opacity', 'observation::4 x 2 6 cm', 'observation::5 cm diameter within', 'observation::6 cm ill', 'observation::6 mm probably', 'observation::6 x 2 4 cm soft', 'observation::7 x 4 6 c', 'observation::8th', 'observation::9th', 'observation::affected', 'observation::ages', 'observation::alkalosis', 'observation::anchor projects', 'observation::aneurysms', 'observation::appearing but', 'observation::appearing volume', 'observation::articular body', 'observation::asthmatic bronchitis', 'observation::base', 'observation::biopsy changes again', 'observation::cabg clips', 'observation::calcificationis', 'observation::capped', 'observation::cardia', 'observation::cath line', 'observation::cath whose', 'observation::change otherwise', 'observation::changes mostly', 'observation::chylous', 'observation::circumscribed dense', 'observation::circumscribed large', 'observation::closed', 'observation::cm ovoid', 'observation::cm rounded', 'observation::column could', 'observation::combination', 'observation::component but', 'observation::contributes', 'observation::costovertebral', 'observation::cyberknife', 'observation::defibrillators', 'observation::defined alveolar', 'observation::defined borders', 'observation::defined pulmonary', 'observation::demarcated local', 'observation::dextro', 'observation::disorder', 'observation::draining', 'observation::dvt', 'observation::elevted', 'observation::elimination', 'observation::encasing', 'observation::expander', 'observation::exploration', 'observation::fibrotic area', 'observation::filled fluid', 'observation::filled large', 'observation::fluid levels which', 'observation::food', 'observation::gibbus', 'observation::glass like', 'observation::growing lung', 'observation::hypodense', 'observation::i', 'observation::icreased', 'observation::iii right', 'observation::in of', 'observation::indeterminant', 'observation::indeterminate but', 'observation::insterstitial', 'observation::intracardiac', 'observation::jaundice', 'observation::kyphotic curvature', 'observation::kyphotic curvature centered', 'observation::lead projects', 'observation::like area', 'observation::like areas', 'observation::line within', 'observation::linx implant', 'observation::locule', 'observation::m', 'observation::meniscus', 'observation::misalignment', 'observation::moderate accompanying', 'observation::moderate amount', 'observation::multisegmental', 'observation::mycetoma', 'observation::necrosis', 'observation::nephrectomies', 'observation::nephrostomy', 'observation::nephroureterectomy', 'observation::obliderating', 'observation::obstructive process', 'observation::opaque foreign', 'observation::operative left', 'observation::operatively', 'observation::organized than', 'observation::origin', 'observation::osteochondroma', 'observation::pacer device', 'observation::pad again', 'observation::pad by', 'observation::pad causing', 'observation::paracentesis', 'observation::parallels', 'observation::particles', 'observation::pectoralis', 'observation::phase', 'observation::positioned lines', 'observation::process such', 'observation::processed', 'observation::pump', 'observation::radiation change', 'observation::ray examination', 'observation::redemonstrated', 'observation::relate', 'observation::related interstitial', 'observation::remnants', 'observation::rounder', 'observation::saccular', 'observation::sacculated', 'observation::sarcoma', 'observation::screw fixation', 'observation::screw fixation again', 'observation::shin', 'observation::shoulders', 'observation::site have', 'observation::sized density', 'observation::small portion', 'observation::spared', 'observation::specific left', 'observation::stir', 'observation::structure within', 'observation::surgical right', 'observation::suspected', 'observation::suture lines', 'observation::than 3 mm', 'observation::thoracostomy', 'observation::transmitting', 'observation::trauma /', 'observation::traumatic rib', 'observation::treated', 'observation::tube ends', 'observation::unequivocal', 'observation::unusual', 'observation::usually', 'observation::variants', 'observation::ventilated left', 'observation::walls', 'observation::well aerated', 'observation::well aerated today', 'observation::well today', 'observation::width', 'observation::wire again'] will be ignored
  warnings.warn(

\n===== fold=1 train=39690 test=4410 methods=6 =====
skip biomedclip_image_embedding fold 1
skip biomedclip_zero_shot_label_vector fold 1
skip biomedclip_mlp_label_vector fold 1
skip kg_radgraph_entity_oracle fold 1
skip gnn_non_transformer_gnn_graphsage_topk500_label_vector fold 1
skip gnn_transformer_gnn_transformerconv_topk100_label_vector fold 1

/data/liangz2/diffuser2/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:1016: UserWarning: unknown class(es) ['anatomy::6 cm', 'anatomy::acute', 'anatomy::auricle', 'anatomy::bandlike', 'anatomy::basal segment', 'anatomy::cadiopulmonary', 'anatomy::caliber', 'anatomy::cardiacsize', 'anatomy::cardiomediastial', 'anatomy::cephalization', 'anatomy::contribute', 'anatomy::deviates', 'anatomy::distortion', 'anatomy::each', 'anatomy::endovascular', 'anatomy::hemidiagraphms', 'anatomy::her', 'anatomy::hips', 'anatomy::horacic', 'anatomy::humeri', 'anatomy::indicates', 'anatomy::inter', 'anatomy::intraabdominal', 'anatomy::intracranial', 'anatomy::iodine', 'anatomy::kerley', 'anatomy::lobulated', 'anatomy::lung disease', 'anatomy::maintains', 'anatomy::material', 'anatomy::mediastinl', 'anatomy::most pedicle', 'anatomy::osteopathy', 'anatomy::particular', 'anatomy::percutaneously', 'anatomy::prevertebral', 'anatomy::processed', 'anatomy::pulmononary', 'anatomy::pulnoary', 'anatomy::redistribution', 'anatomy::secretions', 'anatomy::sided major', 'anatomy::signal', 'anatomy::space may', 'anatomy::streak', 'anatomy::striate', 'anatomy::sulcal', 'anatomy::t10', 'anatomy::t11 when', 'anatomy::t12 has', 'anatomy::team', 'anatomy::thoraolumbar', 'anatomy::thryoid gland', 'anatomy::vasculitis', 'anatomy::vena cava filter', 'anatomy::viridans', 'anatomy::vs', 'observation::0 cm left', 'observation::0 cm rounded', 'observation::0 less severe', 'observation::1 cm ovoid', 'observation::13', 'observation::2 x 1 2 cm left', 'observation::2cm', 'observation::3 cm rounded', 'observation::9 x 2 2 cm', 'observation::air can', 'observation::air today', 'observation::angulated', 'observation::anomaly', 'observation::appearing abnormalities', 'observation::as conspicuous', 'observation::ascites', 'observation::attenuated', 'observation::autoimmune hepatitis', 'observation::avr', 'observation::blood', 'observation::bluntin', 'observation::bowing', 'observation::brochiectasis', 'observation::calculus', 'observation::chamber pacer', 'observation::changes which', 'observation::channel left', 'observation::cholangiocarcinoma', 'observation::clearly', 'observation::closure device', 'observation::cocaine', 'observation::collabse', 'observation::collects', 'observation::comparison', 'observation::conglomerates', 'observation::containing lung', 'observation::cordis', 'observation::decreaseing', 'observation::defined mass', 'observation::demarcation', 'observation::densitiees', 'observation::density may', 'observation::deposited', 'observation::directed', 'observation::distinctness', 'observation::dressing', 'observation::eleveation', 'observation::endocarditis', 'observation::exagerrated', 'observation::existing lung', 'observation::existing small', 'observation::formations now', 'observation::fully characterized', 'observation::fully imaged', 'observation::guidewire', 'observation::ha', 'observation::hemithorax', 'observation::hypervolemia', 'observation::hypoventilatory', 'observation::hypoxia', 'observation::ijv', 'observation::ileus', 'observation::impproved', 'observation::incapsulated', 'observation::incompetence', 'observation::indicating', 'observation::intersitital', 'observation::levels consistent', 'observation::like lower', 'observation::line through', 'observation::maneuver', 'observation::mastopexy', 'observation::mettalic', 'observation::microatelectasis', 'observation::mm projecting', 'observation::moderate new', 'observation::molar', 'observation::mottled', 'observation::myxofibrosarcoma', 'observation::neuropathy', 'observation::ng', 'observation::node could', 'observation::opaque clips', 'observation::originating', 'observation::ornaments', 'observation::overhydration', 'observation::particullary', 'observation::patten', 'observation::pectum', 'observation::picc line again', 'observation::pigtail still', 'observation::pole', 'observation::ports into', 'observation::pressed', 'observation::prior exams', 'observation::psoriasis', 'observation::pull', 'observation::quantities', 'observation::radio', 'observation::rate', 'observation::reconstruction', 'observation::rectangular', 'observation::resides', 'observation::residuals', 'observation::retrolisthesis', 'observation::righ', 'observation::sclerosing', 'observation::seem', 'observation::sepation', 'observation::shaped old', 'observation::shrapnel', 'observation::sickle', 'observation::sized heart', 'observation::specific air', 'observation::specific right', 'observation::splinting', 'observation::spots', 'observation::streakiness', 'observation::subglottic', 'observation::supine technique', 'observation::support', 'observation::svc', 'observation::systems', 'observation::tendinitis', 'observation::tracheobronchomalacia', 'observation::trapping', 'observation::traumatic noting', 'observation::tube projects', 'observation::wall which', 'observation::warrants', 'observation::well visualized due', 'observation::x 1 5 cm density', 'observation::x 3 5 cm'] will be ignored
  warnings.warn(

\n===== fold=2 train=39690 test=4410 methods=6 =====
skip biomedclip_image_embedding fold 2
skip biomedclip_zero_shot_label_vector fold 2
skip biomedclip_mlp_label_vector fold 2
skip kg_radgraph_entity_oracle fold 2
skip gnn_non_transformer_gnn_graphsage_topk500_label_vector fold 2
skip gnn_transformer_gnn_transformerconv_topk100_label_vector fold 2

/data/liangz2/diffuser2/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:1016: UserWarning: unknown class(es) ['anatomy::2 cm below', 'anatomy::2nd', 'anatomy::across', 'anatomy::almost', 'anatomy::among', 'anatomy::anormalities', 'anatomy::ap', 'anatomy::apparent', 'anatomy::around', 'anatomy::arrest', 'anatomy::artey', 'anatomy::axillar', 'anatomy::bronchopneumonic', 'anatomy::care', 'anatomy::chilaiditi', 'anatomy::collections', 'anatomy::ct', 'anatomy::defects', 'anatomy::distance', 'anatomy::distended', 'anatomy::early', 'anatomy::either', 'anatomy::expansion', 'anatomy::foci', 'anatomy::gastrointestinal', 'anatomy::gradient', 'anatomy::hilar left', 'anatomy::hilar opacity', 'anatomy::interstial', 'anatomy::intraarticular', 'anatomy::intralobular', 'anatomy::like', 'anatomy::lower t', 'anatomy::lucent', 'anatomy::lung zone', 'anatomy::meidastinal', 'anatomy::metallic', 'anatomy::mimic', 'anatomy::mineral', 'anatomy::most portion', 'anatomy::mural', 'anatomy::neo', 'anatomy::oblique', 'anatomy::pectoralis', 'anatomy::percutaneous', 'anatomy::ph', 'anatomy::rub', 'anatomy::series', 'anatomy::side as', 'anatomy::side than', 'anatomy::spine fusion', 'anatomy::sternotomy', 'anatomy::subdiaphgramatic', 'anatomy::superimposition', 'anatomy::suprabasal', 'anatomy::supradiaphragmatic', 'anatomy::t10 vertebral', 'anatomy::t5 vertebral', 'anatomy::t6 level', 'anatomy::target', 'anatomy::thirds', 'anatomy::throughout', 'anatomy::thymus', 'anatomy::tourtous', 'anatomy::twelfth', 'anatomy::uper', 'anatomy::usually', 'anatomy::views', 'anatomy::zone distribution', 'observation::0 x 3 6 cm', 'observation::0 x 3 7cm rounded', 'observation::1 x 4 4 x 4 0 cm', 'observation::10', 'observation::2 cm may', 'observation::2 cm well', 'observation::2 x 2 3 cm', 'observation::2 x 3 0 cm', 'observation::2 x 7 5 cm', 'observation::22 mm since', 'observation::3 x 3 9 cm', 'observation::5 cm opacity', 'observation::8 x 3 cm', 'observation::9 cm more', 'observation::9 cm that', 'observation::anterolateral', 'observation::appendicitis', 'observation::as well expanded today', 'observation::as well this exam', 'observation::ateletasis', 'observation::benignity', 'observation::blurriness', 'observation::bronchopneumonic', 'observation::bronchopnuemonia', 'observation::capsular', 'observation::cath dens', 'observation::cath dual', 'observation::cath port', 'observation::cholecystectomy clips project', 'observation::chondrocalcinosis', 'observation::cm cystic', 'observation::cm round', 'observation::coalition', 'observation::collection between', 'observation::collection should', 'observation::collinear', 'observation::columns', 'observation::columns as', 'observation::correlating', 'observation::cribriform', 'observation::crowd', 'observation::cyberknife fibrosis', 'observation::defined areas', 'observation::defined vascular', 'observation::deformitities', 'observation::degrees', 'observation::dehydration', 'observation::denoting', 'observation::density could', 'observation::deodorant', 'observation::depicted', 'observation::dextropositioning', 'observation::did', 'observation::differences', 'observation::dullness', 'observation::edematous', 'observation::effaced', 'observation::elevator', 'observation::endarterectomy', 'observation::endoleak', 'observation::existing old', 'observation::existing opacity', 'observation::expanding left', 'observation::explanted', 'observation::extension that', 'observation::fan', 'observation::filled tracks', 'observation::fluid level which', 'observation::fluid levels consistent', 'observation::fluid levels has', 'observation::fully cleared', 'observation::generator over', 'observation::glass lesion', 'observation::grade liposarcoma', 'observation::hcc', 'observation::hemi', 'observation::hemodynamically significant', 'observation::hiatal hernias', 'observation::hickman catheter tip', 'observation::hilus', 'observation::homogeneously', 'observation::hydrothorax', 'observation::ifnection', 'observation::incipient', 'observation::indicates', 'observation::inflated lung', 'observation::injectable port', 'observation::intravascular', 'observation::inward', 'observation::kink', 'observation::less apparent', 'observation::leukopenia', 'observation::ligament', 'observation::limits normal', 'observation::lns', 'observation::located mass', 'observation::lumen pacemaker', 'observation::lumpectomies', 'observation::mammoplasty', 'observation::materials', 'observation::measure', 'observation::meet', 'observation::mm 14 mm since', 'observation::mm circular', 'observation::mm densely', 'observation::mm soft', 'observation::mm structure', 'observation::neutropenia', 'observation::normal /', 'observation::occlussion', 'observation::oligemia', 'observation::opcity', 'observation::operative alignment', 'observation::os', 'observation::overriding', 'observation::parathyroid', 'observation::pedicle', 'observation::pericarditis', 'observation::platelet', 'observation::pneumatocyst', 'observation::pneumothroax', 'observation::positional', 'observation::posttraumatic', 'observation::preexisted', 'observation::pyloric feeding', 'observation::radiodense', 'observation::rales', 'observation::reflects', 'observation::regional', 'observation::reoccurred', 'observation::represent', 'observation::retrosternal', 'observation::rheumatic', 'observation::s hernias', 'observation::sensitive', 'observation::shaped region', 'observation::sillouhette', 'observation::site as', 'observation::slightl', 'observation::solid material', 'observation::specks', 'observation::splenic', 'observation::stent within', 'observation::syndesmophytes', 'observation::systolic', 'observation::tears', 'observation::thoracotomy changes', 'observation::traumatic findings', 'observation::up procedure', 'observation::us', 'observation::uzrd', 'observation::vigorous'] will be ignored
  warnings.warn(

\n===== fold=3 train=39690 test=4410 methods=6 =====
skip biomedclip_image_embedding fold 3
skip biomedclip_zero_shot_label_vector fold 3
skip biomedclip_mlp_label_vector fold 3
skip kg_radgraph_entity_oracle fold 3
skip gnn_non_transformer_gnn_graphsage_topk500_label_vector fold 3
skip gnn_transformer_gnn_transformerconv_topk100_label_vector fold 3

/data/liangz2/diffuser2/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:1016: UserWarning: unknown class(es) ['anatomy::aa', 'anatomy::articulation', 'anatomy::asymmetry', 'anatomy::bands', 'anatomy::based fat', 'anatomy::bibasliar', 'anatomy::bilaeral', 'anatomy::cardial fat', 'anatomy::cardiopulmary', 'anatomy::carina', 'anatomy::carinal', 'anatomy::clavicular joint', 'anatomy::comparable', 'anatomy::complete', 'anatomy::conduit', 'anatomy::convexed', 'anatomy::courses', 'anatomy::cricopharyngeus', 'anatomy::cutaneous', 'anatomy::depending', 'anatomy::esophageal', 'anatomy::especially', 'anatomy::extremities', 'anatomy::ijv', 'anatomy::inferior location', 'anatomy::intracavitary', 'anatomy::intrapleural', 'anatomy::irregular', 'anatomy::isthmus', 'anatomy::l2', 'anatomy::least parts', 'anatomy::lower zone', 'anatomy::lumen central', 'anatomy::mixed', 'anatomy::multilevel', 'anatomy::note', 'anatomy::osteoarthritis', 'anatomy::partially', 'anatomy::phrenic', 'anatomy::pick', 'anatomy::pre', 'anatomy::predominant', 'anatomy::predominantly', 'anatomy::presternal', 'anatomy::priors', 'anatomy::proven', 'anatomy::ra junction', 'anatomy::radiograph', 'anatomy::reflects', 'anatomy::reported', 'anatomy::reticulation', 'anatomy::see', 'anatomy::side along', 'anatomy::sided component', 'anatomy::so', 'anatomy::some', 'anatomy::sphincter', 'anatomy::stenting', 'anatomy::stones', 'anatomy::superolateral', 'anatomy::supported', 'anatomy::suture', 'anatomy::symmetric', 'anatomy::t3 4 level', 'anatomy::thoracic process', 'anatomy::triple', 'anatomy::ventriculoperitoneal', 'anatomy::wart', 'anatomy::zone vascular', 'observation::0 x 3 0 cm', 'observation::00', 'observation::12', 'observation::15', 'observation::4 cm mass', 'observation::4 x 1 7 cm', 'observation::5 2 cm wide', 'observation::5 cm wide', 'observation::5 x 5 3 cm', 'observation::8 cm left', 'observation::8 mm', 'observation::accumulated', 'observation::appearing right', 'observation::apposition', 'observation::atelectais', 'observation::battery', 'observation::bcgosis', 'observation::be definitively assessed due', 'observation::bit lower', 'observation::bleb', 'observation::blulting', 'observation::breakage', 'observation::broad', 'observation::bronchovasculature', 'observation::cerclage wire', 'observation::ch', 'observation::channel pacemaker', 'observation::chlamydia', 'observation::circumscribed oval', 'observation::coexisting', 'observation::conforms', 'observation::consistence', 'observation::consolidating', 'observation::coures', 'observation::cvp', 'observation::defined increased', 'observation::degree more', 'observation::descends', 'observation::developed upper', 'observation::device has', 'observation::discern where', 'observation::dissecting', 'observation::each', 'observation::entered', 'observation::eosinophilia', 'observation::existing stent', 'observation::field view', 'observation::filled when', 'observation::flare', 'observation::fluid loculations', 'observation::fluids level', 'observation::grade fevers', 'observation::grafts', 'observation::haemophilus', 'observation::hernias', 'observation::homogeneous', 'observation::hypoplasia', 'observation::imbedded', 'observation::impressions', 'observation::indeterminate acuity', 'observation::infectious minimal', 'observation::infolding', 'observation::insufficient', 'observation::interposition', 'observation::juxtaphrenic', 'observation::layer', 'observation::like atelectasis', 'observation::like component', 'observation::limite', 'observation::looking', 'observation::lymphadenopathies', 'observation::made', 'observation::markedly', 'observation::metastatses', 'observation::microcalcifications', 'observation::micronodularity', 'observation::mildtop', 'observation::mm ring', 'observation::moderatesized', 'observation::multilocular', 'observation::navicular', 'observation::necrotizing', 'observation::node compatible', 'observation::node may', 'observation::nodular opacities', 'observation::normal likely', 'observation::normalization', 'observation::occurring', 'observation::offset', 'observation::op changes', 'observation::operative loculations', 'observation::opportunistic', 'observation::oval opacity', 'observation::pad identified', 'observation::plating', 'observation::positive', 'observation::posterioly', 'observation::predominanlty', 'observation::presence', 'observation::presents', 'observation::prior exam', 'observation::probable', 'observation::quite', 'observation::radiopaque devices', 'observation::redistributed', 'observation::relation', 'observation::rightwards', 'observation::rule', 'observation::scar formations', 'observation::severe compression', 'observation::shadows rather', 'observation::sharply visualized', 'observation::short', 'observation::sign', 'observation::situated', 'observation::speckled', 'observation::stripping', 'observation::stronger', 'observation::summation', 'observation::syndesmosis', 'observation::t8', 'observation::than 9 mm', 'observation::tortunosity', 'observation::transversely across', 'observation::trapped', 'observation::under 1 cm', 'observation::vertebroplasty changes', 'observation::walled', 'observation::weding', 'observation::well evaluated', 'observation::wirelike', 'observation::x 4 6 cm'] will be ignored
  warnings.warn(

\n===== fold=4 train=39690 test=4410 methods=6 =====
skip biomedclip_image_embedding fold 4
skip biomedclip_zero_shot_label_vector fold 4
skip biomedclip_mlp_label_vector fold 4
skip kg_radgraph_entity_oracle fold 4
skip gnn_non_transformer_gnn_graphsage_topk500_label_vector fold 4
skip gnn_transformer_gnn_transformerconv_topk100_label_vector fold 4

/data/liangz2/diffuser2/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:1016: UserWarning: unknown class(es) ['anatomy::5 cm', 'anatomy::actually', 'anatomy::annuls', 'anatomy::antrum', 'anatomy::attention', 'anatomy::avascular', 'anatomy::based rounded', 'anatomy::bed consistent', 'anatomy::bibasalar', 'anatomy::boarders', 'anatomy::branches', 'anatomy::bronchoalveolar', 'anatomy::cartilaginous', 'anatomy::chain', 'anatomy::chambers', 'anatomy::cpa', 'anatomy::cuff', 'anatomy::disruption', 'anatomy::dominant', 'anatomy::eleventh', 'anatomy::epihilar', 'anatomy::extension', 'anatomy::fissue', 'anatomy::flow', 'anatomy::hand', 'anatomy::he', 'anatomy::hemidiagphram', 'anatomy::hemidiaphgragm', 'anatomy::hemidiphragms', 'anatomy::hemorrhage', 'anatomy::interposition', 'anatomy::ize', 'anatomy::jejunum range', 'anatomy::lend', 'anatomy::localizing', 'anatomy::multifocal', 'anatomy::nasoenteric', 'anatomy::next', 'anatomy::occupying', 'anatomy::orbital', 'anatomy::pneumonic', 'anatomy::reflection', 'anatomy::reveals', 'anatomy::rhythm', 'anatomy::rightwardly', 'anatomy::rotator', 'anatomy::side where', 'anatomy::sided fat', 'anatomy::sided large', 'anatomy::sillouette', 'anatomy::sparing', 'anatomy::stone', 'anatomy::t4', 'anatomy::thoracic volume', 'anatomy::ung', 'anatomy::vena cava vein', 'anatomy::wall port', 'anatomy::zone could', 'anatomy::zonse', 'observation::0 cm', 'observation::0 x 2 x 3 cm', 'observation::11 mm which', 'observation::3 mm local', 'observation::4cm rounded', 'observation::9 centimeters', 'observation::accurately assess', 'observation::adenocaricinoma', 'observation::airless', 'observation::altectasis', 'observation::angle', 'observation::anterolisthesis', 'observation::areola', 'observation::arge', 'observation::assess because', 'observation::assymetry', 'observation::atresia', 'observation::augmented', 'observation::avid opacity', 'observation::based rounded', 'observation::basis', 'observation::be assessed given', 'observation::be assessed since', 'observation::be evaluated it', 'observation::bigger', 'observation::bronchogram', 'observation::bubbles', 'observation::cardiad', 'observation::cephalad', 'observation::changes along', 'observation::circulation', 'observation::circumscribed but', 'observation::clacified', 'observation::cm that', 'observation::colectomy', 'observation::collection within', 'observation::come', 'observation::comensatory', 'observation::commensurate', 'observation::component within', 'observation::compresion', 'observation::concealed', 'observation::conceals', 'observation::condition', 'observation::connections', 'observation::constant', 'observation::contained', 'observation::continuously', 'observation::cp', 'observation::cranially', 'observation::ct', 'observation::debris', 'observation::defined dense', 'observation::defined ground', 'observation::defined lung', 'observation::degerative', 'observation::density structure', 'observation::detect', 'observation::dextroscoliotic', 'observation::dimineralized', 'observation::discontinuation', 'observation::displaced lucency', 'observation::dissected', 'observation::dobhoff', 'observation::elevating', 'observation::enlarge', 'observation::esema', 'observation::existed', 'observation::extention', 'observation::fdg avid opacity', 'observation::few', 'observation::fifth', 'observation::filled neo', 'observation::filled structures', 'observation::fluffy', 'observation::fluid level denoting', 'observation::fluid level now', 'observation::fracturing', 'observation::fracutres', 'observation::gastrectomy', 'observation::gently', 'observation::glass nodular', 'observation::grade lung', 'observation::growing', 'observation::grown', 'observation::have ford', 'observation::headed', 'observation::hepatocellular', 'observation::hiatal hernia but', 'observation::highly', 'observation::hypoexpanded', 'observation::hypovascularity', 'observation::hyuperinflated', 'observation::impactions', 'observation::indicate', 'observation::infections', 'observation::infolded', 'observation::instead', 'observation::insult', 'observation::inter around', 'observation::interface', 'observation::interposed', 'observation::interspersed', 'observation::interstial', 'observation::introducer', 'observation::ipsilateral', 'observation::juxtamediastinal', 'observation::laceration', 'observation::lead within', 'observation::less distended but', 'observation::like scar', 'observation::line cannot', 'observation::longest', 'observation::longstanding', 'observation::loop within', 'observation::lumpectomy', 'observation::lytic change', 'observation::marginates', 'observation::meniscoid', 'observation::millimeters', 'observation::mm 14 mm', 'observation::mm long', 'observation::mm oval', 'observation::mm post', 'observation::moderatly', 'observation::most wire', 'observation::ninth', 'observation::normal though', 'observation::normalsize', 'observation::notmal limits', 'observation::obstructed', 'observation::opacites', 'observation::operative change', 'observation::organization', 'observation::overnight', 'observation::pacers', 'observation::pectoral', 'observation::pectorally', 'observation::penetrated', 'observation::per', 'observation::persistently', 'observation::place as', 'observation::place within', 'observation::plug', 'observation::pneumohydrothorax', 'observation::poor', 'observation::preserved', 'observation::pressure', 'observation::proliferative', 'observation::protrudes', 'observation::put', 'observation::reflective', 'observation::resolved right', 'observation::rheumatologic', 'observation::riding right', 'observation::serpiginous', 'observation::severe intimal', 'observation::shadow but', 'observation::shallow', 'observation::shape configuration', 'observation::shaped convex', 'observation::size left', 'observation::spaces', 'observation::spherical', 'observation::spiral', 'observation::spite', 'observation::stability', 'observation::staple', 'observation::strongly', 'observation::structural', 'observation::substantially increased', 'observation::surgical reduction', 'observation::t8 compression', 'observation::tachycardia', 'observation::than one half', 'observation::their', 'observation::thicker', 'observation::torsion', 'observation::transmitted', 'observation::umremarkable', 'observation::view this exam', 'observation::wetness'] will be ignored
  warnings.warn(

\n===== fold=5 train=39690 test=4410 methods=6 =====
skip biomedclip_image_embedding fold 5
skip biomedclip_zero_shot_label_vector fold 5
skip biomedclip_mlp_label_vector fold 5
skip kg_radgraph_entity_oracle fold 5
skip gnn_non_transformer_gnn_graphsage_topk500_label_vector fold 5
skip gnn_transformer_gnn_transformerconv_topk100_label_vector fold 5

/data/liangz2/diffuser2/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:1016: UserWarning: unknown class(es) ['anatomy::0 pulmonary window', 'anatomy::5 cm below', 'anatomy::angels', 'anatomy::angle as', 'anatomy::anterior ribs', 'anatomy::aortopulmonic window', 'anatomy::apicoseptal', 'anatomy::arm tingling', 'anatomy::arteriosum', 'anatomy::based tumor', 'anatomy::blebs', 'anatomy::bridging', 'anatomy::cardimediastinal', 'anatomy::cariomediatinal', 'anatomy::catheter', 'anatomy::cerebellar', 'anatomy::cerivcal', 'anatomy::cleared', 'anatomy::close', 'anatomy::contact', 'anatomy::contents', 'anatomy::contiguous levels', 'anatomy::costosternal', 'anatomy::deficiency', 'anatomy::denotes', 'anatomy::did', 'anatomy::displacement', 'anatomy::displaces', 'anatomy::expected', 'anatomy::flowing', 'anatomy::frontal', 'anatomy::hemispheric', 'anatomy::hila region', 'anatomy::hyperexpansion', 'anatomy::infra', 'anatomy::inner', 'anatomy::inward', 'anatomy::juxtamediastinal', 'anatomy::ligamentum', 'anatomy::lob', 'anatomy::lungfield', 'anatomy::masses', 'anatomy::midesophagus', 'anatomy::mostly', 'anatomy::must', 'anatomy::myocardium', 'anatomy::organs', 'anatomy::out', 'anatomy::paraaortic', 'anatomy::paranasal', 'anatomy::parathoracic', 'anatomy::pigtailed', 'anatomy::posteromedial', 'anatomy::questioned', 'anatomy::representing', 'anatomy::reticulolinear', 'anatomy::retrosternum', 'anatomy::roux', 'anatomy::severe', 'anatomy::sicth', 'anatomy::side but', 'anatomy::side likely', 'anatomy::side since', 'anatomy::sided double', 'anatomy::sided pressure', 'anatomy::silouhette', 'anatomy::site', 'anatomy::spiral', 'anatomy::streaks', 'anatomy::t12 vertebral body', 'anatomy::tiny', 'anatomy::torso', 'anatomy::tumors', 'anatomy::visible', 'anatomy::volvulus', 'anatomy::will', 'observation::0 x 3 5 cm', 'observation::1 cm linear', 'observation::1 x 1 1 cm opacity', 'observation::2 mm right', 'observation::3 x 2 1 cm round', 'observation::4 4 0 mm', 'observation::4 mm', 'observation::7 2 8 cm respectively', 'observation::8 cm respectively', 'observation::alters', 'observation::apparently', 'observation::appearances', 'observation::artery', 'observation::atelactasis', 'observation::atelctasis', 'observation::atelecatasis', 'observation::be defined', 'observation::borders', 'observation::buckshot', 'observation::bulky', 'observation::c', 'observation::calcifcations', 'observation::capsulated', 'observation::cartilaginous', 'observation::cell carcinoma', 'observation::chain suture site', 'observation::circular', 'observation::clips can', 'observation::collapsing', 'observation::collecting', 'observation::compession', 'observation::consisting', 'observation::consolidate', 'observation::contoured', 'observation::course through', 'observation::cutaneous', 'observation::defibrillator has', 'observation::defined than', 'observation::defined vascularity', 'observation::degeneration', 'observation::degree turn', 'observation::density consistent', 'observation::ends deeper', 'observation::enlargedgoiter', 'observation::enters', 'observation::environmental', 'observation::esophagectomy changes', 'observation::eventrated', 'observation::expansive', 'observation::exposures', 'observation::extrinsic', 'observation::fat deposition', 'observation::filter', 'observation::fixating', 'observation::fluid levels corresponding', 'observation::fragmentation', 'observation::fundoplication', 'observation::grade temperature', 'observation::gravitating', 'observation::gross', 'observation::gunshot', 'observation::hemodynamic', 'observation::heterogenous', 'observation::hickman port catheter', 'observation::hoarseness', 'observation::hypertensive', 'observation::ij', 'observation::indeterminate upper', 'observation::infiltrations', 'observation::inlfation', 'observation::intersitial', 'observation::interstital', 'observation::introduced', 'observation::ivc', 'observation::lateralized', 'observation::layers', 'observation::least 4', 'observation::least 4 cm', 'observation::lenticular', 'observation::line would', 'observation::lingula', 'observation::lobulatated', 'observation::locally', 'observation::losses', 'observation::lymphangitis', 'observation::mentioned rib', 'observation::min', 'observation::minor fissure', 'observation::minor fissure as', 'observation::mm peripheral', 'observation::mm projects', 'observation::none', 'observation::nontuberculous', 'observation::operative setting', 'observation::ossifications', 'observation::overexpansion', 'observation::overlaod', 'observation::pacitiy', 'observation::pellets', 'observation::pen', 'observation::penetration', 'observation::phleboliths', 'observation::plana', 'observation::pleurx catheter placement', 'observation::pleurx catheters', 'observation::port cath that', 'observation::projectional', 'observation::proteinosis', 'observation::read', 'observation::reconstructive', 'observation::redistrubtion', 'observation::related lung', 'observation::relation acromion', 'observation::repositioning', 'observation::scans', 'observation::sequestration', 'observation::shaping', 'observation::sheet', 'observation::side port may', 'observation::sliding', 'observation::spaced', 'observation::splenomegaly', 'observation::stabilizing', 'observation::stages', 'observation::sticker', 'observation::stigmata', 'observation::strandlike', 'observation::structure which', 'observation::subdiaphgragmatic', 'observation::suggests', 'observation::tacks', 'observation::then', 'observation::thick', 'observation::through surgery', 'observation::through which', 'observation::toe', 'observation::tracking just', 'observation::transesophageal', 'observation::transplanted', 'observation::tricuspid', 'observation::ttern', 'observation::tumors', 'observation::ventricular', 'observation::ventriculomegaly', 'observation::visually', 'observation::vmoderate', 'observation::warranting', 'observation::weakness', 'observation::well appreciated beyond', 'observation::well localized', 'observation::what', 'observation::whether', 'observation::x 23 mm dense', 'observation::x 6 mm could'] will be ignored
  warnings.warn(

\n===== fold=6 train=39690 test=4410 methods=6 =====
skip biomedclip_image_embedding fold 6
skip biomedclip_zero_shot_label_vector fold 6
skip biomedclip_mlp_label_vector fold 6
skip kg_radgraph_entity_oracle fold 6
skip gnn_non_transformer_gnn_graphsage_topk500_label_vector fold 6
skip gnn_transformer_gnn_transformerconv_topk100_label_vector fold 6

/data/liangz2/diffuser2/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:1016: UserWarning: unknown class(es) ['anatomy::11th', 'anatomy::6th rib left', 'anatomy::8', 'anatomy::agian', 'anatomy::angle likely', 'anatomy::anteroposterior', 'anatomy::azygoesophageal', 'anatomy::basal right', 'anatomy::bronchopneumonia', 'anatomy::bronchotracheal', 'anatomy::ca', 'anatomy::cardimediastinum', 'anatomy::cardiopulmoanry', 'anatomy::cardkiopulmonary', 'anatomy::caudal', 'anatomy::causes', 'anatomy::caval', 'anatomy::circumference', 'anatomy::costovertebral', 'anatomy::crossings', 'anatomy::cystic', 'anatomy::deformity', 'anatomy::diaphragmatic tube', 'anatomy::discoid', 'anatomy::engorgement', 'anatomy::exaggerated', 'anatomy::facet', 'anatomy::fragments', 'anatomy::grater', 'anatomy::healing', 'anatomy::hemiazygos', 'anatomy::hemothorax', 'anatomy::heterogeneity', 'anatomy::hx', 'anatomy::increased', 'anatomy::infiltrate', 'anatomy::interposed', 'anatomy::interruption', 'anatomy::intraluminal', 'anatomy::jxn', 'anatomy::l2 should', 'anatomy::lngs', 'anatomy::lung region', 'anatomy::manubrial', 'anatomy::mediport', 'anatomy::mesh', 'anatomy::notch', 'anatomy::outlet', 'anatomy::pat', 'anatomy::pectorally', 'anatomy::pedicles', 'anatomy::perhaps', 'anatomy::peribronchical', 'anatomy::perihilum', 'anatomy::peripheries', 'anatomy::peristernal', 'anatomy::peritoneal', 'anatomy::pleurae', 'anatomy::pleurx', 'anatomy::prior', 'anatomy::procedural', 'anatomy::pulmonary window', 'anatomy::rales', 'anatomy::reconstruction', 'anatomy::remaining', 'anatomy::retroesternal', 'anatomy::rightsided', 'anatomy::rings', 'anatomy::scoliosis', 'anatomy::side only', 'anatomy::sided hydro', 'anatomy::sided location', 'anatomy::sided svc', 'anatomy::siillouhette', 'anatomy::silhoette', 'anatomy::sillouhette', 'anatomy::skeleton', 'anatomy::space as', 'anatomy::staghorn', 'anatomy::stem', 'anatomy::sternal component', 'anatomy::subsequent', 'anatomy::superior vena cava', 'anatomy::systems', 'anatomy::undulation', 'anatomy::upward', 'anatomy::view', 'anatomy::visualized', 'anatomy::wall may', 'anatomy::widespread', 'observation::1 8 cm 3 5 cm', 'observation::2 cm opacity', 'observation::3 x 1 5 cm', 'observation::3cm superior', 'observation::5 7 5 cm', 'observation::5 cm structure', 'observation::5mm right', 'observation::7 x 6 4 cm', 'observation::9 cm left', 'observation::9 cm rounded', 'observation::abscesses', 'observation::abuse', 'observation::ac', 'observation::acid', 'observation::aerations', 'observation::air levels', 'observation::airway', 'observation::alongside', 'observation::already', 'observation::ankylosing', 'observation::anteroposterior', 'observation::approximately', 'observation::as full', 'observation::barrel', 'observation::blebectomy', 'observation::body sensation', 'observation::bronchogenic', 'observation::bronchograms consistent', 'observation::cath end', 'observation::cbd', 'observation::change between', 'observation::chrnoic', 'observation::chroncity', 'observation::circumscribed lung', 'observation::cleared', 'observation::cll', 'observation::cm each', 'observation::cm well', 'observation::common', 'observation::conditions', 'observation::confusion', 'observation::conglomerate', 'observation::consider', 'observation::corpectomy', 'observation::created', 'observation::crossing', 'observation::cut off', 'observation::cylindiracal', 'observation::defined 4', 'observation::defined small', 'observation::dense area', 'observation::device lead', 'observation::device pack', 'observation::devise', 'observation::diaphragm', 'observation::distribute', 'observation::egophony', 'observation::element', 'observation::englarged', 'observation::enough', 'observation::erosive', 'observation::expanded symmetric', 'observation::fluid level compatible', 'observation::forming infection', 'observation::gastrojejunostomy catheter', 'observation::gastrojejunostomy catheter within', 'observation::hazy opacities', 'observation::hazziness', 'observation::head', 'observation::here', 'observation::hyerinflation', 'observation::increases', 'observation::indeterminate mid', 'observation::interfacial', 'observation::it', 'observation::lead cardiac', 'observation::lead device', 'observation::lead pacing', 'observation::line position', 'observation::loculated right', 'observation::loss within', 'observation::lying', 'observation::lymphocytic', 'observation::malacia', 'observation::marker that', 'observation::mention', 'observation::mildling', 'observation::mm lymph', 'observation::multilobulated', 'observation::mutliple', 'observation::neurocysticercosis', 'observation::nipple shadow', 'observation::nocardia', 'observation::noninfectious', 'observation::normal but', 'observation::o2 requirements', 'observation::obliquely', 'observation::opacificaties', 'observation::organisms', 'observation::ovarian', 'observation::overloads', 'observation::pad rather', 'observation::paroxysmal', 'observation::peritoneal', 'observation::phenomenon', 'observation::pigtail drain', 'observation::pleurx drainage', 'observation::poorly visualized though', 'observation::positioned icd', 'observation::predating', 'observation::preservation', 'observation::pressures', 'observation::radiodensities', 'observation::radiolucent', 'observation::report', 'observation::resected', 'observation::respiratory', 'observation::revision', 'observation::rpo position', 'observation::rul', 'observation::rv', 'observation::senile', 'observation::shadows but', 'observation::sharper', 'observation::shattered', 'observation::simulates', 'observation::stage changes', 'observation::sub', 'observation::sublte', 'observation::successful', 'observation::surgeries', 'observation::surgical configuration', 'observation::syncope', 'observation::thickness', 'observation::thin', 'observation::third right', 'observation::thorax', 'observation::tips again', 'observation::tobacco', 'observation::traumatic injury', 'observation::tubulated', 'observation::typical', 'observation::ultrasound', 'observation::unchnaged', 'observation::unfused', 'observation::unwinding', 'observation::which could', 'observation::wi', 'observation::x 16 mm opacity', 'observation::x 7 cm mass'] will be ignored
  warnings.warn(

\n===== fold=7 train=39690 test=4410 methods=6 =====
skip biomedclip_image_embedding fold 7
skip biomedclip_zero_shot_label_vector fold 7
skip biomedclip_mlp_label_vector fold 7
skip kg_radgraph_entity_oracle fold 7
skip gnn_non_transformer_gnn_graphsage_topk500_label_vector fold 7
skip gnn_transformer_gnn_transformerconv_topk100_label_vector fold 7

/data/liangz2/diffuser2/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:1016: UserWarning: unknown class(es) ['anatomy::10', 'anatomy::4 cm', 'anatomy::abdominal process', 'anatomy::accounts', 'anatomy::acromion', 'anatomy::aerated', 'anatomy::aligns', 'anatomy::anterolaterally', 'anatomy::apicolaterally', 'anatomy::asthma cardiac', 'anatomy::attenuation', 'anatomy::bibasialr', 'anatomy::cardiacmediastinal', 'anatomy::cement', 'anatomy::column e', 'anatomy::compressive', 'anatomy::decreased', 'anatomy::diaphragam', 'anatomy::displaced', 'anatomy::drug', 'anatomy::estimated', 'anatomy::extraparenchymal', 'anatomy::faint', 'anatomy::girdles', 'anatomy::having', 'anatomy::hematoma', 'anatomy::induced', 'anatomy::interstital', 'anatomy::intramuscular', 'anatomy::intravenous', 'anatomy::iv', 'anatomy::lateral arch', 'anatomy::likley', 'anatomy::ling', 'anatomy::lowe', 'anatomy::lower hemithorax', 'anatomy::mid esophagus', 'anatomy::mogul', 'anatomy::monitoring', 'anatomy::nodal', 'anatomy::non', 'anatomy::nterstitial', 'anatomy::o', 'anatomy::off', 'anatomy::ossesous', 'anatomy::pathologic', 'anatomy::patten', 'anatomy::plugging', 'anatomy::pneumothorax', 'anatomy::posteriormost', 'anatomy::previously', 'anatomy::radical', 'anatomy::raise', 'anatomy::relatively', 'anatomy::ronchial', 'anatomy::saline', 'anatomy::several', 'anatomy::sided area', 'anatomy::sided lateral', 'anatomy::sided plate', 'anatomy::sided power', 'anatomy::sized', 'anatomy::space along', 'anatomy::spontaneous', 'anatomy::study', 'anatomy::substantial', 'anatomy::t11 which', 'anatomy::t6 7 level', 'anatomy::t7 vertebral', 'anatomy::take', 'anatomy::tap', 'anatomy::tear', 'anatomy::thoracostomy', 'anatomy::trauma', 'anatomy::underlying', 'anatomy::upper portion', 'anatomy::vagus', 'anatomy::width', 'observation::1 cm', 'observation::14', 'observation::18 mm wide', 'observation::2 cm rounded', 'observation::3 ac', 'observation::3 cm right', 'observation::5 cm density', 'observation::5 cm left', 'observation::5 mm', 'observation::5 x 2 7 cm round', 'observation::5 x 6 6 cm thin', 'observation::7 x 4 6 cm', 'observation::8 x 2 2 cm', 'observation::9 cm', 'observation::9 cm right', 'observation::9 x 2 2 cm which', 'observation::abdominal', 'observation::accompanying', 'observation::accurately be assessed', 'observation::air identified', 'observation::airtrapping', 'observation::appearing heart', 'observation::arising', 'observation::atelecatsis', 'observation::based right', 'observation::beginning', 'observation::bullectomy', 'observation::bullet', 'observation::cannulated', 'observation::cannulates', 'observation::cement', 'observation::chamber dual', 'observation::circumscribed left', 'observation::circumscribed mass', 'observation::circumscribed round', 'observation::cm elliptical', 'observation::cm linear', 'observation::cm post', 'observation::cobblestone', 'observation::construct', 'observation::content', 'observation::coughing', 'observation::crepitus', 'observation::cut', 'observation::defined focal', 'observation::defined region', 'observation::defined relatively', 'observation::degnerative', 'observation::denotes', 'observation::density area', 'observation::device which', 'observation::dexropositioning', 'observation::discontinuities', 'observation::distorted', 'observation::distribution only', 'observation::diverticulitis', 'observation::dobbhoff catheter', 'observation::dobbhoff tube', 'observation::double', 'observation::downward', 'observation::effect although', 'observation::eliminated', 'observation::enchondroma', 'observation::end versus', 'observation::entity', 'observation::episodes', 'observation::esophagectomy pull', 'observation::essentially', 'observation::existing process', 'observation::fashion', 'observation::fibroadenomas', 'observation::filled colon', 'observation::filled distention', 'observation::fluid due', 'observation::fluid level again', 'observation::fluid level identified', 'observation::fluid levels that', 'observation::formations as', 'observation::fungus ball', 'observation::gallstone', 'observation::gastritis', 'observation::generator device', 'observation::glass pattern', 'observation::healings', 'observation::hemorrhagic', 'observation::hyperparathyroidism', 'observation::hypoplastic', 'observation::ilateral', 'observation::indicated', 'observation::inspiration as', 'observation::interbody', 'observation::invasive', 'observation::its', 'observation::kommerell', 'observation::lace', 'observation::leiomyosarcoma', 'observation::less distinct', 'observation::level projects', 'observation::like right', 'observation::longitudinally', 'observation::maintained', 'observation::malalignment', 'observation::medallion', 'observation::mm likely', 'observation::mm really', 'observation::moderate vascular', 'observation::multilobar', 'observation::nonbacterial', 'observation::nonunion', 'observation::obstructive left', 'observation::operative appearance', 'observation::organism', 'observation::outward borders', 'observation::packs', 'observation::paralysis', 'observation::patch', 'observation::pigtail catheter within', 'observation::pleuritic', 'observation::pneumthorax', 'observation::pnuemonia', 'observation::pnuemothorax', 'observation::port port', 'observation::portions', 'observation::position within', 'observation::postero', 'observation::previously', 'observation::procedural left', 'observation::protruding', 'observation::radiating', 'observation::resuscitation', 'observation::s age', 'observation::s shaped spinal', 'observation::s tenderness', 'observation::saturation', 'observation::sequelae', 'observation::shaped spinal', 'observation::sharply round', 'observation::sharpness', 'observation::shown', 'observation::shunts', 'observation::situation', 'observation::slight fever', 'observation::small right', 'observation::spontaneous', 'observation::spoon', 'observation::stone', 'observation::superimposition', 'observation::surgical opacity', 'observation::synostosis', 'observation::system', 'observation::technique', 'observation::term interval', 'observation::thymectomy', 'observation::tips catheter', 'observation::tips over', 'observation::unchagned', 'observation::unlikely', 'observation::uptake', 'observation::vertebra', 'observation::very well defined', 'observation::view', 'observation::visualize', 'observation::wedged', 'observation::well demarcated', 'observation::well depicted', 'observation::x 10 mm density', 'observation::x 10 mm right'] will be ignored
  warnings.warn(

\n===== fold=8 train=39690 test=4410 methods=6 =====
skip biomedclip_image_embedding fold 8
skip biomedclip_zero_shot_label_vector fold 8
skip biomedclip_mlp_label_vector fold 8
skip kg_radgraph_entity_oracle fold 8
skip gnn_non_transformer_gnn_graphsage_topk500_label_vector fold 8
skip gnn_transformer_gnn_transformerconv_topk100_label_vector fold 8

/data/liangz2/diffuser2/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:1016: UserWarning: unknown class(es) ['anatomy::5 cm above', 'anatomy::aortic lines', 'anatomy::artifact', 'anatomy::being', 'anatomy::bleb', 'anatomy::brachycephalic', 'anatomy::branch', 'anatomy::bronchiovasculature', 'anatomy::bronchopleural', 'anatomy::bullous', 'anatomy::cap', 'anatomy::cardiomedistinal', 'anatomy::cardiopulmonry', 'anatomy::carotids', 'anatomy::cava', 'anatomy::centrally', 'anatomy::cm distal', 'anatomy::coils', 'anatomy::concerning', 'anatomy::coracoid', 'anatomy::corevalve', 'anatomy::coronaries', 'anatomy::cortex', 'anatomy::date', 'anatomy::dermal', 'anatomy::displacing', 'anatomy::effort', 'anatomy::electrodes', 'anatomy::equal', 'anatomy::evidence', 'anatomy::extent', 'anatomy::foot', 'anatomy::formation', 'anatomy::hd', 'anatomy::herniation', 'anatomy::hyper', 'anatomy::immediately', 'anatomy::infraclavicular', 'anatomy::infrahepatic', 'anatomy::intraparenchymal', 'anatomy::intravascular', 'anatomy::ivc', 'anatomy::junction into', 'anatomy::kyphoplasty', 'anatomy::larger', 'anatomy::less', 'anatomy::low lung', 'anatomy::lung opacity', 'anatomy::median', 'anatomy::mediastianal', 'anatomy::midclavicular', 'anatomy::origin', 'anatomy::plerual', 'anatomy::possible', 'anatomy::reactions', 'anatomy::restriction', 'anatomy::rod', 'anatomy::rotation', 'anatomy::segmentectomy', 'anatomy::side matching', 'anatomy::sided air', 'anatomy::sided device', 'anatomy::sided surgery', 'anatomy::sided tube', 'anatomy::silouette', 'anatomy::situated', 'anatomy::sternomanubrioial', 'anatomy::subchondral', 'anatomy::subphrenic', 'anatomy::supracardiac', 'anatomy::suspicious', 'anatomy::t3', 'anatomy::territory', 'anatomy::thin', 'anatomy::two', 'anatomy::unilateral', 'anatomy::vena', 'anatomy::ventriculopleural', 'anatomy::window could', 'observation::1 mm rounded', 'observation::3 x 4 5 cm mass', 'observation::4 cm large', 'observation::5 x 1 0 x 1 1 cm', 'observation::6 mm density', 'observation::6 rounded opacity', 'observation::8 x 1 6 cm', 'observation::accessing', 'observation::annuloplasty', 'observation::annulus', 'observation::appearing changes', 'observation::arises', 'observation::arthrosis', 'observation::artifactual', 'observation::aspirated', 'observation::assaulted', 'observation::assymetric', 'observation::athletic', 'observation::avid lesion', 'observation::be assessed because', 'observation::because', 'observation::bed', 'observation::bifurcating', 'observation::bore right', 'observation::bridge', 'observation::cage', 'observation::calcfication', 'observation::capping', 'observation::carotid', 'observation::cath issues', 'observation::centers', 'observation::changes related', 'observation::clavicular', 'observation::cm broad', 'observation::cm faint', 'observation::cm mass', 'observation::concurrent', 'observation::conglomeration', 'observation::contacting', 'observation::costal', 'observation::cranial', 'observation::current', 'observation::curve', 'observation::curvilinear structure', 'observation::defined left', 'observation::defined linear', 'observation::defined more', 'observation::defined ovoid', 'observation::deployed', 'observation::device placement', 'observation::dextrocardia', 'observation::diease', 'observation::discoid', 'observation::dissemination', 'observation::distortions', 'observation::distraction', 'observation::diversion', 'observation::drainage catheters', 'observation::e', 'observation::ectatic type', 'observation::electrode also', 'observation::enlargements', 'observation::eroded', 'observation::evaluate given', 'observation::facility', 'observation::favor', 'observation::fixations', 'observation::fluid level around', 'observation::fluids', 'observation::foreshortening', 'observation::formation about', 'observation::freactures', 'observation::frontal', 'observation::glass densities', 'observation::habitus', 'observation::hemodialysis catheter has', 'observation::hep', 'observation::hernia repair', 'observation::heterotopic', 'observation::included', 'observation::incompletely imaged', 'observation::indicative', 'observation::infilterates', 'observation::inspirational', 'observation::interstitium', 'observation::leukocytosis', 'observation::limits as', 'observation::lobe', 'observation::macrolobulated', 'observation::marked than', 'observation::meningioma', 'observation::mentioned', 'observation::milder', 'observation::mixed', 'observation::morgagni', 'observation::much as 11 mm', 'observation::name', 'observation::need', 'observation::needle', 'observation::nodes again', 'observation::normal unchanged', 'observation::obliques', 'observation::occlusion', 'observation::occupy', 'observation::ocollection', 'observation::on or', 'observation::op', 'observation::opacifying', 'observation::orogastric type tube', 'observation::pack along', 'observation::pad although', 'observation::palpitations', 'observation::paralyzed', 'observation::parenchyma', 'observation::patterns', 'observation::patulous', 'observation::pheresis', 'observation::pills', 'observation::plasty', 'observation::polyarthropathy', 'observation::port below', 'observation::port cath tip', 'observation::posture', 'observation::radiation fibrosis', 'observation::represents', 'observation::reversible', 'observation::s chin', 'observation::seen on', 'observation::segmenectomy', 'observation::several', 'observation::sizes', 'observation::skinfold', 'observation::slighlty', 'observation::slightly as', 'observation::standing as', 'observation::starting', 'observation::sternotomy changes', 'observation::stimulation', 'observation::stricture', 'observation::t2 fractures', 'observation::tip over', 'observation::tortousity', 'observation::tortuousity', 'observation::toward', 'observation::track signs', 'observation::traction', 'observation::tram', 'observation::traumatic but', 'observation::type tube', 'observation::upgrade', 'observation::vats', 'observation::vertically', 'observation::waxed', 'observation::weight', 'observation::which have', 'observation::widely', 'observation::x 3 cm right', 'observation::zonredistibution'] will be ignored
  warnings.warn(

\n===== fold=9 train=39690 test=4410 methods=6 =====
skip biomedclip_image_embedding fold 9
skip biomedclip_zero_shot_label_vector fold 9
run biomedclip_mlp_label_vector Supervised BiomedCLIP+MLP 14-logit label-space retrieval.
run kg_radgraph_entity_oracle Oracle KG retrieval from RadGraph observation/anatomy entity TF-IDF vectors.
run gnn_non_transformer_gnn_graphsage_topk500_label_vector GNN/KG predicted 14-label vector retrieval against training label vectors.
run gnn_transformer_gnn_transformerconv_topk100_label_vector GNN/KG predicted 14-label vector retrieval against training label vectors.

,fold,retrieval_method,relevance,k,num_queries,precision_at_k,recall_at_k,ap_at_k,mrr_at_k,ndcg_at_k,hit_at_k,description
0,0,biomedclip_image_embedding,label,1,4410,0.661224,0.000046,0.661224,0.661224,0.661224,0.661224,BiomedCLIP image embedding cosine retrieval.
1,0,biomedclip_image_embedding,label,5,4410,0.650431,0.000221,0.582878,0.747252,0.652501,0.872789,BiomedCLIP image embedding cosine retrieval.
2,0,biomedclip_image_embedding,label,10,4410,0.644059,0.000421,0.556626,0.752497,0.647318,0.912018,BiomedCLIP image embedding cosine retrieval.
3,0,biomedclip_image_embedding,label,50,4410,0.635029,0.002025,0.519673,0.755903,0.638090,0.975283,BiomedCLIP image embedding cosine retrieval.
4,0,biomedclip_image_embedding,label,100,4410,0.630256,0.003952,0.509479,0.756090,0.633290,0.987755,BiomedCLIP image embedding cosine retrieval.

## 9. Aggregate Retrieval Results and Paired Tests

In [9]:
retrieval_summary = pd.read_csv(OUTPUT_ROOT / "retrieval_10fold_summary.csv")
metric_cols = ["precision_at_k", "recall_at_k", "ap_at_k", "mrr_at_k", "ndcg_at_k", "hit_at_k"]
aggregate = retrieval_summary.groupby(["retrieval_method", "relevance", "k"])[metric_cols].agg(["mean", "std"]).reset_index()
aggregate.columns = ["_".join(c).strip("_") for c in aggregate.columns]
aggregate = aggregate.sort_values(["relevance", "k", "mrr_at_k_mean"], ascending=[True, True, False])
aggregate.to_csv(OUTPUT_ROOT / "retrieval_10fold_aggregate_summary.csv", index=False)
display(aggregate)

def bh_fdr(p_values):
    p = np.asarray(p_values, dtype=float)
    q = np.full_like(p, np.nan)
    mask = np.isfinite(p)
    if mask.sum() == 0:
        return q
    idx = np.where(mask)[0]
    order = np.argsort(p[mask])
    sorted_idx = idx[order]
    sorted_p = p[sorted_idx]
    ranks = np.arange(1, len(sorted_p) + 1)
    sorted_q = sorted_p * len(sorted_p) / ranks
    sorted_q = np.minimum.accumulate(sorted_q[::-1])[::-1]
    q[sorted_idx] = np.clip(sorted_q, 0, 1)
    return q

baseline_name = "biomedclip_image_embedding"
rows = []
for (method, relevance, k), cand in retrieval_summary[retrieval_summary["retrieval_method"] != baseline_name].groupby(["retrieval_method", "relevance", "k"]):
    base = retrieval_summary[
        retrieval_summary["retrieval_method"].eq(baseline_name)
        & retrieval_summary["relevance"].eq(relevance)
        & retrieval_summary["k"].eq(k)
    ]
    merged = cand.merge(base, on=["fold", "relevance", "k"], suffixes=("_candidate", "_baseline"))
    if merged.empty:
        continue
    for metric in metric_cols:
        c = merged[f"{metric}_candidate"].to_numpy(dtype=float)
        b = merged[f"{metric}_baseline"].to_numpy(dtype=float)
        valid = np.isfinite(c) & np.isfinite(b)
        if valid.sum() < 2:
            continue
        diff = c[valid] - b[valid]
        p_t = np.nan
        p_w = np.nan
        if stats is not None and np.nanstd(diff, ddof=1) > 0:
            p_t = float(stats.ttest_rel(c[valid], b[valid]).pvalue)
            try:
                p_w = float(stats.wilcoxon(diff[np.abs(diff) > 1e-12]).pvalue)
            except Exception:
                p_w = np.nan
        rows.append({
            "retrieval_method": method,
            "baseline": baseline_name,
            "relevance": relevance,
            "k": int(k),
            "metric": metric,
            "candidate_mean": float(np.nanmean(c[valid])),
            "baseline_mean": float(np.nanmean(b[valid])),
            "mean_diff": float(np.nanmean(diff)),
            "win_folds": int((diff > 0).sum()),
            "loss_folds": int((diff < 0).sum()),
            "paired_t_p": p_t,
            "wilcoxon_p": p_w,
        })
pairwise = pd.DataFrame(rows)
if not pairwise.empty:
    pairwise["paired_t_q"] = bh_fdr(pairwise["paired_t_p"])
    pairwise["wilcoxon_q"] = bh_fdr(pairwise["wilcoxon_p"])
pairwise.to_csv(OUTPUT_ROOT / "retrieval_pairwise_tests_vs_biomedclip_image.csv", index=False)
display(pairwise.sort_values(["relevance", "k", "metric", "mean_diff"], ascending=[True, True, True, False]).head(80))

,retrieval_method,relevance,k,precision_at_k_mean,precision_at_k_std,recall_at_k_mean,recall_at_k_std,ap_at_k_mean,ap_at_k_std,mrr_at_k_mean,mrr_at_k_std,ndcg_at_k_mean,ndcg_at_k_std,hit_at_k_mean,hit_at_k_std
72,gnn_transformer_gnn_transformerconv_topk100_la...,combined,1,0.986213,0.003835,0.000026,2.945923e-07,0.986213,0.003835,0.986213,0.003835,0.986213,0.003835,0.986213,0.003835
54,gnn_non_transformer_gnn_graphsage_topk500_labe...,combined,1,0.982744,0.009023,0.000026,3.425679e-07,0.982744,0.009023,0.982744,0.009023,0.982744,0.009023,0.982744,0.009023
90,kg_radgraph_entity_oracle,combined,1,0.980363,0.006129,0.000026,3.102870e-07,0.980363,0.006129,0.980363,0.006129,0.980363,0.006129,0.980363,0.006129
0,biomedclip_image_embedding,combined,1,0.975896,0.001747,0.000026,1.566876e-07,0.975896,0.001747,0.975896,0.001747,0.975896,0.001747,0.975896,0.001747
18,biomedclip_mlp_label_vector,combined,1,0.975850,0.001852,0.000026,1.499496e-07,0.975850,0.001852,0.975850,0.001852,0.975850,0.001852,0.975850,0.001852
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17,biomedclip_image_embedding,label,200,0.627279,0.001969,0.007753,6.484322e-05,0.502267,0.001982,0.751991,0.004099,0.629808,0.001954,0.996531,0.000659
35,biomedclip_mlp_label_vector,label,200,0.651491,0.002380,0.009017,6.699260e-05,0.530085,0.002667,0.751177,0.004777,0.651480,0.002400,0.994535,0.001192
53,biomedclip_zero_shot_label_vector,label,200,0.596465,0.002181,0.007796,8.982543e-05,0.454158,0.001863,0.723267,0.003486,0.597852,0.002159,0.996712,0.000711
89,gnn_transformer_gnn_transformerconv_topk100_la...,label,200,0.612382,0.162469,0.011611,1.123508e-03,0.580773,0.164450,0.622096,0.158606,0.612190,0.162264,0.698662,0.153666
71,gnn_non_transformer_gnn_graphsage_topk500_labe...,label,200,0.611474,0.162444,0.009771,2.107421e-03,0.590816,0.164911,0.620019,0.166092,0.611267,0.163201,0.688413,0.166838

,retrieval_method,baseline,relevance,k,metric,candidate_mean,baseline_mean,mean_diff,win_folds,loss_folds,paired_t_p,wilcoxon_p,paired_t_q,wilcoxon_q
326,gnn_transformer_gnn_transformerconv_topk100_la...,biomedclip_image_embedding,combined,1,ap_at_k,0.986213,0.975896,0.010317,10,0,7.004506e-05,0.001953,2.044558e-04,0.004469
218,gnn_non_transformer_gnn_graphsage_topk500_labe...,biomedclip_image_embedding,combined,1,ap_at_k,0.982744,0.975896,0.006848,9,1,4.053236e-02,0.083984,6.755394e-02,0.134176
434,kg_radgraph_entity_oracle,biomedclip_image_embedding,combined,1,ap_at_k,0.980363,0.975896,0.004467,8,1,7.175312e-02,0.019531,1.139608e-01,0.035274
2,biomedclip_mlp_label_vector,biomedclip_image_embedding,combined,1,ap_at_k,0.975850,0.975896,-0.000045,4,6,9.512660e-01,0.867188,9.723762e-01,0.911053
110,biomedclip_zero_shot_label_vector,biomedclip_image_embedding,combined,1,ap_at_k,0.973333,0.975896,-0.002562,2,7,3.938496e-02,0.054688,6.672546e-02,0.090587
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448,kg_radgraph_entity_oracle,biomedclip_image_embedding,combined,10,ndcg_at_k,0.990819,0.975288,0.015531,10,0,1.373067e-08,0.001953,7.129386e-08,0.004469
232,gnn_non_transformer_gnn_graphsage_topk500_labe...,biomedclip_image_embedding,combined,10,ndcg_at_k,0.977381,0.975288,0.002093,6,4,3.198216e-01,0.375000,4.212285e-01,0.476471
340,gnn_transformer_gnn_transformerconv_topk100_la...,biomedclip_image_embedding,combined,10,ndcg_at_k,0.977053,0.975288,0.001765,7,3,7.170344e-01,0.556641,8.033166e-01,0.656301
16,biomedclip_mlp_label_vector,biomedclip_image_embedding,combined,10,ndcg_at_k,0.975637,0.975288,0.000349,6,4,2.372614e-01,0.193359,3.302092e-01,0.275499
124,biomedclip_zero_shot_label_vector,biomedclip_image_embedding,combined,10,ndcg_at_k,0.973167,0.975288,-0.002121,0,10,2.283037e-04,0.001953,6.043333e-04,0.004469

## 10. nDCG-Ranked Retrieval Summary

In [10]:
aggregate_path = OUTPUT_ROOT / "retrieval_10fold_aggregate_summary.csv"
if aggregate_path.exists():
    aggregate_for_ndcg = pd.read_csv(aggregate_path)
    ndcg_ranked = aggregate_for_ndcg.sort_values(
        ["relevance", "k", "ndcg_at_k_mean", "mrr_at_k_mean"],
        ascending=[True, True, False, False],
    )
    ndcg_ranked_path = OUTPUT_ROOT / "retrieval_10fold_aggregate_summary_ranked_by_ndcg.csv"
    ndcg_ranked.to_csv(ndcg_ranked_path, index=False)
    display(ndcg_ranked.head(80))
    print("Saved", ndcg_ranked_path)
else:
    print("Run the aggregate-results cell first:", aggregate_path)

,retrieval_method,relevance,k,precision_at_k_mean,precision_at_k_std,recall_at_k_mean,recall_at_k_std,ap_at_k_mean,ap_at_k_std,mrr_at_k_mean,mrr_at_k_std,ndcg_at_k_mean,ndcg_at_k_std,hit_at_k_mean,hit_at_k_std
0,gnn_transformer_gnn_transformerconv_topk100_la...,combined,1,0.986213,0.003835,0.000026,2.945923e-07,0.986213,0.003835,0.986213,0.003835,0.986213,0.003835,0.986213,0.003835
1,gnn_non_transformer_gnn_graphsage_topk500_labe...,combined,1,0.982744,0.009023,0.000026,3.425679e-07,0.982744,0.009023,0.982744,0.009023,0.982744,0.009023,0.982744,0.009023
2,kg_radgraph_entity_oracle,combined,1,0.980363,0.006129,0.000026,3.102870e-07,0.980363,0.006129,0.980363,0.006129,0.980363,0.006129,0.980363,0.006129
3,biomedclip_image_embedding,combined,1,0.975896,0.001747,0.000026,1.566876e-07,0.975896,0.001747,0.975896,0.001747,0.975896,0.001747,0.975896,0.001747
4,biomedclip_mlp_label_vector,combined,1,0.975850,0.001852,0.000026,1.499496e-07,0.975850,0.001852,0.975850,0.001852,0.975850,0.001852,0.975850,0.001852
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,biomedclip_zero_shot_label_vector,label,1,0.609320,0.003980,0.000041,9.656996e-07,0.609320,0.003980,0.609320,0.003980,0.609320,0.003980,0.609320,0.003980
76,gnn_non_transformer_gnn_graphsage_topk500_labe...,label,1,0.606485,0.167323,0.000055,1.234762e-05,0.606485,0.167323,0.606485,0.167323,0.606485,0.167323,0.606485,0.167323
77,gnn_transformer_gnn_transformerconv_topk100_la...,label,1,0.602857,0.157343,0.000069,7.334882e-06,0.602857,0.157343,0.602857,0.157343,0.602857,0.157343,0.602857,0.157343
78,kg_radgraph_entity_oracle,label,5,0.781438,0.004126,0.000349,9.085424e-06,0.735257,0.005734,0.847494,0.004689,0.782860,0.004408,0.935850,0.004863
80,biomedclip_mlp_label_vector,label,5,0.651029,0.002565,0.000233,3.290402e-06,0.581410,0.002967,0.741983,0.005063,0.650920,0.003191,0.876054,0.003955

Saved /data/liangz2/openi/multi_kg/retrieval_report_generation_eval/retrieval_10fold_aggregate_summary_ranked_by_ndcg.csv

## Retrieval-Only Outputs

The primary outputs are saved under `/data/liangz2/openi/multi_kg/retrieval_report_generation_eval`:

- `retrieval_10fold_summary.csv`
- `retrieval_10fold_aggregate_summary.csv`
- `retrieval_pairwise_tests_vs_biomedclip_image.csv`
- `retrieval_10fold_aggregate_summary_ranked_by_ndcg.csv`
- per-method/fold query metrics and neighbor audit files under `retrieval_results/`

Use these files to select the best retrieval method/k settings for the report-generation notebook.